### ISSUE TITLE
Ladění ../uzivatel/osoba/create

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#100]
- [x] při pokusu vložit data vrátí error 500
- [x] prozatím skrýt pole rok narození, rok umrtí a rodné příjmení (v DB nechávat prázdné)
- [x] testovat duplicitu v databázi (nesmí být shoda jména + příjmení)
- [ ] @DanaKriv otestovat správné generování zkrácených verzí jmen

**Comment by motyc** [comment]
@DanaKriv Dano, prosím, prověř ty zkrácené verze (hlavně pro specifické případy, jako je více jmen, více příjmení, pomlčky ve jméně (Jean-Luc) a podobně.

**Comment by DanaKriv** [comment]
@motyc Zkusila jsem varianty dvě jména, dvě iniciály jména, kombinace jména a iniciály a naopak, dvě příjmení s mezerou a dvě příjmení s pomlčkou a vše je OK. Pokud  se zapíší dvě iniciály bez mezery nebo jméno s pomlčkou, ve zkrácené verzi se objeví pouze první písmeno, já bych to asi tolerovala.

**Comment by motyc** [comment]
@DanaKriv Díky za test. Já bych opravil pouze to jméno s pomlčkou, kde správné řešení pro `Novák, Jean-Luc` je `Novák, J.-L.`, nikoli pouze `Novák, J.`

**Comment by jnihnat** [comment]
jmeno s pomlckou opravene v #211
