### ISSUE TITLE
Přidat pole skos_mapping_relation do heslar_odkaz

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1000]
Do modelu `heslar_odkaz` přidat pole `skos_mapping_relation` (varchar(20); NOT NULL) s přípustnými hodnotami: 
- skos:closeMatch
- skos:exactMatch
- skos:broadMatch
- skos:narrowMatch
- skos:relatedMatch

Úprava XSD/XML - do `amcr:odkazType` přibude element: `<xs:element name="skos_mapping_relation" minOccurs="1" maxOccurs="1" type="xs:string"/> <!-- "{skos_mapping_relation}" -->` => připraveno v: #1101

**Comment by pesikj** [comment]
@motyc Odhad práce: 2 hodiny

**Comment by motyc** [comment]
@pesikj V pořádku, zaznamenávám k issue.

**Comment by pesikj** [comment]
@motyc Jaká je výchozí hodnota pro záznamy, které jsou již v databázi?
