### ISSUE TITLE
Fedora - doplnění jazyka pro heslářové položky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1001]
Z důvodu lepší standardizace by bylo dobré XML v některých případech doplnit o informaci o užitém jazyce. Definice je připravena zde: https://github.com/ARUP-CAS/aiscr-webamcr/pull/1100

Jde v principu o doplnění atributu `xml:lang` do některých elementů, které byly nově vyčleněny jako `amcr:langstringType`, potažmo `amcr:vocabType`. Data ("cs" nebo "en") jsou do nich doplněna staticky v komentářích v XSD.

**Comment by motyc** [comment]
@pesikj Podle dohody upraveno do nového pull requestu (#1100). Pro vocabType bude všude "cs", pro "langstringType" se bude vycházet z názvu pole (pokud končí "_en", je "en", jinak "cs")

**Comment by pesikj** [comment]
@motyc Jaká je adresa pro namespace "xml"?

**Comment by pesikj** [comment]
@motyc To je právě ale problém v namespace. Do popisu je potřeba vložit adresu registrovaného namespace, nikoli neexistující prefix.

**Comment by motyc** [comment]
@pesikj Ok, ono to ničemu nevadí tam vložit. Platí ty adresy výše.

Patrně v souvislosti s touto úpravou se rozbily přinejmenším tyto elementy (vypisuje se jen prázdný element):
- dokument/jazyk
- dokument/dokument_cast/komponenta/aktivita
- archeologicky_zaznam/dokumentacni_jednotka/komponenta/aktivita
- ../soubor/size_mb
- uzivatel/skupina
- uzivatel/hlidaci_pes
