### ISSUE TITLE
Ladění ../arch_z/detail

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#102]
- [x] chybí pole: organizace, specifikace data, uložení dokumentace, poznámka u komponenty, nejistá datace u komponenty, popis v tabulce s připojenými dokumenty (viz červeně v https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1077257469)
- [x] není implementována logika přidávání DJ (buď 1x Celek + Části, nebo pouze Sondy; zobrazují se i pro projektové akce nerelevantní možnosti - vše ostatní)
- [x] Komponenta se zobrazuje vždy dvakrát (http://192.168.254.24:8080/arch_z/detail/C-201442907A#):
![image](https://user-images.githubusercontent.com/20186892/120850934-69ff0480-c578-11eb-9a43-815e3b8ce44c.png)
- [x] u objektů nemá být specifikace povinná u předmětů ano - je to implementováno přesně opačně (mělo by odpovídat i označení pomocí *)
- [x] u ADB chybí možnost přidávat výškové body
- [x] tlačítko Upravit předměty je bez diakritiky
- [x] dokumentační jednotka - v popisu tlačítka - “Vytovřit” -> "Vytvořit"
- [x] nový PIAN - v popisu tlačítka - “Vytovřit pian”-> "Vytvořit PIAN"
- [x] nový PIAN - po kliknutí na “Vytovřit pian” zůstane na stránce tabulka “Nový pian” s aktivním polem výběru přesnosti - mělo by se zobrazit spíš view nadřazené DJ, ke které jsem PIAN vytvořil
- [x] nová dokumentační jednotka - po kliknutí na “Vytvořit jednotku” zůstane na obrazovce tabulka “Nová dokumentační jednotka”, a abych dále editoval DJ, kterou jsem právě vytvořil ji musím nejdříve v seznamu označit. Po kliknutí na “Vytvořit jednotku” by se měl zobrazit detail právě vytvořené DJ.
- [x] pokud kliknu u ADB na upravit, vrátí 404 (http://192.168.254.30:8080/adb/detail/C-202105930A-D01); přidávání funguje v pořádku

**Comment by pesikj** [comment]
Pole "Nejistá datace" je třeba vytvořit? U modelu ho nevidím.

**Comment by pesikj** [comment]
Přidaná pole u detailu
![image](https://user-images.githubusercontent.com/15179154/127353320-15545264-2c6b-4a75-a2b6-a79b5a202694.png)

**Comment by pesikj** [comment]
Zobrazení komponenty dvakrát je již zřejmě vyřešeno
![image](https://user-images.githubusercontent.com/15179154/127353590-d176ce02-20f5-4db4-ae88-6d32601cedc4.png)

**Comment by pesikj** [comment]
Omezen typ dokumentační jednotky
![image](https://user-images.githubusercontent.com/15179154/127395334-4b25b756-5c1a-49ab-ad12-6a18214ceab5.png)

**Comment by pesikj** [comment]
@motyc 
*nový PIAN - po kliknutí na “Vytovřit pian” zůstane na stránce tabulka “Nový pian” s aktivním polem výběru přesnosti - mělo by se zobrazit spíš view nadřazené DJ, ke které jsem PIAN vytvořil*
View na DJ neexistuje, má se tedy vytvořit?

*nová dokumentační jednotka - po kliknutí na “Vytvořit jednotku” zůstane na obrazovce tabulka “Nová dokumentační jednotka”, a abych dále editoval DJ, kterou jsem právě vytvořil ji musím nejdříve v seznamu označit. Po kliknutí na “Vytvořit jednotku” by se měl zobrazit detail právě vytvořené DJ.*
Zde ten samý dotaz. View neexistuje, má tedy být vytvořeno?

**Comment by motyc** [comment]
@pesikj 
ad view DJ - existuje jako součást http://192.168.254.24:8080/arch_z/detail/, jde o toto zobrazení DJ, na které by bylo dobré přesměrovat:
![image](https://user-images.githubusercontent.com/20186892/127496552-cf2762fc-ab9f-4a1a-bf66-0d954589314c.png)

Nové view určitě není třeba vytvářet.

**Comment by motyc** [comment]
@pesikj 
> Pole "Nejistá datace" je třeba vytvořit? U modelu ho nevidím.

Nene, jde o pole `komponenta.jistota`

**Comment by motyc** [comment]
> Zobrazení komponenty dvakrát je již zřejmě vyřešeno
> ![image](https://user-images.githubusercontent.com/15179154/127353590-d176ce02-20f5-4db4-ae88-6d32601cedc4.png)

Právě, že není vyřešeno, vždyť i zde na screenshotu je tam vždy celý nadpis komponenty zdvojený:
![image](https://user-images.githubusercontent.com/20186892/127497674-5f8c2aff-a566-4bdc-a414-bd862d31995a.png)

**Comment by pesikj** [comment]
Přidán formset na výškové body

@motyc Vycházel jsem ze struktury databáze. Některá pole jsou na úrovni databáze povinná, ale v modelu chyběly (Northing, Easting, Poradi). Přidal jsem je tedy do modelu. Pokud to má být jinak, dejte mi prosím vědět. (Ptal jsem se i Juraje, ale zatím mi neodpověděl.)

![image](https://user-images.githubusercontent.com/15179154/127635434-df9a305c-6ad5-4030-ab60-ca5111a330c1.png)

**Comment by motyc** [comment]
@pesikj
1) ident_cely je automaticky přidělovaný údaj (PID), skládající se z ID ADB a suffixu "-V####" (např. "-V0001"). Má se přidělovat automaticky příůstkově (stačí podle maxima) a nesmí jít editovat.
2) Northing a Easting by měly být podle zadání zrušeny, převedeny na geometrie a ukládány v poli geom. Zobrazovat by se souřadnice měly v S-JTSK (nadpisy sloupců by tedy měly být spíše X a Y) a implicitně se vyplňovat podle PIAN nadřazené dokumentační jednotky.
3) Poradi je nadbytečné, mělo být odstraněno při migraci.

Jak jsem už říkal někdy dříve na schůzce, mám dojem, že z migrace nebyla na databázi aplikována část kroků, která maže nadbytečné sloupce. Možná, by to bylo dobré dořešit (asi za pomoci @Najiva), ať Vás to tak nemate.

**Comment by pesikj** [comment]
1. Díky za vysvětlení. Našel jsem skript pro generování identů, ale pro výškový bod naprogramováno není, zřejmě je tedy potřeba jej dodělat (@Najiva napiš prosím, pokud někde je, ale prošel jsem kód pomocí PyCharmu a ta třída pro ident použitá není)
2. Ok, využiji sloupec geom.
3. Podívám se do migrací.

**Comment by pesikj** [comment]
@motyc Upravený formulář vypadá takto:

![image](https://user-images.githubusercontent.com/15179154/128636058-15ec9a5f-784c-4ee1-855c-0617db2ec3e0.png)

**Comment by pesikj** [comment]
Opravené komponenty

![image](https://user-images.githubusercontent.com/15179154/128640584-e78cd3e3-b4b2-4d68-b879-2db56cad9ef0.png)

**Comment by pesikj** [comment]
Opravená povinnost specifikace u objektů

![image](https://user-images.githubusercontent.com/15179154/128641220-08080b6e-eff3-4507-ad8d-1e2505e1c99a.png)

**Comment by pesikj** [comment]
Plus přidána diakritika u tlačítka Upravit předměty

**Comment by pesikj** [comment]
@motyc Formulář na přidání PIAN vypadá nyní takto, jak tam má být řešeno přidání pole geom?

![image](https://user-images.githubusercontent.com/15179154/128643469-a3154619-81c4-486e-adde-4f1998a68e6b.png)

**Comment by motyc** [comment]
@pesikj Pole geom obsahuje geometrii PIAN, která se zadává skrze mapu. Žádné takové pole by se tedy zobrazovat nemělo. Nebo jste to našel někde v zadání?

**Comment by motyc** [comment]
> @motyc Upravený formulář vypadá takto:
> 
> ![image](https://user-images.githubusercontent.com/15179154/128636058-15ec9a5f-784c-4ee1-855c-0617db2ec3e0.png)

Podobně jako u nálezů, stačí zobrazovat jeden řádek pro přidání nového VB. Jinak to vypadá v pořádku.

**Comment by pesikj** [comment]
![image](https://user-images.githubusercontent.com/15179154/129063572-dbc12e10-cc64-4d03-8912-a85b9f3bded9.png)

Upraveno, večer nahraji na server.

**Comment by motyc** [comment]
@pesikj @jnihnat Zatím tuším opravy nejsou nasazeny...

**Comment by pesikj** [comment]
@motyc 
Prošel jsem si druhou část a obecně mi není jasné, jak by mělo fungovat vytvoření PIAN. Formulář obsahuje pouze volbu přesnosti, ale k vytvoření nového záznamu PIAN je potřeba více dat. Je potřeba tyto hodnoty přidat do formuláře, nebo je převzít odjinud?

**Comment by motyc** [comment]
@pesikj Při vytváření PIAN se zaznamenává:
- geometrie do mapy (z ní se odvozuje řada údajů, jako je typ, list ZM atd.)
- přesnost do formuláře
- historie (automaticky)

Prosím buďte případně specifičtější, v čem jsou nejasnosti.

**Comment by pesikj** [comment]
Jde mi o formulář, který otevřu z menu na stránce arch_z/detail - položka Přidat nový PIAN:

![image](https://user-images.githubusercontent.com/15179154/132705499-4d8d4b5e-ad39-4d34-9d32-a3b2089b82b8.png)

Formulář nyní vypadá takto:

![image](https://user-images.githubusercontent.com/15179154/132705536-d63a464b-1b69-4050-a5bd-ef055eef3086.png)

Po odeslání hlásí 500 (jak je reportováno v issues). Důvodem je, že pro vytvoření nového PIAN nejsou dodány dostatečné informace - chybí geometrie do mapy (dle Vašeho popisu). Chci se tedy zeptat, jak tuto geometrii získat, jestli má být formulář na snímku upraven, či zda informaci vzít z nějakého navázaného záznamu?

**Comment by pesikj** [comment]
@motyc 
Tak beru dotaz zpět, už je mi jasné, že je potřeba využít tlačítka u mapy.

**Comment by motyc** [comment]
@pesikj Ano, je to tak. Jinak já jsem na ten error 500 přišel také v momentě, kdy kliknu na "Upravit PIAN", což by mělo jít u nepotvrzených (opět s využitím mapy). Problém to ale asi bude shodný.

**Comment by motyc** [comment]
@pesikj @jnihnat Výsledky dnešního testování (viz též nezaškrtnuté tasky v první commentu - upravil jsem aby odpovídalo aktuálnímu stavu):
- U komponenty stále chybí checkbox “Nejistá datace”
- Logika přidávání DJ je stále chybná (musí platit ve všech případech přidávání i editace):
-- u první DJ má být pouze volba “Celek akce” nebo “Sonda”
-- u každé další DJ na základě první pouze “Část akce” nebo “Sonda”
-- pokud změním první DJ z “Celek akce” na “Sonda”, musí se automaticky upravit i ostatní existující DJ (“Část” -> “Sonda”) a naopak
- Pokud nevyplním specifikaci u předmětu, hlásí pouze “Záznam se nepovedlo editovat” - je třeba být přesnější, uživateli vůbec nedojde, proč to nejde uložit.
- Tlačítko "Upravit předměty" je stále bez diakritiky.
