### ISSUE TITLE
Ladění ../dokument/detail

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#103]
- [x] http://192.168.254.24:8080/dokument/detail/C-DD-201800006 vrací error 500
- [x]  chybí pole Autoři, Řada, Let (viz červeně https://docs.google.com/spreadsheets/d/1LzGctLXR5-9MJl1rG75l6rKrJ7BvzXDGdSQ_uloyuSg/edit#gid=425649047)

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím na úkol č. 2.

**Comment by jnihnat** [comment]
Upravene formulare na Zapsat, detal aj edit.
