### ISSUE TITLE
Zajistit stabilitu testovacího serveru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1030]
Testovací server v poslední době často není dostupný. Je třeba zajistit jeho stabilitu jak kvůli probíhajícímu testování a dalším potřebám ARÚ, tak kvůli celkové robustnosti řešení - v produkci si něco takového nebudeme moc dovolit.

Je třeba odhalit příčinu pádů a přijmout patřičná opatření, vč. včasné reakce na pády ze strany Huld.

**Comment by sedmar** [comment]
Testovácí server opět běží. Příčina byla vyčerpání diskové kapacity testovacího serveru, což se může do budoucna stát znovu, jelikož systémový oddíl má velikost pouze 7,7 GB a v současné době je zaplněno 83%.

**Comment by motyc** [comment]
@sedmar Děkuji za rychlou informaci a vyřešení. Jaká velikost by byla ideální? Můžeme to asi významně navýšit.

Issue jinak přehazuji na test a nechám ho otevřené, abychom měli jedno místo, kde celkovou stabilitu můžeme odladit.

**Comment by sedmar** [comment]
Nepodařilo se mi zjistit co zabírá stávajících 14 GB z 17 GB, musí jít o nějaké skryté soubory, nebo smazané, ale stále držené některým procesem otevřené. Dle mého názoru by aktuální zaplněnost / měla být kolem ~8GB. Nejjednoduší v současné době je zvýšit kapacitu minimálně na 50GB a v případě, že se zaplněnost disku bude stále zvětšovat ze současných 14GB musí se najít co to způsobuje.

**Comment by motyc** [comment]
Nepůjde náhodou o místo využité Postgresem?

@MichalKminek @vojtakus Můžete prosím zajistit to navýšení? Celkem to spěchá, aby to nedělalo problémy.

**Comment by pesikj** [comment]
@motyc S místem na disku problém určitě je. Ale posledních 14 dní jsem žádné problémy neregistroval, vy ano?

**Comment by motyc** [comment]
@pesikj Nene, také jsem nic jiného teď nezaznamenal. Myslel jsem ale, že toto byla stejná příčina jako koncem května, než se to takto vysvětlilo. Jak jsem psal, nechám to tu otevřené a budeme vše sledovat. Důležité je, abychom vždy po pádu našli důvod a zajistili, že daný problém už nenastane.

**Comment by MichalKminek** [comment]
Aktualne je na oddilu postgres obsazeno 14 GB ze 40 GB. Obsazenost RAM je 6.5 GB ze 16 GB. Muzeme zvetsit oddil postgres. V root filesystemu jsem ve /var/crash nasel 2 dumpy ze May 22 11:14 a May 29 11:36. Nechal jsem logy odmazal jen binarni dumpy. Nyni root filesystem obsazeno 9 GB z 18 GB. Tento filesystem bohate postacuje v pripade potreby navyseni budeme pripojovat nove filesystemy kam potreba.

**Comment by motyc** [comment]
@MichalKminek Ok, děkuji. @pesikj Prosím, nešlo by něco dělat se těmi dumpy (směřovat je jinam), aby takto místo nemohly vyčerpat? Nebo je třeba jednou za den zkusit automaticky najít a přemístit? To by možná mohl pomoci i @MichalKminek 

Postgres myslím nyní není potřeba zvětšovat. Nevěděl jsem, jestli to není dohromady.

**Comment by vojtakus** [comment]
Crash dumpy jsou právě užitečné. Zřejmě v uvedených časech v květnu došla pamět. Můžeme tedy sledovat využití diskových oddílů a operační paměti a tak tomuto problému předejít.
V tuto chvíli je operační paměť využívána ani ne zpoloviny.

**Comment by sedmar** [comment]
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/40425887/cb91077c-65b6-45d8-bd74-210649699b6a)

Jak jsem již včera zmiňoval došlo k vyčerpání diskové kapacity na systémovém úložišti tj. mount point /, využívající úložiště /dev/mapper/cl_amcr--w--dev-root, toto bylo zaplněné ze 100 %, takže docházelo i k anomáliím v shellu. Po vymazání starých záloh db kleslo využití na 83 % a dnes je na 55 %, přes standardní linuxové nástroje (du), jsem včera neidentifikoval možnou příčinu, respektive kumulaci souborů, které toto způsobili. Nícméně je patrné, že od včera došlo k téměř 30 % poklesu využití zmíněného úložiště a co tento pokles způsobilo je otázkou.

**Comment by motyc** [comment]
@vojtakus Ja určitě neříkám, abychom dumpy nedělali. Jde jen o to je po vygenerování dát někam, kde je dostatek místa. Nyní patrně způsobily vyčerpání místa na serveru, který proto včera havaroval.

@sedmar Michal odstranil ty dumpy, proto asi došlo k poklesu. Na systémovém disku bychom prostě asi nejak potřebovali zajistit, aby se různé zálohy, dumpy atd. ukládaly na jiné vhodné místo a nevyčerpavaly prostředky potřebné pro beh sytemu.
