### ISSUE TITLE
Ladění ../dokument/zapsat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#104]
- [x] přidávám-li dokument přes projekt, C/M se stanovuje samo podle projektu
- [x] materiál - výběr by měl být omezen podle typu dokumentu (ne všechny jsou relevantní pro textové dok. a data; viz vztahy v hesláři)
- [x] datum zveřejnění se dovozuje automaticky podle hesláře organizací
- [x] chybí pole Autoři
- [x] v tomto kroku řada nadbytečných polí (zúžit viz https://docs.google.com/spreadsheets/d/1LzGctLXR5-9MJl1rG75l6rKrJ7BvzXDGdSQ_uloyuSg/edit#gid=1270349132); ostatní pole relevantní až pro detail/edit

**Comment by jnihnat** [comment]
@motyc - co prosim znamena bod 3?
datum zveřejnění se dovozuje automaticky podle hesláře organizací
Snazil som se dohedat nejakou relaci ale este v tom nemam taky prehled.
Dekuji

**Comment by svejci** [comment]
Dle mě je tímto myšleno, že dokumenty jsou podle smlouvy mezi Archeologickým ústavem a oprávněnými organizacemi zveřejňovány po lhůtě tří let od archivace dokumentu. Tuto smlouvu však nemají s ústavem uzavřeny všechny oprávněné organizace a proto by se datum zveřejnění mělo dovozovat automaticky podle toho, která organizace dokument do systému vložila a zda má uzavřenou výše zmíněnou smlouvu. D. Novák však určitě ještě upřesní.

**Comment by jnihnat** [comment]
este v tabulce "organizace" sem nasel sloupec mesicu_do_zverejneni a zverejneni_pristupnost. Predpokladam ze sa jedna o prvni uvedeny sloupec. pokud jo, jaka ma byt logika prosim.

**Comment by motyc** [comment]
@jnihnat Ano, to je ono. Dovozuje se to z hesláře organizací (každý dokument má organizaci uvedenu v poli `organizace`), a to z pole `mesicu_do_zverejneni`. Toto číslo (počet měsíců) se automaticky přičte k aktuálnímu datu při archivaci (posun do stavu 3) dokumentu.

**Comment by jnihnat** [comment]
field datum_zverejneni nastaveny na disabled. Pridane jeho dopocitavani pri archivaci.
Napada mne pak ci pri Vraceni se nema mazat. Tedka to bude ffungovat tak ze se nezmaze ale pri dalsi archivaci se prepise.

**Comment by motyc** [comment]
Díky za poznámku - jakmile je jednou vyplněné, už by se nemělo samo přepisovat (tj. při další archivaci ponechte původní hodnotu).

**Comment by jnihnat** [comment]
> 
> 
> Díky za poznámku - jakmile je jednou vyplněné, už by se nemělo samo přepisovat (tj. při další archivaci ponechte původní hodnotu).

upraveno
