### ISSUE TITLE
Oddělené instance Fedora pro jednotlivá prostředí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1046]
Z důvodu snazší správy infrastruktury bude nakonec každé prostředí AMČR mít též vlastní instanci Fedora na odpovídajícím serveru.

- [x] URL základního kontejneru bude vždy: `[base_url]/rest/AMCR` bez dalšího rozlišení, protože prostředí bude definováno již na úrovni base URL (https://fedora.aiscr.cz/, https://fedora-test.aiscr.cz/, https://fedora-dev.aiscr.cz/, https://fedora-tr.aiscr.cz/)
- [x] Při implementaci zajistit sklízení logů z docker kontejneru Fedory do odpovídající instance Kibany/Elasticsearch

Dílčí prostředí Fedory připraví ARÚ

**Comment by pesikj** [comment]
Odhad: 2 hodiny.

**Comment by pesikj** [comment]
@motyc Elasticsearch je na logy připraven, jejich zasílání z Fedory ale musí zajistit ARÚ.

**Comment by motyc** [comment]
Toto odkládám. Přepnutí prostředí proběhne během listopadu v součinnosti s ARÚ.

**Comment by motyc** [comment]
Zavírám to jako připravené, případné problémy po nasazení budeme řešit operativně.
