### ISSUE TITLE
Filtrace projektů - zadání formuláře

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#105]
Zadání zde (list filtrace): https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094

Před implementací je třeba dořešit:
- [x] - doplnit chybějící části
- [ ] - nastylovat (pokud by šly udělat ty navržené samostatně rozbalovací části, bylo by to skvělé; má #68)

(do budoucna nutno dořešit asynchronní hesláře a případně též výběr datumů pomocí daterange - zatím odloženo)

**Comment by Najiva** [comment]
1. django-filter nepodporuje DateRangeFiled

**Comment by Najiva** [comment]
1. nakonec se mi tam povedlo vlozit daterange. S tim ze ted filtr bude filtrovat projekty kde najde prunik z intervalem planovaneho zahajeni. Nepridal jsem tam validaci. Tj. uzivatel musi vybrat datum_do po datumu_od.
2. ok
3. ok

**Comment by motyc** [comment]
Ad 1 - ok
Ad 3 - pak je to chyba v důsledku toho, jak jsme to zpětně převáděli zpět do hlavní tabulky. Pole je třeba doplnit a správně migrovat (nyní v AMČR pole je).

**Comment by Najiva** [comment]
@motyc Existuje podobny soubor na filtr pro modely 3D nebo mam jit podle pas/3D?

**Comment by motyc** [comment]
Dále řešit v rámci #106, zde v podstatě duplicitní
