### ISSUE TITLE
Menu s dok. jednotkami se neomezeně prodlužuje (chybí scrollbar)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1053]
Viditelné např. u http://192.168.254.30:8080/arch-z/akce/detail/C-9113408A/dj/C-9113408A-D10

Mís to aby se zobrazilo rolovátko, menu se protáhne a s ním i mapa.

**Comment by pesikj** [comment]
@motyc Jaká má být maximální výška?

**Comment by motyc** [comment]
@pesikj Stejná, jako má mapa.
