### ISSUE TITLE
Stylování formulářů v projektech

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#106]
Souhrnně zadáno zde: https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=1808817771

**Comment by pkudela** [comment]
Hotovo, zaktualizovano ve vyse uvedenem dokumentu, jeste se ale ceka na par veci ze strany Juraje.

**Comment by motyc** [comment]
Jako celek zavírám, konkrétní nedodělky řešme zvlášť.
