### ISSUE TITLE
Chyba ve formulářích - všechna pole ano/ne jsou ano/ano

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1060]
Pole místo Ano a Ne obsahuje dvakrát Ano:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/fd3aad1c-ef4f-46b0-a00d-0b1d53713d4f)

http://192.168.254.30:8080/arch-z/akce/zapsat/C-202300512 (Odeslat ZAA jako NZ)
http://192.168.254.30:8080/arch-z/akce/detail/C-202300512A/dj/C-202300512A-D01 (Negativní DJ) aj.

**Comment by jnihnat** [comment]
tohle je jen spatny automaticky preklad. Az se dodela #558 opravim to v souborech.

**Comment by jnihnat** [comment]
opraveno
