### ISSUE TITLE
Problémy editace dokumentů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1064]
- [ ] http://192.168.254.30:8080/dokument/edit/C-200810918A-DT-08 (podobné chování i u (http://192.168.254.30:8080/dokument/edit/X-C-TX-000000007)- při pokusu uložit změny níže se nic nestane:

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/cdf47813-5fab-4ba2-9cdd-a6be0b34ca03)

**Comment by pesikj** [comment]
@motyc Na aktuální verzi se žádný z popsaných problémů nevyskytuje, prosím o opětovný test.

**Comment by motyc** [comment]
@pesikj Já jsem to dopoledne, tj. na aktuální verzi znovu zkoušel a stav byl stále stejný. Když kliknu na uložit, tak se jen znovu načte formulář, ale nic se neuloží. Vždy to dělám tak, že vyplním všechna pole a pak zkusím uložit. Chybovou hlášku to žádnou nedává.

**Comment by motyc** [comment]
@pesikj Tak otestováno znovu a problém je zjevně s polem dokument_extra_data.region - pokud je v něm něco vyplněno, záznam se neuloží. Jinak vše ok.

**Comment by motyc** [comment]
### Test 

Problém vůbec nezmizel (testováno na: http://192.168.254.30:8080/dokument/edit/C-200810918A-DT-08). Naopak se zdá, že nyní úplně přestalo fungovat ukládání změn, bez ohledu na pole Region.

Navíc pak http://192.168.254.30:8080/dokument/zapsat/do-arch-z/X-C-9000000046A - nejde zapsat - v konzoli: `An invalid form control with name='region' is not focusable. <select name=​"region" class=​"selectpicker form-control" data-multiple-separator=​";​ " data-live-search=​"true" required id=​"id_region" tabindex=​"-98">​…​</select>​`

**Comment by pesikj** [comment]
@motyc Vím o tom, oprava už je hotová, jen není nasazená. Novou verzi budu deployovat během dne.

**Comment by pesikj** [comment]
@motyc Opraveno, viz.

http://192.168.254.30:8080/dokument/detail/X-C-TX-000000049
http://192.168.254.30:8080/dokument/detail/C-200810918A-DT-08

**Comment by motyc** [comment]
Editace a běžný zápis ok, ale nefunguje stále ten zápis přes akci: http://192.168.254.30:8080/dokument/zapsat/do-arch-z/X-M-9000000009A

**Comment by pesikj** [comment]
@motyc  Myslím, že u Pian to půjde ověřit i přes ty problémy se zoomem a validace geometrie už funguje. Zkoušel jsem to teď a ident zůstal stejný.
