### ISSUE TITLE
Triggery předělat na signály v Django

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1067]
Řešení triggerů na úrovni DB přináší spoustu komplikací. Triggery by bylo vhodné přepsat tak, aby stejné úkony dělalo přímo Django a triggery pak můžeme zrušit.

- [x] `delete_connected_documents` (archeologicky_zaznam) - při implementaci je třeba opravit chybu:
-- V triggeru chybí tam jedna negace. Nyní se `dokument_cast` smaže tehdy, pokud má nějakou komponentu a nemá žádnou neident. akci. Mělo by se to přitom mazat jen tehdy, pokud nemá ani jedno. Také si nejsem jistý zda náhodou nezáleží na pořadí obou příkazů k mazání, protože když by se jako první aplikovalo mazání na `dokument_cast` a až poté na `dokument`, vazba mezi `archeologicky_zaznam` a `dokument` už nemusí existovat.
- [x] `delete_connected_komponenta_vazby_relations` (komponenta_vazby)
- [x] `delete_connected_komponenty_relations` (komponenta) - možná řeší integrita v Django?
- [x] `delete_related_dokument_cast` (dokument) - možná řeší integrita v Django?
- [ ] `delete_related_komponenta` (dokument_cast, dokumentacni_jednotka) - možná řeší integrita v Django?
- [x] `delete_related_neident_dokument_cast` (dokument_cast) - možná řeší integrita v Django?
- [x] `delete_related_neident_vedouci` (neident_akce) - možná řeší integrita v Django?
- [x] `delete_related_soubor` (dokument, samostatny_nalez) - pozor, toto se nemá aplikovat u projektu, protože by to bylo konfliktní s `prevent_project_deletion`
- [x] `delete_unconfirmed_pian` (dokumentacni_jednotka)
- [x] `deleted_records_history` (archeologicky_zaznam, auth_user, dokument, externi_zdroj, pian, projekt, samostatny_nalez) - při implementaci upravit tak, aby:
-- se do pole historie.uzivatel vložil ten, kdo záznam skutečně maže (nyní univerzálně amcr@arup.cas.cz)
-- se záznam do historie vložil, poté se vygenerovala nová metadata.xml a poté se může vše vč. záznamů v tabulce historie smazat (verze zůstane ve Fedoře a nebudeme zbytečně držet sirotky v DB - nyní sirotci zůstávají)
-- `delete_history_spoluprace` (uzivatel_spoluprace) a `deleted_soubor_history` (soubor) - sloučit s předchozím - bude se používat univerzální řešení pro historii popsané výše
- [x] `prevent_project_deletion` (projekt)

**Comment by pesikj** [comment]
Odhad: 40 hodin

**Comment by motyc** [comment]
@pesikj Aby toto šlo relevantně testovat, musí být z DB odstraněny původní triggery, jinak to nedává smysl.

**Comment by pesikj** [comment]
@motyc Triggery jsem smazal.

**Comment by motyc** [comment]
### Test v0.3.5z66
- [ ] `delete_connected_documents` (archeologicky_zaznam) - toto v původním smyslu nefunguje vůbec; po zralé úvaze navrhuji funkci úplně zrušit, protože pokud bychom to měli implementovat správně podle původního záměru, přinášelo by to asi více chyb a zmatků, než užitku; stačí když se do `dokument_cast.archeologicky_zaznam` dá null při smazání souvisejícího arch-z, což se patrně nyní děje (prosím jen prověřit a obdobně řešit i pro vztah přes `dokument_cast.projekt`); případnou údržbu dat a odstraňování sirotků budeme řešit zásahem archiváře, pokud to bude potřeba
- [ ] `delete_related_dokument_cast` (dokument) - nejde testovat - např. http://192.168.254.30:8080/dokument/detail/C-TX-193903973 vůbec nejde smazat
- [ ] `delete_related_komponenta` (dokument_cast, dokumentacni_jednotka)
-- dokument_cast - ok
-- dokumentacni_jednotka - arch-z (akci i lokalita) - po smazání DJ zůstane sirotek v komponenta_vazby, komponenta a všech podřazených záznamech
- [ ] `delete_related_soubor` (dokument, samostatny_nalez)
-- dokument - nejde testovat - např. http://192.168.254.30:8080/dokument/detail/C-TX-193903973 vůbec nejde smazat
-- samostatny_nalez - ok
- [ ] `delete_unconfirmed_pian` (dokumentacni_jednotka)
-- nefunguje, např. nepotvrzený PIAN N-1223-000000067 zůstal i po smazání poslední připojené DJ. Mělo by jít o ekvivalent tohoto spínaného mazáním DJ:
```plpgsql
DELETE FROM pian
WHERE pian.id = old.pian AND pian.ident_cely NOT LIKE 'N-%'
AND NOT EXISTS (
  SELECT FROM dokumentacni_jednotka
  WHERE pian.id = dokumentacni_jednotka.pian
);
``` 
-- při smazání celého arch-z dojde ke smazání potvrzených PIAN, nikoli nepotvrzených bez vazeb (tak nám zmizel např. http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/P-1214-100348), ale nepotvrzené se zachovají (např. http://192.168.8.33:8080/rest/AMCR-test/record/N-1413-316707) - asi někde bude otočená podmínka
- [ ] `deleted_records_history` (archeologicky_zaznam, auth_user, dokument, externi_zdroj, pian, projekt, samostatny_nalez)
-- akce, externi_zdroj, pian, projekt, samostatny_nalez  - ok
-- uzivatel_spoluprace a soubory - sice se DEL záznam nevytvoří, ale nechat být, není to tolik potřeba (tedy ok)
-- lokalita - nefunguje nebo nejde testovat - blokováno #1086
-- auth_user - nejde testovat - blokováno #1420
-- dokument - nejde testovat - např. http://192.168.254.30:8080/dokument/detail/C-TX-193903973 vůbec nejde smazat
-- po uložení metadat a smazání původního záznamu se nemaže související obsah z `historie_vazby` ani `historie`, v DB tedy zůstávají sirotci

**Comment by pesikj** [comment]
@motyc 

> -- nefunguje, např. nepotvrzený PIAN N-1223-000000067 zůstal i po smazání poslední připojené DJ. Mělo by jít o ekvivalent tohoto kódu spínaného mazáním DJ:

Ale v tom dotazu je
```sql
AND pian.ident_cely NOT LIKE 'N-%'
```

Tj. NEmaže to piany, které začínají `N-`.

**Comment by motyc** [comment]
@pesikj Koukám na to a máte pravdu, v původním SQL byla chyba... Cílem je mazat nepotvrzené PIAN (i podle názvu funkce), to "NOT" tam tedy být nemá.

**Comment by pesikj** [comment]
@motyc Ok, tak už je mi to jasné, díky.

**Comment by pesikj** [comment]
@motyc 
> -- po uložení metadat a smazání původního záznamu se nemaže související obsah z historie_vazby ani historie, v DB tedy zůstávají sirotci

To se týká kterého modelu?

**Comment by motyc** [comment]
@pesikj Asi jsem to nezkoušel úplně všude, ale mám pocit, že se to nedělo téměř nikde asi s jednou výjimkou. Ale musel bych to znovu vyzkoušet, nebo by to mohlo jít zjistit vyhledáním sirotků z poslední doby.

**Comment by motyc** [comment]
@pesikj Chtěl jsem většinu signálů otestovat na jednom záznamu (http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000000042A), který však nejde smazat. Systém zahlásí neurčitou hlášku: `Záznam nebyl smazán kvůli vazbám na další záznamy.` Jenže smazání by podle správných pravidel v daném případě nic blokovat nemělo a vše by mělo být ošetřeno v rámci signálů.

Potřeboval bych zjistit, co smazání blokuje a opravit to. Záznam, ale prosím na testu fakticky nemažte! Musel bych celou situaci simulovat znovu a dá to celkem práci vše vytvořit.

**Comment by motyc** [comment]
@pesikj Ukazuje se, že problém nebude jen ext. odkazu, ale asi i v tom mazání nepotvrzených PIAN, protože smazat mi nejde ani akce http://192.168.254.30:8080/arch-z/akce/detail/C-202000945A, kde žádný odkaz není.

**Comment by pesikj** [comment]
@motyc Našel jsem chybu u mazání nepotvrzeného Pianu. S EZ jsem na problém při testování nenarazil. Opravu jsem na vašem záznamu netestoval, protože mám podezření, že bych ho mohl smazat.

**Comment by motyc** [comment]
### Test v0.3.5z94
Zůstalo toto, ostatní snad již vyřešeno:
- [ ] `delete_related_komponenta` (dokument_cast, dokumentacni_jednotka)
-- dokument_cast - při smazání části dokumentu napřímo je vše ok, ale po smazání dokumentu jako celku zůstane sirotek v komponenta_vazby, komponenta a všech podřazených záznamech; mám takové tušení, že problém je v této podmínce: https://github.com/ARUP-CAS/aiscr-webamcr/blob/d5afcc565b2500704270a5d8a9d5cdaa91293bed/webclient/dokument/signals.py#L81C36-L81C36 (nevím, proč by se to mělo aplikovat jen v případě mazání modelů...)
- [ ] `deleted_records_history` Nemůžu otestovat smazání auth_user kvůli #1494 - sice to nějak proběhne, ale v DB záznam zůstane, takže zatím nelze potvrdit.

**Comment by motyc** [comment]
### Test v0.3.5z118
Snad už poslední drobnost:

- [ ] při mazání celého dokumentu, který má nějaké komponenty, zůstane sirotek v tabulce "komponenta_vazby" (např. `SELECT * FROM komponenta WHERE komponenta_vazby = 414629`)
