### ISSUE TITLE
Upravit obsah polí geom_system

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1069]
Do polí `geom_system` (tabulky `pian` a `samostatny_nalez`) místo "wgs84" a "sjtsk" ukládat "4326" a "5514". Bude to standardnější a jasnější.

Je třeba správně doladit i automatickou aktualizaci nepřesných převodů 5514 -> 4326 (dosud značeno sjtsk*) - viz též #387.

SQL migrace opraveny v https://github.com/ARUP-CAS/aiscr-webamcr/pull/1070

**Comment by jiri-bartos-huld** [comment]
Jeste chybi dodelat django migraci https://github.com/ARUP-CAS/aiscr-webamcr/pull/1293

**Comment by jiri-bartos-huld** [comment]
@pesikj tato funkcionalita je pouze jako draft MR, prosim jeste nenasazovat nemam to otestovane, resim problemy s VPN-dnes jsme o tom mluvili.

**Comment by motyc** [comment]
Otestuji po opravě #1126

**Comment by motyc** [comment]
Nemůže být k testu, když to stále čeká na merge #1293

**Comment by pesikj** [comment]
@motyc Ano, migrace aplikovaná není, protože já vždy opravuji initial_migration. Jinak se z migrací stane nepřehledná bramboračka podobně jako z SQL migrací. Bude to aplikováno při novém deploymentu databáze.

**Comment by motyc** [comment]
@pesikj Rozumím a je fajn, že to řešíte. Jenže kvůli tomu nám teď nejdou přidávat PIAN. Je tedy třeba v databázi alespoň ručně smazat původní constraint. Navíc tedy pokud platí implementace v https://github.com/ARUP-CAS/aiscr-webamcr/commit/4d5df9047626756791baaf0109b07a26da37d215, tak tam není ošetřena ten případ s hvězdičkou a nevidím ani ten constraint pro samostatný nález. Možná ale něco přehlížím.
