### ISSUE TITLE
Optimalizace dotazu migrace ktere jsou pomale

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#107]
- [ ]  update historie h set typ_zmeny = 4 where id in (select his.id as hid from historie his join historie_vazby as hv on hv.id=his.vazba where hv.typ_vazby='archeologicky_zaznam' and his.typ_zmeny=111);
- [ ] update historie h set typ_zmeny = 4 where id in (select his.id as hid from historie his join historie_vazby as hv on hv.id=his.vazba where hv.typ_vazby='archeologicky_zaznam' and his.typ_zmeny=7);

**Comment by motyc** [comment]
Jedná se o nedodělanou migraci zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/1740ec27d6f2c889bec874a9b5765c027555e7f6/migrace/6_migrace_dalsi.sql#L89

**Comment by motyc** [comment]
Po dohodě s @pbartosova v kódu odkomentováno a budeme sledovat chování.
