### ISSUE TITLE
Layout formularu - chybejici pole, komponenty atd.

### ISSUE THREAD

**Issue by pkudela** [ARUP-CAS/aiscr-webamcr#108]
- [ ] https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=1372775774  dle navrzeneho formulare by mela byt moznost v dolni casti formulare vlozit projektovou dokumentaci, vlozil jsem tam stejne html, jako mame v oznameni v 2.kroku + souvisejici linky na js a css, ale html tohoto elementu se nevygeneruje tak jak ma
- [x] https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=1906889513  dle navrzeneho formulare chybi 2 pole -> "Vedouci projektu" a "Termin odevzdani". Vedouci projektu jsem doplnil, ale chybi funkcionalita tlacitka "+" (je to odkaz, takze se to pokusim udelat ja) a "Termin odevzdani" uplne chybi.
- [ ] https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=2144585002
"Termin odevzdani" uplne chybi (jde o projekt/edit/).
- [ ] https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094 prosim zde nektera pole chybi, nektera jsou v jinem formatu, nez je navrzeno v dokumentu, cili misto 2 poli je to jedno pole, vetsinou u datumu. V souboru filter.py jsem zakomentoval co kde chybi, takze na tyto dana mista prosim doplnit fields. @Najiva prosim dohodni se s @motyc pokud by nejaky field nesel udelat ve formatu tak jak je v excel dokumentu, aby to @motyc pripadne zmenil, abych to az vse bude doplnene mohl podle toho dodelat. Jo u vyberu podle historie mi prijde, ze jsou tam nejaka pole navic.
- [ ] https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=917077993 dle navrzeneho formulare ma byt v titulku karty "do stavu XXX", stav chybi, takze prosim doplnit

**Comment by motyc** [comment]
Ad 1 - pokud by byl problém dělat to v jednom kroku, lze to nechat k nahrání až po zápisu projektu
Ad 3 - formulář oznamovatel může zůstat k editaci samostatně (má asi samostatné view); jen jsme v zadání vycházeli z podoby /projekt/create

**Comment by motyc** [comment]
@pesikj zde bod 1 patrně popisuje důvod, proč to přestalo fungovat; jak jsem zmiňoval, to vkládání souborů tam být nemusí

**Comment by motyc** [comment]
@svejci Ondro, ta chybějící pole můžeš rozepsat tady; stejně se to již v tomto issue částečně řeší.

**Comment by svejci** [comment]
Chybějící pole ve formulářích (všechny formuláře k nahlédnutí ve složce Sdileno_komentare_Huld/Navrh_formulare - chybějící pole označena červeně na listu detail):
**Samostatné nálezy**: https://docs.google.com/spreadsheets/d/1EaMlKchCjaVRDwGLYDytvEHgSEPfCqFmkxOAw9PaEQ8/edit#gid=2095380239
Souř. systém; Šířka, Délka, Poloha; Předáno organizaci; Evidenční číslo; Nález předán; Přístupnost.
**Dokumenty**: https://docs.google.com/spreadsheets/d/1LzGctLXR5-9MJl1rG75l6rKrJ7BvzXDGdSQ_uloyuSg/edit#gid=425649047
Autoři; Řada; Let.
**Akce**: https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1077257469
Organizace; Specifikace data; Uložení dokumentace; Výškové body (celá část pro jejich popis). Poznámka (u Komponenty), pole Popis v tabulce s Dokumenty.
**Knihovna 3D**: https://docs.google.com/spreadsheets/d/1WVSCrVVFGZduhZ9tbDCeea9c7wyvgCYMWORe8k1AzYg/edit#gid=1525832777
Země; Region; Šířka; Délka

**Comment by motyc** [comment]
Vše z tohoto vlákna rozepsáno do konkrétní issue (podle URL) pro lepší přehlednost. Toto zavírám.
