### ISSUE TITLE
Fedora - mazání záznamů a změny ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1082]
- [x] je třeba ošetřit situaci, kdy se dočasný ident_cely mění, tj. převádí z dočasného na trvalý (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/732) + převod projektových akcí na samostatné a naopak; v takové chvíli by mělo (vzorově aplikováno na http://192.168.8.33:8080/rest/AMCR-dev/record/X-C-000000002):
-- dojít k vytvoření nového kontejneru pod novým ident_cely (to je ok a děje se)
-- uložení nové kopie souvisejících souborů (po případném přejmenování) do nového kontejneru + k aktualizaci jejich metadat v DB
-- propojení záznamů pomocí
--- `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/isReplacedBy> 'https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely_new]'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely_old]"`
--- `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/replaces> 'https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely_old]'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely_new]"`
-- vložení typu pomocí: `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'renamed'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]"`
-- přidání starého záznamu v members do deleted pomocí: `curl -u [user]:[heslo] -X POST -H "Slug: [ident_cely]" "https://fedora.aiscr.cz/rest/[server-name]/model/deleted/member" -H "Content-Type: text/turtle" --data-binary "@member.ttl"`
--- `member.ttl`: `@prefix ore: <http://www.openarchives.org/ore/terms/> . <> ore:proxyFor <info:fedora/[server-name]/record/[ident_cely_old]> .`
- [x] při smazání záznamu z DB neodstraňovat celý kontejner z Fedory (např. `https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]`), ale pouze přidat záznam v members do deleted a doplnit značku do metadat. Tím zajistíme plné verzování a možnost vracet se i ke smazaným záznamům (bude to lepší, než uchovávat nicneříkající tombstones). Udělat pomocí:
-- `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'deleted'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]"`
-- `curl -u [user]:[heslo] -X POST -H "Slug: [ident_cely]" "https://fedora.aiscr.cz/rest/[server-name]/model/deleted/member" -H "Content-Type: text/turtle" --data-binary "@member.ttl"`
--- `member.ttl`: `@prefix ore: <http://www.openarchives.org/ore/terms/> . <> ore:proxyFor <info:fedora/[server-name]/record/[ident_cely]> .`
- [x] Při smazání souboru (u libovolného parenta, tj. projektu, dokumentu, sam. nálezu):
-- rovněž doplnit „deleted“ do metadat ve Fedora pomocí `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'deleted'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]/file/[uuid]"` a soubor ve Fedoře zachovat
-- výjimkou je smazání souboru ihned po nahrání ještě v dropzone - v tomto případě by se měl soubor zcela odstranit i z Fedory pomocí `curl -u [user]:[heslo] -X DELETE "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]/file/[uuid]"`

**Comment by pesikj** [comment]
@motyc Prosím o test, v lokálním prostředí jsem toto nebyl schopen otestovat kvůli request timout z Fedory.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5g)
**Změna ident_cely**
- [ ] Projekty - nefunguje schvalování oznámených (nic neudělá)
- [ ] Dokumenty - https://github.com/ARUP-CAS/aiscr-webamcr/issues/1077
- [ ] Lokality - nefunguje (http://192.168.8.33:8080/rest/AMCR-dev/record/X-C-L000000002) - nový kontejner pro [C-L9001060](http://192.168.8.33:8080/rest/AMCR-dev/record/C-L9001060) se ani nevytvořil, odkazy se nepřidaly atd.
- [ ] PIAN - nefunguje (http://192.168.8.33:8080/rest/AMCR-dev/record/N-1121-000000017) - nový kontejner pro [P-1121-100062](http://192.168.8.33:8080/rest/AMCR-dev/record/P-1121-100062) vznikl, ale nevzniklo propojení, nepřidal se typ atd.
- [ ] Samostatné akce - totéž jako u PIAN (http://192.168.8.33:8080/rest/AMCR-dev/record/X-C-9000000005A -> http://192.168.8.33:8080/rest/AMCR-dev/record/C-9723781A)
- [ ] Externí zdroje - totéž jako u PIAN (http://192.168.8.33:8080/rest/AMCR-dev/record/X-BIB-0734054 -> http://192.168.8.33:8080/rest/AMCR-dev/record/BIB-0000028)

**Mazání**
- [ ] Projekty - nejdou smazat
- [ ] Při smazání souboru (u libovolného parenta, tj. projektu, dokumentu, sam. nálezu) rovněž doplnit „deleted“ do metadat ve Fedora pomocí `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'deleted'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]/file/[uuid]"` a soubor ve Fedora zachovat (vzor zde: http://192.168.8.33:8080/rest/AMCR-dev/record/C-202300519/file/5a25bfa7-a93d-49cb-ad95-e7638bee6153)
- [ ] Chybí řešení pro situace, kdy se maže parent záznam (např. smazaní ADB či PIAN při mazání DJ nebo celé akce)
- [ ] Externí zdroje - nejdou smazat (test na http://192.168.254.30:8080/ext-zdroj/detail/X-BIB-0734072)
- [ ] Uživatel - mazání vrací chybu: http://192.168.254.30:8080/admin/uzivatel/user/3275/delete/
- [ ] Heslo - po smazání se ve Fedoře nic nezmění (http://192.168.8.33:8080/rest/AMCR-dev/record/HES-001436)
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9113971A ani http://192.168.254.30:8080/arch-z/akce/detail/C-9113971A/dj/C-9113971A-D01 nejde smazat - blokuje přítomnost ADB?

**Comment by motyc** [comment]
@pesikj https://github.com/ARUP-CAS/aiscr-webamcr/issues/1082#issuecomment-1616573372 je aktualizováno, nic se nakonec nezměnilo, jen přibylo upozornění na nutnost řešení v dropzone

**Comment by pesikj** [comment]
@motyc

>  Projekty - nefunguje schvalování oznámených (nic neudělá)

Opraveno (http://192.168.254.30:8080/projekt/detail/C-202300525)

> Dokumenty

Opraveno (http://192.168.254.30:8080/dokument/detail/C-200810918A-DT-01)

> PIAN - nefunguje (http://192.168.8.33:8080/rest/AMCR-dev/record/N-1121-000000017) - nový kontejner pro [P-1121-100062](http://192.168.8.33:8080/rest/AMCR-dev/record/P-1121-100062) vznikl, ale nevzniklo propojení, nepřidal se typ atd.

Opraveno (http://192.168.8.33:8080/rest/AMCR-test/model/pian/member/N-1142-000000016)

>  Samostatné akce - totéž jako u PIAN (http://192.168.8.33:8080/rest/AMCR-dev/record/X-C-9000000005A -> http://192.168.8.33:8080/rest/AMCR-dev/record/C-9723781A)

Opraveno (http://192.168.8.33:8080/rest/AMCR-test/model/samostatny_nalez/member/C-202012119-N00010)

Pozor na to, že zde kontrolujete odkazy v DEV verzi Fedory, je potřeba využívat test.

>  Externí zdroje - totéž jako u PIAN (http://192.168.8.33:8080/rest/AMCR-dev/record/X-BIB-0734054 -> http://192.168.8.33:8080/rest/AMCR-dev/record/BIB-0000028)

Opraveno (http://192.168.8.33:8080/rest/AMCR-test/model/ext_zdroj/member/X-BIB-000000010)

>  Projekty - nejdou smazat

Opraveno

>  Chybí řešení pro situace, kdy se maže parent záznam (např. smazaní ADB či PIAN při mazání DJ nebo celé akce)

Je tam vazba restrict, takže jsem přidal chybovou zprávu.

>  Externí zdroje - nejdou smazat (test na http://192.168.254.30:8080/ext-zdroj/detail/X-BIB-0734072)

Opraveno.

>  Uživatel - mazání vrací chybu: http://192.168.254.30:8080/admin/uzivatel/user/3275/delete/

Opraveno.

>  Heslo - po smazání se ve Fedoře nic nezmění (http://192.168.8.33:8080/rest/AMCR-dev/record/HES-001436)

Opraveno (http://192.168.8.33:8080/rest/AMCR-test/record/HES-001437)

> nejde smazat - blokuje přítomnost ADB?

Ano, přidána chybová zpráva

>  Při smazání souboru (u libovolného parenta, tj. projektu, dokumentu, sam. nálezu):

Opraveno.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5t)
- [ ] - vložení typu pomocí: `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'renamed'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]"` - zde jsem zapomněl zdůraznit, že má jít o `ident_cely_old` (funguje to tedy ok, jen se typ všude přidává k novému záznamu místo starého)
- [ ] všude jsem omylem fixně uvedl `https://fedora.aiscr.cz/` - měla by se tam vkládat skutečná základní URL
- [ ] údaje spojené s nahrazením dočasného ident trvalým se propisují až po poměrně dlouhé době (1-2 min). Z čeho to vyplývá a není to zbytečně dlouho?
- [ ] pokud při změně ident záznam nemá soubory, v http://192.168.254.30:8080/admin/django_celery_results/taskresult/ je výsledek evidován jako FAILURE; věcně však proběhlo vše v pořádku - nemělo by to i v těchto případech vracet SUCCESS, aby nás to nemátlo při analýze logů?
- [ ] záznamy v http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member se mohou vytvářet zdvojeně; např. pro X-C-TX-000000007 je tam jak http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/X-C-TX-000000007, tak http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/9644d89e-3a23-4dac-b551-0d0f34b05bcb; problém bude asi jen v testovacích datech, ale mělo by se to při vytváření kontrolovat, jako to děláme jinde
- [ ] Je třeba ošetřit situaci, pokud vytvořím záznam a hned jej smažu, tj. vejdu se do intervalu 30 s - nyní vrací "FedoraError" (což zamezí chybě, ale není pro uživatele srozumitelné), stačilo by asi přidat nějaké smysluplné upozornění, že má uživatel počkat (případně prodiskutovat možnosti).
- [ ] Smazání souboru - testováno u http://192.168.8.33:8080/rest/AMCR-test/record/X-M-202376640/file/0fc856e5-6947-43b0-9694-e5963ae779db - došlo ke smazání souboru z Fedory (a to vč. tombstone), měl by se jen označit jako "deleted" (zadání viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/1082#issuecomment-1616573372)
- [ ] Chybí řešení pro situace, kdy se maže parent záznam (např. smazaní ADB či PIAN při mazání DJ nebo celé akce) - restrict sice funguje, ale zmiňovaná chybová hláška se mi nezobrazí (test na: http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000000011A/dj/X-C-9000000011A-D01)

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5u)
- [ ] Nevím, jestli s tím jde něco dělat, ale stále se v odkazu zobrazuje jako base URL `https://fedora.aiscr.cz/` místo `http://192.168.8.33:8080/`
- [ ] Vytváření zdvojených záznamů v http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member přetrvává. Nyní např. vznikly dva záznamy zároveň při schválení projektu:
-- http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/X-C-202250787
-- http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/74945f59-74b6-4ea4-944d-ea2df05c2c64
- [ ] při schválení projektu se všechny soubory duplikovaly: http://192.168.8.33:8080/rest/AMCR-test/record/C-202300533/file (oznámení je tam dokonce třikrát)
- [ ] pokud schválím projekt a poté ihned kliknu na smazání souboru v projektové dokumentaci, dostanu hlášku, že se to povedlo, ke smazání vše ve skutečnosti nedojde; může souviset s předchozím bodem.
- [ ] http://192.168.254.30:8080/dokument/model/detail/X-C-3D-000000014 - nejde smazat (testováno i u dalších záznamů jiných typů a nejde smazat nic; jen problikne a nic se nestane)
- [ ] Je třeba ošetřit archivaci, když se ident nemění (např. http://192.168.254.30:8080/arch-z/akce/detail/C-9003462A) - stále nefunkční

**Comment by pesikj** [comment]
@motyc 

> Nevím, jestli s tím jde něco dělat, ale stále se v odkazu zobrazuje jako base URL

S tím nejde dělat nic, protože IP adresa ze serveru nefunguje.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/d43e9c40-c072-4142-9f29-d1b8094ba4fe)

**Comment by motyc** [comment]
### Testování v0.3.5z18
Nyní kompletně rozbité. Při schválení http://192.168.254.30:8080/projekt/detail/M-202300206 se do http://192.168.8.33:8080/rest/AMCR-test/record/X-M-000000007 nic nedoplnilo a http://192.168.8.33:8080/rest/AMCR-test/record/M-202300206 vůbec neobsahuje soubor s metadaty ani odkaz na původní záznam. Mazání nelze testovat vůbec, protože nic nejde mazat (viz #1299).

**Comment by pesikj** [comment]
@motyc Na aktuání verzi jsem prováděl test zde: http://192.168.254.30:8080/dokument/detail/C-TX-202300012

Soubor je přejmenovaný a přijde mi, že i kontejner je OK. Jen prosím pozor na ti, že přejmenování souboru je **asynchronní**, tj. neprojeví se hned, ale až po skončení asynchronní operace. Pokud je to problém, jde to udělat synchronně, ale u větších souborů nebo většího množství menších souborů to bude pomalé. Spíše bych navrhoval informovat uživatele nějakou informační zprávou.

**Comment by pesikj** [comment]
@motyc Pro projekty to dle mého taky vypadá dobře: http://192.168.254.30:8080/projekt/detail/C-202300559

**Comment by motyc** [comment]
@pesikj Ano, potvrzuji, že uvedené příklady takto vypadají zcela v pořádku. Ještě to otestuji, ale myslím, že by to mohlo být ok.

**Comment by motyc** [comment]
@pesikj Testování issue jako takového ale stále ještě brání tento bug: #1299

Teď jsem to zkoušel a povedlo se mi smazat jen Externí zdroj, jinak v podstatě nic smazat nejde.

**Comment by motyc** [comment]
### Test v0.3.5z66
V základu ok, jsou tam jen tyto menší chyby:
- [ ] rovněž doplnit „deleted“ do metadat ve Fedora pomocí curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'deleted'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]/file/[uuid]" a soubor ve Fedoře zachovat - _také není implementováno - soubor se správně zachová, ale nedostane patřičný příznak (test na http://192.168.8.33:8080/rest/AMCR-test/record/X-C-000000015/file/4d8ef1d6-cad8-4bcc-a33a-f56544e17562); "deleted" se doplní jen v případě smazání celého nadřazeného záznamu, což v principu není špatně, ale je třeba mít i tu první variantu, kdy smažu jen soubor_
- [ ] výjimkou je smazání souboru ihned po nahrání ještě v dropzone - v tomto případě by se měl soubor zcela odstranit i z Fedory pomocí `curl -u [user]:[heslo] -X DELETE "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]/file/[uuid]"` - _toto není implementováno - údaje se pouze smažou z DB, ale ve Fedoře soubor zůstane (test na: http://192.168.8.33:8080/rest/AMCR-test/record/X-C-000000015/file/e6bd66ea-65c3-4ae5-8d93-e81bad4249f4)_
- [ ] Při archivaci http://192.168.8.33:8080/rest/AMCR-test/record/X-C-L000000014 vznikly duplicitní záznamy http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/X-C-L000000014 a http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/345ceb30-ad96-4c71-9b80-601014da9669

**Comment by pesikj** [comment]
@motyc 
>  Při archivaci http://192.168.8.33:8080/rest/AMCR-test/record/X-C-L000000014 vznikly duplicitní záznamy http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/X-C-L000000014 a http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/345ceb30-ad96-4c71-9b80-601014da9669

Opraveno, ale nevím, jak to zkontrolovat, v navázaných záznamech odkaz na duplicitu nevidím.

**Comment by motyc** [comment]
@pesikj Je to třeba odchytit ve Fedroře. Jde to takto: http://192.168.8.33:8080/rest/fcr:search?condition=fedora_id%3DAMCR-test%2F*%2Fdeleted%2F*&condition=modified%3E%3D2023-12-22T14%3A44%3A00.000Z&offset=0&max_results=100 (po příhlášení přes admin účet Fedory a patřičné úpravě časové podmínky)

**Comment by motyc** [comment]
### Test v0.3.5z81
Původní chyby jsou odstraněné. Narazil jsem ale ještě na nějaké podivnosti:
- [ ] Při generování nového PIAN katastru vznikl základní záznam správně (http://192.168.8.33:8080/rest/AMCR-test/record/P-1324-900088/fcr:versions/20240117174339), ale ihned poté byl jakoby přejmenován (http://192.168.8.33:8080/rest/AMCR-test/record/P-1324-900088/fcr:versions/20240117174344) s tím, že do "replaces" se vložil odkaz na http://fedora.aiscr.cz:8080/rest/AMCR-test/record/ (což je nesmysl) a do deleted generický záznam: http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/97d691bb-205f-451f-95da-e8bb84aa722b. Myslím, že se to děje proto, že PIAN vzniká rovnou jako potvrzený a aplikace se s tím neumí správně poprat, tj. snaží se udělat stejnou operaci, jako by existoval předchozí nepotvrzený PIAN.
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f8ac3761-bbf3-412a-bbaf-2ab153f4d885)
- [ ] Historicky se nám tak do http://192.168.8.33:8080/rest/AMCR-test/record dostaly odkazy na různé záznamy, zpravidla projekty a PIAN. U projektů se zdá, že se to tam vytvořilo již dávno a nadále se to neděje. U PIAN je asi vysvětlení výše, ale zajímavé je, že nyní tam odkaz už nevznikl. Prosím tedy každopádně o prověření. Abychom to mohli nějak rozumně stopovat, tak jsem teď odstranil dané položky z Fedory, stav před smazáním je ale na screenshotu níže:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/b3e172a6-444a-4608-a891-eb74c578f22c)
