### ISSUE TITLE
Fedora - problém s duplicitami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1086]
Při smazání a opětovném vytvoření některých záznamů vznikne duplicita. Řešit tak, že pokud kontejner již existuje a zároveň je v `http://fedora.aiscr.cz/rest/AMCR-test/model/deleted`, tak na něj navázat:
- [x] upravit type ve Fedora pomocí:
-- `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "DELETE DATA {<> <http://purl.org/dc/terms/type> 'deleted'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]"`
-- `curl -u [user]:[heslo] -i -X PATCH -H "Content-Type:application/sparql-update" -d "INSERT DATA {<> <http://purl.org/dc/terms/type> 'restored'}" "https://fedora.aiscr.cz/rest/[server-name]/record/[ident_cely]"`
- [x] odstranit odkaz z model/deleted pomocí:
-- `curl -u [user]:[heslo] -X DELETE "https://fedora.aiscr.cz/rest/[server-name]/model/deleted/member/[ident_cely]"`
-- `curl -u [user]:[heslo] -X DELETE "https://fedora.aiscr.cz/rest/[server-name]/model/deleted/member/[ident_cely]/fcr:tombstone"`
- [x] aktualizovat metadata.xml a standardně doplňovat soubory
- [x] pokud záznam již existuje a není ve `http://fedora.aiscr.cz/rest/AMCR-test/model/deleted`, vrátit chybu do aplikace.

Tím zajistíme plnou perzistenci i funkčnost aplikace.

**Comment by pesikj** [comment]
@motyc V rámci řešení je třeba:

- Upravit logiku vytváření kontejnerů - přidat vytvoření projektové akce jako speciální případ.
- Implementovat všechny nové request pro zadané případy.

Odhad pracnosti: 8 hodin.

**Comment by motyc** [comment]
@pesikj Zadání aktualizováno podle dohody, odhad potvrzuji.

**Comment by motyc** [comment]
@pesikj Nelze testovat do opravy #1299

**Comment by motyc** [comment]
### Test v0.3.5z66
Testováno na http://192.168.254.30:8080/arch-z/akce/detail/C-201774404A a http://192.168.254.30:8080/arch-z/akce/detail/C-201018541A. Náhrada v základu proběhla dobře, ale:
- [ ] http://192.168.8.33:8080/rest/AMCR-test/record/C-201774404A/metadata/fcr:metadata vůbec nekoresponduje s aktuálním záznamem http://192.168.254.30:8080/arch-z/akce/detail/C-201774404A - je to nějaká kombinace původních dat a nových, jak kdyby tam zůstali nějací sirotci, kteří se na to sami připojili
- [ ] po obnovení akce nebyl odstraněn záznam http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/C-201774404A (viz druhý bod prvního příspěvku)
- [ ] pokud záznam již existuje a není ve `http://fedora.aiscr.cz/rest/AMCR-test/model/deleted`, vrátit chybu do aplikace. - _není ošetřeno_

**Comment by pesikj** [comment]
@motyc
>  pokud záznam již existuje a není ve http://fedora.aiscr.cz/rest/AMCR-test/model/deleted, vrátit chybu do aplikace.

Ošetřil jsem to u akcí a samostatných nálezů. Může se to vyskytnout ještě někde?

**Comment by motyc** [comment]
@pesikj Ono by bylo nejlepší, kdyby se to tak chovalo obecně, protože do budoucna může podobná situace nastat např. pokud importujeme nějaké záznamy a poté by došlo k jejich smazání. Když k nim pak dojde řada ident, došlo by ke kolizi ve Fedoře.

**Comment by pesikj** [comment]
@motyc Je potřeba řídit zobrazení varování v aplikaci a zamezit uložení, takže úplně obecné řešení bych tady nedělal, znamenalo by to přepsání všech pohledů, které provádějí zápis záznamu.

**Comment by motyc** [comment]
@pesikj Ok, tak to nasaďte k otestování tam, kde to máte hotové a pak se dohodneme, jak to nejlépe přenést na ostatní situace. Jde o to, že ty importy prostě neumíme předvídat, ale zatím to není klíčové, protože stejně je nemáme implementované.

**Comment by motyc** [comment]
### Test v0.3.5z81
Opravy nebyly moc úspěšné. Jsme v podstatě tam, kde jsme byli, kromě jediného bodu. Chování je stejné pro akce i samostatné nálezy.

- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-201807042A - po zápisu nového záznamu se nevytvořila nová metadata, je tam poslední verze vytvořená při smazání původního záznamu (http://192.168.8.33:8080/rest/AMCR-test/record/C-201807042A/metadata/fcr:metadata)
- [ ] pokud záznam již existuje a není ve `http://fedora.aiscr.cz/rest/AMCR-test/model/deleted`, vrátit chybu do aplikace. - _není ošetřeno_ (nyní testováno na http://192.168.254.30:8080/arch-z/akce/detail/C-202011835A - smazal jsem akci, smazal http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/C-202011835A a následně akci vytvořil znovu; aplikaci to nijak nevadilo, a to bez ohledu na to, zda existuje nebo neexistuje tombstone)
- [ ] http://192.168.254.30:8080/arch-z/lokalita/detail/C-N9000125 - záznam se po smazání hned zase obnovil sám od sebe - http://192.168.8.33:8080/rest/AMCR-test/record/C-N9000125 - chyba zde asi ale bude spíše v chybě v procesu mazání - děje se stále (nyní opakovaný test na http://192.168.254.30:8080/arch-z/lokalita/detail/C-N9000600)

**Později**
- [ ] pokud záznam již existuje a není ve `http://fedora.aiscr.cz/rest/AMCR-test/model/deleted`, vrátit chybu do aplikace - domluvit se, jak zajistit alespoň test pro ostatní typy záznamů, tj.:
-- archeologicky_zaznam/lokalita
-- dokument
-- adb
-- let
-- pian
-- projekt
-- ext_zdroj
-- heslo
-- ruian_kraj
-- ruian_katastr
-- ruian_okres
-- uzivatel
-- osoba
-- organizace

**Comment by pesikj** [comment]
@motyc 

>  pokud záznam již existuje a není ve http://fedora.aiscr.cz/rest/AMCR-test/model/deleted, vrátit chybu do aplikace

Tady jste ale testoval něco úplně jiného. V zadání bylo zkontrolovat, jestli záznam není ve stavu deleted, tj. jestli nedošlo chybě při předchozím mazání a záznam tam nezůstal viset. Pokud jde o kontrolu, zda existuje tombstone, tak jak bychom měli z databáze poznat, že tam má být? Informace o smazaném záznamu jsou pouze ve Fedoře.

**Comment by motyc** [comment]
@pesikj Potvrzuji, že ta hotová část řešení funguje pro akce i SN

**Comment by pesikj** [comment]
@motyc 

> -- akce - funguje pouze pro situace, kdy není ani tombstone; nalezení tombstone ale neznamená, že záznam v deleted existuje (znamená, že někdy existoval a jen po něm něco zbylo). Aplikace se pak chová, jako by vše bylo ok, ale už dělá různé návazné chyby, kterým tímto testem musíme předejít.

Takže pokud existuje tombstone, má aplikace vypsat stejnou chybu?

**Comment by motyc** [comment]
@pesikj Ano.

**Comment by motyc** [comment]
@pesikj Bohužel to nefunguje. Pro http://192.168.8.33:8080/rest/AMCR-test/model/deleted/member/C-202300062A - vrátí tombstone. http://192.168.254.30:8080/arch-z/akce/detail/C-202300062A se přesto podařilo zapsat znovu. Pro PAS také žádná změna, tam to nic nehlásí, ani když není ani ten tombstone.

**Comment by pesikj** [comment]
@motyc Tak mi prosím napište, jak to otestovat. Já smazal záznam v AMČR a pak smazal deleted záznam ve Fedoře a při pokusu o vytvoření nového záznamu hlásí aplikace chybu, a to jak u PAS, tak u akcí. Nevím o jiném způsobu, jak vyvolat situaci, kdy by tato chyba měla nastat.
