### ISSUE TITLE
Náhled se generuje příliš velký

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1090]
Např. zde dobře vidět: http://192.168.254.30:8080/pas/detail/C-202111309-N00004

Omezit na max. 100 px (delší hrana) již při generování.

**Comment by pesikj** [comment]
@motyc Náhled se generuje dynamicky ve chvíli, kdy je potřeba, proto není ukládán. Je to efektivnější řešení než dělat desítky requestů do Fedory.

**Comment by motyc** [comment]
@pesikj Po telefonu dohodnuto:
- [ ] Protože originální obrázky mohou být opravdu velké (stovky MB), nelze je vždy generovat ad hoc - je tedy třeba uložit náhledy buď v lokáním úložišti Djanga, nebo ve Fedoře. V prvním případě je však třeba dát pozor na to, aby nedošlo k vymazání úložiště při každém nasazení nové verze, resp. obnově kontejneru.
- [ ] Pokud to nebude problém, velikost náhledu zvětšit např. na 800 px (delší strana) a zobrazení v tabulkách řešit nastavením max-widht a max-heigth na 100 px v CSS. Pokud by to bylo komplikované, uděláme pro tento bod samostatné issue.

**Comment by pesikj** [comment]
@motyc U nově nahraných souborů je to vyřešeno. Náhled se vkládá jako `thumb` a po otevření modalu se zobrazí `orig`. U dříve nahraných souborů není náhled vygenerovaný, ale předpokládám, že to na testovací verzi nevadí a stačí otestování s novými soubory.

**Comment by motyc** [comment]
@pesikj Ano, ty dříve nahrané netřeba řešit. Musíme pak to pak jen nějak zohlednit při nalévání dat v #38.

Jinak k tomu modalu - ono i tam je to stahování orig trošku ošemetné, protože v systému mám některé originály (i TIFF) o velikostech stovek MB. Proto jsem navrhoval do thumb ukládat soubor v nějaké kompromisní velikosti použitelné i pro modal, a ten pak ještě přes CSS zmenšovat pro tabulky. Relevantní řešení by ale bylo i dělat nějaké dvě velikosti thumb (ve fedoře by vznikl třeba `*/thumb_small` a `*/thumb` (to ale spíš nadhazuji jako variantu).

Pak ještě také zbyla ta otázka, zda bychom byli schopni dělat náhledy i pro PDF. Šlo by to, případně jak je to pracné? (myšlen by byl náhled vytvořený z první strany)

**Comment by pesikj** [comment]
@motyc 

>  Relevantní řešení by ale bylo i dělat nějaké dvě velikosti thumb (ve fedoře by vznikl třeba */thumb_small a */thumb (to ale spíš nadhazuji jako variantu).

To je určitě možné. Dokážete říct, jak velký by měl být náhled do modalu?

**Comment by motyc** [comment]
Dal bych to na těch 800 px pro delší stranu.

**Comment by motyc** [comment]
### Test v0.3.5z116
V principu funguje dobře, jen je třeba doladit:

- [ ] při změně ident_cely nadřazeného záznamu se náhledy nepřenesou do nového kontejneru
- [ ] náhledy se neaktualizují po nahrání náhrady souboru (SN a dokumenty)
- [ ] je třeba upravit podmínku pro tabulku s výpisem dokumentů, aby se náhledy zobrazovaly nejen pro obrázky, ale také pro PDF (vygenerované jsou, ale neukážou se) - asi to bylo opomenuto jen pro: http://192.168.254.30:8080/dokument/vyber
- [ ] http://192.168.254.30:8080/projekt/detail/M-202205326 - vrací `Reverse for 'download_thumbnail_large' with arguments '('', '', '')' not found. 1 pattern(s) tried: ['soubor/stahnout\\-nahled\\-velky/(?P<typ_vazby>[^/]+)/(?P<ident_cely>[^/]+)/(?P<pk>[0-9]+)\\Z']`
