### ISSUE TITLE
Pridat check ze pri dokonceni oznameni jsou vsechny soubory nehrane spravne.

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#11]
Tohle by mel byt javascript check, tak aby bylo jasne ze uzivatel nahral vsechno co chtel.

**Comment by jnihnat** [comment]
@motyc aka je tu prosim presna poziadavka. Momentalne je check pridany po kliknuti na Dokoncit oznameni.
![image](https://user-images.githubusercontent.com/57906106/132337238-aee20c78-d023-4bd4-96fd-21d8ce202eec.png)

**Comment by motyc** [comment]
Není, takto to vypadá ok, jen to asi nebylo nasazené, protože na mne nic nevyskočilo.

**Comment by pesikj** [comment]
@motyc Dnes večer jsem dělal deploy, tak to můžete otestovat znovu.

**Comment by motyc** [comment]
Funguje, zavírám.
