### ISSUE TITLE
Optimalizace prostředí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1117]
Relativně často se mění názvy kontejneru s AMČR (patrně kvůli swarm režimu dockeru). Komplikuje to práci, protože hromadné generování pro Fedoru při tom spadne. Pády jsou patrně způsobeny přečerpáním paměti (více než 95 % obsazeno), což healthcheck vyhodnotí jako problém.

Musíme zjistit, co obsazuje paměť a zda je to nutné. Mohou to např. být i vznikající logy. Zdá se ale, že paměť je poměrně dost obsazena trvale. Hlavní podezřelý je Elasticserch - bude nutno promyslet vhodnou rotaci logu, jeho čištění a případně limity.

**Comment by pesikj** [comment]
@motyc 

elasticsearch je omezen na jedno procesorové jádro a 2 GB RAM.
