### ISSUE TITLE
Prohozený výpis souřadnic ve formuláři v PAS

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1126]
Po testování upřesňuji, je tam nějaký větší problém.
- [ ] http://192.168.254.30:8080/pas/zapsat
-- S-JTSK se vkládá z mapy správně
-- WGS-84 se vkládá z mapy opačně
- [ ] http://192.168.254.30:8080/pas/detail/C-202105414-N00001
-- S-JTSK i WGS-84 se zobrazuje opačně
- [ ] http://192.168.254.30:8080/pas/edit/C-202105414-N00001
-- S-JTSK se zobrazuje opačně, ale vkládá z mapy správně
-- WGS-84 se zobrazuje i vkládá z mapy opačně

Problém je myslím jen v zobrazení, v DB to vypadá v pořádku.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z16)
Všechny varianty jsou nyní naprosto chybně, a to ještě více, než původně. Vypisují se úplně nesmyslné souřadnice, někdy jsou souřadnice duplikované v obou sloupcích apod. Nemá smysl důsledně testovat a jednotlivě reportovat, chyby jsou zřejmé a je třeba to předělat.

**Comment by jiri-bartos-huld** [comment]
Melo by dojit k prekmenovani popisku souradnic: spravne poradi je sirka, delka
spravne by melo byt:   "Sirka (N/X)" a "Delka (E/Y)"
dnes je "Delka (E/X)" a "Sirka (N/Y)"


Po testování upřesňuji, je tam nějaký větší problém.
- [ ] http://192.168.254.30:8080/pas/zapsat
-- S-JTSK se vkládá z mapy správně
-- WGS-84 se vkládá z mapy opačně
- [ ] http://192.168.254.30:8080/pas/detail/C-202105414-N00001
-- S-JTSK i WGS-84 se zobrazuje opačně
- [ ] http://192.168.254.30:8080/pas/edit/C-202105414-N00001
-- S-JTSK se zobrazuje opačně, ale vkládá z mapy správně
-- WGS-84 se zobrazuje i vkládá z mapy opačně

Problém je myslím jen v zobrazení, v DB to vypadá v pořádku.

**Comment by jiri-bartos-huld** [comment]
@pesikj  prosim zmenit v prekladu popisky na  "Sirka (N/X)" a "Delka (E/Y)"

**Comment by motyc** [comment]
@jiri-bartos-huld @pesikj To jsem teď opravil v administraci, už je to opačně.

**Comment by motyc** [comment]
### Test v0.3.5z28
Začínám z toho být poněkud v Jiříkově vidění, protože opravy v tomto issue vše spíše dále rozbíjejí, byť ne tak viditelně, ale o to vážněji. Primární problém je v tom, co se považuje za X a Y ve WGS-84 (4326) a v S-JTSK (5514) při planárním zobrazení.

> Melo by dojit k prejmenovani popisku souradnic: spravne poradi je sirka, delka
spravne by melo byt: "Sirka (N/X)" a "Delka (E/Y)" pro X a Y v epsg:5514 plati abs(x)<abs(y) a nebo lepe X<Y<0
dnes je "Delka (E/X)" a "Sirka (N/Y)" to je dost nesourode

Pokud vezmeme např. tento bod: https://maps.app.goo.gl/A6xnJSiES574edXj9
Tak pro něj platí:
- délka = E (14.326992) = X (-748951,46) - v obou případech jde o pohyb západovýchodním směrem
- šířka = N (50.122756) = Y (-1038201,47) - v obou případech jde o pohyb severojižním směrem

Nedává tedy smysl kombinovat N/X a E/Y, protože bychom do jednoho pole dávali zcela protichůdné osy a uživatele by to jen mátlo. Měli bychom se držet toho, jak souřadnice uvádí všechny GIS aplikace, a to je právě mnou uváděný, navíc bychom měli dodržovat pořadí, které odpovídá definicím v PostGIS DB, kde je správná syntaxe `POINT(E N)`, resp. `POINT(X Y)` podle definice výše.
 
Problém je v celkovém chaosu v zobrazování a ukládání souřadnic:

http://192.168.254.30:8080/pas/zapsat
- [ ] - zadám `detector_system_coordinates` = WGS-84 -> kliknu do mapy -> zobrazí se `detector_coordinates_x` = 50,0086890; `detector_coordinates_y` = 14,1651968 -> uložím a do `samostatny_nalez.geom` správně zapíše `POINT(14.1651968 50.008689)`, ale do `samostatny_nalez.geom_sjtsk` se vloží `POINT(-1049159.52 -762181.61)`, tedy obrácené souřadnice
- [ ] - zadám `detector_system_coordinates` = S-JTSK -> přímo do polí vložím `detector_coordinates_x` = -762181,61; `detector_coordinates_y` = -1049159,52 -> bod na mapě se zobrazí správně -> uložím a do `samostatny_nalez.geom` správně zapíše `POINT(14.1652047 50.0086933)` a rovněž v `samostatny_nalez.geom_sjtsk` se správně vloží `POINT(-762181.61 -1049159.52)`
- [ ] - zadám `detector_system_coordinates` = WGS-84 -> kliknu do mapy -> zobrazí se `detector_coordinates_x` = -1055673,88; `detector_coordinates_y` = -756801,96 -> uložím a do `samostatny_nalez.geom` správně zapíše `POINT(14.2521216 49.9574161)`, ale do `samostatny_nalez.geom_sjtsk` se vloží `POINT(-1055673.88 -756801.96)`, tedy obrácené souřadnice

Chybám výše pak odpovídá i zobrazení přes detail:
- http://192.168.254.30:8080/pas/detail/M-202004181-N00011
- http://192.168.254.30:8080/pas/detail/M-202004181-N00012
- http://192.168.254.30:8080/pas/detail/M-202004181-N00013

A chování editace:
- http://192.168.254.30:8080/pas/edit/M-202004181-N00011
- http://192.168.254.30:8080/pas/edit/M-202004181-N00012
- http://192.168.254.30:8080/pas/edit/M-202004181-N00013

Je bezpodmínečně nutné, abychom se shodli na dodržování syntaxe podle PostGIS (tj. E=X a N=Y), tomu odpovídala implementace v aplikaci a ideálně i označování v kódu. Myslím, že i do budoucna bude extrémně matoucí, pokud se všude v kódu souřadnicím X bude říkat Y a naopak.

Pokud tedy mám pospat cílový stav, mělo by to být tak, že:
- v aplikaci budou pole v tomto pořadí "Délka (E/X)" (`detector_coordinates_x`) a "Šířka (N/Y)" (`detector_coordinates_y`)
- tomu budou odpovídat všechna označení "x" a "y" v souborech:
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/dokument/views.py
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/pas/templates/pas/detail.html
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/core/utils.py
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/dokument/templates/dokument/coor_model_3D.html
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/dokument/templates/dokument/coor_doc.html
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/pas/views.py
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/mapa_doc.js
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/pas/templates/pas/coor.html
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/mapa_pas.js
-- https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/dokument/forms.py
(případně i dalších pokud se týká)

Jinak se z toho zmatku nikdy nevymotáme a vždy s tím budou problémy.

**Comment by pesikj** [comment]
@motyc @jiri-bartos-huld 

Navrhuji zorganizovat společný call a toto issue na něm prodiskutovat.

**Comment by motyc** [comment]
@pesikj  @jiri-bartos-huld Za sebe s tím nemám problém. Stačí dohodnou termín.

**Comment by jiri-bartos-huld** [comment]
@pesikj  @motyc 
Dobry den, omlouvam po nasem hovoru sem onemocne, nyni se pomalu vracim. Pojme zrychlene dohodnout pravidla:

1./Aby vse bylo jednoznacne, souradnice se budou oznacovat: x1,x2,x3 nezavisle na souradnicovem systemy
2./poradi souradnic vychazi podle toho jak jsou definovane ve WKT geometrii pri zapisu/cteni z databaze
ukazka: POINT (x1 x2)  dle https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry
LINESTRING (x1 x2,x1 x2)
3./Uprava: Na vsech urovnich python/javascript se odstani oznaceni X/Y a nahradi se x1,x2. Tam kde bude potreba na JS provest prohozeni souradnic (zapis leaflet) oznacime promenou koncovkou  "_leaf"
4./Priznam, ze jsem nasel jeste jeden atyp a to je vyskovy bod kde je northing/easting/niveleta. Je tam pouzity virtualni model a jeho zmena muze hodne rozbit a zmenu tohoto jsem ani puvodne nenacenoval, tak prosim toto zatim vynechat a resit plosne body a pak az doresit tento atyp.
5./pro souradnicovy system wgs-84/4326 plati
x1=elip.delka 
x2=elips.sirka
pro CR pak plati x2>X1, obe souradnice jsou jak vzdy kladne
zapis WKT: Point(17.218494, 50.168927)
zapis Leaflet: LatLng(50.168927, 17.218494) //zde to musi zustat v poradi x2,x1 protoze takto funguje leaflet
6./pro souradnicovy system sjtsk 5514 plati https://epsg.io/5514
x1=-Y skutecny S-JTSK (mensi kladna souradnice)
x2=-X skutecny S-JTSK
pro CR pak plati x2<X1, obe souradnice jsou jak vzdy zaporne
zapis WKT: POINT(-762181.61 -1049159.52)
zapis leaflet neni

prosim o potvrzeni

**Comment by motyc** [comment]
@jiri-bartos-huld Samozřejmě nemoc nepočká. Je dobře, že už je Vám lépe.

ad 4 - pokud vím, tak tam to funguje dobře. Takže pokud to není třeba přepisovat, nemusíme do toho sahat a stačí např. jen přidat komentář k danému modelu, který vysvětli, co je co a jak se souřadnice interpretují. Souhlasíte?

Vše ostatní potvrzuji a děkuji.

**Comment by jiri-bartos-huld** [comment]
@motyc  Dobry den, zde je  pripravena branch na zmenu souradnic na novy standard, je to rozdeleno do jednotlivych commitu podle oblasti: oznameni/3d/pas/projekty/core. Jeste dohledam, zda se na neco nezapomnelo a jeste jednou otestuji

https://github.com/ARUP-CAS/aiscr-webamcr/pull/1368

**Comment by motyc** [comment]
### Test v0.3.5z61
@jiri-bartos-huld Pořadí již je dobře, zbývají tyto chyby:
 - [ ] http://192.168.254.30:8080/pas/zapsat - při zadání souřadnic čistě zápisem do polí je geom_sjtsk v DB null (bez ohledu na zadané EPSG); při zadání kliknutím do mapy to v pořádku funguje
- [ ] http://192.168.254.30:8080/pas/detail/M-202004181-N00016 - při editaci souřadnic přes formulář nedojde v DB k aktualizaci souřadnic geom_sjtsk (problém asi souvisí s předchozím)
 - [ ] http://192.168.254.30:8080/pas/detail/M-202004181-N00015 - přestože pole geom_sjtsk v DB je null, souřadnice ve formuláři se zobrazí - primární EPSG je při tom 5514, takže by se měly vždy zobrazit souřadnice z primárního zdroje, tj. pole geom_sjtsk (nikoli přepočtené z WGS-84 tam a zpět)

Jinde se to zdá být vše ok.

**Comment by jiri-bartos-huld** [comment]
pripraveno na MR

**Comment by motyc** [comment]
### Test v0.3.5z67

> http://192.168.254.30:8080/pas/detail/M-202004181-N00015 - přestože pole geom_sjtsk v DB je null, souřadnice ve formuláři se zobrazí - primární EPSG je při tom 5514, takže by se měly vždy zobrazit souřadnice z primárního zdroje, tj. pole geom_sjtsk (nikoli přepočtené z WGS-84 tam a zpět)

Situace se nijak nezměnila, ale nevím, co se děje v aplikaci na pozadí. Čekal bych, že vzhledem ke stavu v DB budou pole prázdná, nebo aplikace vrátí chybu. Nyní se souřadnice zobrazí. Sice by taková situace v praxi neměla nastat, ale ukazuje na to, že na front-end je něco divně. Ve formuláři by vždy měly být zobrazeny primární souřadnice podle EPSG, aby bylo jasné, co fakticky zadal a viděl uživatel, když záznam zapisoval.

**Comment by motyc** [comment]
### Test v0.3.5z116
Na pozadí se již vše chová dobře (kromě divných odchylek transformace, ale to dám do #594), ale nepochopili jsme se se správným chováním front-end (byť je to krůček lepší, než před tím). Mělo by to být tak, že:
- pokud je v poli `geom_system` 4326, do formuláře se zobrazí položka "WGS-84" + souřadnice z `geom`
- pokud je v poli `geom_system` 5514, do formuláře se zobrazí položka "S-JTSK" + souřadnice z `geom_sjtsk`

Nyní to funguje tak, že se bez ohledu na `geom_system` vždy vybere položka "WGS-84" a zobrazí se souřadnice z `geom`, což je chyba.

Proto by mělo nastat to, že u http://192.168.254.30:8080/pas/detail/M-202004181-N00015 se vypíše "S-JTSK" a souřadnice budou prázdné, protože v `geom_sjtsk` je null (to je chyba dat vzniklá při testech - jen jsem na to díky tomu přišel).

**Comment by jhavrlant** [comment]
@motyc Jako vystudovaný geometr jen upřesním. Systém JTSK má orientaci os Y na západ a X na jih, přitom je zvykem uvádět souřadnici Y jako první. Aby se nedaly souřadnice zaměnit tak X > Y. S příchodem počítačů a programů, které tuto orientaci os nepodporovaly se to začalo řešit tak, že se přidalo k oběma souřadnicím znaménko "-", a souřadnice se prohodily, aby odpovídaly matematické orientaci os. A proto je v tom nyní takový bordel, protože někdo používá původní oficiální značení, orientaci os a pořadí, někdo používá počítačové (matematické) pořadí a orientaci os a někdo něco mezi. Nedivím se tedy, že zde je s tím takový problém.

**Comment by motyc** [comment]
@jhavrlant Díky moc za vhled.

**Comment by jhavrlant** [comment]
@motyc Jestli by to nevadilo vzal bych si to na starost a spojil s #594

**Comment by motyc** [comment]
@jhavrlant Určitě nevadí, přehazuji tedy na Tebe. Děkuju.
