### ISSUE TITLE
Nezobrazuje se oznamovatel

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#113]
Zdá se, že se úplně přestal v detailu projektu zobrazovat oznamovatel. Nedaří se mi najít žádný příklad, kde by byl vidět a myslím, že to je spíš chyba podmínky jeho zobrazení, než že by tam skutečně nebyl.

**Comment by motyc** [comment]
Chtěl jsem to zkusit na novém projektu, ale nefunguje ani http://192.168.254.30:8080/oznameni/ (kliknutí na "Přejít na další krok" nic nedělá).

**Comment by motyc** [comment]
Nefunguje ani http://192.168.254.30:8080/projekt/create

**Comment by Najiva** [comment]
U oznamovatele byla chyba spojena s migraci kde jeste vybublal problem s IDckami Heslaru (migrace jsou na nich taky zavisle).

U oznameni mam podezreni ze to souvisi z tim jak je nastavena CAPTCHA .... zkus prosim pridat server 30 do povolenych na profilu.

**Comment by motyc** [comment]
Oznámení samotné již funguje, problém tedy asi byl opravdu c CAPTCHA (přidal jsem do seznamu test server).

**Comment by motyc** [comment]
Vyřešeno, zavírám
