### ISSUE TITLE
Zrušit formulář v historii souboru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1130]
V `/historie/soubor/` lze úplně zrušit formulář v záhlaví, protože vše podstatné se nyní po změnách vejde do tabulek (#678) a případné detaily relevantní pro admina (sha512, path) lze vyčíst z XML.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7e518529-63cc-4c68-a7a1-ccea06808fbf)

**Comment by pesikj** [comment]
Odhad: 1 hodina
