### ISSUE TITLE
Opravy formulářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1132]
**Chybí tooltip pod polem**
- [x] /arch-z/akce/zmenit-sam-akci/<str:ident_cely> - arch_z.forms.projektPripojit
- [x] /dokument/cast/pripojit-arch-z/<str:ident_cely> - ez.forms.pripojitArchZaznamForm.dokument.vyberArchz
- [x] /dokument/cast/pripojit-projekt/<str:ident_cely> - arch_z.forms.projektPripojit
- [x] /ext-zdroj/ext-odkaz/pripojit-az/<str:ident_cely>
-- ez.forms.pripojitArchZaznamForm.ez.vyberArchz
-- ez.forms.ExterniOdkazForm.paginace
- [ ] /ext-zdroj/ext-odkaz/pripojit-ez/<str:ident_cely>
-- ez.forms.pripojitExterniOdkazForm.vyberEZ
-- ez.forms.pripojitExterniOdkazForm.paginace (OK)
- [x] /ext-zdroj/ext-odkaz/edit/<slug:slug> - ez.forms.ExterniOdkazForm.paginace
- [x] /uzivatel/edit/
-- Password1
-- Password2
- [x] /uzivatel/notifikace/edit/ - uzivatel.form.notifications_form.notification_types

**Chybný oddělovač hodnot (není "; ")**
- [ ]  Další katastry
-- /arch-z/akce/zapsat/<str:projekt_ident_cely> (OK)
-- /arch-z/akce/detail/<str:ident_cely> - http://192.168.254.30:8080/arch-z/akce/detail/M-202103908A
-- /arch-z/akce/edit/<str:ident_cely> (OK)
-- /arch-z/lokalita/detail/<slug:slug> (OK)
-- /arch-z/lokalita/edit/<slug:slug> (OK)
-- /projekt/detail/<str:ident_cely> - http://192.168.254.30:8080/projekt/detail/M-202103908

**Chybná výchozí hodnota**
- [x] /arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/lokalita/zapsat - Přístupnost (má být anonym)
- [x] /dokument/zapsat - dokument.forms.editDokumentForm.region (má být null)
- [x] /arch-z/akce/detail/<str:ident_cely>/dj/<str:dj_ident_cely>/pian/edit/<str:pian_ident_cely> - pole Přesnost není předvyplněno aktuálně nastavenou hodnotou

**Nesmí jít vybrat null**
- [x] /arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/edit/<str:ident_cely> + /arch-z/lokalita/zapsat + /arch-z/lokalita/edit/<slug:slug> - Přístupnost 
- [x] /arch-z/akce/vyber + /arch-z/lokalita/vyber
-- Období
-- Areál
-- Druh předmětu
-- Druh objektu
-- Specifikace objektu

**Špatný formát**
- [ ] /arch-z/akce/vyber - akce.filter.vbNiveleta (má být číslo)

**Pole má být povinné**
- [x] /dokument/zapsat - dokument.forms.editDokumentForm.region

**Jiné**
- [ ] /dokument/model/edit/<str:ident_cely> - Autoři - Neaplikuje se správně pořadí autorů (při editaci se změní pořadí a nedodrží se to, jak byli autoři zapsáni)
- [x] Pro všechny editační tabulky (další vedoucí, nálezy, VB, tvary apod.) se tooltipy zobrazují i při neaktivním režimu (mimo editaci).
- [ ] /projekt/zapsat - pokud zapomenu zadat lokalizaci v mapě, vymažou se již zadané údaje o oznamovateli

Přehled viz: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by jnihnat** [comment]
IN PROGRESS:
/arch-z/akce/zapsat/str:projekt_ident_cely + /arch-z/akce/edit/str:ident_cely + /arch-z/lokalita/zapsat + /arch-z/lokalita/edit/slug:slug - Další katastry
- to je read only field, ty predse mame nastavene ze tooltip nezobrazujeme. Tohle ma byt vynimka?

**Comment by motyc** [comment]
@jnihnat Máte pravdu. Ono to issue je tady už pekelně dlouho a tehdy to tak ještě read-only nebylo. Nechte v těchto případech bez tooltipu.

**Comment by jnihnat** [comment]
opravy mam pripravene az na komentare nahore, kdyz tak pockam na vas @motyc komentar a pak doupravim a udelam pull request.

**Comment by motyc** [comment]
@jnihnat Zde odpovědi:

- /arch-z/akce/detail/str:ident_cely/dj/str:dj_ident_cely/pian/edit/str:pian_ident_cely - pole Přesnost není předvyplněno aktuálně nastavenou hodnotou - _opravil som, ale ulozeni mi pada na chybe s geomem, i na produ pred upravou, prosim kdyz tak samostatne issue a mozna na Jirku Bartose_

žádnou chybu jsem tady v době neregistruji, co přesněji Vám tam nefunguje?

- /arch-z/akce/vyber + /arch-z/lokalita/vyber
-- Období
-- Areál
-- Druh předmětu
-- Druh objektu
-- Specifikace objektu
_tohle mi nedava smysl, je to vyber, takze musi byt moznost nic nevybrat at nefiltrujeme podle dane moznosti_

Jenže ve filtraci je multivýběr, takže to pole jde plnit zaklikáváním jednotlivých hodnot. Když zakliknu null, je to logicky nesmysl (null se vybere správně tím, že nic nezkaliknu, nebo odkliknu již vybrané). Jinde ve filtraci také null hodnoty nejsou v rámci seznamu viditelné. Teď koukám, že stejný problém je ještě v typu akce (obecně ve všech dvouúrovňových seznamech u filtrace):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5804d941-de8b-4237-bcc2-753a4d56a8ec)

- /arch-z/akce/vyber - akce.filter.vbNiveleta (má být číslo) - _format opraven, ale fungovat filtrovani na tohle nikdy nemohlo, protoze to neni DB pole... kdyz tak prosim samostatne issue_

Aha, zajímavé. Tak já to otestuji a dáme to pak bokem. Je to hodnota z geometrie, takže to skutečně standardní pole není. Je tam ale od začátku, jen jsme to nikdy pořádně netestovali.

- /dokument/model/zapsat +/dokument/model/edit/str:ident_cely - Neaplikuje se správně pořadí (jako u /dokument/zapsat)
_jake poradi prosim myslite?_

To bych také rád věděl. Nemůžu to ale teď ani otestovat, protože http://192.168.254.30:8080/dokument/model/zapsat mi vrací chybu `|as_crispy_field got passed an invalid or inexistent field`; myslím, že je to chyba v opravě #1063; až to pojede, zkusím vystopovat, co jsem tím myslel

**Comment by motyc** [comment]
### Test v0.3.5z116
Téměř vše v pořádku vyřešeno. Zbylo jen následující (u těch nejasných jsem zjistil, o co šlo a upravil popis).

**Chybí tooltip pod polem**
- [ ] /ext-zdroj/ext-odkaz/pripojit-ez/<str:ident_cely>
-- ez.forms.pripojitExterniOdkazForm.vyberEZ

**Chybný oddělovač hodnot (není "; ")**
- [ ]  Další katastry
-- /arch-z/akce/detail/<str:ident_cely> - http://192.168.254.30:8080/arch-z/akce/detail/M-202103908A
-- /projekt/detail/<str:ident_cely> - http://192.168.254.30:8080/projekt/detail/M-202103908

**Jiné**
- [ ] /dokument/model/edit/<str:ident_cely> - Autoři - Neaplikuje se správně pořadí autorů (při editaci se změní pořadí a nedodrží se to, jak byli autoři zapsáni)
- [ ] /projekt/zapsat - pokud zapomenu zadat lokalizaci v mapě, vymažou se již zadané údaje o oznamovateli
