### ISSUE TITLE
Úpravy formulářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1133]
**Formátovat jako (d)d. (m)m. rrrr**
- [x] /arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/detail/<str:ident_cely> + /arch-z/akce/edit/<str:ident_cely>
-- Datum zahájení
-- Datum ukončení
- [x] /arch-z/akce/vyber
-- akce.filter.datumZahajeni
-- akce.filter.datumUkonceni
-- historie.filter.datumZmeny
- [x] /arch-z/lokalita/vyber - historie.filter.datumZmeny
- [x] /dokument/zapsat + /dokument/zapsat/do-arch-z/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely> + /dokument/edit/<str:ident_cely> + /dokument/detail/<str:ident_cely> - Datum zveřejnění
- [x] /dokument/detail/<str:ident_cely> + /dokument/edit/<str:ident_cely> - Datum vzniku
- [x] /dokument/vyber
-- dokument.filters.dokumentFilter.datumZverejneni
-- dokument.filters.historieFilter.historieDatumZmeny
-- dokument.filters.dokumentFilter.datumVzniku
-- dokument.filters.dokumentFilter.letDatum
- [x] /dokument/model/vyber - Datum změny (od-do)
- [x] /pas/detail/<str:ident_cely> + /pas/zapsat + /pas/edit/<str:ident_cely> - Datum nálezu
- [x] /pas/vyber
-- pas.filters.datumNalezu
-- Datum změny (od-do)
- [x] /oznameni/ - Plánované zahájení prací
- [x] /projekt/zapsat + /projekt/detail/<str:ident_cely> + /projekt/edit/<str:ident_cely>
-- Plánované zahájení prací
-- Datum zahájení výzkumu
-- Datum ukončení výzkumu
-- Termín odevzdání NZ
- [x] /projekt/vyber
-- Plánované zahájení prací
-- Datum zahájení výzkumu
-- Datum ukončení výzkumu
-- Termín odevzdání NZ
-- Datum změny (od-do)
-- Akce - Datum zahájení (od-do)
-- Akce - Datum ukončení (od-do)
- [x] /ext-zdroj/vyber - dokument.filters.historieFilter.historieDatumZmeny

**Vstup pouze rrrr**
(stejně jako řešeno pro /arch-z/akce/vyber - akce.filter.adbRoky.label)
- [x] /adb/zapsat/<str:dj_ident_cely> + /dj/detail/<str:ident_cely>
-- Rok popisu
-- Rok revize
- [x] /dokument/zapsat + /dokument/zapsat/do-arch-z/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely> + /dokument/edit/<str:ident_cely> - Rok vzniku
- [x] /dokument/detail/<str:ident_cely> + /dokument/edit/<str:ident_cely>
-- Rok od
-- Rok do
- [x] /dokument/detail/<str:ident_cely>/cast/<str:cast_ident_cely> + /dokument/edit/<slug:slug>
-- neidentAkce.form.rok_zahajeni
-- neidentAkce.form.rok_ukonceni
- [x] /dokument/vyber
-- dokument.filters.model3DFilter.rokVznikuOd
-- dokument.filters.dokumentFilter.rokUdalosti
-- dokument.filters.dokumentFilter.neidentRokZahajeni
- [x] /dokument/model/zapsat + /dokument/model/edit/<str:ident_cely> - Rok vzniku
- [x] /dokument/model/vyber - Rok vzniku (od-do)

**Rozložení**
- [x] /arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/detail/<str:ident_cely> + /arch-z/akce/edit/<str:ident_cely>
-- Vedoucí (v tabulce ostatní) - jeden sloupec
-- Organizace (v tabulce ostatní) - přizpůsobit na zbytek šířky
- [x] /pian/zapsat/<str:dj_ident_cely> + /pian/detail/<str:ident_cely> - Přesnost - jeden sloupec
- [x] /dj/zmenit-katastr/<str:ident_cely> - dj.forms.ChangeKatastrForm.katastr - dva sloupce
- [x] /arch-z/akce/zmenit-sam-akci/<str:ident_cely> - arch_z.forms.projektPripojit - jeden sloupec
- [x] /dokument/zapsat - dokument.forms.editDokumentForm.region - jeden sloupec
- [x] /dokument/detail/<str:ident_cely> + /dokument/edit/<str:ident_cely>
--dokument.forms.tvarForm.tvar - jeden sloupec
--dokument.forms.tvarForm.poznamka - přizpůsobit na zbytek šířky
- [x] /dokument/cast/pripojit-arch-z/<str:ident_cely> - ez.forms.pripojitArchZaznamForm.dokument.vyberArchz - jeden sloupec
- [x] /dokument/cast/pripojit-projekt/<str:ident_cely> - arch_z.forms.projektPripojit - jeden sloupec

**Povinné pole**
(doplnit i v DB jako not null, pokud relevantní)
- [x] /dokument/zapsat + /dokument/zapsat/do-arch-z/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely> + /dokument/edit/<str:ident_cely> - Přístupnost
- [x] /pas/spoluprace/zadost - Text

Přehled viz https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by jnihnat** [comment]
odhad 8h @pesikj

**Comment by motyc** [comment]
@jnihnat Za mne ok, klidně se na to vrhněte.

**Comment by pesikj** [comment]
@jnihnat S odhadem souhlasím.

**Comment by jnihnat** [comment]
mam zmenit i format datumu v tabulkach vyberu? @motyc

**Comment by motyc** [comment]
@jnihnat V tabulkách by měl všude být formát RRRR-MM-DD kvůli přehlednému řazení. Teď koukám, že někde je to chybně, tam prosím o úpravu na RRRR-MM-DD.

**Comment by motyc** [comment]
### Test v0.4.27
- [ ] překlep (YYY místo YYYY), proto asi rozbité zobrazení: https://github.com/ARUP-CAS/aiscr-webamcr/blob/9eceeed67478f962b354d0c63c418c9d2851b7df/webclient/static/js/daterangepicker.js#L10
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/4a53e83e-906d-4e18-a1a5-5a309afbe368)
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-202000951A - výpis datumů je s nulami (při editaci ok)
- [ ] Při výběru datumu u historie se nyní po kliknutí volně do pole používá jeden typ kalendáře a po kliknutí na ikonu kalendáře vpravo se otevírá jiný typ. Nefunguje však ani jeden (datum se vůbec nezadá, nebo po překliknutí jinam vymaže. Celkově mi nedává smysl, proč se pro výběr datumu nepoužívá stejná komponenta, jako na jiných místech (např. datum zahájení akce apod.).
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/058a30cb-f606-4fd5-9c0f-10a974a07631)
- [ ] _/dokument/zapsat + /dokument/zapsat/do-arch-z/str:arch_z_ident_cely + /dokument/zapsat/do-projektu/str:proj_ident_cely + /dokument/edit/str:ident_cely + /dokument/detail/str:ident_cely - Datum zveřejnění_ - pominu-li to, že zápis dokumentu teď nefunguje (řeší #1680), tak mi došlo, že jsme nedořešili správné chování daného pole. Nyní se vyplňuje pouze automaticky, pokud je prázdné, ale nikdy nejde editovat. Prosím o úpravu tak, aby jej archivář a admin (D a E) ve stavu D1 a D2 mohli editovat.
- [ ] http://192.168.254.30:8080/projekt/detail/C-202111066 - výpis datumů je s nulami
- [ ] http://192.168.254.30:8080/projekt/edit/C-202111066 - plánované zahájení s nulami
- [ ] dokument.pristupnost - chybí jako NOT NULL v DB

**Comment by motyc** [comment]
### Test v0.4.31
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber - datum zahájení a ukončení v tabulce se nevypisuje jako RRRR-MM-DD
- [ ] http://192.168.254.30:8080/dokument/vyber - datum zveřejnění v tabulce se nevypisuje jako RRRR-MM-DD
- [ ] http://192.168.254.30:8080/ext-zdroj/vyber - datum vydání v tabulce se nevypisuje jako RRRR-MM-DD
- [ ] http://192.168.254.30:8080/projekt/edit/C-202111066 - plánované zahájení s nulami - stále platí (jde o výchozí načtení z DB, po editaci se zobrazí dobře)

Jinak již vše ok

**Comment by jnihnat** [comment]
@motyc uz EZ jsem musel predelat datum vydani na date field i v DB, snad migrace zabere i na prod datech.

**Comment by motyc** [comment]
@jnihnat Vidíte, to mě vůbec nenapadlo, že to není date, jak tam máme málo dat. Budu se muset podívat do dat, zda to nebude problém a případně dám vědět. Obávám se ale, že to bude muset zůstat jako text.

**Comment by motyc** [comment]
@jnihnat Test zcela ok, jen se chci zeptat. Chápu dobře, že aby migrace u externího zdroje fungovala správně, je potřeba mít vstupní string ve formátu DD.MM.YYYY? Soudím podle: https://github.com/ARUP-CAS/aiscr-webamcr/blob/58ed1f7a58cc525ef021264e497aa5e470085e19/webclient/ez/migrations/0009_alter_externizdroj_datum_rd.py#L18

Pokud to tak je, budeme to jen muset zohlednit v produkčních datech (tam bude spíše YYYY-MM-DD).

**Comment by jnihnat** [comment]
Je to presne tak. Ja som vychadzal z dat co som videl v db, ale pokial by to malo byt v inom tvare nie je problem prepsat migraci.

**Comment by motyc** [comment]
Asi to nechte, vyřešíme to nějak na vstupu... Jen ještě dotaz - bude to brát i data 1.1.2024, nebo jen 01.01.2024?
