### ISSUE TITLE
Spoluprace - dodelat

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#114]
- [x] predani nalezu
- [x] transakce
- [x] stavy

**Comment by Najiva** [comment]
![spolupace](https://user-images.githubusercontent.com/26173315/123519378-30b74180-d6ab-11eb-8203-92f2c2a46ad7.png)

Navrh stavu spoluprace.

**Comment by Najiva** [comment]
Omezeni:

1. Spoluprace s jednim archeologem muze byt pouze jedna 
2. Archeolog nemuze mit spolupraci sam se sebou

Otazka je, jestli chcete aby archeolog mohl vytvorit spolupraci za badatele a rovnou ji aktivoval? Pokud ano tak bych ten diagram jeste asi upravil.

**Comment by motyc** [comment]
Potvrzuji řešení. Každá spolupráce by měla být potvrzena oboustranně, takže i pokud vytvoří spolupráci archeolog, měl by ji potvrdit badatel. Univerzálně potvrzovat může pouze archivář a admin.

**Comment by Najiva** [comment]
Dlasi otazka je zda v prehledu spolupraci ma byt filtr nebo ne. Zatim ho tam davam.

**Comment by motyc** [comment]
Ano prosím, určitě v tom potřebujeme mít možnost hledat.

**Comment by Najiva** [comment]
Castecne jsem dodelal spolupraci. 

1. Zatim muze o spolupraci zadat kazdy ale jenom v roli zadatele.
2. Taky muze spolupraci kazdy aktivovat (potvrdit). To je potreba dodelat spoledne s opravnenimi. 
3.  Neni tam zadne omezeni na format fotek pri uploadu souboru (resp. je stejne jako u dokumentu)
4. Chyby odesilani emailu ale to taky nechavam az se budou resit emaily. Dal jsem kde se dalo TOO do kodu.

Pridal jsem transakce PAS:
1. Nalez lze odeslat, potvrdit, archivovat, vratit a editovat
2. Neni tam kontrola ze ma nalez prilozenu alespon jednu fotografii. Pripadne dalsi omezeni.

**Comment by motyc** [comment]
Spolupráce:
1. V pořádku, to pro tuto fázi stačí. Žádost od archeologa badateli si píšu k dodělání na podzim.
2. Souhlas, vyřeší se s oprávněním.
3. Souhlas, vyřeší se s emaily.

Transkace:
1. ok
2. zaznamenáno do #130 
3. zaznamenáno do #148 

Toto issue zavírám.
