### ISSUE TITLE
Dokumentace kritickych bodu (REQ-NF-7)

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#115]
- [x] - nasazeni
- [x] - konfigurace
- [x] - migrace
- [x] - design kodu
- [x] - administrace
- [x] - užité technologie a závislosti
- [x] - napojení na DB
- [x] - fungování úložiště souborů
- [x] - přidělování ident_cely (viz též #63)
- [x] - řešení oprávnění (předběžný stav)

**Comment by motyc** [comment]
Doplněny dva body.

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím na chybějící body.

**Comment by jnihnat** [comment]
napojení na DB popsane v https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Konfigurace#nastaven%C3%AD-napojen%C3%AD-na-db

**Comment by jnihnat** [comment]
administrace ydokumentovana v https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Administrace
