### ISSUE TITLE
Chyba editace polohy u modelu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1175]
Pokud model nemá zadánu polohu v mapě, v detailu modelu jde poloha editovat, byť nejde uložit.

Viz např.: http://192.168.254.30:8080/dokument/model/detail/C-3D-202300001

**Comment by pesikj** [comment]
Mně se uložení polohy bez problémů podařilo.
http://192.168.254.30:8080/dokument/model/detail/C-3D-202300001

**Comment by motyc** [comment]
@pesikj Nejde o to, že by uložit nešla, ale o to, že pokud není poloha vyplněná, jde do mapy přidávat i v detailu modelu bod, aniž bych otevřel editační režim. Cíl je, aby mapa v detailu šla jen prohlížet a do mapy se bod dal přidat jen při editaci.

**Comment by jiri-bartos-huld** [comment]
opraveno ve spolecnem MR

**Comment by motyc** [comment]
Blokováno kvůli #558
