### ISSUE TITLE
Přejmenování potomků při archivaci dokumentu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1178]
- [ ] K přejmenování komponent dokumentu při změně ident_cely dochází pouze u řady "3D", mělo by se to však dít vždy (pro všechny řady dokumentů):
https://github.com/ARUP-CAS/aiscr-webamcr/blob/36c483358601900f8e632a6711435afbbe1af799/webclient/dokument/models.py#L361C12-L361C12

```python
        for dc in self.casti.all():
            if "3D" in perm_ident_cely:
                for komponenta in dc.komponenty.komponenty.all():
                    komponenta.ident_cely = perm_ident_cely + komponenta.ident_cely[-5:]
                    komponenta.save()
                    logger.debug("dokument.models.Dokument.set_permanent_ident_cely.renamed_components",
                                   extra={"ident_cely": komponenta.ident_cely})
            dc.ident_cely = perm_ident_cely + dc.ident_cely[-5:]
            dc.save()
            logger.debug("dokument.models.Dokument.set_permanent_ident_cely.renamed_dokumentacni_casti",
                         extra={"ident_cely": dc.ident_cely})
``` 

- [ ] Druhý problém je, že se správně nepřejmenovávají soubory, viz např.: http://192.168.254.30:8080/dokument/detail/C-TX-202300006 (zůstal původní název)

**Comment by pesikj** [comment]
@motyc Opraveno, pouze pozor na to, že přejmenování souborů bude probíhat asynchronně.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z17)
Nevidím změnu. Testováno na http://192.168.254.30:8080/dokument/detail/C-TX-202300009 - komponenta i soubor zůstaly nepřejmenovány.

**Comment by pesikj** [comment]
@motyc Testoval jsem na aktuální verzi a přejmenování proběhlo korektně:

http://192.168.254.30:8080/dokument/detail/C-TX-202300013

**Comment by motyc** [comment]
@pesikj Ok, opět otestuji.
