### ISSUE TITLE
Ladění login page

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#119]
- [x] prosím o dokumentaci, jak funguje úprava textů na titulní straně (popis, novinky); je třeba otestovat (mělo by jít o soubory čtené z FTP, které půjde volně editovat; viz REQ-G-12)
- [x] email by neměl být case-sensitive (upravit též související chybové hlášky)

**Comment by jnihnat** [comment]
Popis kde jsou soubory k uprave login page:
https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Login-page

**Comment by motyc** [comment]
@vojtakus @MichalKminek Ahoj, prosím potřeboval bych na 192.168.254.30 R/W přístup k těmto souborům: https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Login-page

**Comment by MichalKminek** [comment]
Pristup predan

**Comment by motyc** [comment]
Pokusil jsem se otestovat, ale změna souborů v 192.168.254.30/home/amcr/aiscr-webamcr/webclient/templates/index_page se nijak na serveru neprojevila.

**Comment by MichalKminek** [comment]
Pravdepodobne bude potreba aktualizovat kontejner?

**Comment by motyc** [comment]
Po pravdě nevím, co to znamená. V principu mi jde o to, aby bylo možné popis na úvodní stránce měnit podle potřeby, bez nutnosti restartovat server, tj. bez toho, aby to narušilo běh aplikace.

**Comment by pbartosova** [comment]
Tasky jsou splněné. Ano, je nutný restart. Pokud nevyhovuje chování, prosím řešit jako nový požadavek.

**Comment by motyc** [comment]
Nadále řešeno v #383
