### ISSUE TITLE
Ošetření editace řad dokumentů nepovolených pro zápis

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1199]
http://192.168.254.30:8080/dokument/edit/C-PY-001145001

Souvisí s #800

**Comment by pesikj** [comment]
@motyc Prosím o doplnění specifikace, bez ní nemůže být zahájena oprava.

**Comment by motyc** [comment]
@pesikj Ano, vím o tom. Proto je to přiřazeno na mě a v odpovídajícím stavu v projektu.
