### ISSUE TITLE
Zabraneni duplicitnim oznamenim a umozneni editace existujiciho oznameni pri kroku zpet

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#12]
Tohle je funkcionalita ktera neni v requirementech ale prida to na robustnosti reseni proto je potreba uvazovat o pridani. Momentalne server nechrani pred duplicitami ani neumoznuje update jednou postnuteho oznameni.

**Comment by motyc** [comment]
Rozděleno na #255 a #256
