### ISSUE TITLE
Zajištění aktualizace verze a data v citaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1201]
Do release procesu bychom potřebovali zahrnout mechanismus, který před releasem aktualizuje číslo verze a datum v souboru https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/CITATION.cff

**Comment by pesikj** [comment]
@motyc To číslo verze má být pod klíčem `version` (nyní je tam `pre-release`) nebo jinde.

**Comment by motyc** [comment]
@pesikj Ano, přesně tak.
