### ISSUE TITLE
Fedora - implementace transakcí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1207]
Zvážit odesílání příkazů v rámci transakcí z důvodu omezení nadměrného verzování záznamů a zvýšení bezpečnosti/konzistence při potenciálních chybových stavech.

https://wiki.lyrasis.org/display/FEDORA6x/Transactions

Ověřit také:
- nastavení `fcrepo.session.timeout` - jak se bude chovat při nahrávání větších souborů? (nyní nastaveno na 3 min)
- jaký je přesný postup nahrávání z hlediska manipulace se soubory? Dochází k nahrání někam do temp na úrovni Djanga, nebo se to nahrává přímo od uživatele do Fedory?

**Comment by pesikj** [comment]
@motyc Dokážete definovat, kterých akcí by se to mělo týkat?

**Comment by motyc** [comment]
@pesikj Ideální by bylo aby se vždy všechny operace související s jednou uživatelskou interakcí v Django odeslaly jako jedna transakace do Fedory. Tím by to bylo konzistentní z hlediska možných chyb a rollbacků a zároveň by neměly vznikat nadbytečné verze kontejnerů. Pokud by to takto nešlo, pak alespoň odeslat najednou vždy operace nad jedním kontejnerem v rámci `/rest/AMCR/record/*` (např. při vytvoření kontejneru, úpravu souboru, proces mazání atd.)

**Comment by motyc** [comment]
@pesikj Přestalo fungovat nahrávání souborů. Sice se nahrají do Feodry, ale už se správně neuloží do DB a u nadřazeného záznamu není vidět. Nevím, zda to nesouvisí s tímto issue, protože s poslední verzí asi došlo k nasazení, byť nevím, zda je to komplet hotové.

**Comment by motyc** [comment]
@pesikj Chyba při pokusu o migraci do Fedory:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/1132af8a-a564-40d1-8d7e-ddc1034d136d)

**Comment by pesikj** [comment]
@motyc To generování by v nové verzi již mělo fungovat. Testoval jsem to jen lokálně, ale v tom by neměl být rozdíl. Dále byly opraveny některé chyby, které transakce způsobily. Některé věci jsou ale blokovány neuzavřenými transakcemi. Tady je potřeba na Vaší straně nastavit, aby se transakce opravdu po nějaké době zavíraly, jinak např. nebude fungovat zakládání nových projektů.

**Comment by motyc** [comment]
@pesikj Ok, moc děkuji, prověřím to s Vojtou. Nasadíte prosím tuto verzi i na .30?

**Comment by motyc** [comment]
@pesikj Tak na .30 jsem teď chtěl spustit ADB a bohužel to na transakcích selhalo (chová se to tak bez ohledu na model). Rozdíl oproti .24 byl, že zde jsem to pouštěl bez nastavení limitu na 3 záznamy:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2a4eb06a-6838-403f-a770-4c667939d4e6)

**Comment by motyc** [comment]
@pesikj To ale nedává smysl. Aplikace je odstavená a v DB Fedory na .30 žádné visící transakce nevidím (na rozdíl od .33, kde jich několik skutečně visí). Není tam náhodou nějaká chyba v tom, že se to snaží pracovat s Fedorou na .33 místo .30, tj. že je špatně konfigurace?

**Comment by pesikj** [comment]
@motyc Připojuje se to k adrese https://fedora-test.aiscr.cz:443/rest/AMCR/record/ADB-ZABR79-000001/metadata, takže to je asi ok.

**Comment by pesikj** [comment]
@motyc Tak už je to opravené. Ta druhá instalace Fedory je nastavená tak, že neakceptuje číslo portu v adrese transakce.

**Comment by motyc** [comment]
@pesikj Zatím to vypadá ok. Budu pokračovat v generování, tak na 30 teď prosím nesahat.

**Comment by motyc** [comment]
@pesikj
- [ ] Pro model `User` se z nějakého důvodu transakce vytvoří, vše se do ní vloží, ale neodešle se. Nyní jsem to obešel tím, že jsem si vytvořené transakce vypsal z DB a hromadně odeslal, ale musíme přijít na to, proč se to neodesílá.
- [ ] Také jsem si všiml, že z nějakého důvodu neběží .24 (chyba při nasazení?).

Každopádně na 30 pokračuji v generování.
