### ISSUE TITLE
Ladění ../accounts/register/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#121]
- [x] telefon ponechat bez složitých regulárních výrazů (povolit číslice a znak +)

**Comment by jnihnat** [comment]
@motyc - pro jistotu pisu jake jsou povolena cisla tedka:
- zacinajici +420 nebo +421 a nasledne 9 cislic
- bez predcisli krajiny, pak se validuje 10 nebo 9 znaku.
- jsou povoleny mezery, tie sa odstranuju.
Pozadovany stav:?
- povolit vsetky cisla zacinajici s/bez + a libovolny pocet cislic? (nebo zadat aspon minimalny pocet?
Navrhuji uz rovno upravit i to pole z TextArea na Text (text area je vacsi a ma to rozsirovatko v rohu)

**Comment by motyc** [comment]
S úpravou pole na text souhlasím.
Co se týče validace - přemýšlím o tom, a problém je hlavně v té předvolbě, která by neměla být omezena, případně v délce. V podstatě by tedy mělo stačit odstranit kontrolu předvolby (420/421) a povolit různé délky čísel (např. 5-15), aby prošly různé mezinárodní varianty.
