### ISSUE TITLE
Vložení pop-up u neprodukčních verzí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1238]
Některá prostředí AMČR mohou být veřejná, přestože nebudou produkční (zejména tréninková verze). Musíme zajistit, že uživatelé tato prostředí omylem nebudou využívat k práci.

Při příchodu na libovolnou stánku dané instance (max. jednou denně) zobrazit pop-up s upozorněním, že se nejedná o produkční verzi.

**Comment by jnihnat** [comment]
uprava pripravena, pridana i dokumentace do casti Nasazeni jak to nastavit. ROvno jsem to nastavil na server .30 takze staci mergnout a nasadit a mnela by se zobrazit hlaska po prihlaseni.

**Comment by motyc** [comment]
@jnihnat Funguje to díky, jen prosím upravit, aby se ten pop-up sám nezavřel a čekal na zavření uživatelem.

**Comment by motyc** [comment]
@pesikj Je třeba nastavit pro dev (a výhledově i pro tr), aby je systém chápal jako testovací instance.
