### ISSUE TITLE
Omezení max. počtu exportovaných záznamů z tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1239]
Omezit max. povolený počet záznamů, které lze exportovat z tabulek, aby nemohlo docházet k přetížení DB.

- [ ] Přidat konfiguraci limitu do administrace.
- [ ] Když počet záznamů v tabulce přesáhne uvedený počet, export nebude aktivní (místo exportu vyskočí hláška, že byl přesažen limit počtu záznamů na jeden export).

Až bude vyřešena asynchronní varianta exportů (#395), bude export aktivní i nad tento limit a bude to hranice, kdy se synchronní řešení změní na asynchronní.

**Comment by pesikj** [comment]
@motyc Toto možná nebude potřeba.

**Comment by motyc** [comment]
@pesikj To by samozřejmě byla skvělá varianta.

**Comment by pesikj** [comment]
Pokud bude schváleno #395, můžeme toto uzavřít.
