### ISSUE TITLE
Ladění ../accounts/register/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#124]
- [x] @motyc prověřit poslední fázi registrace (aktivace linkem v mailu) - nutno zjistit #118

**Comment by jnihnat** [comment]
@motyc 
- upraveny synchro emailov, teraz sa ukladaju na server do adresara /vol/web/media/emails.
- otestoval som druhu fazi registrace, ta je funkcni, mozne otestovat na dev prostredi taky, staci pak email vyhledat v adresari na serveru hore.
- nasel som jednu vec k uprave: Ak user neni jeste aktivni (neaktivovany linkem z mailu/neaktivovany nastavenim role v adminu) tak se zobrazuje hlaska o nespravnosti username/password. Muzu to opravit a nastavit jednu hlasku pre nevalidni username/password a jednu pre neaktivovaneho usera pokud souhlasite. Prosim pripadne o texty error hlasky. 
Dekuji

**Comment by motyc** [comment]
Ad nastavení hlášek - ano, rozhodně souhlasím, že lepší budou dvě odlišné hlášky, děkuji za návrh.
