### ISSUE TITLE
Ladění ../projekt/navrhnout-ke-zruseni/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#125]
- [x] sice se otestuje zda projekt nemá akci (viz BR-P-7) a vyskočí hláška, ale projekt lze přesto navrhnout ke zrušení
- [x] nemá být vůbec dostupné pro projekty v stavu P0 (oznámený)

**Comment by jnihnat** [comment]
@motyc 
- u prvniho upraveno presmerovani, v pripade warningu je user presmerovan na stranku z ktere sel na navrh-na-zruseni a tam se zobrazi warning.  - Prosim o potvrzeni ze je to takto OK.
- u druhyho - pri stavu Oznameny neni mozne jit na stranku navrh-na-zruseni ale jenom na stranku zrusit. - Ma se neco teda menit nebo to tak je ok?

**Comment by motyc** [comment]
@jnihnat
ad 1 - ano, to by mělo být OK; definitivně potvrdím po nasazení, až budu moci otestovat
ad 2 - tlačítko zrušit by v tomto případě nemělo být vůbec dostupné
