### ISSUE TITLE
Ladění ../projekt/prihlasit/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#127]
- [x] pole Rejstříkové číslo a Název památky označeny jako povinné, i když vyplněno bez ochrany
- [x] pole organizace se má nativně vyplnit podle organizace uživatele (děje se pouze na pozadí a ve formuláři není vidět); pole má být editovatelné pouze adminem (to souvisí s oprávněním a nyní neřešíme); když to nyní udělá (může), tak se jeho editace přepíše podle organizace uživatele; logiku řešení je třeba otočit - pole bude předvyplněné při vstupu do formuláře, pro archeologa bude ale zašedlé (vyřešíme později), admin bude moci upravit na jinou organizaci, volba se následně uloží tak, jak ji nově nastavil.
- [x] BR-P-8: When “pamatkova ochrana” of the project site is “bez ochrany” there must not be able to fill “pamatka_cislo” and “pamatka_popis” fields of the project.

**Comment by jnihnat** [comment]
@motyc Prosim aky je pozadovany stav:
ak je "bez ochrany" - tak maju byt fieldy disabled alebo len nepovinne a je ich mozne menit? (prvy a treti bod v issue su totiz v rozpore)
ak by mneli byt disabled, mazat i ty pole pokud v nich neco je?

**Comment by motyc** [comment]
@jnihnat
Pokud je "bez ochrany", tak by měly být pole neaktivní. Pokud v nich něco je, tak při změně na "bez ochrany" obsah odstranit (zde předpokládám, že odeslání změn na server je vázáno až na transakci uložení změn, tj. není to nevratné, pokud se to stane omylem). Pardon za ten rozpor, spíš je to nešťastně formulované.

Pole organizace by tam mělo zůstat, ale mělo by být předvyplněné podle organizace uživatele (to nyní není, hodnota se zjevně vloží ex-post při odeslání). Pokud ve formuláři výchozí hodnotu změním, měla by se tato změna standardně uložit do DB. Tolik chování nyní.

Zbylé chování (deaktivace pole organizace pro určité typy uživatelů) se dotýká uživatelských oprávnění a ošetření takových případů bylo ponecháno pro další fáze vývoje.

**Comment by jnihnat** [comment]
Upraveno nasledovne:
- pokud je "bez ochrany" tak jsou fieldy disabled
- pokud neni "bez ochrany" tak jsou fieldy enabled + doplname pokud v nem neco pred tim bylo vyplneno
- oba pole jsou bez "*" - doplnat to dynamicky by bylo narocne

Organizace je predvyplnena podle usera (pred tim byla brana z projektu) a po novu se updatuje podle toho co user vybere ne podle toho jakou ma user.
