### ISSUE TITLE
Ladění ../arch_z/edit/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#128]
- [x] chybí tlačítko pro + přidání jména osoby
- [x] chybí ověření souslednosti data zahájení/ukončení (ukončení nesmí předcházet zahájení; ukončení ani zahájení nesmí být v budoucnu o více než měsíc)
- [x] katastry uzamknout pro editaci (bude se řešit později načítáním z PIAN)
- [x] chybí pole: organizace, specifikace data, uložení dokumentace

**Comment by pesikj** [comment]
V budoucnu o více než měsíc - to je myšleno k aktuálnímu datu?

**Comment by pesikj** [comment]
Další osoba může být jen jedna, nebo by mělo být možné jich přidat více?

**Comment by motyc** [comment]
Ad - "v budoucnu" - ano, od aktuálního data
Ad - další osoba - zde se možná špatně chápeme, jde o přechod na formulář http://192.168.254.30:8080/uzivatel/osoba/create pro zápis nové osoby do hesláře; přidávání více vedoucích je jiné téma (také k řešení, ale stačí na podzim - týká se hlavně samostatných akcí).

**Comment by pesikj** [comment]
Organizace má být podle vedoucího?

**Comment by svejci** [comment]
Ano, organizace by se měla vyplnit podle vedoucího.

**Comment by pesikj** [comment]
A to pole by tedy mělo být pouze pro čtení?

**Comment by svejci** [comment]
Pole by mělo být dále přístupné k editaci.

**Comment by pesikj** [comment]
OK

**Comment by pesikj** [comment]
Tlačítko přidáno sem:
![image](https://user-images.githubusercontent.com/15179154/127293801-2f3ab395-741f-45a9-93b3-9876dba5ab61.png)

**Comment by pesikj** [comment]
Přidána validace data
![image](https://user-images.githubusercontent.com/15179154/127307502-62e2ca97-ba3c-400f-b67c-cce81d45064d.png)

**Comment by pesikj** [comment]
Validace posloupnosti dat
![image](https://user-images.githubusercontent.com/15179154/127308234-20e6f1a6-c597-4ef7-ac17-a63a1b5469ad.png)
