### ISSUE TITLE
Fedora - chyba odkazu dokument/arch. záznam

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1280]
Lokalita[ C-K9000903](http://192.168.254.30:8080/arch-z/lokalita/detail/C-K9000903) má vazbu na dokument [C-DT-100005485](http://192.168.254.30:8080/dokument/detail/C-DT-100005485). Ten ale má v [metadata.xml](http://192.168.8.33:8080/rest/AMCR-test/record/C-DT-100005485/metadata/) v příslušném elementu uvedeno: `<amcr:archeologicky_zaznam id="X-C-K0751394">X-C-K0751394</amcr:archeologicky_zaznam>`, což je starý ident_cely lokality před archivací.

Stejný problém vzniká při archivaci samostatných akcí (nyní testováno na [C-TX-202300006](http://192.168.254.30:8080/dokument/detail/C-TX-202300006)).

Bude nutno doplnit signál tak, aby se při změněn ident_cely arch. záznamu vždy vygenerovala nová metadata pro napojené dokumenty a naopak při změně ident_cely dokumentu se totéž stalo pro připojené arch. záznamy a projekty (to jsem neprověřoval, ale tuším tam také problém).

**Comment by motyc** [comment]
### Test v0.3.5z61
Předchozí problémy jsou odstraněné, ale obdobné chyby nastávají ještě minimálně v těchto případech:
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9723786A/dj/C-9723786A-D01 - nedošlo k úpravě odkazu u PIAN (http://192.168.8.33:8080/rest/AMCR-test/record/P-1142-100036/metadata/fcr:metadata)
- [ ] http://192.168.254.30:8080/arch-z/lokalita/detail/C-L9001062/dj/X-C-L000000008-D01 - nezměnilo se označení DJ a komponenty + stejný problém s PIAN jako v předchozím případě
- [ ] http://192.168.254.30:8080/projekt/detail/C-201705736 - nezměnilo se odkaz na http://192.168.254.30:8080/dokument/detail/C-DD-202300006
- [ ] http://192.168.254.30:8080/ext-zdroj/detail/BIB-0000031 - neupravila se vazba na http://192.168.254.30:8080/arch-z/akce/detail/C-202105970B (stejný problém ošetřit pro opačný směr a pro lokality)

**Comment by pesikj** [comment]
@motyc Provedl jsem opravy, ale přestala fungovat Fedora, takže jsem to nemohl otestovat.
