### ISSUE TITLE
Nefunguje mazání záznamů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1299]
v0.3.5z17
Mazání záznamů libovolného typu je nyní nefunkční - vše zdánlivě proběhne dobře, ale záznam se nesmaže. Testováno na projektu, nálezu, DJ... Fungovalo mi pouze mazání souborů.

**Comment by motyc** [comment]
### Test v0.3.5z37
Je to lepší, ale nefunguje to vždy. Zde smazání nefunguje (zdánlivě proběhne, záznam zůstane):
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000010A
- [ ] http://192.168.254.30:8080/pas/detail/M-202101534-N00223 
- [ ] http://192.168.254.30:8080/dokument/model/detail/C-3D-202000194 - úplně chybí související tlačítko, ale ani přímé smazání přes http://192.168.254.30:8080/dokument/smazat/C-3D-202100042 nefunguje
- [ ] http://192.168.254.30:8080/dokument/detail/X-C-TX-000000033 - jako předchozí
(poslední dva body jsou zachyceny i v #379, tak to zobrazení možná opraví @jnihnat)

**Comment by motyc** [comment]
@pesikj No a dokážeme rozluštit, proč se zobrazuje? Smazání lokality by myslím nic záměrně blokovat nemělo, tak to bude spíš nějaká neošetřená nebo chybně ošetřená věc.

**Comment by pesikj** [comment]
@motyc Je to blokováno PIANem u dokumentační jednotky.

**Comment by motyc** [comment]
@pesikj Pak je to ale chyba. Pokud je PIAN potvrzený, prostě se jen smaže DJ a PIAN zůstane. Pokud je nepotvrzený a nemá další vazby, dojde k jeho smazání na základě signálu (původně trigger).

**Comment by pesikj** [comment]
@motyc Ok, opraveno.

**Comment by pesikj** [comment]
@motyc Nasazena oprava dle domluvy po telefonu.
