### ISSUE TITLE
Ladění ../pas/detail/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#130]
- [x] nefunkční přidávání fotografií
- [x] nedokončená implementace (editace záznamu, posuny stavů)
- [ ] chybí mapové prostředí s podporou potřebných funkcí jako v původní aplikaci; mělo by být jednotně postaveno na Leaflet
- [ ] chybí pole katastrální území, souř. systém, Souřadnice Y / N, Souřadnice X / E (všechny spojeny funkčně s mapou; viz stávající řešení)
- [x] v poli s projekty by se v závorce měl vypisovat též vedoucí
- [x] chybí kontroly při odeslání (alespoň jedna foto)

**Comment by pesikj** [comment]
@jnihnat Prosím zkontroluj, zda je 5 hotové a podívej se prosím na 6.
