### ISSUE TITLE
Chyba odpojování PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1304]
Nefunguje odpojování PIAN (např. http://192.168.254.30:8080/arch-z/akce/detail/C-9723781A/dj/C-9723781A-D01) - vše se tváří ok, ale nic se na konci nestane.

**Comment by pesikj** [comment]
@motyc Na aktuální verzi se mi nepodařilo nasimulovat.

**Comment by motyc** [comment]
@pesikj Ok, také prověřím.

**Comment by motyc** [comment]
@pesikj Tak mi to fungovalo pro nepotvrzený PIAN, ale zde to třeba nefunguje: http://192.168.254.30:8080/arch-z/akce/detail/C-9157770A/dj/C-9157770A-D01

**Comment by pesikj** [comment]
@motyc Mně to funguje i pro potvrzený. Zkoušel jsem tu samou DJ. Jinak nevím, v čem by mohl být rozdíl, proč to někdy funguje a někdy ne.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/70ae10da-bae2-4b4d-8289-5760497c6d5c)

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/230a8291-45c5-43b2-a3d2-3c578031976c)

**Comment by motyc** [comment]
Tak rozdíl je minimálně v tom, že potvrzené by se neměly mazat na základě triggerů (ale tam to bude ještě trochu zamotané, protože v DB jsou původní triggery a něco zároveň asi už dělá aplikace - viz #1067). Jenže mě se vůbec neotevřelo to modal okno (jen čára a v konzole vracela myslím 502). Tak nevím, zda už třeba neběžel nějaký výpadek, nebo něco takového...

**Comment by motyc** [comment]
@pesikj Nechám to k testu a uvidíme za čas.
