### ISSUE TITLE
Třída CoordinatesDokumentForm

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1306]
https://github.com/ARUP-CAS/aiscr-webamcr/blob/95d78eb4e39f6629af052ebb20c3dde2dde5d697/webclient/dokument/forms.py#L54 
toto je třída, která myslím vůbec nemá patřit do aplikace dokument, ale do pas

Mělo by se myslím přesunout do správné aplikace (pas) a přejmenovat, aby to nebylo úplně zmatečné. Souvisí to možná také se zmatky kolem #1126

**Comment by jhavrlant** [comment]
@motyc  class CreateModelExtraDataForm(forms.ModelForm): se používá pouze v 3D modelech, takže je asi správně.

**Comment by motyc** [comment]
@jhavrlant Ano, tam je to myslím ok. Ani po pravdě nevím, jak se tam ten druhý odkaz dostal - možná to byl nějaký zmatek. Issue se týká jen `CoordinatesDokumentForm`. I když teď ale koukám, že se to používá zde:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/2be4c2e5842403b9496c2e759dfeebeb6dcca587/webclient/dokument/views.py#L1241

Možná by tedy stačilo upravit komentáře, ať to nemate...
