### ISSUE TITLE
Refactoring - lokalita

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1307]
Lokalita obsahuje některé překlady, které nejsou pro ni vůbec relevantní - zdá se mi, že jsou tam některé části kódu, jako třeba k ADB, které pro lokality vůbec nevznikají; podobně např. test, že lokalita má NZ před odesláním (sice se nepoužívá, ale klíče a tedy asi i kód zůstaly).

**Comment by jhavrlant** [comment]
Upraveno v #715 (#1841)
