### ISSUE TITLE
Chyba přidávání a mazání komponent

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1310]
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-202300555A/dj/C-202300555A-D01 - Když jsem přidal komponentu, poté ji smazal a opět se ji pokusil vytvořit hlásí mi to chybu `AttributeError at /komponenta/zapsat/C-202300555A-D01`
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000000018A/dj/X-C-9000000018A-D01 - po smazání komponenty X-C-9000000018A-K002 zmizela i komponenta komponenty X-C-9000000018A-K001

**Comment by pesikj** [comment]
@motyc V nejnovější verzi by již mělo být odstraněno, prosím o test.
