### ISSUE TITLE
Chyba pro DJ typu Katastrální uzemí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1323]
- [ ] Jde přidat druhou DJ libovolného typu, pokud už tam je první typu “Katastrální území”.
- [x] Přestala fungovat změna typu DJ na “Katastrální uzemí”.
- [x] Při změně typu z "Katastrální území" na jiný nedojde k odpojení PIAN katastru.

K prvnímu bodu ještě poznamenávám, že v původní implementaci bylo myslím zadávání více DJ typu “Katastrální území” zcela zakázáno. Ideální stav by byl, aby se dalo přidávat více DJ a katastr z D01 by se vkládal do hlavního katastru, ostatní DJ pak do dalších katastrů. Pokud to implementace nyní neumožňuje, uděláme na to případně změnový požadavek.

**Comment by pesikj** [comment]
@motyc Nedohledal jsem v zadání popis toho, jak by měla být nastavena pravidla v souvislosti s Katastrálním území. Již implementovaná pravidla fungují (je-li přidána sonda, lze přidat jen další sondu; je-li přidán celek akce, lze přidat jen část akce).

**Comment by motyc** [comment]
@pesikj Ono to bude asi roztroušené, napříč různými issues. Problém je primárně v situaci na screenu níže, kdy už mám zapsanou DJ typu Katastr a mohu přidat další libovolného typu (http://192.168.254.30:8080/arch-z/akce/detail/C-9723783A/dj/zapsat):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a614680a-b07f-4cd2-808a-42b7e1059da9)

Původní chování bylo takové, že by měla být DJ typu katastr prostě max jen jedna a hotovo. Ta práce s dalšími katastry je spíše změnový požadavek, jak sám podotýkám a můžeme to vyčlenit bokem.

Pak jsou tam ty další dva problémy, kdy nejde měnit DJ s jiným typem na Katastrální území (např. http://192.168.254.30:8080/dj/detail/C-9000094A-D01 -> vrátí `'CreateDJForm' object has no attribute 'typ'`).

No a třetí chyba je (a to také dříve fungovalo), že při změně DJ z Celku či Sondy na Katastr nedojde k odpojení PIAN katastru, takže nastane takováto situace, kdy třeba zde Sonda má PIAN katastru: http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000009A/dj/X-M-9000000009A-D01

Všechny tyto věci byly dříve správně.

**Comment by pesikj** [comment]
@motyc Chyby jsou opravené.

> Ideální stav by byl, aby se dalo přidávat více DJ a katastr z D01 by se vkládal do hlavního katastru, ostatní DJ pak do dalších katastrů. Pokud to implementace nyní neumožňuje, uděláme na to případně změnový požadavek.

Problém s implementací nedokážu posoudit, protože ze zadání není vůbec jasné, jak by toto mělo fungovat.

**Comment by motyc** [comment]
### Test v0.3.5z61
Ještě je třeba ošetřit toto (na tu úpravu udělám zvlášť issue, to zde teď neřešme).
- [ ] Jde přidat druhou DJ libovolného typu, pokud už tam je první typu “Katastrální území” (např. http://192.168.254.30:8080/arch-z/akce/detail/C-9723783A/dj/zapsat). Pokud existuje DJ typu KÚ, druhá již nesmí jít přidat (skrýt tlačítko "Přidat dokumentační jednotku".
