### ISSUE TITLE
PIAN - chyba mazání bodových prvků v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1327]
http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000009A/dj/X-M-9000000009A-D02/pian/zapsat - v mapě nefunguje funkce pro odstranění zadaného bodu (ikona koše; kliknutí na bod nic neudělá; pro linie a polygony je to ok)

**Comment by jiri-bartos-huld** [comment]
Opraveno: @pesikj 
prosim koukni sem: https://github.com/ARUP-CAS/aiscr-webamcr/commit/955aad7ae3d55e530b776260953e09550d94322a
Chybb byla, ze 
[map_translations['TempPIAN']] neni preklad ale vraci to array
+ ma se pouzit bindTooltip nikoliv bindPopup

**Comment by jiri-bartos-huld** [comment]
@motyc oprava je na MR

**Comment by motyc** [comment]
@jiri-bartos-huld @pesikj Pokud byl překlad řešen chybně, bude tedy třeba jej nastavit jinak a správně, aby se dostal do Rosetty.
