### ISSUE TITLE
Administrace - nadbytečné položky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#133]
- [x] obsažena řada ne zcela jasných položek navíc (historie, projekty, oznamovatelé), které přes administraci nemají jít měnit - k tomu slouží aplikace a její procesní pravidla

**Comment by pesikj** [comment]
@motyc Toto je pro účely vývoje, abychom mohli přistupovat k záznamům přímo, později bude odebráno. Nyní navrhuji toto issue odložit.

**Comment by motyc** [comment]
@pesikj souhlasím a značím jako podzim

**Comment by motyc** [comment]
@pesikj Možná by pomohlo řešení, že bychom si pro tyto tabulky věci, které nebudou součástí finálního řešení, vytvořili v administraci nějakou samostatnou záložku/kategorii? Tím by se věc vyjasnila a na konci vývoje by se to prostě jen dalo pryč.

**Comment by pesikj** [comment]
@motyc I agree with the proposal.

**Comment by motyc** [comment]
Nově se objevilo toto:
![image](https://user-images.githubusercontent.com/20186892/171865518-af96bcc9-7c8c-40aa-a77d-4e5123d55bce.png)

Když na položky kliknu, dostanu error 500. O co jde?

**Comment by pesikj** [comment]
@motyc To souvisí s issue #306 a naplánovanými úlohami, nikoli s tímto issue.

**Comment by motyc** [comment]
@pesikj S tímto issue to souvisí v tom směru, že to máme v administraci, nejde to otevřít a není jasné, o co jde. Bude to tam i do budoucna? Pokud ano, pak je třeba aby to neházelo 500 a aby to bylo zadokumentované.

**Comment by motyc** [comment]
@pesikj Rozumím, nechám to tedy do daného issue a přidávám tam tuto naši diskusi.

**Comment by pesikj** [comment]
@motyc Výborně, děkuji.
@jiri-bartos-huld Pokud bys potřeboval výpis z logu kvůli chybě 500, dej mi vědět.
