### ISSUE TITLE
Readthedocs - nastavení webhook

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1339]
Dnes jsem obdržel následující zprávu emailem, je třeba to ošetřit:

> Previously, manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, we have deployed an update so that all new integrations will be created with a secret, and we are deprecating old integrations without a secret. You must migrate your integration by January 31, 2024, when they will stop working without a secret.
> 
> We are contacting you because you have at least one integration that does not have a secret set. These integrations are:
> 
>     https://readthedocs.org/dashboard/aiscr-webamcr/integrations/233134/
> 
> If you aren't using an integration, you can delete it. Otherwise, we recommend clicking on "Resync webhook" to generate a new secret, and then update the secret in your provider's settings as well. You can check [our documentation](https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html) for more information on how to do this.
> 
> You can read more information about this in our blog post: https://blog.readthedocs.com/security-update-on-incoming-webhooks/.

**Comment by jnihnat** [comment]
@motyc tohle asi ja neudelam, nemam totiz dostatecne prava v github projektu.
Ale mnelo by stacit jit do https://readthedocs.org/dashboard/aiscr-webamcr/integrations/233134/
sebrat secret a jit do github projektu kde by mnelo stacit pridat secret:
Go to the Settings page for your GitHub project
Click Webhooks > Add webhook
For Payload URL, use the URL of the integration on your Read the Docs project, found on the project’s Admin > Integrations page. You may need to prepend https:// to the URL.
For Content type, both application/json and application/x-www-form-urlencoded work
Fill the Secret field with the value from the integration on Read the Docs
Select Let me select individual events, and mark Branch or tag creation, Branch or tag deletion, Pull requests and Pushes events
Ensure Active is enabled; it is by default
Finish by clicking Add webhook. You may be prompted to enter your GitHub password to confirm your action.
You can verify if the webhook is working at the bottom of the GitHub page under Recent Deliveries. If you see a Response 200, then the webhook is correctly configured. For a 403 error, it’s likely that the Payload URL is incorrect.

**Comment by motyc** [comment]
@jnihnat Díky, vyřešeno.
