### ISSUE TITLE
Automatické mazání starých image ze serveru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1349]
Je třeba upravit deployment skript tak, aby se automaticky mazaly starší image, protože jinak může na serveru dojít místo.

**Comment by pesikj** [comment]
Vzhledem k #1332 možná bude potřeba mazat pouze některé verze.

**Comment by motyc** [comment]
@pesikj Ono ale ty staré verze dokážeme kdykoli zbuildovat znovu z konkrétního release, nebo ne? Navíc by vše mělo být na https://hub.docker.com/repositories/aiscr

**Comment by pesikj** [comment]
Ano, vše tam je. Jen se to zdrží stahováním, ale je pravda, že to jsou řádově desítky vteřin.

**Comment by motyc** [comment]
To je pravda, ale myslím, že to nevadí. Te rollback bude spíše výjimečný...

**Comment by pesikj** [comment]
@motyc Rozumím.
