### ISSUE TITLE
Ladění ../dokument/create/model

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#136]
- [x] místo roku vzniku je ve formuláři datum
- [ ] - mapa by měla odpovídat řešením #49 (Leaflet; nemělo by se v rámci aplikace používat víc variant)
- [x] - chybí pole země, region, šířka (uzamčeno - podle mapy), délka (uzamčeno - podle mapy)

**Comment by pesikj** [comment]
Takže namísto data vzniku bychom měli evidovat pouze rok vzniku?

**Comment by motyc** [comment]
Je to vázáno na pole dokument.rok_vzniku, takže ano. Možná chyba vnikla použitím špatného pole.

**Comment by jnihnat** [comment]
Pole sirka a delka doplnene. nejsou akurat automaticky doplneny z mapy, To nechavam az po uprave mapy, pripadne pri ni.
