### ISSUE TITLE
Lokalita - chyba změny typu DJ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1362]
http://192.168.254.30:8080/arch-z/lokalita/detail/C-L9001061/dj/X-C-L000000004-D01 - nejde změnit typ na lokalitu, vrátí 'NoneType' object is not subscriptable

**Comment by pesikj** [comment]
@motyc Odkaz nefunguje a nevím, jak toto nasimulovat.

**Comment by motyc** [comment]
Problém byl ve změně typu k KÚ na lokalitu. Už funguje, zavírám.

**Comment by motyc** [comment]
Tak bohužel jsem to spíš testoval omylem opačně - nejde měnit katastr na lokalitu - viz např. http://192.168.254.30:8080/dj/detail/lokalita_dj_zakladni/X-M-N000000001-D01

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/6b4918fa-83fd-4cb2-aa39-dda9783e939e)

**Comment by pesikj** [comment]
@motyc Ten odkaz vede na view, které podporuje pouze POST request. Můžete mi prosím poslat odkaz na akci? Nemůžu ji vyhledat podle identu, i když odstraním postfix D001.

**Comment by pesikj** [comment]
@motyc Můžete mi prosím poslat odkaz na lokalitu? To view z odkazu podporuje pouze POST request.

**Comment by motyc** [comment]
@pesikj Zde to je: http://192.168.254.30:8080/arch-z/lokalita/detail/M-N1000004/dj/X-M-N000000001-D01

Je to možná kombinované s tím problémem s potomky a jejich přejmenováním (#1280)

**Comment by pesikj** [comment]
@motyc Udělal jsem refaktorizaci funkce `update_all_katastr_within_akce_or_lokalita`, aby to používalo standardní ORM a tím pádem se změny u ostatních katastrůj ukládaly do Fedory.
