### ISSUE TITLE
Historie uživatele - některé změny se neevidují

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1363]
http://192.168.254.30:8080/historie/uzivatel/U-003547 - neevidují se změny role pro nově vytvořené skupiny (nyní Správa heslářů, Správa letů); měly by se zaznamenat všechny změny přiřazení do skupin

**Comment by motyc** [comment]
@pesikj Toto musím znovu otevřít a to ze třech důvodů:
- [ ] historie se zjevně generuje jen při změnách přes administraci, ale nikoli při změnách přes http://192.168.254.30:8080/uzivatel/edit/
- [ ] pokud přes administraci edituji jen skupiny, vzniknou dva záznamy v historii, jeden s prázdnou poznámkou k editaci celého formuláře a druhý (i když se v něm nic nezměnilo) a druhý k editaci skupin
- [ ] ale hlavně, do historie se do poznámky vypisuje i změna hesla, včetně běžně čitelného samotného hesla - heslo se takto v žádném případě ukládat nesmí (nahradit např. hvězdičkami)

**Comment by pesikj** [comment]
@motyc Jak jste nasimuloval to vložení hesla do poznámky? Mně se pro změnu hesla přes samostatný formulář v administraci do historie nic neukládá.

**Comment by motyc** [comment]
@pesikj Po chvilce dumání jsem zjistil, že se to stane při přidání uživatele skrz administraci: http://192.168.254.30:8080/admin/uzivatel/user/add/

Teď tam máte nový příklad u uživatele testheslo@test.cz

**Comment by pesikj** [comment]
@pesikj Super, děkuji.

Změna hesla má samostatnou metodu, protože to už je jiný formulář, to je ošetřeno v #1413.
