### ISSUE TITLE
Ladění ../dokument/edit/model/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#140]
- [x] místo roku vzniku je ve formuláři datum
- [ ] - mapa by měla odpovídat řešením #49 (Leaflet; nemělo by se v rámci aplikace používat víc variant)
- [x] - chybí pole země, region, šířka (uzamčeno - podle mapy), délka (uzamčeno - podle mapy)

**Comment by jnihnat** [comment]
tasky 1 a 3 opraveny v ramci #136. Pri mape potreba doladit dotahovani sirky a delky
