### ISSUE TITLE
Možnost přidat další katastry u AZ s přesností na katastr

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1401]
Pokud AZ má DJ typu `katastrální území`, bude možné další katastry u těchto záznamů upravovat v editaci záznamu. Hlavní katastr se standardně řídí podle DJ.

**Comment by pesikj** [comment]
@motyc

Co se má stát v případě, že uživatel založí DJ typu katastr pro vedlejší katastr a poté vedlejší katastr odebere?

**Comment by motyc** [comment]
Asi tomu úplně nerozumím, jak to myslíte. Jako že smaže danou DJ? V tu chvíli by zase zmizel katastr z dalších katastrů. Jak jsem ale psal do #1323, zatím toto nechte být. Issue mám hozené k domluvě u nás a případně zadáme změnový požadavek. Není to ale teď nic palčivého. Je možné, že zvolíme jen tu variantu B a v mapě se to vůbec nebude řešit.

**Comment by pesikj** [comment]
@motyc Myslel jsem to spíše obráceně, tj. další katastr je odebrát z formuláře akce/archeologického záznamu, ale existuje k němu DJ.

**Comment by motyc** [comment]
To by nikdy nemělo nastat. Buď uděláme A nebo B, ale společně to právě z těchto důvodů nedává smysl, protože by to věc jen komplikovalo.

**Comment by jhavrlant** [comment]
@motyc Chci se jen ujistit. Možnost editovat nebo přidávat další katastry u samostatné akce nikde jinde není, určují se podle pianů.

**Comment by motyc** [comment]
@jhavrlant Jestli myslíš oprávnění, tak podle editace akce.

**Comment by jhavrlant** [comment]
@motyc Myslím případ, kdy by se daly další katastry editovat např. zde http://192.168.254.30:8080/arch-z/akce/edit/C-9003601A
Nyní je políčko šedé. V případě DJ typ katastrální území by mělo jít další katastry editovat. Mě jde o to jestli může nastat ještě jiná situace, kdy by šly katastry editovat a nebylo políčko šedé.

**Comment by motyc** [comment]
@jhavrlant Ne, toto je jediný případ.

**Comment by jhavrlant** [comment]
@motyc Při smazání DJ typu katastr se mají další katastry smazat?

**Comment by motyc** [comment]
@jhavrlant Naopak bych to tam spíš nechal, než to bude cíleně přepsáno něčím jiným.

**Comment by jhavrlant** [comment]
@motyc  Editace dalších katastrů má být jen u Akce nebo i u Lokality?

**Comment by motyc** [comment]
@jhavrlant U obojiho.
