### ISSUE TITLE
Arch-z - chyba zapínání vrstev

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1403]
Na obrazovce `arch-z` zlobí zapínání vrstev PIAN a SN (v PAS je to přitom ok).
-- Otevřu http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000038A
-- Ve výchozím stavu mám zapnutou vrstvu PIAN a jdou SN zapnout v pořádku.
-- Když vypnu PIAN a zapnu SN, tak se nezobrazí.
-- Když zapnu PIAN, zapnu SN a vypnu PIAN, je vše ok.
-- Když poté zapnu PIAN, zobrazí se až po pohybu mapou.

**Comment by jiri-bartos-huld** [comment]
pripraveno na MR
