### ISSUE TITLE
Změna dočasných ident na trvalé - úprava pravidel

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1405]
Aktuálně platné pojetí změn dočasných ident_cely na trvalé mají některé nezamýšlené důsledky v kontextu verzování ve Fedoře. Musíme uvážit, zda v zájmu zjednodušení neudělat některé drobné úpravy, avšak s velkým dopadem na verzování a míru vytváření zbytných kopií (tj. zejména na ušetřenou kapacitu úložiště).

Jmenovitě bych navrhoval:
- [x] u AZ, dokumentů a EZ přidělovat trvalý ident_cely nikoli až při archivaci (stav 2 -> 3), ale při odeslání záznamu (stav 1 -> 2); kvůli starým datům je třeba aby se změna prováděla v obou případech (tj. 1->2 i 2->3), jen se bude (jako se již nyní testuje) ověřovat, že záznam zatím má jen dočasný ident a nikoli už trvalý (aby změna neproběhla dvakrát)
- [x] záznamy s dočasným ident_cely (všech kategorií, tj. projekty, AZ, dokumenty, EZ a PIAN) z Fedory po přidělení trvalého ident_cely (tj. po vytvoření nového záznamu ve Fedoře s trvalým ident) mazat - v důsledku po nich zůstane tombstone record + proxy odkaz, vznikne odkaz v modelu deleted a navíc bude zpětný odkaz u aktuálního záznamu v "replaces" a v poznámce v historii; stejný záznam přitom budeme mít nadále uchován pod trvalým id jako první verzi

Veškerá ostatní platná logika by jinak zůstala zachována. Stále by tak neměly nastávat situace, kdy uživatele vytvoří spoustu záznamů, které nikdy nedodělá či smaže a ty nám budou zbytečně zaplevelovat řady ident. Pokud by to někdo dělal přes odesílání záznamů, můžeme to s ním individuálně řešit, protože tak jako tak budeme muset záznamy vypořádat. Hlavní účel tak dočasný ident splní, zároveň ale nebudeme uchovávat zbytnou (totožnou) kopii všech souborů, co se nám do AMČR dostanou.

@pesikj Co si o tom myslíte, je to reálné, nebo je tam nějaký zásadní háček z hlediska implementace?

**Comment by pesikj** [comment]
@motyc Bod 1 mi přijde jednoduchý, jde jen o přesun metody na změnu identu.

U bodu 2 taky nevidím žádný zásadní problém, jen bude potřeba upravit requesty.

**Comment by motyc** [comment]
@pesikj Super, děkuji. Pak to tedy domluvíme zařadíme do toho posledního balíku úprav na začátku roku.

**Comment by pesikj** [comment]
@motyc 
>  záznamy s dočasným ident_cely (všech kategorií, tj. projekty, AZ, dokumenty, EZ a PIAN) z Fedory po přidělení trvalého ident_cely (tj. po vytvoření nového záznamu ve Fedoře s trvalým ident) mazat - v důsledku po nich zůstane tombstone record, vznikne odkaz v modelu deleted a navíc bude zpětný odkaz u aktuálního záznamu v "replaces" a v poznámce v historii; stejný záznam přitom budeme mít nadále uchován pod trvalým id jako první verzi

Můžete zde popsat, jaká by měla být změna oproti současnému stavu? Mně to není vůbec jasný.

**Comment by motyc** [comment]
@pesikj V podstatě to znamená jediné - jakmile záznam s dočasným ID ("X-...") změníme na trvalý, tak po vytvoření nového záznamu z Fedory smazat kontejnery:
https://fedora-test.aiscr.cz/rest/AMCR/record/X-...
https://fedora-test.aiscr.cz/rest/AMCR/model/*/member/X-...

Zachován zůstane jen kontejner https://fedora-test.aiscr.cz/rest/AMCR/model/deleted/member/X-... + odpovídající tombstone pro předchozí dva kontejnery.

**Comment by motyc** [comment]
@pesikj Nakonec jsem to udělal rovnou jako úpravu: https://github.com/ARUP-CAS/aiscr-webamcr/commit/26ea97987fb4f2b7e49423c296908b8939a48bb3

Je tam nechaný jeden komentář, kde je potřeba doplnit volání do Fedory.

**Comment by motyc** [comment]
Omylem jsem to poslal do špatné větve, pardon, už je to opraveno. Správně má být https://github.com/ARUP-CAS/aiscr-webamcr/commit/18e00033ef56c2c043913451a87556b1e4f9d6f4

**Comment by motyc** [comment]
dokumenty - ok
AZ - problémy v #1535 - dotestovat později 
EZ - problémy v #1535 - dotestovat později
