### ISSUE TITLE
Antivirová kontrola nahrávaných dat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1406]
Je třeba ověřovat soubory při nahrávání z hlediska možné přítomnosti škodlivého kódu (antivirová kontrola).

@MichalKminek @vojtakus
1) Dochází již nyní k nějakým kontrolám na úrovni infrastruktury u nás po nahrání, nebo nikoli?
2) Je k tomu případně možné nějak využít náš ESET a je nějak provozovaný v serverovém prostředí, nebo se na to musí jít úplně jinak?
3) Nebylo by nejlepší sáhnout po nějakém open-source řešení, které nabízí i API (např. https://www.clamav.net/)?

Pozor zejména na šifrované soubory (rovnou zamítat).

**Comment by pesikj** [comment]
@motyc V případě ZIPu můžeme v rámci aplikace provést i rozbalení a kontrolu MIME typů u souborů uvnitř archivu. Je to práce tak na 4-8 hodin. Prosím o případné schválení. Vyřešilo by to i problém šifrovaných archivů.

**Comment by motyc** [comment]
Diky za navrh, to zni dobre, tak to tak prosim udelejme.

**Comment by pesikj** [comment]
@motyc 

>  V případě ZIPu můžeme v rámci aplikace provést i rozbalení a kontrolu MIME typů u souborů uvnitř archivu. Je to práce tak na 4-8 hodin. Prosím o případné schválení. Vyřešilo by to i problém šifrovaných archivů.

Toto je implementováno pro všechny podporované archivy.

**Comment by MichalKminek** [comment]
Za mne urcite ano s blokovanim sifrovanych souboru.

**Comment by motyc** [comment]
@MichalKminek Jsme s @pesikj dohodnuti, že se podívá na ClamAV a jak to přesně funguje a pak by se případně ozval, co udělá Huld a co by případně bylo třeba instalovat na naší straně (pokud něco).

**Comment by MichalKminek** [comment]
ClamAV muze bezet na kazdem AMCR serveru a pres socket nebo TCP spojeni nabizet skenovani souboru, rozumi i archivum, ale ne vsem. Muzeme poskytnout tuto sluzbu na nasich serverech. Provozovali bychom clamd daemon, ktery by byl dostupny pres clamscan/clamdscan utilitu.

**Comment by pesikj** [comment]
Určitě by bylo lepší, kdyby ClamAV běžel jako služba na serveru, minimálně se tím zjednoduší deployment aplikace. Připravím tedy odesílání souborů přes socket. Můžete prosím připravit nějakou testovací službu, třeba na serveru .30?

**Comment by MichalKminek** [comment]
Na testovacim serveru je clamav/clamd sluzba na TCP/3310 nebo dostupna pres socket. Primo na serveru jsou k dispozici clamscan - pomalejsi, ale dedi prava spustitele a clamdscan - rychly, ale dostane se jen k datum s pravy pro uzivatele clamscan.

**Comment by motyc** [comment]
Nefunguje komunikace s antivirem. Bude třeba doladit s @MichalKminek

Bohužel tak nyní nelze nahrávat soubory skrz aplikaci.

**Comment by motyc** [comment]
### Test v0.4.27

Bohužel stále nefunkční (test na .30). Blokuje všechny ostatní testy spojené se soubory.
