### ISSUE TITLE
Ladění ../pas/create/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#142]
- [ ] chybí mapové prostředí s podporou potřebných funkcí jako v původní aplikaci; mělo by být jednotně postaveno na Leaflet
- [ ] chybí pole katastrální území, souř. systém, Souřadnice Y / N, Souřadnice X / E (všechny spojeny funkčně s mapou; viz stávající řešení)
- [ ] chybí tlačítko načíst polohu
- [x] v poli s projekty by se v závorce měl vypisovat též vedoucí
- [x] pole projekt by mělo být jediné povinné pro založení a editaci záznamu nálezu (záznam musí jít uložit rozepsaný, pole by měla být povinná až při odeslání archeologovi)
- [x] v poli Projekt je chybná logika zobrazení: (1) pro badatele jen projekty průzkumu organizací, kde spolupracuji v P3 a P4; (2) pro archeologa jen vlastní projekty průzkumu v P3 a P4 + kde spolupracuji; (3) pro archiváře a výše všechny projekty průzkumu. Přinejmenším stavy nejsou správně zohledněny.

**Comment by pesikj** [comment]
Měla by zde tedy být stejná mapa jako při vytváření projektu?

**Comment by motyc** [comment]
Stejná v tom smyslu, že půjde též o Leaflet, nicméně některé funkce musí mít navíc, zejména jde o zadání bodu pomocí souřadnic a načtení aktuální polohy.

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím na úkoly 3-6

**Comment by jnihnat** [comment]
@motyc -ad6, pro jistotu se zeptam ci to dobre chapu:
- badatel - projekty v stave 3 a 4 (Zahajeny a Ukonceny v terenu) a filter na organizace vedouciho, kde je user spolupracovnik.?
- archeolog - to same co badatel + projekty kde vedouci = user ?
- archivar a vyse - vsetky projekty pruzkum vo vsetkych stavoch?

**Comment by motyc** [comment]
ad badatel - ok
ad archeolog - to same co badatel + projekty kde organizace = user.organizace
ad archivar - ok

**Comment by jnihnat** [comment]
upraven filter.
