### ISSUE TITLE
Ladění ../pas/list/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#143]
- [x] chybí pole pro výběr podle historie (viz červeně https://docs.google.com/spreadsheets/d/1EaMlKchCjaVRDwGLYDytvEHgSEPfCqFmkxOAw9PaEQ8/edit#gid=1011776228)

**Comment by pesikj** [comment]
Poslal jsem Vám požadavek na přístup k tabulce

**Comment by motyc** [comment]
@pesikj Pošlete mi prosím svůj Google účet, přidám Vás obecně do sdílených složek.

**Comment by motyc** [comment]
@pesikj Jste tam přidán, dal jsem Vám přístup do celé složky se sdílenými dokumenty, takže snad uvidíte vše potřebné.
