### ISSUE TITLE
Ladění ../pas/spoluprace/list

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#146]
- [x] chybí historie spolupráce
- [x] spolupráci není možné zcela smazat (funkce pro archiváře/admina)
- [x] sloupce v tabulce by měly být: Stav, Vedoucí (formát: "příjmení, jméno (id)"), Organizace (vedoucí), Spolupracovník (formát: "příjmení, jméno (id)"), Organizace (spolupracovník), Aktivace

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím na úkoly 1 a 3

**Comment by jnihnat** [comment]
@motyc 
ad1 co myslite tim "chybí historie spolupráce" - filtr?

**Comment by motyc** [comment]
@jnihnat Nikoli, změny ve spolupráci by měly mít historii podobně jako projekty, akce či dokumenty viz vazby v DB) a na tu je třeba mít možnost se proklikem dostat (změny pro konkrétní spolupráci se zobrazí v tabulce, jakou výše jmenovaných případů).

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím i na druhý bod.

**Comment by jnihnat** [comment]
@motyc 
ad2 - chapu spravne, ze pro archiváře/admina by se mnel zobrazit sloupec navic s linkem "Smazat" - ten link by vedl na do transakcniho okna pro potvrzeni?

**Comment by motyc** [comment]
@jnihnat Ano, chápete správně.
