### ISSUE TITLE
Organizaci u externího zdroje převést na volný text

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1467]
- [x] Upravit SQL migraci (upravit typ pole a vložit hodnotu z hesla)
- [x] Upravit datový typ v modelu
- [x] Upravit XSD pro generování
- [x] Upravit formuláře

**Comment by motyc** [comment]
@pesikj Zde prosím jen o upřesnění - co teď bude aplikace očekávat jako vstup z SQL migrací - bude to pole stále ještě vázané na heslář, nebo už přímo string? Musím podle toho případně doplnit SQL migraci...

**Comment by pesikj** [comment]
@motyc V migracích není nic potřeba upravovat, tj. bude tam ID vázané na heslář.

**Comment by motyc** [comment]
Ok, děkuji.
