### ISSUE TITLE
Ladění ../pas/edit/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#147]
- [ ] chybí mapové prostředí s podporou potřebných funkcí jako v původní aplikaci; mělo by být jednotně postaveno na Leaflet
- [ ] chybí pole katastrální území, souř. systém, Souřadnice Y / N, Souřadnice X / E (všechny spojeny funkčně s mapou; viz stávající řešení)
- [ ] chybí tlačítko načíst polohu
- [x] v poli s projekty by se v závorce měl vypisovat též vedoucí
- [x] nesmí jít editovat pole Projekt (souvisí s přidělením ident_cely)
- [x] chybí tlačítko Zpět
- [x] pole projekt by mělo být jediné povinné pro založení a editaci záznamu nálezu (záznam musí jít uložit rozepsaný, pole by měla být povinná až při odeslání archeologovi; od N2 dále by však již měla být kontrola vždy)

**Comment by jnihnat** [comment]
Body 4-7 dodelany. Pokud ma byt projekt jediny povinny, je potrebne do Edit dodelat jeste mapu pro polohu. Zatim to neni a proto som nechal i polohu ako povinnu pri create.

**Comment by svejci** [comment]
Na kterém serveru je prosím již možné uvedené úpravy vidět? Nevím jestli nekoukám na špatné místo, ale zatím přidané úpravy nevidím. Děkuji

**Comment by jnihnat** [comment]
upravy este nie su mergnoute do hlavni vetve, tak zatim nikde.

**Comment by pesikj** [comment]
Až bude schválený merge request, změny budou na serveru 192.168.254.30.

**Comment by svejci** [comment]
@pesikj Děkuji, jen jsem si nebyl jistý jestli se dívám na správné místo. Počkám až bude vše na serveru 192.168.254.30.

**Comment by pesikj** [comment]
@svejci Na server 192.168.254.30 je nahraná nová verze včetně řešení tohoto issue.

**Comment by svejci** [comment]
@pesikj Děkuji, prošel jsem si nasazené body 4-7 a zobrazení vedoucího u projektů, nemožnost editovat pole Projektu a tlačítko zpět u mne fungují v pořádku. Při založení projektu zůstává stále povinné určění polohy, což ale souvisí s komentářem ze 16.8. ohledně přidání mapy pro edit záznamu.
