### ISSUE TITLE
Ladění ../upload_file/pas/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#148]
- [x] chybí omezení typů souborů (JPG, JPEG, PNG, TIFF, TIF - nikoli case-sensitive)
- [x] chybí tlačítko Zpět

**Comment by jnihnat** [comment]
@motyc prosim ake ma byt omezeni pro stranku "upload_file/dokument/" - nech to omezeni udelam u vsech uz najednou. (Projektove omezeni mam z issue #98 )

**Comment by jnihnat** [comment]
@motyc - U mna sa tlacitko Zpet nachadza a funguje spravne. Mozte prosim este raz otestovat?

**Comment by motyc** [comment]
@jnihnat pro upload_file/dokument/ prosím omezit na PDF.

**Comment by motyc** [comment]
@jnihnat ad tlačítko zpět - ano, už tam je, máte pravdu
