### ISSUE TITLE
Pridat check constraints na vsechny sloupce ktere referuji na heslar

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#15]
Check constraint by mel  byt zalozen na nazvu heslare ne na id-ckach. 

EDIT @motyc: podrobněji viz: https://github.com/ARUP-CAS/aiscr-webamcr/issues/15#issuecomment-1293309590

**Comment by pesikj** [comment]
Zde úplně nerozmím zadání. Contraint musí být nastavený na foreign key. Znamená to, že je potřeba foreign key předělat?
@Najiva @motyc

**Comment by Najiva** [comment]
@pesikj Protoze jsou vsechny heslare v jedne tabulce, cizy klic nedokaze zamezit tomu aby vazba na zaznam z jineho heslare(podmnoziny zaznamu z tabulky heslar) nez na ktery ma ukazovat byla nevalidni. Je potreba pridat novy constraint (check) ktery bude omezovat reference na tabulku heslar pouze na jeji podmnoziny.

**Comment by pesikj** [comment]
@Najiva To lze řešit parametrem limit_choices_to u pole ForeignKey, jde tedy o přidání těchto parametrů do polí, kde chybí?

**Comment by motyc** [comment]
@pesikj Myslím, že když jsme to s @Najiva řešili, tak jsme to chtěli právě mít na úrovni databáze. Jestli jsem dobře hledal, tak "limit_choices_to" je funkce Djanga, nikoli PostgreSQL.

**Comment by Najiva** [comment]
@pesikj Ne. Myslenka byla mit to jak na aplikacni urovni tak na urovni databaze (protoze se s daty manipuluje i mimo aplikace). Jesli to ale David nevyzaduje tak to neni kriticke. Taky proto jsem to issue nedodelal. Zakladal jsem ho podle sveho uvazeni.

**Comment by motyc** [comment]
Souhlasím, že toto můžeme řešit později, není to pro stávající fázi kritické.

**Comment by pesikj** [comment]
Dobře, mně se k tomu moc informací zatím nepodařilo dohledat. Ale přinejhorším se na nějakém testovacím projektu dá vytvořit testovací pole, zmigrovat ho a podívat se create skript databáze.

**Comment by motyc** [comment]
Cílem úpravy je na úrovni DB zamezit tomu, aby došlo užití `heslar.id` ve špatném kontextu. Přehled správného přiřazení hesel podle obsahu `heslar_nazev.nazev` je zde: https://docs.google.com/spreadsheets/d/1mwz3N31idVVX0yDKXVTtk161wddK3oWSASuN24TwCd4/edit#gid=0

Je třeba omezit (pravděpodobně pomocí check constraint) rozsah přípustných hodnot pro daná pole, aby nemohlo dojít k chybě.

**Comment by motyc** [comment]
Vyřešeno v https://github.com/ARUP-CAS/aiscr-webamcr/commit/2ec64abb1ba078259a47c29d52d7692541c6f8da
