### ISSUE TITLE
PAS - chyba pojmenování souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1508]
http://192.168.254.30:8080/pas/detail/M-202101534-N00212 - chyba pojmenování souborů (všechny se nahrávají se stejným názvem)

**Comment by pesikj** [comment]
@motyc Je někde specifikováno, jak to má fungovat? V metodě na přejmenování je regex, který počítá s číslem na začátku jména souboru, ale protože tam to číslo není, nevloží se na konec názvu písmeno. Tak nevím, kde je vlastně chyba.

**Comment by motyc** [comment]
@pesikj V PAS je správné schéma např. M202105907N00170F01, složené z SN.ident_cely (bez pomlček) + "F" + pořadové číslo na dvě číslice. Pořadové číslo se stanovuje jako maximum, tj. případné mezery v řadě se nezaplňují.
