### ISSUE TITLE
Ladění testů, logování a monitoringu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1523]
**Testy**
- [x] @jhavrlant zkusí lokálně rozchodit Fedoru, k čemuž potřebuje konfiguraci nasazení od VB (@motyc  již poskytl příkazy pro vygenerování základní struktury; ještě možná bude třeba dořešit správné uživatelské účty - to si případně dáme vědět mimo GitHub)
- [x] databázi pro testování užívání připravíme jako ořezanou kopii skutečné databáze; až ji bude @jhavrlant  potřebovat, tak se prosím obrátit na @motyc a nějak to vymyslíme

**Logování**
- [x] @MichalKminek, @vojtakus a @pesikj společně zajistit sklízení logů z PostgreSQL a Fedory do Elasticsearch
- [x] @MichalKminek připravit volume pro logy a předat info @pesikj, kam je má směřovat

**Monitoring**
- [x] @vojtakus - zprovoznit monitoring Postgres přes https://grafana.com/oss/prometheus/exporters/postgres-exporter/ a předat informace @pesikj 
- [x] @pesikj - nastavit uchování logů z monitoringu (asi dát do stejného volume, jako jiné logy?)
- [x] @pesikj - dořešit propojení cAdvisor s Prometheem/Grafanou
- [x] @vojtakus @MichalKminek Nyní data z monitoringu prostředků (cAdvisor) máme dva dny zpět. Bylo by dobré prodloužit na 30 dní, aby bylo konzistentní se zbytkem.

**Healthcheck**
- [x] @pesikj + @vojtakus - doplnit test a závislosti pro Fedoru

**Optimpalizace**
- [x] @MichalKminek zajistit optimalizaci nastavení Postgres na test serveru
- [x] @MichalKminek nebo @vojtakus vložit logování pro dlouhé dotazy (> 1 s - nastavení poladíme) - https://wiki.postgresql.org/wiki/Logging_Difficult_Queries

**Jiné**
- [x] @pesikj analyzovat možnosti pro antivir v rámci #1406
- [ ] @MichalKminek a @vojtakus - zanést související informace do dokumentace prostředí
- [x] @pesikj doplnit do Grafany a Kibany admin účty pro @MichalKminek, @vojtakus a @jhavrlant a předat jim přístupy

**Comment by vojtakus** [comment]
Zapnuto zaznamenávání dlouhých dotazů v PostgreSQL na amcr-w-test a amcr-w-tr.

**Comment by vojtakus** [comment]
V testovcím prostředí spuštěn Postgres Exporter jako samostatný kontejner (zatím mimo swarm). Připojen přes Prometheus. V Grafana přidána přehledová nástěnka Postgres Overview.

**Comment by motyc** [comment]
Díky @pesikj a @vojtakus za učiněné pokroky. Ten monitoring výkonu teď funguje skvěle, a to jak pro Cadvisor, tak pro Postgres. Myslím, že pro ladění to bude opravdu velmi užitečné.

Zbývá nám tedy dořešit logování, uchování historie monitoringu a nastavení healthchecku na Fedoru (rozdělení úkolů viz první příspěvek).

Nevím také, zda @MichalKminek už upravil to základní nastavení Postges na .30. Pokud ne, prosím o brzké vyřešení, abychom dostávali relevantnější čísla z testů.
