### ISSUE TITLE
Nahrazování souborů - samovolné přesměrování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1532]
http://192.168.254.30:8080/soubor/nahrat/dokument/nahradit/C-TX-194106081/529917?next=/dokument/detail/C-TX-194106081 - po otevření po pár vteřinách přesměruje na http://192.168.254.30:8080/dokument/detail/C-TX-194106081

Soubory tak nyní nejde nahrazovat.

**Comment by pesikj** [comment]
@motyc Teď jsem to testoval a k žádnému přesměrování nedošlo.
