### ISSUE TITLE
Chyby aktualizace katastrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1534]
- [x] Pokud upravím nepotvrzený PIAN (posunu jej v mapě), katastry se aktualizují jen pro arch. záznam, v rámci kterého pracuji. Pokud je na PIAN napojeno více AZ, u nich se katastry nezmění podle aktuální polohy PIAN.
- [x] Při úpravě PIAN se asi v některých případech neaktualizují další katastry. Při testování to vzniklo odpojením stávajícího PIAN a připojením na jiný, kdy se aktualizoval pouze hlavní katastr.
- [x] Neaktualizují se katastry při připojení záznamu na existující PIAN.

**Comment by pesikj** [comment]
@motyc Zde prosím o specifikaci, jak by to mělo fungovat, především co se týká úpravy vedlejších katastrů. To mi není jasné vůbec.

**Comment by pesikj** [comment]
@motyc Ano, souhlasím.

**Comment by jhavrlant** [comment]
@motyc Co se má stát s katastry při odpojení pianu, kdy AZ už na sebe nemá připojen žádný pian. Asi mu zůstane pouze aktuální hlavní katastr?

**Comment by motyc** [comment]
@jhavrlant Ano, přesně tak.
