### ISSUE TITLE
Chybí možnost zadat DJ typu Katastrální území u sam. akcí při vytváření DJ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1543]
Katastrální území nelze zadat při zápisu nové DJ u samostatné akce, ale pouze při editaci již existující. Stačí to doplnit do toho zápisu: http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000000052A/dj/zapsat

U lokalit to funguje v pořádku.

**Comment by pesikj** [comment]
@motyc S těmi úpravami to souviset nebude. Tato část kódu už příliš kombinovaná a je třeba nějaká revize. Vygeneroval jsem pomocí ChatGPT popis, jaké typy DJ jsou k dispozici. Kód je níže, podle mě je to popsané srozumitelně. Prosím o revizi textu a specifikaci chyb.

Tento kód určuje, jaký seznam dostupných typů dokumentační jednotky bude nabídnut na základě různých podmínek souvisejících s dokumentační jednotkou a souvisejícími jednotkami.

1. Nejprve se seznam dostupných typů dokumentační jednotky nastaví tak, aby obsahoval všechny typy dokumentačních jednotek.

2. Jestliže typ archivního záznamu je lokality, seznam dostupných typů dokumentační jednotky se omezuje pouze na typy 'Lokalita' a 'Katastr'.

3. Pokud existuje konkrétní dokumentační jednotka s typem 'Část akce', seznam dostupných typů dokumentační jednotky se omezuje pouze na typ 'Část akce'.

4. Další logika závisí na tom, zda jsou k dispozici související dokumentační jednotky (`jednotky`):

   - Pokud jsou mezi souvisejícími jednotkami nějaké typu 'Sonda', zohledňují se různé podmínky, jako je existence dalších 'Sond' před aktuální jednotkou, přítomnost ADB v jiných jednotkách nebo pokud je více 'Sond'. Na základě těchto podmínek se seznam dostupných typů dokumentační jednotky upraví.
   
   - Pokud má dokumentační jednotka typ 'Celek akce' nebo 'Katastr', seznam dostupných typů dokumentační jednotky se upraví tak, aby zahrnoval typy 'Celek akce', 'Sonda' a potenciálně 'Katastr', v závislosti na tom, jestli je akce definována jako samostatná a zda existují jednotky typu 'Část akce'.

   - V případě, že mezi souvisejícími jednotkami jsou nějaké typu 'Celek akce', seznam dostupných typů dokumentační jednotky se omezuje na typ 'Část akce'.

5. Pokud nejsou splněny žádné z výše uvedených podmínek, seznam dostupných typů dokumentační jednotky se standardně nastaví na typy 'Celek akce' a 'Sonda'.

6. Nakonec, pokud mezi souvisejícími jednotkami existují nějaké typu 'Katastr' a dokumentační jednotka nemá typ 'Katastr' nebo vůbec žádný typ, typ 'Katastr' se ze seznamu dostupných typů dokumentační jednotky vyloučí.

Tento kód tedy dynamicky určuje, jaké typy dokumentačních jednotek jsou pro danou situaci vhodné nebo dostupné na základě existujících vztahů mezi jednotkami a kontextu akce.

**Comment by motyc** [comment]
@pesikj Vyloženě chybu tam takto nevidím (jen 4 je trošku kryptický). Každopádně se tam píše `5. Pokud nejsou splněny žádné z výše uvedených podmínek, seznam dostupných typů dokumentační jednotky se standardně nastaví na typy 'Celek akce' a 'Sonda'.` - to platí pro projektové akce. Pokud jde o samostatnou akci, mělo by být dostupné 'Celek akce', 'Sonda' a 'Katastrální území'.

Zvláštní fakt je, že ještě začátkem týdne to bylo ok. Musel to rozbít nějaký z nedávných commitů.
