### ISSUE TITLE
Chybné přečíslování nepotvrzeného PIAN při úpravě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1545]
Pokud vytvořím nepotvrzený PIAN na nějakém místě a pak jej upravím a posunu tak, že se octne na jiném listu ZM50, samovolně se změní jeho ident_cely. Tato změna není nijak ošetřena ve Fedoře atd. a není žádoucí.

K přečíslování na správný list může případně dojít při potvrzení PIAN (nevím jak přesně tento proces funguje, zda se to dozuje ze skutečné polohy, nebo z původního dočasného ident_cely...), ale nikoli prostou editací.

**Comment by pesikj** [comment]
@motyc Prosím o přesný postup, jak chybu nasimulovat. Funkce `get_temporary_pian_ident()` je volána pouze v pohledu `create()`, tak netuším, jak by se toto mohlo dít.

**Comment by motyc** [comment]
@pesikj Také se mi to nedaří nasimulovat a po pravdě ani stopováním ve Fedoře se mi nedaří najít, kde jsem to vydedukoval. Myslím, že jsem prostě byl nepozorný a překoukl se při testování. Omlouvám se a issue zavírám.
