### ISSUE TITLE
Lokality - chyba řazení podle dalších katastrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1552]
http://192.168.254.30:8080/arch-z/lokalita/vyber?sort=dalsi_katastry&sort=nazev

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/b74ca60c-800a-4bf3-9785-c68a2bd3d0d5)

**Comment by motyc** [comment]
@pesikj Vypadá ok, jen po seřazení je na začátku seznamu několik divných záznamů bez dalšího katastru, i když jinak je to řazené dobře. Nevíte, čím to je?
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/79eea9e5-a9b6-44ae-9b0e-7d8fae865463)

**Comment by pesikj** [comment]
@motyc Byl tam prázdný řetězec místo null hodnoty, už jsem to opravil, aby se to tak neukládalo.
