### ISSUE TITLE
Responsivita - levé menu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1557]
- [ ] Tlačítko pro zavření menu na mobilu mizí mimo obrazovku:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2e430ea2-1899-4c1a-a527-b9f1469e6687)

**Comment by pesikj** [comment]
@motyc A kam s ním, pokud je menu širší než obrazovka?

**Comment by pesikj** [comment]
@motyc A logo chcete posunout dolů?

**Comment by motyc** [comment]
Ano, tak jsem to myslel.
