### ISSUE TITLE
Responsivita - tabulky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1565]
- [x] V zobrazení tabletu se nezobrazují tooltipy u zkrácených údajů.
- [x] V mobilním zobrazení se tooltipy zobrazí, ale zůstávají viset při užití kroku zpět, a to i přes formulář filtrace:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/da0bf806-9fcf-45ca-8bd8-37e346994dd8)
- [x] Lister je na mobilu bezva, ale v zobrazení tabletu je chvíle, kdy to zlobí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2fddbabb-3979-4870-b71f-8393e88cdd31)

**Comment by pesikj** [comment]
@motyc 

>  V mobilním zobrazení se tooltipy zobrazí, ale zůstávají viset při užití kroku zpět, a to i přes formulář filtrace:

Toto se mi nepodařilo nasimulovat, zkoušel jsem Chrome a Firefox. V obojím tooltipy mizí.

**Comment by motyc** [comment]
@pesikj Otestuji znovu

**Comment by motyc** [comment]
### Test v0.4.61

- [ ] V mobilním zobrazení se tooltipy zobrazí, ale zůstávají viset při užití kroku zpět, a to i přes formulář filtrace _- popisuji přesný postup pro nasimulování: (1) v Chrome zapnu F12 a nastavím zobrazení tabletu/mobilu; (2) zobrazím libovolnou tabulku s výběrem záznamů; (3) otevřu detail záznamu; (4) použiji tlačítko "zpět" v prohlížeči; (5) tooltip je viditelný a nedá se ho zbavit jinak než aktualizací celého okna_
- [ ] Lister je na mobilu bezva, ale v zobrazení tabletu je chvíle, kdy to zlobí _- stále platné_:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/4e28c63d-84f9-4364-8b7a-856b5c210659)

**Comment by pesikj** [comment]
@motyc Děkuji za postup, ale problém se mi přesto nepodařilo nasimulovat. Přidal jsem skrytí existujících tooltipů po načtení aplikace, snad to problém vyřeší.
