### ISSUE TITLE
Lokalita - chybí možnost změnit katastrální území

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1569]
http://192.168.254.30:8080/arch-z/lokalita/detail/X-C-L000000023/dj/X-C-L000000023-D01 - v menu nevidím možnost pro změnu katastru

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2f142611-b808-463d-a94a-ab42c65f9e0e)

Ověřit, že bude ošetřeno i #1533

**Comment by pesikj** [comment]
@motyc Honzo podívej se na to prosím, to asi souvisí s právy.
