### ISSUE TITLE
Fedora - kontroly při ukládání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1572]
- [x] Do třídy `check_container_deleted_or_not_exists` ještě doplnit test na GET_LINK (prosím o kontrolu - jde spíše o koncepci doplnění, než přesný zápis)
```python
def check_container_deleted_or_not_exists(cls, ident_cely):
        logger.debug("core_repository_connector.check_container_is_deleted.start",
                     extra={"ident_cely": ident_cely})
        result = cls._send_request(f"{cls.get_base_url()}/record/{ident_cely}", FedoraRequestType.GET_CONTAINER)
        result_2 = cls._send_request(f"{cls.get_base_url()}/model/deleted/member/{ident_cely}",
                                     FedoraRequestType.GET_DELETED_LINK)
        result_3 = cls._send_request(f"{cls.get_base_url()}/model/{self._get_model_name()}/member/{ident_cely}",
                                     FedoraRequestType.GET_LINK)

        if result.status_code == 200:
            if cls.check_container_deleted(ident_cely):
                if result_2.status_code == 200:
                    if result_3.status_code == 200:    
                        logger.debug("core_repository_connector.check_container_is_deleted.true",
                                 extra={"ident_cely": ident_cely, "result_text": result.text})
                        return True
        elif result.status_code == 404 and result_2.status_code == 404 and result_3.status_code == 404:
            logger.debug("core_repository_connector.check_container_is_deleted.true",
                         extra={"ident_cely": ident_cely, "result_text": result.text})
            return True
        logger.debug("core_repository_connector.check_container_is_deleted.false",
                     extra={"ident_cely": ident_cely, "result_text": result.text})
        return False
``` 
- [x] Před vytvořením libovolného nového kontejneru vždy spustit `check_container_deleted_or_not_exists` a vrátit chybu, pokud neprojde (nyní jen pro akce a SN).
- [x] Před úpravou kontejneru vždy zkontrolovat že GET_CONTAINER a GET_LINK vrací 200 a vrátit chybu, pokud neprojde.
- [x] Pří testech ve Fedoře se opírat pokud možno vždy přímo o status code vracený jako header, nikoli o obsažené texty, pokud to není vyloženě nutné (zkontrolovat kód a případně upravit).
 
Díval jsem se, zda jde nějak snadno nahradit ten test `regex = re.compile(r"dcterms:type *\"deleted\" *;")`, ale bohužel jde filtrovat jen podle nativních polí, takže zde jiná cesta není.

**Comment by motyc** [comment]
@pesikj Navrhoval bych také řešit společně s těmi signály a transakcemi...

**Comment by pesikj** [comment]
@motyc Souhlasím.

**Comment by motyc** [comment]
@pesikj Tady pro jistotu, abychom se nepochopili špatně - ta poznámka "nyní jen pro akce a SN" byla myšlena tak, že dosud to bylo udělané jen pro akce a SN, ale že se to právě má nově aplikovat všude

**Comment by motyc** [comment]
### Test v0.4.36
- [ ] `check_container_deleted_or_not_exists` chybí pro model letů (https://fedora-test.aiscr.cz/rest/AMCR/model/let)

Jinak vše ok.
