### ISSUE TITLE
Oznámení - vrstva undefined

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1575]
V oznamovacím formuláři (http://192.168.254.30:8080/oznameni/) se v mapě objevila vrstva "undefined". Její vypínání a zapínání nic nedělá.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/fd7acdae-3c04-4e25-a9fd-63378cb86851)

**Comment by jiri-bartos-huld** [comment]
@motyc @pesikj  tohle je drobnost v rosete chybi preklad pro 'lokalizace', prosim doplnit
var overlays = {
    [map_translations['cuzkKatastralniMapa']]: cuzkWMS,
    [map_translations['cuzkKatastralniUzemi']]: cuzkWMS2,
    [map_translations['lokalizace']]: poi
};

**Comment by motyc** [comment]
@jiri-bartos-huld Ten překlad je jedna věc, ale spíš mě mátlo, že nic nedělá to klikání... To také souvisí s chybu textace?

**Comment by jiri-bartos-huld** [comment]
@motyc Ne, tohle je ted opraveno na  MR
