### ISSUE TITLE
Chyba funkce Výchozí zobrazení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1576]
http://192.168.254.30:8080/projekt/zapsat

- [x] Pokud funkci použiji, pouze zmizí bod z mapy, ale mapa se nevrátí do výchozího zobrazení
- [x] Navíc zjevně souřadnice někde zůstanou v mezipaměti, protože když pak formulář odešlu, nevadí tomu, že bod v mapě není a vezme to poslední dostupné souřadnice. Po kliknutí na tlačítko by měl systém původní souřadnice zapomenou (a v důsledku i vyprázdnit pole "Hlavní katastr".

Při editaci (např. http://192.168.254.30:8080/projekt/edit/C-202300526) se to chová správně.

**Comment by jiri-bartos-huld** [comment]
@pesikj pridano na MR

**Comment by motyc** [comment]
@pesikj Z hlediska mapy už ok, jen na http://192.168.254.30:8080/projekt/zapsat chybí test, že jsou nějaké souřadnice vyplněné (tj. že existuje bod mapě). Když nyní nějaký zadám, kliknu na "Výchozí zobrazení" a odešlu záznam. Testy to projde, byť záznam nemá žádný bod (nejde to řešit jako not null v DB, protože hodně projektů z minulosti bod nemá).
