### ISSUE TITLE
PAS - chyba žádosti o spolupráci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1589]
http://192.168.254.30:8080/pas/spoluprace/zadost

Po odeslání žádosti chyba:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/28aa2f3a-79fc-439e-a0f1-3672acdbdabc)

**Comment by motyc** [comment]
### Test v0.3.5z123
- [ ] První žádost prošla, na druhou a jakoukoli další teď již hlásí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f4802178-92c4-4f2b-bbfd-4d19fa5450e8)

**Comment by pesikj** [comment]
@motyc Prosím o návod, jak toto nasimulovat.

**Comment by motyc** [comment]
@pesikj Přihlásil jsem se jako libovolný badatel (147022@mail.muni.cz) a požádal o spolupráci nějakého archeologa - v daném případě jsem zkoušel novak@arup.cas.cz a frolik@arup.cas.cz. První žádost na novak@arup.cas.cz mi prošla, pak už ale nefungovalo nic.
