### ISSUE TITLE
Přihlašovací jméno je case-sensitive

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1591]
Přihlašovací jméno je case-sensitive a navíc velká písmena nejde zadat, protože se automaticky upraví na lower-case a pokud jsou tedy v mailu velká písmena, nikdy se uživatel nepřihlásí. Uživatelské jméno mělo být case-insensitive.

**Comment by pesikj** [comment]
@motyc 

> protože se automaticky upraví na lower-case a pokud jsou tedy v mailu velká písmena, nikdy se uživatel nepřihlásí

Pokud uživatel zadá do políčka pro e-mail velká písmena, jsou převedena na malá. E-mailová adresa není case sensitive, takže e-mail je doručen bez ohledu na velikost písmen. Přihlašování je tedy možné. Pokud chcete změnu přihlašovacího mechanismu, je to požadavek na nový vývoj.

**Comment by motyc** [comment]
@pesikj Jenže se nepřevádí na lower-case to, co je uloženo v DB, ale jen to, co člověk zadá při přihlášení. Pokud tak email v DB obsahuje velká písmena, přihlásit se nejde. To je myslím chyba. Chápu dobře, že Django při registraci dělá lower-case pro pole email před uložením? Pokud to tak je, pak by stačilo prostě jen opravit data při migraci...

**Comment by pesikj** [comment]
@motyc Ten převod dělá už javascript při vyplňování pole, takže do databáze se uloží malá písmena.

**Comment by motyc** [comment]
@pesikj Ok, pak tedy opravdu stačí opravit data. To zařídím já.
