### ISSUE TITLE
Too many clients

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1597]
Při procházení záznamu na mne najednou vyskočila zvláštní chyba. Bude třeba prověřit, co se stalo a proč (pouze jsem editoval mapu, měnil velikost okna a následně zkusil znovu načíst DJ. Snad půjde vyčíst z logů (čas viz screenshot). Po opětovném načtení vše jelo ok.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/cc53f09f-5146-4c4f-83ba-6ec618a428f4)

**Comment by motyc** [comment]
Nasymulováno podruhé opakovaným klikáním na DJ u akce http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000038A

**Comment by pesikj** [comment]
@motyc Vypadá to, že to shazuje databázi.

**Comment by motyc** [comment]
Dnes jsme to řešili s @vojtakus, protože DB se úplně zasekla. Aplikace za sebou zjevně nechává spoustu neuzavřených spojení (nyní 200), které se tam nakumulovaly. Je třeba to v aplikaci vyřešit. Je to dobře vidět i v Grafaně:

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/4a9d616b-7870-4f3e-8bec-556bfc5b0ee1)

Zdá se, že to vzroste vždy v noci skokově ve stejný čas o 100 spojení, není náhodou nějak zase zapnuté #387 a nesouvisí to s tím?

**Comment by pesikj** [comment]
@motyc Jediná úloha, která je spuštěná, je `send-notifications-E-N-01-02`.

**Comment by motyc** [comment]
@pesikj Pak to musí souviset s nějakou chybou v #389 a je to primárně na @jnihnat

**Comment by motyc** [comment]
Problém ukázal na nedotažené řešení pro #1357. Bude to třeba ještě doplnit tak, aby to ověřovalo, že frontou prochází příkazy. To by odhalilo i tuto chybu.
