### ISSUE TITLE
Chyba migrace notifikací

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1608]
- [x] Migrace myslím nemůže fungovat, protože funkce `get_content_type` vybírá z projektů, ale přitom ty vazby z mají být na `ruian_kraj`
https://github.com/ARUP-CAS/aiscr-webamcr/blob/5f28436e1f48fe8b5ccc7303d96d01862987488f/migrace/copy_data.py#L75
- [x] Kde a jak se z tabulky `notifikace_typ` využívají sloupce `text_cs` a `text_en`? Pokud k ničemu, tak smazat a upravit také https://github.com/ARUP-CAS/aiscr-webamcr/blob/7f4879e1c605456b1b9471199d4e6d71f3f4999b/migrace/copy_data.py#L89

**Comment by pesikj** [comment]
@motyc 

>  Kde a jak se z tabulky notifikace_typ využívají sloupce text_cs a text_en? Pokud k ničemu, tak smazat a upravit také

Je to použito v admin rozhraní.

**Comment by motyc** [comment]
@pesikj Mrkneme na to spolu, ale myslím, že bychom se bez toho i tak obešli. Ty předměty jsou definované přímo v kódu a nevím, co jiného vlastně má být obsahem.
