### ISSUE TITLE
Úprava deployment procesu pro nasazení na různých prostředích

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1625]
- [x] Prostředí pro nasazení aplikace se mohou lišit. Je třeba buď mít možnost explicitně stanovit, která deployment konfigurace se má použít (mít různé soubory pro různá prostředí), nebo mít možnost parametrizovat, že se některé části pro některá prostředí nepoužijí. Nyní zejména dochází ke konfliktům kvůli rozdílným prostředím na test a dev serveru.
- [x] Nahradit deprecated funkce v deployment procesu (https://github.com/ARUP-CAS/aiscr-webamcr/actions/runs/8114614247):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a8858752-40c6-4f9b-8a37-fcbbd82494be)

**Comment by pesikj** [comment]
@motyc Vyřešeno tak že skript `prod_deploy.sh` má parametr `-d`. Pokud je spuštěn s tímto parametrem, proběhne deployment kontejneru s databází, jinak ne.

**Comment by motyc** [comment]
@pesikj Super. Řešil jste i ty deprecated funkce?

**Comment by pesikj** [comment]
Ano.
