### ISSUE TITLE
Rozbitý formulář historie

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1679]
Patrně navazuje na #1043
- [ ] Z kódu vyplývá, že došlo ke sjednocení chování historie pro všechny pohledy. To však vedlo k tomu, že pole "Typ změny" nabízí k výběru hodnoty relevantní pouze pro dokumenty, nikoli odpovídající danému typu záznamu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f702dc4d-0e32-476f-8e6b-8909ec5cd576)

Může s tím souviset i chyba kalendářů zmiňovaná v #1133

**Comment by motyc** [comment]
### Test v0.4.29
- [ ] Pro Projekt, Samostatná akce, Lokalita a PAS chybí položka "KAT" - původní řešení viz https://github.com/ARUP-CAS/aiscr-webamcr/pull/1646 (asi omylem přepsáno v rámci paralelních změn)
- [ ] Pro všechny menu typu "Moje záznamy" se najednou do uživatele vloží vždy hodnota "1", místo skutečného id přihlášeného uživatele. Vrací to tak nesmysly.

Mám dojem, že celkově dotazy na historii vrací nějak zmatečné výsledky, ale budu to muset více otestovat (teď nestíhám). Hlavně prosím ověřit, že platí ten slučovací poměr mezi typem, datumy, uživatelem a organizací (všude musí být AND na úrovni jednoho záznamu v historii). Tuším, že v tom by zase mohl být zakopaný pes. Mám ale zároveň dojem, že se to nechová všude stejně.

**Comment by pesikj** [comment]
@motyc Není spíš problém v tom, že není možné vyplnit datum?

**Comment by pesikj** [comment]
@motyc Na aktuální vývojové verzi už to nedokážu nasimulovat, zkuste to prosím otestovat do deploymentu nové verze.

Jinak s těmi daty byl skutečně problém, v implementaci to úplně chybělo, v nové verzi bude též opraveno.

**Comment by motyc** [comment]
### Test v0.4.31
- [ ] Pro Projekt, Samostatná akce, Lokalita a PAS chybí položka "KAT" - původní řešení viz https://github.com/ARUP-CAS/aiscr-webamcr/pull/1646 (asi omylem přepsáno v rámci paralelních změn)
- [ ] http://192.168.254.30:8080/projekt/vyber?historie_typ_zmeny=PX1&historie_uzivatel_organizace=315733 - nevrátí nic, přitom takové projekty existují (http://192.168.254.30:8080/historie/projekt/C-201336151)
- [ ] http://192.168.254.30:8080/projekt/vyber?historie_datum_zmeny_od_after=23.5.2013&historie_datum_zmeny_od_before=23.5.2013&historie_uzivatel=91&historie_uzivatel_organizace=315733 - `Field 'id' expected a number but got [<User: Jílková, Štěpánka (U-000326, Archaia)>].`
