### ISSUE TITLE
Dokument - naše záznamy - duplikace záznamů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1681]
Patrně souvisí s #1043

http://192.168.254.30:8080/dokument/vyber?historie_typ_zmeny=D01&historie_uzivatel_organizace=315755&sort=stav&sort=ident_cely

Záznamy se v tabulce duplikují. Nevím, zda to nebude problém i pro jiné obdobné případy (z prvního pohledu to tak nepůsobí).

**Comment by motyc** [comment]
@pesikj Teď mi daný dotaz/položka v menu nevrací nic.

**Comment by pesikj** [comment]
@motyc Chybu jsem našel a opravil, bude to vyřešeno v příští verzi.
