### ISSUE TITLE
Chyba zobrazení PIAN záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1683]
http://192.168.254.30:8080/arch-z/akce/detail/C-9116962A 

Ve výchozím zobrazení se v pořádku provede zoom na PIAN D01, ale ten není vidět:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/977fec4a-78e8-440c-b291-885687570214)

Problém se zdá být v tom, že je nějak podivně nastaven výpočet okna, které PIAN se mají zobrazit. Po posunu mapy se totiž v určitou chvíli PIAN u D01 zobrazí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/26b7387f-c061-4dbc-88cd-f4880c073dc5)

Podobně to funguje s PIAN pařícímu k D02, který se zobrazí jen někdy:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/246a1135-f1ae-401f-8129-1def8684eadb)

Zajímavé však je, že PIAN pro D03 se zobrazí vždy bez problémů:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/72cb926b-2f4d-49ba-b49c-fd5bd7c09349)

**Comment by jhavrlant** [comment]
@motyc Když najedu na nějaký pian myší (fialový, zelený nebo žlutý), zvýrazní se žlutě. Neměla by se použít jiná barva, aby nebyla stejná jako žlutá DJ?

**Comment by motyc** [comment]
@jhavrlant Mě to dosud po pravdě nevadilo, protože to je také svým způsobem výběr a vlastně to celkem pěkně koresponduje. Nebo Ti to přijde zmatečné?

**Comment by jhavrlant** [comment]
@motyc Je to otázka zvyku. Jen není vidět nájezd na žlutý prvek.

**Comment by motyc** [comment]
@jhavrlant Ten je ale zase sám o sobě zvýrazněný, tak to snad stačí. Kdyby to nedělalo dobrotu, upravíme to časem.

**Comment by jhavrlant** [comment]
@motyc V aplikaci s kromě jednobarevných špendlíků používají také více barevné 
![pin_purple_point2](https://github.com/ARUP-CAS/aiscr-webamcr/assets/155644357/76364e9d-6454-4cb4-8b5a-7101df62cbce)
![pin_purple](https://github.com/ARUP-CAS/aiscr-webamcr/assets/155644357/f1bc3fd3-c27e-4d35-bc73-23e004e4f8f6)
![pin_green_point2](https://github.com/ARUP-CAS/aiscr-webamcr/assets/155644357/a59efcc4-025d-4c70-9856-6021df22e01f)
![pin_green](https://github.com/ARUP-CAS/aiscr-webamcr/assets/155644357/d94ee63b-db4d-4dd8-9bee-cb5ca9f8fd1b)
Tak se chci zeptat na význam.

**Comment by motyc** [comment]
@jhavrlant Obecně vysvětlení/původní zadání najdeš v těchto dvou issues:
https://github.com/ARUP-CAS/aiscr-webamcr/issues/303
https://github.com/ARUP-CAS/aiscr-webamcr/issues/302

Je to ale tak, že plná tečka jsou bodové PIAN, prázdná tečka jsou definiční body linií/ploch (ty jsou navíc i v mapě menší).

**Comment by jhavrlant** [comment]
@motyc Je zde problém při vytváření pianu z katastru. Geometrie katastru je uložená jako MULTIPOLYGON, takže vytvořený pian ji převezme a uloží v pianu. Nevím jestli to není chyba, když MULTIPOLYGON v pianu běžně nepodporujeme.

**Comment by motyc** [comment]
@jhavrlant V tom by myslím problém být neměl, protože ho nikdy jako takový nezobrazujeme a needitujeme. Uložený být může a ničemu to nevadí. Některé katastry bohužel mají více částí, takže to jinak být nemůže.
