### ISSUE TITLE
Katastry nevést vždy jako jednotky PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#17]
Katastry bychom měli mezi PIAN zařadit až při prvním použití, neměly by tak existovat zbytečné PIAN 4 (přesnost na katastr) bez vazeb. V praxi to znamená:
- [x] při migraci smazat PIAN s přesností 4 v případech, kdy na ně není napojena žádná dokumentační jednotka; dotaz na výběr je: `SELECT pian.* FROM heslar_nazev INNER JOIN (heslar INNER JOIN (pian LEFT JOIN dokumentacni_jednotka ON pian.id = dokumentacni_jednotka.pian) ON heslar.ID = pian.presnost) ON heslar_nazev.ID = heslar.nazev_heslare WHERE (((heslar_nazev.nazev)='pian_presnost') AND ((heslar.zkratka)='4' AND ((dokumentacni_jednotka.id) Is Null)))`
- [x] při vytvoření nelokalizované dokumentační jednotky (viz #319 a #318) automaticky připojit existující PIAN 4 katastru, pokud již existuje (tj. když `ruian_katastr.pian is not null` tak `dokumentacni_jednotka.pian = ruian_katastr.pian`)
- [x] nebo automaticky vytvořit nový PIAN 4, pokud jej ještě daný katastr PIAN přiřazen nemá (tj. když `ruian_katastr.pian is null`), a následně jej připojit k DJ; vytvoření proběhne tak, že:
-- `pian.stav` = 2
-- `pian.zm10` - určit podle `ruain_katastr.definicni_bod`
-- `pian.zm50` - podle `pian.zm10`
-- `pian.ident_cely` - podle `pian.zm50` a standardní procedury přidělování permanentního ID
-- `pian.typ` = plocha
-- `pian.presnost` = 4
-- `pian.geom` = `ruian_katastr.hranice`
-- `pian.historie` - standardně zaznamenat vytvoření PIAN
-- `ruian.pian` = `pian.ident_cely`

**Comment by pesikj** [comment]
@motyc 

> Je na něj napojená nějaká dokumentační jednotka (ať již akce či lokality).

Jak toto konkrétně může uživatel provést?

**Comment by motyc** [comment]
@pesikj Jde o funkci, která souvisí se samostatnými akcemi a lokalitami, viz #318 a #319 - v těchto případech je možné nezadat přesnou lokalizaci DJ, ale lokalizovat ji s přesností "4", tedy na katastr.

**Comment by pesikj** [comment]
@motyc Rozumím tomu tedy správně, že to tedy půjde až v nově vytvořených částech aplikace a ve stávajících (např. u DJ u akce u projektu) to nejde? Podmínka níže brání zobrazení přesnosti na katastr v komentářích.

`limit_choices_to=Q(nazev_heslare=HESLAR_PIAN_PRESNOST) & Q(zkratka__lt="4")`

Myslím, že smysl dává toto implementovat až po #318 a #319.

**Comment by motyc** [comment]
@pesikj Ano, je to tak, ale máme to ve stávajících datech (to jen pro info). Klidně to můžeme odsunout, pokud to je praktičtější, než to dělat souběžně. Přišlo mi ale, že když se bude pracovat na těch dvou modulech, už by se mělo to chování nastavit podle tohoto issue (to je ten druhý bod). Úplně by nedávalo smysl to udělat nějak a pak to předělávat...

**Comment by pesikj** [comment]
@motyc Je možné to udělat souběžně, ale implementace těch modulů je nutná, aby bylo řešení možné otestovat.

**Comment by motyc** [comment]
@pesikj Rozumím, s tím nemám vůbec problém. Testovalo by se to až najednou.

**Comment by motyc** [comment]
@pesikj Upřesněno zadání podle dohody.

**Comment by pesikj** [comment]
@motyc 
> `-- pian.zm50 - podle pian.zm10`

To znamená konkrétně co? Že ta hodnota je také `ruain_katastr.definicni_bod`?

**Comment by motyc** [comment]
@pesikj Z názvu listu ZM10 (např. 03-10-21) je vždy přímo odvoditelný název listu ZM50 (jde o podřetězec, např. 03-10).

**Comment by pesikj** [comment]
@motyc A jak můžu propojit tabulky ruian_katastr a Kladyzm? Jde nějak propojit ta pole s geometrií?

**Comment by motyc** [comment]
@pesikj Úplně mi není jasné, proč je třeba je propojovat? Případný vztah je tam pouze z hlediska průniku geometrie, resp. polohy definičního bodu katastru na listu ZM.

**Comment by pesikj** [comment]
@motyc 
> -- pian.zm10 - určit podle ruain_katastr.definicni_bod

Pole `zm10` je navázané na tabulku `Kladyzm`. Pokud mám tedy určit `zm10` podle `ruain_katastr.definicni_bod`, pak potřebuji na základě definičního bodu vybrat vhodný záznam z tabulky `Kladyzm`. Můžete tedy prosím specifikovat, jak to udělat?

**Comment by motyc** [comment]
@pesikj Bude se to řešit úplně stejně, jako pro běžný PIAN, tedy prostorovým průnikem definičního bodu katastru (=poloha v mapě, jako by ji zadal uživatel bodem) a hranice základní mapy.  Nedokážu říci, jaké přesně funkce se na to používají, ale rychlým hledáním v kódu mi přijde, že se jedná o toto řešení: https://github.com/ARUP-CAS/aiscr-webamcr/blob/ba559c1d5560547513935215021d5a3d10275895/webclient/pian/views.py#L246

**Comment by motyc** [comment]
### Výsledek testu
Funguje velice dobře, jen jedna věc kolem geometrií:
- [ ] pole `pian.geom_system` nemůže u nově vytvořených PIAN zůstat prázdné - mělo by se vyplnit relevantní hodnotou ("wgs84" / "sjtsk"); v tomto kontextu mne napadá - nejsou náhodou geometrie v `ruian_katastr.hranice` uloženy v SJTSK? Já to z DB nepoznám, ale pokud by to tak bylo, měli bychom při tvorbě PIAN vložit hodnotu z `ruian_katastr.hranice` uložit do `pian.geom_sjtsk`, `pian.geom_system` by mělo být "sjtsk" a pole `pian.geom` by se mělo vyplnit s užitím transformačního skriptu od @jiri-bartos-huld;

**Comment by pbartosova** [comment]
@motyc pole hranice typu geometry v tabulce ruin_hranice je uložena ve wgs84

**Comment by pbartosova** [comment]
Je nutné doplnit pian.geom_system=const wgs84 a zajistit převod wgs84->jtsk. Navrhnout, na jaké úrovni se transformace bude provádět. Navrhujeme řešit jako nový požadavek.

**Comment by motyc** [comment]
@pbartosova `doplnit pian.geom_system=const wgs84` - to tedy prosím dodělat a toto issue pak bude v pořádku.

`zajistit převod wgs84->jtsk` - ono by se to sice mělo dít automaticky jako u kteréhokoli jiného PIAN, což už myslím dělal @jiri-bartos-huld, ale souhlasím, abychom to dořešili zvlášť. Stejně se k tomu bude třeba vrátit ještě v kontextu #372. Zapsal jsem to do tohoto issue jako další bod.

**Comment by motyc** [comment]
Mohu otestovat až po nasazení opravy https://github.com/ARUP-CAS/aiscr-webamcr/issues/780#issuecomment-1356088852 (poslední bod).
