### ISSUE TITLE
Doplnění KAT do stavů ve filtraci historie

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1705]
Pro Projekt, Samostatná akce, Lokalita a PAS chybí položka "KAT" - původní řešení viz https://github.com/ARUP-CAS/aiscr-webamcr/pull/1646 (asi omylem přepsáno v rámci paralelních změn)

**Comment by pesikj** [comment]
@motyc Já je tam vidím.
<img width="394" alt="image" src="https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/5353c378-da99-425d-b76b-f70c228af7ff">
