### ISSUE TITLE
Asynchronní hesláře s multivýběrem - ladění ergonomie

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1710]
Chování asynchronních seznamů s multivýběrem je v některých situacích velmi nepraktické, až těžko použitelné. Problém je zejména se situacemi, kdy je vybraná hodnota na více řádků, jak ilustruje případ níže (zeleně chování ok, červeně problém). Navíc se zdá, že jen některé seznamy reagují na přidávání položek roztažením na výšku (dobré řešení):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5c4cec32-fda6-499d-8dcd-54aea92ac8aa)

Je potřeba chování odladit tak, aby seznamy šly vždy pohodlně používat.

**Comment by motyc** [comment]
@jnihnat Bohužel to asi nepomohlo, chování je stále stejný (viz příklad výše).

**Comment by jnihnat** [comment]
@motyc prosim skuste promazat cache. Pripadne jaky prohlizec pouzivate+verzi? Ja to skousel na Chrome, Mozille a Safari a vsude stejny vysledek:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/57906106/3039fc97-0706-4520-ab30-a462a538c206)

**Comment by motyc** [comment]
@jnihnat Já testuji v Chrome a teď jsem to zkusil i v anonymním okně, kde by cache neměla hrát roli (se stejným výsledkem). V Mozille je to o něco lepší. Můžu zítra ukázat.

**Comment by motyc** [comment]
@jnihnat Bohužel to stále zůstalo stejné :(
