### ISSUE TITLE
Nefunkční kalendář ve správě odstávek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1711]
Pokud vložím nějakou hodnotu z kalendáře, nebo použiji tlačítko "Dnes", vloží se do pole `undefinedd.undefinedm.2024`

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/3eefc4a6-7ecd-4cd8-9e73-44525e8528da)

**Comment by jnihnat** [comment]
@motyc - muzete prosim skusit protestovat. Skousel jsem ted u sebe i na .30 a funguje, mozna to byla Django vec a prechodem na 5 se to opravilo "samo"
