### ISSUE TITLE
Nefunkční heatmapy na .30

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1712]
- [ ] Na .30 nefungují heatmapy, protože v databázi chybí data v dotčených materializovaných pohledech. Na serveru .24 vše funguje nad totožnými daty. Je třeba zjistit, co je za problém.
- [ ] Nastavit jednou za čas automatickou aktualizaci pohledů (asi přes Celery cron)

**Comment by motyc** [comment]
Od @jhavrlant 
> Ahoj,
> díval jsem se na ty heatmapy a materializované pohledy a všimnul jsem si že, v aplikaci se používají materializované pohledy:
> amcr_heat_pas_l2
> amcr_heat_pas_lx2
> amcr_heat_pian_l2
> amcr_heat_pian_lx2
> amcr_heat_projekt_l2
> amcr_heat_projekt_lx2
>  a v databázi je:
> amcr_heat_pian_l1
> amcr_heat_pian_l2;
> amcr_heat_pian_lx1;
> amcr_heat_pian_lx2;
> amcr_heat_projekt_l1;
> amcr_heat_projekt_l2;
> amcr_heat_projekt_lx1;
> amcr_heat_projekt_lx2;
> takže buď v databázi chybí tabulky pro pas nebo se v aplikaci odkazuje na neexistující tabulky.

**Comment by motyc** [comment]
@jhavrlant No, pak to určitě bude potřeba sjednotit a opravit, a to tak, aby se vše správně aplikovalo i při migraci. Myslím, že ty pohledy se vytváří Django migrací. Správný stav lze asi vzít z DB amcr_test_old, kterou máme na .30 (to je stav před poslední migrací), který fungoval.

Jinak ono to vypadá tak, že *_l1 se vždy používá jako zdroj pro *_l2 na úrovni DB.

**Comment by jhavrlant** [comment]
@motyc je potřeba přidat v administraci Task update_materialized_views pro aktualizaci heatmap. Asi by bylo dobré to někam poznamenat jako úkon při instalaci po migraci.

**Comment by motyc** [comment]
@jhavrlant Přidávám do #387
