### ISSUE TITLE
Update redis snapshots - selhání kvůli healthcheck

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1713]
Působí to, jak kdyby se neustále dokola ptala AMČR do Fedory, a to několikrát za vteřinu - co to je?

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/08487181-5f52-4496-8b4e-10e7adb78c75)

**Comment by motyc** [comment]
S @jhavrlant jsme se dohodli, že automatické generování snapshotů při spuštění nové instance vypneme a bude se spouštět čistě ručně. Znamená to tedy
- [ ] Upravit příslušný skript
- [ ] Popsat přesnou sekvenci příkazů, jak generování spustit (následně to zařadím jako krok do migrace)

**Comment by motyc** [comment]
@pesikj @jhavrlant Na TR jsem teď zkusil cíleně spustit vygenerování snapshotů pomocí import cron.tasks; cron.tasks.update_snapshot_fields() , abychom prověřili, zda se poté data objeví. Problém je, že to 10 min skončilo restartem serveru kvůli healthcheck. Musíme asi upravit parametry healthcheck, nebo jej v rámci tohoto procesu nějak cíleně potlačit.

**Comment by pesikj** [comment]
@motyc A víte, který healthcheck aplikaci sestřelil?

**Comment by motyc** [comment]
@pesikj Nevím, protože nevím jak a kam se dívat, ale pod monitoringu bych sázel na ten, který hlídá vytížení procesoru, protože při generování CPU jede naplno. Zdá se mi ale, že naplno jede jen jedno jádro/vlákno, a že to ve skutečnosti přetížené není. Možná by bylo dobré to v té kontrole nějak zohlednit.

**Comment by pesikj** [comment]
@motyc A máme pořád healthcheck na CPU? V kódu ho nemůžu najít.

**Comment by motyc** [comment]
@pesikj No, to je dobrá otázka. Vím, že byl, ale teď vůbec netuším. Může to být samozřejmě i něco jiného. Zjevné je, že to vždy končí restartem serveru (jak ty noční běhy, tak teď, když jsem to pustil ručně).

**Comment by pesikj** [comment]
@motyc Problém by mohl být v tom, že redis klient vrací nějaké varování, které shazuje jeho healthcheck. Opravil jsem to v posledním commitu.

**Comment by motyc** [comment]
@pesikj Pak je ale divné, že se po tom zaseknutí nerestartuje i redis, ale jen kontejner `webamcr_web.1`. Je to záměr, aby tak healthcheck fungoval?

Zmíněnou opravu každopádně otestuji...

**Comment by pesikj** [comment]
Podle mě je standartní chování, že je restartován vždycky ten kontejner, kterého se healthcheck týká. Ale pokusím se to najít nastavení, které by zajistilo restartování více kontejnerů.

**Comment by motyc** [comment]
@pesikj Asi to zatím nechte do zítřka být, jen si shromážděte nápady a info. @jhavrlant to také studuje a má nějaké poznatky, tak to zítra probereme společně.

**Comment by pesikj** [comment]
@motyc Přidal jsem do healthchecku restart redisu, pokud je healthcheck neúspěšný.

**Comment by motyc** [comment]
@pesikj Bezva, ještě prosím o kontrolu a případný merge souvisejícího #2013

**Comment by jhavrlant** [comment]
@motyc Zde jsou SQL příkazy místo update_snapshot_fields:
--dokument.autori_snapshot
with autor_summary as (
select
	d.id as dokument_id,
	d.ident_cely as dokument_nazev,
	STRING_AGG(a.vypis_cely,
	'; '
order by
	da.poradi) as autori
from
	dokument d
join 
    dokument_autor da on
	d.id = da.dokument
join 
    osoba a on
	da.autor = a.id
where
	(d.autori_snapshot is null
		and da.id is not null)
group by
	d.id
order by
	d.id
    )
update
	dokument d
set
	autori_snapshot = autor_summary.autori
from
	autor_summary
where
	d.id = autor_summary.dokument_id;
--dokument.osoby_snapshot
with osoba_summary as (
select
	d.id as dokument_id,
	d.ident_cely as dokument_nazev,
	STRING_AGG(a.vypis_cely,
	'; '
order by
	a.vypis_cely) as osoby
from
	dokument d
join 
    dokument_osoba da on
	d.id = da.dokument
join 
    osoba a on
	da.osoba = a.id
where
	(d.osoby_snapshot is null
		and da.id is not null)
group by
	d.id
order by
	d.id
    )
update
	dokument d
set
	osoby_snapshot = osoba_summary.osoby
from
	osoba_summary
where
	d.id = osoba_summary.dokument_id;
--historie.organizace_snapshot_id
with organizace_sn as (
select
	"historie"."id",
	"usr"."organizace" as org
from
	"historie"
inner join "auth_user" usr on
	("historie"."uzivatel" = "usr"."id")
where
	"historie"."organizace_snapshot_id" is null
)
update
	historie
set
	organizace_snapshot_id = organizace_sn.org
from
	organizace_sn
where
	historie.id = organizace_sn.id;
--akce.vedouci_snapshot
with vedouci_summary as (
select
	d.archeologicky_zaznam as AZ_id,
	STRING_AGG(a.vypis_cely,
	'; '
order by
	a.vypis_cely ) as vedouci
from
	akce d
join 
    akce_vedouci da on
	d.archeologicky_zaznam = da.akce
join 
    osoba a on
	da.vedouci = a.id
where
	("d"."vedouci_snapshot" is null
		and "da"."id" is not null)
group by
	d.archeologicky_zaznam
order by
	d.archeologicky_zaznam
    )
update
	akce d
set
	vedouci_snapshot = vedouci_summary.vedouci
from
	vedouci_summary
where
	d.archeologicky_zaznam = vedouci_summary.AZ_id;
--externi_zdroj.autori_snapshot
with autor_summary as (
select
	d.id as EZ_id,
	d.ident_cely as EZ_nazev,
	STRING_AGG(a.vypis_cely,
	'; '
order by
	da.poradi) as autori
from
	externi_zdroj d
join 
    externi_zdroj_autor da on
	d.id = da.externi_zdroj
join 
    osoba a on
	da.autor = a.id
where
	(d.autori_snapshot is null
		and da.id is not null)
group by
	d.id
order by
	d.id
    )
update
	externi_zdroj d
set
	autori_snapshot = autor_summary.autori
from
	autor_summary
where
	d.id = autor_summary.EZ_id;
--externi_zdroj.editori_snapshot
with osoba_summary as (
select
	d.id as EZ_id,
	d.ident_cely as EZ_nazev,
	STRING_AGG(a.vypis_cely,
	'; '
order by
	a.vypis_cely) as osoby
from
	externi_zdroj d
join 
    externi_zdroj_editor da on
	d.id = da.externi_zdroj
join 
    osoba a on
	da.editor = a.id
where
	(d.editori_snapshot is null
		and da.id is not null)
group by
	d.id
order by
	d.id
    )
update
	externi_zdroj d
set
	editori_snapshot = osoba_summary.osoby
from
	osoba_summary
where
	d.id = osoba_summary.EZ_id;
--lokalita.dalsi_katastry_snapshot
with katastr_summary as (
select
	STRING_AGG(rk.nazev,
	'; '
order by
	rk.nazev) as katastry,
	"lokalita"."archeologicky_zaznam",
	"lokalita"."dalsi_katastry_snapshot"
from
	"lokalita"
inner join "archeologicky_zaznam" on
	("lokalita"."archeologicky_zaznam" = "archeologicky_zaznam"."id")
inner join "archeologicky_zaznam_katastr" azk on
	("archeologicky_zaznam"."id" = azk."archeologicky_zaznam_id")
join ruian_katastr rk on
	rk.id = azk.katastr_id
where
	("lokalita"."dalsi_katastry_snapshot" is null
		and azk."katastr_id" is not null)
group by
	"lokalita".archeologicky_zaznam 
    )
update
	lokalita d
set
	dalsi_katastry_snapshot = katastr_summary.katastry
from
	katastr_summary
where
	d.archeologicky_zaznam = katastr_summary.archeologicky_zaznam;

**Comment by motyc** [comment]
@pesikj @jhavrlant Vypadá to dobře, teď jsem pustil `update_all_redis_snapshots` na .30 a vše proběhlo bez pádu. Zavřu, až to otestujeme i na .34.
