### ISSUE TITLE
Projekt - nefunkční filtrace podle oblasti

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1716]
http://192.168.254.30:8080/projekt/vyber?stav=1&oblast=C&sort=-ident_cely&sort=planovane_zahajeni&sort=hlavni_katastr

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/eac16f19-0856-4431-a26d-d5fd8c9c1b87)

**Comment by jnihnat** [comment]
opraveny i akce a pas.
