### ISSUE TITLE
Projekt - přihlásit - chyba výběru vedoucího

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1717]
Seznam je nějaký graficky rozbitý:

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/e11eb69c-5cab-4d23-b027-dbfdc1c97a72)

**Comment by pesikj** [comment]
@motyc Toto vůbec nemůžu nasimulovat, v aplikaci nevidím tlačítko přihlásit (jako admin).
