### ISSUE TITLE
User - chyba transakce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1720]
Volání `DocumentGenerator.generate_metadata(model_class="User")` při hromadném generování sice připraví transakci a vloží do ní odpovídající příkazy, transakce se však nikdy neodešle.

**Comment by pesikj** [comment]
@motyc Teď jsem to testoval a transakce se uzavírají v pořádku, v kódu je vše také ok.

**Comment by motyc** [comment]
@pesikj Ok, vyzkouším znovu. Mohli pomoci jiné změny, co se od února udály.
