### ISSUE TITLE
Chyba transakce při změně katastru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1721]
http://192.168.254.30:8080/arch-z/akce/detail/C-9002402A/dj/C-9002402A-D01

Pokud použiji funkci "PIAN - změnit katastr", transakce se připraví, ale neodešle.

**Comment by pesikj** [comment]
@motyc Opravu je třeba testovat na jiné akci, tato je blokovaná neuzavřenou transakcí.
