### ISSUE TITLE
3D - chyba archivace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1723]
http://192.168.254.30:8080/dokument/model/detail/X-C-3D-000000002

Dokument nejde archivovat - zůstávají viset transakce (nyní `354f88ad-1676-4387-a075-097a7a16b968`).

**Comment by pesikj** [comment]
@motyc Zkoušel jsem archivaci zde a normálně prošla: http://192.168.254.30:8080/arch-z/akce/detail/M-9116052A

Je možné, že ty transakce už tam byly předtím, záznamy zůstávají zamčené trvale.

**Comment by motyc** [comment]
@pesikj Ano, ale tady šlo o záznam v knihovně 3D (nikoli o akci). Na každém místě se to chová jinak.

Já k těm transakcím dám dnes nebo zítra nějaký výsledek širšího testu. Je tam hodně jednotlivostí.
