### ISSUE TITLE
Výškový bod - nevyplňují se výchozí souřadnice

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1725]
- [x]  Např.: http://192.168.254.30:8080/arch-z/akce/detail/C-9001196A/dj/C-9001196A-D01. U VB by se měly předvyplnit souřadnice X a Y podle polohy PIAN, nyní se však vyplňuje vždy 0 (dříve fungovalo dobře).
- [x] Pokud odešlu formulář s X, Y a Z = 0, vrátí error 500 - mělo by se ošetřit testem ve formuláři: `null value in column "geom" of relation "vyskovy_bod" violates not-null constraint`

**Comment by motyc** [comment]
@jhavrlant První bod ok, druhý asi opomenutý (platné).

**Comment by motyc** [comment]
@jhavrlant V pořádku opraveno, pouze je třeba doplnit klíče pro související chybové hlášky do Rosetty. Nyní jsou tam někde pevně, ale nedaří se mi najít, kde to je.

**Comment by jhavrlant** [comment]
@motyc Které varovné hlášky máš namysli.

**Comment by motyc** [comment]
@jhavrlant Že souřadnice X, Y, Z musí být větší/menší než (když např. zadám 0 do nadmořské výšky).

**Comment by motyc** [comment]
@jhavrlant On je problém v tom, že to nereaguje na přepnutí jazyka v aplikaci. Jinak by mi to bylo jedno.

**Comment by jhavrlant** [comment]
@motyc Ano vypadá to blbě, když přepnu do jiného jazyka, ale myslím že, to nastane jen výjimečně. Ta hláška bude odpovídat jazyku, který má nastaven uživatel v prohlížeči. Máme tedy 3 možnosti.
1. Nechat to tak, jak to je.
2. Použít django validaci na serveru, trochu nepraktické pro uživatele, ale jednoduché pro vývojáře (mě)
3. Předělat validaci na javascript. Komfortní pro uživatele. Malinko pracnější.

**Comment by motyc** [comment]
@jhavrlant Díky za vysvětlení, volím tedy variantu 1.
