### ISSUE TITLE
Fedora - doplnění chybových hlášek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1726]
Ve spojitosti s Fedorou dochází k situaci, kdy v aplikaci něco udělám, vše se tváří, že proběhlo v pořádku, ale ve skutečnosti se nic nestane. Prověřit možnost doplnění chybové hlášky tak, aby uživatel dostal odpovídající zpětnou vazbu.

Nastává např. při:
- http://192.168.254.30:8080/projekt/detail/X-M-202387259 - nejde potvrdit - je to patrně kvůli chybějícím souborům v Fedoře (v konzoli nic)
- http://192.168.254.30:8080/adb/vb/smazat/ADB-MTRE79-000001-V0001 - nejde smazat kvůli transakci (v konzoli viditelné 500)

Problém asi bude částečně v tom, že stránka s chybovou hláškou Fedory vrací header 200:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/ba9fb5e8-f6d9-456f-9146-737e81853426)

**Comment by pesikj** [comment]
@motyc Nevím, co je zde přesně myšleno. Můžu doplnit šablonu o dodatečné informace (např. číslo transakce, text vrácený fedorou, typ requestu). Tato obrazovka ukazuje, že kvůli problémů s Fedorou nedošlo k úspěšnému dokončení akce, aplikace se tedy netváří, že vše proběhlo v pořádku.

**Comment by motyc** [comment]
@pesikj On problém je v tom, že jsem stránku vylovil až procházením různých volání z konzole a hledáním, co vlastně selhalo. Tím, že stránka vrací 200, nikoli třeba 500, tak to působí tak, že vše proběhlo a komplikuje to debuging. Možná to ale můžeme probrat po telefonu/na schůzce, abychom si to chování vyjasnili a dohodli se. Třeba něco špatně chápu já.

Určitě neuškodí i doplnění konkrétních podrobností transakci/requestu/chybovém stavu, ale to je až sekundární věc.

**Comment by pesikj** [comment]
@motyc Kód 500 byl nastavený.
