### ISSUE TITLE
Komponenty - nejde upravovat aktivity

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1727]
Pokud provedu nějaké změny v aktivitách u komponenty a uložím změny, vše se vrátí do výchozího stavu a změny se neuloží.

**Comment by jnihnat** [comment]
Opraveno v #1779
Po prechodu na fedoru a save bez commitu je potrebne m2m relacenukladat zvlast. Predelal jsem teda i u projektu a dokumentu. Ostatne co som tak koukal se uz tedka uklada samostatne. Dalsi problem co mi zabral cas byl ze i po ulozeni se nic neobnovilo na formulari... na pricine je cacheops co se pridal. Takze nejlip prokontrolovat vsude kde je m2m relace.

**Comment by motyc** [comment]
@jnihnat Díky za vysvětlení. Myslím, že s tím souvisí i #1728. Dám váš komentář tam, ať se to prokontroluje.

**Comment by motyc** [comment]
### Test v0.4.47

- [ ] Neošetřeno pro https://wamcr-test.aiscr.cz/dokument/model/edit/X-C-3D-202311846
