### ISSUE TITLE
Progress bar u exportu zlobí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1737]
Zejména ve variantě s "Pokračovat" nebo pokud dělám více exportů za sebou, progress bar se hned naplní a nenabíhá postupně, byť ještě export není vůbec hotový.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
- [ ] Při pokusu exportovat vše z tabulky dokumentů progess bar nejdříve naskočil naplno, pak se vrátil cca do 1/6 a následně skočil na cca 3/5, kde se zasekl na většinu doby přípravy exportu, následně poskočil na cca 4/5, kde zase byl dlouho.
-- Mohlo by to být nějak jemnější, aby se to průběžně o trochu hýbalo.
-- Je třeba vyřešit to divné skákání na začátku (to se mi ale nestalo vždy).
- [ ] Když jsem pustil souběžně export v jiném tabu, který skončil dříve, progress bar v původním tabu se úplně vynuloval.
- [ ] `core.templates.core.export_modal.file_generated` - zobrazí se už v průběhu generování, podle názvu bych čekal až na konci (napodruhé se mi to zobrazilo až po nějakém čas, nějakou dobu je tam správná hláška `core.templates.core.export_modal.file_being_generated`)
![image](https://github.com/user-attachments/assets/d76d86bd-1a36-4c90-93fb-b2313f82ea9b)
- [ ] Když jsem export zavřel ještě před konce, zůstala tam viset hláška `core.templates.core.export_modal.file_generated` a celé to působí nějak rozbitě:
![image](https://github.com/user-attachments/assets/c99c2339-b15b-42d0-b3ef-a938cac03a88)

U dokumentů se mi nepodařilo export ze systému vymáčknout ani napodruhé (čekal jsem několik minut a nic). Když jsem totéž zkoušel u samostatných akcí, chování bylo celkově lepší. Celkově mi přijde, že to někdy funguje a někdy ne a není úplně jasné, jestli se to v danou chvíli nezaseklo. Chtělo by to proklikat v aktuální verzi na testu a odladit to tak, aby to bylo pro uživatele více předvídatelné.

**Comment by pesikj** [comment]
@motyc 

>  core.templates.core.export_modal.file_generated - zobrazí se už v průběhu generování, podle názvu bych čekal až na konci (napodruhé se mi to zobrazilo až po nějakém čas, nějakou dobu je tam správná hláška core.templates.core.export_modal.file_being_generated)

Toto je správně, označuje to stav, kdy byl soubor vygenerován a začíná jeho stahování.

**Comment by motyc** [comment]
### Test v1.0.13-rc9
- [ ] Celkově to funguje mnohem lépe, ale při velkém množství záznamů to bohužel nedoběhne ani po mnoha minutách. Je zajímavé, že se nezdá, že by to rostlo lineárně, ale že od nějakého počtu to prostě trvá nekonečně dlouho. Buď je třeba najít a ošetřit příčinu, nebo dočasně při více než 50 tis. záznamech vůbec nedovolit stažení a vyřešíme to v budoucnu (to lze asi udělat prostým skrytím tlačítka "Pokračovat" u příslušné hlášky). Kde mi to selhalo:
-- https://amcr-test.aiscr.cz/dokument/vyber?sort=typ_dokumentu&sort=ident_cely
-- https://amcr-test.aiscr.cz/projekt/vyber?sort=hlavni_katastr&sort=ident_cely
