### ISSUE TITLE
Chyba odstraňování nepotvrzených PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1741]
Pokud dojde k odpojení nepotvrzeného PIAN bez dalších vazeb změnou DJ na typ katastr, odpojovaný PIAN se nesmaže.

**Comment by motyc** [comment]
### Test v0.4.47

- [ ] Pokus o test u https://wamcr-test.aiscr.cz/arch-z/akce/detail/M-9106443A/dj/M-9106443A-D01 vrací:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/eade8d94-c2fe-413a-88c6-e80127812fb4)

**Comment by motyc** [comment]
### Test v0.4.61

- [ ] Ke smazání nyní patrně dojde, ale i zde se objevuje problém s `restored` - záznam se ve Fedoře hned obnoví (https://fedora-test.aiscr.cz/rest/AMCR/record/N-1121-000000021), v DB se správně smaže.

**Comment by motyc** [comment]
### Test v0.4.70

- [ ] Znovu rozbité, jen jinak. Prosím o pečlivější test opravy:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/c9346a09-2079-4b07-8fdf-6cf2ca943519)

**Comment by pesikj** [comment]
@motyc Tato chyba je ale způsobená commitem od @jhavrlant, který je o 2 dny novější než moje úpravy. Z toho tedy logicky plyne, že jsem to během vývoje a tesování opravy nemohl zohlednit.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/7c82558e-f20e-4ad7-8b26-e847291a304c)

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/6efd45ed-05f6-4370-b4ad-53e999bc5061)

**Comment by motyc** [comment]
@pesikj Aha, omlouvám se. Tak na to prosím @jhavrlant mrkni Ty, jestli ta oprava zpět je ok. Asi šlo o nějaké nedorozumění.

**Comment by motyc** [comment]
### Test v0.4.74

Vrátili jsme se ke stejnému problému, kdy při přepojení na katastr dojde k odstranění, ale hned se PIAN zase obnoví. Viz: https://fedora-test.aiscr.cz/rest/AMCR/record/N-1443-334047 (původně viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/1741#issuecomment-2136928722)

**Comment by motyc** [comment]
@pesikj Ve v0.4.76 nedošlo k vůbec žádné změně. Stále stejná chyba (https://fedora-test.aiscr.cz/rest/AMCR/record/N-0344-378849).
