### ISSUE TITLE
Změna generování definičních bodů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1746]
Nahradit funkci `ST_Centroid` využitím `ST_PointOnSurface` pro generování definičních bodů PIAN.

**Comment by jhavrlant** [comment]
@motyc Tak jsem tu funkci zkouše a je to určitě zlepšení, jen ten bod nemusí být vždy uprostřed, např. u čar bývá občas na jejím začátku nebo konci.

**Comment by motyc** [comment]
@jhavrlant Předpokládám, že je to tehdy, když má jen dva vertexy? Jestli ano, pak je to asi ok.

**Comment by jhavrlant** [comment]
> @jhavrlant Předpokládám, že je to tehdy, když má jen dva vertexy? Jestli ano, pak je to asi ok.
@motyc Vypadá to že ano.
