### ISSUE TITLE
Chování tlačítka Dokončit při nahrávání souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1748]
Tlačítko Dokončit u nahrávaných souborů - bylo by lepší, kdyby bylo neaktivní, když právě nahrávání probíhá, protože není úplně jasné, co se stane, pokud na něj v průběhu nahrávání kliknu a mohou tak vznikat chyby.

**Comment by motyc** [comment]
### Test v1.0.10-rc3
Oba problémy se týkají https://amcr-test.aiscr.cz/oznameni/
- [ ] Deaktivace tlačítka "Dokončit oznámení" zde není implementovaná
- [ ] Pokud kliknu na tlačítko "Dokončit oznámení" a v modalu s dotazem, zda jsem nahrál vše kliknu na "Zrušit" nebo kliknu vedle, spinner se zasekne a nejde pokračovat (souvisí s #2284).

**Comment by jhavrlant** [comment]
@pesikj Opravuji
