### ISSUE TITLE
Dokumenty a 3D - omezit zaměnitelnost

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1761]
Nyní jde dokument 3D otevřít v rozhraní pro dokumenty (http://192.168.254.30:8080/dokument/detail/X-C-3D-202311846), což může vést k chybám.

Otevření běžného dokumentu ve 3D vrací 500 (http://192.168.254.30:8080/dokument/model/detail/X-C-TX-000000006), což je třeba vhodně odchytit.

Je tak třeba ošetřit, aby ve 3D (http://192.168.254.30:8080/dokument/model/*) aplikace akceptovala jen MODEL_3D_DOKUMENT_TYPES a v části dokumenty jen doplněk k MODEL_3D_DOKUMENT_TYPES. Týká se to detailu i libovolných editačních obrazovek (atd.), pokud nejsou oběma částmi sdílené.

**Comment by jnihnat** [comment]
@motyc co prosim mate na mysli timto:
"a v části dokumenty jen doplněk k MODEL_3D_DOKUMENT_TYPES" - prvotne jsem si myslel bude 3D nebo ne 3D ale tohle me mate :)

**Comment by motyc** [comment]
@jnihnat To bude asi spíš jen problém s češtinou :) Je to myšleno tak, že v dokumentech bude platit `exclude(MODEL_3D_DOKUMENT_TYPES)` a ve 3D to naopak `filter(MODEL_3D_DOKUMENT_TYPES)`. Nic složitějšího.

**Comment by jnihnat** [comment]
snad jsem neopomnel na zadnou stranku.
