### ISSUE TITLE
Úprava fontu na kartách

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1765]
Nadpisy dlaždic/karet na landing page a domovských obrazovkách modulů by měly být bezpatkovým fontem odpovídajícím logu (Museo, případně jiný obdobný)

**Comment by pesikj** [comment]
@motyc Font museo je tam nastavený, ale není zobrazený, protože není nahraný ve statistických souborech. Máte soubory toho fontu?

**Comment by motyc** [comment]
@pesikj Zde je sada fontů patřících k logu AMČR: [fonts.zip](https://github.com/ARUP-CAS/aiscr-webamcr/files/15448646/fonts.zip)
