### ISSUE TITLE
Registrace uživatelů není při odstávce blokována

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1768]
Pokud je zapnutá odstávka, není zablokovaná registrace uživatelů (http://192.168.254.30:8080/accounts/register/)

**Comment by motyc** [comment]
### Test v0.4.74

Bohužel blokování nefunguje, naopak když se zkusím zaregistrovat, hodí to chybu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a4acab56-bc4e-43fc-98c9-051603eadf95)

**Comment by jnihnat** [comment]
https://uwsgi-docs.readthedocs.io/en/latest/Management.html

**Comment by motyc** [comment]
@jnihnat Odstávka již funguje, ale nadále nefunguje registrace jako taková (vrací totéž, co je popsáno v předchozím postu: https://github.com/ARUP-CAS/aiscr-webamcr/issues/1768#issuecomment-2179452749). Nevím, zda to přímo souvisí, nebo to je na @pesikj a jiné issue... **Každopádně toto velmi spěchá.**

**Comment by jnihnat** [comment]
@motyc opraveno v #1978. rovno som zmenu mergol, muze se nasadit
@jhavrlant - pripadne muzete nasadit

**Comment by motyc** [comment]
@jnihnat Super, děkuju.
@jhavrlant S nasazením ještě počkej, uděláme to pak najednou s dalšími opravami.
