### ISSUE TITLE
Projekt - chyba napojení hesel

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1772]
V rámci revize hesel jsem narazil na jsem narazil na jedno opomenuté místo, kde jsou odkazy na hesla napsána fixně v kódu a vazby jsou po nové migraci rozbité. Situaci ale neumím opravit, protože nevím, jak správně načíst konstanty do HTML.

Zde jsem připravil správné konstanty: https://github.com/ARUP-CAS/aiscr-webamcr/commit/449acbf2568ac1e44acfb5f051e32c3edd457b1d

- [x] Zde je pak třeba opravit kód tak, aby místo fixního výčtu používal seznam ID z konstanty [KULTURNI_PAMATKY](https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/heslar/hesla_dynamicka.py#L22)
https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/projekt/templates/projekt/prihlasit.html#L72
https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/projekt/templates/projekt/edit.html#L145

--------------

- [x] Podezřelá se mi zdá také následující konstrukce, kde bych čekal nějaké využití konstanty [TYP_PROJEKTU_ZACHRANNY_ID](https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/heslar/hesla_dynamicka.py#L14) Možná ale jen správně nechápu, jak to funguje (aktuálně se to chová v pořádku, jen nevím, přes co se to propojuje):
https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/projekt/templates/projekt/edit.html#L197
https://github.com/ARUP-CAS/aiscr-webamcr/blob/449acbf2568ac1e44acfb5f051e32c3edd457b1d/webclient/projekt/templates/projekt/create.html#L124

**Comment by jnihnat** [comment]
@motyc pridal som este:
KULTURNI_PAMATKA_OP = get_id_from_heslar("HES-000176")
KULTURNI_PAMATKA_UN = get_id_from_heslar("HES-000181")

**Comment by motyc** [comment]
@jnihnat Ty jsme teď právě pro novou migraci rušili, ale to asi nevadí. Prostě je to jen pak nenajde.
