### ISSUE TITLE
Nefunkcni logout

### ISSUE THREAD

**Issue by jnihnat** [ARUP-CAS/aiscr-webamcr#1785]
Po prechodu na Django 5 nefunguje logout z duvodu zakazani GET requestu pro logout. Je potrebne predelat na POST, stejne i autologout a aby fungoval next.

**Comment by jnihnat** [comment]
@motyc - pro info, uz na tom delam, nechavam na vas doplneni labelu a pod.

**Comment by motyc** [comment]
@jnihnat Děkuji moc, hotovo.

**Comment by motyc** [comment]
### Test v0.4.47

- [ ] Logout funguje, ale nefunguje automatické přihlášení zpět, pokud mám otevřených více tabů...

**Comment by jnihnat** [comment]
Prosim o retest, na locale uz funguje, nejspis opraveno v ramci jinych oprav v js.
