### ISSUE TITLE
> @pesikj - je este potreben spravit migraci na odstraneni constraint "soubor_filepath_key" z tabulky soubory.

### ISSUE THREAD

**Issue by pesikj** [ARUP-CAS/aiscr-webamcr#179]
> @pesikj - je este potreben spravit migraci na odstraneni constraint "soubor_filepath_key" z tabulky soubory.

Dobře, já ji upravím.

_Originally posted by @pesikj in https://github.com/ARUP-CAS/aiscr-webamcr/issues/171#issuecomment-897487671_

**Comment by pesikj** [comment]
Migrace je nahraná s číslem 20, je potřeba ji spustit.

**Comment by motyc** [comment]
@pesikj K tomuto bych rád znal lépe důsledky pro úložiště. Bude systém v případě duplicitních souborů bez problémů fungovat, resp. jak? Dosud byl součástí názvu i hash, platí to stále? (ptám se proto, co vlastně znamená "duplicita")

**Comment by pesikj** [comment]
To asi lépe vysvětlí @jnihnat

**Comment by jnihnat** [comment]
@motyc - tuna sa kazdy jeden duplicitny zaznam ulozi s dalsimi nahodnymi znakmi na konci. Kontrola na duplicitu se dela cez nazev, ktery je i s checksumem. teda presny obsah souboru.
![obrázok](https://user-images.githubusercontent.com/57906106/134580637-247814d1-3543-4f85-8169-b8158f123a10.png)

**Comment by motyc** [comment]
@jnihnat Super, díky za vysvětlení, nemám výhrad.
