### ISSUE TITLE
DJ - chyba při zápisu pokud jsem archeolog

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1800]
Jako archeolog při ukládání nové DJ vrací chybu, jako administrátor je to bez problému.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/8c82f435-c2c6-4a2a-9959-973a3b76aaa3)

**Comment by jhavrlant** [comment]
Dovolil jsem si opravit aby to tam nevázlo.
