### ISSUE TITLE
Chyba editace projektu bez souřadnic

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1805]
Pokud projekt nemá souřadnice (např. https://wamcr-test.aiscr.cz/projekt/detail/C-201664018) a provedu jeho editaci bez zásahu do mapy (https://wamcr-test.aiscr.cz/projekt/edit/C-201664018), po uložení dostanu chybu 
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/16fd5b8f-f1aa-468f-978e-b3df95a9e19e)

Patrně to bude tím, že se do souřadnic něco divného vloží samo.

**Comment by motyc** [comment]
@jhavrlant Oprava nezabrala - testováno teď na: http://192.168.254.30:8080/projekt/detail/C-201125000

**Comment by jhavrlant** [comment]
> @jhavrlant Oprava nezabrala - testováno teď na: http://192.168.254.30:8080/projekt/detail/C-201125000
Oprava je ve verzi v0.4.53 nyní je tam v0.4.52.
