### ISSUE TITLE
Rosetta - problém s ukládáním

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1812]
Ukládání v Rosetta je najednou hrozně pomalé a často končí time-outem. Bylo již před merge posledních úprav (#1624), spíš to vypadá na nějaký problém s backend, jak kdyby aplikace na něco čekala. Uložení nakonec proběhne dobře, ale zasekne na dlouho celou aplikaci.

**Comment by jnihnat** [comment]
pri kazdem ukladani se restartuje aplikace, coz kvuli threads trvalo dlouho (python nema nativni podporu). Odebral jsem.
Otazka ale je ci chceme to restartovani mat hned po ulozeni stranky, nebo nove tlacitko nekde na prehledove tabulce. Bez restartu se nenactou nove preklady.

**Comment by jnihnat** [comment]
Predelano a jelikoz ten same restart byl u odstavek, tak jsem to udelal i tam, najdete tam tlacitko na restart aplikace.
