### ISSUE TITLE
PIAN - problém s načtením u badatele (oprávnění)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1816]
Patrně v důsledku nějaké chyby ověření oprávnění se pro badatele nenačítají PIAN z 
http://192.168.254.30:8080/mapa-pian-pas

Dotaz vrací: `RecursionError: maximum recursion depth exceeded while calling a Python object`

Hlásil @jhavrlant

**Comment by jnihnat** [comment]
tak tu sa uz asi priklonim k vytvoreni toho materialized view, proste to nezvladne udelat vsechny joiny, mozna nejaka uprava v Django 5 a pod... kazdopadne mi zabere vic casu to hledat a optimalizovat ako udelat ten view. pokud souhlasite @motyc

**Comment by motyc** [comment]
@jnihnat Souhlasím, zvláště když nám nic jiného nezbývá. Přidávám ještě @jhavrlant, který to také nějak promýšlí.

Jen doplňuji vazbu na https://github.com/ARUP-CAS/aiscr-webamcr/issues/1043#issue-1771181506 - tam je i návrh pohledu již připravený ode mě.

**Comment by jhavrlant** [comment]
@motyc @jnihnat Zkoušel jsem vytvořit materializovaný pohled a obnova pohledu mi trvala skoro 15 s, tak nevím jestli je to ta správná cesta.

**Comment by motyc** [comment]
@jhavrlant A jak ten pohled vypadal? Já teď vyzkoušel na .30 nad `amcr_test_backup_v0.4.48_20240510` udělat :

```plpgsql
CREATE MATERIALIZED VIEW IF NOT EXISTS mat_view_pian AS (
    WITH hist AS (
        SELECT historie.vazba, historie.uzivatel FROM historie
        WHERE typ_zmeny = 'AZ01' OR typ_zmeny = 'PI01'
    )
    SELECT DISTINCT
    pian.id AS pian_id,
    pian.ident_cely AS pian_ident,
    pian.geom::bytea,
    heslar.zkratka as presnost,
    dokumentacni_jednotka.ident_cely AS dj_ident,
    ST_Centroid(pian.geom)::bytea AS centroid,
    pian.stav,
    archeologicky_zaznam.pristupnost,
    h_pian.uzivatel AS pian_user,
    h_archz.uzivatel AS archz_user,
    u_pian.organizace AS pian_org,
    u_archz.organizace AS archz_org,
    projekt.organizace AS projekt_org
    FROM pian
    JOIN heslar ON pian.presnost = heslar.id
    LEFT JOIN dokumentacni_jednotka ON dokumentacni_jednotka.pian = pian.id
    LEFT JOIN archeologicky_zaznam ON dokumentacni_jednotka.archeologicky_zaznam = archeologicky_zaznam.id
    LEFT JOIN akce ON akce.archeologicky_zaznam = archeologicky_zaznam.id
    LEFT JOIN projekt ON akce.projekt = projekt.id
    LEFT JOIN hist h_pian ON archeologicky_zaznam.historie = h_pian.vazba
    LEFT JOIN hist h_archz  ON archeologicky_zaznam.historie = h_archz.vazba
    LEFT JOIN auth_user u_pian ON h_pian.uzivatel = u_pian.id
    LEFT JOIN auth_user u_archz ON h_archz.uzivatel = u_archz.id
) WITH DATA;

-- Obnova pohledu při každé změně pian, historie, dokumentacni_jednotka, archeologicky_zaznam, akce, projekt, auth_user, heslar:
REFRESH MATERIALIZED VIEW mat_view_pian;
``` 

A následně zavolal:
```plpgsql
REFRESH MATERIALIZED VIEW mat_view_pian;
``` 

Výsledek: `Query returned successfully in 3 secs 743 msec.`

To mi přijde úplně ok.

**Comment by jhavrlant** [comment]
Zkoušel jsem to u sebe. Tak jsem to vyzkoušel na .30, ale přidal jsem indexy a výsledek 4 secs 578 msec. Po tu dobu se na tu tabulku nejde dotazovat.

**Comment by motyc** [comment]
@jhavrlant To by myslím šlo, když bychom nějak rozumně nastavili ty aktualizace... (buď jednou za pár minut, nebo s vazbou na aktualizace konkrétních tabulek (asi by stačilo: pian, dokumentacni_jednotka, archeologicky_zaznam, akce, projekt, auth_user, heslar); otázka, co by bylo lepší.

**Comment by jnihnat** [comment]
Bude treba dobre promyslet, protoze to same se pouziva pri dotazovani na piany u dj.

**Comment by motyc** [comment]
@jnihnat Ano, ale vlastně nevím, jaký podklad navíc je nyní k tomu rozmýšlení potřeba. Bude každopádně ASAP implementovat řešení, protože toto je opravdu závažný problém a bude třeba dobře otestovat, že to funguje.

**Comment by jhavrlant** [comment]
Zkusím nejdříve ten dotaz zoptimalizovat, nějaký prostor tam je.

**Comment by motyc** [comment]
Nadále řešme v #1043
