### ISSUE TITLE
v DB zmenene constrainy

### ISSUE THREAD

**Issue by pesikj** [ARUP-CAS/aiscr-webamcr#183]
v DB zmenene constrainy
autor - zmenene na null     - mame M2M autori
jazyk dokumentu - zmenene na null         - mame M2M jazyky
odpovedny_pracovnik_vlozeni - zmenene na null              ???
datum_vlozeni - zmenene na null                             ???
datum_archivace - zmenene na null                           ???

_Originally posted by @jnihnat in https://github.com/ARUP-CAS/aiscr-webamcr/issues/180#issuecomment-900184250_

Provést stejné úpravy na serveru .24

**Comment by motyc** [comment]
Viz https://github.com/ARUP-CAS/aiscr-webamcr/pull/180#issuecomment-902234555

Díval jsem se na to a jde o soubor: https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/migrace_mazani.sql

**Comment by motyc** [comment]
@pesikj @pbartosova Ještě jednou důrazně prosím o otestování nad verzí databáze, kde bude provedena kompletní migrace, tj. vč. mazání. Jedině tak ověříme, že aplikace běží na správném podvozku a nepracujeme v ní s něčím, co v databázi ve skutečnosti vůbec nebude... Stejně tak je to jediný způsob, jak zkontrolovat správnost migrací.

**Comment by pesikj** [comment]
@motyc Používáme databázi zaloha na serveru .30. Migrace bude provedena sem?

**Comment by motyc** [comment]
@pesikj To si asi řekněte Vy, zda přemazat stávající požívanou databázi, nebo zda si to raději dát jinam, kdyby došlo k nějakým problémům (očekávám, že chyby nastat mohou). Nebo nevyzkoušíme to prvně raději na serveru .24?

**Comment by pesikj** [comment]
Záznam ze schůzky:
Pole, která jsou popsaná, by měla být smazána z modelu i databáze.

**Comment by motyc** [comment]
Stav databáze komplexně vyhodnocen v #474

**Comment by motyc** [comment]
Toto issue zavírám. Vše potřebné se řeší v tom 474 a toto se stalo irelevantním.
