### ISSUE TITLE
Chyby přesměrování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1833]
Nově je na řadě míst rozbité přesměrování po provedení dané akce, přišel jsem na to nejméně u:
- [ ] Při posunu stavu EZ2 do EZ3 externího zdroje s dočasným ident dojde k přesměrování na původní ident_cely, nikoli na nově přidělený, takže záznam není nalezen.

**Comment by pesikj** [comment]
@motyc Taky jsem si toho dříve všiml, ale nyní už se mi to nepodařilo nasimulovat, zřejmě to bude souviset s problémem s transakcemi.

**Comment by motyc** [comment]
@pesikj Otestováno a zbyla jen jedna varianta, kde se to stále děje.
