### ISSUE TITLE
Fedora - úprava proxy při změně ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1842]
Navazuje na #1405 

Pokud nyní měníme ident_cely, smazáním starého kontejneru se nám rozpadne vazby mezi starým a novým záznamem. Stačí to vyřešit tak, že v tomto kontextu upravíme proxy původního záznamu (např. https://fedora-test.aiscr.cz/rest/AMCR/model/archeologicky_zaznam/member/X-M-91322096A) tak, aby ukazovala na nový záznam, místo starého. V `rest/AMCR/model/deleted/member/` naopak zůstane odkaz na tombstone (např. https://fedora-test.aiscr.cz/rest/AMCR/model/deleted/member/X-M-91322096A).

Znamená to do [record_ident_change](https://github.com/ARUP-CAS/aiscr-webamcr/blob/1899a1045ca493739c9fbb47e181062aa8527a20/webclient/core/repository_connector.py#L793C9-L793C28) doplnit kroky:
- [x] Smazání existujícího odkazu `rest/AMCR/model/[model_name]/member/[ident_cely]` spuštěním [_delete_link](https://github.com/ARUP-CAS/aiscr-webamcr/blob/1899a1045ca493739c9fbb47e181062aa8527a20/webclient/core/repository_connector.py#L755) nad `ident_cely_old`
- [x] Přidání nového odkazu (obdoba [_create_link](https://github.com/ARUP-CAS/aiscr-webamcr/blob/1899a1045ca493739c9fbb47e181062aa8527a20/webclient/core/repository_connector.py#L359)), s tím rozdílem, že název zůstane podle `rest/AMCR/model/[model_name]/member/[ident_cely_old]`, ale v [proxy](https://github.com/ARUP-CAS/aiscr-webamcr/blob/1899a1045ca493739c9fbb47e181062aa8527a20/webclient/core/repository_connector.py#L368) se použije odkaz na nový záznam, tj. `ident_cely_new`

Nic dalšího se nemění.

**Comment by motyc** [comment]
### Test v0.4.61

- [ ] Funguje to, ale druhý bod se bude muset vydělit do samostatné transakce a dělat až nakonec, protože jinak si Fedora myslí, že záznam existuje a přidělí mu automaticky hash místo požadovaného názvu (např. https://fedora-test.aiscr.cz/rest/AMCR/model/pian/member/26d5bc36-c290-42c8-94de-0d4d993fcc5d místo https://fedora-test.aiscr.cz/rest/AMCR/model/pian/member/N-1212-000000022

**Comment by motyc** [comment]
### Test v0.4.70

- [ ] Nový proxy odkaz se nadále generuje chybně, ale může to možná být tím, že místo aby generoval `rest/AMCR/model/[model_name]/member/[ident_cely_old]` a do proxy se dalo `[ident_cely_new]`, tak se to dělá naopak (snaží se vytvořit `rest/AMCR/model/[model_name]/member/[ident_cely_new]` a do proxy se dá `[ident_cely_old]` - to ale spíše tipuji podle chování, problém může být jinde.
- [ ] Při každé editaci libovolného záznamu se nyní vygeneruje nová proxy na N-1223-000000031 nebo X-BIB-1328591, jako by to viselo někde v cache. Viz (a spousta dalších):
-- https://fedora-test.aiscr.cz/rest/AMCR/model/pian/member/0e0ab0f0-b808-4c00-849b-515d26503612
-- https://fedora-test.aiscr.cz/rest/AMCR/model/pian/member/b1ed7e81-09c3-493f-8f52-ae7c65602d9a
-- https://fedora-test.aiscr.cz/rest/AMCR/model/ext_zdroj/member/d01c1afc-0f1f-4a0e-8282-28d05e585cea
-- https://fedora-test.aiscr.cz/rest/AMCR/model/ext_zdroj/member/82f4239d-b51b-47ab-9397-2fbea007ee35

**Comment by pesikj** [comment]
Opravy jsem provedl, nevím, jak to otestovat. V logu je nyní vše bez chyb.

**Comment by motyc** [comment]
@pesikj V pohodě, vyzkouším já.

**Comment by motyc** [comment]
### Test v0,4,74

- [ ] Problém s vytvořením podivného kontejneru při editaci se výrazně omezil, ale opět se mi to stalo pro https://fedora-test.aiscr.cz/rest/AMCR/model/dokument/member/8e3745a8-f438-4260-856a-50acba3de530 (bylo to asi v souvislosti s editací DJ u akce). Nevím ale, zda se to nemůže dít i jindy, testování bylo relativně omezené.
- [ ] Při odeslání http://192.168.254.30:8080/arch-z/akce/detail/M-9002361A (původně X-M-9000000025A) byl odkaz pouze smazán, ale nevytvořil se vůbec. Odkaz vznikl jen pro souběžně s tím posouvaný dokument M-TX-202400055 (původně X-M-TX-000000039) _- stále platné (nyní test na http://192.168.254.30:8080/arch-z/akce/detail/C-9004593A)_

**Comment by pesikj** [comment]
@motyc Bod 2 opraven. Co se týká bodu 1, tak jsem prováděl úpravy, snad to problém vyřešilo.

**Comment by motyc** [comment]
### Test v0.4.76
- [ ] Při odeslání http://192.168.254.30:8080/arch-z/akce/detail/M-9002361A (původně X-M-9000000025A) byl odkaz pouze smazán, ale nevytvořil se vůbec. Odkaz vznikl jen pro souběžně s tím posouvaný dokument M-TX-202400055 (původně X-M-TX-000000039) - již lepší, tentokrát se vše vytvořilo správně, pouze se neprovedlo smazání kontejneru akce s dočasným ID (https://fedora-test.aiscr.cz/rest/AMCR/record/X-C-9000000021A), přestože všechny proxy se správně vytvořily
- [ ] Dále došlo k rozbití zápisu akce (http://192.168.254.30:8080/arch-z/akce/zapsat), kdy mi systém napoprvé vrátil varování, že daný kontejner ve Fedoře již existuje, je to ale proto, že v DB se záznam zapsal zcela bez ident_cely (viz `SELECT * FROM archeologicky_zaznam ORDER BY id DESC LIMIT 100; SELECT * FROM public.archeologicky_zaznam`); další už se logicky vůbec nezapíše, protože v DB vzniká duplicita

**Comment by motyc** [comment]
> Dále došlo k rozbití zápisu akce (http://192.168.254.30:8080/arch-z/akce/zapsat), kdy mi systém napoprvé vrátil varování, že daný kontejner ve Fedoře již existuje, je to ale proto, že v DB se záznam zapsal zcela bez ident_cely (viz `SELECT * FROM archeologicky_zaznam ORDER BY id DESC LIMIT 100; SELECT * FROM public.archeologicky_zaznam`); další už se logicky vůbec nezapíše, protože v DB vzniká duplicita

Problém byl v užívání jedné Fedory pro dvě instance. Pomohl reset sekvencí a odmazání chybného záznamu z DB. Vyplynula z toho pouze chyba: #1981

**Comment by motyc** [comment]
@pesikj Narazil jsem na dva nové problémy, z nichž první je zcela urgentní:
- [ ] Nefunguje nahrávání souborů přes: http://192.168.254.30:8080/oznameni/ - vrátí v konzoli chybu repozitáře. Důvodem patrně je, že se nyní nevytvoří kontejner a metadata pro vnikající projekt (např. X-C-000001002)
- [ ] Zároveň nadále vznikají zbytečné proxy odkazy, ale to není třeba řešit ihned. Např.:
-- https://fedora-test.aiscr.cz/rest/AMCR/model/dokument/member/8d56eddb-7d95-4d13-874e-9242694cf5b5
-- https://fedora-test.aiscr.cz/rest/AMCR/model/projekt/member/3ed5fea2-0411-4c6f-8cf9-fe98cc975af7
-- https://fedora-test.aiscr.cz/rest/AMCR/model/projekt/member/0a098026-46ef-41b0-b78f-7a7f76d96ffc

**Comment by pesikj** [comment]
@motyc První problém je vyřešen v https://github.com/ARUP-CAS/aiscr-webamcr/commit/d008b87a442ed775ca82348f75a7038fac68d1ef

**Comment by motyc** [comment]
@pesikj Potvrzuji, že funguje, zbytek z tohoto issue stačí řešit později pro produkci.

**Comment by motyc** [comment]
Pro mě - test opravy (nějakou dobu sledovat): https://fedora-test.aiscr.cz/rest/fcr:search?condition=fedora_id%3DAMCR%2F*%2Fmember%2F*&condition=modified%3E%3D2024-07-01T00%3A00%3A00.000Z&offset=0&max_results=100
