### ISSUE TITLE
Příliš časté upozornění na testovací prostředí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1844]
Hláška `Přihlásili jste se do testovací verze aplikace. Veškerá obsažená data jsou zde pouze pro účely testování či školení a nemusí odrážet reálný stav produkční verze na adrese https://amcr.aiscr.cz/` se najednou zobrazuje mnohem častěji než jednou denně. Asi se změnila konfigurace, nebo jde o chybu.

**Comment by pesikj** [comment]
@jnihnat Je to kvůli tému, že ten signál se spustí při aktualizaci uživatelské role. Při aktualizaci uživatelské role je třeba invalidovat vše, protože filtry v tabulkách už nejsou aktuální. Pokud bys to uměl odchytit nějak specificky, tak to můžeš upravit.

**Comment by jnihnat** [comment]
Predelani vse na invalidate_model, tak kdyby se pri testovani zdalo ze po zmene neco ostalo nezmenene dejte vedet.
