### ISSUE TITLE
PAS - chyby filtrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1880]
- [ ] http://192.168.254.30:8080/pas/vyber?druh_nalezu=632&sort=ident_cely
- [ ] http://192.168.254.30:8080/pas/vyber?obdobi=245&sort=datum_nalezu&sort=ident_cely
- [ ] http://192.168.254.30:8080/pas/vyber?oblast=M&historie_typ_zmeny=SN01&sort=ident_cely

**Comment by pesikj** [comment]
@motyc A v čem je problém?

**Comment by motyc** [comment]
> @motyc A v čem je problém?

Vše vracelo 500, možná už to spravil Honza tím včerejším committem.

**Comment by motyc** [comment]
Zavírám
