### ISSUE TITLE
Celery - periodická aktivita

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1881]
Celery nově vyvíjí nějakou dosti zatěžující periodickou aktivitu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5f5d6f03-e4e5-4c72-a4a2-ff9b22facbc5)

Víme o co jde a je to žádoucí?

**Comment by pesikj** [comment]
Já netuším.

**Comment by motyc** [comment]
@pesikj Máme teď spuštěné nějaké periodické úlohy, nebo ne?

**Comment by pesikj** [comment]
@motyc Ano, tyto.

<img width="474" alt="image" src="https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/393e0e62-7f44-40fa-927b-098c44bb28e2">

@jnihnat Mrkni prosím na to nastavení u notifikací, ta `*` na začátku znamená, že se to spouští každou minutu od 2. hodiny do 3. hodiny. S tím grafem se to časově neshoduje, ale možná to není správně.

**Comment by motyc** [comment]
@pesikj Může to být jen problém interpretace času na serveru (časové zóny), takže by to mohlo být spojené.

**Comment by motyc** [comment]
Problém byl v `update_all_redis_snapshots` (http://192.168.254.30:8080/admin/django_celery_beat/periodictask/4/change/). Vyřešeno vypnutím, patrně již není třeba.
