### ISSUE TITLE
Soubory - drobné chyby

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1885]
- [x] Přestalo fungovat zobrazení velkých náhledů ve výběrových tabulkách.
- [x] Soubory v tabulkách v detailu záznamů se neřadí abecedně podle názvu.

**Comment by pesikj** [comment]
@motyc

>  Přestalo fungovat zobrazení velkých náhledů ve výběrových tabulkách.

A netýká se to jen souborů, kde velké náhledy nejsou vygenerované, protože ty soubory byly nahrané dříve? U nově nahraných souborů jsem to teď testoval a funguje to.

**Comment by motyc** [comment]
### Test v0.4.70
- [ ] Náhledy jsou ok, ale řazení stále nefunguje - viz např.: http://192.168.254.30:8080/dokument/detail/X-C-TX-201801103 (XCTX201801103.txt bych čekal první, je mezi T a U)
