### ISSUE TITLE
Optimalizace filesystému

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#19]
Optimalizovat úložiště souborů tak, aby nebylo tolik zatěžující pro filesystem (vytvořením nové struktury složek). Data rozdělit z hlediska nutnosti zálohování a archivace do dílčích složek (vnitřní struktura bude odpovídat implementaci podle potřeb Djanga):
- [x] AG (původně navrženo AGPO) - automaticky generované soubory projektové dokumentace (oznameni z klienta stisknutí zapsat a pri vygenerování nového oznámení)
- [x] PD (původně navrženo OSPD) - ostatní soubory projektove dokumentace
- [x] SD (původně navrženo OSD) - soubory dokumentů při zápisu nového dokumentu
- [x] FN (původně navrženo FDN) - slozka pro fotodokumentaci samostatných nálezů
- automaticky generované dokument řad ZA a ZL - zrušeno (nemigruje se; původně navrženo AGDZZ)

**Comment by motyc** [comment]
![image](https://user-images.githubusercontent.com/20186892/151788715-52b4d9df-14e4-4b17-9596-16a896664aa3.png)

**Comment by pesikj** [comment]
@motyc Chápu správně, že toto issue se týká i migrace (kopírování) souborů? A to už je v rámci migrací nějak řešeno, jen je potřeba upravit cílové adresáře?

**Comment by pesikj** [comment]
@Najiva Ahoj Juraji, větev aiscr-amcr#37 jsem nikde nenašel. Vidím, že už jsi na tom udělal hodně práce. Nevíš, kde ty úpravy jsou?

**Comment by pesikj** [comment]
@motyc A dokážeme ze stávajících záznamů v databáze správně detekovat typ souboru, abychom ho mohli vložit do správné složky?

**Comment by motyc** [comment]
@pesikj Nikoli přímo, ale odvozeně ano. Zde zkusím definovat:
- AG - napojeno na projekt + název ve struktuře "[hash]_oznameni_[ident_cely]*.pdf"
- PD - napojeno na projekt a není AG
- SD - vše co má vazbu na DT Dokument
- FN - vše co má vazbu na samostatný nález
- automaticky generované dokumenty řad ZA a ZL - dokument.rada = ZA | ZL

**Comment by Najiva** [comment]
@pesikj bylo to uz davno takze si moc nepamatuju ale pamatuji si ze se to tehdy nedotahlo a ja si rikal ze to je skoda, protoze se k tomu bude nekdo jiny tezko vracet. Repozitar jsme meli na gitlabu tak mozna je ta vetev tam.

**Comment by pesikj** [comment]
Chyby hlášené @motyc 
1) Oznámení z moravy spadla do PD, místo do AG (např. oznameni_M-201900006.pdf).
2) Soubory log_dokumentace.pdf prosím dát též do AG.
3) Do PD též spadly druhá a další oznámení (např. oznameni_C-201773808A.pdf).
4) Jetě tam jsou nějaká starší oznamení dovozovaná z dočasných ident_cely (např. oznameni_X-C-201999038.pdf) - ty také dát do AG.

**Comment by motyc** [comment]
Na včerejší email jsem neodpověděl, protože jsem se chtěl blíže podívat na data. Jsou většinově správně, ale vypadlo na mne těchto 16 zvláštních souborů:

```
339393 | 1555013852_terms.pdf
339395 | 3360360575_Želva Burgers_21.11.2020.pdf
339400 | 142194681_IMG_3679 - Copy.jpg
339422 | oznameni_C-202105941_A.pdf
339428 | oznameni_C-202105941_D.pdf
339396 | 224988006_FAZ2029882.pdf
339397 | 362085401_Revize elektro.pdf
339398 | 195037839_rozpad vytah.pdf
339399 | 2476412652_WIBID_WIBOR_Reference_Rates_2020.pdf
339403 | 455695002_XCTX202107578.pdf
339404 | oznameni_C-202105929.pdf
339421 | oznameni_C-202200002.pdf
339426 | oznameni_C-202105941_B.pdf
339427 | oznameni_C-202105941_C.pdf

320027 | 1614352256334_.pdf
327907 | 1617709129598_14_archeolog_oznameni_C-202011716.pdf
```

Z nich jen poslední dva se mi podařilo najít na produkci. Na základě uvedeného soudím:
1) data zjevně nejsou z produkčního serveru, takže se v tom míchají soubory vytvořené v testovací verzi webAMČR, čímž vzniká trošku zmatek (soubory jsou špatně pojmenované);
2) `1614352256334_.pdf` vypadá jako sirotek - asi proto skončil v !DO NOT MIGRATE, je to tak?
3) `1617709129598_14_archeolog_oznameni_C-202011716.pdf` je divně pojmenovaný; půjde patrně o ručně nahranou upravenou kopii AG (podle pravidel by mělo padnout do PD)

Jinak je to ale už myslím v pořádku.

**Comment by pesikj** [comment]
Ty soubory, které chybějí na produkci, jsou testovací soubory, které jsem nahrával v rámci testování a mají většinou nesmyslné názvy (aby nebyla duplicita v názvu). To prosím ignorujte.
`320027` má typ vazby `ZA`, proto má `!DO NOT MIGRATE`.

**Comment by motyc** [comment]
@pesikj  Mohu poprosit o informaci, jaká je adresa složky na FTP pro ukládání dat? Pro test si musím zajistit přístup u našich IT, tak abych jim dokázal specifikovat kam.

**Comment by pesikj** [comment]
@motyc Tady je asi problém s tím, že adresář je závislý na ID kontejneru, to ještě upravím (ve vývojovém prostředí jsem to měl jinak) a pošlu adresu.

**Comment by pesikj** [comment]
Mělo by to být zde: `/var/lib/docker/volumes/aiscr-amcr-webclient_static_data/_data`

**Comment by motyc** [comment]
@pesikj Správná složka se zdá být `/var/lib/docker/volumes/aiscr-webamcr_static_data`. Tu starou nepoužívanou složku by bylo vhodné odstranit/odpojit...

**Comment by motyc** [comment]
### Výsledky testu
- [ ] k dockeru je zjevně mountováno více úložišť a některá z nich jsou neaktuální (určitě `aiscr-amcr-webclient_static_data` - jen stará data; nevím jestli i `aiscr-webamcr_locale_data` - to je prázdné)
- [ ] potvrzení o oznámení se generují a ukládají do složky `/_data/media/`, místo aby byly v `/_data/media/soubory/AG/rrrr/mm/dd`
- [ ] Zkusil jsem nahrát foto nálezu (C202010524N00003F04.JPG), kterou bych čekal v `/_data/media/soubory/FN/2022/06/16`. Vůbec nevím, kde skončila (složka vůbec neexistuje).
- [ ] Po nahrání náhrady souboru k dokumentu https://wamcr-test.aiscr.cz/dokument/detail/C-TX-201800285 vznikly v `/_data/media/soubory/SD/2022/06/16` dva soubory místo jednoho: `1529591058098_CTX201800285.pdf`; `1529591058098_CTX201800285_tUjr7dq.pdf`. Problém je asi v tom, že jsem se nejdříve pokusil nahrát foto v jpg a systém zahlásil chybu (i když nečitelnou - html kód v alertu). Přesto se zjevně první soubor nahrál, ale nikoli s příponou `jpg`, ale s příponou `pdf`.

Testování je celkově poněkud problematické, protože při nahrávání souborů systém hlásí nesrozumitelné chyby a chová se nevyzpytatelně:
![image](https://user-images.githubusercontent.com/20186892/174119634-193c93e2-e28d-463f-8765-6e49c9812740.png)

**Comment by pesikj** [comment]
@motyc aiscr-webamcr_locale_data je nutné kvůli překladům, aiscr-amcr-webclient_static_data jsem odstranil.

**Comment by pesikj** [comment]
@motyc

Pole typ_souboru s tímto požadavkem nijak nesouvisí, viz řešení, které používá pole typ_vazby.

**Comment by motyc** [comment]
@pesikj Souvisí, protože vznikl na základě původních úprav Juraje, když toto issue začal řešit, ale nedodělal to. Pokud to pole nepotřebujete, stačí ho smazat a je to. Obsahovalo ty hodnoty jako "OSPD" apod. (viz první post).

**Comment by pesikj** [comment]
@motyc 

>  pro soubory AG se zjevně negeneruje záznam do historie (pole soubor.historie je prázdné

To nijak nesouvisí s ukládáním na file systém.

**Comment by motyc** [comment]
> @motyc
> 
> > do path se cesta ukládá ve dvou formátech:
> 
> To zřejmě souvisí s tím, že některé soubory jsou uploadovány uživatelem a některé generovány přímo. Nicméně na funkci to nemá vliv.

@pesikj A nebylo by dobré to mít sjednocené kvůli exportům atd.? Nevím, jak moc je komplikace to odladit...


> @motyc
> 
> > pro soubory AG se zjevně negeneruje záznam do historie (pole soubor.historie je prázdné
> 
> To nijak nesouvisí s ukládáním na file systém.

Vyčleněno do #597

**Comment by motyc** [comment]
### Výsledek testu
- [ ] patrně chyba v kódu https://github.com/ARUP-CAS/aiscr-webamcr/commit/51d9b8a1538a6de5972db2ebb935e0bea36f3330#r78589124 při dropnutí sloupce; zároveň by bylo dobré dropnout sloupec `soubor.typ_souboru` i ze stávající DB, ať ověříme, že se něco nerozbije
- [ ] Také jsem si všiml, že soubor `log_dokumentace_XY.txt` se dává do PD, ale logicky by měl jít do AG (automaticky generované) - stále platí
- [ ] do path se cesta ukládá ve dvou formátech - stále platí, opravdu bych byl pro jednotnost; je nějaká věcná obtíž v tom, to tak mít? Navíc jsem si teď ještě všim, že ta dlouhá verze cesty (`/vol/web/media/soubory/`) je věcně chybná (neodpovídá cestě na serveru)

**Comment by motyc** [comment]
@pesikj Asi bych v první řadě potřeboval tedy vysvětlit, jak ukládání obsahu a využití pole soubor.path v aplikaci funguje. Na základě toho se dohodneme. Jde o to, že soubory nebudeme určitě ukládat přímo do containeru - v něm by měla být mountovaná složka do úložiště souborů, kde budou data uložena (to je tak snad nyní nastavené - zde prosím o potvrzení @MichalKminek či @vojtakus). Pokud je toto úložiště (mountovaná složka) právě jedno, nerozumím tomu, jak mohou vznikat dvě různé relativní adresy souboru, uložené v soubor.path a jaký to má praktický důvod.

**Comment by MichalKminek** [comment]
Chtel bych se domluvit, aby kontejner nic interne neukladal. Je potreba pripojit volume nebo cestu do hostitelskeho filesystemu. Tedy interni cesta z dockeru /vol/web/media/soubory/ musi vest ven, napr. /var/lib/amcr. Toto zatim neni pripraveno, pripravili bychom na to extra misto. Toto je take zpusob, kdy vice kontejneru muze tyto data sdilet. Chapu to tak, ze dane misto obsahuje dokumenty AMCR - analogie stavajiciho megalitdr adresare? Pokud by to bylo potreba, tak i treba soubor s konfiguraci dockeru muze byt mapovan mimo docker, takze by sel editovat a po restartu patricneho kontejneru by se to nacetlo - konfigurace z hostitelskeho prostredi by se pripojila dovnitr do kontejneru a tan by s ni pracoval. Pripojuje se to stejne jako volumy.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] V AG se složky pro měsíce generují ve dvou formátech ("m" pro oznámení a "mm" pro log dokumentace), sjednotit na "mm" (používáme všude jinde).

Problematiku "soubor.path" a mountování úložiště vyčleňuji k řešení do #365
