### ISSUE TITLE
Testování - dílčí nové chyby

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#192]
Obecné
- [x] v poli s dalšími katastry se zobrazuje za posledním čárka, i když tam žádný další není
- [x] jsou vypnuté našeptávače v textových polích (hlavně na http://192.168.254.30:8080/oznameni/ je to škoda); naopak jinde zapnuté jsou, kde dělají problémy (např. http://192.168.254.30:8080/projekt/edit/ pro datumy, kde to překrývá kalendář)

http://192.168.254.30:8080/projekt/create
- [x] ostatní projekty v mapě se nenačítají předem (mapa je prázdná; zobrazí se až u projektu s existující vlastní lokalizací)

http://192.168.254.30:8080/projekt/detail/
- [x] prvky mapy mají tendenci překrývat rozbalovací seznamy:
![image](https://user-images.githubusercontent.com/20186892/132195708-fcad36b3-3c71-4b28-a677-d69926b147a1.png)

http://192.168.254.30:8080/projekt/edit/
- [x] Zda jsou pole povinná, musí být vázáno na odpovídající procesní stav, jinak nejde smysluplně editovat (od daného stavu povinná jsou):
P0 - https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=1372775774
P2 - https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=801994121
P3 - https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=2097946344
P4 - https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=377696929
P7-P8 - pouze podle P0

http://192.168.254.30:8080/projekt/list
- [x] filtrace Změna stavu obsahuje všechny hodnoty, nikoly jen ty pro projekty

http://192.168.254.30:8080/pas/create
- [x] prvky mapy překrývají seznam:
![image](https://user-images.githubusercontent.com/20186892/132192686-c0e58d98-0074-42c4-91d8-2e428109adc4.png)
- [x] Vyplnění polohy má být v tomto kroku nepovinné

http://192.168.254.30:8080/pas/edit/ulozeni/
- [x] Nález předán - nemá mít volbu “není nastaveno”

http://192.168.254.30:8080/pas/potvrdit/
- [x] Nález lze potvrdit, i když není v předaný “ano”

http://192.168.254.30:8080/historie/spoluprace/
- [x] Typ změny je u starých záznamů proškrtnutý (asi problém migrace)

http://192.168.254.30:8080/pas/spoluprace/zadost
- [x] Chybí tlačítko zpět

http://192.168.254.30:8080/dokument/zapsat/
- [x] Posudky nemají být povinné pole

**Comment by pesikj** [comment]
Rozpiště to prosím do tasků k tomuto issue, děkuji.

**Comment by motyc** [comment]
@pesikj Rozepsáno.

**Comment by pesikj** [comment]
@jnihnat První bod jsem vyřešil.

**Comment by jnihnat** [comment]
bod 5 opraveny v #206 
bod 4 a 7 opravene v #203

**Comment by jnihnat** [comment]
ad2 - tu som vypol len naseptavac u datumu. U poli ktere su "textarea" se naseptavac (ten automaticky z prohlizece) se zapnout neda.

**Comment by jnihnat** [comment]
@motyc 
ad 3 - mozete prosim viac specifikovat? Chcete aby sa pri create projektu v mape zobrazovali lokalizace uz existujicich projektu?
ad 8 - predpokladam ze v tomto pripade je potrebne pridat mapu pri pas/edit?

**Comment by motyc** [comment]
ad 3 - zjednodušeně - ostatní projekty se mají zobrazovat tehdy, pokud je zaškrtnuto "Projekty" ve vrstvách; nyní se zobrazí jen někdy, což je pro uživatele matoucí (netuší, co má udělat, aby je viděl):
![image](https://user-images.githubusercontent.com/20186892/132863267-4ed01ba4-257c-49bb-8338-c015df5887f6.png)

ad 8 - to řešíme jinde (#147); zde je problém v tom, že pas/create vyžaduje vyplnění polohy jako povinné; povinná však má být poloha až při odeslání nálezu do stavu N2;

ad 11 - zde je správná převodní tabulka:
1 -> SP01
2 -> SP12
3 -> SP-1
4 -> SP12

**Comment by DanaKriv** [comment]
@jnihnat Potřebovala jsem otestovat vytváření ID pro ADB (http://192.168.254.30:8080/arch_z/detail/C-202105936A#), ale po stisknutí tlačítka Vytvořit ADB to padá.

**Comment by jnihnat** [comment]
@pesikj nasiel som chybu pre form CreateVyskovyBodForm. su tam pouzite polia northing a easting pre zobrazeni X a Y z pian.geomu, ktore boli ale zmazane v migraci `migrace_mazani.sql`
Mozem ich odobrat z modelu a vo forme nahradit vlastnymi poliami `X` a `Y`. 
otazka - Neviem ale ci je mozne pri vytvarani/uprave vyskoveho bodu ten geom menit, alebo ma byt disabled a brat sa len z pianu. 
@motyc - otazka je nejspis na Vas. Dekuji za odpoved

**Comment by pesikj** [comment]
@jnihnat Díky za zjištění, já už to s @motyc řešil a je potřeba to uložit do nové struktury - sloupec typu Geom, akorát jsem to nedodělal, protože jsem nevěděl, jak na to. Ale už asi vím :-)
