### ISSUE TITLE
Uživatel - chyba odstranění notifikace v administraci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1939]
Při snaze odstranit notifikace na projekty (pes) chyba transakce. Ve správě vlastního účtu jde vše dobře, stejně jako vytváření či editace.

**Comment by pesikj** [comment]
@motyc Otestoval jsem to a žádnou chybu nevidím.

**Comment by motyc** [comment]
@pesikj Zkoušel jsem to teď znovu na http://192.168.254.30:8080/admin/uzivatel/user/3801/change/ - výsledek:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/c2d77882-13cd-4566-bbaa-d3187ebe8f42)

Normálně jsem zaklikl:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/e6e24b53-3f6a-430e-8682-c52a6988ae05)

A poté uložil formulář.

**Comment by pesikj** [comment]
@motyc V logu jsem to dohledal, ale chybu se mi podařilo nasimulovat. Je možné, že ten záznam byl kompromitovaný nějakou předchozí akcí.

**Comment by motyc** [comment]
@pesikj Ja to zkoušel prave na ruznych zaznamech a vsude stejne... Mozna to zkuste na .30. Vytvorit u nekoho notifikaci a pak zkusit smazat.
