### ISSUE TITLE
DJ - chyba přidávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1946]
Nejde zapisovat DJ (tuším, že v tom bude mít prsty @jhavrlant):
http://192.168.254.30:8080/arch-z/akce/detail/C-202402007A/dj/zapsat

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/63d076c1-bb5c-4a1c-8788-a3ed93fd3063)

**Comment by jhavrlant** [comment]
@motyc Moje chyba. Taková drobnost, už jsem to opravil, čeká to na komit.
