### ISSUE TITLE
TR - problém s restartem přes Rosetta

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1969]
Při použití restartu aplikace v http://192.168.254.34:8080/rosetta/files/project/ zjevně server zamrzne a probudí se až po 10 min, kdy jej restartuje healthcheck. Na testu stejná funkce pracuje bez problémů. Pak běží vše správně, vč. nových překladů.

**Comment by jnihnat** [comment]
vola se tohle:
https://uwsgi-docs.readthedocs.io/en/latest/Management.html

**Comment by motyc** [comment]
@jhavrlant Dočasné řešení pomohlo, odsouvám do jiného milestone, ale nechávám otevřené do nalezení přesné příčiny.

**Comment by jhavrlant** [comment]
@motyc Asi nejlepší bude se na to podívat na produkční verzi, až bude připravená, snad se tam ten problém projeví.

**Comment by motyc** [comment]
@jhavrlant Produkční prostředí by už mělo být od Michala připravené, teď ho má v ruce @vojtakus . Je tedy možné to tam případně po dohodě s ním zkoušet.
