### ISSUE TITLE
Organizace a osoby - nejde uložit změny

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1982]
- [x] Kvůli #884 jsem doplnil do editace organizací v administraci pole `cteni_dokumentu`. Pole se zobrazí a vše funguje správně při zápisu nové organizace, nefunguje ale nyní editace existujících organizací (http://192.168.254.30:8080/admin/uzivatel/organizace/1565912/change/) - změny se zdánlivě provedou, ale po novém načtení je vše při starém (i v DB).
- [x] Stejný problém je i u editace osob: http://192.168.254.30:8080/admin/uzivatel/osoba/31146/change/

Nevím, zda jsem něco udělal chybně já, nebo je zakopaný pes jinde.

**Comment by motyc** [comment]
@pesikj Tady jen prosím o review https://github.com/ARUP-CAS/aiscr-webamcr/commit/c8fd4a4d6aed0f0d7253c4a298166f0bd1226d51, protože to @jhavrlant omylem dal přímo do dev. Mám takový dojem, že ta chyba může souviset spíše s mými zásahy do https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/heslar/admin.py, než že by bylo potřeba toto...

**Comment by pesikj** [comment]
@motyc To vypadá ok. Obojí jsem teď testoval na .34 a funguje to.
