### ISSUE TITLE
DJ - nejde přidávat komponenty u DJ s potvrzeným PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1989]
U DJ s potvrzeným PIAN je komplet skryté menu "+" a nejde tak přidávat komponenty, i když by to z pohledu oprávnění jít mělo. Po odpojení PIAN či přidání nepotvrzeného PIAN to funguje. Viz např.: https://amcr-test.aiscr.cz/arch-z/akce/detail/C-9107170A/dj/C-9107170A-D01

Když ručně zadám https://amcr-test.aiscr.cz/arch-z/akce/detail/C-9107170A/dj/C-9107170A-D01/komponenta/zapsat, tak to funguje ok. Problém je tedy opravdu jen v zobrazení menu (bude tam nějaká chybná podmínka).

**Comment by pesikj** [comment]
Mělo by to být vyřešeno v #1991.

**Comment by pesikj** [comment]
Mělo by to být vyřešeno v #1991.
