### ISSUE TITLE
Export - prázdné řádky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1993]
Export vrací prázdné řádky. Pravděpodobně se správně neaktualizují snapshoty. Testováno XLSX podle: http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_typ_zmeny=AZ01&historie_uzivatel=1&sort=stav&sort=ident_cely

Připomínám, že máme vypnutý ten task `update_all_redis_snapshots`, ale neměl být potřeba.

**Comment by pesikj** [comment]
@motyc `update_all_redis_snapshots` musí být spuštěný alespoň jednou, což se zřejmě nestalo. Není nutné ho pouštět opakovaně každou noc.

**Comment by motyc** [comment]
@pesikj Ok, slučuji jako duplicitu do #1713. Problém je v tom, že to bohužel vždy po chvilce spadne na healthcheck, což bude problém i pro TR. Musíme vymyslet, co s tím...

**Comment by motyc** [comment]
Tak problém zavolání update all nevyřešilo, protože si zjevně redis myslím, že je vše hotové (funkce se spustí a hned ukončí):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/6eda1b87-a72f-4780-930b-4caf72bcf8be)
