### ISSUE TITLE
TR - nenačítají se data v položkách "naše"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1997]
Viz např. https://amcr-tr.aiscr.cz/arch-z/akce/vyber?zahrnout_projektove=False&historie_typ_zmeny=AZ01&historie_uzivatel_organizace=315755&sort=stav&sort=ident_cely

Problém tipuji, že bude podobný jako pro #1993, tj. že je nějaký problém s cache/generováním snapshotů. Na TR jsou úplně prázdné i exporty.

**Comment by motyc** [comment]
Na TR jsem teď zkusil cíleně spustit vygenerování snapshotů pomocí `import cron.tasks; cron.tasks.update_snapshot_fields()` , abychom prověřili zda se poté data objeví.

**Comment by jhavrlant** [comment]
@motyc Ten dotaz je závislý na  "historie"."organizace_snapshot_id", takže pokud je políčko prázdné tak nic nenajde.

**Comment by motyc** [comment]
@jhavrlant Ok, tím se to vysvětluje. Musíme tedy otestovat po vyřešení #1713
