### ISSUE TITLE
Převod akce ze samostatné na projektovou a naopak - chyba transakce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2002]
- [x] https://amcr-test.aiscr.cz/arch-z/akce/zmenit-sam-akci/M-9116054A
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/99986d80-ef97-4c5b-a792-d7585a96a00e)

- [x] https://amcr-test.aiscr.cz/arch-z/akce/zmenit-proj-akci/C-201119063A?sent_stav=2

**Comment by motyc** [comment]
### Test v1.0.0-RC3.2
Samotný převod již funguje, ale neudělají se všechny související operace, které by se měly stát při převodu. Testoval jsem M-9123148A -> C-202110748B -> X-C-9000001023A
- [ ] Původní záznam M-9123148A, resp. C-202110748B se nedá se do deleted a neupraví se odkazy (aktualizovala metadata, ale v bez viditelné změny). Pro zjednodušení bych použil chování podle `record_ident_change` - možná půjde přímo použít tato funkce.
- [ ] Neupraví se odkazy u navázaných záznamů (dokumenty, EZ) - metadata ve Fedoře zůstanou, takže odkazy přestanou být relevantní. Podobně pozor na PIAN a ADB (to jsem přímo netestoval, ale může to být problém i tam).

**Comment by motyc** [comment]
### Test v1.0.0-RC3.4
X-C-9000001023A -> C-202008574B - pokus o převod končí chybou:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/bba7259a-f5c4-4c75-93b4-b4d13e996177)

Ve fedoře zůstanou viset tyto kroky, takže tuším že tam buď selhává nebo úplně chybí i ty úpravy vazeb na dokumenty a EZ:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/8a0b0c84-2bc5-4bce-81a1-203373e14a55)

**Comment by pesikj** [comment]
@motyc Zkoušel jsem teď převod této akce: http://192.168.254.30:8080/arch-z/akce/detail/M-201900649B

A proběhlo to bez problémů. Tady jsou je i EZ a dokument. Tak nevím, co bylo v té vaší akci jinak, dohledat se mi ji nepořadilo.

**Comment by motyc** [comment]
@pesikj Stále tam je zde, tak na to můžete mrknout: https://amcr-test.aiscr.cz/arch-z/akce/detail/C-202008574B

Ona se převedla, jen to zůstalo viset ve Fedoře a hodilo to uvedenou hlášku.

**Comment by motyc** [comment]
### Test v1.0.0-RC4
Teď to pro https://amcr-test.aiscr.cz/arch-z/akce/detail/C-202008574B nefunguje vůbec (vrátí 500, jako chybu Fedory). V logu fedory je toto:
![image](https://github.com/user-attachments/assets/d11b50b1-9b43-437c-947a-a4ff670fb1f1)

Z logu Fedory je vyloženě divné, že to teď hned na začátku snaží vytvořit AMCR/record/C-202008574B a související proxy, když oboje existuje a není to potřeba.

Myslím, že to bude třeba pořádně zkontrolovat a zajistit aby to dělalo následující kroky v této posloupnosti:
- (pro převod N -> R) standarně založilo nový záznam s ident_cely podle projektu | (pro převod R -> N) založilo nový záznam s trvalým ident_cely (zde se to nyní snaží založit záznam s dočasným ident_cely)
- do nového záznamu to vložilo replaces a odkaz na starý záznam
- smazalo původní proxy v model/archeologicky_zaznam
- vytvořilo novou proxy v model/archeologicky_zaznam s ident podle původního záznamu a ukazující na nový záznam
- původní záznam vložilo do model/deleted a označilo jako deleted
- upravilo metadata změnou dotčených záznamů:
-- projekt
-- EZ
-- dokumenty
-- ADB
-- PIAN

**Comment by pesikj** [comment]
@motyc Teď jsem zkoušel převést akci X-C-9000001047A a vše prošlo bez problémů. Ta akce, na které jste testoval, už je ve Fedoře nějak poškozená a tím pádem proces končí chybou. Prosím tedy o test na jiné akci.

**Comment by motyc** [comment]
@pesikj Ok, zkusím to celé nějak přetestovat.

**Comment by motyc** [comment]
### Test v1.0.1-rc2
Při testu na jiných záznamech to vypadá lépe, ale jsou tam nějaké nesrovnalosti:
- [ ] https://fedora-test.aiscr.cz/rest/AMCR/record/C-202110748/metadata - při převodu akce na projektovou se do metadat projektu vložil starý ident_cely
- [ ] Při převodu z projektové na samostatnou akci vytvořit akci rovnou s trvalým ident_cely, nikoli s dočasným (z C-201337705A vznikla X-C-9000001049A)

Další dva body plynou z nejasností v zadání, případně nedomyšlenosti a je to třeba upravit:
- [ ] https://fedora-test.aiscr.cz/rest/AMCR/record/C-9150536A (stejně tak https://fedora-test.aiscr.cz/rest/AMCR/record/C-201337705A) - kontejner původní akce se komplet odstraní (bez ohledu na směr převodu); vzhledem k tomu, že jde o záznamy s trvalým ident_cely měly by se jen označit jako deleted a vložit údaj replaced by - problém je i v tom, že pokud takto odstraníme projektovou akci, zápis nové místo ní se zablokuje, protože testujeme jinou situaci (viz např. https://amcr-test.aiscr.cz/arch-z/akce/zapsat/C-201337705)
- [ ] došlo mi, že kvůli předchozímu nemůžeme v tomto případě ani měnit původní proxy v model/archeologicky_zaznam, protože po zápisu nové akce k projektu by odkaz ukazoval na špatný kontejner

Jinak je to dobré (úpravy souvisejících záznamů atd.).
