### ISSUE TITLE
ADB - při smazání se neupraví Fedora

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2040]
Smazání proběhne, ale nezavolají se operace ve Fedoře s tím spojené.

Test na https://fedora-test.aiscr.cz/rest/AMCR/record/ADB-KRAS07-000001

**Comment by pesikj** [comment]
Chybu jsem našel, prosím o test (kvůli špatnému připojení jsem to netestoval).
