### ISSUE TITLE
Apache timeout - prodloužení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2046]
Při exportu většího množství záznamů (např. https://amcr-tr.aiscr.cz/arch-z/akce/vyber?zahrnout_projektove=False&sort=hlavni_katastr&sort=ident_cely) dostanu chybu proxy - nevím, zda nemůže souviset s nějakými time-out, které bude třeba prodloužit.

- [x] prod
- [x] tr
- [x] test
- [ ] dev

**Comment by jhavrlant** [comment]
@motyc Problém bude asi v nastavení apache, protože přes http://192.168.254.34:8080/ se chyba neprojeví (alespoň zatím).

**Comment by motyc** [comment]
Ano, potvrzuji, že to asi bude ono. Prosím, prober to výhledově s @vojtakus nebo @MichalKminek a upravte nastavení.

**Comment by motyc** [comment]
@vojtakus Tak to opravdu vypadá na nějaký problém se timeout po jedné minutě, viz zde
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/66f15c42-10f0-4caa-8673-8847cd13206f)

**Comment by vojtakus** [comment]
Čas prodloužen na tr a prod.

Nastavení v /etc/httpd/conf.d:

```
    Timeout 600
    ProxyTimeout 600

```

Možno otestovat.

**Comment by motyc** [comment]
V pořádku, zavírám. Na DEV dořešíme operativně podle potřeby.
