### ISSUE TITLE
PIAN a ADB - nefunguje signál pro změnu přístupnosti

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2085]
Pokud se změní přístupnost AZ, neupraví se metadata u ADB a PIAN - jejich přístupnost se z AZ odvozuje (dříve fungovalo).

**Comment by pesikj** [comment]
@motyc Tohle pravděpodobně souvisí s přidáním metod `initial_pristupnost` od @jhavrlant. Raději se na to prosím podívejte vy @jhavrlant, mně není úplně jasné, co to má dělat.
