### ISSUE TITLE
AZ - duplicitní proxy odkaz v deleted při změně ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2087]
Při změně ident_cely AZ se proxy v deleted se vytvořila duplicitně:
https://fedora-test.aiscr.cz/rest/AMCR/model/deleted/member/X-C-9000001026A
https://fedora-test.aiscr.cz/rest/AMCR/model/deleted/member/3c5e94aa-99dd-400d-96e3-6d2fa0850b7d

Na dotčený záznam se lze podívat zde: https://fedora-test.aiscr.cz/rest/AMCR/record/C-9004601A (v aplikaci/DB je smazaný)

**Comment by pesikj** [comment]
Testováno zde: https://fedora-test.aiscr.cz/rest/fcr:search?condition=created%3E%3D2024-07-13T00%3A28%3A00.000Z&offset=0&max_results=10
