### ISSUE TITLE
Soubory - náhledy pro soubory, kde je nelze generovat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2095]
Pro řadu typů soborů logicky nejsme schopni vytvářet náhledy. To není velký problém, ale dělá to potíže ve chvíli, kdy nahrazujeme jeden existující soubor jiným souborem jiného typu, u kterého náhled vyrobit nejde. Pak zůstane starý náhled. Ten nemůžeme smazat, protože by to dělalo problém, kdybychom nahráli další verzi, kde by náhled zase byl (existoval by tombstone). Nejlepším řešením by bylo, definovat pro nepodporované formáty nějaké ikony jako placeholdery, které se do Fedory normálně nahrají jako náhled. Každému povolenému typu bychom mohli nastavit náhled samostatně, takže by to i pěkně vypadalo v aplikaci. Vycházet by bylo možné z nějaké knihovny (např. https://www.flaticon.com/free-icons/file-type-file) a referovat to na dílčí typy:
- "text/plain": ("txt", "text"), [txt](https://github.com/user-attachments/assets/3267899c-89cf-49f2-8225-88d44759a088)
- "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ("xlsx"), [xlsx](https://github.com/user-attachments/assets/b6eaba5f-e85b-4dd0-8a83-89348c328970)
- "text/csv": ("csv"), [csv](https://github.com/user-attachments/assets/03a549c0-b233-40a4-8449-afe019c15e99)
- "application/zip": ("zip"), "application/zip-compressed": ("zip"), "application/x-zip-compressed": ("zip"), [zip](https://github.com/user-attachments/assets/bebfecab-c2d1-4a14-98a7-290563dda7ba)
- "application/vnd.rar": ("rar"), "application/x-rar-compressed": ("rar"), "application/x-rar": ("rar"), [rar](https://github.com/user-attachments/assets/2139d4f7-3e5f-457f-a2fb-7e6b48921a10)
- "application/x-7z-compressed": ("7z"), [7z](https://github.com/user-attachments/assets/9d1a675d-758f-42f4-a3a6-534a81dd2b36)
- "application/vnd.ms-excel": ("xls", "xla", "xlb", "xlc", "xlm", "xlt", "xlw"), [xls](https://github.com/user-attachments/assets/b505d048-e76b-41c3-9786-3f1d862704e8)
- "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ("docx"), [docx](https://github.com/user-attachments/assets/af0cad49-1de7-4ae5-b5f1-53f43b3358f9)
- "application/msword": ("doc", "dot", "wiz"), [doc](https://github.com/user-attachments/assets/497761bd-f45a-402c-9091-b865b7732b94)
- "application/rtf": ("rtf"), [rtf](https://github.com/user-attachments/assets/5a3e635b-06f4-446f-a4a0-14669f6fd369)
- "application/vnd.oasis.opendocument.text": ("odt"), [odt](https://github.com/user-attachments/assets/1611e5b5-aab6-41a3-b4d5-a3a9ae059e2e)
- "application/vnd.oasis.opendocument.spreadsheet": ("ods"), [ods](https://github.com/user-attachments/assets/779cfc71-6028-483a-b367-132e7acf0d48)
-----------------
nemělo by to být potřeba pro (tam se náhledy generují - případně revidovat):
- "image/jpeg": ("jpeg", "jpg", "jpe", "jfif", "jfif-tbnl", "jif", "pjpg"),
- "image/png": ("png"),
- "image/tiff": ("tiff", "tif"),
- "image/heic": ("heic", "heif"), "image/heif": ("heic", "heif"),
- "image/svg+xml": ("svg", "svgz"),
- "image/bmp": ("bmp"),
- "image/gif": ("gif"),
- "application/pdf": ("pdf"),

**Comment by motyc** [comment]
@pesikj Po prvního příspěvku doplněny ikony pro všechny možnosti z první skupiny. Mrkněte prosím ještě na ty formáty pod čarou, zda se pro ně pro všechny opravdu náhledy generují. Podle toho bych pak případně také doplnil, pokud by se někde nedělaly. Pro jistotu potvrzuji, že ikonu vztahujeme k mimetype, nikoli přímo k příponě.

**Comment by pesikj** [comment]
@motyc Ještě se negenerují náhledy pro soubory `"image/heic": ("heic", "heif"), "image/heif": ("heic", "heif")`.

**Comment by motyc** [comment]
@pesikj Tady doplňuji: [heic](https://github.com/user-attachments/assets/bfd3ddb8-a960-46a1-b374-7bcbfa52c1e6)

**Comment by jhavrlant** [comment]
@motyc Teď jsem se na to ještě díval a chybí tam text/plain, myslím v komitu.

**Comment by jhavrlant** [comment]
@motyc Taky koukám, že ta detekce formátu občas nefunguje. Nahrál jsem tam csv a dostal jsem txt, což se dá pochopit. Ale pak jsem zkusil náhodný textový soubor [set_repo_prod.txt](https://github.com/user-attachments/files/16398491/set_repo_prod.txt)  a dostal jsem text/x-tex, ale jako uživatel se to nedozvím, jenom to, že obsah neodpovídá příponě. Soubory bez jasné hlavičky jsou problém.
