### ISSUE TITLE
3D - při zápisu se neuloží vybrané aktivity

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2097]
Pokud zapisuji dokumentu přes https://amcr-test.aiscr.cz/dokument/model/zapsat, vybrané aktivity u komponenty se neuloží. Rovnou zkontrolovat, že se i správně vygenerují metadata.

Jinde jsem opravovali v #2039 a #1727

**Comment by pesikj** [comment]
@motyc Tady nevím, jak je to myšleno. Dokument jsem zapsal přes danou adresu a pak se mi komponenty bez problémů uložily.

**Comment by motyc** [comment]
@pesikj Komponenty ano, ale neuloží se obsah pole "aktivity". Teď otestováno znovu a je to tak.

**Comment by pesikj** [comment]
To je pole aktivity tady? To se mi normálně ukládá.
![image](https://github.com/user-attachments/assets/a99d2ec1-af66-42ce-bae3-dbd12237700d)

**Comment by motyc** [comment]
@pesikj Je to ve 3D, proto jsem dával konkrétní odkaz: https://amcr-test.aiscr.cz/dokument/model/zapsat

**Comment by pesikj** [comment]
Ok, díky.
