### ISSUE TITLE
3D - při změně ident_cely se nevytvoří proxy v deleted

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2098]
Vše proběhne ok, ale chybí proxy odkaz v deleted pro původní ident_cely

**Comment by pesikj** [comment]
@motyc Teď jsem to testoval a připadá mi to ok: https://fedora-test.aiscr.cz/rest/AMCR/model/deleted/member/X-C-3D-000001025
Ta implementace je stejná pro všechny modely, takže by to mělo případně nefungovat i pro ostatní modely.

**Comment by motyc** [comment]
@pesikj Pardon, to byla chyba testu. Filtroval jsem to podle času změny a deleted se mi nevešel do filtrace, protože to vycházelo na 2024-07-12T15:56:59.628478Z (hledal jsem >= 2024-07-12T15:57:00.000Z). Zavírám.
