### ISSUE TITLE
Nefunkční registrace při chybě SMTP

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2104]
https://amcr-test.aiscr.cz/accounts/register/ po odeslání vrátí:

![image](https://github.com/user-attachments/assets/cbe81dfb-5944-46ed-925e-84af7e4b9e6d)

Děje se to na .30 i .34, takže to nesouvisí s Mailtrap.

**Comment by pesikj** [comment]
Stejnou chybu vrací i `send_mail('Test Email', 'This is a test email sent from Django.', 'your_email@gmail.com', ['recipient@example.com'], fail_silently=False)`. Spíše myslím, že to souvisí s nastavením dockeru, serveru nebo sítě.

**Comment by motyc** [comment]
@vojtakus @jhavrlant Prosím, kluci, mrkněte na to.

**Comment by pesikj** [comment]
Ještě doplním, že na localhost to žádnou chybu nehlásí.

**Comment by jhavrlant** [comment]
Mě z tréningu mail normálně přišel.

**Comment by motyc** [comment]
Tak nové poznatky:
- na .34 byl problém v tom, že jsem zadával neexistující adresu z domény `@arup.cas.cz`, což SMTP zablokuje, protože pozná, že email v naší doméně neexistuje; s jiným mailem to funguje
- na .30 bych tipoval, že problém je v tom, že mailtrap je teď plný a resetuje se zítra; je možné, že SMTP jakoby něco zahlásí, jinde chyby ignorujeme, ale u registrace ne - to by asi šlo otestovat

**Comment by motyc** [comment]
Ukázalo se, že problém je v tom, že pokud SMTP vrátí při registraci chybu, aplikace to neumí odchytit a předat smysluplnou zprávu zpět uživateli (skončí to na 500). Projevilo se to ve dvou situacích:
- když na .30 je plný mailtrap
- když na .34 má odejít mail na neexistující adresu v doméně @arup.cas.cz (SMTP to vyhodnotí jako chybu a odmítne jej odeslat)

Je třeba to vhodně ošetřit, aby to vrátilo srozumitelnou hlášku a nekončilo to na 500

**Comment by pesikj** [comment]
Přidal jsem upozornění jako message.
