### ISSUE TITLE
Správa uživatelů - při vytvoření uživatele přes administraci se nenastaví výchozí notifikace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2105]
https://amcr-test.aiscr.cz/admin/uzivatel/user/add/ - při vytvoření uživatele přes administraci se nenastaví výchozí notifikace

**Comment by jnihnat** [comment]
Tomuto trocha nechapu. Proc to chceme delat, kdyz admin tu moznost to naklikat ma. Budeme muset zbytecne resit pripady, kde se admin rozhodne pridat jen 2 notifikace napr. Za mne zbytecny overhead na to, ze tento spusob pridavani uzivatel by nemnel byt primarni. Ale rozhodnete se vy, hovorim ze to nebude jen tak je pridat, budeme muset resit ze admin to muze naklikat i sam a rozlisovat to.

**Comment by motyc** [comment]
Řekli jsme si online - není teď prioritní. Preferoval bych opt-out kvůli zmatkům, protože k nim jinak může (a bude docházet).

Už jsem ale pochopil, kde je problém - za mě by byla možnost při přidávání tu část formuláře s nastavením notifikací skrýt a zobrazit ji až při editaci uživatele.

**Comment by jnihnat** [comment]
nakonec jsem to udelal trochu jinak. pri vytvareni se zobrazi vsechny notifikace vybrane. Uzivatel je ma moznost upravit ale nemusi. Pokud neuravi, tak se ulozi vsech 6.
