### ISSUE TITLE
PAS - spolupráce - chyba oprávnění při zapnuté cache

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2108]
Po přihlášení v roli badatele i archeologa vidím v tabulce spolupráce všechny existující záznamy - nijak se tedy nezohledňuje oprávnění. Dříve fungovalo - velmi důležité, prosím o rychlou opravu.

**Comment by jnihnat** [comment]
@motyc a @pesikj - problem spusobuje cache pridana v https://github.com/ARUP-CAS/aiscr-webamcr/pull/1897/files
muzu jednoducho odebrat ale pak asi zase budeme o neco pomalejsi

**Comment by motyc** [comment]
@jnihnat Můžete prosím být konkrétnější, co přesně z pull request to způsobuje? Nejlepší by bylo to opravit, ale cache nelikvidovat.

**Comment by motyc** [comment]
Oprava funguje v pořádku. Bylo by však dobré ještě zjistit, proč nám tam ta cache nefunguje. Proto dávám do bugů k dalšímu prozkoumání.

**Comment by jhavrlant** [comment]
Problém byl, že cacheops vygeneruje vyjímku, že není správně nakonfigurovaný a django filters ji zahodí, takže se nedozvíme, že tam máme chybu.
