### ISSUE TITLE
Soubory - chyba nahrávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2114]
Problém je způsobený patrně touto úpravou:
https://github.com/ARUP-CAS/aiscr-webamcr/commit/e80131b6b936802f627fc4ec9357bc03c5d856b9

Cílem bylo aktualizovat seznam povolených souborů a přípon + to zohlednit v dotčeném slovníku, který se používá při porovnání mimetype nahrávaného souboru. Z nějakého důvodu to teď vůbec nefunguje, byť nemám pocit, že bych to upravil v jiné logice, než tam již byla použitá.

![image](https://github.com/user-attachments/assets/47e5f7a4-cb51-482a-bc48-28237892cb90)

**Comment by motyc** [comment]
Už to vidím, asi jen chyba syntaxe. Opraveno v: https://github.com/ARUP-CAS/aiscr-webamcr/pull/2115

**Comment by jhavrlant** [comment]
@motyc  chyba je ještě v dz.js řádek 137 chybí uvozovky

**Comment by motyc** [comment]
Pravda, díky. Opraveno.
