### ISSUE TITLE
Plánované zahájení  - rozbitý daterangepicker

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2117]
Na žádném z očekávaných míst nefunguje daterangepicker. Zjevně souvisí s opravami zabezepečení, protože konzole hlásí:

![image](https://github.com/user-attachments/assets/10605ff0-11f7-416e-a84c-11585aba661c)

a v důsledku pak:
![image](https://github.com/user-attachments/assets/7fc15aa3-dca3-45b8-85e1-4183e84f07f2)

**Comment by jhavrlant** [comment]
@motyc Na které je to stránce?

**Comment by jhavrlant** [comment]
Navrhuji stáhnout a používat vlastní kopii.

**Comment by motyc** [comment]
@jhavrlant Je to na:
https://amcr-test.aiscr.cz/projekt/zapsat
https://amcr-test.aiscr.cz/projekt/edit/C-202110994
https://amcr-test.aiscr.cz/oznameni/

Jinak souhlas, bude lepší mít to staticky.
