### ISSUE TITLE
Chyba celery

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2120]
![image](https://github.com/user-attachments/assets/324f4542-f526-42cd-bf55-57c0e996ada9)

Rozbil to asi tento commit: https://github.com/ARUP-CAS/aiscr-webamcr/pull/2109/commits/c66ed5a84e6d7b672943e569651a2a02f07088bc

**Comment by pesikj** [comment]
@motyc Tohle nemá s tím commitem nic společného, viz řádek, kde se chyba objevuje
```py
for queue_name, queue_tasks in queue.items():
```
Pravděpodobně nefunguje celery.

**Comment by motyc** [comment]
@pesikj Ok, pardon, už jsem to nestudoval do detailu. Tak na to můžeme mrknout na schůzce i s Honzou. Upravoval ten healthcheck, tak to může souviset.

**Comment by motyc** [comment]
Prozatím vyřešil restart serveru, ale musíme ještě pořádně prověřit.
