### ISSUE TITLE
Hláška o přihlášení do testovací verze

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2123]
Hláška `core.message_constants.neprodukcniTestovaciProstredi.text` se nezobrazuje ani v jednom prostředí. Je třeba zkontrolovat a doladit tak, aby se zobrazovala všude kromě produkce.

**Comment by pesikj** [comment]
Pro správnou funkci je potřeba nastavit v testovacím prostředí hodnotu `TEST_ENV` v secrets na `"True"`.

**Comment by motyc** [comment]
@pesikj @jhavrlant Zobrazuje se nyní i na produkci. Myslím, že bude je třeba upravit patřičný config, ale dávám to sem, abychom nezapomněli.
