### ISSUE TITLE
Import PIAN - akceptovat multi verze geometrií

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2134]
Při přípravě geometrií ve WKT je problém v tom, že zejména ArcGIS vede všechny polygony jako multipolygony, přestože mají jednoduchou geometrii. Abychom nemuseli vytvářet složité návody vně systému, prosím o následující úpravu:
- [x] aplikace bude na importu akceptovat i multi* prvky (MultiPoint, MultiLineString, MultiPolygon)
- [x] jejich zpracování proběhne tak, že se použije ST_GeometryN(geom, 1), tedy vybere se první dostupná geometrie a ostatní se zahodí + systém vrátí upozornění, že k tomu došlo
- [x] variantou je, aby systém rozdělil geometrii na všechny její části a v tabulce je pak vylistoval samostatně - to nepožaduji apriori, pokud to není vyloženě snadné

**Comment by jhavrlant** [comment]
@motyc Dokonce akceptujeme i GEOMETRYCOLLECTION, které se rozloží na základní prvky. Stejně tak se rozloží Polygon s dírami na obvod a díry.
