### ISSUE TITLE
Fedora pro vývoj

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2139]
- [x] Přidat do DEV verze prostředí ([docker-compose-dev-local-db-all-containers.yml](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/docker-compose-dev-local-db-all-containers.yml)) Fedoru, aby bylo možné plně testovat lokálně.
- [x] Vyřešit i vytvoření základní struktury.

**Comment by motyc** [comment]
@pesikj už to máš ozkoušené? Můžu zavřít?

**Comment by pesikj** [comment]
@motyc Ano, už vše funguje.
