### ISSUE TITLE
Zálohy DB se vytváří s každým restartem serveru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2160]
Zálohy DB se vytváří s každým restartem serveru, měly vznikat pouze při nasazení nové verze. Nyní je chování trošku nejasné. Domluvit se, jak vhodně řešit, vč. odstraňování nepotřebných záloh.

**Comment by motyc** [comment]
Proces je třeba přinejmenším optimalizovat.

**Comment by motyc** [comment]
Ještě bude třeba upravit tak, aby ověřovalo, že jsou opravdu všechna připojení ukončená.

**Comment by jhavrlant** [comment]
@motyc Bohužel to ještě není, protože to zlobí jen na produkci, tak to můžu testovat jenom tam. Asi udělám někdy v noci odstávku, a zkusím zase opravu, kterou jsem připravil.

**Comment by motyc** [comment]
@jhavrlant Je vše ok a mohu toto už zavřít?

**Comment by jhavrlant** [comment]
@motyc Můžeš to zavřít, Proběhlo to bez problémů.
