### ISSUE TITLE
Ošetřit automatické updaty serverových komponent

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2161]
Systém při automatické aktualizaci může restartovat některé komponenty (nyní došlo k update a restartu Dockeru). Je třeba nastavit vhodný režim aktualizací tak, aby součásti serverového prostředí nemohly zastavit bez cíleného rozhodnutí admina.

- [x] prod
- [x] tr
- [x] test
- [x] dev

**Comment by vojtakus** [comment]
Automatická obnova balíků dnf-automatic je ponechána s přidáním vyjímky pro docker v /etc/dnf/dnf.conf:
exclude=docker*

**Comment by motyc** [comment]
@vojtakus

**Comment by motyc** [comment]
@vojtakus K tomu ještě dotaz  - máte prosím vymyšleno, kdy a jak budeme aktualizovat Docker, když je to vyřazené z automatiky?

**Comment by MichalKminek** [comment]
Pravidelne kontrolujeme stav updatu na vsech serverech. Update dockeru probehne i na testu a devu a tr. Dame vyjimku i tam, abychom videli, zda balik zastavi kontejnery nebo ne. Nasledne v krajnim pripade na produkci update dockeru s planovanou malou odstavkou. Ke kontejnerum se jeste vratime az dobehne preklopeni ze starsich redhatu. Issue bych zavrel.

**Comment by motyc** [comment]
Ok, díky za vysvětlení. Beru na vědomí a zavírám.
