### ISSUE TITLE
Migrace souborů - problém s většími soubory

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2163]
![image](https://github.com/user-attachments/assets/3fcf2979-8f54-475b-96ba-0dcc897f7373)

Od GPT:
The specific error is BrokenPipeError: [Errno 32] Broken pipe. This error usually occurs when one end of a pipe is closed while the other end is trying to write to it. In this context, it likely means that the receiving end of a data transfer was closed or unavailable when the system tried to send data.
Possible Causes and Considerations:

Network Issues: The connection to the server or storage could have been interrupted, causing the pipe to break.
Server-Side Problems: The server handling the file storage or antivirus checks might have encountered an issue or crashed.
File Size or Transfer Limits: The data being transferred might be too large, causing the receiving server to close the connection.
Configuration or Timeout Issues: There might be a misconfiguration or insufficient timeout settings.
To resolve this issue, you can:

Check network stability and server availability.
Ensure the server's capacity and configuration can handle the data volume.
Investigate any server-side logs for further insights.
Consider handling the BrokenPipeError in your code to attempt a retry or provide a graceful failure message.

Soubor CTX201303014.pdf (43626.pdf) má 244.8 MB

**Comment by motyc** [comment]
Problém je v nastavení antiviru. Po vyřešení sjednotit konfigurace na dílčích serverech

**Comment by jhavrlant** [comment]
@motyc  Nastavil jsem stejné limity na prod, tr a test.

**Comment by motyc** [comment]
Díky, zavírám
