### ISSUE TITLE
Revize popisků - drobné korekce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2176]
- [x] `arch_z.forms.CreateAkceVedouciObjektForm.vedouci.tooltip` a `arch_z.forms.CreateAkceVedouciObjektForm.organizace.tooltip` se nezobrazí u patřičné tabulky (https://amcr-test.aiscr.cz/arch-z/akce/zapsat a https://amcr-test.aiscr.cz/arch-z/akce/edit/C-9004494A)
- [x] `projekt.forms.navrhZruseniProj.reason.tooltip` a `dj.forms.createDjForm.pianText.tooltip` - toto nějak vůbec neumím najít, kde se použije - není zbytečné?

**Comment by jnihnat** [comment]
projekt.forms.navrhZruseniProj.reason.tooltip - projekt navrhnout zruseni a pod textem jiny duvod:
![image](https://github.com/user-attachments/assets/a8312e18-70d1-43a5-9427-526e83845dfb)

dj.forms.createDjForm.pianText.tooltip - odstranene, lebo sa nikdy nezobrazi, kedze pian_tex je vzdy read only

**Comment by jnihnat** [comment]
Otestujte prosim tooltipy i pod dokument tvary tabulkou.

**Comment by motyc** [comment]
### Test v1.0.4-rc1
- [ ] `arch_z.forms.CreateAkceVedouciObjektForm.vedouci.tooltip` divně zalamuje:
![image](https://github.com/user-attachments/assets/90eed534-d46d-4a25-a843-bc204ee74b9d)
- [ ] `projekt.forms.navrhZruseniProj.reason.tooltip` - navedl jste mne na umístění `projekt.forms.navrhZruseniProj.reasonText.tooltip` - ten vidím a je ok, ale ten první ne

Tvary jsou ok, ty jsem prověřil.

**Comment by motyc** [comment]
@jnihnat Na ten problém se zalamováním jsem narazil ještě tady: https://amcr-test.aiscr.cz/dokument/detail/M-TX-198401579/cast/M-TX-198401579-D002
![image](https://github.com/user-attachments/assets/c290af58-fa5d-4989-a78b-67f1cef18e92)

Klidně opravu zahrňte večer do https://github.com/ARUP-CAS/aiscr-webamcr/pull/2200

**Comment by jnihnat** [comment]
opraveno v #2200
