### ISSUE TITLE
Chyba logování IP adres

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2209]
Při přihlášení uživatele logujeme IP adresu, ale ukládá se nám vždy nějaká lokální IP serveru.

Zde přehled z TR serveru:
![image](https://github.com/user-attachments/assets/0fdb66da-a97e-49ca-8db1-0cb55b215d3d)

**Comment by jhavrlant** [comment]
Pro info dávám stránku, která se věnuje tomuto problému https://stackoverflow.com/questions/49415595/docker-swarm-get-real-ip-client-host-in-nginx

**Comment by motyc** [comment]
@jhavrlant Teď mi to na testu místo 10.0.0.2 loguje 172.23.0.1. Ať přes ipconfig hledám jakkoli, tak nemůžu najít nic, co by s tím korespondovalo. Čeho to může být IP?

**Comment by jhavrlant** [comment]
@motyc Máme dvě možnosti, vrátit tu opravu [364ef03](https://github.com/ARUP-CAS/aiscr-webamcr/commit/364ef03fe3523234e2f9c4b5880af77baaffd7e2) co jsem dělal předtím a bude fungovat monitoring djanga bez změny secret, ale nebude fungovat logování IP adres při otevření aplikace přes IP adresu nebo změníme secret a bude fungovat obojí logování.

**Comment by motyc** [comment]
@jhavrlant Secret změnit můžeme, to ničemu nevadí. Nebo ano?
