### ISSUE TITLE
Chyba při smazání uživatele - prověření cache v administraci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2217]
Po smazání uživatele na produkci jsem dostal 500:

http://192.168.254.37:5601/app/discover#/doc/30e56f65-7740-4841-8afa-ec6c9ccda77c/amcr?id=Duq6DZEBg6ddjnvGukNd

U jiných to však šlo dobře - byl to trošku specifický účet (původní superadmin účet ze staré aplikace).

**Comment by motyc** [comment]
@jhavrlant Napadá mě, že v mailu nebyl vůbec validní mail (bez zavináče atd. - jen string "admin"). Může to asi souviset.

**Comment by motyc** [comment]
@jhavrlant Toto asi bude spíš na @pesikj

**Comment by pesikj** [comment]
@motyc Uživatel nemá vazbu na historii, což by podle mě korektně vytvořený účet mít měl. Nejjednodušší bude v databázi historii doplnit.

**Comment by motyc** [comment]
Co přesně máte na mysli tím "nemá vazbu na historii"? Já jsem teď na ten účet koukal na 30 i 34 a v obou případech má vyplněno pole historie i záznam v historie_vazby. Co tedy přesněji chybělo?

Na prod už je účet smazaný, jen jsem tam musel ručně dořešit Fedoru...

**Comment by motyc** [comment]
@pesikj Máte pravdu, že na testu to funguje, ale z nějakého důvodu se to jinak chová na produkci - teď jsem pro test vytvořil vazbu: https://amcr.aiscr.cz/admin/heslar/heslarhierarchie/1210/change/ a dotčená hesla se neupravila :(

**Comment by pesikj** [comment]
@motyc Je tam chybová hláška, takže musel chybět záznam v tabulce `historie_vazby`. Pokud je to jinde v pořádku, tak to prosím zkuste taky smazat a případně se podívejte, zda tam není jiná chyba.

```
historie.models.HistorieVazby.DoesNotExist: HistorieVazby matching query does not exist.
```

**Comment by motyc** [comment]
Tak na TEST i TR šlo smazání bez problémů. Je to fakt divné. Inu, nevadí, issue zavírám, asi to byla nějaká zvláštní situace.

**Comment by motyc** [comment]
Ještě to znovu raději otevírám pro kontrolu - nedivil bych se, kdyby to rovněž souviselo nějak s cache, když se to seklo na tomto:
![image](https://github.com/user-attachments/assets/83018807-1f2d-471b-8101-609919ed7739)

Prosím důsledně prověřit, že se z tou cache v administraci nakládá všude správně.

**Comment by motyc** [comment]
Možná to mohlo souviset s #2220
