### ISSUE TITLE
Chyba signálů při vypnutém debug mode

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2220]
https://amcr-test.aiscr.cz/admin/heslar/heslarhierarchie/

Dříve fungovalo, musel se rozbít signál či je problém s cache.

**Comment by pesikj** [comment]
@motyc Teď jsem to testoval a k aktualizaci došlo, v kódu je taky vše v pořádku.

**Comment by motyc** [comment]
@pesikj Máte pravdu, že na testu to funguje, ale z nějakého důvodu se to jinak chová na produkci - teď jsem pro test vytvořil vazbu: https://amcr.aiscr.cz/admin/heslar/heslarhierarchie/1210/change/ a dotčená hesla se neupravila :(

**Comment by motyc** [comment]
@pesikj Ještě jeden poznatek, na produkci funguje signál pouze při smazání vazby. Přidání a update nefunguje.

**Comment by motyc** [comment]
Verze aplikací jsou na test i prod shodné a na oboje chodím přes doménové jméno.

**Comment by motyc** [comment]
Doplňuji, na 34 (TR) to také nejde.

**Comment by pesikj** [comment]
@motyc Přidal jsem invalidaci, po nasazení to prosím otestujte.

**Comment by motyc** [comment]
Viz https://github.com/ARUP-CAS/aiscr-webamcr/pull/2244#discussion_r1702686592

**Comment by jhavrlant** [comment]
@pesikj  @motyc Zjistil jsem, že chyba se objevuje pokud je debug mod vypnutý. Vyzkoušeno na dev. S debug modem funguje bez něj ne.

**Comment by jhavrlant** [comment]
@motyc  @pesikj  Tak už je to jasné. Je potřeba přidat k signálům  weak=False viz. https://stackoverflow.com/questions/69003196/django-signal-only-works-when-debug-true-django-3-2-4

**Comment by pesikj** [comment]
@jhavrlant Super, díky.
