### ISSUE TITLE
Konkurenční úpravy jednoho záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2245]
Navazuje na #2215

> http://192.168.254.34:5601/app/discover#/doc/858d02c4-091e-44c1-9600-ddb1a3dbaf32/amcr?id=-eWD_pABbIKW8Eg7CmFe
> http://192.168.254.34:5601/app/discover#/doc/858d02c4-091e-44c1-9600-ddb1a3dbaf32/amcr?id=9uWD_pABbIKW8Eg7CWGH

@jhavrlant @pesikj Hledal jsem, co se mohlo stát, a zdá se mi, že problém je viditelný zde: http://192.168.254.34:5601/app/discover#/doc/858d02c4-091e-44c1-9600-ddb1a3dbaf32/amcr?id=1OWD_pABbIKW8Eg7B2Fo
![image](https://github.com/user-attachments/assets/8e2ef086-c3c9-45d1-8050-923833a24841)

Do nějaké chvíle tam běží transakce [0e8fbdb4-c236-4d92-8b34-03829f13cc87](http://192.168.254.34:5601/app/discover#/view/3776ef29-cf88-4689-ad71-d2541c7699b9?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2024-07-29T12:41:56.000Z',to:'2024-07-29T12:42:00.000Z'))&_a=(columns:!(level,message,path,logger_name,transaction),filters:!(),grid:(),hideChart:!f,index:'858d02c4-091e-44c1-9600-ddb1a3dbaf32',interval:auto,query:(language:kuery,query:%220e8fbdb4-c236-4d92-8b34-03829f13cc87%22),sort:!(!('@timestamp',desc)))). Najednou je vyvolána nová transakce [68f10bf3-5efc-4f5f-9700-1277729232a5](http://192.168.254.34:5601/app/discover#/view/3776ef29-cf88-4689-ad71-d2541c7699b9?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2024-07-29T12:31:56.000Z',to:'2024-07-29T12:43:00.000Z'))&_a=(columns:!(level,message,path,logger_name,transaction),filters:!(),grid:(),hideChart:!f,index:'858d02c4-091e-44c1-9600-ddb1a3dbaf32',interval:auto,query:(language:kuery,query:%2268f10bf3-5efc-4f5f-9700-1277729232a5%22),sort:!(!('@timestamp',desc)))) nad stejným PIAN. To logicky skončí chybou.

Mám pocit, že to může být něčím klikáním v aplikaci bez čekání na dokončení úlohy. Něco podobného se mi podařilo reprodukovat tak, že jsem si stejný záznam otevřel ve dvou oknech, udělal stejnou úpravu a odeslal v obou oknech najednou. To bychom měli zkusit případně odchytit a správně vyhodnotit (nejen pro PIAN, ale obecně).

Asi to nebude mít snadné řešení, ale prosím zamyslete se. co se s tím dá dělat. Může se to asi dotýkat různých situací na různých úrovních.

**Comment by pesikj** [comment]
@motyc @jhavrlant
Podle mě můžeme použít následující řešení:
Zprávu o úspěšném uložení nebudeme vyvolávat v editačním pohledu, ale až v následujícím pohledu na základě informace o správném zápisu dat do Fedory (které proběhne až po úspěšném zápisu do databáze). Transakce uloží informaci o svém úspěšném commitu do redius a pohled si z redisu informaci o uložení následně načte a podle toho zobrazí zprávu o úspěchu nebo neúspěch. Tím bude zajištěno, že informace o úspěšném uložení nebude zobrazena, pokud uložení úspěšné nebylo.

**Comment by motyc** [comment]
@pesikj Za mne je to asi ok, ale je to hlavně na posouzení @jhavrlant , protože nedohlédnu přesné důsledky. Můžeš mi prosím jen ještě víc vysvětlit, co myslíš tímto (jak se to bude projevovat?):

> Chování aplikace tady nebude úplně konzistentní, ale to je dáno tím, že část aplikace používá function-based view a část aplikace class-based views.

Důležité hlavně je, aby bylo spolehlivě zajištěno, že ať už se to dostane do kteréhokoli bodu, tak v případě chyby proběhne ten rollback v DB i ve Fedoře...

**Comment by pesikj** [comment]
@motyc Jde o to, že v některých případech se ukáže chybová stránka a v některých případech bude uživatel přesměrován na detail záznamu a zobrazí se červená pop-up zpráva nahoře. Práce s daty se to netýká, ta bude vždy stejná.

**Comment by motyc** [comment]
@pesikj Ok, to se tedy nedá nic dělat a není to myslím velký problém.

**Comment by motyc** [comment]
### Test v1.0.12-rc6
- [ ] https://amcr-test.aiscr.cz/ext-zdroj/ext-odkaz/edit/akce/X-C-9000001058A/896?next_url=/arch-z/akce/detail/X-C-9000001058A - nefunguje úprava paginace (500)
- [ ] Při editaci výškového bodu (úprava výšky) nedojde k aktualizaci metadat ADB.
- [ ] Pokud chci smazat externí zdroj, který má nějaké externí odkazy, aplikace to nedovolí, ale chybí hláška pro uživatele.
- [ ] https://amcr-test.aiscr.cz/dokument/cast/edit/C-TX-193000574-D001 - nefunguje úprava (500)
- [ ] Při potvrzení spolupráce přes mail se neupraví metadata (např. https://amcr-test.aiscr.cz/pas/spoluprace/aktivace-email/836).
