### ISSUE TITLE
Chyba v logu při validaci plánovaného zahájení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2247]
Navazuje na #2215.

http://192.168.254.37:5601/app/discover#/doc/30e56f65-7740-4841-8afa-ec6c9ccda77c/amcr?id=MhbZG5EBIONj-bekrL9_

Zdá se, že tam je nějaký problém s tím doplňováním data. Když se vše zadá dobře, funguje to, ale v nějakých situacích to zjevně hází 500. Nasimulovat se mi to ale nedaří.

Mohou to ale být volání od nějakého robota, protože jde o chyby v divné časy žádné reálné nové podání tam zatím nemáme.

**Comment by jhavrlant** [comment]
@motyc Zjistil jsem, že date range může být otevřený i uzavřený viz: https://www.postgresql.org/docs/current/rangetypes.html#RANGETYPES-INCLUSIVITY 
, ale předělávat už to asi nebudeme.

**Comment by motyc** [comment]
@jhavrlant To jo, ale ta naše komponenta tam vždy posílá ten polootevřený. Ale to nevadí, určitě bych do tho nehrabal. Spíš jen jde o to, co znamená ten error.
