### ISSUE TITLE
Timeout při vyhledávání volného ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2263]
Pokus o odeslání akce https://amcr.aiscr.cz/arch-z/akce/detail/X-M-9000000008A končí na timeout (http://192.168.254.37:5601/app/discover#/doc/30e56f65-7740-4841-8afa-ec6c9ccda77c/amcr?id=IMkdRpEB9bJNXVlEN8Lk). Zjevně se čeká na nějakou operaci, kterou se nedaří provést a skočí to tak chybou a zaseklou transakcí ve Fedoře

Podobná situace nastává u všech akcí v rozsahu X-M-9000000006A - X-M-9000000013A a vše jde opakovaně nasimulovat. Editace akcí funguje v pořádku. Zároveň to nesouvisí s připojeným dokumentem (https://amcr.aiscr.cz/dokument/detail/M-TX-202400192), protože i po jeho odpojení je chování stejné.

Na testu se mi to nepodařilo nasimulovat. Ve Fedoře vše vypadá ok.

Zde popis od uživatele:
> Vyplnil jsem standardně vše, co je u akce vyžadováno a doplnil dokument (jde o expertní posudky typu geofyzikální zpráva – tedy bez NZ), doplnil PIAN importem a kliknul odeslat, ale k odeslání nedošlo.
> Žádné anomálie jsem nesledoval, ale čím mohou být akce nestandardní: nemají NZ (pole Nahrazuje NZ: Ano), PIAN byl importován, ze svého účtu vyplňuji a posunuji stavy za jinou organizaci.

-----------------------

EDIT: Problém odhalen - v tabulkách sekvencí pro ident_cely nebyly příslušné záznamy a proces nalezení správného čísla trval příliš dlouho. Proto vše nakonec padlo na timeout. Upravím příslušné tabulky se sekvencemi, ale chtělo by to zároveň optimalizovat skripty pro přidělování tak, aby bylo vyhledání prázdné pozice efektivnější.

**Comment by motyc** [comment]
Problém odhalen - v tabulkách sekvencí pro ident_cely nebyly příslušné záznamy a proces nalezení správného čísla trval příliš dlouho. Proto vše nakonec padlo na timeout. Upravím příslušné tabulky se sekvencemi, ale chtělo by to zároveň optimalizovat skripty pro přidělování tak, aby bylo vyhledání prázdné pozice efektivnější.

**Comment by jnihnat** [comment]
tedka skousim akce u sebe, projit 400 000 zaznamu mi trvalo sekundu a pul:
webamcr-web-1            | 2024-09-30 15:02:15,111 DEBUG current sequence ID: 200002
webamcr-web-1            | 2024-09-30 15:02:16,771 DEBUG arch_z.models.get_akce_ident.missing
webamcr-web-1            | 2024-09-30 15:02:16,771 DEBUG new sequence ID: 600003

**Comment by motyc** [comment]
@jnihnat Pak bude problém asi někde jinde... Nechme to otevřené a zkusím to nasimulovat na testu, jak se to bude chovat pro jednotlivé konkrétní případy. Možná to opravdu nakonec bylo jen tím, že tam některé řádky nebyly vůbec, takže to nekonečně dlouho čekalo na odpověď, která nepřišla, protože jejich vytváření bylo rozbité. Je možné, že se mi toho zpětně pomotalo více dohromady.

**Comment by jnihnat** [comment]
skousel sem hledat jeste v elasticu a po tom jak se najde nove Sequence ID, tak se zacnou prepisovat ID u Komponent a DJ a nikde tohle nevidim v logu. Takze mozna predse jen byl zadrhel v tom ulozeni do DB co predelaval @jhavrlant a po novu uz to bude fungovat.
Pripadne ak chces skusit na velkem setu u samostatne akce s regionem M.
```
--BEFORE TEST akce region M
create table arch_z_temp_mock (new_id INT);

with rows as (
INSERT INTO archeologicky_zaznam (ident_cely, typ_zaznamu,stav,hlavni_katastr,pristupnost)
SELECT
    'M-9' || i || 'A','A',2,324400,868
FROM generate_series(200000, 600001) as i
RETURNING id
)
insert into arch_z_temp_mock (new_id)
	select id from rows;

update akce_sekvence 
set sekvence = 200000
where region = 'M';


--AFTER TEST
delete from archeologicky_zaznam
where id in (select new_id from arch_z_temp_mock);

drop table arch_z_temp_mock;
```

**Comment by motyc** [comment]
Jo, opravdu se zdá, že skript samotný bude ok, jen byl problém s tím zápisem řádků. Ještě to ale prověřím, díky za dotaz pro test. Já to asi otestuju primárně tak, že teď na testu v DB umažu řádek se sekvencí, resp. upravím jeho obsah a pak zkusím něco zapsat...
