### ISSUE TITLE
Fix code scanning alert - Construction of a cookie using user-supplied input.

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2272]
Tracking issue for:
- [ ] https://github.com/ARUP-CAS/aiscr-webamcr/security/code-scanning/60

**Comment by jhavrlant** [comment]
Je to v pořádku, ident_cely se kontroluje hned na začátku  https://github.com/ARUP-CAS/aiscr-webamcr/blob/4858b45a648113cf497b378223f82aecb0d6f599/webclient/komponenta/views.py#L276
takže ho nemůže útočník zneužít k útoku.
