### ISSUE TITLE
Redis varování při startu

### ISSUE THREAD

**Issue by jhavrlant** [ARUP-CAS/aiscr-webamcr#2277]
Po startu kontejneru redis v jeho logu je toto varování:
 9:C 21 Aug 2024 12:50:18.332 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

To varován je na tr i na prod

**Comment by vojtakus** [comment]
Změna nastavení vm.overcommit_memory = 1 je teď provedena nejprve na tr.

**Comment by vojtakus** [comment]
Nastavení provedeno na prod:
`# cat /proc/sys/vm/overcommit_memory`
`1`

**Comment by motyc** [comment]
@jhavrlant Je vše ok a mohu toto už zavřít?

**Comment by jhavrlant** [comment]
@motyc Můžeš to zavřít, Hláška se už nezobrazuje.
