### ISSUE TITLE
Rozšířit obsah některých autocomplete

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2293]
Při zobrazení některých výběrových seznamů doplnit více údajů, aby se v seznamech dalo lépe orientovat:
- [x] `arch-z/autocomplete/akce` - upravit na `ident_cely (hlavni_katastr; hlavni_vedouci; datum_zahajeni - datum_ukonceni)`
- [x] `arch-z/autocomplete/lokalita` - upravit na `ident_cely (nazev)`
- [x] `projekt/autocomplete/archz` - upravit na `ident_cely (hlavni_katastr; vedouci_projektu)`
- [x] `projekt/autocomplete/dokument` - upravit na `ident_cely (hlavni_katastr; vedouci_projektu)`
- [x] `dokument/autocomplete` - upravit na `ident_cely (autori_snapshot: rok)`
- [x] `ext-zdroj/autocomplete` - upravit na `ident_cely (autori_snapshot rok: nazev)`

**Comment by jnihnat** [comment]
@motyc roztahnu i to pole, at se to tam vse vejde:
![Image](https://github.com/user-attachments/assets/01c35952-730e-497c-810a-d99ee85190d3)

**Comment by motyc** [comment]
@jnihnat Ano, určitě. Díky moc.

**Comment by jnihnat** [comment]
taky u:
dokument/autocomplete - upravit na ident_cely (autori_snapshot rok)

ext-zdroj/autocomplete - upravit na ident_cely (autori_snapshot rok: nazev)

si nie som isty ktery rok to je a nazev, tedka mam u dokumentu `rok_vzniku` a u ez `rok_vydani_vzniku: result.nazev`

**Comment by motyc** [comment]
Ano, to je správně.

**Comment by motyc** [comment]
### Test v1.0.12-rc1
Funguje dobře, jen dvě upřesnění:
- [ ] Výsledky jsou nyní řazené zvláštně na přeskáčku, řadit vzestupně podle ident_cely
- [ ] Šlo by, aby se při zápisu z vyhledávacího pole prohledávaly i údaje z jiných polí než ident_cely? Pokud je to komplikované, oddělíme do jiného issue a necháme na později.

**Comment by jnihnat** [comment]
Pridane i filtrace, az na arch-z podle `datum_zahajeni - datum_ukonceni` pokud chceme i tohle radeji samostatne issue, bude treba vymyslet jaky format podporovat pri zadavani a pod.
