### ISSUE TITLE
Projekty - chyba výběru v historii

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2296]
https://amcr.aiscr.cz/projekt/vyber?historie_typ_zmeny=P01&historie_typ_zmeny=PX1&historie_datum_zmeny_od_after=4.8.2024&historie_datum_zmeny_od_before=4.8.2024&sort=hlavni_katastr&sort=ident_cely - vrátí prázdný výsledek s chybovou hláškou pod polem ve filtraci, přestože dotaz byl zadán přes formulář a měl by být dobře:
![image](https://github.com/user-attachments/assets/dd3cf213-127b-43cf-b3e7-aa852b920c00)

Pravděpodobně je tam nějaký problém s UCase, který rozbije chování filtrace.

**Comment by jnihnat** [comment]
Bolo to trochu zlozitejsi to najit. neni to typo, ale byla tam chyba a ta plati pro vsechny filtre na historii typ zmeny, nefungovalo to nikde ked sa vybrala vice nez 1 moznost.

**Comment by motyc** [comment]
Aha. Tak super, že jsi na to přišel. Po nasazení to zkusím pořádně protestovat.
