### ISSUE TITLE
E-P-02 chodí i badatelům

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2297]
E-P-02 - chodí i badatelům, i když by měl chodit jen archeologům a výše

**Comment by jnihnat** [comment]
pokud dobre chapu kod, tak E-P-02 je hlidaci pes co si nastavuje uzivatel. Pokud jo, tak navrhuji zakazat nastaveni pro badatele. @motyc co vy na to? Samozrejme s osetrenim kdyz uzivatel zmeni roli.

**Comment by motyc** [comment]
@jnihnat To omezení už právě nastavené je (přes oprávnění pro URL). Problém byl u migrovaných účtů (tam jsme to ručně odebrali), ale do budoucna bude i v situaci, kdy někomu odebereme oprávnění. Přijde mi nejjednodušší při odeslání zkontrolovat, že daný uživatel je archeolog, archivář nebo admin. To je neprůstřelné a nemusíme řešit žádné výjimky.

**Comment by motyc** [comment]
### Test v1.0.12-rc1
Bohužel nefunkční. Email o zápisu projektu https://amcr-test.aiscr.cz/projekt/detail/C-202402075 odešel i pro https://amcr-test.aiscr.cz/admin/uzivatel/user/2543/change/, přestože jde o badatele.
