### ISSUE TITLE
Nedostupná poslední položka v seznamech

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2299]
V některých výběrových seznamech není vidět poslední položka, protože rolovátko jakoby nedojede do konce a seznam je uříznutý. Týká se  to např. výběru datace u komponenty, výběru posudků při zápisu dokumentů nebo výběru formátu při zápisu 3d modelu:

![image](https://github.com/user-attachments/assets/e150c8a8-76f8-482b-b44d-997b20ec46e3)

**Comment by jhavrlant** [comment]
@motyc Ta chyba byla vytvořena při řešení #2057. Díval jsem se na ten problém a nejjednodušší by bylo vypnout to malé rozbalení a vše rozbalovat jako specifikace předmětu na tom videu.

**Comment by motyc** [comment]
@jhavrlant Ano, s tím určitě nemám problém. Hlavní je, aby to nějak rozumně fungovalo :)
