### ISSUE TITLE
EZ - duplicitně pojmenované tlačítko

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2301]
U EZ není rozlišeno tlačítko pro zápis (https://amcr-test.aiscr.cz/ext-zdroj/zapsat) a pro uložení změn při editaci (https://amcr-test.aiscr.cz/ext-zdroj/edit/X-BIB-0995406). Druhé by mělo mít jiný popisek, je tak třeba mít pro něj jiný klíč.

**Comment by jnihnat** [comment]
ez.templates.create.ulozitButton.label nahrazeno:

create - ez.templates.ExterniZdrojCreateView.ulozitButton.label
edit - ez.templates.ExterniZdrojEditView.ulozitButton.label
