### ISSUE TITLE
AZ - archivace bez komponent

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2302]
Aplikace správně ověřuje, že všechny pozitivní DJ mají komponenty při odeslání archeologického záznamu. Totéž je však třeba ověřovat i při archivaci záznamu, kde nyní ověření chybí.

**Comment by jhavrlant** [comment]
@motyc  Neměla by se podobná kontrola dělat také u Dokument, Lokalita, PAS a možná i u Projektu?
Pokud tomu dobře rozumím tak stačí přidat kontrolu před odesláním do kontroly před archivací.

**Comment by motyc** [comment]
@jhavrlant Ano, mělo by to platit univerzálně, že pokud je něco povinné pro odeslání, je to povinné i pro archivaci. Díky za poznámku.
