### ISSUE TITLE
Žádosti o zpřístupnění údajů o oznamovateli

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2309]
- [x] upravit viditelnost oznamovatele tak, aby byl viditelný ještě jeden měsíc od přihlášení kvůli omezení predátorského přihlašování
- [x] umožnit požádat o zaslání skrytých (nikoli smazaných) os. údajů přímo skrz aplikaci s vepsáním zdůvodnění, takže by nám přišel mail a vždy by se taková žádost dala ad hoc posoudit a vyřídit - přibylo by jako položka v menu projektu, pokud je oznamovatel skrytý

**Comment by jnihnat** [comment]
@motyc k bodu 2. Pokud uzivatel klikne na novou moznost:
- Zobrazim modal
- Modal bude mit textove pole pro vepsani zduvodneni
- Po potvrzeni posleme email - na jakou adresu a jak ma vypadat template?

**Comment by motyc** [comment]
@jnihnat Dobré otázky:

ad 1 - je to další `elif` pro `user.hlavni_role.id == ROLE_ARCHEOLOG_ID`, tj. na konec přidat něco v tomto smyslu:
```python
            elif (
                projekt.stav in [PROJEKT_STAV_PRIHLASENY, PROJEKT_STAV_ZAHAJENY_V_TERENU, PROJEKT_STAV_UKONCENY_V_TERENU, PROJEKT_STAV_UZAVRENY]
                ):
                last_prihlaseni = projekt.historie.get_last_transaction_date(PRIHLASENI_PROJ)
                if last_prihlaseni and last_prihlaseni["datum"] >= datetime.now(last_uzavreni["datum"].tzinfo) - timedelta(days=30):
                    show_oznamovatel = True
``` 

ad 2
- ano
- ano
- adresa pro odeslání bude info@amapa.cz (ideálně dát do konfigurace), pro tělo mailu založ html, dej mi echo a já ho naplním (jen mi tam prosím jako předlohu prosím napiš, jak vložit to zdůvodnění z modalu)

Označení mailu bude "E-P-08".

**Comment by motyc** [comment]
### Test v1.0.12-rc1
- [ ] Pole v žádosti prosím upravit na textarea, ať se tam lépe zapisuje.

Jinak je chování v pořádku.

**Comment by jnihnat** [comment]
@motyc kolik radku?

**Comment by motyc** [comment]
@jnihnat Třeba 5.

**Comment by motyc** [comment]
### Test v1.0.12-rc4
- [ ] V rosettě chybí tyto klíče (posledně bohužel nešlo otestovat):
-- projekt.views.ZadostUdajeOznamovatelView.title.text
-- projekt.views.ZadostUdajeOznamovatelView.submitButton.text
