### ISSUE TITLE
Přepínání jazyka trvá dlouho

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2347]
Přepínání jazyků trvá poměrně dlouho a systém nedává žádnou indikaci, že se něco děje. Může to být do budoucna dost matoucí a chtělo by to buď zrychlit, nebo doplnit nějaký indikátor aktivity.

**Comment by motyc** [comment]
### Test v1.0.12-rc1
Situace se moc nezlepšila (trvá skoro 10 sec), navíc se neaplikují nové překlady

**Comment by motyc** [comment]
### Test v1.0.12-rc4
Už to běhá skvěle rychle, ale problém je, že se neaplikují změny překladů ani s restartem. Upravil jsem arch_z.templates.arch_z.arch_z_detail.toolbar.dalsiVolby.title (vidět zde: https://amcr-test.aiscr.cz/arch-z/akce/detail/X-C-9000001051A), ale vypisuje se stále "Akce" místo "Akce - test"

**Comment by jnihnat** [comment]
@motyc Dnes v kalendary opraveno. Co se tyka prveho bodu, tak to mi funguje. Nastavil jsem na treninku Akce test a je to tam.

**Comment by motyc** [comment]
@jnihnat Na tréninku ano (.34 = amcr-tr), ale ne na testu (.30 = amcr-test), kde je ta aktuálně testovaná verze.

**Comment by jnihnat** [comment]
@motyc z nejakeho duvodu prestal fungovat uwsgi.reload(). koukam na to uz hodinu a neprisel jsem zatim na to. ale restart celeho swarmu zabral... takze jen ten reload uvnitr aplikace nefunguje. nevis ci tam Honza nahodou neco neupravoval? Nebo nebyl nejaky update na servery?

**Comment by motyc** [comment]
Nevim o tom, ze by do toho nejak hrabal, ani te by se menilo prostredi :( 

Tak to uz dnes nech byt. Znamena to asi, ze to nebude velky zasah do kodu, tak se na to pak muze jeste podivat Honza, az se v utery vrati... Nebo te treba jeste neco pres vikend napadne.

Updatovali jsme to jQuery, to me jediné napada + nejake knihovny pres GitHub. Tak jeste tam muze byt nejaka zmena.

**Comment by motyc** [comment]
@jnihnat Ponížení verze pomohlo.
