### ISSUE TITLE
PAS - načtení současné polohy

### ISSUE THREAD

**Issue by jiri-bartos-huld** [ARUP-CAS/aiscr-webamcr#235]
PAS - načítání současné polohy  - DN: při použití se u mne nic nestane (ať už při editaci, nebo při zápisu nového nálezu)

**Comment by jiri-bartos-huld** [comment]
Nacitani soucasne polohy je omezeno pouze pres HTTPS
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

**Comment by pbartosova** [comment]
Testovat lze pouze jako to dělají vývojáři, lokálně. A nebo zkusit vymyslet něco s Vojtou a Michalem.

**Comment by motyc** [comment]
Funguje, zavírám.
