### ISSUE TITLE
Upravit podmínky pro přístupnost projektu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2353]
Přístupnost projektu (`pristupnost_pom`) se stanovuje podle navázaných záznamů, ale prozatím se zohledňují jen nálezy PAS. Upravit tak, aby se:
- [x] nadále vždy defaultně vkládalo `PRISTUPNOST_ANONYM_ID`
- [x] pro `TYP_PROJEKTU_PRUZKUM_ID` používal nadále dotaz jako dosud, tj.:
```plpgsql
SELECT heslar.ident_cely, heslar.heslo FROM heslar
JOIN samostatny_nalez ON heslar.id = samostatny_nalez.pristupnost
JOIN projekt ON projekt.id = samostatny_nalez.projekt
WHERE projekt.ident_cely = 'XY'
ORDER BY heslar.razeni ASC LIMIT 1;
``` 
- [x] pro `TYP_PROJEKTU_ZACHRANNY_ID` a `TYP_PROJEKTU_BADATELSKY_ID` se začal používat dotaz
```plpgsql
SELECT heslar.ident_cely, heslar.heslo FROM heslar
JOIN archeologicky_zaznam ON heslar.id = archeologicky_zaznam.pristupnost
JOIN akce ON archeologicky_zaznam.id = akce.archeologicky_zaznam
JOIN projekt ON akce.projekt = projekt.id
WHERE projekt.ident_cely = 'XY'
ORDER BY heslar.razeni ASC LIMIT 1;
``` 

------------
- [x] Po zpracování bude tam, kde dojde ke změně, třeba přegenerovat metadata Fedory.

**Comment by pesikj** [comment]
@motyc Asi jsi myslel `pristupnost`, `pristupnost_pom` je u PIANu.

**Comment by motyc** [comment]
@pesikj Projekt také nemá vlastní, ale asi je to je problém pojmenování, protože v modelu se to jmenuje jen `pristupnost`, přestože v DB to pole není. V XML je to pak `pristupnost_pom` - viz:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/4710caf35908c95c6a9ec291d73af2767c74e7b5/webclient/xml_generator/definitions/amcr.xsd#L50

**Comment by pesikj** [comment]
@motyc Tady je kód pro Django shell na úpravu metadat

```py
from heslar.hesla_dynamicka import TYP_PROJEKTU_ZACHRANNY_ID, TYP_PROJEKTU_BADATELSKY_ID, get_id_from_heslar
from projekt.models import Projekt
from core.repository_connector import FedoraTransaction

def find_projects_needing_update():
    anonym = get_id_from_heslar("HES-000865")
    for item in Projekt.objects.filter(typ_projektu__in=(TYP_PROJEKTU_ZACHRANNY_ID, TYP_PROJEKTU_BADATELSKY_ID)).iterator():
        if item.pristupnost.pk != anonym:
            yield item

for item in find_projects_needing_update():
    item: Projekt
    print(item.ident_cely)
    fedora_transaction = FedoraTransaction()
    item.save_metadata(fedora_transaction)
    fedora_transaction.mark_transaction_as_closed()
```

**Comment by pesikj** [comment]
@motyc 

> Projekt také nemá vlastní, ale asi je to jen problém pojmenování, protože v modelu se to jmenuje jen pristupnost, přestože v DB to pole není. 

Ano, bude to jenom rozdílné pojmenování.

**Comment by motyc** [comment]
@pesikj Bezva, nezapomněl jsi jen udělat PR?

**Comment by motyc** [comment]
### Test v1.0.13-rc1
Po pokusu změnit přístupnost u akce error 500 (https://amcr-test.aiscr.cz/arch-z/akce/edit/C-202011835A)

**Comment by motyc** [comment]
### Test v1.0.13-rc8
- [ ] Nová implementace pro záchranné a badatelské projekty je ok, ale přestalo to fungovat pro průzkumy. Např. zde bych čekal archeologa, je tam ale anonym: https://amcr-test.aiscr.cz/projekt/detail/C-202011835
