### ISSUE TITLE
Dropzone na Win10 nepozná RAR a 7z

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2355]
Tyto typy souborů tak nejdou nahrávat. Je to možné nějak šikovně ošetřit?

**Comment by motyc** [comment]
### Test v1.0.13-rc1
- [ ] Nahrávání už funguje, pokud ale rozkliknu dialog pro výběr souborů, musím nechat zobrazit všechny soubory, abych RAR a 7z viděl. Šlo by ještě zařídit, aby byly mezi těmi filtrovanými sobory rovnou?

**Comment by motyc** [comment]
@jhavrlant Bohužel žádná změna oproti předchozímu testu (na Win10 i Win11; oboje test v Chrome)

**Comment by jhavrlant** [comment]
@motyc Mě to funguje, ale je potřeba dát pozor, jestli nemáš starou verzi v cache a taky každá stránka načítá jiné formáty viz [dz.js](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/dz.js). S nahráváním aktuálních statických souborů jsou problémy, Snažil jsem se to nějak řešit, ale zatím jsem to vzdal, ta konfigurace je trochu nestandardní.

**Comment by motyc** [comment]
Ani smazání cache nepomáhá :( Ale to nevadí. Necháme to být. Nahrát to tam nějak případně jde (minimáln drag&drop) a jde o marginálii.
