### ISSUE TITLE
Nefunguje kontrola datumů v anglické lokalizaci

### ISSUE THREAD

**Issue by jhavrlant** [ARUP-CAS/aiscr-webamcr#2369]
Pokud se přepne do anglické verze tak nefunguje kontrola datumů. Např https://amcr-test.aiscr.cz/projekt/edit/C-201665792 při pokusu o uložení hodí chybu neplatné datu, protože očekává anglický formát. Pravděpodobně to souvisí s tím že nastavení USE_L10N bylo v Djangu 5 odstraněno. Otázka je jestli v anglické verzi používat anglické formátování datumů a k tomu i kontrolu, nebo použít český formát.

**Comment by motyc** [comment]
@jhavrlant Používal bych všude jednotně český formát, protože by úprava asi byla spíš více matoucí.
