### ISSUE TITLE
Optimalizace načítání stránek s náhledy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2376]
Stránky, kde se načítá větší množství náhledů se načítají velmi dlouho. Bylo by dobré upravit tak, aby se stránka zobrazila a nečekalo se na donačtení všech náhkedů. Některé projekty či akce takto v podstatě nejde otevřít (např. https://amcr.aiscr.cz/projekt/detail/M-202300130).

Bude se týkat:
- výběru v PAS
- výběru dokumentů
- výběru ve 3D
- akcí s mnoha dokumenty
- lokalit s mnoha dokumenty
- projektů s mnoha nálezy

Domluvte se prosím, kdo to zkusí upravit.

**Comment by jnihnat** [comment]
@motyc - mas prosim nejaky priklad z testu/treninku? Vybery by totiz mnely fungovat uz tedka.

**Comment by motyc** [comment]
@jnihnat Na testu se to neprojevuje, protože tam nemáme tolik těch náhledů. Musel bych je tam importovat, ale to se dělá blbě, protože v tabulkách je to řazené jinak, než v DB. Vyrobil jsem Ti teď na produkci admin účet pod jnihnat@gmail.com, tak to můžeš prohlédnout tam, jen prosím opravdu dávej pozor, ať něco omylem neupravíš, nesmažeš, nebo tak... Heslo si nastav přes reset hesla.

**Comment by jnihnat** [comment]
Tak jsem to nasel. Jirka pridal volani do Fedory ci existuje nahled souboru kvuly tomu zobrazeni skaredy ikony a to spomalovalo vse. Odebral jsem to a upravil pres CSS aby se to nezobrazovalo kdyz tak.

**Comment by motyc** [comment]
@jnihnat Super, díky moc. Ještě prosím o odpověď zde, jinak je to myslím hotové: https://github.com/ARUP-CAS/aiscr-webamcr/pull/2386#discussion_r1774101941

**Comment by motyc** [comment]
### Test v1.0.12
Bohužel na testu to nebylo možné ověřit, takže až na produkci - načítání tabulek funguje dobře, ale otevření projekt https://amcr.aiscr.cz/projekt/detail/M-202300130 stále končí na time-out (resp. trvá nekonečně dlouho). Optimalizaci tedy bude třeba udělat jinak.

**Comment by pesikj** [comment]
Tady by podle mě mohlo pomoci asynchronní načítání těch obrázků.

**Comment by motyc** [comment]
Problém nemusí souviset jen s náhledy - pomalé je obecně načítání tabulek s navázanými záznamy, kde je jich velké množství (např. napojených k EZ: https://amcr.aiscr.cz/ext-zdroj/detail/BIB-0005695)

**Comment by pesikj** [comment]
@motyc Nejspíše to bude více věcí dohromady.

**Comment by jnihnat** [comment]
pridal som asynchronni nacitani na detailu projektu pro nalezy a ez pro akce a lokality.
Ocakavame jeste nekde velke mnozstvi zaznamu at to udelam i tam?

**Comment by motyc** [comment]
@jnihnat jeste to mohou byt dokumenty u AZ - taky jich muze byt hodne, kdyz jde o foto.

**Comment by jnihnat** [comment]
na 30 je napr dobry projekt na otestovanie M-202300130.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
- [ ] Načítání vypadá, že funguje dobře, nicméně v některých tabulkách teď nejde používat ovládací ikony (klikání na ně nic nedělá), jde o:
-- dokumenty u AZ i u projektů - nejde odpojovat
-- AZ v detailu EZ - nejde odpojovat ani editovat paginaci

Upravoval jsem nově oprávnění (viz tabulka URLs), ale v principu mi nepřijde, že to souvisí, protože na tlačítko prostě nejde kliknout. Když si přes admin tools vykopíruji související odkaz, adresa funguje a oprávnění se chovají v pořádku.

**Comment by motyc** [comment]
### Test v1.0.13-rc
- [ ] Ovládací prvky už fungují dobře, ale neskrývá se editace paginace a odpojení v detailu EZ, pokud na ně nemám oprávnění (je to vidět dobře zde: https://amcr-test.aiscr.cz/ext-zdroj/detail/BIB-0000012); v detailu akce/lokality je to ok.
- [ ] Podobně se pak správně neskrývá tlačítko pro odpojení dokumentu zde: https://amcr-test.aiscr.cz/arch-z/lokalita/detail/C-N1000126 či zde https://amcr-test.aiscr.cz/arch-z/akce/detail/C-9149037A (oprávnění se vyhodnocuje správně).

Jinak se vše chová už v pořádku.
