### ISSUE TITLE
Chybné vyhodnocení katastrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2390]
Od @svejci 
U akce C-202310201A (https://amcr.aiscr.cz/arch-z/akce/detail/C-202310201A) uživatel chtěl odstranit nadbytečný katastr (Nové Benátky) z akce. myslel jsem, že jsou to opět stará data a vyřeším to opět přidáním a smazáním nějaké pracovní DJ. Tady nadbytečný kaastr ale stále zůstává (správně jsou Dražice). Prohlédl jsem připojené DJ a jejich PIAN a, pokud jsem se nepřehlédl, jsou podle mapy všechny jen na jednom katatrálním území. Když jsem si to testoval v tréninkévé verzi (https://amcr-tr.aiscr.cz/arch-z/akce/detail/X-C-9000000023A), tak PIAN ještě 10 m uvnitř správného katastru doplňuje katastr vedlejší. Podle cuzk by měla být katastrální mapa aktuální od 2014.

Podle mého testování se skutečně jedná o chybu. Je otázka, kde vzniká - nemůže tam být nějaký problém v transformaci souřadnic?

**Comment by jhavrlant** [comment]
@motyc Problém bude zřejmě v datech viz obrázek {červená čára jsou hranice z databáze tabulka ruian_katastr pole hranice)
![image](https://github.com/user-attachments/assets/bd81b20f-2425-4368-b3dd-41022c6fdaa5)
Nevím jaký je přesně zdroj dat, ale vypadá to že hranice jsou nějakým způsobem zjednodušené.

**Comment by motyc** [comment]
Safra to je divné. Pak to ale nemá teď snadné řešení a holt to tak bude muset zůstat, asi do zpracování #372. Ještě to prozkoumám...

**Comment by motyc** [comment]
Potvrzeno, že jde o problém nepřesnosti dat. Dále bude řešeno v #372
