### ISSUE TITLE
Nevhodné překrývání hlášek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2412]
- [x] Pokud edituji komponentu a její nálezy (podobné to asi bude u DJ + ADB + VB, možná i jinde), zobrazují se dvě samostatné hlášky o úspěchu/neúspěchu úpravy. Ty se navíc překrývají, takže i když zadám něco chybně v nálezech, zobrazí se mi zelená hláška, že bylo vše úspěšné, pod kterou je skrytá červená, že nikoli. Bylo by dobré to nějak sloučit a vyhodnocovat sjednoceně.
- [x] Zdvojená je nyní třeba i hláška při zápisu projektu a posunech jeho stavů.
- [x] Zdvojená hláška po uložení změn v editaci dokumentu (např. https://amcr-test.aiscr.cz/dokument/edit/X-C-TX-000001060)
- [x] Zdvojená hláška při mazání akce, která nejde smazat kvůli vazbám (např. má ADB).
- [x] Zápis 3D modelu (hláška je zdvojená).

Může částečně souviset s #2245

**Comment by pesikj** [comment]
Tou určitě souvisí s #2245. Ale prosím o kontrolu i opačného problému, tj. nezobrazující se hlášky nebo generické hlášky o úpravě záznamu (i když myslím, že drtivou většinu problémů řešil PR ze soboty a včerejšího večera).

**Comment by motyc** [comment]
### Test v1.0.13-rc1
- [ ] Chtěl jsem otestovat `Zdvojená hláška při mazání akce, která nejde smazat kvůli vazbám (např. má ADB).` a po pokusu smazat https://amcr-test.aiscr.cz/arch-z/akce/detail/X-C-9000001058A se záznam zablokoval a hází 500. Je to podobné, jako problém u #2459 a tuším, že problém bude stejný. Ke smazání dojít nemělo, pouze měla vyskočit chybová hláška.

**Comment by pesikj** [comment]
@motyc Tady už asi vím, čím to bylo. Nasimulovat to nedokážu, ale mělo by to být odstraněné (pro success zprávy podobná oprava funguje).
