### ISSUE TITLE
Zvyseni verze uwsgi

### ISSUE THREAD

**Issue by jnihnat** [ARUP-CAS/aiscr-webamcr#2429]
UWSGI verze se musela snizit kvuli #2347. Treba proskoumat proc v nove verzi nefunguje uwsgi.reload a kdyz tak vyresit.

**Comment by motyc** [comment]
@jnihnat Díky, zařazeno.

**Comment by jnihnat** [comment]
tak jsem to rozchodil u sebe a pak dohledal i opravu, je to chyna uwsgi a opravena ve verzi 28. (Otestovano lokalne a naozaj funguje) - link na uwsgi PR - https://github.com/unbit/uwsgi/pull/2689
Bude teda vyreseno bumpem na verzi 28

**Comment by motyc** [comment]
Super, děkuju!
