### ISSUE TITLE
Reklamace po předání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#244]
http://192.168.254.30:8080/projekt/create
- [x] 3 - _Pokud se kalendář u plánovaného zahájení nevejde celý na obrazovku, nejde jeho chybějící část zobrazit pouze drobným posunem, ale je nutné rolovat až na úplný konec obrazovky, pak se teprve posune. Kalendář se otočením kolečka myši posune (spolu s formulářem), pokud je na něm kurzor. Problém bude v tom, že se v okně při zmenšení vytváří dvě nezávislá rolovátka._ DN: původní problém ok, ale proč je najednou kalendář řešen vertikálně (dva kalendáře pod sebou) a nikoli horizontálně, jako je to na https://wamcr-test.aiscr.cz/oznameni/? Je pak zcela zbytečně třeba scrollovat.

----------------

http://http://192.168.254.30:8080/projekt/smazat
- [x] 10 - _Projekty nejdou smazat - po klinutí na “Smazat objekt” vyskočí error 500._ EDIT: Sice již nevrací error 500, ale smazat stále nejde (např. https://wamcr-test.aiscr.cz/projekt/detail/C-201700025)

----------------

http://192.168.254.30:8080/arch_z/detail/
- [x] 14 - Omezení typů DJ funguje správně při editaci první DJ, při přidání zcela nové první DJ však lze vybrat cokoli.
- [x] 16 - _Nejde odpojit dokumenty (chyba 500)._ EDIT: již nevrací 500, ale odpojovat stále nejdou

----------------

http://192.168.254.30:8080/projekt/uzavrit/
- [x] 29 - Pokud uzavírám projekt k jehož akcím jsou připojeny dokumenty, v některých případech nedojde k jejich posunu z D1 do D2. Příklad - http://192.168.254.30:8080/projekt/detail/C-202105946. Akce C-202105946A má dva dokumenty, první ve stavu odeslán, druhý zapsán. Po odeslání akce se jejich stav nezměnil. Akce C-202105946B má jeden dokument, akci i dokument jsem ponechala ve stavu zapsán. Pak jsem ukončila výzkum a uzavřela projekt. Akce C-202105946A je ve stavu odeslaná, stav dokumentů se nezměnil (první odeslán, druhý zapsán). Akce C-202105946B i její dokument jsou ve stavu odeslán. U C-202105947 to ale bylo opačně, akce se dvěma dokumenty (jedním odeslaným a druhým zapsaným) je má po uzavření oba odeslané a u akce s jedním dokumentem se stav nezměnil. Nedaří se vysledovat jednotnou příčinu.

**Comment by motyc** [comment]
Chtěl jsem otestovat opravy, ale zjevně to není nasazené, takže se vyjadřuji jen k dotazům (pardon za dlouhou odezvu, dříve jsem se k tomu prostě nedostal).

ad 4 - kolegyně myslím narážela na to, že u povinných polí vyskakuje chybová hláška někdy jako pop-up, ![image](https://user-images.githubusercontent.com/20186892/140102821-eafd89f7-04fb-4997-9345-a93ebe94a3b6.png)
a někdy jako text pod polem ![image](https://user-images.githubusercontent.com/20186892/140102955-5c6083d8-010b-4cec-a551-e1b9891b2edb.png). To by mi ale nijak zvlášť nevadilo (asi to souvisí s validací před odesláním a po odeslání). Problém je primárně v tom chybovém stavu, který nastane, když tam zadám chybný řetězec. Přijde mi, jak kdyby se projekt zapsal a validace u oznamovatele proběhla až poté, takže se to tím dostane do chybového stavu. To mi nepřijde jako ideální. Projekt bych do DB vložil až ve chvíli, kdy validace pro celý formulář budou ok.

ad 17 - Ano, tam byl problém s těmi drop-downy, zejména protože nejde vykopírovat číslo PIAN. Rozumím, proč to tak je. Zatím to přeskočte a o řešení se případně ještě pobavíme. Ono by to nemuselo být úplně podstatné, protože tam stejně ještě budeme patrně dělat nějaký zásah, který to asi vyřeší.

**Comment by jnihnat** [comment]
@motyc - to ukladani v 4 som vyresil. To rozdielne zobrazeni error je presne tak ako pisete, jedno je validace uz na stranke vdaka bootstrapu a jednu je za na strane BE a proto se to zobrazuje jinak.

**Comment by motyc** [comment]
Doplněn bod 31

**Comment by motyc** [comment]
@pesikj V nasazené verzi otestovány položky označené jako vyřešené a odstraněny z prvního příspěvku.

**Comment by pesikj** [comment]
@motyc 
31 je vyřešeno převodem do pop-upu.

**Comment by motyc** [comment]
@pesikj Revidováno - odstraněny již nerelevantní body.

**Comment by pesikj** [comment]
@jnihnat Honzo, prosím, podívej se na zbylé body. Díky.

**Comment by motyc** [comment]
@jnihnat Ano, u projektové akce jen tyto dvě.

**Comment by jnihnat** [comment]
bod 10 a 16 mozne otestovat hned, opravny script pusten nad nadabazy.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Smazání projektu zdánlivě proběhne dobře, ale po návratu na projekt zjevně záznam stále existuje.
- [ ] Odpojení dokumentu již funguje, ale při odpojování se smažou i archivované dokumenty (testováno u https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-200810779A), místo aby se jen odpojily.
![image](https://user-images.githubusercontent.com/20186892/175911545-0ff5554f-a68a-454f-89f3-972e23ac134f.png)

**Comment by jnihnat** [comment]
Mazani mozne otestovat hned.
