### ISSUE TITLE
Problémy při vytváření PIAN

### ISSUE THREAD

**Issue by jiri-bartos-huld** [ARUP-CAS/aiscr-webamcr#245]
Při vytváření PIAN se u polygonů nedaří uzavřít geometrii kliknutím na počáteční bod (je třeba kliknout na ikonu pro úpravu geometrie a pak někam volně do prostoru). Stejně tak se nedaří vytvořenou geometrii v mapě smazat (geometrie se vždy znovu objeví). V obou případech zůstávají při práci viset tlačítka jak Dokončit nebo Storno a po kliknutí se nic nestane. Když přidám bod, není už cesty zpět a nejde kreslit linii či polygon. Funkcionalita je zjevně celkově rozbitá.

**Comment by motyc** [comment]
@jiri-bartos-huld Podařilo se nasimulovat u https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-200913623C

Kliknu na D02 -> Přidat nový PIAN -> udělám polygon -> kliknu na první bod -> tvar změní barvu, ale zůstane aktivní editace a aplikace se dostane do chybového stavu (kliknutí na dokončit též nic nedělá, funguje jen storno, ale také nějak podivně):
![image](https://user-images.githubusercontent.com/20186892/171848742-7a9fdd15-b8c1-4b1a-9d72-5c398bf2c6a5.png)
