### ISSUE TITLE
Prověřit opakované odesílání emailů při potvrzení účtu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2452]
od @svejci 

> Občas se stane, že přijde několik e-mailů, že ten samý uživatelský účet čeká na aktivaci. Většinou jsou to 2 e-maily, dnes u jednoho účtu 3 (ID: U-004855). Jsou buď ze stejné hodiny a minuty, nebo třeba minutu po sobě. Čím je toto způsobeno? Také uživatel kliká opakovaně před doběhnutím nějakého procesu? Primárně mi nejde o to, že chodí 2 e-maily s žádostí o aktivaci, ale pokud by příčina byla jiná než opakované klikání, tak jestli nechodí i jiné e-maily takto opakovaně, což může být pro uživatele buď matoucí nebo obtěžující.
> 2024-09-27 - přišlo k U-004861 celkem 11 e-mailů v totožné hodině a minutě

Prověřit, zda je problém čistě na straně uživatele (opakované klikání na odkaz v mailu) a zda to jde nějak omezit.

**Comment by jnihnat** [comment]
pridana podminka do aktivace, aby se neposlal email znovu po kliknuti na link, kdyz byl poslan uspesne v poslednych 10 minutach.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
Testováno na https://amcr-test.aiscr.cz/accounts/activate/Im5vdmFraW9hc2h1ZWFAYXJ1cC5jYXMuY3oi:1t69lu:COQbQlpggUbkoq1aYmhi3GUcLl3fHX97q1VPg5rIIO0/ a bohužel to nefunguje. E-U-02 sice přijde jen jednou, ale E-U-04 přijde tolikrát, kolikrát použiju odkaz.
