### ISSUE TITLE
EZ - chyba při mazání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2459]
Navazuje na #2245 - Pokud chci smazat externí zdroj, který má nějaké externí odkazy, aplikace to nedovolí, ale chybí hláška pro uživatele. 

Zkusil jsem smazat záznam https://amcr-test.aiscr.cz/ext-zdroj/detail/X-BIB-0995406 a výsledkem je 500 a to tak, že záznam teď ani nejde otevřít; žádná transakce ale nevisí, musí to být něco jiného. Chyba 500 je vázaná pouze na danou session. V jiném okně pod jiným uživatelem se záznam otevře. Samotné odhlášení a přihlášení ale nepomůže.

**Comment by motyc** [comment]
@pesikj Já když se snažím otevřít https://amcr-test.aiscr.cz/ext-zdroj/detail/X-BIB-0995406, tak stále dostávám 500 :(

Hlásím se pod účtem novak@arup.cas.cz

**Comment by pesikj** [comment]
@motyc Zkoušel jsi to teď? Já tu chybu nevidím v logu.

![image](https://github.com/user-attachments/assets/a7a459f9-df99-47d2-9658-1e988d4a3704)
