### ISSUE TITLE
Problém s připojením k https://code.jquery.com/

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#247]
Aplikace se vůbec nenačte a konzole hlásí chybu `VM241:6772 crbug/1173575, non-JS module files deprecated.`

Podrobný rozbor a řešení zde: https://github.com/ARUP-CAS/aiscr-webamcr/issues/247#issuecomment-1026907053

**Comment by jnihnat** [comment]
@motyc prosim na ktorom servery se tohle vyskytuje? Skusil som 192.168.254.24 tak aj 192.168.254.30 a na oboch vse funguje spravne. Dekuji.

**Comment by motyc** [comment]
Zkoušel jsem to doma přes VPN, kde mi to vůbec nefungovalo (včera i před tím během týdne). Nyní v práci mi to také jde. Ještě to tedy prověřím, až budu zpět doma pokusím se zjistit, v čem je problém.

**Comment by motyc** [comment]
@jnihnat Tak znovu otestováno a je to velice zvláštní - chvilku mi to funguje a pak to zase najednou nejde. Děje se to podobně v různých prohlížečích.

Zde report z Chrome konzole:
![image](https://user-images.githubusercontent.com/20186892/146895004-1a688a4e-cebd-4228-9d6b-d21b437d8506.png)

A zde z Mozilly:
![image](https://user-images.githubusercontent.com/20186892/146895148-bcdd3dc9-3baa-44cf-ac11-d7ccc9f91f65.png)

**Comment by jnihnat** [comment]
Z konzole je vidno ze padne request na jquery, co vysvetluje preco nefunguje vicero veci. Z ni vsak uz neni zrejme kvuli cemu to ale padne, ten request se ale dela uz z browseru. Muze byt ze to zablokuje firewall napriklad. Pro lepsi pochopeni by som ale potreboval videt export ze Site (v developer modu) kdyz se to stane. V mozile je to po kliknuti na pravym tlacitkem mysi a Ulozit vsetko ako HAR.

**Comment by motyc** [comment]
Zde to je, snad jsem to exportoval správně:
[wamcr-test.aiscr.cz_Archive [21-12-21 10-52-27].zip](https://github.com/ARUP-CAS/aiscr-webamcr/files/7751331/wamcr-test.aiscr.cz_Archive.21-12-21.10-52-27.zip)

**Comment by motyc** [comment]
Ad block používám jen v Chrom, ale tím to být nemůže, protože ho nemám v jiných prohlížečích a navíc jej mám i v práci, kde mi to jde v pořádku. Divné ale je, že to chvilkami funguje (tj, nezablokuje se to vždy).

Cookies jsem zkoušel promazat. Ten response pošlu, až budu zase u dotčeného PC. Zkusím také ještě na chvilku shodit antivir/firewall.

**Comment by motyc** [comment]
Zkouším otevřít https://code.jquery.com/jquery-3.5.1.min.js a chová se to hrozně zvláštně. V Chrome někdy vše projde ok a zobrazí se:
![image](https://user-images.githubusercontent.com/20186892/147086934-25d46b99-60ef-479d-b48d-c03fba670cfb.png)

Jenže po refreshi nebo při dalším pokusu se vrátí toto:
![image](https://user-images.githubusercontent.com/20186892/147087037-d0355769-39cf-4c64-bb7c-dc46fb4357b7.png)

Podobně se chová Mozilla - někdy projde, někdy neprojde.

Když to zrovna funguje, tak běží dobře i https://wamcr-test.aiscr.cz/. Zdá se to jako nějaká podivnost na síti, ale vůbec nechápu, o co by mohlo jít. Kdyby Vás napadlo, kde může být problém, tak budu vděčný. Také se pokusím hledat příčiny.

**Comment by motyc** [comment]
Našel jsem k tomu následující, ale přiznám se, že už to trošku přesahuje mé pochopení, v čem je problém a zda je to na straně mého počítače/sítě, nebo aplikace jako takové:
https://pretagteam.com/question/crbug1173575-nonjs-module-files-deprecated-in-angular
https://stackoverflow.com/questions/67191286/crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%EA%9E%89530595551
https://support.google.com/chrome/thread/122907066/crbug-1173575-non-js-module-files-deprecated?hl=en
https://programmerah.com/solved-vs-code-debug-javascript-error-crbug-1173575-non-js-module-files-deprecated-34400/

**Comment by jnihnat** [comment]
ja som podobne hladal riesenia vcera a prave ma to viedlo k problemom s certifikatmi a pod v browseru.
Skusim este nahradit jquery najnovsou verziou, mozno to pomoze, ale nasadenie bude musiet pockat na @pesikj 
viete skusit otvorit tuto stranku ci sa vam to bude stavat aj na nej:?
https://code.jquery.com/jquery-3.6.0.js

**Comment by motyc** [comment]
Dělá to totéž i s novým odkazem (https://code.jquery.com/jquery-3.6.0.js) :(

**Comment by jnihnat** [comment]
Deje se vam to prosim jen na jednom PC, pripadne len z jedneho pripojenia (doma?)

**Comment by motyc** [comment]
Momentálně se mi to děje na jednom PC (zkoušeno ještě na dalších dvou na stejné síti a tam to jde dobře). Nehraje ani roli to, zda jsem nebo nejsem připojen na VPN.

Pokud si ale dobře vzpomínám, tak poprvé jsem stejný problém registroval na notebooku na úplně jiné síti...

**Comment by jnihnat** [comment]
jeste jeden dotaz, deje se to i v privatnim okne?

**Comment by motyc** [comment]
Ano, žádný rozdíl.

**Comment by jnihnat** [comment]
mohli by sme si k tomu zajtra zavolat? Uz mi dochadzaju napady a u mna sa mi to nijak nedari nasimulovat.

**Comment by motyc** [comment]
Určitě mohli (+420775200064). Je mi jasné, že je to trošku nešťastná věc a může to být opravdu nějaká specifická hloupost na mém PC. Když se to nepodaří vyřešit, tak holt budu testovat z práce a počkáme, jestli se to třeba s nějakým updatem Windows nevyřeší. Děkuji moc.

**Comment by jnihnat** [comment]
Napadlo mi skusit jeste jednu vec, muzete se skusit pripojit cez mobilni hotspot? Ci to nahodou nedela router/internetovy provider?
Pripadne bych si pak skusil zavolat kolen 11:00 ak  Vam to vyhovuje.

**Comment by motyc** [comment]
To bohužel nemůžu, protože tam se nepřipojím na VPN. Ale routerem by to být nemělo, vzhledem k tomu, že na stejné síti na notebooku to funguje. Jedenáctá je bez problémů.

**Comment by motyc** [comment]
Mám dojem, že jsem našel celkem přesný popis problému zde: https://issueexplorer.com/issue/jquery/codeorigin.jquery.com/77

Skutečně se nedostanu ani na https://code.jquery.com/ jako takovou.

Když přidám do `c:\Windows\System32\Drivers\etc\hosts` konkrétní mapování `69.16.175.42 code.jquery.com` (což tam navrhují jako dočasné řešení), tak to najednou vše funguje. Kdyby Vás napadlo, co mám udělat pro to, aby to fungovalo trvale, budu rád. Já už tady běžím po hodně tenkém ledě vlastních znalostí.

**Comment by jnihnat** [comment]
Pokial tohle resi problem, tak to potom spise vypada na problem s DNS serverom. Ten pokial nemate nastaveny v pocitaci rucne, tak zavysi od nastavenia poskytovatela internetu. A to je uz potom divne, preco to z PC nefunguje ale z notebooku ano na jednej sieti.
Inak by som sa asi pripojil k tomu premiestnit to js do statickych souboru na server a to vyresi problem.

**Comment by motyc** [comment]
DNS mám dynamicky přidělované, takže je to opravdu zvláštní, jak říkáte.

Jinak souhlasím, proberte to tedy prosím s kolegou Pešíkem a pokud tam nebude nějaký háček, šel bych touto cestou. Nechávám to tedy otevřené, jen změním název issue.

**Comment by motyc** [comment]
Dodávám další informace:
- když si na daném počítači nastavím na pevno hosts file (doplněno: `69.16.175.42	code.jquery.com` a `69.16.175.42	releases.jquery.com`) funguje to pouze při připojení na přímo přes ip serveru
- když se připojuji přes https://wamcr-test.aiscr.cz/, nedaří se mi připojit

Stále platí, že na jiném počítači v téže síti to jede. Zároveň ale platí, že na daném počítači to nejde v žádném prohlížeči. Vypnutí ESET či Windows firewall nepomůže, zkoušel jsem https://support.pearson.com/getsupport/s/article/Reset-an-Internet-Connection-Flush-DNS a zkoušel jsem resetovat nastavení sítě přes Windows.

@MichalKminek @vojtakus nenapadne ještě něco vás, prosím? Zejména ve vztahu k tomu, že přes https://wamcr-test.aiscr.cz/ to nejede a na přímo ano (při tom editovaném hostu, jinak to nejede vůbec).

**Comment by MichalKminek** [comment]
Zaznam hosts nastavujes na Win nebo Linuxu? Rozliseni muzes vyzkouset prikazem ping. Mas nastevnou proxy? Mozna bude lepsi po telefonu, kdy by se ti to hodilo?

**Comment by motyc** [comment]
@MichalKminek Je to na Win 10. Mám teď schůzku, ale po ní zavolám...

**Comment by pesikj** [comment]
Implementováno na DEV serveru, problém byl měl být odstraněn, ale je potřeba test od @motyc, který má prostředí, kde může problém nasimulovat.

**Comment by motyc** [comment]
@pesikj Ve skutečnosti to už ani já spolehlivě neotestuji, protože se mi patrně podařilo na PC problém odstranit trvaleji. Určitě je ale dobře, že se to udělalo, protože na to lidé v různých kontextech narážejí stále. Pokud tedy vše funguje i po převodu na static, můžeme to brát za vyřešené.
