### ISSUE TITLE
Rozdílné chování aplikace u komponent a nálezů při povinných položkách

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2471]
- Při vytváření nové komponenty, pokud nevyberu Období nebo Areál, tak jen vyskočí okno "Zvolte prosím některou položku v seznamu".
- Pokud toto udělám u nálezů, tedy nevyberu buď Druh (u objektů) nebo Předmět nebo Specifikaci (u předmětů), tak proběhne zpracování a teprve poté vyskočí chybová hláška "Záznam se nepodařilo upravit", pole zčervená a objeví se "Toto pole je vyžadováno"

Bylo by možné to sjednotit? Pokud na povinnou položku uživatel zapomene, nebo ji přehlédne u nálezů, tak musí čekat, než proběhne operace, místo aby mu jen vyskočilo upozornění jako u komponenty a rovnou provedl opravu.

Také když přidám jen Specifikaci u předmětu, tak po chybové hlášce a vybrání druhu specifikace zmizí. Obráceně se to ale neděje, takže když uživatel uvidí že se uklikl nebo zapomněl druh vyplnit, pak ho vyplní, tak se nemusí všimnout, že specifikace zmizela a absolvuje ještě jeden cyklus s chybovou hláškou.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
- [ ] Je to téměř dobré, jen je trošku odlišné chování pro sloupec Druh a Specifikace. Pro druh se pouze zvýrazní pole, ale nevyskočí žádná hláška, pro specifikaci se objeví i hláška. Bylo by dobré, aby se to chovalo u obou jako u specifikace:

![image](https://github.com/user-attachments/assets/0c03e256-cce6-4416-a772-c2c1a98ebbf6)
![image](https://github.com/user-attachments/assets/bf7dcc69-8d8e-43cc-b40d-63c6cd19206a)

**Comment by jhavrlant** [comment]
Mě se většinou zobrazí. Problém je, že ten dialog vytváří přímo prohlížeč a mi na něj nemáme žádné páky.
![Image](https://github.com/user-attachments/assets/5235ca8f-2b39-4d62-bab0-33fa30a672e3)

**Comment by motyc** [comment]
Ok, tak to nechme a mrknu na to ještě časem. Teď jsem to zkoušel v Mozille a tam mi to jede ok. Zjevně to tedy může být i nějaké specifické nastavení či chování prohlížeče.
