### ISSUE TITLE
Navýšit max. velikost nahrávaných souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2493]
Navýšit limit pro nahrávání souborů ze 100 MB na 250 MB na jeden soubor.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
Zjevně bude potřeba upravit ještě nějaký další parametr v rámci prostředí, protože test server hlásí:
`Soubor CTX201404706B.pdf se nepodařilo nahrát. <html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.26.1</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

Tuším, že to bude spíše na @jhavrlant nebo @vojtakus

**Comment by jhavrlant** [comment]
Opravím to v proxy nginx

**Comment by motyc** [comment]
@jhavrlant Omlouvám se, ale ještě mi došla potřeba jedné úpravy, aby se nemohlo stát, že nám někdo zavalí systém nesmysly - u nahrávání projektové dokumentace je třeba omezit maximální počet souborů třeba na 40. Tím se zajistí, že nám nikdo nenahraje více než 10 GB v jednom zátahu, zároveň pokud bude potřebovat nahrát hodně malých souborů, stačí je zazipovat.

**Comment by motyc** [comment]
### Test v1.0.13-rc8
