### ISSUE TITLE
Automatické odhlášení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#251]
- [x] při nečinnosti více než 60 min
- [x] je potřeba upozornit uživatele po odhlášení, že byl odhlášen kvůli nečinnosti
- [x] pokud možno zobrazit counter
- [x] 10 min před uplynutím odhlášení se dotázat, zda prodloužit

**Comment by jnihnat** [comment]
60 minnut pro odhlaseni a 10 minut pro warning je nastavitelne v settings

**Comment by motyc** [comment]
Funkční to je, avšak je třeba lépe vyřešit informaci 10 min před vypršením, protože takto uživatel snadno přehlédne, že brzy bude odhlášen (zvláště když nemá aktuálně otevřený dotčený tab prohlížeče). Udělat asi přes `Window.prompt()`.

**Comment by jnihnat** [comment]
@motyc navrhl bych spis confirm ako prompt(ten vyzaduje input od usera). Priklad si muzete skusit tu:
https://jsfiddle.net/xj1w68zn/
Jak je tych 100, tak to je timeout po kterem se zobrazi confirm okno. Je to v milisekundach, takze ak date 3000, potom hore Run, pak kliknete v pravo dole na Try a prekliknete se na dalsi tab, tak uvidite jak to zafunguje.

**Comment by motyc** [comment]
@jnihnat Zkouším to v Chrome a tam mi to tedy nic neudělá, pokud nemám tab právě aktivní. V principu tedy souhlas, jen ta ukázka mi nějak nešlape.

**Comment by motyc** [comment]
@jnihnat Jen se chci ujistit - ta deprecation pro Chrome se týká jen užití v iframes - je to skutečně náš případ? Alert používáme např. i v digitálním archivu a tam funguje bez problémů.

**Comment by jnihnat** [comment]
@motyc jo ta deprecation by se mnela tykat dokonce jen cross-origin iframes. Ospravedlnujem sa za zmatky.
Jinak co som vcera skusal tak na chrome mam jeden problem, ze ten alert se mi nechce spustit pokud nejsem na tom tabe v tom momente, nezobrazi se ani po prekliknuti spatky na neho...
Preto by som navrhoval ostat pri systeme aktualnych notifikacii. Viem upravit jeden riadok a ta notifikacia sa nebude schovavat a teda ostane vzdy nahore pokial ju uzivatel nezatvori/nekline na nu pre reload.
Tiez sa da pridat parameter pre "zasednutie stranky"
![image](https://user-images.githubusercontent.com/57906106/173602745-288e1292-e14a-4afa-8c2e-da1bf9719075.png)

**Comment by jnihnat** [comment]
tak este jedno zistenie. Alert funguje, ale confirm a prompt nie:
https://chromestatus.com/feature/5140698722467840
Takze teoreticky to mozme prerobit aj na ten alert, tam je akurat "problem" v tom ze akokolvek user zatvori alert (napr. aj pomoci ESC klavesy) tak by sme robili obnovenie session. neda sa totiz zachytavat samostatne click na OK.

**Comment by motyc** [comment]
@jnihnat To by nemělo vadit. Jde nám o to podchytit situace, kdy uživatel zjevně odešel od počítače. Pokud tedy výstrahu nějak "aktivně" zavře, lze to chápat jako obnovení. Toto lze řešit i textem oznámení ("Brzy budete automaticky odhlášeni z důvodu neaktivity. Potvrzením či zavřením této výstrahy dojde k obnovení času do odhlášení.").

Zde se jen zeptám - předpokládám, že pokud čas uplyne a výstrahu nikdo neodklikne, tak se session následným odkliknutím již neobnoví, že ano?

**Comment by jnihnat** [comment]
tak som to este otestoval a nakoniec musim zavrhnut aj riesenie s alertom.
Ak sa spusti, tak sa neobnovuje nijak okno, co znmena 2 veci:
- odpocitavanie do odhlasenia zostane na obrazovke stat bez zmeny i ked v pozadi odpocitavanie pokracuje.
- ak sa alert nezatvori do 10 minut (nastavenie kedy sa ma zobrazit) tak to uzivatele neodhlasi, lebo alert to blokuje. Az uzivatel klikne na zavreni alertu, tak az vtedy ho to odhlasi.
co by som vedel spravit a za mna by to vyzeralo aj lepsie:

https://user-images.githubusercontent.com/57906106/173871987-3a14e12d-6403-4b8c-91e8-c94f14a51654.mp4

**Comment by jnihnat** [comment]
to preblikavanie title funguje aj ked ste na inej karte. Je to len pracovna verzia pre ukazku, takze to ze title ostal potom prazdny prosim neberte ako chybu.

**Comment by motyc** [comment]
@jnihnat To vypadá dobře, takto souhlasím a děkuji.

**Comment by jnihnat** [comment]
je tam nastaveno:
- session trva 60 minut
- blikani + message o odhlaseni zacne 10:00 pred koncem
Este som to skusil u seba na Chrome i Mozille a u mne vse v poradku.

**Comment by jnihnat** [comment]
jeste k:
"Při testu jsem si nechal jedno otevřené okno a podíval se na něj, když bylo cca 6 min. do odhlášení"
Muzete se prosim kouknout do konzole, ci se tam neco neobjevi?

**Comment by motyc** [comment]
@jnihnat A má to blikání atd. někdy i skončit, nebo jede až do nuly?

Zapnul jsem konzoli a musím počkat, než uběhne timer... Pak dám vědět.

**Comment by jnihnat** [comment]
ma to jit do odhlaseni, pripadne pri prolongaci session se to taky zrusi to blikani.
Pokud to nebude fungovat, a v konzoli nic nebude, tak mne napada jeste jedna vec co by tomu mohla pomoct.
jinak na ktere strance jste byli kdyz to nefungovalo? Skusim u sebe nastavit kratsi time a retestovat to na ty strance.

**Comment by motyc** [comment]
@jnihnat To vám už nedokážu říci.

Napadá mě, že může být problém též v tom, že mám zároveň otevřeno více tabů AMČR, kde se session obnovuje. To bude typický usecase:
- mám otevřené jedno okno a otevřu si druhé, kde dělám třeba s jiným záznamem
- v prvním okně ubíhá čas a neresetuje se
- stále dělám ve druhém okně
- v prvním okně doběhne na 10 min (teď bych čekal upozornění - nestalo se nic)
- stále dělám ve druhém okně
- v prvním okně čas doběhne a session je ukončena
- ve druhém okně to zjistím ve chvíli, kdy chci něco udělat a aplikace místo toho skočí na login page

To byl mimochodem hlavní důvod, proč potřebujeme to upozornění blikáním. Varianta by samozřejmě byla i to, že se použije ta "čerstvá" session z aktivního okna a to první okno session neukončí, dokud pracuji jinde. Možná zkuste prověřit tento postup, zda to nesouvisí...

**Comment by pesikj** [comment]
@motyc Ano, mám taky zkušenost, že pokud má člověk otevřeno více záložek a na jedné záložce není aktivní, tak je pak odhlášen. Přihlášení je totiž jednotné a společné pro všechny záložky v prohlížeči.

**Comment by motyc** [comment]
@jnihnat Tak otestováno znovu, tentokrát pouze s jedním oknem AMČR:
- když mám okno otevřené, funguje to skvěle
- když otevřu jiný tab, bliká to také, ale s velkými pauzami, tak nějak přerušovaně
- mám dojem, že původní chyba opravdu souvisí s tím, když mám otevřených více tabů s AMČR
- konzole nic nehlásí

**Comment by motyc** [comment]
@jnihnat Nejde mi o to obejít chování více tabů, je za mne v pohodě, jen mi při těch víc tabech prostě nefungovalo to upozornění, proto jsem to popisoval (ne kvůli požadavku na změnu, rozumím, že by to byla komplikace). Ale asi to bylo něčím jiným, jak píšete.

Dolaďte tedy asi ty poslední Vámi jmenované dva body a bude to.
