### ISSUE TITLE
Odstávka systému

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#252]
Vhodným způsobem vyřešit možnost odstávky systému
- [x] systém neumožní přihlášení a zobrazí adminem nastavené zdůvodnění
- [x] systém nebude přijímat oznámení projektů a bude zobrazovat upozornění se zdůvodněním
- [x] systém musí upozornit přihlášené uživatele na blížící se odstávku a po určité době musí dojít k jejich odhlášení

**Comment by motyc** [comment]
> Jiří Pešík
> 6. ledna 2022 14:29
> 
> Ideální by bylo evidovat tabulku s odstávkami a tu využít.

**Comment by jnihnat** [comment]
@motyc posilam predbezne reseni:
- pro prihlasovace stranky udelana stranka:
![image](https://user-images.githubusercontent.com/57906106/190955359-aa0295b2-a117-4e3c-a946-09e0bd233742.png)
- pro stranky oznameni udelana stranka:
![image](https://user-images.githubusercontent.com/57906106/190955451-e82fe534-c456-4b31-bf84-d60945cc22b6.png)
- stranky muzou byt CZ a EN, pokud reknete, uzivately se pak zobrazi podle nastaveni browseru. Zatim mam len CZ, napiste pokud chcete reseni podle nastaveni browseru prosim.
- stranky musi byt taky hard coded, teda text se neda menit nikde v django aplikaci, je to mozne dodelat, ale zabere to jeste o neco vice casu a ohybani, takze pokud to postaci nastavit jednou a nebude se to menit pri kazde odstavce, tak bych to nedelal.
- pro oznameni pro prihlasene dodelana lista:
![image](https://user-images.githubusercontent.com/57906106/190956396-91b77e6f-7e7d-46b7-a6c1-d917d7e2bd40.png)
- oznameni i s textem nastavitelne cez admin panel.
- Napiste prosim sve pripominky, aby som to pripadne este hned upravil.

**Comment by motyc** [comment]
@jnihnat Děkuji za návrh. Celkové řešení je pěkné.
- Ano, prosím aby se počítalo s CS/EN verzí, stejně jako to budeme mít v celém systému.
- Text o odstávce, nebo alespoň jeho část bychom měnit potřebovali (viz `zobrazí adminem nastavené zdůvodnění`), protože potřebujeme informovat uživatele i o tom, kdy může očekávat, že odstávka skončí, případně o jejích důvodech; obojí bude samozřejmě pokaždé jiné. Ideální by bylo nastavení přes Rosettu, jako u jiných textů... Jako nouzová varianta mně napadá, že by mohl být zobrazen odkaz na bližší informace o odstávce na nějakou pevnou adresu (např. https://amcr-info.aiscr.cz/odstavky), kde bychom měli statickou stránku, kterou bychom si upravovali podle potřeby. To by vlastně asi také nebyl problém, pokud je to jinak implementačně moc náročné (tento odkaz bych pak dal jak na ty statické stránky tak do té lišty v aplikaci).
- Tu lištu s oznámením bych dal nějakou červenou nebo něco takového, aby to víc vypadalo jako výstraha + třeba doplnil ikonu s vykřičníkem (něco jako https://myloview.cz/obraz-alert-icon-exclamation-mark-in-triangle-attention-danger-and-c-EEEFEF3).
- Ad odhlášení po určité době - Jde o to, že nechceme systém vypínat ve stavu, kdy jsou přihlášení uživatelé a něco dělají, protože to zásadně zvyšuje riziko poškození dat v DB; cílem je to řešit tak, aby ve chvíli vypnutí serveru byla víceméně jistota, že již nikdo není přihlášený, protože byla zapnuta plánovaná odstávka, uživatele systém postupně odpojí více řízeně a až pak vypneme server.

**Comment by jnihnat** [comment]
@motyc 
- jeste k poslednimu bodu, chapu kam tim mirime, umim to udelat pres ten proces co mame pro autologout, ze v pripade ak user udela volani na server hodinu pred odstavkou (podle max delky necinnosti) tak sprocesujeme request, zobrazime hlasku podle toho co udelal + hlasku o odhlaseni za 5 sekund a pak ho odhlasime. Je pak ale potrebne taky zakazat prihlaseni a zobrazit nejakou lasku tam, nejspis by to pak vypadalo stejne jako pro ten error co je nahore. Pokud s tim takto souhlasite skusim to udelat.

**Comment by motyc** [comment]
@jnihnat Ano, to zablokování přihlášení nových by tam mělo být - to máme hned v prvním bodu požadavků (`systém neumožní přihlášení a zobrazí adminem nastavené zdůvodnění`). Jinak navržené řešení je super, jen bych mu dal třeba 30 sekund, ať se stihne rozkoukat...

**Comment by jnihnat** [comment]
@motyc 
- hruby popis nastaveni je na wiki pod: https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Administrace
- kdyby tam neco chybelo nebylo jasne, prosim napiste a doplnim info
@pesikj 
- az budes nasazovat, prosim pouzi novy deploy script deploy_proxy.sh (upravil som aj na wiki v nasazovani)

**Comment by motyc** [comment]
### Výsledek testování
- [ ] Když v http://192.168.254.30:8080/admin/core/odstavkasystemu/1/change/ změním obsah pole `Model.odstavka.textcz`, tak se nastavení zjevně propíše do `base.odstavka.text` v Rosettě, ale bohužel se to neprojeví v aplikaci. To se stane až ve chvíli, kdy to případně uložím znovu přes Rosettu.
- [ ] Chápu to dobře, že odstávka může být přidána jen v případě, že jiná odstávka není zrovna zapnutá? To je asi ok, ale jsou nějak vyřešeny případné kolize, tj. např. když se zároveň aktivují dvě apod. - co se v takovou chvíli bude dít?
- [ ] Abych to mohl otestovat, potřeboval bych mít jasno v tom, kde a kdy se zobrazují:
-- `Model.odstavka.textcz/En`
-- `core.forms.odstavkaSystemu.errorTextCs/En`
-- `core.forms.odstavkaSystemu.errorTextOznamCs/En`
(pokud by se to v souvislosti s předchozím bodem nějak upravovalo, tak potřebuji info podle skutečné situace)
- [ ] http://192.168.254.30:8080/accounts/login/ - pokud odstávka běží (tj. nelze se zalogovat), chtělo by to zobrazovat obsah `core.forms.odstavkaSystemu.errorTextCs`; nyní se ukazuje `base.odstavka.prohibitLogin.Text`
- [ ] http://192.168.254.30:8080/oznameni/ je přístupné i při běžící odstávce
- [ ] Je třeba revidovat časové limity:
-- čas do automatického odhlášení při běžící odstávce je nyní 30 s, nastavit na 10 min
-- `base_odstavka_logoutWarning_text` zobrazovat ve shodě s předchozím (10 min před odhlášením; dojde tak i ke včasnému rozblikání tabu, což je super)
- [ ]  Jaká uživatelská oprávnění musím mít, abych mohl odstávky spravovat? Musím být globální admin? Pokud ano, bylo by vhodnější vydělit to pod samostatné oprávnění, protože globálního admina nechceme moc nikomu dávat.
- [ ] Za `model.odstavka.modelTitle` se v zobrazení v administraci automaticky přidává "s"
![image](https://user-images.githubusercontent.com/20186892/203541309-82092812-d2e9-4dc0-9a7a-ea1f889b42c2.png)

**Comment by jnihnat** [comment]
oprava pak pripravena v #750 
co se tyce dotazu:
1. opraveno malo by stacit ulozit jednou
2. upraveno, je mozne pridavat vice najednou ale pridal som validaci jen na jednu Odstavku se stavom "True"
3. vyskyty:
- Model.odstavka.textcz/En - prejmenovano na base.odstavka.textEN.label aby spravne referovalo na base.odstavka.text
- core.forms.odstavkaSystemu.errorTextCs/En - pokud je aktivna odstavka na login strance
- core.forms.odstavkaSystemu.errorTextOznamCs/En - pokud je aktivni odstavka na oznameni strance
4. opraveno - prohibit login se zobrazuje uz jen hodinu pred odstavkou
5. opraveno
6. opraveno
7. k celemu admin panelu maji pristup jen super useri podle Djanga
8. opraveno

Mam jeste jeden bod co muzu upravit, v puvodnim modelu jsem mal ona text_en a text_cs ktore se zobrazuji v administraci pod  base.odstavka.textEN/CS.label - nevim ci maji zmysel ako samostatne polia v modelu, nebo je nemit jen jako pole formularu, ktere se nikde neulozi jen upravi preklady. Muzu pak napriklad pridat "nazev odstavky". Tu bych poprosil Vasi pomoc co Vam dava zmysel. dekuji

**Comment by jnihnat** [comment]
@motyc este mne napadla jedna vec, pokud do 10 minut uzivatel refreshne stranku, nebo odesle formular, presune se, tak cas do odhlaseni se zase nastavi na 10 minut. Je to takto ok, nebo chceme aby se zobrazil uz jen zbyvajici cas z puvodnich 10 minut?

**Comment by motyc** [comment]
@jnihnat
ad 7 - prosím, řešme to tedy tou skupinou v http://192.168.254.30:8080/admin/auth/group/, protože superadmin opravdu bude max 1-2 lidé; @pesikj bude vědět, jak to myslím; skupina by byla např. "Správa odstávek" a pokud v ní uživatel je, může s tím pracovat v administraci; pokud je to velká práce navíc, dejte mi vědět a dohodneme se, jak s tím naložit

> Mam jeste jeden bod co muzu upravit, v puvodnim modelu jsem mal ona text_en a text_cs ktore se zobrazuji v administraci pod base.odstavka.textEN/CS.label - nevim ci maji zmysel ako samostatne polia v modelu, nebo je nemit jen jako pole formularu, ktere se nikde neulozi jen upravi preklady. Muzu pak napriklad pridat "nazev odstavky". Tu bych poprosil Vasi pomoc co Vam dava zmysel. dekuji

Musím se přiznat, že tomu popisu vůbec nerozumím - co je současný stav a chování? A co navrhujete změnit a jak by se to chovalo? Pardon, ale trošku se v tom textu ztrácím...

> Je to takto ok, nebo chceme aby se zobrazil uz jen zbyvajici cas z puvodnich 10 minut?

Čas už by se neměl resetovat, protože jinak by tam uživatel průběžným klikáním mohl zůstat donekonečna :)

**Comment by jnihnat** [comment]
K tomu druhemu bodu:
Soucasny stav je:
- mame db sloupce ktere nejsou nikde vyuzity - odmazu je z db, ostanou jen ve formulari pro nastavovani textace.
- chyby pole na nastaveni prohibitLogin.text text ktery se zobrazuje na login page ak bezi 60 minut pred odstavkou. - pridam pole i na formular
- chyby nazov odstavky - to bych pridal ak souhlasite at mame nejake slovne odliseni odstavek. Nebo neni potreba?

**Comment by motyc** [comment]
Děkuji za popis. Ten název myslím není potřeba, stačí že víme, kdy odstávka bude. Zas tak často se to neděje. Jinak ok.

**Comment by motyc** [comment]
@jnihnat Nemohu testovat, protože ani jako superuser teď položku odstávek v admin menu nevidím a skupina také vytvořená není, byť vidím související příkaz v migracích.

**Comment by pesikj** [comment]
@motyc Migraci jsem spustil, takže skupinu už byste měl vidět.

**Comment by motyc** [comment]
@pesikj Skupinu sice vidím, ale teď mi ze správy uživatelů úplně zmizela možnost skupinu přidělit uživateli. Naopak tam zůstala část "Uživatelská oprávnění:", která tam být nemá. Skupinu tedy nemám jak přidělit.

**Comment by sedmar** [comment]
@motyc Pretrvava nemožnost přidělit skupinu uživateli? Pokud ano, mělo by to být přesunuto na do jiného projektu, abychom na tom mohli začít pracovat případně dořešit proč tomu tak stále jest.

**Comment by motyc** [comment]
@sedmar Už to tam je, otestuji a potvrdím.

**Comment by motyc** [comment]
@sedmar Tak ovládací prvek tam nyní už je, ale stále to nejde testovat. Problém je ale u jiného issue, jmenovitě viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/384#issuecomment-1337777612 (první bod) - nejde přidávat do skupin. Toto issue bych tedy nikam neposouval, jen je třeba nasadit opravu pro to #384.

**Comment by motyc** [comment]
### Výsledky testu
- [ ] při snaze přidat odstávku (http://192.168.254.30:8080/admin/core/odstavkasystemu/add/) dostanu error 500
- [ ] http://192.168.254.30:8080/admin/core/odstavkasystemu/1/change/ - zobrazované texty neodpovídají zadaným textům (zobrazují se výchozí texty na všech třech místech)
- [ ] kontrolu nelze plně provést, protože ani s oprávněním na úpravu textů se nyní do Rosetty nejde dostat (chybí v admin menu)
- [ ] když upravím texty v http://192.168.254.30:8080/admin/core/odstavkasystemu/2/change/, automaticky se změny propíšou do http://192.168.254.30:8080/admin/core/odstavkasystemu/1/change/ - pokud to tak bude, nemá vůbec smysl, aby šlo zadat více odstávek a pracoval bych vždy pouze s jednou položkou, kterou lze jen aktivovat/deaktivovat a nastavit její parametry

Další testy jsou blokovány předchozími body.

**Comment by pesikj** [comment]
@motyc
> při snaze přidat odstávku (http://192.168.254.30:8080/admin/core/odstavkasystemu/add/) dostanu error 500

Je to skutečně error 500, nebo error 403?

**Comment by jnihnat** [comment]
@motyc k bodum:
>     * [ ]  kontrolu nelze plně provést, protože ani s oprávněním na úpravu textů se nyní do Rosetty nejde dostat (chybí v admin menu); EDIT: beru zpět - chyba je jen v tom, že Rosetta není vidět v menší verzi menu, když jsem např. v http://192.168.254.30:8080/admin/core/odstavkasystemu/; v zobrazení http://192.168.254.30:8080/admin/ položka vidět je
- je tohle veliky problem? chapu, ze to neni optimalni, ale pouzivame k tem prekladum rozsireni. Pokud bych se v tom menl hrabat a hledat kde to chyby, zabere to vic casu.

>     * [ ]  když upravím texty v http://192.168.254.30:8080/admin/core/odstavkasystemu/2/change/, automaticky se změny propíšou do http://192.168.254.30:8080/admin/core/odstavkasystemu/1/change/ - pokud to tak bude, nemá vůbec smysl, aby šlo zadat více odstávek a pracoval bych vždy pouze s jednou položkou, kterou lze jen aktivovat/deaktivovat a nastavit její parametry
- muzu nastavit ze je povolena jen jedna odstavka. to neni problem. Druha moznost je mit vsechny pole v DB pro nejakou zpetnou kontrolu. Pokud to ale neni potreba min prace pro mne.

**Comment by motyc** [comment]
@jnihnat
- Rosetta v menu - Není to velký problém, ale je to matoucí. Nesouvisí to ale s tímto issue přímo a můžeme to dát bokem do oprav.
- jedna/více - udělejte to na tu jednu; je fakt zbytečné to komplikovat

**Comment by jnihnat** [comment]
opraveno/upraveno - rosettu necham na pozdeji. pridavat odstavku je mozne jen pokud neexistuje zadna jina akce. z DB jsem tedka nic neodmazaval, at vam neco neodstranim, ale odstranit to klidne muzete sam cez admina.
