### ISSUE TITLE
Odkazy na Digiarchiv a do API

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#253]
Každý archivovaný záznam by měl v záhlaví v menu "Další volby" obsahovat:
- [x] proklik do Digitálního archivu na URL https://digiarchiv.aiscr.cz/id/[ident_cely] (např. https://digiarchiv.aiscr.cz/id/M-TX-202100002)
- [x] proklik na jeho detail do OAI API na URL https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/[ident_cely]&metadataPrefix=oai_amcr; (např. https://api.aiscr.cz/dapro/oai?verb=GetRecord&identifier=https://api.aiscr.cz/id/M-TX-202100002&metadataPrefix=oai_amcr)

**Comment by jnihnat** [comment]
doplnene do:
- Akce
- dokumenty
- 3D dokumenty
- samostatny nalez
- projekt
