### ISSUE TITLE
Možnost editace neschválených oznámení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#256]
Editace je myšlena pro uživatele, který oznámení zapisuje (nyní zapíše první krok, jde na druhý, vidí chybu, ale už ji nemůže opravit).

**Comment by pesikj** [comment]
@motyc Předpokládám, že administrátor může editovat cokoli.

**Comment by motyc** [comment]
@pesikj Ano, ale to není v tomto případě úplně relevantní. Tady jde o funkci pro nepřihlášeného uživatele spojenou s http://192.168.254.30:8080/oznameni/ - přejdu na formulář -> vyplním ho -> jdu na další krok (nahrání dokumentace) -> vidím v údajích chybu a chci ji opravit (nyní již nemůžu)

Admin se k projektu pak dostane po přihlášení, to funguje již nyní.

**Comment by pesikj** [comment]
@motyc Znamená to tedy, že je potřeba umožnit uživateli návrat zpět do prvního kroku s tím, že ve formuláři budou data, která vyplnil?

**Comment by motyc** [comment]
@pesikj Pokud je to možné, klidně to lze udělat takto.

**Comment by motyc** [comment]
### Výsledek testování
- [ ] Když kliknu na "Upravit oznameni", nezobrazí se v mapě již zadaný bod (katastr je však vyplněn dobře).
- [ ] Zadáním URL http://192.168.254.30:8080/oznameni/?ident_cely=[libovolný ident_cely projektu] mohu editovat jakýkoli projekt; funkce by měla umožnit editovat právě a jen aktuálně rozpracované oznámení danému uživateli do doby jeho odeslání, ne se volně dostávat k projektům a editovat je bez autorizace

**Comment by sedmar** [comment]
Bude opraveno.

**Comment by jnihnat** [comment]
@jiri-bartos-huld - prosim pozri sa na prvy bod:
-  Když kliknu na "Upravit oznameni", nezobrazí se v mapě již zadaný bod (katastr je však vyplněn dobře).
vo formulari je latitude a longitude, len to uz dotiahnut do mapy pri loade ak tam su. Verim ze ty to budes mat spravene za kratsie akoby som to mal ja hladat v kode kde to uz mas niekde naimplementovane.
Vdaka

**Comment by jiri-bartos-huld** [comment]
@jnihnat opraveno poslano na MR

**Comment by motyc** [comment]
### Výsledek testu
Původní problémy ok, jen drobnost pro jistotu:
1. vyplním formulář http://192.168.254.30:8080/oznameni/
2. přejdu na krok 2
3. vrátím se na krok 1 a zkopíruji si adresu (např. http://192.168.254.30:8080/oznameni/?ident_cely=X-C-001276769)
4. dokončím oznámení a odešlu jej
5. zkopírovanou adresu (např. http://192.168.254.30:8080/oznameni/?ident_cely=X-C-001276769) zkusím znovu otevřít
6. místo error 403, který dostanu běžně, dostanu error 500; patrně zůstalo rozpracované oznámení v cookie/session, a proto se to chová jinak - hlásím to proto, aby tam nemohla vzniknout nějaká chyba v DB, i když je to nepravděpodobné

**Comment by jnihnat** [comment]
opraveno.
