### ISSUE TITLE
Možnost odhlášení projektu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#257]
Archeolog z organizace, která přihlásila projekt, musí mít u projektu v P2 možnost požádat o odhlášení projektu:
- Je nutné zadat zdůvodnění.
- Odesílá email E-P-07 (do DB se neukládá)

**Comment by motyc** [comment]
> David Novák 
> 6. ledna 2022 14:57
> Odložit po implementaci automatických emailů
> 
> Jan Ihnat 
> 21. prosince 2021 16:07
> Uz chapu. Jde teda o zqadost o odhlaseni, kde po zadani duvodu se odosle mail.
> Chceme tuhle akci zapsat do historie?
> Dane nove tlacitko by bylo pak pod Dalsima volbama?
> Tu bych rovno dodelal Emailovy modul, na spravu sablon z komentare nize, samotne odesilani emailu a pripadnu dalsi parametrizaci ak bude nutna.
> 
> David Novák 
> 19. prosince 2021 12:39
> 
> Ano, znamená. Bohužel ale existující tlačítko nestačí, protože slouží archivářům a tento úkon rovnou udělá. Ze strany uživatele archeologa nejde přistoupit na to, že by stavy vracel libovolně, protože to souvisí i s některými administrativními kroky ve vztahu k ARÚ. Jde tedy o odlišnou funkci (resp. po vyhodnocení situace právě toto tlačítko archivář použije, aby projekt odhlásil).
> Text emailu je definován zde (E-P-07): [emaily_texty](https://docs.google.com/document/d/16ByqpA4RaB96F5YwT5no9313LRJknlbo7lwGo0YqZcM/edit)
> 
> Jan Ihnat 
> 12. prosince 2021 19:53
> Odhlaseni znanema vraceni z P2 do P1? Pokud ano, staci nechat tlacitko “Vratit”anebo ho prejmenovat na Odhlaseni? 
> Je potreba definovat dany email, pripadne kde najdu definici?

**Comment by jnihnat** [comment]
prosim otestovat aj zadost o udaje oznamovately - staci zobrazeni formulare.

**Comment by motyc** [comment]
Pro mě - nezapomenout na URLs

**Comment by motyc** [comment]
### Test v1.0.13-rc1
Ještě prosím o drobnou úpravu, aby odesílatelem mailu byl podobně jako u žádosti o os. údaje ten uživatel, který žádost odeslal.

Jinak je to bez problémů.
