### ISSUE TITLE
Chyba přihlášení do administrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#2578]
Při nasazování verze v1.0.13 na trénink jsme zjistili, že přestalo fungovat přihlášení do administrace přes stránku https://amcr-test.aiscr.cz/admin/ - login stránka se vůbec nezobrazí a rovnou se ukáže jakoby prázdná administrace. Je to celkem zásadní problém, protože kvůli tomu nejde vypínat a zapínat odstávky systému jinak než přes úpravu DB. Danou verzi tak nelze dát na produkci.

Může to souviset s úpravami v #2458

**Comment by jhavrlant** [comment]
Problém způsobila tato řádka: @method_decorator(user_passes_test(lambda u: u.is_superuser)) v webclient\fedora_management\admin.py. Raději bych aby to opravil Jirka, ale jestli nebuje mít čas, tak to zítra udělám.

**Comment by pesikj** [comment]
Je to tak, ještě otestuji, aby tam pak neměl přístup nikdo další. Ale post requesty jsou ošetřené samostatně a šablona taky.

**Comment by motyc** [comment]
Díky oběma. Nastavím tedy odstávku na zítřek večer a nasadili bychom opravu na TR a novou verzi na PROD. Udělám teď merge, připravím RC a ještě to raději @jhavrlant prožene automatickými testy.

**Comment by motyc** [comment]
Za mě to vypadá v pořádku.
