### ISSUE TITLE
Kontrola na posun stavu při odeslání aktualizace záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#258]
Je třeba ošetřit situaci, kdy dva uživatelé otevřou totožný záznam (např. pro přihlášení projektu) a následně jej upraví a změnu odešlou. Pokud při tomto dojde k posunu stavu (např. P1->P2), druhý uživatel by již neměl mít možnost změny uložit (měl by dostat chybovou hlášku; lze identifikovat z historie záznamu, potažmo z aktuálního stavu). Toto je třeba vyřešit u všech typů záznamů pro všechny posuny stavů, jinak mohou vznikat zcela chybové situace.

Jde o to řešit primárně kolize při posunu stavu záznamu.

**Comment by jnihnat** [comment]
Aktualne funguju kontroly nasledovne i po uprave:
1. V nekterych pripadech se kontroluje stav zaznamu. (stara funcionalita ktoru som nemenil) Napr pri posune z odoslany do zapsany - pokud neni stav odeslany vrati se chyba 403 - pristup zakazan - Do budoucna bych to upravil a vracel standardne na detail zaznamu + warning/error sprava hore
2. pak je pridana nova kontrola na zmenu stavu nekym jinym:
- pokud chcem napr vratit z archivovana ale nekdo ji uz mezi tim vratil do potvrzeno, tak se vratim na detail s chybovou hlaskou hore
- kvuli tyto kontrole som musel pridat na konec url "?sent_stav" bez toho by se ta kontrola delat nedala. Kedze je kazdy posun dvoukrokovy, tak musim vedet z jakeho stavu na obrazovku jdu, pokud by k jiny zmene doslo na dany obrazovce. Proto nebylo mozne pouzit ani historii
