### ISSUE TITLE
Umožnit nahrání nové verze existujícího souboru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#260]
Umožnit nahrání nové verze existujícího souboru při zachování nazev_puvodni; ostatní se logicky aktualizuje.

Predpoklad je novy sloupec v tabulce soubory s tlacitkem “nahrat novy”, pripadne neco obdobneho.

Implementovat funkcionalitu pro dokumenty (/dokument/detail/), knihovnu 3D (/dokument/detail/model/) a samostatné nálezy (/pas/detail/). Pro projektovou dokumentaci to není třeba.

**Comment by pesikj** [comment]
@motyc To se týká těchto tří tabulek: u projektu (projektová dokumentace), knihovny 3D a samostatných nálezů?

Všude má být funkcionalita stejná?

**Comment by pesikj** [comment]
Ještě tedy Akce.

**Comment by motyc** [comment]
@pesikj Dobrá otázka - mělo by to být možné pro dokumenty (/dokument/detail/), knihovnu 3D (/dokument/detail/model/) a samostatné nálezy (/pas/detail/). Pro projektovou dokumentaci to není třeba.

**Comment by pesikj** [comment]
@motyc Upravil jsem text zadání, aby reflektoval poslední komentář.

**Comment by motyc** [comment]
Nefunguje, po nahrání a uložení přeskočí okno a nic se nestane (testováno u dokumentu i samostatného nálezu) - např. https://wamcr-test.aiscr.cz/dokument/detail/ZA-C-201908687A-01

**Comment by motyc** [comment]
Doplňuji v souvislosti s testem #19 - soubor se zjevně do systému nahraje, ale aplikace to nijak uživateli nedá najevo. Navíc se nesmaže původní soubor, ale zůstane zachován ve filesystému.

**Comment by pesikj** [comment]
@motyc Vycházel jsem ze zadání, že má jít o nahrání nové verze souboru, nikoli o přepsání stávající, proto je zachován i původní soubor.

**Comment by motyc** [comment]
@pesikj Omlouvám se, to jsem se nepochopili. Pokud bychom původní verze zachovávali, muselo by se k nim nějak jít dostat, což by stejně byla práce navíc. Pokud to není problém, řešte to jako náhradu.

**Comment by pesikj** [comment]
@motyc O nahrání souboru je uživatel informován vizualizací v dropzone.

![image](https://user-images.githubusercontent.com/15179154/174324236-271e0326-c46e-458d-8f6d-27be40a482ee.png)

**Comment by motyc** [comment]
@pesikj Máte pravdu, je to konzistentní se zbytkem, jen to není úplně praktické. Musím se nad tím víc zamyslet. Udělám k tomu potvrzení nahrávání nové issue.

Všiml jsem si ale, že nové nahrání se nezapíše do historie změn souboru (kvůli tomu jsme ji dělali).

**Comment by motyc** [comment]
### Výsledky testu
- [ ] kliknutí na tlačítko "Nahradit" na libovolném místě vrátí error 500

**Comment by motyc** [comment]
### Výsledek testu
Nahrání funguje, ale:
- [ ] při nahrání se neaktualizuje `soubor.nazev_puvodni` (tím pádem i do historie se zapisuje nesmysl do poznámky)
- [ ] Zobrazeno nesmyslné varování při nahrání duplicitního souboru k nálezu v PAS (http://192.168.254.30:8080/nahrat-soubor/329139?next=/pas/detail/C-202010524-N00003) a soubor se nenahraje. Bylo by opravdu dobré to vyřešit jednou pro vždy, reportujeme to stále dokola:
![image](https://user-images.githubusercontent.com/20186892/179218136-9ad2c177-aca0-4222-98c8-a0348e509975.png)
- [ ] Naopak při opakovaném nahrání téhož souboru k dokumentu systém žádné hlášení o duplicitě nedává. Správně to funguje jen při nahrávání zcela nového souboru (platné všude).

**Comment by pesikj** [comment]
@motyc 
Toto je požadavek na změnu, v zadání nic o kontrole formátu není.

- Při pokusu nahrát soubor ve špatném formátu u dokumentu rovněž vyskočí nesrozumitelná hláška (viz výše), u samostatného nálezu to naopak projde a chybu to nehlásí vůbec.

Toto je požadavek na změnu, v zadání nic o přejmenování souborů není.

- Soubory nálezů mají chybné pojmenování (nejsou vypuštěny pomlčky); chybně: 1617996406701_C-202010524-N00003F1.tif, správně: 1617996406701_C202010524N00003F1.tif (liší se od nahrání nového souboru); navíc dojde ke změně přípony na "tif", přestože jde o soubory JPEG (původně přípona .JPG).

**Comment by pesikj** [comment]
@motyc 

> při nahrání se do historie.poznamka uloží soubor.nazev_puvodni místo skutečného názvu nahrávaného souboru

V zadání není o zápisu do historie vůbec nic, včetně toho, jaká hodnota se kam má ukládat.

**Comment by motyc** [comment]
@pesikj S vaším hodnocením nemůžu souhlasit. Jedná se o známé a popsané funkce, které jsme nepožadovali nijak měnit, pouze umožnit soubor nahradit novou verzí. Stejně jako v každém issue znovu nepopisujeme GUI, nevidím důvod popisovat stále dokola jiné funkce, které mají obecný charakter. Pokud v tomto je třeba postupovat jinak, musíme se domluvit, ale moc si nedokážu představit, jak bychom to dělali. Vezmu-li to postupně:
1) `Při pokusu nahrát soubor ve špatném formátu u dokumentu rovněž vyskočí nesrozumitelná hláška (viz výše), u samostatného nálezu to naopak projde a chybu to nehlásí vůbec.` - jde o obecné chování (omezení akceptovaných typů souborů), navíc se uživateli zobrazuje v některých případech rozbitý alert
2) `Soubory nálezů mají chybné pojmenování (nejsou vypuštěny pomlčky); chybně: 1617996406701_C-202010524-N00003F1.tif, správně: 1617996406701_C202010524N00003F1.tif (liší se od nahrání nového souboru); navíc dojde ke změně přípony na "tif", přestože jde o soubory JPEG (původně přípona .JPG).` - pojmenování souborů je obecné pravidlo a rozhodně jsme zde nechtěli, aby se systém choval odlišně; navíc opět je to dokonce rozbité, protože to ze všech souborů dělá zdánlivě tif
3) `při nahrání se do historie.poznamka uloží soubor.nazev_puvodni místo skutečného názvu nahrávaného souboru` - chování historie vyplývá z #364 (`historie.poznamka - název souboru při nahrání`)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Při nahrání se do `historie.poznamka` nyní uloží jméno mazaného souboru, nikoli toho nově nahrávaného
- [ ] Při opakovaném nahrání téhož souboru systém nedává žádné hlášení o duplicitě (již existující obecná funkce). Správně to funguje jen při nahrávání zcela nového souboru.
- [ ] Soubory se nepřejmenují podle stanovených pravidel (#362)
- [ ] Vůbec se nekontroluje správnost formátů podle: https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Fungovani-uloziste-souboru

**Comment by motyc** [comment]
### Výsledky testu
- [ ] hash se do názvu souboru (v DB i na úložišti) vloží dvakrát (např. http://192.168.254.30:8080/historie/soubor/220687), špatně tak je i nazev_zkraceny
- [ ] kontrola duplicity nefunguje (např. pro http://192.168.254.30:8080/dokument/detail/X-C-TX-201904189 nahrány dva totožné soubory bez jakéhokoli oznámení; navíc stejný soubor existuje i u jiných záznamů)
- [ ] při pokusu nahrát cokoli k sam. nálezu (např. http://192.168.254.30:8080/nahrat-soubor/pas/nahradit/339176?next=/pas/detail/C-202104256-N00009) dostanu nesmyslnou hlášku a soubor se nenahraje:
![image](https://user-images.githubusercontent.com/20186892/182810885-bf362007-495c-4261-a120-733629259813.png)

**Comment by motyc** [comment]
### Výsledky testu
- [ ] Pokud nahrávám náhradu souboru, nemá docházet ke změně jeho názvu (změně sufixu A-Z). Nyní když u dokumentu http://192.168.254.30:8080/dokument/detail/X-C-TX-201904189 nahrávám náhradu souboru, tak se např. soubor XCTX201904189D přejmenuje na XCTX201904189E. Název by se ale měnit neměl (mělo by zůstat XCTX201904189D), pouze upravit hash a přípona (jinak by celá funkce neměla smysl). Totéž se děje u samostatných nálezů.
- [ ] Kliknu na nahradit soubor -> nahraji novou verzi -> zjistím, že jsem zvolil špatný soubor a kliknu na odstranit -> chci nahrát jiný soubor a systém zahlásí chybu (okno s nesmyslným html). Dochází k tomu asi proto, že kliknutím na odstranit se smaže celý záznam o souboru a novou náhradu už není k čemu nahrát. Nevím, jak to nejlépe koncepčně vyřešit (při nahrávání úplně nových souborů tohle není problém). Ale při náhradách by bylo třeba postupovat nějak jinak, aby k tomu nemohlo dojít. Napadají mne varianty: 
1) místo funkce odstranit umožnit znovu otevřít dialog pro výběr souboru, kterým by se ten aktuální nahradil
2) funkci odstranit při nahrazování nezobrazovat (vypnout) - uživatel by se tak vrátil zpět a celý proces prostě jen zopakoval

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Pokud nahraji soubor s jinou příponou, neaktualizují se správně metadata (mimetype) a navíc se nezmění přípona souboru na správnou (nahrán soubor PNG, zůstala přípona JPG). Po minulém testu jsem na to raději upozorňoval: `Název by se ale měnit neměl (mělo by zůstat XCTX201904189D), pouze upravit hash a příponu`). Testováno na http://192.168.254.30:8080/historie/soubor/339288
- [ ] Z nějakého důvodu se mi nedaří aktualizovat tento soubor: http://192.168.254.30:8080/nahrat-soubor/pas/nahradit/329139?next=/pas/detail/C-202010524-N00003 (hlásí klasicky tu nesrozumitelnou chybu v HTML). Může jít o chybu testovacích dat, ale nedokážu říci.

**Comment by motyc** [comment]
Vše v pořádku.
