### ISSUE TITLE
Persistentní link pro zobrazení záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#261]
Každý záznam musí být přístupný přes persistentní link, složený z URL prefixu (https://amcr.aiscr.cz/id/) a ident_cely záznamu (např. (https://amcr.aiscr.cz/id/C-201703683). Zadání odkazu zobrazí detail záznamu.

**Comment by motyc** [comment]
Tak jak je kód napsán, nebude fungovat pro všechny typy ident_cely (opravdu pro všechny by to měl být systém schopen vyhodnotit), chybně bude např. i pro akci: https://wamcr-test.aiscr.cz/id/C-200912973B.

Nevím, zda je nejlepší spoléhat se na regulární výrazy a zda by se místo toho neměl generovat index všech ident_cely ze všech datových tříd, které jej obsahují. Ten by se použil k vyhodnocení dotazu. Na rozdíl od regulárních výrazů by to bylo neprůstřelné, jen by se musel vyřešit způsob vytváření a doplňování indexu (periodicky jednou denně? při každé operaci s ident_cely?). Ident_cely je ale u spousty položek (vč. komponent, ADB, uživatelů, hesel...), struktura se může lišit (komplexní jsou zejména dokumenty) a psát pro vše výrazy by asi byla dost hrůza.

Bylo by dobré persistentní link záznamu někde viditelně zobrazit (např. dát ikonu pro zobrazení linku vedle čísla záznamu v horní liště).

**Comment by jnihnat** [comment]
@motyc 
- Ja som za ponechani regexu, jen je ho potreba upravit... u Akce je chyba a je tam natvrdo A a nepocital som s podrazenymi polozkami, to je jednoducha uprava. 
- pokud by sme mneli vymyslet nejakou logiku pro pridelovani dalsiho unikatniho klice a mit to v jedny tabulce, tak to mi pripada zbytecna prace navic, kdyz uz ted je ident_cely unikatni cez celou aplikaci.

**Comment by jnihnat** [comment]
@motyc pokud to u dokumentu ma byt podle HESLAR_DOKUMENT_RADA tak to asi potreba neni. Umym ten regex upravit, at si ty rady dotahne odtamtud. Mozna jen poprosim, ci vse krome 3D ma smerovat na dokument/detail a jen 3D na dokument/detail/model
alebo to ma byt komplexnejsie.

**Comment by motyc** [comment]
@jnihnat V základu z toho hesláře vycházet jde, problém ale je, že u některých řad jsou dvě alternativy skladby ID. Zatím to ale založte čistě na řadách a standardní skladbě (jako TX), ty speciální případy popíšu až najdu chvilku času a jde je doplnit.

S 3D potvrzuji - je to jen ta jedna.

**Comment by jnihnat** [comment]
@motyc jeste prosim o upresneni smerovani pro:
ADB a vyskovy bod - to je napojene na DJ a teda smerovat na patricni akci?
Pian - to pokud vim tak muze byt pripojen na vice DJ a teda neda se urcit jedinecna url. nebo se mylim? Co v tomto pripade?

**Comment by motyc** [comment]
@jnihnat Pokud by šlo nastavit kotvu přímo na daný formulář (DJ, ADB, VB) u akce, bylo by to lepší (viz chování #286), ale i přechod na akci stačí, pokud to tak nejde.

**Comment by jnihnat** [comment]
upraveno a kontrolovano oproti DB.
Vsiml som si akurat ze v dokumentoch jsou zaznamy v tvaru:
[řada]-[ID projektu, akce nebo lokality]-[pořadové číslo v libovolné délce]
predpokladam ze jde o snimky z terennich akci, akurat bude chyba ve Vasi vzorci.
pak u vyskovych bodov maji nektere body jiny zacatek identu jako je navazany ADB.
napr. X-ADB-PRAH71-0009-V0003 -> ADB-PRAH71-007419

**Comment by motyc** [comment]
@jnihnat ad foto - To je starý formát, zápisu, který bude změn na správný podle vzorce. Je k tomu issue https://github.com/ARUP-CAS/aiscr-amcr/issues/141, které čeká na vyřešení.

ad VB - to je opět jen problém migrace; musíme vyřešit v issue #376

**Comment by jnihnat** [comment]
ok upraveno teda na nove hodnoty po migraci.

**Comment by motyc** [comment]
### Výsledky testování
Chyby nalezeny při zadání:
- [ ] http://192.168.254.30:8080/id/M-202005151A-D02 (referuje chybně na http://192.168.254.30:8080/arch-z/akce/detail/M-202005151A-D02, ve verzi s "D01" přitom funguje)
- [ ] http://192.168.254.30:8080/id/ADB-PRAH01-001234 (neexistující ID) dostanu error 500 místo 404

Zapomněl jsem též odpovědět na otázku k PIAN - tam to čeká na zpracování #392, zatím tedy nemíří nikam, jen připravit regex.

**Comment by jnihnat** [comment]
@motyc tomu bodu 1 nerozumiem. Pisete zze D02 odkazuje na D02. co je na tom spatne?

**Comment by motyc** [comment]
@jnihnat Problém byl v tom, že http://192.168.254.30:8080/arch-z/akce/detail/M-202005151A mě posílalo na daný odkaz, který ale neexistoval (správně je http://192.168.254.30:8080/arch-z/akce/detail/M-202005151A). Teď to ale najednou funguje dobře.

**Comment by motyc** [comment]
### Výsledky testování
- [ ] http://192.168.254.30:8080/id/ADB-PRAH01-001234 (neexistující ID) dostanu error 500 místo 404 (stále platí)

**Comment by jnihnat** [comment]
moje chyba, zapomnel sem to oznacit pro @pesikj aby to mergol... bude v dalsi dodavce.
