### ISSUE TITLE
Dohodnout URL pro plánovaná view a revidovat stávající

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#262]
Dohodnou URL pro plánovaná view a revidovat stávající (zejména problém s arch_z, kde budou různé typy view; evidovat v https://docs.google.com/spreadsheets/d/19lpy9VQ6qfIW5S2c7pi__UtmSsPy7pRbRDeY5b5Bkzc/edit)

**Comment by motyc** [comment]
@jnihnat Zde poznámky z revize:
1. asi by bylo dobré sjednotit jazyk URL na češtinu; nicméně nevím, nakolik možné to je u views spojených s registrací atd. jde to, nebo je s tím nějaký problém?
2. Seznam URL/view, které myslím ve skutečnosti v aplikaci nepoužíváme (nutno prověřit, možná ok):
- [ ] `/adb/detail/<str:ident_cely>`
- [ ] `/dj/detail/<str:ident_cely>`
- [ ] `/komponenta/detail/<str:ident_cely>`
- [ ] `/oznameni/edit/<int:pk>`
- [ ] `/pian/detail/<str:ident_cely>`
3. Seznam URL ke změně (bez těch spojených s registrací uživatele):
- [ ] všechny stávající `/arch_z/*` -> `/arch_z/akce/*` - je to nutné kvůli budoucímu #319, který také vychází z tabulky/view arch_z
- [ ] `/arch_z/akce-get-katastr` ->`/arch_z/akce-zjisti-katastr`
- [ ] `/arch_z/get-pians-in-cadastre` -> `/arch_z/katastr-zjisti-piany`
- [ ] `/delete_file/<int:pk>` -> `/smazat-soubor/<int:pk>`
- [ ] `/dokument/create/model` -> `/dokument/model/zapsat`
- [ ] `/dokument/detail/model/<str:ident_cely>` -> `/dokument/model/detail/<str:ident_cely>`
- [ ] `/dokument/edit/model/<str:ident_cely>` -> `/dokument/model/edit/<str:ident_cely>`
- [ ] `/dokument/list/model` -> `/dokument/model/vyber`
- [ ] `/download_file/<int:pk>` ->`/stahnout-soubor/<int:pk>`
- [ ] `/oznameni/get-katastr-from-point` -> `/oznameni/oznameni-zjisti-katastr`
- [ ] `/pas/create` -> `/pas/zapsat`
- [ ] `/pas/pas-get-katastr` -> `/pas/pas-zjisti-katastr`
- [ ] `/pas/list` -> `/pas/vyber`
- [ ] `/pas/spoluprace/list` -> `/pas/spoluprace/vyber`
- [ ] `/pian/list-pians/` -> `/pian/seznam-pian/`
- [ ] `/dokument/dokumenty/` -> `/dokument/seznam-dokumenty/`
- [ ] `/dokument/dokumenty-bez-zapsanych/` -> `/dokument/seznam-dokumenty-bez-zapsanych/`
- [ ] `/projekt/create` -> `/projekt/zapsat`
- [ ] `/projekt/get-points-arround-point` -> `/projekt/projekt-zjisti-okolni-projekty`
- [ ] `/projekt/list` -> `/projekt/vyber`
- [ ] `/upload-file/post` -> `/nahrat-soubor/odeslat`
- [ ] `/upload_file/dokument/<str:ident_cely>` -> `/nahrat_soubor/dokument/<str:ident_cely>`
- [ ] `/upload_file/projekt/<str:ident_cely>` -> `/nahrat_soubor/projekt/<str:ident_cely>`
- [ ] `/upload_file/pas/<str:ident_cely>` -> `/nahrat_soubor/pas/<str:ident_cely>`
- [ ] `/uzivatel/osoba/create` -> `/osoba/zapsat`
- [ ] `/uzivatel/osoby/` -> `/seznam-osoby/`
4. Nedoplnil jsem sloupce GET/POST pro nové URL, protože nevím jak je to správně; to si doplňte podle potřeby prosím za Huld

**Comment by jnihnat** [comment]
@motyc 
1. nieco by slo zmenit jednoduchsie a nieco tazsie, ale zmenit by malo byt mozne vsetko
2. 
- adb, komponenta, dj, pian /detail sa pouzivaju u akce k zobrazovani
- oznameni/edit - sa pouziva u projektu na editaci oznamovatele
3. 
- navrhuji u nahrat soubor pouzivat vzdy nahrat-soubor a ne jednout "_" a jednou "-" pokud to teda nema nejaky vyznam. Odporuceni je nikdy nepouzivat v url "_" protoze se ma tendenci stracet zraku.

**Comment by motyc** [comment]
@jnihnat 
1. Tak nechme tuto část v EN, ať si zbytečně nepřiděláváme práci.
2. ok; v takovém případě bych jen upravil:
- [ ] `/oznameni/edit/<int:pk>` -> `/projekt/oznamovatel/edit/<int:pk>`
3. úplný souhlas, vzniklo to omylem, měla tam být pomlčka. Co se týče podtržítka, tak to ale ještě máme v "arch_z". Nezměníme to tedy také na "arch-z"?
4. To je mi celkem jedno, ale rozhodnutí nechám na vás. Srozumitelné mi přijde obojí a i v češtině se používá "editovat".

**Comment by jnihnat** [comment]
1. ponechane
2. zmenene
3. zmenene na arch-z
4. nechane edit

**Comment by ScottVanWagenen** [comment]
Exists in Jira
https://huld.atlassian.net/browse/AMCR-10

**Comment by motyc** [comment]
### Výsledek testování

Provedl jsem kontrolu na základě jednotlivých souborů urls.py a aktualizoval Google sheet. Níže uvádím nutné korekce a případné dotazy.

- [ ] není mi jasné, kde jsou definovány níže uvedené adresy - zde jen prosím o navedení na správný soubor; v repozitáři se mi nic z toho najít nepodařilo:
`/accounts/activate/<str:activation_key>/`
`/accounts/activate/complete/`
`/accounts/password_change/`
`/accounts/password_change/done/`
`/accounts/password_reset/`
`/accounts/password_reset/done/`
`/accounts/register/closed/`
`/accounts/register/complete/`
`/accounts/reset/<uidb64>/<token>/`
`/accounts/reset/done/`

- [ ] `akce-get-piany` -> `/arch-z/katastr-zjisti-piany`
- [ ] Není mi jasné, k čemu zvlášť definujeme aplikaci "uzivatel". Pokud je potřebná, měla by se jmenovat nějak logičtěji (uživatele spravujeme přes accounts, toto s tím nemá nic moc společného, jde o hesláře). Přijde mi ale, že související views by mohly klidně být součástí "core" nebo "heslar".
- [ ] `/uzivatel/seznam-uzivatele-choices/` -> choices by se mělo počeštit, ale nevím, co to přesně dělá, tak neumím zvolit správný výraz
- [ ] `/dokument/model/vybrat` -> `/dokument/model/vyber` (ať je to jednotné)
- [ ] `/nalez/edit-nalez/<str:komp_ident_cely>` -> `/nalez/edit/<str:komp_ident_cely>`
- [ ] `/nalez/smazat-nalez/<str:typ>/<str:ident_cely>` -> `/nalez/smazat/<str:typ>/<str:ident_cely>`
- [ ] `/pian/create/<str:dj_ident_cely>` -> `/pian/zapsat/<str:dj_ident_cely>`
- [ ] `projekt/oznamovatel/edit/<int:pk>` - je definováno ve "webclient" místo v "projekt" - má to nějaký důvod? Přijde mi to trošku zmatečné...

Též jsme nedořešili část "Dohodnou URL pro plánovaná view". Toto bych ale udělal tak, že před implementací nových views se vždy dohodneme na struktuře URL. Prosím tedy, abyste při potřebě zavedení nové URL vždy tuto informaci napsali do dotčeného issue, abychom si dané znění a strukturu URL potvrdili, a to ideálně už ve fázi analýzy.

**Comment by motyc** [comment]
ad 1 - přejmenování není třeba (jak jsme se dohodli), jen mi nebylo jasné, proč to nemohu najít

ad 3 - nemám problém s existencí té části `uzivatel`, ale nedává logiku do ní řadit `osoba/zapsat` a `seznam-osoby/`, když máme i aplikaci `heslar`, kam to krásně zapadá; pokud to nezpůsobí nějaké zásadní obtíže, navrhuji zmíněné dvě položky přesunout

ad 4 - ok

ad 7 - asi omylem změněno na `/nalez/nalez/<str:typ>/<str:ident_cely>` (správně `/nalez/smazat/<str:typ>/<str:ident_cely>`)

ad 9 - ok
