### ISSUE TITLE
Informace o podporovaných formátech souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#263]
Při nahrávání souborů ve špatném formátu by měla vyskočit nápověda s podporovanými formáty.

**Comment by jnihnat** [comment]
pridane message constanty pro jednotlive stranky, ktere se zobrazi jako alert v pripade nepovoleneho typu souboru.

**Comment by motyc** [comment]
Otestovat, až bude #354

**Comment by motyc** [comment]
@jnihnat Prosím do dokumentace (https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Fungovani-uloziste-souboru) doplnit, jaké formáty jsou nyní akceptované v jaké části aplikace (URL). Musíme to zrevidovat, ale nemám podle čeho.

**Comment by jnihnat** [comment]
doplnene
