### ISSUE TITLE
Umožnit zobrazení všech metadat o souboru a jeho historie

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#265]
Umožnit zobrazení všech metadat o souboru a historie (asi by stačil tooltip či něco obdobného).

Metadata z tabulky soubor:
- nazev_zkraceny
- nazev_puvodni
- rozsah
- nazev
- mimetype
- size_bytes

Historii standardně vytvářet, tj. zaznamenávat kdo a kdy soubor naposledy změnil. To ale platí i pro první nahrání (podstatný je vztah k uživateli a času).

**Comment by motyc** [comment]
Přidávám pro úplnost, ale vysvětleno na schůzce.

> Jan Ihnat 
> 21. prosince 2021 16:43
> osobne ty metadata mi nedavaji zmysel, protoze:
> 
> - nazev_zkraceny = nazev_puvodni a nazev_zkraceny je zobrazen v tabulce
> - rozsah = vzdy null
> - nazev = checksum + _ + nazev_zkraceny - tohle nezobrazujeme
> - mimetype, size_bytes, vytvoreno - uz teraz zobrazujeme v tabulce.
> - Jedine co teda nezobrazujeme je nazev. Udelat to jako tooltip neni problem, ani narocny, jen mi to pripada zbytecny.
> 
> Historii je mozne dodelat, ta by byla podobna jako v jinych mistech.
> Ked pozeram do kodu, tak tam vidim este tohle:
> Vlastnik u souboru je na pevno User s email="amcr@arup.cas.cz" je tohle spravne?

**Comment by pesikj** [comment]
@motyc Může to být na stráce s historií souboru? Na tooltip je to poměrně dost informací.

**Comment by motyc** [comment]
@pesikj Určitě může, tam to bude pasovat dobře.

**Comment by motyc** [comment]
Funkčně ok, ale problém je v zobrazení - viz screenshot (je tam ta šipka z předchozí obrazovky, jen bílá + tlačítko zpět je schované za patičkou):

![image](https://user-images.githubusercontent.com/20186892/168138382-6a461b2a-3b4e-4fa0-9744-b47885c550e5.png)

**Comment by motyc** [comment]
Test na: https://wamcr-test.aiscr.cz/historie/soubor/329159
- [ ] úplně chybí tlačítko "Zpět"
- [ ] popisek posledního pole v záhlaví ubíhá mimo obrazovku (předpokládám ale, že jde o pole soubor.vytvoreno, které bude patrně v souvislosti s #474 odstraněno)

(původně hlášeno pro #364, ale tady dává větší smysl vzhledem k předchozím komentářům)

**Comment by motyc** [comment]
@pesikj Ano, to bude nejlepší.
