### ISSUE TITLE
Přechod z dokumentu zpět na akci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#266]
Při přidávání nového dokumentu k akci dojde k přepnutí na záložku Dokument, ale uživateli nemusí být jasné, jak se vrátit na původní akci. Usnadnit přechod zpět na záznam, v souvislosti se kterým byl dokument vytvořen.

**Comment by motyc** [comment]
Pro nově vytvořený dokument je to ok, ale nefunguje to úplně správně pro dokumenty napojené na více záznamů, protože to přechází vždy na první připojenou akci, nikoli na místo ze, kterého jsem přišel. Problém lze ilustrovat pro dokument https://wamcr-test.aiscr.cz/dokument/detail/C-DD-201710000. Ten je napojen na:
- C-201774779A
- C-201908687A
- C-202009779

Bez ohledu na to, odkud na něj přijdu, po kliknutí na příslušný ovládací prve se ale otevře vždy C-201774779A.

Bude to potřeba ošetřit lépe, případně možnost zobrazovat jen tam, kde je cesta návratu jasná... (tj. kde není víc propojení). Můžeme se domluvit.

**Comment by jnihnat** [comment]
Tuna premyslim:
- umym dostat z headeru requestu REFERRERA, pokud by byl detail akce nebo projektu vtedy ho pouzit pro back tlacitko.
- "problem" by byl pokud uzivatel prejde napr na editovat, tak pak by se tam uz tlacitko nezobrazilo po ulozeni editu.
- tento "problem" by se dal obejit nejak cez cookies a ukladat si tam ten redirect, tu by mohol ale vznikat dalsi problem, kedy uzivatel prejde na detail priamo zadanim do linku a pod.
Tu by sa mi teda zisiel viac ten biznis pohlad, ako sa to pouziva:
- ci si len vacsinou zobrazim detail a chcem ist spat, alebo detail, casto editujem a chcem ist spat.
- pokial to druhe skusil by som to cez tu cookie a nejakou dalsou logikou kedy sa ma odmazat a pod aby sme nemali spatne redirecty.

**Comment by motyc** [comment]
Bude asi nastávat obojí, tj. jdu tam a hned zase zpět, nebo něco upravím a vracím se teprve poté. Když nad tím přemýšlím, tak mi přijde, že by šlo:

- po kliknutí na dokument z https://wamcr-test.aiscr.cz/projekt/detail/xxx nebo z https://wamcr-test.aiscr.cz/arch-z/akce/detail/xxx by se vložilo id "xxx" do cookie a otevřel https://wamcr-test.aiscr.cz/dokument/detail/yyy. Id "yyy" by se též uložilo do cookie.
- dokud bych zůstal v rámci obrazovek aplikace "dokument" se stejným id "yyy", jako je uloženo v cookie, tlačítko zpět by fungovalo pro uložené id "xxx"
- jakmile bych odešel mimo aplikaci dokument nebo na dokument s jiným id "yyy", cookie by se resetovalo a tlačítko zpět by se nezobrazovalo

Ale možná najdete nějakou lepší cestu.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Jsou tam zapomenuté uvozovky + část adresy jiné aplikace, takže to nefunguje. Nyní: https://wamcr-test.aiscr.cz/dokument/detail/%22/arch-z/akce/detail/C-200811817A%22 Správně: https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-200811817A
