### ISSUE TITLE
Přidání osoby - dořešit chování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#268]
Přidání osoby - dořešit chování

- u akce se vytvoří další záložka a po přidání jména se změní na Homepage;
- u projektu se další záložka nevytvoří a po přidání osoby se systém vrátí na pole se jménem vedoucího 

Udelat modal okno (pop up - stejne jako po kliknuti na Licence v pate stranky). User by mnel moznost ulozit/zavrit okno. Po ulozine by bylo mozne danu osobu rovno vyplnit do formulare.

**Comment by motyc** [comment]
U projektu ok. Ze zápisu/editace akce to však přechází na divnou stránku: https://wamcr-test.aiscr.cz/osoba/zapsat

**Comment by jnihnat** [comment]
opraveno v #487 V aktualni nasazene verzi tlacitko po pridani osoby chybi pro create i edit. To je taky opraveno do nove verze.
