### ISSUE TITLE
Doplnit formulář pro správu vlastního uživatelského účtu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#269]
Doplnit formulář pro správu vlastního uživatelského účtu, ve kterém bude možno:
- [x] zobrazit: auth_user.first_name, auth_user.last_name, auth_user.email, auth_user.ident_cely, auth_user.date_joined, auth_user.organizace + role a oprávnění + historie)
- [x] upravit: auth_user.password, auth_user.telefon
- [x] spravovat notifikace - viz #720

**Comment by sedmar** [comment]
Samostna stranka pro editaci.

**Comment by pesikj** [comment]
@motyc Protože #389 není hotové a vývoj ještě nějakou dobu potrvá, prosím o oddělení nastavení notifikací pro uživatele do samostatného issue, ať můžeme udělat zbytek. Děkuji.

**Comment by motyc** [comment]
@pesikj hotovo

**Comment by pesikj** [comment]
@motyc Je toto barevné schéma OK?

![image](https://user-images.githubusercontent.com/15179154/199071261-32fa0f26-aa5c-4ba2-a832-626f773df9ec.png)

**Comment by pesikj** [comment]
@motyc Bylo by možné si zítra zavolat kvůli zobrazování historie?

**Comment by motyc** [comment]
@pesikj
Ad barevné schéma - bez problémů, takto neutrální je to dobré.
Ad telefonát - k dispozici u PC budu ca 9-12 a poté ca 14:30-17:30, tak klidně zavolejte.

**Comment by motyc** [comment]
@pesikj
Ad tabulka historie
- celé to vzniklo zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/48218d29eea99910e5fdb1fba4a9132a1552e3a7/migrace/migrace_1.sql#L38
- data reprezentují údaj o změně údajů účtu podle `user_deactivation_times` v původní DB
- neevidovali jsme uživatele, který změnu udělal, takže je tam všude `amcr@arup.cas.cz`
- `typ_zmeny_old` obsahuje údaj, zda šlo o aktivaci (1) či deaktivaci (0); `typ_zmeny` tak lze doplnit jednotně podle toho, jak si to budeme nově označovat
- `poznamka` je výsledné oprávnění (auth_level) po úpravě; to asi lze zatím nechat a případně to později převedeme na srozumitelné údaje

V tabulce `stats_login` jde o všechna přihlášení do desktopu.

**Comment by pesikj** [comment]
@motyc Přihlášení uživatele podle mě nemá smysl migrovat, přihlášení by se mělo zobrazovat pouze pro aktuální systém, jinak by to mohlo vést ke zmatení uživatelů.

**Comment by motyc** [comment]
@pesikj Na druhou stranu je to pro nás zajímavé pro statistiky a také je to způsob, jak odhalit nepoužívané účty. Co to zmigrovat, ale označit nějak zvlášť, aby bylo jasné, že je to z desktopu?

**Comment by pesikj** [comment]
@motyc 
Takhle se zobrazuje historie přihlášení. Data bych rozhodně nemigroval ze staré tabulky do nové, struktura těch dat je úplně jiná a logika zápisu taky. Bylo by možné udělat query na tabulku stats_login a doplnit je ve výpisu k datům přihlášení, pokud by vás ta historie zajímala.

![image](https://user-images.githubusercontent.com/15179154/200653705-0df7e4b8-f8ef-4478-b718-62a53a2f172b.png)

**Comment by motyc** [comment]
@pesikj Rozumím. Ještě se na tím zamyslím. Můžeme to teoreticky udělat tak, že si stávající stav ke dni migrace vyexportujeme a budeme to mít k dispozici offline. Zatím tabulku stats_login tedy pusťte z hlavy, není to tak podstatné.

**Comment by pesikj** [comment]
@motyc Dobře, souhlasím.

**Comment by pesikj** [comment]
@motyc Viz komentář o spojení přes Zoom u jiného issue. Měli bychom si definovat, zda chceme zobrazovat seznam oprávnění, seznam skupin nebo obojí.

**Comment by pesikj** [comment]
@motyc 
> U některých polí chybí překlady na skutečné hodnoty hesel (zobrazují se cizí klíče)
-- Organizace
-- Hlavni role
-- Skupiny
 Date joined -

Tady nevím, co tím myslíte? Já vidím všude texty. Je to tak i na screenshotu z 8. listopadu.

![image](https://user-images.githubusercontent.com/15179154/204809912-836d8615-d36f-4610-9ad2-230f31e9d37c.png)

**Comment by motyc** [comment]
@pesikj Já vidím (právě teď na http://192.168.254.30:8080/upravit-uzivatele/) toto:
![image](https://user-images.githubusercontent.com/20186892/204820152-f0252e0a-13f5-456a-8c36-8b95334d33b0.png)

(cache jsem promazal)

**Comment by motyc** [comment]
### Výsledky testu
- [ ] - date joined - prosím ořezat/nezobrazovat desetinná místa u sekund (asi opomenuto z posledně)
- [ ] - po uložení se nezobrazí žádná potvrzující hláška
