### ISSUE TITLE
REQ-G-13: It must be possible to register a new user.

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#27]
Implementace registrace uzivatele.

**Comment by Najiva** [comment]
- [ ] Registrace uzivatele
- [ ] Overovani emialu
- [ ] Notifikace spravce
- [ ] Notifikace o aktivaci

**Comment by Najiva** [comment]
Je potreba styling vsech templatu v templates/django_registration

**Comment by pkudela** [comment]
Ahoj @Najiva , potrebuju nejak videt v browseru jednotlive templaty/kroky registrace. Nyni, kdyz kliknu z login stranky na odkaz "Zaregistrovat se", tak se nic nestane viz. screenshot nize. Muze tam prosim dodat spravne url?

![image](https://user-images.githubusercontent.com/16591052/119665728-f69d1a80-be34-11eb-9e65-5e767d2f0045.png)

**Comment by pkudela** [comment]
hotovo, ten posledni - activation filed jsem nedokazal nasimulovat text, takze to vypada takto, musel jsem tam doplnit zacatek a konec kodu

![image](https://user-images.githubusercontent.com/16591052/119851179-7d71f600-bf0e-11eb-9e6a-764b99c8f325.png)

**Comment by pkudela** [comment]
@Najiva jinak tedy hotovo, prosim o kontrolu

**Comment by motyc** [comment]
Zavírám, emaily budeme řešit jako samostaný problém.
