### ISSUE TITLE
Doplnit generování potvrzení o oznámení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#273]
- [x] Při při posunu **záchranného** projektu z P0 do P1 AMČR vygeneruje potvrzení o oznámení v PDF (podle šablony; liší se pro C a M) a odešle jej oznamovateli (na zadaný email; text emailu viz E-P-01a/b).
- [x] Potvrzení se při odeslání automaticky ukládá do projektové dokumentace (název: “oznameni_[ident_cely].pdf”).
- [x] Archivář/admin má možnost Generovat nové potvrzení a odeslat jej oznamovateli (volitelné). To se opět ukládá do projektové dokumentace (název: “oznameni_[ident_cely][A..Z].pdf”).

**Comment by pesikj** [comment]
@motyc Máme již k dispozici šablony nebo nějaké jejich koncepty?

**Comment by motyc** [comment]
@pesikj ano, ten lze převzít ze stávající aplikace: [template.odt](https://github.com/ARUP-CAS/aiscr-webamcr/files/8253928/template.odt)

**Comment by pesikj** [comment]
Podle jako adresa, telefon atd. jsou informace, které jsou uložené někde v aplikaci? Pokud ne, je požadována možnost je uživatelsky upravovat?

**Comment by motyc** [comment]
@pesikj Ještě drobně aktualizováno, omylem jsem to poslal neúplné...

**Comment by pesikj** [comment]
@motyc Bude nutné použít jiný font, Arial je bohužel proprietární. Jako alternativu navrhuji OpenSans: https://fonts.google.com/specimen/Open+Sans.

**Comment by pesikj** [comment]
@motyc KATASTR má být `hlavni_katastr`?

**Comment by motyc** [comment]
@pesikj Jen raději upozorňuji, abyste nezapomněl, že na základě územní příslušnosti projektu (C/M) se liší i obsah dokumentu. V prvním příspěvku je to trošku zasuté. Proto jsou i ty konstanty uváděny vždy ve dvou variantách.

**Comment by motyc** [comment]
@podle kraje, ale tady jde použít i ident_cely, protože pro ten už to musí být nějak implementované....

**Comment by motyc** [comment]
- u https://wamcr-test.aiscr.cz/projekt/detail/C-202200003 se vygenerovala moravská verze, přitom jde o projekt C
- plánované zahájení lépe naformátovat pro výpis: `dd. mm. rrrr - dd. mm. rrrr`
- místo měsíce v datu oznámení se vypisuje znak procenta
- ident_cely do potvrzení vypsat až ten, který je přidělen jako trvalý, nikoli ten dočasný; totéž platí pro název souboru
- chybí některá vytučnění v textu (viz vzor)
- v datumech dny a měsíce uvádět bez nuly na začátku, pokud jsou jednočíslicové
- při pokusu použití funkce "Generovat nové potvrzení" dostanu error 500

**Comment by pesikj** [comment]
@motyc Z jakého pole tedy mám brát ident?

**Comment by pesikj** [comment]
@motyc Vše opraveno kromě identu, zde prosím o vysvětlení, viz předchozí komentář.

**Comment by pesikj** [comment]
Opraveno.

**Comment by motyc** [comment]
### Výsledek testu

https://wamcr-test.aiscr.cz/projekt/detail/C-202200003
- [ ] - v podpisu je Praha i Brno:
![image](https://user-images.githubusercontent.com/20186892/173661685-8c546799-e0fc-4b87-9bf2-53965fcd3be9.png)
- [ ] - okres se vypisuje dvakrát `KLADNO (Kladno) (okr. Kladno)` -> `KLADNO (okr. Kladno)`

https://wamcr-test.aiscr.cz/projekt/detail/C-202200010
- [ ] - při schválení projektu (P0 -> P1) nedošlo k automatickému vygenerování potvrzení

**Comment by motyc** [comment]
### Výsledky testu
- [ ] při schválení projektu (P0 -> P1) nedošlo k automatickému vygenerování potvrzení (http://192.168.254.30:8080/projekt/detail/C-202200016)
- [ ] oznameni_C-202200003_B.pdf - za `KLADNO (okr. Kladno)` je mezera navíc před čárkou (`KLADNO (okr. Kladno) ,`

**Comment by motyc** [comment]
### Výsledek testu
- [ ] oznámení se generuje dobře, ale vrátila se již dříve opravená chyba, kdy se do něj zapisuje dočasný ident_cely v místo trvalého (`ident_cely do potvrzení vypsat až ten, který je přidělen jako trvalý, nikoli ten dočasný; totéž platí pro název souboru`; viz též https://github.com/ARUP-CAS/aiscr-webamcr/issues/273#issuecomment-1150165956)
