### ISSUE TITLE
Doplnit generování expertních listů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#275]
U záchranných projektů:

- [x] Doplnit generování expertních listů - více viz zadání podoby viz: https://docs.google.com/document/d/1TP5kDXfKvr9-_WCQ7E8c7cVqXJSJ_1tq/edit

Vygenerovaný soubor je pouze ke stažení.

**Comment by motyc** [comment]
- Pole poznamka_podpis.label má být aktivní pouze pro případ, kdy je vybráno vysledek.jine.text
- Označení pole poznamka_podpis.label obsahuje překlep -> poznamka_popis.label bude lepší
- Vysledný dokument má chybné kódování a je celý rozhozený - neotevře jej správně ani MS Word, ani OpenOffice Writer (optimalizovat pro Word)

**Comment by pesikj** [comment]
@motyc Soubor se nyní jmenuje např. expertni_list_C-202105929.rtf, jaký další suffix myslíte?

**Comment by motyc** [comment]
@pesikj Ano, takto jsem to myslel, díky.

**Comment by pesikj** [comment]
[expertni_list_C-202105929 (13).zip](https://github.com/ARUP-CAS/aiscr-webamcr/files/8920192/expertni_list_C-202105929.13.zip)

Vyřešena kompatibilita s MS Word. Předchozí verze byla testována na Open Office a Ubuntu, teď nemůžu ověřit, jestli tato verze funguje s obojím.

**Comment by motyc** [comment]
@pesikj Přiložený soubor je ve Word a OpenOffice Writer pod Windows v pořádku.

**Comment by motyc** [comment]
@pesikj Jen jsem si všiml, že:
- celý text poznámky je nyní tučně
- bold naopak chybí u oznamovatele a jednacího čísla
- chybný je formát souřadnic (chybí N/E a oddělovač není čárka)
- celý pravý sloupec je výškově posunutý o něco níže než levý, takže hodnoty nelícují s popisky
- chybí zápatí "Dokument byl vytvořen..."
- "razítko a podpis" má být kurzivou
 
To bych doporučoval opravit podle vzoru, ať se k tomu pak nemusíme vracet.

**Comment by pesikj** [comment]
@motyc Vše vyřešeno.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] nevypisuje se projekt.vedouci
- [ ] nevypisuje se ([oznamovatel.telefon]; [oznamovatel].[email])
- [ ] odstavec `Potvrzujeme, že došlo ke splnění oznamovací povinnosti a bylo umožněno provést na dotčeném             území záchranný archeologický výzkum podle ustanovení § 22, odst. 2, zákona č. 20/1987 Sb., o státní             památkové péči. V průběhu výzkumu byly vyzvednuty či dokumentovány archeologické nálezy.` obsahuje na dvou místech hromadu mezer (platí též pro `Potvrzujeme, že došlo ke splnění oznamovací povinnosti a bylo umožněno provést na dotčeném             území záchranný archeologický výzkum podle ustanovení § 22, odst. 2, zákona č. 20/1987 Sb., o státní             památkové péči. V průběhu výzkumu nebyly vyzvednuty ani dokumentovány žádné archeologické nálezy.` (pozor, GitHub vícečetné mezery zde v postu skrývá)
- [ ] před "Dne dd. mm. rrrr" ještě jednou odřádkovat
- [ ] Jsou texty v dokumentu součástí překladů v administraci, nebo nikoli? Jde mi o to, zda je nutné hlásit překlepy, nebo zda si je opravíme sami (např. `zachranny` -> `záchranný` - typy jsou bez diakritiky všechny).
