### ISSUE TITLE
Automatická archivace projektu s poslední akcí.

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#278]
Jakmile je archivována poslední akce projektu, dotázat se uživatele, zda chce archivovat též projekt.

Mělo by jít o alert nebo modal s dotazem a možností projekt rovnou archivovat (ano / ne).

**Comment by jnihnat** [comment]
@motyc navrh ako by to mohlo vypadat:
![obrazek](https://user-images.githubusercontent.com/57906106/157416463-1adf2eda-7899-443c-b0ea-89480af408b9.png)
prvni cast bude manazovatelna v ramci prekladu a ta druha bude pevna Ano/Yes jako link.
muze to tak byt?

**Comment by jnihnat** [comment]
jeste otazka, ci to zobrazovat jen pro projekty, ktere je mozne archivovat, teda v stavu Uzavren? Jinak to po kliknuti na link hodi chybu 403 Pristup zakazan.

**Comment by motyc** [comment]
@jnihnat Nebylo by to lepší jako modal, ať to nevypadá, jen jako nějaká systémová hláška? Pokud je to komplikace, pak to takto jde, jen by mi to přišlo lepší - klasický modal s danou hláškou a možnostmi ano/ne.

Co se týče omezení, tak je to přesně tak, jak říkáte - zobrazovat to jen tehdy, pokud je projekt ve stavu P5 (uzavřen).

**Comment by jnihnat** [comment]
upraveno na modal:
![obrazek](https://user-images.githubusercontent.com/57906106/157448214-cb91b1c3-6c0a-48fb-acea-b5c65174e040.png)
vsetky texty budu editovatelne v translations. (title, text, tlacitla ano, ne) Pridana i kontrola na stav projektu.

**Comment by motyc** [comment]
https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201227215A
Kliknu na `Archivovat` a modal z dotazem má nulovou velikost: 
![image](https://user-images.githubusercontent.com/20186892/168135388-76d18b85-e16c-4ccc-a4ac-6a3dacf71113.png)
