### ISSUE TITLE
Při změně data ukončení projektu automaticky doplnit termín odevzdání NZ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#279]
Při změně data ukončení projektu automaticky doplnit termín odevzdání NZ (projekt.datum_odevzdani_NZ = projekt_datum_ukonceni + 3 roky).

**Comment by jnihnat** [comment]
Pridana logika:
- ak sa nezmeni termin_odevzdani_NZ a zaroven se zmeni termin_ukonceni -> nastavit termin_odevzdani_NZ = termin_ukonceni + 3 roky
