### ISSUE TITLE
Do akce doplnit tabulku Ostatní vedoucí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#282]
Doplnit tabulku Ostatní vedoucí (vedoucí + organizace; řešit jako nálezy u komponent).

V tabulce budou 2 sloupce Vedouci a Organizace a bude je mozne pridavat a odstranovat stejně jako nalezy u komponent.

Poloha tabulky viz https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1077257469

Na Detaile jenom zobrazeni, Editace zaznamu jen v edit mode.

**Comment by pesikj** [comment]
@motyc Ukládání má být prováděno do tabulky `akce_vedouci`?

**Comment by motyc** [comment]
@pesikj  Ano, přesně tak.

**Comment by motyc** [comment]
- [ ] - chybí nadpis "Další vedoucí"
- [ ] - povinná jsou obě pole (nelze mít vedoucího bez organizace)
- [ ] - nejde přidat více než jeden další vedoucí (neumím přidávat další řádky) - při editaci to jde obejít opakovaným otvíráním editace, ale při zápisu ani to ne; v případě této tabulky budeme asi potřebovat samostatné tlačítko pro přidávání řádků
- [ ] - v detailu se vypisují ID místo hesel (https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201233302A)
- [ ] - pokud vyplním jen organizaci, dostanu aplikaci do chybového stavu (podobně při vyplnění duplicitní hodnoty se zobrazení rozhodí):
![image](https://user-images.githubusercontent.com/20186892/171884886-1fe4ae5c-3859-4e17-80fe-50b9c966b2e1.png)

**Comment by pesikj** [comment]
@motyc A organizace i vedoucí jsou povinná pole?

**Comment by pesikj** [comment]
> * [ ]  - v detailu se vypisují ID místo hesel (https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201233302A)

@motyc Tohle se u mě neprojevuje, otestuji to po deploymentu nové verze na server.

**Comment by motyc** [comment]
@pesikj Hlavní vedoucí a organizace ve formuláři jsou povinná pro posun do A2, další vedoucí jsou "povinně volitelná" - tj. pokud chci přidat dalšího vedoucího, musím vyplnit oboje.

**Comment by pesikj** [comment]
@motyc OK, tak jsem to pochopil správně :-)

**Comment by pesikj** [comment]
@motyc Já detail vidím normálně, můžete dát konkrétní odkaz?

**Comment by motyc** [comment]
### Výsledek testu
Funkčně je již vše ok, jen dvě kosmetické drobnosti:
- [ ] záznamy se řadí jinak v detailu a při editaci - nevím, jaký je k tomu klíč, ale držel bych se pořadí při zadání (tj. asi řazení podle akce_vedouci.id)
- [ ] nadpis arch_z.create.dalsi_vedouci vybočuje z designu (navíc je přisazeno blíž k poli nad sebou, než k tomu, s čím souvisí); udělat stejně, jako máme oddělovače např. v http://192.168.254.30:8080/projekt/detail/C-202200019 (Přihlášení, Terénní část) - příště to specifikuji rovnou, nedošlo mi, že přesné zadání chybí (bral jsem to nějak automaticky)

**Comment by motyc** [comment]
### Výsledek testu
Stále je to problematické graficky. Je třeba se držet principů nastavených grafikem, i když na to už (bohužel) přímo nedohlíží. Nedostatky jsou zcela zjevné a je neudržitelné, pokud bychom toto měli korigovat vždy takto podrobně:
- [ ] Písmo popisků je bílé (není vidět - asi se stalo u všech obdobných tabulek)
![image](https://user-images.githubusercontent.com/20186892/181227269-55ebae28-f4b0-46ae-af85-fb1f5808b1b0.png)
- [ ] Tabulka zabíhá až do okraje nadřazeného div (dokonce jej přesahuje!), místo aby dodržovala nastavený padding
![image](https://user-images.githubusercontent.com/20186892/181227071-8bb12e3e-751b-4dde-b054-30c3364ebd22.png)
- [ ] Nadpis z neznámého důvodu nezařezává se zbytkem obsahu
![image](https://user-images.githubusercontent.com/20186892/181227938-941b17fd-ebc9-42e0-bffc-5f8ac0406bdb.png)

**Comment by motyc** [comment]
### Výsledky testu
- [ ] řazení je znovu náhodné/podle nejasného klíče (již řešeno viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/282#issuecomment-1185347166)
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-201233302A - chyba v grafice tabulky (čáry oddělující řádky zvláštně nelícují; asi souvisí se skrytím sloupce "Odstranit"):
![image](https://user-images.githubusercontent.com/20186892/182817986-22735792-8745-469a-b498-73a1bbe3ca7f.png)
- [ ] http://192.168.254.30:8080/arch-z/akce/zapsat/C-201233302 - obsahuje zbytečně prázdný sloupec "Odstranit":
![image](https://user-images.githubusercontent.com/20186892/182818280-b5c2391b-374d-41ee-b5c2-f67c5587e9ad.png)
