### ISSUE TITLE
Zvýraznit aktivní prvek v menu dokumentačních jednotek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#283]
V tabulce “Dokumentační jednotky” není patrné, kterou dokumentační jednotku či komponentu mám momentálně aktivní k editaci. Aktivní prvek vhodně zvýraznit.

**Comment by pesikj** [comment]
@motyc Může to být takhle

![image](https://user-images.githubusercontent.com/15179154/157536600-c348f41d-51ee-4d2c-9dbf-b2ad864f8fda.png)

**Comment by motyc** [comment]
@pesikj Ano

**Comment by pesikj** [comment]
@motyc OK. Barva je stejná jako v záhlaví, abych nepřidával další barvu na stránku (asi jste to poznal).

**Comment by motyc** [comment]
Ke zvýraznění prvku nedojde ve chvíli, kdy vytvořím nový - ve formuláři jej mám, ale v seznamu není označený (platí pro DJ i komponenty).

**Comment by pesikj** [comment]
Opraveno
