### ISSUE TITLE
Automatické předvyplnění aktivit podle volby areálu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#284]
Vazba bude definována v heslar_hierarchie

@motyc - dodat vzorová data (v původní DB patrně nejsou)

**Comment by jnihnat** [comment]
@motyc mate prosim uz ta vzorova data? Abychom to vedeli udelat? Pripadne to ma byt podobne jako u #285 ?

**Comment by motyc** [comment]
Tabulka dávno existuje, jen jsem ji zapomněl poslat (omlouvám se): [arealy_aktivity_210310.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/8630908/arealy_aktivity_210310.xlsx)

Řešení by mělo být totožné jako u #285, tj. obsah tabulky je třeba přenést na vztah v tabulce heslar_hierarchie. Asi by bylo dobré zařadit to přímo do migrací

**Comment by jnihnat** [comment]
@motyc pracuji akurat na insertu dat do tabulky, koukam akurat ze nektere arealy maji 2 aktivity jako vychozi. napriklad mesto ma aktivitu sidlistni i vyroba.
Je to jisto spravne? Pripadne ak jo, tak brat jako vychozi aktivitu podle poradi?

**Comment by motyc** [comment]
@jnihnat Ano, je to správně, vztah komponenta : aktivity je N:M (pole je multiselect)

**Comment by motyc** [comment]
Funguje to pouze při editaci, nikoli při zápisu nové komponenty.

**Comment by jnihnat** [comment]
doplneno i pro zapis. Doplnil som to i pro Knihovnu 3D, snad spravne.

**Comment by motyc** [comment]
@jnihnat Ano, dobrý postřeh, díky.

**Comment by motyc** [comment]
### Výsledek testu

https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201227322A
- [ ] Nefunguje při postupu: přejdu na akci -> vytvořím novou DJ -> chci přidat novou komponentu. Pokud povedu po vytvoření DJ refresh okna, funguje to dobře. Při editaci též v pořádku.
