### ISSUE TITLE
Nedoplňuje se výchozí specifikace u nálezů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#285]
Definováno vztahem v hesláři (heslar_hierarchie.typ = “výchozí hodnota”).

**Comment by jnihnat** [comment]
@motyc pokud se jedna o vychozi hodnotu, tak ta se bere pro heslo_nadrazene nebo heslo_podrazene?
momentalne pokud vyfiltruju vsechny specifikace a pak hledam pro ne vychozi hodnotu ve sloupci, tak ani u jednoho sloupce mi nevrati zadny prunik.

**Comment by motyc** [comment]
Přijde mi, že nefunguje. V https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201232019A zadám např. "zlomek keramiky nesp." a nic se nedoplní.

**Comment by jnihnat** [comment]
Doplneno na komponenty u Akce a 3D modelu

**Comment by motyc** [comment]
@jnihnat Ad objekty - to je v pořádku, u objektů vztah nejde predikovat.
