### ISSUE TITLE
Sloučení tlačítek na obrazovce akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#287]
Tlačítka “Upravit jednotku” (apod. pro komp., nálezy...) by se neměla opakovat

- [x] sloučit tlačítko pro uložení změn pro komponentu a nálezy, resp. pro DJ, ADB a VB (zkrátka pro děděné formuláře, které se zobrazují společně a souvisí spolu)
- [x] přejmenovat na “Uložit změny” (pokud půjde sloučit)

**Comment by motyc** [comment]
> Jan Ihnat 
> 7. prosince 2021 22:03
> Slo by o predelani vicero views do jedneho a tam to podminovat. K tomu se jeste vyuzivaji formsety s kterymi je praca obtiznejsi. Proto ten vyssi odhad.
> Tiez by som pridal button s pridavanim radku/odebranim pridaneho radku, aby se dalo najednou ulozit vice nalezu/predmetu, ak by byla takova pozadavka.

**Comment by pesikj** [comment]
@motyc Ano, chyba souvisí s #373 a formulářem a poli `northing` a `easting`.

**Comment by motyc** [comment]
Doporučoval bych se podívat v této souvislosti i na jeden bug evidovaný v #461, kdy dochází při uložení k samovolnému odpojení PIAN od první DJ.

**Comment by motyc** [comment]
Test musí počkat na opravu #373

**Comment by motyc** [comment]
Vracím k opravě. Není jasné, co způsobuje co, ale jako celek to nefunguje (viz #373 a #461) a komentáře výše.

**Comment by pesikj** [comment]
@motyc Můžete prosím aktualizovat odkaz na issue? #461 je uzavřené.

**Comment by motyc** [comment]
@pesikj Souvisejí s tím dílčí issue #522 a #527

**Comment by motyc** [comment]
Přesunuto z #286:
Pokud něco upravím ve formuláři DJ, ADB či VB a kliknu na uložit změny, vše zdánlivě proběhne dobře, ale po znovunačtení obrazovky jsou ve formuláři původní data před úpravou.

**Comment by pesikj** [comment]
@motyc Vyzkoušel jsem všechny tři formuláře a ve všech případech došlo k uložení informací a zobrazení úprav po znovunačtení stránky.

**Comment by motyc** [comment]
@pesikj Otestuji to tedy po nasazení nové verze, třeba se něco změnilo. Ráno to ale ještě na testu platilo.

**Comment by pesikj** [comment]
@motyc Nevím už, kam patří odpojování PIANu, ale je to opraveno.

**Comment by motyc** [comment]
@pesikj A šlo by tedy výchozí stav automaticky rozpoznat jako prázdný řádek? Jinak by to musel pokaždé mazat uživatel, což je neudržitelné a nesmírně nepraktické. Alternativou je, aby se výchozí souřadnice načetly až kliknutím uživatele na nějaké tlačítko a řádek by tak byl ve výchozím stavu prázdný.
