### ISSUE TITLE
PAS - úpravy spolupráce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#288]
- [x] Při žádosti o spolupráci a při deaktivaci spolupráce umožnit vepsat doplňující text, který se zobrazí v příslušném emailu a uloží do poznámky v historii.
- [x] Pokud se změní archeologovi oprávnění na badatele, nebo je spolupracující badatel deaktivován, deaktivovat související spolupráce v PAS.

**Comment by pesikj** [comment]
@motyc Chápu správně, že odeslání e-mailu zatím není implementováno?

**Comment by motyc** [comment]
@pesikj Ano, to budeme řešit spolu s #389
