### ISSUE TITLE
PAS - doplnit náhledy fotografií

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#289]
Doplnit náhledy fotografií do `/pas/vyber` (a odvozených obrazovek) ekvivalentně k zobrazení náhledů v modulu Dokumenty (http://192.168.254.30:8080/dokument/vyber).

V detailu nálezu se již náhledy zobrazují.

**Comment by pesikj** [comment]
Odhad: 2 hodiny.
