### ISSUE TITLE
PAS - umožnit vytvoření kopie existujícího záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#291]
Umožnit vytvoření kopie existujícího záznamu - data ze záznamu se propíšou do nového okna  http://192.168.254.30:8080/pas/zapsat, následuje již standardní postup.

Funkci není třeba omezovat podle stavu. Bude součástí menu “Další volby”.

**Comment by pesikj** [comment]
@motyc Takže nemá jít o kopii záznamu v databázi, ale předvyplnění formuláře?

**Comment by motyc** [comment]
Ano, je to tak. Staci predvyplnit

**Comment by pesikj** [comment]
@motyc Mají být součástí i fotografie?

**Comment by motyc** [comment]
@pesikj Nene, jen data ve formuláři

**Comment by pesikj** [comment]
V rámci převodu na class-based views je nutné znovu testovat zápis PAS pro všechny varianty.

**Comment by motyc** [comment]
### Test v1.0.13-rc1
https://amcr-test.aiscr.cz/pas/zapsat vrátí 500

**Comment by motyc** [comment]
### Test v1.0.13-rc9
Funguje to pěkně, jen jedna drobnost:
- [ ] kopírují se i údaje v části "Uložení". Ty z původního záznamu nepřenášet a nechat výchozí stav. Kopírovat jen to, co je v části detail, tj. ve viditelných polích na stránce zápisu.
