### ISSUE TITLE
Doplnit nástroj pro vyhledávání polohy podle geonames

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#293]
Řešení:
Geonames pro obce a okresy dostupná na všech mapach
- Uživatel musí zadat min 3 znak
- Zobrazi se list box nabidkou max 6ti nazvu
- Uzivatel klikne a je presmerovan na misto na mape =definicno bod bod obce/okresu
- pro okresy se pouzije fixni meritko X, pro obce fixni meritko Y
- pri presmerovani na misto se nezobrazi docasny pin pro def. bod ani se nezvyrazni obvod objektu

### Realizace
Zasažené stránky:
- amcr/pas/create SN
- amcr/pas/detail/X
- amcr/pas/edit/X
- amcr/projkety/create Projekty
- amcr/projkety/detail/X
- amcr/projkety/edit/X
- amcr/dokumenty/create Knihovna 3D
- amcr/dokumenty/detail/X
- amcr/dokumenty/edit/X
- amcr/arch_z/detail/X Piany

**Comment by jiri-bartos-huld** [comment]
Prvni nastrel:
1./Vyhledavaci tlacitkko vmape
![obrazek](https://user-images.githubusercontent.com/77389730/190017848-80df7ce6-b6a2-487a-8815-8b86550bcff7.png)
2./Vyhledavani Ibce+Okresy(ty jsou navrchu)
![obrazek](https://user-images.githubusercontent.com/77389730/190017751-df9cb6e3-2332-4998-849f-7d53e5db8b4a.png)

**Comment by motyc** [comment]
@jiri-bartos-huld To vypadá bez problémů. Jen bych ho možná dával hned pod / vedle (?) tlačítek pro zoom, protože také bude všude a bude často užívané...

**Comment by jiri-bartos-huld** [comment]
Vyhledavaci button jsem dal primo pod vyhledavani (melo by byt samostatne kvuli rozbalovani) melo by byt pouze jedna rada (full screen na tabletu/mob. by mohl byt problem). 
![obrazek](https://user-images.githubusercontent.com/77389730/191283447-6e4f4484-9462-4e0c-b3c5-4aae5482cfe6.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Rozumím, díky.

**Comment by jiri-bartos-huld** [comment]
@pesikj pripraveno na MR https://github.com/ARUP-CAS/aiscr-webamcr/pull/694

**Comment by motyc** [comment]
### Výsledek testu
Testuji na http://192.168.254.30:8080/oznameni/, ale platí všude:
- [ ] Chování je nevyzpytatelné:
1) Hledám pojem "blansko" -> najde se "Blansko (Jihomoravský kraj)" a "Blansko (Blansko)" -> kliknu na "Blansko (Jihomoravský kraj)" -> dojde k zoomu na celý okres **(OK)**
2) Smažu obsah pole a znovu hledám "blansko" -> najde se "Blansko (Jihomoravský kraj)" a "Blansko (Blansko)" -> kliknu na "Blansko (Blansko)" -> zazoomuje se na nějaké podivné místo **(CHYBA)** 
![image](https://user-images.githubusercontent.com/20186892/203576231-2f948b95-a106-44c7-a612-aa8101d35607.png)
3) Udělám znovu totéž, co v kroku 2 znovu -> objeví se správný výřez **(OK)**
4) Aktualizuji celé okno -> zadám a vyberu Velká Dobrá (Kladno) -> výřez je opět úplně nesmyslný **(CHYBA)**
![image](https://user-images.githubusercontent.com/20186892/203579680-ffb9177f-b123-42c7-9600-6c35374645f7.png)
- [ ] Jaké přesně je to nastavení úrovní hledání, resp. z čeho se vyhledává? Chápal jsem to tak, že podle obcí najdu např. i jednotlivé menší osady, tj. půjde hledat podrobněji než podle katastrů. Nyní to tak úplně nevypadá. Např. na mapě níže nenajdu "Mechov". Nejde tam zvolit takový heslář, aby to našlo i tyto sídelní jednotky?
![image](https://user-images.githubusercontent.com/20186892/203578181-2e170a11-9ee9-46ad-a884-c02cad2b8809.png)
- [ ] Zoom pro okresy je v pořádku. Zoom při vyhledání obce bych nastavil o něco více oddálený, cca takto:
![image](https://user-images.githubusercontent.com/20186892/203578787-22620ad1-1b04-4efe-9412-932ac63cd121.png)

**Comment by jiri-bartos-huld** [comment]
@motyc 

1./Opraveno
2./Neni chyba: Mechov neni obec ale vesnicka v casti obce Otrocin. Vyhledavani bylo dohodnuto podle zabaged vrstvy obce a okresy, my se primo ptame na vrtsvy 12,15
![obrazek](https://user-images.githubusercontent.com/77389730/204595900-b124d616-8dad-43db-961a-4ee86f53927a.png)
3./Opraveno-uznavam ted je to hezci

**Comment by motyc** [comment]
@jiri-bartos-huld
ad 2 - Neříkám, že je to nutně "chyba", ale spíše nedorozumění v tom, co jsme tím mysleli. Je někde seznam vrstev, které takto jde v našeptávači použít? A jak velký problém (jak je časově náročné) vrstvu přidat či vyměnit?

**Comment by jiri-bartos-huld** [comment]
@motyc 
Urcite neni problem pridat vrstvu, ale
1./Pokud bude vrstev vice tak by to chtelo omezit v cem se ma hledat [rozklikavaci menu se sipku]
2./Mozna by chtel uzivatel sve nastaveni ulozit, nekdy chteji uzivatele ukladat jinak vyhledavani pro akce a jinak pro samostatne nalezy,...
3./Tech moznych vrstev je docela hodne-nekdy se pouzivaji podkomponenty pro rozsirene hledani: pro "mechov" muzete dostat cast obce: Mechova, Mechov vesnici ale i Novy Samechov

Prosim podivejte se na:
https://ags.cuzk.cz/geoprohlizec/

![obrazek](https://user-images.githubusercontent.com/77389730/204622894-9497f30a-289e-4e8a-83fa-789cc0b57675.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Děkuji moc za rozobor:
ad 1 - to menu na šipku je dobré řešení; pokud to není problém, jsem pro to přidat teď, pokud je to spíše na další objednávku, tak pro to udělám nové issue a zařadíme to podle možností;
ad 2 - to by asi bylo fajn rozšíření, ale zatím bych toto neřešil; doplnit to můžeme až po nějaké lepší zkušenost s chováním a způsobem užívání v praxi;
ad 3 - po otestování na ČÚZK by ideální bylo vyměnit vrstvu "Obce" za vrstvu "Geonames", což by vyřešilo vše potřebné - pokud to není problém, prosím to udělejte rovnou...

**Comment by pesikj** [comment]
@motyc Můžeme tedy tento požadavek přesunout do implemented s tím, že nová funkcionalita bude zadána jako nové issue?

**Comment by motyc** [comment]
@pesikj Z odpovědi @jiri-bartos-huld mi není jasné, zda řešení pro bod 3 je jen úprava konfigurace, či něco složitějšího; pokud je to jen konfigurace, prosím o úpravu rovnou (lépe se to bude testovat) a pro zbytek bych udělal issue. Ok?

Jinak je ale potřeba ještě v rámci tohoto issue nasadit a otestovat opravy zbylých bodů podle https://github.com/ARUP-CAS/aiscr-webamcr/issues/293#issuecomment-1325220207

**Comment by jiri-bartos-huld** [comment]
@pesikj @motyc 
Dobry den, prosim o zadani noveho pozadavku na Geonames, protoze to neni jen uprava konfigurace, obecne lze rici, ze obce a okresy se chovaji odlisne nez Adresy,Geonames...

**Comment by sedmar** [comment]
@motyc Můžeme tedy přistoupit k testování tohoto požadavku, případně pak k jeho akceptaci stím, že dodatečná funkcionalita neobjednaná zde bude řešeno v návazném issue jako nový požadavek na vývoj?

**Comment by motyc** [comment]
@sedmar Ano. Až bude nasazeno, otestuji opravy a doplňující issue udělám jako nové požadavky.
