### ISSUE TITLE
Mapový podklad - katastrální území z AMČR

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#295]
AMČR - Katastrální území - nutno vytvořit interní WMS a tu zobrazovat

**Comment by jiri-bartos-huld** [comment]
Podklad bude zpracovan jako vektorova liniova kresba  bez uprav generalizace=linie vsech kat. uzemi budou spojeny a poskytnuty pro vsechna meritka. Neni mozne realizovat jako WMS, protoze zde by byl potreba geoserver  http://geoserver.org/. Generalizace je vynechana protoze https://postgis.net/docs/ST_Simplify.html neni schopno poskytnout stejnou generalizaci spolecne hranice pro sousedni katastry. @motyc

**Comment by motyc** [comment]
@jiri-bartos-huld Navržené řešení není úplně špatné, ale nebude příliš systémově náročné na načítání dat?

Asi se prosím věnujte zejména issues, které jsou nejsou označené "ARU - need processing", kde víme, že je nějaký krok nutný na naší straně. Provozujeme ESRI ArcGIS server, kde jsme schopni WMS případně zprovoznit.

**Comment by motyc** [comment]
Vyřešíme používáním aktuálních dat RUIAN - zavírám jako nerelevantní.
