### ISSUE TITLE
Uživatelský import geometrie PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#298]
- [x] umožnit snadný import jednoho geoprvku - bude řešeno jako volba "Importovat PIAN" v menu u dokumentačních jednotek (pravidla pro oprávnění stejná jako při zápisu nového PIAN)
- [x] importní soubor bude typu CSV se sloupci:
- `label` - uživatelské označení geoprvku
- `epsg` - označení souřadnicového systému, přípustné hodnoty 4326 (5514 doplníme v budoucnu, až bude podporovat i mapa)
- `geometry` - geometrie ve formátu WKT (přípustné point, polyline a polygon)
- [x] obsah souboru bude jedna nebo více geometrií, ze kterých si při importu vyberu ze seznamu podle `label`
- [x] po přidání se otevře formulář s volbou přesnosti a možností uložení + se geometrie zobrazí v mapě (jako bych ji naklikal ručně), kde ji mohu upravit standardními nástroji
(dále již aplikujeme standardní postup)

Pro usnadnění přípravy na straně uživatelů ARÚ zajistí vytvoření exportního pluginu pro QGIS (není součástí zadání).

**Comment by motyc** [comment]
@jiri-bartos-huld Děkuji za zpětnou vazbu. Toto issue musíme ještě lépe prodiskutovat interně. Prosím odhady zatím nedělejte. V kontextu napsaného revidujeme zadání a ozveme se. Nejde o něco zařazeného do stávající objednávky, zdržení zde tedy nehrozí.

**Comment by motyc** [comment]
Změnit zadání v tomto smyslu:
- umožnit snadný import jednoho geoprvku
- importní soubor ve formátu (vybrat) WKT, GeoJSON, GML (pro usnadnění přípravy můžeme udělat plugin pro QGIS)
- obsah souboru bude jedna nebo více geometrií, ze kterých si vyberu
- po přidání se geometrie zobrazí v mapě, kde ji mohu upravit standardními nástroji
- pro uložení je třeba zvolit přesnost (atd.) - dále již standardní postup

**Comment by motyc** [comment]
Zadání kompletně přepracováno a původní přístup nahrazen jiným, vhodnějším řešením.

**Comment by jiri-bartos-huld** [comment]
@motyc prosim o zodpovezeni dotazu, kolik dat pocitame, ze bude v souboru? Pokud to bude malo, muzeme pouzit modalni dialog, ale kdyz budou stovky geometrii, tak musime resit jinak.

**Comment by motyc** [comment]
@jiri-bartos-huld Otázka je, co znamená málo. Obecně si myslím, že většinou jich budou max. desítky, výjimečně stovky. Lze k tomu ale dát buď nějaké omezení, nebo doporučení pro uživatele, pokud by to věci komplikovalo. V čem přesněji je ten limit?

**Comment by pesikj** [comment]
@motyc Podle mě by bylo schůdné v modal okně zobrazit tak 10 až 20 záznamů. Pokud jich má být více, byla by lepší samostatná stránka.

**Comment by motyc** [comment]
Teď jsme to ještě s @pesikj probírali po telefonu a má představa byla taková, že by se v modal okně zobrazilo pole s drop-down listem, do kterého by se na četly všechny položky z tabulky ze sloupce nadepsaného `label` a nic dalšího. Ze seznamu by šlo normálně vybrat jednu položku (chování stejné, jako máme všude, tj. s možností vyhledávání podřetězců v rámci seznamu labelů). K ní by se pak po potvrzení načetla do mapy geometrie (sloupec `geometry`). V tomto případě mám pocit, že na počtu řádků víceméně nesejde, protože ten rozbalovací seznam jich snese poměrně hodně.

K tomu mne napadá:
- bylo by dobré po načtení validovat, že tabulka obsahuje všechny sloupce podle zadání (`label`, `epsg`, `geometry`) a vlastně vůbec nemusíme řešit, zda budou v tabulce i nějaké další nebo ne
- také prosím pozor na to, že je třeba zkontrolovat validitu obsahu sloupce geometrie, abychom nenačítali nějaké nesmysly, např. zapsané ve špatné syntaxi
- měli bychom uživatele upozornit na to, pokud v `label` budou duplicitní označení (vícekrát stejná hodnota), protože jinak bude výběr nejednoznačný

**Comment by jiri-bartos-huld** [comment]
Ukazka bez prepisu geometrie:
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/aa3f04b1-3e94-4267-9548-34e43b764cff)

Ukazka s prepisem geometrie & labelu:

http://localhost:8000/arch-z/akce/detail/C-202211987A/dj/C-202211987A-D02/pian/edit/N-1142-000000013?label=moje&geometry=POLYGON%20((13.2164736%2049.9596986,13.2154006%2049.9589111,13.2178685%2049.9583378,13.2183513%2049.9593602,13.2164736%2049.9596986))

![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/32b5c630-b9ad-464b-a8de-27640ef08d76)

**Comment by jiri-bartos-huld** [comment]
@jnihnat @pesikj 
1./prosim kouknte na https://github.com/ARUP-CAS/aiscr-webamcr/pull/1264 je tam implementovana funkcionalita popsana v prispevku nahore
2./Nyni zbyva vytvorit to tlacitko na nahrani tabulky a vyberu radku (myslim, ze je dohodnuto, ze tohle bud delat @jnihnat)
Pote co se vybere radek v CSV tak staci presmerovat na stranku:
/arch-z/akce/detail/C-202211987A/dj/{{DJ_ID}}/pian/edit/{{PIAN_ID}}?label={{label}}&geometry={{WKTgemetrie}}

**Comment by jiri-bartos-huld** [comment]
@jnihnat prosim rozmysli dialog

**Comment by jnihnat** [comment]
@jiri-bartos-huld pripravene pro tebe #1287.

**Comment by jiri-bartos-huld** [comment]
@pesikj @jnihnat dodelal jsem fce pro validaci epsg (vraci True/False)/geometrie(vraci pole[True/False, "duvod"] prosim muzete donapojit. Na vstupu je vzdy string (krom epsg kde to zvladne i cislo)

pozuziti je jednoduche:

print(file_validate_epsg("4326"))
print(file_validate_epsg("4326a"))
print(file_validate_epsg(4326))
print("geometry---")
print("geometry---")
print(file_validate_geometry("multi (10 20)"))
print(file_validate_geometry("point (10 20)"))
print(file_validate_geometry("point (10 20 55 a)"))
print("---line")
print(file_validate_geometry("LINESTRING ()"))
print(file_validate_geometry("LINESTRING (30 10, 10 30, 40 40)"))
print(file_validate_geometry("LINESTRING (30 10, 10 30, 40 a)"))
print("polygon---")
print(file_validate_geometry("POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))"))

**Comment by motyc** [comment]
@pesikj Rád bych otestoval, ale nikde nevidím volbu, jak PIAN importovat. Čekal bych ji v menu dokumentační jednotky bez PIAN, tam ale není: http://192.168.254.30:8080/arch-z/akce/detail/C-9723779A/dj/C-9723779A-D02

**Comment by jnihnat** [comment]
@motyc a @jiri-bartos-huld tu doslo asi k nejakemu nedorozumeni, Jirka to udelal na pian/edit:
/arch-z/akce/detail/C-202211987A/dj/{{DJ_ID}}/pian/edit/{{PIAN_ID}}?label={{label}}&geometry={{WKTgemetrie}}
Podle p. Novaka to ma byt asi na:
/arch-z/akce/detail/<str:ident_cely>/dj/<str:dj_ident_cely>/pian/zapsat
@jiri-bartos-huld muzes predelat svoji cast? Ja upravim pak Django cast, bude to mala drobnost.

**Comment by motyc** [comment]
@jnihnat A jak se to u toho editu chová? Pokud je možno importem nahradit stávající geometrii PIAN, tak to není špatná funkce, ale určitě to potřebujeme i pro zápis nového, kde to bude užívané mnohem častěji.

**Comment by motyc** [comment]
@jnihnat Do URLs jsem doplnil pro import PIAN akce `pian_import_new` a `pian_import_change`

**Comment by jiri-bartos-huld** [comment]
@jnihnat @
Mluvil jsem s @motyc a dohodli jsme se, ze by melo byt pridano tlacitko do menu pod mapu:
1./Podminka zobrazeni talcitka pokud dj nema zadny pian
2./Pri zmacknuti tlacitka by pak stacilo nacist tabulku, vybrat pian a pak presmerovat na stranku:

arch-z/akce/detail/C-202300521A/dj/C-202300521A-D02/pian/zapsat?geometry=POLYGON%20((13.2164736%2049.9596986,13.2154006%2049.9589111,13.2178685%2049.9583378,13.2183513%2049.9593602,13.2164736%2049.9596986))&label=moje

vse by pak melo fungovat

**Comment by jnihnat** [comment]
dodelano v #1338
Musel som uprit i odkud tahame "context" pro lokality a zjednotit to s akci at to nemame na dvou mistech. Prosim pro jistotu teda proklikat lokalitu i akci s DJ/komponentami.
@pesikj - FYI

**Comment by motyc** [comment]
Nelze testovat kvůli #1342

**Comment by motyc** [comment]
### Test v0.3.5z32
Při pokusu o upload CSV se zobrazí hláška o úspěchu, ale soubor zase zmizí a modal se vyprázdní, jako bych tam žádný soubor nevložil. Je úplně jedno, zda to zkouším pro nový PIAN, nebo pro aktualizaci, stejně jako v jaké části aplikace to dělám.

**Comment by jnihnat** [comment]
za mne opravy a vylepseni v #1351
dostanu se uz na zapsat a edit s danou geometrii a vsak po ulozeni se neulozi, protoze se nic do requestu neposle:
{
	"csrfmiddlewaretoken": "mZ3EQgU5CERhTXVCTxyAuJx1jjP7U2mJCn0bRCEFizXJUNub9e0zhXC58wjYQVlV",
	"presnost": "861",
	"geom": "",
	"geom_sjtsk": "",
	"geom_system": "4326",
	"dj_ident_cely": "C-9108572A-D01"
}

@jiri-bartos-huld kouknes na tohle ty, nebo mam ja?

**Comment by motyc** [comment]
@jiri-bartos-huld Ještě mě napadá jedno úskalí daného řešení, a to že pokud budeme geometrii posílat přes GET, tak u velkých geometrií můžeme teoreticky přesáhnout maximální délku URL (2000 znaků) a nebude to fungovat. Navrhoval bych tedy upravit z GET na POST.

**Comment by jiri-bartos-huld** [comment]
@jnihnat  koukneme na to spolu-na callu
@motyc omezeni je jen pro MS Edge ostatni problem nemaji. Jednoduzse zapsat to do body a vyzvednout si to pres JS nepujde, pokud to budeme chtit resit tak POST na python z neho naplnit django promenou, tu nacpat do javascript promnene a z ni cist. Neco cookies. Ale obe metody nas pripravy o refresh F5, po nem geometrie zmizi.

**Comment by jiri-bartos-huld** [comment]
@pesikj @motyc @jnihnat 
1./Neukladani opraveno-pujde na MR spolu s prechodem na x1,x2 souradnice
2./Obejit omezeni na 2000 znaku @jnihnat navrhl pomoci redisu, @pesikj prosimmuzes dohodnout at je to samostatny task

**Comment by motyc** [comment]
### Test v0.3.5z61
- [ ] Import již funguje, nicméně je tam nějaká chyba v přesměrování u nově zakládaných PIAN (při editaci je to ok). Po tom, co dám uložit změny, tak se PIAN v pořádku vytvoří, ale vyskočí na mne:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/1fb640b1-aaf3-418e-85de-5714445ae44b)
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9723785A/dj/C-9723785A-D03/pian/edit/N-0143-000000064?label=test&geometry=POLYGON((14.211083185030288%2050.779374233416775,14.211080850734076%2050.77934618950885,14.2111053608443%2050.77934618950885,14.211108862288619%2050.779372019424656,14.211083185030288%2050.779374233416775)) - výchozí zoom je nějaký zvláštní, je to hodně oddálené a nevím proč
- [ ] Import ověřuje validitu geometrie při načítání tabulky pouze nějak částečně, takže mohu zkusit vložit zcela nevalidní prvky (např. http://192.168.254.30:8080/arch-z/akce/detail/C-9723785A/dj/C-9723785A-D03/pian/zapsat?label=test&geometry=LIN(12.81972271691689%2050.4) a aplikace to nijak neodchytí. Mělo by se to ověřit ve výběrové tabulce i při načtení mapy, protože do URL se geometrie může teoreticky dostat i jinak.
- [ ] Bude třeba oddělit hlášku `pian.views.importovatPianView.check.wrongEpsg` pro situaci, kdy je chybné záhlaví sloupce a kdy je chybný obsah sloupce (EPSG není 4326). Chybovou hlášku jinak nejde smysluplně univerzálně nastavit, protože pokaždé je třeba sdělit něco jiného. Ekvivalentně pak platí pro pian.views.importovatPianView.check.wrongGeometry.
- [ ] Když label nechám v CSV prázdný, dostanu neodchycenou chybu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/02840ea3-086c-49cf-80e5-614dbf4765b9)
- [ ] Když má CSV nevalidní syntaxi (např. neodpovídá počet sloupců u jednoho řádku), dostanu neodchycenou chybu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5466c5bf-fa80-4da7-bef1-2b1e9aeb21fa)
- [ ] Hodně zde zlobí i ten výchozí zoom, jak je ale již podchyceno v https://github.com/ARUP-CAS/aiscr-webamcr/issues/1047#issuecomment-1854433241 (někdy zazoomuje, někdy ne, někdy až napodruhé...)

**Comment by pesikj** [comment]
@motyc Můžete mi prosím poslat soubory, se kterými jste prováděl testování?

**Comment by motyc** [comment]
@pesikj Stále to zkouším na této, ale dělal jsem do ní ad hoc zásahy, abych nasimuloval ty různé zmíněné situace: https://github.com/ARUP-CAS/aiscr-webamcr/files/13392968/PIAN_import_test.csv

**Comment by pesikj** [comment]
@motyc Včera bylo domluveno, že validaci souřadnic si převezmete vy. Funkce pro validaci je zde:

Funkce je ve skriptu `webclient/core/utils.py`, název funkce `file_validate_geometry`.

**Comment by motyc** [comment]
@jhavrlant Honzo, to je tedy prosím na Tebe (https://github.com/ARUP-CAS/aiscr-webamcr/issues/298#issuecomment-1896440026).

**Comment by pesikj** [comment]
@motyc Prosím o doplnění informace, zda body týkající se validace souboru jsou již v pořádku.

**Comment by motyc** [comment]
### Test v0.3.5z119
- [ ] Ověření validity geometrií již ok, jen je třeba doplnit validaci i pro samotný GET request, jak posledně dohodnuto.
- [ ] Když u některého záznamu pole `label` nebo `geometry` prázdné v CSV, dostanu neodchycenou chybu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/02840ea3-086c-49cf-80e5-614dbf4765b9)
- [ ] Klíč není v Rossettě:
-- `pian.views.importovatPianView.check.no_data`
-- `pian.views.importovatPianView.check.wrongColumnName`

**Comment by motyc** [comment]
### Test v0.4.14
- [ ] Ověření validity geometrií již ok, jen je třeba doplnit validaci i pro samotný GET request, jak posledně dohodnuto. _- Žádná změna. Systém akceptuje i zcela nesmyslné get requesty (např.: http://192.168.254.24:8080/arch-z/akce/detail/X-M-9000000038A/dj/X-M-9000000038A-D02/pian/zapsat?label=Test16&geometry=POINT((13.971922485202075 )_
- [ ] Když u některého záznamu pole `geometry` prázdné v CSV, dostanu neodchycenou chybu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/82f8c011-4e88-4eef-a3d0-36c1c59ffb17)

Mapa je teď celkově rozbitá kvůli #1619, což může test ovlivňovat.

**Comment by motyc** [comment]
Zdá se, že úprava od @pesikj nyní blokuje vracení akcí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/4eeccb46-3b99-4c7c-8915-006f3d2fa83c)

Vlastně ani nevím, proč se v danou chvíli http://192.168.254.30:8080/pian/validovat-geometrii/ volá, ale každopádně vrací error 500 a akce nejde vrátit (test na http://192.168.254.30:8080/arch-z/akce/detail/M-9101236A).
