### ISSUE TITLE
Upravit datové vrstvy - projekty

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#299]
Upravit datové vrstvy pro dílčí užití mapy (**tučně** - defaultně zapnuté)
- [x] 1 - **Lokalizace projektu** (aktivní vrstva)
- [x] 2 - **Projekty - zapsané** (P1; geom z projektu)
- [x] 3 - **Projekty - přihlášené** (P2; geom z projektu)
- [x] 4 - **Projekty - běžící** (P3; geom z projektu)
- [x] 5 - Projekty - realizované (P4-P6; geom z projektu)
- [x] 6 - Projekty - zrušené (P7-P8; geom z projektu)
- [x] 7 - **Samostatné nálezy projektu** (SN připojené k danému projektu; geom z nálezu; zohlednit přístupnost a vlastnictví - viz #379); nikdy se negeneruje heatmapa
- [x] 8 - **PIAN projektu** (PIAN připojené k akcím daného projektu; geom z PIAN; zohlednit přístupnost a vlastnictví - viz #379); nikdy se negeneruje heatmapa

Rozsah dat:
1: def. bod aktivního projektu
2-6: vždy všechny projekty v DB (podle daných kritérií)
7: Pouze SN projektu s přístupností + vlastnictvím pro daného uživatele
8: Pouze PIANy projektu s přístupností + vlastnictvím pro daného uživatele

Caching:
Bude aplikován caching pro vrstvy na úrovni 7+8, tj. jeden request pro každou vrstvu pouze při načtení stránky důvodem je řešení přístupnosti a vlastnictví.

Clustering:
Pokud počet prvku v aktivních vrstvách (2-8) dohromady přesáhne 500, pak se pro všechny vrstvy dohromady ma aplikovat clustering a detailní geometrie ma byt pro tyto vrstvy vypnuta.
Clustering zapnout též tehdy pokud prvků je méně než 500, ale mapa má velmi malé měřítko. Jde o to, ze do 500 máme zobrazovat primo detailní data bez clusteringu. Pakliže zobrazím celou mapu CR a PP+SNP budou mít řekneme 5 geometrii tak bych je mel podle současných pravidel zobrazit jako detailní geometrie (bez moznosti clusteringu). To nove pravidlo řekne, ze clustering je možný od určitého meřítka. Tedy pokud ma projekt 4 geometrie v Praze a 1 geometrii v Brně a jednu v Ostravě, tak podle stare definice se při zobrazeni cele CR ma vše zobrazit jako body/geometrie. Podle nového bude možné zobrazit pražský cluster + samostatnou geometrii pro Brno a Ostravu.

Heatmapa:
Používá se pouze jedna heatmapa a to pro vrstvy 2-6, ta se zobrazí podle obecných pravidel (viz #302)

Zasažené stránky:
amcr/projekt/create
amcr/projekt/detail/X
amcr/projekt/edit/X

**Comment by jiri-bartos-huld** [comment]
@motyc Prosim o doplneni, toto velmi ovlivni cenu tasku
1. V Projektech se pri velkem "zmenseni"(treba zobrazeni cele CR) pracuje s HeatMapou. Jak by se mela mapa chovat nyni?
- [ ]  Kazda vrstva projektu ma heatmapu
- [ ]  Vsechny vrstvy projektu maji spolecnou heatmapu
- [ ]  "Pian projektu" obsahuje pouze PIANY aktivniho projektu s tim, ze je zde navic potreba vyresit pristupnost a vlastnictvi
- [ ]  Vrstva pianu ma podorovat Heatmapu/clustering -Heatmapa urcite nebude mozne kvuli pristupnosti a vlastnictvi
- [ ]  Vrstva "SamNalezu projektu" obsahuje SN projektu s pristupnosti a vlastnictvim
- [ ]  Ma vrstva SN mit heatmapu/clustering?
- [ ]  Pokud ma byt zobrazeno vice vrstev s heatmapou ma byt vysledna heatmapa sloucena?
2. Jaky je ocekavana max. pocet SamNalezu a PIANu v projektu
Pokud cca do 1000: bude mozne cachovani, vypocet prostupnosti a vlastnictvi se provede jednou a pak bude platny po cele zobrazeni stranky?

**Comment by jiri-bartos-huld** [comment]
@motyc 
- [ ]  clustering pro projekty: Pokud mam zobrazene "zapsane" a "bezici" ma byt clustering spolecny/slouceny pro obe vrstvy?
- [ ] heatmapa pro projekty: Pokud mam zobrazene "zapsane" a "bezici" ma byt clustering spolecny pro obe vrstvy nebo pro vsechny vrstvy?
3. Jaka jsou pravidla pro clustering  mezi jednotlivymi vrstvami SamNalez x Projekt x PIAN?
4. Jaka jsou pravidla pro zobrazeni geometrie/def. bodu/HeatMapy SamNalezu

**Comment by motyc** [comment]
@jiri-bartos-huld
ad 1
- zaškrtal jsem možnosti
- v principu nepotřebujeme heatmapu tam, kde nehrozí velké množství záznamů, tj. v tomto issue není třeba vůbec (10.000 záznamů v praxi nejde přesáhnout pro jeden projekt)
- pro samostatné nálezy by měl stačit clustering, heatmapa by není potřeba - v bodu je to ale sloučené, tak jsem jej zaškrtnul
- sloučení heatmapy prvků různých typů není relevantní, ale dobré by bylo sloučení clusterů, pokud to jde (případně prosím o informaci, zda je to nějak komplikované/problematické)
- pro projekty v různém stavu clustery/heatmapu sloučit

ad 2
- PIAN - obvykle to jsou jednotky, v některých případech desítky, naprosté maximum je 999
- sam. nálezy - zde to nejde snadno odhadovat, může to být i přes 1000, ale rozhodně to neplatí nyní a vývoj nejde úplně predikovat; je to ale spíš málo pravděpodobné

U toho cachování nedokážu dohlédnout důsledky, ale jak píšu výše, těch záznamů obvykle tolik nebude.

ad 3 - sloučit
ad 4 - stejná jako v #302

**Comment by jiri-bartos-huld** [comment]
@motyc  Prosim o kontrolu a odsouhlaseni, chtel bych takto "napevno" definovat zadani, ty otazky pomohly k pochopeni a sestaveni techto bodu ale bude lepsi zadani prepsat aby vse bylo na jednom seznamu:
Pokusim se tedy zadani sumarizovat:

Pozadovane vrstvy jsou:
LP: Lokalizace projektu (aktivní vrstva) 
L1: Projekty - zapsané (P1; geom z projektu)
L2: Projekty - přihlášené (P2; geom z projektu)
L3: Projekty - běžící (P3; geom z projektu)
L4: Projekty - realizované (P4-P6; geom z projektu)
L5: Projekty - zrušené (P8; geom z projektu)
PP: PIAN projektu (geom z PIAN; zohlednit přístupnost a vlastnictví)
SNP: Samostatné nálezy projektu (geom z nálezu; zohlednit přístupnost a vlastnictví)

Rozsah dat:
LP: def. bod aktivniho projektu
L1-L5: vzdy vsechny projekty v DB
PP: Pouze PIANy projektu s pristupnosti+vlastnictvim pro daneho uzavatele
SNP: Pouze SN projektu s pristupnosti+vlastnictvim pro daneho uzavatele

Caching: Bude aplikovan caching pro vrstvy na urovni PP+SNP, tj. jeden request pro kazdou vrstvu pouze pri nacteni stranky duvodem je reseni pristupnosti a vlastnictvi.

Clustering:
1./ Pokud pocet prvku v aktivnich vrstvach (L1-L5,PP,SNP) dohromady presahne 500, pak se pro vsechny vrstvy dohromady ma aplikovat clustering a detailni geometrie ma byt pro tyto vrstvy vypnuta

Heatmapa: 
1./Pouziva se pouze jedna heatmapa a to pro vrtsvy L1-L5, ta se zobrazi pokud pocet aktivnich L1-L5 bude vetsi nez 5.000

Je potreba  jeste vyresit jeden atyp:
/Pokud uzivatel aktivuje vsechny vrstvy a da zobrazit celou CR, pak se mu zobrazi 
a.HeatMapa pro L1-L5. 
b.LP jako geometrie+def. bod. 
c.PP+SNP budto jako geometrie s def. bodem nebo jako clustery (pokud je geom>500). 

Je potreba rozhodnout bod c. kdy se maji PP+SNP, prestoze jich je mene nez 500, zobrazit jako clustery. Navrhuji definovat fixni zoom(stanovime meritko) pri nemz dojde k nasilnemu prepnuti na clustery

**Comment by motyc** [comment]
- `PP: Pouze PIANy projektu s pristupnosti+vlastnictvim pro daneho uzavatele` - tady to je to spíše přístupností nebo vlastnictvím (PIAN vidím, pokud je pro mou roli veřejný, nebo pokud jej vytvořil někdo z mé organizace); dtto pro SNP (vlastnictví = nález patří k projektu mé organizace)
- `1./Pouziva se pouze jedna heatmapa a to pro vrtsvy L1-L5, ta se zobrazi pokud pocet aktivnich L1-L5 bude vetsi nez 5.000` - limit pro heatmapu máme myslím 10.000 (nebo se to změnilo?)
- `Je potreba rozhodnout bod c.` - a kvůli čemu je třeba vynucovat ten clustering? Asi to není velký problém, ale je otázka, zda je to nutné...

**Comment by jiri-bartos-huld** [comment]
add c: Spatne to chapete(mozna jsem to spatne napsal), jde o to, ze do 500 mame zobrazovat primo detailni data bez clusteringu. Paklize zobrazim celou mapu CR a PP+SNP budou mit rekneme 5 geometrii tak bych je mel podle soucasnych pravidel zobrazit jako detailni geometrie (bez moznosti clusteringu). To nove pravidlo rekne,  ze clustering je mozny od urciteho meritka. Tedy pokud ma projekt 4 geometrie v Praze a 1 geometrii v Brne a jednu v Ostrave, tak podle stare definice se pri zobrazeni cele CR ma vse zobrazit jako body/geometrie. Podle noveho bude mozne zobrazit prazsky cluster+samostatnou geometrii pro Brno a Ostravu.

**Comment by jiri-bartos-huld** [comment]
Myslim, ze mam vsechny pdrobnosti k zadani.

**Comment by jiri-bartos-huld** [comment]
@motyc 
1. Vrstvy 1-6 budou podporovat vyber pres bounding-box =budou se vracet jen geometrie co je mozne zobrazit na obrazovce
2. Vrstvy 7-8 budou vracet vzdy vsechny zaznamy, duvodem je caching na urovni requestu

**Comment by motyc** [comment]
@jiri-bartos-huld Ano, to asi není problém. Pro vrstvy 7-8 nikdy nepůjde o extrémní počty záznamů.

**Comment by jiri-bartos-huld** [comment]
@pesikj  @jnihnat  Tohle je pripraveno k nasazeni 31.10.2023

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z17)
- [ ] http://192.168.254.30:8080/projekt/detail/C-202011498 - nevidím PIAN akce (přihlášen jako admin)
- [ ] http://192.168.254.30:8080/projekt/detail/C-202105414 - nevidím Samostatný nález (přihlášen jako admin)
- [ ] Heatmapa se zobrazuje bez ohledu na to, zda je nějaká vrstva 2-6 zapnutá a kolik je aktuální počet viditelných lokalizací. Čekal bych, že se zapne pouze ve chvíli, kdy počet lokalizací v součtu za zapnuté vrstvy přesáhne limit (tuším 5000 záznamů)

**Comment by jiri-bartos-huld** [comment]
vse by melo byt opraveno na MR

**Comment by motyc** [comment]
### Test
Vrstvy projektů fungují skvěle, tam nemám co vytknout.

- [ ] Samostatné nálezy projektu stále nevidím, ať se snažím jakkoli (viz http://192.168.254.30:8080/projekt/detail/M-202101534)
- [ ] http://192.168.254.30:8080/projekt/edit/M-202101534 - mapa se nezobrazuje vůbec
- [ ] PIAN projektu - chová se velmi zvláštně, někdy se správný PIAN zobrazí, někdy ne. Naopak někdy naskakují i zcela nesouvisející PIAN okolo. Velmi dobře patrné je to u http://192.168.254.30:8080/projekt/detail/C-202011498 (všimněte si také, že v popiscích PIAN se tvrdí, že mají přesnost 4, i když to není pravda:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/78ebaa7c-89cf-4e50-8461-a78258653c66)

**Comment by motyc** [comment]
### Test v0.3.5z61
- [ ] http://192.168.254.30:8080/projekt/edit/M-202101534 - do clusteringu se započítává i právě editovaný projekt (na http://192.168.254.30:8080/projekt/detail/M-202101534 je to přitom správně); resp. problém je v tom, že se daný projekt objevuje i v jiných vrstvách, než "Lokalizace projektu"
- [ ] PIAN projektu - již ok, pouze zelená se aplikuje jen na centroid a nikoli na celou geometrii.
- [ ] http://192.168.254.30:8080/projekt/zapsat - Nastavování již jde ok a vše se chová smysluplně. Problém je nyní v tom, že se zdají být nějaká nesprávná data, se kterými heatmapa pracuje. Zde je dobře vidět, že to vypadá, že v Plzni nejsou žádné projekty:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f75597c3-b6a0-4d84-bba7-684ebd5f6c65)

Když ale zazoomuji blíže, je naopak vidět, že projektů je tam oproti okolí velmi mnoho:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7ac7e615-3efe-4c98-b44d-0eea7d6db8cc)

Je proto zřejmé, že data pro heatmapu se negenerují správně.

**Comment by jiri-bartos-huld** [comment]
pripraveno na MR

**Comment by motyc** [comment]
### Test v0.3.5z67
@jiri-bartos-huld Důrazně prosím o důslednější testování před předáním. Mám pocit, že to nikdo nekontroluje ani v základu a prostě si náhodně pinkáme nedodělky (netýká se pouze tohoto issue).
- [ ] Teď se PIAN projektu pro změnu nezobrazuje vůbec: http://192.168.254.30:8080/projekt/detail/C-202011498
- [ ] _nadále platí:_ http://192.168.254.30:8080/projekt/zapsat - Nastavování již jde ok a vše se chová smysluplně. Problém je nyní v tom, že se zdají být nějaká nesprávná data, se kterými heatmapa pracuje. Zde je dobře vidět, že to vypadá, že v Plzni nejsou žádné projekty:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f75597c3-b6a0-4d84-bba7-684ebd5f6c65)

Když ale zazoomuji blíže, je naopak vidět, že projektů je tam oproti okolí velmi mnoho:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7ac7e615-3efe-4c98-b44d-0eea7d6db8cc)

Je proto zřejmé, že data pro heatmapu se negenerují správně.

**Comment by jiri-bartos-huld** [comment]
Teď se PIAN projektu pro změnu nezobrazuje vůbec: http://192.168.254.30:8080/projekt/detail/C-202011498

![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/861a11fc-0b15-40cb-a243-014903b2708d)

**Comment by jiri-bartos-huld** [comment]
@pesikj @motyc 
Dobry den, prisel jsem na to: pro projekty bylo omezeni, ze do heatmapy nevstupuji ctverce kde "0.01" oblast nema alespon 10 projektu-spravne nove jsem nastavil min>1. Jen umozornim, to min. by melo byt vyssi nez 1, aby se do heatmapy nenacitaly zbytecne drobne body, ktere jsou po cele republice a nezpomalo by to nacitani heatmapy).

prosim podivejte se na to(je to nastavene na serveru 30) a pokud souhlasite, zaclenime opravu do  gitu.

oprava:
DROP MATERIALIZED VIEW IF EXISTS amcr_heat_projekt_l2;
CREATE MATERIALIZED VIEW amcr_heat_projekt_l2 as select count(*) as count, geom as st_centroid from amcr_heat_projekt_l1 
where ST_IsEmpty(geom)=false
group by st_centroid having count(*) >1;

![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/c28f57f6-e946-47d7-a749-cfce86b11265)

**Comment by motyc** [comment]
@jiri-bartos-huld Dobrý večer, ano, to vypadá bez problémů. Myslím, že můžete aplikovat. Díky.

**Comment by pesikj** [comment]
@motyc @jiri-bartos-huld Migrace jsem upravil.

**Comment by motyc** [comment]
### Test v0.3.5z77
Heatmapa už vypadá, že funguje v pořádku. Problém zůstává s těmi PIAN.

- [ ] U původně referovaného záznamu se PIAN připojené akce zobrazí, zjevně to ale neplatí pro jiné případy. Může je spojovat to, že jde o situace, kdy k podřazené akci máme více PIAN (mají více DJ) a případy, kdy máme více akci k projektu. Např.:
-- http://192.168.254.30:8080/projekt/detail/C-201671890
-- http://192.168.254.30:8080/projekt/detail/C-201340052

**Comment by jiri-bartos-huld** [comment]
1.
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/26356a7a-0732-40f4-bc09-7dbf137627bc)
2.
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/7f150e82-a56e-4939-94d3-b2d14545dfba)
