### ISSUE TITLE
Upravit datové vrstvy - akce/lokality

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#300]
Upravit datové vrstvy pro mapy u akcí a lokalit (**tučně** - defaultně zapnuté; čísla uvádí pořadí vrstev)
- Vrstvy 1 a 2 nikdy nemají heatmapu ani clustering, protože neobsahují vyšší počty záznamů.
- Při souběžném zapnutí vrstev 3 a 4 tvořit heatmapu jako sloučenou verzi, která se bude vytvářet z obou vrstev.
- V případě heatmapy NENÍ třeba zohledňovat přístupnost a vlastnictví u žádné z vrstev, protože informace je natolik generalizovaná, že stejně nikomu nic neřekne. Clustering přístupnost a vlastnictví zohledňovat MUSÍ.
- [x] 1 - Lokalizace projektu (nadřazený projekt; geom z projektu) - pouze pro akce, nikoli pro lokality; vrstva o jednom geoprvku = lokalizace projektu do kterého DJ patři
- [x] 2 - **PIAN záznamu** (aktivní vrstva)
- [x] 3 - Samostatné nálezy (všechny; geom z nálezu; zohlednit přístupnost a vlastnictví - viz #379); v heatmapě počítat pouze se SN4.
- [x] 4 - **PIAN** (všechny; geom z PIAN; zohlednit přístupnost a vlastnictví - viz #379); slouží též pro výběr PIAN z mapy.

**Comment by jiri-bartos-huld** [comment]
@motyc 
1./ Neni zadana v M2, je potreba omezit tento task mimo #319 
3./ "PIAN projektu" a "PIAN" se prekryvaji, nabizim:
 - zachovat jak chcete, ale vrstva "PIAN projektu" bude nad vrstvou "PIAN"
 - clustering resit spolecne ale mit omezujici pravidlo, kvuli rychlosti(jinak budeme muset resit prunik), jen pro vrstvu "PIAN">500
 - prekryvani by v soucnasosti  nemel byt problem protoze "potvrzene" nelze posouvat, ale v budoucnu by to mohl byt pro editaci problem, protoze edituji vrchni a pokud ho posunu tak pod nim bude videt puvodni.
4./Narazime na problem ze muze existovat heatmapa jak pro PIANY tak pro SamNalezy. Jak to prosim resit? Nabizim:

- [ ] Sloucenou heatmapu, ktera se bude vytvaret z obou vrstev (mozna nebude idealni zobrazeni, ale alespon neco)

**Comment by motyc** [comment]
@jiri-bartos-huld
1. Je to součástí S4, který se bude dělat zároveň. M2 jen vyděluje věci dotýkající se mapy. V rámci #319 se ale celý detail v části DJ co se týče mapy nijak neliší, mělo by tak jít o využití již existujících částí aplikace a jejich integraci do tohoto modulu... Každopádně nemusí se to zohledňovat tady, jen na to upozorňuji, aby bylo jasno. Časová náročnost celé implementace modulu by měla být zohledněna v #319.
3. volil bych `clustering resit spolecne ale mit omezujici pravidlo, kvuli rychlosti(jinak budeme muset resit prunik), jen pro vrstvu "PIAN">500`
4. souhlasím

**Comment by motyc** [comment]
@jiri-bartos-huld Po úvaze zadání ještě upraveno, a to tak že:
- ve vrstvě PIAN zobrazíme potvrzené i nepotvrzené PIAN
- díky tomu nebudeme potřebovat vrstvu PIAN projektu
- ve vrstvě PIAN je třeba kromě přístupnosti zohlednit též vlastnictví, tj. PIAN vidím, pokud:
-- je pro mou roli veřejný (přístupnost),
-- nebo pokud patří k projektu mé organizace (vlastnictví),
-- nebo pokud je mnou vytvořený (vlastnictví).
(jak bylo domluveno, neplatí pro heatmapu, kde je to jedno)

Prosím o odpovídající úpravu odhadu

**Comment by jiri-bartos-huld** [comment]
@motyc prosim, co je to "SN4"

**Comment by motyc** [comment]
@jiri-bartos-huld samostatné nálezy kde stav = 4

**Comment by motyc** [comment]
@jiri-bartos-huld Ano, to je dobrá poznámka, to by samozřejmě bylo skvělé, pokud bychom to v těchto případech skryli. Děkuji.

**Comment by jiri-bartos-huld** [comment]
@motyc 
jeste jeden kratky dotaz:  Pokud napriklad vrstva 4. ma dostatek bodu na vytvoreni heatmapy ale 3. by sama vytvorila pouze clustery/nebo par bodu co udelat pri jejich spolecnem zobrazeni (prosim vyberte si):
1./ Spolecnou heatmapu pro 3.+4.
2./ Pro vrstvu 4 heatmapu a pro vrstvu 3 clustery
_Při souběžném zapnutí vrstev 3 a 4 tvořit heatmapu jako sloučenou verzi, která se bude vytvářet z obou vrstev._

**Comment by motyc** [comment]
@jiri-bartos-huld Varianta 1, tedy vždy počítat se sloučenou verzí. Pokud by uživatel chtěl vidět jen jedno, danou vrstvu si může vypnout.

**Comment by jiri-bartos-huld** [comment]
@jnihnat prosim pristupnost a vlastnictvi

**Comment by jiri-bartos-huld** [comment]
@pesikj  @jnihnat  Toto je pripraveno k nasazeni 31.10.2023

**Comment by motyc** [comment]
### Testování v0.3.5z21
Dohodnuto s @jiri-bartos-huld 
- [ ] přesunout `akce-get-pas-pian` do app core
- [ ] `akce-get-pas-pian` přejmenovat na `mapa-pian-pas`
- [ ] doplnit označení action `mapa_pas` a `mapa_pian` do komentářů v kódu kvůli párování s nastavením oprávnění
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9723779A/dj/C-9723779A-D01 - selhává heatmapa
- [ ] http://192.168.254.30:8080/pas/detail/C-202300531-N00001 - selhává kompletně

(souvisí také s PAS viz #995)

**Comment by jiri-bartos-huld** [comment]
@jnihnat do kdu bylo doplneno:
musi zohlednit pristupnost [mapa_pian] -jednou pro zjisteni poctu pak pro vypis pas
musi zohlednit pristupnost [mapa_pas] -take dvakrat

je to vse v samostatne vetvy /MR draft
https://github.com/ARUP-CAS/aiscr-webamcr/pull/1322

**Comment by jiri-bartos-huld** [comment]
Nyni by vse melo byt za mapu na MR

**Comment by motyc** [comment]
Nelze testovat kvůli #1342

**Comment by motyc** [comment]
Funguje bez problémů. Jediná výtka je špatná ikona u nálezů, ale to už řešíme v https://github.com/ARUP-CAS/aiscr-webamcr/issues/995#issuecomment-1815543137
