### ISSUE TITLE
Upravit datové vrstvy - Knihovna 3D

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#301]
Upravit datové vrstvy pro dílčí užití mapy (**tučně** - defaultně zapnuté)
- [x] AMČR Zájmové body - přejmenovat -> **Lokalizace modelu** (aktivní vrstva)
- [x] Knihovna 3D (vše z řady 3D; geom z extra_data)

Reseni: 
- Nazev vrstvy "AMČR Zájmové body" bude prejmenovan na "Lokalizace modelu"
- Rozliseni na 2 vrstvy: aktivni prvek(prave editovany) a ostatni

Zasazene stranky:
- amcr/dokument/create/model	:Knihovna 3D: zapsat
- amcr/dokument/detail/model/X	:Knihovna 3D: detail
- amcr/dokument/detail/model/X	:Knihovna 3D: editace

**Comment by motyc** [comment]
> David Novák 
> 19. prosince 2021 13:55
> Jde jen o informaci, odkud se v tomto případě bere geometrie prvků - tabulka “dokument_extra_data”, sloupec “geom” - a o tom, jaké záznamy brát (všechny modely).
> 
> Jiří Bartoš 
> 13. prosince 2021 17:05
> David Novák Dotaz: Prosim nerozumim pozadavku: "Knihovna 3D* (vše; geom z extra_data)"

**Comment by motyc** [comment]
@jiri-bartos-huld Odhad po vysvětlení potvrzuji, jen prosím při implementaci zohlednit i budoucí potřeby implementace issue #299 a #300 (a případných dalších obdobných), aby se náklady na řešení nepropisovaly opakovaně.

**Comment by jiri-bartos-huld** [comment]
@motyc jedine jak je mozne zohlednit #299 a #300 je vycleneni techto vrstev z mapove sablony a pridavat je dynamicky na zaklade kontextu, uprava v ramci #301 bude obsahovat upravu sablony+reseni pro 3D knihovnu

**Comment by motyc** [comment]
@jiri-bartos-huld Samozřejmě mi jde hlavně o to, aby to bylo nějak racionální. Pokud to v technické rovině nedává smysl, nedá se nic dělat. Jen mi šlo o to, aby byla tato issue chápána při odhadu jako celek, protože jde o třikrát tentýž problém...

**Comment by jiri-bartos-huld** [comment]
@pesikj  @jnihnat  Toto je pripraveno k nasazeni 31.10.2023

**Comment by motyc** [comment]
@jiri-bartos-huld Zde vše funguje, jen prosím upravit URL z původního `akce-get-3d` na `model/mapa-3d`

**Comment by jiri-bartos-huld** [comment]
@motyc  adresar "model" neexistuje mate na mysli puvodni "dokument"? Protoze jinak to je presun a prejmenovani.

**Comment by motyc** [comment]
@jiri-bartos-huld není k tomu potřeba samostatný adresář, je to jen podřazeno o úroveň níž v rámci názvu URL, podobně jako zde: http://192.168.254.30:8080/dokument/model/vyber

https://github.com/ARUP-CAS/aiscr-webamcr/blob/5b0326cfbc2929a9a1252af62984891a0cb6d8c5/webclient/dokument/urls.py#L37

Celá adresa tak bude http://192.168.254.30:8080/dokument/model/mapa-3d

Opravdu jde čistě jen o to, abychom související věci měli označovány shodně.

**Comment by jiri-bartos-huld** [comment]
OK, takze spravne smerovani je dokumenty/model/mapa-3d

**Comment by jiri-bartos-huld** [comment]
Vse by melo byt odevzdano v MR

**Comment by motyc** [comment]
Blokováno kvůli #558
