### ISSUE TITLE
Symbologie linií a polygonů + principy clusteringu/heatmapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#302]
Symbologie PIAN u linií a polygonů
- [x] žlutá - vybraný prvek
- [x] zelená - ostatní prvky téhož záznamu
- [x] červená - editovaný prvek
- [x] modrá - jiné datové vrstvy
- [x] definiční body ploch a linií odlišit symbolem (#303) 
- [x]  def. bod může mít jen žlutou/zelenou/modrou barvu protože nelze přímo editovat

Celková logika zobrazení
- [x] <500 - maximální počet výsledku, při kterých jsou vidět rovnou markery (a vykreslí se též linie/polygony): Pozadavek na Python metodu spouradniceXY pro geometrie
- [x] 500-10 000 - generují se clustery (na základě bodů/centroidů): Pozadavek na Python methodu souradniceXY pro marker/centroidlinii/polygonu
- [x] >10 000 - zobrazuje se heatmapa (clustering to již nezvládá a načítání trvá příliš dlouhou dobu)
(konkrétní limimitní hodnoty lze ladit, ale princip by bylo vhodné zachovat): Pozadavek na Python methodu souradniceXY pro skupinu k-mean (behme implementace rozhodnout zda nebude potreba db procedure/materializovany pohled)

**Comment by jiri-bartos-huld** [comment]
![obrazek](https://user-images.githubusercontent.com/77389730/171282284-ce337421-1150-4b86-9dad-20194fafded3.png)
ukazka heatmapy

**Comment by motyc** [comment]
### Výsledky testu
- [ ] vybraný prvek není žlutý, ale červený - červená se má použít po zahájení editace či při zadávání nového
- [ ] při zahájení editace se PIAN změní na fialový, místo červený (v případě linií a polygonů); v případě bodů je po zahájení bod zelený a po vložení nového bodu zčervená až nový bod.
- [ ] definiční body nemají odlišen symbol (zadání upřesněno v #303)
- [ ] definiční body mají červenou, i když zadání v tomto mluví jasně (může být jen žlutá/zelená/modrá)
- [ ] modrá barva hodně splývá z obsahem mapy (vodní toky) - pokud to není problém, změnil bych základní barvu ostatních datových vrstev z modré na fialovou (tu, která se nyní zobrazuje při editaci) - jde o odchylku od zadání, pokud to není triviální úprava, lze nechat na další objednávku
- [ ] Pokud zapnu “Připojit PIAN z mapy” nebo “Přidat nový PIAN”, přestanou se v mapě aktualizovat data.
- [ ] Chybí indikátor, že se mapa ještě načítá a působí tak zvláštně, že se obsah mapy postupně mění a není jasné, kdy načítání skončilo. Někdy se dokonce stane, že se objeví clustery a následně mapa přeskočí na heatmapu, i když ničím nehnu (asi jak se na pozadí donačítají data). Je to opravdu velice matoucí.
- [ ] I když vypnu vrstvu "AMČR Piany", tak se zjevně na pozadí data různě načítají a zobrazuje se heatmapa. Vrstva se skryje až na úrovni clusterů/geometrií.
- [ ] v případě projektů se data vůbec nezobrazují, dokud projekt není lokalizovaný (špatně), navíc je počet zobrazených limitován na maximálně 100, takže to nejde testovat
- [ ] Heatmapa se často zobrazuje chybně, jako body ve čtvercové síti:
![image](https://user-images.githubusercontent.com/20186892/173865976-e9446983-634c-45b8-8551-7cc7aa489495.png)
Souvisí to myslím s nastavením parametrů mapy. V Digiarchivu se osvědčilo nastavení (nevím ale, zda je použita stejná knihovna):
```
"heatmapOptions":
		{
			"radius": 0.5,
			"maxOpacity": 0.8,
			"minOpacity": 0.15,
			"scaleRadius": true,
			"useLocalExtrema": true,
			"latField": "lat",
			"lngField": "lng",
			"valueField": "count",
			"gradient":
			{
				"0.0": "rgb(255,0,255)",
				"0.15": "rgb(0,0,255)",
				"0.25": "rgb(0,255,0)",
				"0.45": "rgb(255,255,0)",
				"0.65": "rgb(255,170,0)",
				"0.95": "rgb(255,0,0)",
				"1.0": "rgb(255,0,0)"
			}
		},
```

**Comment by jiri-bartos-huld** [comment]
1. Fialova pro markery/linie/polygony
2. Zluta pro Vybrane prvky (stejna barva se pouzije pri najezdu myssi)
![obrazek](https://user-images.githubusercontent.com/77389730/174895147-4669d78c-e5ba-42f7-8126-f5c20fb96795.png)
3. Editace geometrie je cervena
![obrazek](https://user-images.githubusercontent.com/77389730/174895420-aab7e4b0-bc9f-4d7f-b161-e73b27533238.png)

**Comment by jiri-bartos-huld** [comment]
@motyc 
Vsimpl jsem si, ze nejsou zapnute Modre/Fialove(ostatni) def. body pro linie a polygony
1./ Muzeme je zapnout ale zvysi to densitu kresby na mape
![obrazek](https://user-images.githubusercontent.com/77389730/174898418-b89939b4-76d8-4309-af63-3b96458a75d2.png)
2./nebo muzeme nechat bez def. bodu, protoze podrobne info dostane uzivatel "prejezdem" po geometrii
![obrazek](https://user-images.githubusercontent.com/77389730/174895863-dcd7415d-1b25-4efd-8d3a-251c6141a045.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Pokud to není nutné a funguje clustering i bez nich, zatím bych je nezapínal a případně to doladíme po delším testování. To chování je třeba si dostatečně "osahat".

**Comment by jiri-bartos-huld** [comment]
Editace je nyni cervena: 
1./Marker
https://user-images.githubusercontent.com/77389730/175035078-06ff77d4-cad9-40d1-828e-8c17fbf9ae1e.mp4
2./Geometrie
https://user-images.githubusercontent.com/77389730/175035090-75684ca2-8a87-4970-8372-9936e57d828e.mp4

PSc chyba: 
https://github.com/Leaflet/Leaflet/issues/4484

**Comment by motyc** [comment]
### Výsledek testu
Nelze testovat, mapa u akce se zasekne ve stavu načítání (běží kolečko a nic se neděje).

**Comment by motyc** [comment]
### Výsledek testu
- [ ] geometrie se načítají i v případě, že je již zapnutý clustering (>=500 geometrií)
![image](https://user-images.githubusercontent.com/20186892/176887373-57214b5f-1bd0-407f-9f17-33eac94940f0.png)
- [ ] clustery se zobrazují i ve chvíli, kdy již mají být vidět jen geometrie (<500 geometrií)
![image](https://user-images.githubusercontent.com/20186892/176887575-d1629846-0af6-477f-b258-ba0ee0d57cc2.png)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] clustering pro PIAN nyní nefunguje vůbec (test přes http://192.168.254.30:8080/arch-z/akce/detail/C-200913623C)

**Comment by jiri-bartos-huld** [comment]
opraveno primraveno na MR:

![obrazek](https://user-images.githubusercontent.com/77389730/180208567-0a15fbc2-a277-4e4f-b9ba-9982fb733a43.png)
priblizeni
![obrazek](https://user-images.githubusercontent.com/77389730/180208662-2fc3adf0-0d16-4a39-9140-e8092fd5b0b1.png)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Vstoupím na http://192.168.254.30:8080/arch-z/akce/detail/C-200913623C a vidím heatmap -> zazoomuji a vidím clustery -> zazoomuji a vidím geometrie (podut ok) -> odzoomuji na předchozí úroveň a zmizí geometrie, ale clustery se již neobjeví (CHYBA) -> odzoomuji a zobrazí se heatmapa (ok) -> zazoomuji a clustery stále nevidím (CHYBA)

**Comment by motyc** [comment]
@jiri-bartos-huld Po vymazání cache funguje v pořádku.
