### ISSUE TITLE
Nastavení symbologie bodů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#303]
Toto issue částečně navazuje na https://github.com/ARUP-CAS/aiscr-digiarchiv-2/issues/117, kde jsme ještě ladili implementaci a bylo by vhodné, aby v některých základních konturách bylo chování shodné. Na základě toho bych navrhoval následující:

- [x] Projekty:  pin s ikonou `<span class="material-icons">dynamic_feed</span>` (https://materialui.co/icon/dynamic-feed)
- [x] PIAN - bod: ![image](https://user-images.githubusercontent.com/20186892/151148766-4c6387ab-6284-42a6-bb3c-0fa04d00836c.png)
- [x] PIAN - definiční bod (linie/plocha): ![image](https://user-images.githubusercontent.com/20186892/151148798-0d57d171-4875-4df1-a21e-40486481df4b.png)
- [x] Samostatné nálezy:  pin s ikonou `<span class="material-icons">location_on</span>` (https://materializecss.com/icons.html)
- [x] Knihovna 3D: pin s ikonou `<span class="material-icons">3d_rotation</span>` (https://materializecss.com/icons.html)

Pak by to odpovídalo ikonám v levém menu, což by bylo šikovně přehledné.

Úzce souvisí též #302

**Comment by motyc** [comment]
> Jiří Bartoš 
> 6. ledna 2022 0:33
> David Novák pripravim grafickou ukazku: priznavam, ze se mi prilis nelibi dynamic feed, protoze to muze evokovat, ze je vice projektu na sobe

**Comment by motyc** [comment]
@jiri-bartos-huld Vzhledem k pravděpodobnosti, že to může jít snadněji případně prosím o efektivní využití ušetřeného času, zejména pro řešení #302, resp. pro odhadování obou úprav přímé souvislosti, ať se náklady neduplikují.

**Comment by jiri-bartos-huld** [comment]
@motyc 
Dobry den, pripravil jsem sadu symbologii a barev: samotny pin jsem nechal s pruhlednym vyrezem:

![obrazek](https://user-images.githubusercontent.com/77389730/160779132-7d25ddd4-76dc-4898-bb44-024156bdbb67.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Vypadá to dobře, kromě té žluté, kde je dost malý kontrast mezi tečkou a pinem ve třetím sloupci. Asi by to chtělo tu žlutou barvu dát trošku světlejší/výraznější/více do žluta (nebo to jinak vyladit)...

Také mi přijde, že je obecně ta tečka ve třetím sloupci posazena excentricky. Možná je to nějaký optický klam, je ale určitě posunutá oproti druhému sloupci, kde to sedí uprostřed.

**Comment by jiri-bartos-huld** [comment]
Dobry den, upravil jsem: centrovani+pro 3 sloupec jsem pridal konturu(stejne jako ma 2 sloupec)

![obrazek](https://user-images.githubusercontent.com/77389730/160830736-150faca4-d119-4057-a353-3d7e961d2d20.png)

**Comment by jiri-bartos-huld** [comment]
Postupne zde pripravim zde nekolik nahledu:
1./Vytvoreni oznameni
-adresa http://127.0.0.1:8000/oznameni/
-Puvodne modry PIN sloupec 2
-Nove cerveny PIN sloupec 2
-Jine vrstvy neobsahuji piny
![image](https://user-images.githubusercontent.com/77389730/160916085-13f98594-822b-4251-9487-1af389498a3b.png)

2./Vytvoreni projektu
-adresa http://localhost:8000/projekt/zapsat
-Puvodni cerveny pin sloupec 2
-Nove Cerveny pin sloupec 5
-Jine vrsty: projekty Modre piny sloupec 5
![image](https://user-images.githubusercontent.com/77389730/160918632-6bd1d691-cd1d-4d10-a149-b497b6325348.png)

3./Zobrazeni projektu

4./Editace projektu

**Comment by motyc** [comment]
@jiri-bartos-huld Zde komentáře:
1) Má být červený, sloupec 6 (jde o projekt)
2) ok
3) ok
4) ok
5) ok
6) ok

**Comment by jiri-bartos-huld** [comment]
Editace Pian:

-Aktivni pian je linie (cervena), ta ma def. bod(centroid) cerveny pin sloupec 2

-V porjektu jsou jeste 3 piany zadane markerem (zeleny sloupec 3) a jeden zadany zelenym polygonem (centroid zeleny 
sloupec2)

-ostatni piany jsou modre linie/polygony/modry marker sloupec 3. pricemz polygony ani linie nemaji def. body



![image](https://user-images.githubusercontent.com/77389730/162614472-260ffc80-b8fa-44e5-895c-5985e89ea249.png)

**Comment by jiri-bartos-huld** [comment]
8./ Oznameni je opraveno
![image](https://user-images.githubusercontent.com/77389730/162614964-30b2e00e-9e31-4be8-80cb-56f18c4f385e.png)


> @jiri-bartos-huld Zde komentáře:
> 
>     1. Má být červený, sloupec 6 (jde o projekt)
> 
>     2. ok
> 
>     3. ok
> 
>     4. ok
> 
>     5. ok
> 
>     6. ok

**Comment by motyc** [comment]
@jiri-bartos-huld Díky, zde pár poznámek k https://github.com/ARUP-CAS/aiscr-webamcr/issues/303#issuecomment-1094243654
1) Šlo by u linií definiční bod prosím dávat na centerpoint (střed linie) nikoli na centroid?
2) Trošku mne mate to "v projektu jsou ještě 3 PIANy" - o jaký pohled jde, u akce, nebo u projektu? Pokud u akce, pak by zelené měly být jen PIAN téže akce, nikoli celého projektu (to ale ještě můžeme probrat, případně definitivně rozhodnout po testování).
3) Centroidy byly záměrně myšlené jako menší piny (viz první příspěvek), aby byly snadno odlišitelné od bodů a tolik nerušily.
4) V tom mouse over prosím uvádějte i přesnost (stačí jako číslo v závorce za ID, např. "P-1224-001703 (2)". Je to důležitý údaj.
5) Editace geometrie - pokud se při editaci změní čára na přerušovanou, není myslím třeba měnit i barvu, ale pokud vám to při testování přijde nedostatečné, můžeme to rozhodnou, až si to osaháme. Určitě ale bude třeba zmenšit ty markery pro vertexy, protože jsou hrozně velké a "zavazí" při práci. Zkusil bych tak polovinu, ale chtělo by to testovat.

**Comment by motyc** [comment]
### Výsledky testu
- [ ] definiční bod neodpovídá zadání (má stejnou velikost pinu jako běžný bod)
- [ ] PAS - při zadání ok, ale pro detail (např. https://wamcr-test.aiscr.cz/pas/detail/C-202104879-N00003) se na mapě bod vůbec nezobrazí
- [ ] pin je ve výchozím stavu v detailu zelený (projekt, 3D; PAS nejde testovat, ale bude to asi stejné), má být žlutý (zelené používáme pro jiná související data - viz #302)

**Comment by motyc** [comment]
Definiční body nelze otestovat kvůli https://github.com/ARUP-CAS/aiscr-webamcr/issues/302#issuecomment-1167087249. Jinak vše ok.
