### ISSUE TITLE
Upravit zobrazení souřadnic

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#304]
Upravit zobrazení souřadnic (vpravo dole)
- [x] - zobrazit decimální stupně s přesností na sedm řádů
- [x] - optimalizovat umístění (posunout více ke spodnímu okraji)

**Comment by jiri-bartos-huld** [comment]
ponechano male odsazeni:
![image](https://user-images.githubusercontent.com/77389730/156767547-2f3338a2-27a5-488b-a778-9465d71f2844.png)
