### ISSUE TITLE
Revidovat transformační klíč S-JTSK -> WGS-84

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#305]
Revidovat transformační klíč S-JTSK -> WGS-84 (momentálně velice nepřesný)

Navazuje na #49 a https://gitlab.com/ais-amcr/webamcr/-/issues/128

Návrh řešení Huld:
1. Tam kde na vstupu jsou presne S-JTSK souradnice, navrhujeme vyuzit presnejsiho transformacniho klice CUZK, kdy po mat. transformaci je jeste provedena dotransformace na predpocitany grid v ramci CR, ktery by mel vypocet zlepsit.

Nevyhodou je, ze vypocet potrebuje
- znat vysku bodu Bpv (navrhujeme pouzit treba 460m. nm coz je prum. vyska v CR)
- Vypocet je poskytovan jako webova sluzba, neni tedy mozne ziskat plynule cteni souradnic pohybem mysi atd.
- Vypocet je urcen pro ETRS a nikoliv WGS84 (v pripade CR by nemel byt prozatim problem)

Pokud nebude WEBsluzba CUZK dostupna,umoznime mene presnou transformaci a do mapy zobrazime message box s varovanim, ze presna transformace neni dostupna (umoznime do DB ulozit mene presnou trabsformaci)

2./ Pri zadani souradnic v systemu WGS je tez mozne volat obdobnou sluzbu CUZK a ziskat tim S-JTSK, ale my to obecne nedoporucujeme. Protoze body budou stejne zobrazeny na mape ve wgs84/WorldMercator.

3./ Pro zobrazeni prubeznych souradnic doporucujeme zobrazovat jenom prirozene WGS84 (mapy jsou v systemu world-mercator wgs84).

Omezeni:
Pro prvotni implementaci navrhujeme aby byl CUZK transformacni klic JTSK->WGS84 byl implementovan jen na geometrii typu bod. **(ARÚ nesouhlas)**

### ARÚ požaduje analyzovat možné alternativy nezávislé na externí službě (viz komentáře)

**Comment by motyc** [comment]
> Jiří Bartoš 
> 5. ledna 2022 23:39
> David Novák Ještě doplním offline možnost pro grid transformaci není, ZÚ je přímo tvůrcem a veřejnosti poskytuje jen službu.
> 
> Jiří Bartoš 
> 4. ledna 2022 16:23
> David Novák Souhasim s Ad3/2, upravil jsem zadani.
> 
> David Novák 
> 23. prosince 2021 11:58
> Ad 3 - postupoval bych podle bodu 2, ale asi by bylo dobré si takové záznamy v DB explicitně označit.
> Napadá mne ale - ona neexistuje nějaká možnost využít stejný transformační klíč, jako používá služba ČÚZK a integrovat jej přímo k nám, aby transformace nebyla závislá na externí službě?
> 
> Jiří Bartoš 
> 22. prosince 2021 21:31
> David Novák prosim o nazor na bod 3.
> 1./ Chyba v poloze bude max. do 10cm pro kazdou souradnici 
> 2./Chovani aplikace se zmeni, pribude prodleva pri kliknuti do mapy uzivatel bude muset cetak na presny prepocet
> 3./Pokud nebude WEBsluzba CUZK dostupna,
> - nebude dostupna ani transformace-uzivateli se zobrazi hlaska
> - umoznime mene presnou transformaci a do mapy zobrazime message box s varovanim, ze presna transformace neni dostupna (umoznime do DB ulozit mene presnou trabsformaci)
> - existuje moznost, ze vzdy provedeme vypocet lokalne pro mene presny klic a mezitim se zeptame CUZK na presnou transformaci, pokud do nejake doby nedostaneme odpoved tak zobrazime message-box (mam strach aby toto nematlo uzivatele pri rucni editaci souradnic)
> 
> David Novák 
> 19. prosince 2021 14:40
> 1) S návrhem souhlasím, k tomu jen dotazy:
> Jak moc stanovená výška ovlivňuje polohovou přesnost (v jakých řádech - cm/dm/metry)?
> Jak změna ovlivní chování aplikace z pohledu uživatele? Z jeho pohledu zůstane vše stejné (kromě vrácených souřadnic)?
> Jak bude ošetřeno, co se stane při nedostupnosti služby ČÚZK?
> 2) Převod WGS → S-JTSK funguje myslím bez problémů a přesně, tam asi není třeba nic měnit.
> 3) Rozumím a souhlasím.
> 4) Není relevantní, viz předchozí.
> 
> Jiří Bartoš 
> 15. prosince 2021 19:20
> David Novák prosime o revizi navrhu.
> 
> Jiří Bartoš 
> 13. prosince 2021 18:08
> Dobry den, transformace z JTSK do WGS84 neni a  nikdy nebude exaktni, uz jenom tim ze vztah mezi Greenwitch (wgs84) a Ferro (S-JTSK) neni presne znam, pro vypocet je potreba znat nejenom polohu ale i vysku, …
> Pro zlepseni navrhujeme:
> 1./ Tam kde na vstupu jsou presne S-JTSK souradnice, navrhujeme vyuzit presnejsiho transformacniho klice CUZK, kdy po mat. transformaci je jeste provedena dotransformace na predpocitany grid v ramci CR, ktery by mel vypocet zlepsit. 
> Nevyhodou je, ze vypocet potrebuje 
> - znat vysku bodu Bpv (navrhujeme pouzit treba 460m. nm coz je prum. vyska v CR)
> - Vypocet je poskytovan jako webova sluzba, neni tedy mozne ziskat plynule cteni souradnic pohybem mysi atd.
> - Vypocet je urcen pro ETRS a nikoliv WGS84 (v pripade CR by nemel byt prozatim problem)
> 
> 2./ Pri zadani souradnic v systemu WGS je tez mozne volat obdobnou sluzbu CUZK a ziskat tim S-JTSK, ale my to obecne nedoporucujeme. Protoze body budou stejne zobrazeny na mape ve wgs84/WorldMercator.
> - Jedinny pripad kdy to doporucujeme zvazit je kdyz uzivatel klikne do mapy a ma prepnuto na zobrazeni S-JTSK souradnic
> 
> 3./ Pro zobrazeni prubeznych souradnic doporucujeme zobrazovat jenom prirozene WGS84 (mapy jsou v systemu world-mercator wgs84).
> 
> 4./Pokud je pozadovane prubezne zobrazeni JTSK (v bode 3 nedoporucujeme)
> - Doporucujeme pouzit “nepresny“ soucasny vypocet a zobrazit uzivateli, ze souradnice jsou nepresne ( soucasna presnost je mp=10m)
> - Moznost pri kazdem pohybu mysi se dotazat na webovou sluzbu CUZK pro transformaci nedoporucujeme-aplikace bude nepouzitelna
> - Moznost dynamicky prepinat v leafletu mezi projekcemi nedoporucujeme- presnost bude horsi nez soucasna

**Comment by motyc** [comment]
> Jiří Pešík 
> před 7 dny
> Jiří Bartoš Můžu v tomto být nějak nápomocen?
> 
> David Novák 
> 11. ledna 2022 18:34
> A z jakého důvodu to nejde použít? Níže vidím, že to selže, ale víme proč? Nebylo by lepší vložit úsilí do nalezení problému?
> Možná se ptám natvrdle, ale snažím se najít nejlepší řešení. Odložit to určitě nemůžeme, je to zcela zásadní věc.
> 
> Jiří Bartoš 
> 11. ledna 2022 18:30
> David Novák Dobry den, jak jiz jsem psal nize: V soucasnosti nejsme schopni pouzit QGIS transformaci, proto doporucujeme budto pouzit primo transformaci ZU nebo toto issue zatim nerealizovat.
> 
> Jiří Bartoš 
> 11. ledna 2022 18:28
> Dobry den, v soucasnosti nejsme schopni pouzivat transformaci z QGISu tak,zze ji napojime do postgresu ani samostatne v nastroji proj8
> 
> PROJ string:
> ```
> +proj=pipeline 
> +step +inv +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel 
> +step +proj=push +v_3 
> +step +proj=cart +ellps=bessel 
> +step +proj=helmert +x=589 +y=76 +z=480 
> +step +inv +proj=cart +ellps=WGS84 
> +step +proj=pop +v_3 
> +step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
> ```
> 
> POZADOVANO PROJ string:
> ```
> +proj=pipeline 
> +step +inv +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel 
> +step +proj=push +v_3 
> +step +proj=cart +ellps=bessel 
> +step +proj=helmert +x=570.8 +y=85.7 +z=462.8 +rx=4.998 +ry=1.587 +rz=5.261 +s=3.56+convention=position_vector 
> +step +inv +proj=cart +ellps=WGS84 
> +step +proj=pop +v_3 
> +step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 \
> ```
> 
> PROJ string:
> ```
> +proj=pipeline
> +step +proj=axisswap +order=2,1
> +step +proj=unitconvert +xy_in=deg +xy_out=rad
> +step +proj=push +v_3
> +step +proj=cart +ellps=WGS84
> +step +proj=helmert +x=-589 +y=-76 +z=-480
> +step +inv +proj=cart +ellps=bessel
> +step +proj=pop +v_3
> +step +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel
> ```
> 
> POZADOVANO PROJ string:
> ```
> +proj=pipeline 
> +step +proj=unitconvert +xy_in=deg +xy_out=rad 
> +step +proj=push +v_3 
> +step +proj=cart +ellps=WGS84 
> +step +inv +proj=helmert +x=570.8 +y=85.7 +z=462.8 +rx=4.998 +ry=1.587 +rz=5.261 +s=3.56 +convention=position_vector 
> +step +inv +proj=cart +ellps=bessel 
> +step +proj=pop +v_3 
> +step +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel \
> ```
> 
> ```
> projinfo -s EPSG:5514 -t EPSG:3857 -o PROJ
> Candidate operations found: 1
> Note: using '--spatial-test intersects' would bring more results (4)
> Operation No. 1:
> 
> unknown id, Inverse of Krovak East North (Greenwich) + S-JTSK to WGS 84 (3) + Popular Visualisation Pseudo-Mercator, 6 m, Europe - Czechoslovakia
> ```
> 
> PROJ string:
> ```
> +proj=pipeline +step +inv +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +step +proj=push +v_3 +step +proj=cart +ellps=bessel +step +proj=helmert +x=589 +y=76 +z=480 +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
> ```
> 
> David Novák 
> 6. ledna 2022 19:31
> Zde je definice transformace, kterou používám v QGIS:
> ![image](https://user-images.githubusercontent.com/20186892/151192053-a5615b2d-1dfe-4a23-adb9-e8777f3c065d.png)
> Přepis:
> ```
> Inverse of S-JTSK to WGS 84 (1) + Krovak East North (Greenwich)
> Rozsah: Approximation assuming equality between plate-fixed static and earth-fixed dynamic CRSs.
> Remarks: Parameter values from S-JTSK to ETRS89 (1) (code 1622). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation. Replaced by S-JTSK to WGS 84 (5) (code 5239).
> Rozsah: GIS.
> Remarks: Greenwich-based alternative to projection code 5218.
> Oblast použití: Czechia., Czechia; Slovakia.
> Identifikátory: INVERSE(EPSG):1623, EPSG:5510
> +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=570.8 +y=85.7 +z=462.8 +rx=4.998 +ry=1.587 +rz=5.261 +s=3.56 +convention=position_vector +step +inv +proj=cart +ellps=bessel +step +proj=pop +v_3 +step +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel
> ```
> 
> Opačný směr:
> ![image](https://user-images.githubusercontent.com/20186892/151192209-0b20e54c-0a24-42bf-9ee6-fd4502ebd2b1.png)
> 
> Přepis:
> ```
> Inverse of Krovak East North (Greenwich) + S-JTSK to WGS 84 (1) + Popular Visualisation Pseudo-Mercator
> Rozsah: GIS.
> Remarks: Greenwich-based alternative to projection code 5218.
> Rozsah: Approximation assuming equality between plate-fixed static and earth-fixed dynamic CRSs.
> Remarks: Parameter values from S-JTSK to ETRS89 (1) (code 1622). Assumes ETRS89 and WGS 84 can be considered the same to within the accuracy of the transformation. Replaced by S-JTSK to WGS 84 (5) (code 5239).
> Rozsah: Web mapping and visualisation.
> Oblast použití: Czechia; Slovakia., Czechia., World.
> Identifikátory: INVERSE(EPSG):5510, EPSG:1623, EPSG:3856
> +proj=pipeline +step +inv +proj=krovak +lat_0=49.5 +lon_0=24.8333333333333 +alpha=30.2881397527778 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +step +proj=push +v_3 +step +proj=cart +ellps=bessel +step +proj=helmert +x=570.8 +y=85.7 +z=462.8 +rx=4.998 +ry=1.587 +rz=5.261 +s=3.56 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=webmerc +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84
> ```
>

**Comment by jiri-bartos-huld** [comment]
Dobry den, vsiml jsem si ze vetsina tasku tykajici se mapy neni oznacena jako DONE+READY for testing, prestoze vse je nasazeno na serverech 24/34uz od zacatku cervana, nejspise se stav z Jira nepropsal.

Omlouvam se a upravuji stav ticketu+davam info

Toto je reseno v ramci https://github.com/ARUP-CAS/aiscr-webamcr/issues/306

Jeste si dovolim malou poznamku: To jak jsme resili neuspesne pouziti knihovny PROJ, myslim, ze problem bude v tom, ze pouzita definice je pouze definice zobrazeni a ne transformace.

**Comment by motyc** [comment]
@jiri-bartos-huld Díky za odpověď. Na základě #306 je tedy zřejmé, že užíváme tu transformaci ČÚZK. Jaká transformace se ale užívá, pokud služba nebude dostupná? I zde by bylo dobré najít něco přesnějšího, než původní verzi, kde jsou vznikající chyby opravdu obrovské. Např. zde lze najít transformace s centimetrovou přesností: http://freegis.fsv.cvut.cz/gwiki/S-JTSK_/_Grid (podle autorů to lze implementovat v PostGIS). Pokud by se podařilo najít velmi přesné offline řešení, přišlo by mi zbytečné spoléhat na ČÚZK. Opravdu mi nepřijde šťastné, že se řešení tolik upnulo na službu ČÚZK a byla vyvinuta minimální snaha najít požadované řešení pro transformaci na naší straně, přestože jsem několikrát zdůrazňoval, že chci, abyste takové řešení našli.

**Comment by jiri-bartos-huld** [comment]
@motyc @pesikj  @ScottVanWagenen 
Dobry den,
1./ Puvodne v lednu byl pozadavek na QGIS/proj4 transformaci, pokud si vzominate starvil jsem cca 12hodin abych ji zprovoznil a bych schopen rozhodnout zda je to dobra cesta/dat odhady, ale tuto transformaci se mi nepodarilo zprovoznit, proto jsem se dohodli na implementaci pres CUZK/ZU a my jsme na zaklade toho vytvorili odhady
2./Plne chapeme, ze je to zasadni vec: Transformace primo pres postgreSQL by byla lepsi pokud by dodrzela danou presnost, protoze by neavisela na extrni sluzbe. My ale nejsme shopni zarucit ze vse bude bez problemu fungovat a ze danou "vec" technologicky zvladneme. Muze to znit detinsky, ale pokud bycho dodatecne zvolili cestu postgis a vyskytl se nekde problem, tak bychom se vraceli zpet k CUZK/ZU, ktere funguje cca 12 let a ktere jsme v tomto tasku nacenovali.

**Comment by motyc** [comment]
@jiri-bartos-huld Problém je, že neplatí to "dohodli na ČÚZK/ZU". Na mé dotazy v lednu již nikdo nereagoval a diskuze zůstala neukončená, což považuji za největší problém, který by se do budoucna neměl opakovat.

Nicméně vzhledem k tomu, že issue ale bylo řešeno jako reklamace, tak opravdu není přínosné se o tom nyní dále dohadovat. Pokud bude převod správně fungovat (ještě prověřím), tak issue uzavřeme a další postup ohledně možného PostGIS řešení dohodneme v rámci nově vytvořeného #594.

**Comment by motyc** [comment]
### Výsledek testu
Testuji chování PAS s použitím těchto souřadnic:
![image](https://user-images.githubusercontent.com/20186892/179248767-ec5985a2-e09a-4cc2-ab36-c51260040ef8.png)

Pracuji na http://192.168.254.30:8080/pas/zapsat a http://192.168.254.30:8080/pas/edit/*

- [ ] zadám souřadnice v S-JTSK (-690995:-1010382) -> nález zapíšu -> souřadnice se samovolně (!) změní na -690994,45:-1010381,61, místo aby zůstaly zachovány původní; avšak když jdu na editaci a přepnu zpět na WGS-84, zobrazí se (správně) 50,4397503:15,0812526 - vzniká tedy rozpor mezi zobrazovanými/uloženými daty a realitou podle používané transformace; výsledku vůbec nerozumím, je každopádně špatně; pokud nějaké souřadnice zadám zápisem, musí zůstat zachovány tak, jak jsou
- [ ] posunutý je celý mapový podklad, jak dokazuje srovnání níže - ve všech případech by mělo jít o stejné souřadnice (viz výše), ale v AMČR se bod zobrazuje značně posunutý oproti podkladu - to je obrovský problém, protože při zadávání dat přes mapu, např. při využití katastrální mapy, budou vznikat úplně chybná data!
![image](https://user-images.githubusercontent.com/20186892/179254884-b23506e2-97a7-48f1-828d-782cd6122aa2.png)

**Comment by jiri-bartos-huld** [comment]
Ukladani je opraveno:
![obrazek](https://user-images.githubusercontent.com/77389730/180231382-a12327fb-a9b3-47c1-b0fe-188ae4a5f068.png)

@pbartosova @motyc 
Posunuty/stoceny mapovy podklad neni chybou a ani nepatri k tomuto tasku/issue: zobrazeni v AMCR je dohodnuto jako WorldMercator (valcove) a vsechny mapove podklady jsou ziskavany v tomto zobrazeni. Nejblize  tomuto zobrazeni je posledni obrazek ETRS, tam neni stoceni, ale pouze posun. [link](https://github.com/kartena/Proj4Leaflet)

**Comment by motyc** [comment]
@jiri-bartos-huld Pro mapové podklady vytvořeno samostatné issue #620, dále budeme řešit tam.

**Comment by motyc** [comment]
### Výsledek testu
Stále platné:
- [ ] zadám souřadnice v S-JTSK (-690995:-1010382) -> nález zapíšu -> souřadnice se samovolně (!) změní na -690994,45:-1010381,61, místo aby zůstaly zachovány původní; avšak když jdu na editaci a přepnu zpět na WGS-84, zobrazí se (správně) 50,4397503:15,0812526 - vzniká tedy rozpor mezi zobrazovanými/uloženými daty a realitou podle používané transformace - _doplňuji, že aby došlo k chybě, nález je potřeba zapsat, nebo uložit jeho editaci_

**Comment by jiri-bartos-huld** [comment]
@motyc 
Dobry den, podle me jde stejne jako u #302 o nacachovani starsi verze js:
1./Zde je jak vypnout pro napr. pro chorme
https://github.com/ARUP-CAS/aiscr-webamcr/issues/302
2./Zde je dukaz, ze se to chova spravne
https://user-images.githubusercontent.com/77389730/183913196-c820dc90-2ffd-48ba-b8a3-e8c8dfcdb23d.mp4
3./Je tam videt jeste drobna chybka, kdyz jako prvni krok pri zadavani SamNalezu prepnu na sjtsk tak se mi predvyplni  nesmyslne udaje-toto jeste rychle opravim a poslu na MR

**Comment by motyc** [comment]
@jiri-bartos-huld 

Ad 1 - Máte pravdu, bylo to asi tím.
Ad 3 - to máme podchycené zde: #611
