### ISSUE TITLE
Při ukládání dat pro PIAN a pro samostatné nálezy uložit obě varianty souřadnic

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#306]
Při ukládání dat pro PIAN a pro samostatné nálezy uložit obě varianty souřadnic (WGS-84 a S-JTSK) do DB a označit nativní systém pro daný prvek, tj. ten užitý pro zadání souřadnic před transformací.

Uvod: 
1. Velka cast PIAN vznika nezavislym DB importem, dale oznacovano jako impPIAN
2. impPIAN muze obsahovat jak body v JTSK
3. impPIAN podporuje pouze PIAN typu bod
4. je pozadovana poznost rucni editace souradnic jtsk

ReseniDB 
1. Ponechat impPIAN
2. Zmenit DB schema: 2 sloupce pro geometrii (wgs84 a jtsk)+sloupec oznaceni puvodniho systemu+2 sloupce datetime last_update_geom pro jednotlive geometrie
3. Dodelat nezavisly nastroj cmd utilita pro doplneni/update souradnic pro body importu
4. pokud je puvodni system jtsk tak pro ziskani wgs84 pouzit sluzbu cuzk
5. pokud je puvodni syste wgs84 tak pro wgs84 pouzit stejny algoritmus jako na UI
6. Na UI vzdy posilat 2 geometrie a 2 geometrie ocekavat z UI

ReseniUI
1. Novy PIAN je mozne zadat navic zadat jako bod wgs84/s-jtsk
2. Editace pianu: pokud je pian zadan bodem je mozna jeho editace souradnic ve wgs84 nebo s-jtsk (druhy system se dopocte)
3. Do DB se posilaji vzdy 2 geometrie (ziskani 2 geometrie odpovida ReseniDB v bodu 3)

Komplikace:
- Nutne resit validaci SJTSK geometii pri ukladani do DB pro linie a polygony
 
Zasazene stranky: 
- amcr/arch_z/detail/X
- ... (část chybí)

**Comment by motyc** [comment]
> Jiří Bartoš 
> 4. ledna 2022 17:00
> David Novák Dobry den DB bod 3 je tam protoze, ReseniUI by melo vzdy ocekavat, ze dostane jak JTSK tak i WGS84 a ukladat bude vzdy tez obe souradnice. V pripade, ze probehne import “bokem“, musime take doplnit wgs84.
> 
> David Novák 
> 4. ledna 2022 16:39
> Úvod
> - ad 2 - je to pouze S-JTSK
> - ad 3 - nikoli, mohou to být body, linie i polygony
> 
> Reseni DB
> - ad 3b - nemělo by být třeba (viz výše)
> 
> Jinak v pořádku, ale vypadlo z toho řešení pro Samostatné nálezy, které nemají PIAN ale souřadnice jsou přímo v tabulce samostatny_nalez (je jasné, že řešit se to bude stejně, jen to tam není zmíněno).
> 
> David Novák 
> 19. prosince 2021 14:04
> U PIAN jde o tyto dvě věci:
> - Podstatná část PIAN vznikla a dále bude vznikat importem, ve kterém byla data v S-JTSK; k převodu tam tedy došlo (dochází)
> - V editaci PIAN by mělo být možné posouvat body/vertexy na konkrétní souřadnice, a to jak ve WGS-84, tak v S-JTSK (viz AMCR-51); jde víceméně ekvivalent funkce u Sam. nálezů, jen se to komplikuje o ty linie a plochy, proto je to třeba pro vertexy). S-JTSK je obecně nejužívanější systém, bohužel jej tedy nemůžeme vynechávat.
> 
> Jiří Bartoš 
> 13. prosince 2021 17:30
> Dobry den, prilis nechapu “pozadi” tohoto tasku David Novák prosim vysvetleni
> 1. Myslel jsem, ze problem v souradnicich se tyka jen Sam.Nalezu, kde je moznost zadavat souradnice S-JTSK “rucne“. Pro tento pripad “rucni zadani souradnic S-JTSK“ doporucujeme opravdu do DB ukladat obe varianty. V ostatnich pripadech pouze WGS84 (tim bude jasne, ze vstupem nebylo prave JTSK).
> 2. Priznavam se ze nechapu proc ukladat PIAN duplicitne v S-JTSK?

**Comment by jiri-bartos-huld** [comment]
Dobry den, vsiml jsem si ze vetsina tasku tykajici se mapy neni oznacena jako DONE+READY for testing, prestoze vse je nasazeno na serverech 24/34uz od zacatku cervana, nejspise se stav z Jira nepropsal.

Omlouvam se a upravuji stav ticketu+davam info

Info: 
GUI aplikace: pro zadany pian a samostatny nalez provede prislusnou konverzi do obou systemu a ulozi do DB.
Ve vetsine pripadu se zadavaji souradnice klikanim v mape, jsou tedy znamy souradnice WGS84 (konverze v tomto pripaade je mozna primo v aplikaci=browseru). V pripade samostatneho nalezu, ale je moznost primo zadavat souradnice SJTSK, v tomto pripade se provede volani sluzeb https://geoportal.cuzk.cz pro presnou konverzi mezi SJTSK->WGS84.

Poznamka ke konverzi SJTSK->WGS84:
1./Podle dohody pouzivame presnou dotransformaci https://geoportal.cuzk.cz 
2./Omezujici specialita je zpusob jakym je tato transformace CUZK poskytovana ven. V ramci INSPIRE ma CUZK/ZU povinnost poskytovat vybrana data a transformace verejnosti zdarma, ale ne vzdy je dana forma poskytovani. CUZK/ZU ma omezeni na transformaci tim, ze neposkytuje integraci pro prime volani z browseru Mozilla/Edge pomoci omezeni CORS halvicek psokytovanych serverem.Proto je transformace implementovana tak, ze nase aplikace nase api v pythonu bezici na serveru 24/34 a ten az provede volani geoportalu.
vice o CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
3./Transformace je implementovana pro typ geometrie Bod/Linii/Polygon

Import dat: Jak jsem se bavili existuje moznost, ze budou do DB impotovany PIANy "bokem" a to pouze v systemu S-JTSK
Z tohoto duvodu jsem doplnili apliaci dvema CRON JOBy. Kazdy z JOBu je nezavily a spousti se kazde 2 minuty
1./MyCronJobPianToJTSK: tento job je pomocny (neni soucasti objednavky) ma vam pomoci s konverzi databaze pianu WGS84 na S-JTSK, kazde 2 minuty vybere 200 geometrii ve WGS84, ktere nemaji variantu ve systemu JTSK a provede primou konverz, pomoci stejneho aloritmu, ktery se pouziva v DJANGO aplikaci.

2./MyCronJobPianToWGS84: tento job slouzi ke konverzi importovanych geometrii v SJTSK do systemu WGS84. Spousti se tez, kazde 2minuty a pro 200 nalezenych geometrii SJTSK provede spolecne volani https://geoportal.cuzk.cz pomoci ktereho provede zpresnenou konverzi do WGS84.

**Comment by jiri-bartos-huld** [comment]
Jenom upresnim, ze pozadavek na rucni upravu vertexu polygonu je samostatny task, a v tomto tasku je pouze reseno jak prepocet jednoho bodu tak mnoziny bodu mezi obema SS.

**Comment by motyc** [comment]
@jiri-bartos-huld Popis výše je potřeba vhodným způsobem zanést do dokumentace (https://github.com/ARUP-CAS/aiscr-webamcr/wiki), a to spolu s popisem i zbytku řešení GISové části rozhraní. Popis řešení tam v tomto ohledu zcela chybí a je třeba abychom přesně věděli, jak co funguje, co kde lze konfigurovat apod.

Zároveň mám nějaké dotazy:
1) K samotné transformaci pomocí ČÚZK se vyjadřuji v https://github.com/ARUP-CAS/aiscr-webamcr/issues/305#issuecomment-1156513437
2) "provede primou konverz, pomoci stejneho aloritmu, ktery se pouziva v DJANGO aplikaci" - pokud si dobře vzpomínám, zde problémy s přesností nejsou, že ano?
3) Předpokládám, že aplikace k běhu potřebuje mít v pořádku geometrii ve formátu WGS-84, aby mohla data korektně zobrazovat. Pokud je import řešen tak, že se geometrie doplňují postupně po dvou minutách, jak se bude aplikace chovat, dokud se postupně nevygenerují data ve WGS-84? Nemělo by to být spíš součástí procesu importu, aby se rovnou volala transformační služba a data se až následně ukládala?
4) Obdobně ve druhém směru - proč není nevolat transformaci ihned po vytvoření geometrie a uložení do databáze, aby bylo možné dát uživateli zpětnou vazbu v případě, že něco selže, ale dělá se to až takto hromadně po dvou minutách?
5) V případě, že dojde k užití nativní (nepřesné) transformace S-JTSK -> WGS-84, jsou tyto případy nějak označeny, aby mohly být později transformovány lépe? (pokud se vyřeší správná transformace nezávislá na ČÚZK, nebylo by třeba řešit)

**Comment by pesikj** [comment]
@jiri-bartos-huld Jirko, jaký je stav tohoto issue?

**Comment by motyc** [comment]
@jiri-bartos-huld Děkuji za odpovědi.

ad 3  u toho importu tomu nějak rozumím a v podstatě to nějaký zásadní problém není. Je třeba jen vhodným způsobem ošetřit reporting chyb, aby to nebylo závislé na nějakém ručním procházením logu, ale např. aby v případě chyb dostal o problému admin nějakou zprávu. Jinak se může snadno stát, že se tam budou kupit problémy, o kterých nikdo nebude vědět. Máte k tomuto nějaký návrh?

ad 4 -problém ale vidím v tomto druhém případě, tj. při zadávání z aplikace; dám příklad - co se stane, pokud zadám v PAS nález pomocí S-JTSK souřadnic a záznam odešlu? To bude geometrie v mapě v detailu záznamu viditelná až po dvou minutách, kdy dojde k přepočtení na WGS-84 a uložení v tomto formátu do DB? Pokud to funguje, jak popisujete, tak by to asi mělo platit.

ad 5 - ano, ale pokud používáme potenciálně dva algoritmy (velmi nepřesný nativní a ČÚZK), potřebujeme vědět, kdy byl použit který, abychom případně přepočty nativním mohli přepočítat přesněji.

ad 8 - buď jsem se podíval při ověření omylem do špatné tabulky (mohlo se stát), nebo došlo od reportování k opravě na správný stav - nedokážu posoudit, co platí, ale nyní to vypadá v pořádku.

**Comment by jiri-bartos-huld** [comment]
ad 3 - Ok, na to se vubec nemyslelo: Nam se emaily moc nepotvrdili (lide to po case ignoruji). Nelepsi reseni vzdy bylo mit budto custom reportovaci nastroj/script (dole je tabulka kde se vypisuji chyby behem konverze). Nebo to resit v aplikaci v sekci administratora mit neco jako "zpravy administratorovi".

```
CREATE TABLE public.amcr_geom_migrations_jobs(
    id serial primary key,
    typ text not null,
    count_selected_wgs84 integer default 0 not null,
    count_selected_sjtsk integer default 0 not null,
    count_updated_wgs84 integer default 0 not null,
    count_updated_sjtsk integer default 0 not null,
    count_error_wgs84 integer default 0 not null,
    count_error_sjtsk integer default 0 not null,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    detail text default null
);```

**Comment by jiri-bartos-huld** [comment]
@motyc 
ad 5 -mate naprostou pravdu: existuje pripad mene presne transformace
alert("Přesná transformace ze systemu S-JTSK není v současnosti dostupná, proto bude použita méně přesná transformace!")
v tomto pripade se do DB geom_system zapise "sjtsk*" Tedy exclusive S-JTSK anmisto "sjtsk"

**Comment by jiri-bartos-huld** [comment]
wiki https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Presnost-souradnicovych-systemu

**Comment by jiri-bartos-huld** [comment]
1./ geom_updated_at a geom_sjtsk_updated_at se pouziva jen pri hromadne transformaci PIANu pri pouziti importniho nastroje: doplnim do dokumntace
2./ Moje chyba:omlouvam se, kdyz jsem hledal chybu v SamostatnychNalezech tak jsem omilem pouzil jinou verzi amcr, ktera pouzivala velka pismena: opravil jsem jak pro 24 tak 30. Jednalo se o cca 5 chyb
3./overuji

**Comment by motyc** [comment]
@jiri-bartos-huld
1) Ok, ale nebude to třeba i při importování sam. nálezů? Potřeba převodu mezi systémy tam bude vznikat úplně stejně... (viz výše: `Jinak v pořádku, ale vypadlo z toho řešení pro Samostatné nálezy, které nemají PIAN ale souřadnice jsou přímo v tabulce samostatny_nalez (je jasné, že řešit se to bude stejně, jen to tam není zmíněno).`)
2) rozumím, díky za opravu
3) ano, opravdu se to tak dělo; otestuji znovu, až bude nová verze

**Comment by jiri-bartos-huld** [comment]
add 1. pripravena migrace pro SamNalezy
