### ISSUE TITLE
Nastavit maximální přesnost souřadnic

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#307]
Nastavit maximální přesnost pomocí přípustných řádů v daném souřadném systému, a to max na úrovni cm - zbytek lze ořezávat (zbytečně skladujeme falešně "přesná" data):
- WGS-84 - 7 řádů
- S-JTSK - 2 řády

Reseni:
- Bude omezeno jiz pri posilani dat z FE
- Do budoucna pravdepodobne omezi AMCR: nebude mozne presne urcit body na linii: Nebude mozne do DB ulozit presny prusecik dvou linii, atd.

**Comment by ScottVanWagenen** [comment]
exists in Jira
https://huld.atlassian.net/browse/AMCR-45

**Comment by ScottVanWagenen** [comment]
Exists in Jira. Please remove label
https://huld.atlassian.net/browse/AMCR-10

**Comment by jiri-bartos-huld** [comment]
Dobry den, vsiml jsem si ze vetsina tasku tykajici se mapy neni oznacena jako DONE+READY for testing, prestoze vse je nasazeno na serverech 24/34uz od zacatku cervana, nejspise se stav z Jira nepropsal.

Omlouvam se a upravuji stav ticketu+davam info

Info: Za nas implementovano v plnem rozsahu

**Comment by motyc** [comment]
Testováno na https://wamcr-test.aiscr.cz/pas/zapsat, kde to vypadá ok. Prosím ale o referenci na konkrétní commit, protože u jinde to nezkontroluji jinak něž pohledem do kódu.

**Comment by motyc** [comment]
@pesikj @jiri-bartos-huld Zde prosím o reakci na poslední komentář.

**Comment by motyc** [comment]
@jiri-bartos-huld Zde bych potřeboval nějaký popis, jak to mohu ověřit, a chybí mi odkaz na kód, kde se to řeší. Upozorňuji, že nejde o zobrazení (#311), ale omezení při ukládání dat.

**Comment by motyc** [comment]
@jiri-bartos-huld Pokud jsem dobře rozluštil, že k tomuto issue se váže #590, pak z toho nedokážu dovodit, jak to přesně funguje. Prosím o popis do dokumentace. Nejsem si navíc jistý, zda to je nastaveno skutečně všude, tj. nejen pro PAS a 3D, ale též pro PIAN (všechny typy geometrií).

**Comment by jiri-bartos-huld** [comment]
wiki https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Presnost-souradnicovych-systemu
