### ISSUE TITLE
Při ukládání dat do DB kontrolovat validitu geometrií

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#308]
Zadani:
Při ukládání dat do DB kontrolovat validitu geometrií
- self-intersection pro linii a polygon
- příliš krátké segmenty
- polygon s méně než třemi vertexy
- zakazat: Null geometry
- multipart feature (nikdy MP ze vstupu)

Navrhovane reseni:
- implementace pgsql pro ulozeni/update geometrie jednu proceduru pro vsechny tabulky (funkci volat vzdy před ulozenim do DB). Toto reseni je do budoucna nejobecnejsi, protoze nam umozni dodatecne custom validace. Zaroven na rozdil od triggeru nebude blokovat treba existenci multipart v DB.
- Trigger vlastne vynuti ulozeni validni geometrie : [23. Validity — Introduction to PostGIS](https://postgis.net/workshops/postgis-intro/validity.html) 
-- self-intersection polygon - `ST_IsValid`
-- self-intersection linie - `ST_IsSimple`
-- polygon min pocet bodu (3vertexy/4body) - `ST_IsValid`
-- null geometry - `ST_IsEmpty`
-- multipart (zakazat na vstupu) - `ST_NumGeometries`
- Nutne doresit jak se ma system zachovat, kdyz mu je predana nevalidni geometrie
-- System odmitne ulozit fgeom do DB
-- Aplikace zobrazi informaci o nevalidni geometrii: “Geometrie prvku není validní, prosíme zadejte geometrii znovu.“

**Comment by motyc** [comment]
@jiri-bartos-huld
> Dobry den, prosim o vysvetleni:
> 1. prilis kratke segmenty= je to konstanta (treba 20cm), nebo je to slozitejsi vypocet (3% z celkove delky linie) 
> 2. prosim o revizi(provedl jsem upravy)
> 3. Chyba pri ulozeni: pokud dojde k poruseni pravidel pro geometrii, uzivatel dostane hlasku “Geometrie prvku není validní” Prosíme zadejte geometrii znovu. “, tim se rozumi , ze uzivatel ma geometrii smazat a nakreslit znovu. Je to ok, nebo ma uzivatel obdrzet podrobnou hlasku: Linie se krizi atd?

1. Spíše bych dal konstantu (např. <10 cm). Jde o to abychom se vyhnuli dvojklikům, které jsou pod rozlišovacími možnostmi systému. Přesné číslo asi budeme muset otestovat.
2. Revize zanesena a se vším souhlas.
3. Záleží na pracnosti. Pokud není problém být přesný, bude to užitečné, ale pokud je to velká komplikace, klidně stačí obecná hláška.

**Comment by pesikj** [comment]
V JIRA označeno jako Resolved, takže posunuji k testu.

**Comment by pesikj** [comment]
@jiri-bartos-huld Jirko, jaký je stav tohoto issue?

**Comment by jiri-bartos-huld** [comment]
https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Validace-Geometrie

**Comment by jiri-bartos-huld** [comment]
Dobrý den, požadavek na on-line validaci nebyl požadován, navrhuji ho přesunou/zahrnout do rozvoje
1. Jednoduchá validace by mohla být implemntována pomocí AJAX 

- [ ] Uprava globální HTML šablony pro "alerty " při validní/nevalidní geometrii
- [ ] REST connector ná urovni server/python
- [ ] Zajistit, že na všech stránkách kde se edituje geometrie dochází ke správné validaci

2. Problém bude v tom, že uživatel by nejspíeš potřeboval odpověď typu 3 a 4 bod linie jsou příliš blízko sebe. To by znamenalo chybu "Obarvit" nebo dodělat číslování. Toto bude potřeba lepší zadání.
