### ISSUE TITLE
Symbol pro měření vzdálenosti změnit na pravítko

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#310]
Pro lepší srozumitelnost symbol pro měření vzdálenosti změnit na pravítko se stupnicí místo současné šipky

**Comment by jiri-bartos-huld** [comment]
Navrhujeme rovne pravitko:
![obrazek](https://user-images.githubusercontent.com/77389730/191294802-57e34065-238e-4729-a79a-8107c797dcf7.png)
Nkdy se pouziva i trojuhlenik, ale je to mene caste.
![obrazek](https://user-images.githubusercontent.com/77389730/191295015-22dbcc64-8e93-4c28-98f2-1a13446e6f16.png)

**Comment by jiri-bartos-huld** [comment]
@pesikj prosim o zacleneni, zaslano na MR https://github.com/ARUP-CAS/aiscr-webamcr/pull/692
