### ISSUE TITLE
Sjednotit formát výpisu souřadnic

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#311]
Sjednotit formát výpisu souřadnic - někde desetinná tečka, jinde čárka (čárka je v češtině správně)

Navrhovane Reseni: 
1. Cisla reprezentujici souradnice sjtsk budou ve formatu desetine carky
2. Cisla reprezentujici souradnice wgs84 budou prevedena do formatu s des. carkou
3. Zobrazeni aktualni souradnic WGS84 na mape: Nahled je v systemu DEC (des. carka), a editace je v systemu DEC (des. carka)

Zasazene stranky (1,2,3):
- amcr/pas/create 	:Samostatne nalezy: Zapsat
- amcr/pas/detail/X	:Samostatne nalezy: Moje nalezy
- amcr/pas/edit/X	:Samostatne nalezy: Moje nalezy -editace

Zasazene stranky (2,3): 
- amcr/dokument/create/model	:Knihovna 3D: zapsat 
- amcr/dokument/detail/model/X	:Knihovna 3D: detail 
- amcr/dokument/detail/model/X	:Knihovna 3D: editace  

Zasazene stranky (3): 
- amcr/projekt/create 
- amcr/projekt/detail/X 
- amcr/projekt/edit/X 
- amcr/arch_z/detail/X

**Comment by jiri-bartos-huld** [comment]
Dobry den, vsiml jsem si ze vetsina tasku tykajici se mapy neni oznacena jako DONE+READY for testing, prestoze vse je nasazeno na serverech 24/34uz od zacatku cervana, nejspise se stav z Jira nepropsal.

Omlouvam se a upravuji stav ticketu+davam info

Info: Za nas implementovano v plnem rozsahu:
Pro info davam asi nejdulezitejsi zmenu v podobe zmeny DD na DEC pro stupnove miry(WGS84)
Nahled:
![image](https://user-images.githubusercontent.com/77389730/173814065-c554b072-1136-4865-8030-90bf8251c4e0.png)
Editace:
![image](https://user-images.githubusercontent.com/77389730/173814140-8f6820c6-abed-4c2c-9e27-20e64ea765ba.png)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] chybně užíváno ve formulářích PAS (zapsat, edit, detail - pole Šířka a Délka)
