### ISSUE TITLE
Katastry akce/lokality automaticky odvozovat ze zadaných PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#315]
Katastry akce/lokality automaticky odvozovat ze zadaných PIAN:
- Hlavní katastr se dovozuje z první DJ
-- bod - poloha
-- linie - střed (na linii)
-- polygon - centroid (uvnitř)
- Vše ostatní (průnik) do dalších katastrů

Detailni zadani:

1. stranka: http://lamcr/projekt/zapsat
pole hlavni katastr odvodit z geometrie zadaneho bodu
dalsi katastry se zadavaji pouze rucne

2. strana: http://lamcr/pas/zapsat
pole katastralni uzemi odvodit z geometrie zadaneho bodu

3. strana: http://amcr/projekt/edit/C-202105929
pole hlavni katastr odvodit z geometrie zadaneho bodu
dalsi katastry: jsou zadavany rucne nebo se odvozuji ze vsech Akci?

4. http://localhost:8000/arch-z/akce/detail/C-202105929A
pole hlavni katastr odvodit z geometrie nebo pianu prbni Dj
dalsi katastry: jsou zadavany rucne nebo se odvozuji ze vsech Dj nebo pouze prvni Dj a jejim prunikem do jinych kat.uzemi?

**Comment by jiri-bartos-huld** [comment]
@motyc prosim o upravu zadani: pokusil jsem se to nastinit aby to nebylo jen bodove, ale na nekterych mistech se mi zadani nezda jenoznacne

**Comment by motyc** [comment]
Doplnil jsem čísla a reaguji:
1) Ano, to už by mělo být hotové a nic se v tomto nemění.
2) dtto
3) Nic se nemění, mluvíme pouze o PIAN.
4) hlavní - ok; další: odvozují se z průniku všech DJ do jednotlivých kat. území

**Comment by motyc** [comment]
@jiri-bartos-huld Doplnil jsem čísla a reaguji:
1) Ano, to už by mělo být hotové a nic se v tomto nemění.
2) dtto
3) Nic se nemění, mluvíme pouze o PIAN.
4) hlavní - ok; další: odvozují se z průniku všech DJ do jednotlivých kat. území

**Comment by jiri-bartos-huld** [comment]
@motyc 
Jeste drobnosti k bodu 4.
Ma uzivatel moznost zadat "dalsi katastry" rucne, nebo je tato funkcionalita vyhrazena pouze automatickemu dohledavani?

**Comment by motyc** [comment]
@jiri-bartos-huld V případě akcí/lokalit (#319) nebudou ruční doplnění ani editace možné. U projektu zůstane, protože projekt definujeme bodem (přinejmenším prozatím).

**Comment by jiri-bartos-huld** [comment]
Informace o implemetaci:
1./ Opraveno projekt edit, tlacitko vychozi stav, vrati se puvodni poloha bodu vcetne puvodniho katastru
4./
Pokud nema prvni DJ vyplneny PIAN, pro Hlavni kat. uzemi se pouzije prvni vyplneny DJ s PIAN
Ostatni katastry se vyplnuji v ABCednim poradi
![obrazek](https://user-images.githubusercontent.com/77389730/195074677-201deb64-143d-4603-b688-cd3f1752b2c4.png)
V databazi se upravuji nasledujici tabulky
**PUBLIC.archeologicky_zaznam** slopec **hlavni_katastr**
**PUBLIC.akce**  sloupce **katast** (odpovida halvnimu katastru), **dalsi_katastry**(ostatni katastry)

**Comment by motyc** [comment]
@jiri-bartos-huld 
Vše ok, jen mi není jasné proč duplikujeme sloupec archeologicky_zaznam.hlavni_katastr ještě v akce.katastr? Není to nějaké zmatení, protože DB je na serveru 24 ve špatné podobě/verzi? I pro vývoj by se měla používat verze DB na serveru 30, po zohlednění oprav podle #474.

**Comment by motyc** [comment]
@jiri-bartos-huld
Mám nějaké dotazy kvůli kompatibilitě se starými daty (#315) a celkově kvůli tomu, že heslář katastrů bude s časem procházet změnami s tím, jak se mění RÚIAN (#372). V takové chvíli se může začít rozcházet aktuální skutečnost při novém zápisu s již uloženými staršími daty.
1) Pokud nebude u starých dat napojení katastrů odpovídat geometrii PIAN, bude s tím aplikace mít nějaký technický problém?
2) Pokud otevřu záznam, u kterého již je napojen PIAN a má doplněné katastry, v jaké chvíli nyní dojde k jejich automatické aktualizaci? Až po nějakých úpravách PIAN/DJ, nebo i bez uživatelského zásahu do záznamu?
3) Aktualizuje se napojení vždy kompletně pro celý arch. záznam, nebo se vyhodnocují jen změny, které souvisí s konkrétními PIAN/DJ?

**Comment by motyc** [comment]
### Výsledek testu
Funguje to moc pěkně, kromě jediného:
- [ ] pokud je PIAN u první DJ typu linie či polygon, hlavní katastr má být u linie nastaven podle polohy středu linie a u polygonu podle centroidu uvnitř polygonu - to se nyní nezohledňuje a rozdělení mezi hlavní a další katastry nemá jasný klíč (viz např. http://192.168.254.30:8080/arch-z/lokalita/detail/C-N0000002)
- [ ] Prosím také o odpověď na otázky položené v komentáři výše (nějakou přesdstavu jsem sice už získal, ale raději bych to měl explicitně):
-- 1 - Pokud nebude u starých dat napojení katastrů odpovídat geometrii PIAN, bude s tím aplikace mít nějaký technický problém?
-- 2 - Pokud otevřu záznam, u kterého již je napojen PIAN a má doplněné katastry, v jaké chvíli nyní dojde k jejich automatické aktualizaci? Až po nějakých úpravách PIAN/DJ, nebo i bez uživatelského zásahu do záznamu?
-- 3 - Aktualizuje se napojení vždy kompletně pro celý arch. záznam, nebo se vyhodnocují jen změny, které souvisí s konkrétními PIAN/DJ?

**Comment by jiri-bartos-huld** [comment]
1.Nyni je opraveno: Pri zalozeni akce zadam ku:troja, posleze zadam pian P-1224-102337 a Hlavni ku se zmani na Sedlec
![obrazek](https://user-images.githubusercontent.com/77389730/206929661-f420d9f4-7ff1-457e-a717-0f734c5098b9.png)

**Comment by jiri-bartos-huld** [comment]
Otazky:
1./Na technicky problem jsem nenarazil, applikace neprovadi zadne dodatecne kontroly.  Pouze pokud provedete znovu zmenu pianu na prvni DJ, tak se kat.uzemi aktualizuji jinak zustava vse neaktualni
2./pouze pokud provedete aktualizaci dj/pian vcetne ulozeni
pokud tedy provedete zmenu v DB/jinym nastrojem, tak se zobrazuje neaktualizovany udaj
Navrhuji do budoucna pozadovat, budto  aktualizaci/upozorneni pri nacteni zaznamu nebo DB job, ktery bude hledat chyby/opravovat zaznamy
3./Vzdy konkretni DJ

**Comment by jiri-bartos-huld** [comment]
pripraveno na MR
