### ISSUE TITLE
Upozornění pro uživatele při překryvu prvků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#316]
Někam k mapě jasně napsat pro uživatele, že musí kliknout pravým tlačítkem, aby mohl posouvat pořadí prvků při překryvu.

Reseni:
1. Pri vyberu PIAN kliknutim levym tlacitkem bude vzdy zobrazen po dobu 3 skeund vpravo dole messagebox
s textem: "Pro vyber jineho prvku kliknete pravym tlacitkem"
2. MessageBox se bude zobrazovat jen v pripade, ze bude mozne vybrat jiny prvek. Tj v pripade, ze uzivatel klikne na prvek, ktery je osamocny, tak se messageBox nezobrazi
3. V ramci tohoto tasku by melo byt dodelano zacleneni tento typ messageboxu do vsech mapovych podkladu (v budoucnu mohou existovat podobne pozadavky jinde), tak aby vse slo pouzit do budoucna (toto nenavysuje cenu tasku)

https://github.com/tinuzz/leaflet-messagebox

Zasazene stranky bodem 1.,2.: amcr/arch_z/detail/X
Zasazene stranky bodem 3: oznameni, spolecna sablona pro 3d a SN

**Comment by jiri-bartos-huld** [comment]
@motyc provedl jsem doplneni o bod 2,3 (nenavysuji cenu tasku), prosim o kontrolu

**Comment by motyc** [comment]
@jiri-bartos-huld Se vším souhlas, děkuji.

**Comment by jiri-bartos-huld** [comment]
Obecny message box by mel vypadat nejak takto:
1./Bude to obecna komonenta pro praci se zpravami (obazek je pouze ilustrativni chybi zde zmet car pres sebe)
2./Komponenta bude pracovat jako zasobnik, tj. bude umoznovat zobrazit vice hlasek pod sebou s ruznou delkou platnosti.
3./Pro tento typ hlasky zde bude omezeni, ze v jeden okamzik bude moc byt zobrazena pouze jedna hlaska tohoto typu.

![obrazek](https://user-images.githubusercontent.com/77389730/191295842-f8c4640d-3f2e-485f-a27f-ac0f3cbe3b03.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Za mne je řešení v pořádku, rád bych ale upozornil, že tento úkol není součástí aktuální objednávky. Do té spadá jen [Sprint 4](https://github.com/ARUP-CAS/aiscr-webamcr/milestone/9).

**Comment by motyc** [comment]
@jhavrlant Ano, u akci a lokalit. Nastaveni jinak zni dobre.

**Comment by motyc** [comment]
### Test v0.4.75
(zatím zkouším na dev, než bude na testu)
- [ ] Při běžném klikání funguje v pořádku, nicméně hláška se nezobrazí v nejdůležitější chvíli, tj. s aktivovanou funkcí "PIAN- připojit z mapy":
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/70a73c91-fb2f-41ab-bac3-9076488eb759)

**Comment by jhavrlant** [comment]
@motyc Přidal jsem tam zvýraznění prvku při najetí na název pianu v bublině přenést do popředí

**Comment by motyc** [comment]
@jhavrlant Bezva!
