### ISSUE TITLE
Úprava pole PIAN ve formuláři DJ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#317]
Pole “Pian” ve formuláři je matoucí
- [x] - Připojený ve výchozím režimu pouze vypsat (tj. převést pole na neaktivní).
- [x] - Do nabídky možností doplnit “Připojit PIAN podle ID”, která umožní změnu PIAN výběrem ze seznamu

**Comment by jnihnat** [comment]
@motyc chceme tento update delat cez modal okno jen pro vyber pianu, nebo jen pole enablovat, nechat uzivatele vybrat a ulozit standardne jako ted?

**Comment by motyc** [comment]
@jnihnat Oboje je v pořádku. Vyberte variantu, která bude lepší z technického hlediska.

**Comment by motyc** [comment]
Odhalena chyba - funguje správně při editaci, ale pole je stále aktivní při zápisu nové DJ. Zde zcela odstranit.

![image](https://user-images.githubusercontent.com/20186892/171844305-5f17ccf4-778d-417c-bcc0-b91500eb3b7e.png)

**Comment by jnihnat** [comment]
@motyc chceme pri zapisu mit tlacitko pro enablovani pole?

**Comment by motyc** [comment]
@jnihnat nene, tam neni potřeba
