### ISSUE TITLE
Modul Samostatné akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#318]
Jedná se o ekvivalent projektových akcí (http://192.168.254.30:8080/arch-z/akce/detail/ a související view) s následujícími rozdíly:
- [x] - Samostatná akce existuje bez vazby na projekt (rozlišit lze podle “N” v poli “typ”)
- [x] - Má samostatnou položku “Samostatné akce” na úvodní obrazovce (zelená - #247e4b) a související menu, s volbami:
- Zapsat akci (otevře obdobu http://192.168.254.30:8080/arch-z/akce/zapsat/)
- Vybrat akce (výběr umožní vyhledat i projektové akce v případě patřičné volby ve filtraci; https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1110658884)
- Moje akce (pouze podmnožina výběru)
- Archivovat akce (pouze podmnožina výběru)
- [x] - Formulář detail obsahuje navíc:
- pole Odložená NZ - pokud je “Ano”, lze odeslat bez dokumentu typu “nálezová zpráva” (funguje obdobně jako pole “Odeslat ZAA jako NZ”) - _Teoreticky lze řešit i volbou v rámci odeslání akce (podle toho by se údaj doplnil do DB) - nebylo by pak nutné upravovat formulář. Informace, že jde o akci s odloženou NZ, bychom doplnili na nějaké jiné smysluplné místo._
- možnost měnit Specifikaci data + související úpravy chování polí pro jeho zadání (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/36)
- [x] - Při volbě typu první DJ je možné zadat typ “Katastrální území” (původně v AMČR nazváno “Nelokalizovaná akce” - pouze přejmenovat). Pokud se tak stane:
- k DJ je automaticky připojen PIAN katastru podle uživatelské volby (nutno dohodnout, jak přesně uživatel vybere katastr, když pro akce s PIAN jej budeme stanovovat automaticky a pole ve formuláři je neaktivní)
- nelze přidávat další DJ
- [x] - Umožnit archiváři snadno převést projektovou akci na samostatnou a naopak (zadáním čísla projektu, ke kterému se má připojit). Při tom obsah zůstane stejný, pouze se změní identifikátory a operace se zapíše do historie záznamu.
- [x] - Vzniká s dočasným ID (“X-” na začátku), trvalé ID je přiděleno při první archivaci (při jakékoli další změně stavu se již nemění). Struktura ident_cely odpovídá schématu:
[region]-[číslice 9][šestimístné pořadové číslo][písmeno "A"]; celkem 10 znaků
Příklad: C-9000001A
Pořadové číslo 1-999999, k němuž se přičítá 9,000,000.
Má verzi s provizorním ID: X-C-9123456A
Tvorbu řady je třeba ošetřit obdobným způsobem jako např. pro projekty (viz https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely)

**Comment by jnihnat** [comment]
@motyc mnel bych dotazy k zadani:
add bod 3 - takze Samostatna akce bude mit pole "Odlozena NZ" a soucasne "Odeslat ZAA jako NZ"? k druhe casti, vyberte si jak to chcete, je to mozne mit jak ve formulari jako nove pole tak v modale pro odeslani. Stejne bych to ale pridal na Detail aby to uzivatel videl proc akce nema dokument.
add bod 3 - Specifikace data - spravne chapu, ze pri zmene na moznost s ... v letech, tak se pole zmeni na "ciselny input kde user zada jen cislo" a my si pak ulozime a budeme zobrazovat rok s prvnim dnem napr. 2022-01-01? Bude mozne pole menit pri editaci, nebo ne?
add bod 4 - Katastrelni uzemi je mozne vybrat jen pro prni DJ?
add  bod 4 - stanovovat bychom ho mohli s hlavniho katastru, ten bude muset byt vyplneni pri vytvareni akce bez projektu.
add bod 4 - co kdyz ma katastr vice pianu? Ktery pian se vybere?
add bod 4 - nelze pridavat dalsi DJ? jen v pripade katastralniho uzemi?
add bod 5 - chapu zmenu identifikatoru, predpokladam, ze to zmenime u vsech odvozenych identifikatoru take? DJ, komponenty, dokumenty, soubory dokumentu?
add bod 5 - jak se ma nazyvat dana akce v historii? Chceme pri zmene jen zadani projektu podle ID? ma se nejak zobrazit "tabulka s vybranym projektem a tam nejake info o nem? Jako mame pri pripojovani dokumentu?

Dekuji za odpovedi.

**Comment by motyc** [comment]
@jnihnat
ad 3a - Ano, budou obě možnosti. V praxi by nikdy nemělo být použito obojí současně (to klidně i testujte programově). Jinak se asi více přikláním k variantě, že půjde o volbu ve formuláři - bude to přehlednější asi bude snadnější řešit ten vzájemný vztah k "Odeslat ZAA jako NZ".
ad 3b - tady je to trošku složitější; v DB máme dvě (resp. čtyři) pole` datum_zahajeni` a `datum_zahajeni_v` (obdobně pro ukončení); pokud vyberu specifikaci s "... v letech", změní se pole jak říkáte a tato hodnota se tak, jak je, přenese do pole `datum_zahajeni` (např. "2022"), přičemž do `datum_zahajeni_v` se automaticky doplní "2022-01-01" (pro ukončení by to bylo "2022-12-31"). Zobrazovat ve formuláři se nadále bude `datum_zahajeni`; `datum_zahajeni_v` ale bude používáno při vyhledávání. Měnit při editaci by mělo vše jít standardně. Takto to funguje i nyní a na nic lepšího, co by zachovalo výhody obojího, jsme nepřišli, a je tomu uzpůsobená i migrace (viz #36).

ad 4a - ano
ad 4b - ok, jen musí být v takovém případě umožněna i editace...
ad 4c - katastr nemůže mít více PIAN - vazbu definuje pole `ruian_katastr.pian`
ad 4d - ano, souvisí to s 4a

ad 5a - ano, správně
ad 5b
-- historie - tady nerozumím otázce, můžete prosím upřesnit? Myslíte, jak se má změna typu záznamu zaznamenat do historie?
-- ano, stačí zadání podle ID projektu
-- ano, posupovat jako u připojení dokumentu by bylo dobré, omezí se tím potenciální chyby

**Comment by jnihnat** [comment]
@motyc 
ad 5b - ano presne to myslim jak se to ma zapsat do historie.
dalsi dotaz k datum zahajeni a ukonceni. - Tedka tam je validace ze nemuzou byt vetsi nez mesic do budoucna, Pokud specifikace nebude "presne" tak nedava zmysel, tam sem ji odstanil, Ale pro jistotu, pro specifikaci presne to ma ostat?

**Comment by motyc** [comment]
@jnihnat
- 5b - Zapsal bych to jako "Změna typu" a do poznámky uvedl akce.ident_cely před změnou a po změně (např. takto: "C-9145699A -> C-201120178")
- validace - pro "přesně" validaci zachovejte; pro další varianty to prosím omezte tak, že nepůjde zapsat vyšší než aktuální rok
- stavy - to je dobrá poznámka; omezení podle stavu akce není potřeba; omezení u projektu by mělo být podle typu i stavu:
-- nesmí jít přiřadit k projektu typu "průzkum", kde se s akcemi vůbec nepracuje
-- projekt musí být v některém ze stavů v rozmezí P3-6

**Comment by motyc** [comment]
@jnihnat Moc se omlouvám, ale v návaznosti na upozornění v jiném issue (https://github.com/ARUP-CAS/aiscr-webamcr/issues/474#issuecomment-1302189339) jsem zjistil, že jsem podal trošku zavádějící odpověď k té specifikaci data:
> ad 3b - tady je to trošku složitější; v DB máme dvě (resp. čtyři) pole datum_zahajeni a datum_zahajeni_v (obdobně pro ukončení); pokud vyberu specifikaci s "... v letech", změní se pole jak říkáte a tato hodnota se tak, jak je, přenese do pole datum_zahajeni (např. "2022"), přičemž do datum_zahajeni_v se automaticky doplní "2022-01-01" (pro ukončení by to bylo "2022-12-31"). Zobrazovat ve formuláři se nadále bude datum_zahajeni; datum_zahajeni_v ale bude používáno při vyhledávání. Měnit při editaci by mělo vše jít standardně. Takto to funguje i nyní a na nic lepšího, co by zachovalo výhody obojího, jsme nepřišli, a je tomu uzpůsobená i migrace (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/36).

Ve skutečnosti je to tak, že jsme pole datum_zahajeni_v a datum_ukonceni_v zmigrovali a odstranili (jak popisuje #36). Byl to logický krok ke zjednodušení fungování aplikace a následných filtrací. V aplikaci by to tedy mělo fungovat takto:
- specifikace "přesně" - ve formuláři jsou dvě pole pro zadání přesných datumů; do DB se uloží tak, jak jsou vyplněny
- specifikace "přesně v letech" nebo "někdy v letech" - ve formuláři jsou dvě pole pro zadání roku; do DB se uloží rrrr-01-01 pro zahájení a rrrr-12-31 pro ukončení

Nic složitějšího v tom není a opravdu se omlouvám, že jsem to popsal chybně. Podle https://github.com/ARUP-CAS/aiscr-webamcr/pull/710/files mám ale dojem, že jste to implementoval (správně) tak, jak to popisuji nyní.

**Comment by jnihnat** [comment]
Jo presne tak som to nakonec udelal, bylo to i jednoduchsi nez to ukladat do dvou ruznych poli.

**Comment by motyc** [comment]
### Výsledek testu
(test filtračního formuláře ještě probíhá, výsledky dáme zvlášť)
- [ ] zmizela možnost přejít zpět z projektové akce na projekt
- [ ] z detailu akce zmizela tabulka “Další vedoucí” (v zápisu a editaci zůstala)
- [ ] převod na akce na projektovou a naopak má být dostupný i pro admina (pardon za nepřesnost zadání, ale běžně to tak chápeme a nedošlo mi to; oprávnění hlavních vždy fungují kumulativně, tj. co může badatel, může archeolog atd.; když tedy něco může archivář, může to dělat i admin)
- [ ] odvozování dočasného ident_cely by mělo fungovat jako např. u projektu, tj. nemělo by docházet k tomu, že se jedno ID používá opakovaně: https://github.com/ARUP-CAS/aiscr-webamcr/blob/bb482358a3e5f1c46545c4792b7a8dfb2fdab38a/webclient/core/ident_cely.py#L27
- [ ] pod položkou menu “Archivovat” - je třeba zobrazovat záznamy ve stavu 2, nikoli 3 (tj. ty, které je potřeba archivovat: http://192.168.254.30:8080/arch-z/akce/vyber?stav=2)
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber - výchozím režimu se nemají zobrazovat projektové akce (http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False) - platí pro Vybrat, Moje i Archivovat; volba přes filtraci návic teď vůbec nefunguje (dá stejný výsledek pro obě varianty - to může být problém v datech; nejjistější by bylo dívat se, zda je cizí klíč v poli akce.projekt)
- [ ] když použiji specifikaci data “přesně”, datum zahájení a ukončení se nikdy neuloží (pole jsou po uložení prázdná)

**Comment by jnihnat** [comment]
@motyc  - odvozovani od id v db jako je u projektu neni mozne, kvuli tomu ze id v db je uz vetsi nez 999 999. (v zadani je Pořadové číslo 1-999999, k němuž se přičítá 9,000,000.)
Muzu upravit jen at to bere nejvetsi poradove docasne ident cislo a k tomu pricitam 1. To se ale dostavame do stejne patove situace, protoze ak budu mit X-M-9000006A, zarchivuju na M-9000006A, tak opet budu moct vytovrit X-M-9000006A ak mezi tim nevznikne dalsi. jedina dalsi moznost je udelat sequenci, otazka je ale ci to je naozaj potrebne. podle kodu nikdy nevznikne stejne ID soucasne.

**Comment by jnihnat** [comment]
@motyc este som natrafil na jeden problem, v DB jsou tedka ty ID doplnovane podle ID predpokladam ze stare DB, a teda nektere maji 7 cifer a nektere 8, priklad:
X-M-9714160A
X-M-91008636A
X-M-9715731A
X-M-9743375A
X-M-91071998A

**Comment by motyc** [comment]
@jnihnat To je zajímavé. Prověřím to na produkčním serveru a pokud to bude problém i tam, řešil bych to při migraci úpravou do jednotného formátu. Předpokládám, že trvalých ID se to netýká, že ano?

**Comment by jnihnat** [comment]
Trvale ID vypadaji OK.

**Comment by jnihnat** [comment]
@motyc opraveno vse v #786 az na:
- docasny ident, pred opravou potrebuji vedet co udelame a upravit stavajici data, at muzu radne nastavit sekvenci. (mozna potom lepsi videlit jako samostatne issue?)
- katastr ve filtraci - plati to same co pro lokality, udelal bych to najednou v #328

**Comment by motyc** [comment]
@jnihnat Prověřil jsem to na produkci a je tam 81 akcí s kratší verzí (12 znaků) a ca 1300 z delší (13 znaků). Dokonce je zcela zřejmé, jak to vzniklo - je to odvozováním dočasného ident_cely z id záznamu! :) Tím pádem navrhuji následující - nadále odvozovat ten dočasný ident_cely z id, i když to bude znamenat, že dočasný ident bude většinou delší, než ten finální. Ničemu to nevadí. Nemusíme tím pádem vůbec řešit ani ty stará data. Souhlasíte, nebo přehlížím nějaký problém?

S katastry souhlas.

**Comment by jnihnat** [comment]
Upraveno v #788 Upravil som aj regex pro presmerovani podle id.

**Comment by motyc** [comment]
### Výsledky testu
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9109620A/dj/C-9109620A-D01/komponenta/detail/C-9109620A-K001
-- když je akce ve stavu A3, tak je  pole komponenta.jistota prázdné, i když v DB je “true”
-- když je akce ve stavu A2, zobrazuje se “Ne”, i když to neodpovídá DB (tam je “true”)
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9001325A/dj/C-9001325A-D01 - error 500 (obecně všechna zobrazení ADB)

Filtrace (http://192.168.254.30:8080/arch-z/akce/vyber a odvozené)
- [ ] akce.filter.zahrnoutProjektove
-- nemůže být multiselect a nemělo by obsahovat prázdnou hodnotu (je to v podstatě přepínač)
-- pokud použiji položku “Archivovat”, sice tam nejsou projektové akce, ale ve filtru to není vidět; výchozí URL je proto asi třeba upravit na: http://192.168.254.30:8080/arch-z/akce/vyber?stav=2&zahrnout_projektove=False (nebo by “Ne” mělo být ve formuláři jako výchozí hodnota - záleží tedy i na předchozím bodu))
- [ ] akce.filter.terenniZjisteni
-- má být pozitivní (místo ano) a negativní (místo ne)
-- vrací chybné výsledky - při zaškrtnutém “ano” vrátí i negativní záznam http://192.168.254.30:8080/arch-z/akce/detail/C-9143108A
- [ ] akce.filter.odlozenaNz - funguje dobře, ale mělo tam být podle zadání pole pro “ZAA jako NZ”; to prosím doplnit, ale odlozenaNZ zachovat také (bylo pro filtraci opomenuto) - opraveno v: https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1110658884)
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber?komponenta_jistota=False - najde i akce bez komponenty, nikoli jen ty, kde je v komponenta.jistota hodnota “false”
- [ ] akce.filter.adbRoky - formát by měl být jen RRRR
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber?vlastnik=1898 - řešení přes vlastníka není šťastné, protože když pak aplikuji libovolný jiný filtr, tento parametr se odebere; lepší řešení je: http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_typ_zmeny=AZ01&historie_uzivatel=1898 (to řeší i problém popsaný v #766)

**Comment by jnihnat** [comment]
posledni bod bych presunul do #766 jak zminujete. Je to u vsech vyberu krome projektu, teda i u starych 3D modelu, proto je to stejne i u novych, kde jsem cerpal inspiraci jak to uz je naprogramovane.

**Comment by motyc** [comment]
@jnihnat Ok, přeházím to vše tam a doplním i pro ostatní moduly

**Comment by sedmar** [comment]
@jnihnat souvisí s #780

**Comment by jnihnat** [comment]
@motyc - k  akce.filter.terenniZjisteni - to byla chyba jmena, bylo to filtrovani pole ZAA jako NZ, ktere jsem jeste opravil. k polu terenni zjisteni, ktere pole se nim ma filtrovat prosim?

**Comment by motyc** [comment]
@jnihnat U "Terénní zjištění" - to lze opsat z http://192.168.254.30:8080/projekt/vyber, ale v principu je to nastaveno tak, že:
- pozitivní - akce má alespoň jednu pozitivní DJ
- negativní - akce má pouze negativní DJ
Viz:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/2c21113f0477954b1386bac839672d9ad8537169/webclient/projekt/filters.py#L487

**Comment by jnihnat** [comment]
@motyc - ten filter mame jako lokalita.filter.djZjisteni.label, teda v sekci DJ a Pian.

**Comment by motyc** [comment]
@jnihnat Tam je ale něco jiného - tam se to vztahuje na to, zda je tam nějaká DJ s danou hodnotou v daném poli; tady se to řeší souhrnně pro celou akci. Ve filtraci neumíme dělat negace, takže ta druhá varianta (negativní akce) by nešla nijak vybrat...

**Comment by jnihnat** [comment]
@motyc asi uz zacinam chapat, teda:
negativni akce = akce ma DJ ktere maji vsechny jen negativni_jednotka = True
pozitivni akce = akce, ktera ma aspon jednou DJ, ktera ma negativni_jednotka=False
pokud ne, tak prosim jeste o dovysvetleni. Jinak pokud plati to nahore, tak to je spatne i u projektu pokud to ma byt stejne.

**Comment by motyc** [comment]
@jnihnat Potvrzuji.

**Comment by jnihnat** [comment]
zjisteni opraveno v #813

**Comment by motyc** [comment]
### Výsledek testu
- [ ] - filtrace podle Terénní zjištění (http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&has_positive_find=True) vrací error 500

Jinak ok.

**Comment by jnihnat** [comment]
> ### Výsledek testu
> 
>     * [ ]  - filtrace podle Terénní zjištění (http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&has_positive_find=True) vrací error 500
> 
> 
> Jinak ok.

mini chyba, opraveno v #821
