### ISSUE TITLE
Modul Lokality

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#319]
Jedná se o ekvivalent samostatných akcí (#318), od kterých se odlišuje následujícím:
- [x] Související URL budou mít schéma http://192.168.254.30:8080/arch-z/lokalita/* (dále jako u akce)
- [x] Formuláře mají odlišný obsah (https://docs.google.com/spreadsheets/d/1jwzkkpbFgAiywPsET54y5Spwrr6gv8-FLiOUJoQcQL0/edit)
- [x] Položka “Lokality” na úvodní stránce je fialová (#951e7a), položky v menu jsou:
- Zapsat lokalitu
- Vybrat lokality (https://docs.google.com/spreadsheets/d/1jwzkkpbFgAiywPsET54y5Spwrr6gv8-FLiOUJoQcQL0/edit#gid=1110658884)
- Moje lokality
- Archivovat lokality
- [x] Má vždy pouze jednu DJ, omezenou na typy:
- Lokalita
- Katastrální území
(v důsledku tak vypadává celá část dotýkající se ADB, protože se týká jen sond)
- [x] Odeslání je možné i bez připojení dokumentu typu “nálezová zpráva”.
- [x] Struktura ident_cely odpovídá schématu:
[region]-[písmeno podle typu lokality][sedmimístné pořadové číslo]; celkem 10 znaků
Příklad: C-N1000001, C-L1000001, M-K1000001
Písmena podle typů jsou: N – nemovité archeologické památky; L – letecké lokality; K – krajinné prvky
Má verzi s provizorním ID: X-C-N1234567

**Comment by jnihnat** [comment]
@motyc 
Zdravim, zacal sem na implementaci modulu, zatim mam tyhle otazky:
- pole "Jistota urceni" je z heslare, nevim ale najit z ktereho, pomuzete prosim?
- jak by mnela vypadat tabulka na strance vyber? Potreboval bych sekvenci poli a defaultne zobrazene polia
Dekuji za odpovedi.

**Comment by motyc** [comment]
@jnihnat
- jistota určení - Jde o nové polev DB a heslář není v původní AMČR; totéž platí pro stav dochování (pozor, neplést se zachovalostí u dokumentu); hesláře přikládám zde: [heslare_lokality_doplneni.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/9674165/heslare_lokality_doplneni.xlsx)
- všechny tabulky asi budeme ještě v tomto smyslu revidovat najednou příští rok, ale nastavme to tak, abychom zobrazovali pole:
-- ident_cely
-- stav
-- pristupnost
-- hlavni_katastr
-- typ_lokality
-- druh
-- nazev
-- zachovalost
-- jistota

a defaultně vypnutá, ale zobrazitelná:
-- uzivatelske_oznaceni
-- dalsi_katastry

**Comment by jnihnat** [comment]
@motyc 
prichazim s dalsim setom otazek:
- v google sheets pre Zapsat a Edit chybi mapa, ma tam byt? Pripadne kde? Predpokladam pak stejnu funkcionalitu jako u Projektu
- jak to ma byt s polem Dalsi katastry? V google sheets je vzdy disabled a z mapy, ale u projektu to funguje normalne jako heslar.
- maji byt hlasky a tlacitka vzdy jako Lokalita uspesne zapsana a pak Akce uspesne zapsana, nebo bude stacit jedna Archeologicky zaznam uspesne zapsan?

**Comment by jiri-bartos-huld** [comment]
@motyc @jnihnat 
Dobry den pridavam se s dotazy:
1./Zapsat Lokalitu neni mapa,je to tak spravne?
2./Pokud mam zalozenou Lokalitu , tak smim pridat je jedenu nobo vice DokumentacnichJednotek?


![obrazek](https://user-images.githubusercontent.com/77389730/194778315-eae4dee8-fba4-4f71-a962-ec82d22c4525.png)

**Comment by jnihnat** [comment]
@jiri-bartos-huld 
1. viz dotaz ode mne na @motyc koment vis.
2. bod 4 v description - Lokalita ma jen 1 DJ. proto tam je i omezeni.

**Comment by motyc** [comment]
@jnihnat
1) mapa je v detailu, nikoli v zapsat/editovat, protože jde o ekvivalent obrazovky akce (http://192.168.254.30:8080/arch-z/akce/detail/C-200912907A; http://192.168.254.30:8080/arch-z/akce/edit/C-200912907A atd.), nikoli obrazovky projektu
2) to souvisí s funkcionalitou #315, která je rovněž součástí této objednávky; vše se bude vyplňovat automaticky
3) asi bych to raději oddělil, bude to lepší do budoucna, pokud by se to nějak mělo nějak upravovat

@jiri-bartos-huld 
1) ano
2) jak píše @jnihnat, jen jednu

**Comment by jnihnat** [comment]
Upravim teda zapis, kde bude se bude ukladat Lokalita bez katastru. Rovnez pak Edit, kde bude jen readonly pro oba fieldy. Doplnovani paj udela Jirka, uz ale asi v ramci issue #315 - prosim pak potvrd ze to udelas v ramci toho.

Hlasky udelam teda oddelene.

@jiri-bartos-huld - napis prosim teda ci jeste budes delat neco v ramci tohoto issue, at pripadne vim ci uz delat merge. Vdaka

**Comment by jiri-bartos-huld** [comment]
@motyc Dobrry den, mam doplnujici dotazy
1./Pri zakladani Lokalit, ma uzivatel pravo zadat rucne jak Hlavni tak i dalsi Katastralni uzemi, je to spravne?
2./Pri zadani PIAN do DJ by bylo vhodne nekam ulozit i katastralniUzemi toho pianu (tech kat. uzemi muze byt i vice), patri vsechny do dalsich kat.uzemi?

**Comment by motyc** [comment]
@jiri-bartos-huld
1) Ne, katastry zůstanou prázdné, dokud nebude vyplněn PIAN nebo použita funkce pro zadání DJ typu "Katastrální území" (kde je je třeba mít možnost katastr vybrat).
2) Ano, to je správné chování, díky za podnět. Takto to bude platit vždy pro funkci #315.

**Comment by motyc** [comment]
@jiri-bartos-huld Je to popsáno v #315:

> Katastry akce/lokality automaticky odvozovat ze zadaných PIAN:
> 
> Hlavní katastr se dovozuje z první DJ
> -- bod - poloha
> -- linie - střed (na linii)
> -- polygon - centroid (uvnitř)
> Vše ostatní (průnik) do dalších katastrů

**Comment by jiri-bartos-huld** [comment]
@jnihnat 
Ahoj Jirko, prosim:
1./chybi typ lokality katastralniUzemi
2./nemelo by jit zadat katastralniUzemi pri zakladani lokality-viz diskuze vise
3./prosim vyres konflikty v pull-requestu

Az to budes mit, tak dej prosim vedet podle me bude jeste potreba upravit mapu, tak aby v pripade typu=katastralni uzemi spravne zazumovala

**Comment by motyc** [comment]
@jiri-bartos-huld @jnihnat ad 1 - jde o typ DJ, nikoli lokality (viz též #374)

**Comment by jnihnat** [comment]
@motyc 
Narazil som na "maly" problem pri zakladani Lokality...
Pokud nemam hlavni katastr, tak nemam z ceho odvodit region. Teda to dela problem pri ziskavani docasneho identu, protoze ten ma v sobe region.
Moznosti je asi vice, ci uz delat "docasny ident docasneho identu" = X-X-... nebo tam davat na pevno C na zacatku.
Pak nastane otazka kdy menit dany ident, jenom pri prvnim nastaveni hlavniho katastru nebo pri kazde zmene pokud se meni region?
Oboji samozrejme zasahuje do identov navazanych objektu, cez DJ, komponenty az k Dokumentum...
Prosim teda popis jak by se to mnelo chovat na zacatku a pri zmenach regionu.

**Comment by motyc** [comment]
@jnihnat Safra, to máte pravdu a jde o nedomyšlenost z naší strany. Můj návrh řešení zní: dovolme při zápisu zadat hlavní katastr (výběrem z asynch. seznamu), ze kterého se odvodí ID. Katastr bude později automaticky aktualizován na základě skutečné polohy PIAN, ale už bez vlivu na ID. Je to takto schůdné?

Totéž bude platit pro #318

**Comment by jnihnat** [comment]
@motyc Upravene, akurat mne napada podobna vec s Typem lokality, nevadi ze je mozne menit typ lokality a ident cely se nemeni?

**Comment by motyc** [comment]
@jnihnat To už je věc obsahové správy. V praxi se to neděje, jedině v případě chyby, kdy je stejně lepší lokalitu zapsat znovu správně.

**Comment by jiri-bartos-huld** [comment]
@jnihnat 
Honzo, prosim koukni na tu nemoznost zakladat DJ=katastralniUzemi, stale mi jde vytvorit jen ty Lokalita. Podle em je to posledni co nam chybi v tomto tasku.

![obrazek](https://user-images.githubusercontent.com/77389730/196051592-849552af-562b-4e50-b066-34fc502d6a50.png)

**Comment by jnihnat** [comment]
@jiri-bartos-huld kterou db pouzivas u sebe? Je tam migrace na upravu jmena... ja to poustim na lokalni db tak to mam upravene.

**Comment by motyc** [comment]
### Výsledek testu
(test filtračního formuláře ještě probíhá, výsledky dáme zvlášť)
- [ ] odvozování dočasného ident_cely by mělo fungovat jako např. u projektu, tj. nemělo by docházet k tomu, že se jedno ID používá opakovaně: https://github.com/ARUP-CAS/aiscr-webamcr/blob/bb482358a3e5f1c46545c4792b7a8dfb2fdab38a/webclient/core/ident_cely.py#L27
- [ ] nejde odpojovat dokumenty (po potvrzení v modal okně dokument nezmizí a napojení se zachová); u akcí to však funguje v pořádku
- [ ] pod položkou menu “Archivovat” - je třeba zobrazovat záznamy ve stavu 2, nikoli 3 (tj. ty, které je potřeba archivovat: http://192.168.254.30:8080/arch-z/lokalita/vyber?stav=2)

---------------

- [ ] Objevena chyba zadání na naší straně - pokud je to třeba udělat nové issue a objednat zvlášť, pochopíme to:
- typ se musí vyplňovat automaticky podle druhu (na základě vazby heslářů lokalita_druh -> lokalita_druh_kat -> lokalita_typ)
- druh je dvoustupňový heslář (lokalita_druh + lokalita_druh_kat)
- v editaci nesmí jít změnit typ
- v editaci může jít změnit druh pouze v rámci daného typu (na základě vazby heslářů)
Jde o to, že by se nám jinak mohl rozpadnout vztah mezi ident_cely a typem a druhem lokality. Výše popsané bylo promítnuto i do zadání formulářů.

**Comment by jnihnat** [comment]
@motyc - prvni 3 chyby jsem opravil. z druheho som udelal aspon z druhu dvojstupnovy heslar(to bylo jednoduche). Ci udelat zbytek v ramci tohoto issue se prosim domluvte s @pesikj a @sedmar . Hruby odhad bych dal na 3 hodiny neco podobne uz mame co by se snad dalo prepouzit. Jinak ale chyby i vazba nadrazenosti mezy typem a druhem v heslar_nadrazenost.

**Comment by motyc** [comment]
@jnihnat Děkuji. Doplnil jsem teď ještě výsledky testování filtrace (do původního komentáře).

Ohledně implementace té úpravy počkám na vyjádření @sedmar. Určitě není problém hodiny započítat do nějaké nové objednávky po novém roce, ale asi by mi přišlo rozumné to upravit rovnou.

Co se týče vazby typ a druh_kat, tak ta je následovná:
- letecká archeologie
-- polygon archeologického průzkumu
- nemovitá památka
-- přírodní útvar s lidskou aktivitou
-- zaniklý areál
-- historická část živého areálu
- krajinný prvek
-- přírodní krajinný útvar
-- živé sídlo
-- extravilán živých sídel
-- místo historické paměti
-- zvláštní prvek krajiny

(při psaní SQL prosím neodkazujte jen na znění hesel, ale vždy i na kombinaci s konkrétním heslářem, protože jinak nemusí být hesla unikátní)

**Comment by jnihnat** [comment]
@motyc - opravena filtrace az na ten katastr, to bych nechal samostatne. Ten sami zaklad je pouzit na vicerych mistech, tak at se to pak pretestuje v jednom issue. K tomu plati i to pripadne vyhledavani podle casti nazvu katastru, to stoji za prebadani pred tim ci to je mozne. Rovnako bych videlil i to issue s typem lokality i kdyz se rozhodne to delat teraz. Ale takto by sme mneli za mne aspon tohle issue hotove. (Ak teda nenajdete dalsi chyby :) )

**Comment by motyc** [comment]
@jnihnat Katastry budeme řešit v rámci #328 a typ/druh jsem dal do #775. Až bude zbytek nasazen k testu, tak potvrdím opravy.

**Comment by sedmar** [comment]
@motyc Do budoucna nelze vázat zavření issue z objednávky na implementaci issue, které se bude řešit v rámci maintenace, tzn. dodatečná funkcionalita, která nebyla objednána v dané objednávce. Tím, že neděláme agilní vývoj, tak se bohužel do takových situací budeme dostávat vlivem toho, že zadání nebylo definováno tak, aby to umožnilo otestování s danou implementací bez dodatečné funkcionality.

**Comment by motyc** [comment]
@sedmar Ano, to úplně chápu a zavření tohoto issue neplánuji na to rozšíření vázat, pouze mi přijde vhodné zpracovat jej teď, kvůli testování apod. Rozhodně to bereme jako vstřícný postup ze strany Huld a neplánujeme nic komplikovat. Pokud vše ostatní ale bude v pořádku, nemám problém toto issue označit za akceptované.

**Comment by motyc** [comment]
### Výsledek testu
Chyby kopírují dva problémy v #318, jinak ok:
- [ ] http://192.168.254.30:8080/arch-z/lokalita/vyber?komponenta_jistota=False - najde i akce bez komponenty, nikoli jen ty, kde je v komponenta.jistota hodnota “false”
- [ ] http://192.168.254.30:8080/arch-z/lokalita/vyber?vlastnik=1898 - řešení přes vlastníka není šťastné, protože když pak aplikuji libovolný jiný filtr, tento parametr se odebere; lepší řešení je: http://192.168.254.30:8080/arch-z/lokalita/vyber?historie_typ_zmeny=AZ01&historie_uzivatel=1898 (to řeší i problém popsaný v #766)

**Comment by jnihnat** [comment]
opraveno v ramci #318 v #809
