### ISSUE TITLE
Ladění formulářů - revize povinných polí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#322]
Všude nutno prověřit povinná/nepovinná pole.

**Comment by svejci** [comment]
Davide (@motyc ), 
prošel jsem opět formuláře z pohledu povinných a nepoviných polí. Udělal jsem k tomu opět tabulku s přehledem stavu v návrhu formuláře a v aktuální nasazené verzi. Protože v původních návrzích formulářů jsem některé listy nedělal, tak mám opět nějaké dotazy, protože už nevím, jestli jsi daný list vytvořil jen jako kopii už existujícího s tím, že je celý třeba přepracovat, nebo už označení polí bylo s nějakým záměrem. U něčeho jsou to pak jen věci k ujasnění.

U projektů je jeden formulář pro stavy P1 a P7 a P8. Projekt v P1 je zapsaný. Uživatel by si zde tedy teoreticky mohl doplnit vedoucího a památkovou ochranu a následně si projekt přihlásit. Tím by se ale jednalo o P12. Pokud by si tyhle informace uživatel jen uložil bez posunu stavu, mohlo by to podle mě dělat zmatek, kdy by projekt už vypadal, že ho má někdo přihlášený. P7 a P8 jsou pak stavy navržen ke zrušení a zrušený a zde by uživatel už neměl mít samozřejmě přístup. 

U stavů P4-6 máme také jeden formulář. U pole uživatelské označení povolujeme jeho editaci v aktuálním desktopu ve stavu P4, ale dále už ne. Změníme to nebo pro stav P4 vytvoříme nový formulář?

Specifikace data u projektových akcí - ponecháme do budoucna možnost výběru? 

Datum ukončení - Mělo by být povinné jen pro odeslání akce, nebo při úpravě již v terénu ukončené akce. Rozdělit stavy na dva formuláře?

Přístupnost - bude vůbec možnost nechat nevybrané? Bude přednastavené na A, mělo by jít měnit, ale ne nechat prázdné, v nasazené verzi je označené tedy chybně jako povinné

Odeslaná akce - archeolog již editovat nemůže, povinný pole ale zůstávají stejná, je třeba dělat nový formulář pro admina?

Při zápisu samostatného nálezu máme nyní povinný jen projekt. Nebylo by dobré přidat i další pole jako datum, okolnosti a hloubku?

Katastrální území pří zápisu samostatného nálezu - Vyplní se automaticky zadáním do mapy, v aktuální živé verzi není povinné, má být povinné? V nasazené testovací verzi je povinné už v této fázi.

U vytvoření Letu máme jediné povinné pole Datum - je otázka zda toto jediné editovatelné pole, ale aby nešlo vytvořit záznam bez jediného popisu, u pole datum by mohlo být alespoň neznámé, stejně tak by šla přidat další pole, která považujeme za důležitá, pro fotografie, u kterých by nebylo známé by byla možnost neznámé? rozlišilo by se tak nevyplněno a neznámé.


Tabulku i s poznámkami posílám ještě do Brna Tomovi, aby to také celé projel, jestli jsem tam neudělal nějakou botu.

[povinna_pole_kontrola.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/8040257/povinna_pole_kontrola.xlsx)

**Comment by jnihnat** [comment]
@motyc jde nam tu prosim jen o povinne pole a jich oznaceni v pripade stavu zaznamu, nebo i jejich editovatelnost podle zarazeni uzivatele?

**Comment by motyc** [comment]
@jnihnat Tady jde čistě o označení a povinnost pole vyplnit (bez ohledu na roli). Ostatní se bude řešit v rámci oprávnění nebo jiných issue.

**Comment by jnihnat** [comment]
@motyc mam trocha problem pochopit ako to ma byt u akci,dokumentu,samostatny_nalezu,knihovna_3D:
- ma to byt podobne jako u projektu, kde stav 1 ma jine povinne polia jak stav 2 a 3?
- pokud plati tvrdenie hore, nebolo by mozne spravit podobne tabulky ako u projektu samostatne pre stav?
- jedna sa tu hlavne o moznost editu v danom stave.

Chcem predist pripadnym dalsim opravam a prehadzovanim si issue zbytecne.
dakujem

**Comment by motyc** [comment]
@jnihnat Ve většině případů je to spíše tak, že některá pole jsou povinná až pro odeslání, ale nikoli nutně pro zápis daného záznamu (tj. dokud je záznam rozpracovaný, mohou být nevyplněná). Někde ale skutečně závislost na stavu bude (např. část údajů o uložení nálezů v PAS). @svejci Můžeš to prosím projít dospecifikovat, aby to v tomto bylo jasné a jednoznačné? Část toho z tabulky vyplývá, ale nejsem si jistý, zda úplně vše. Také jsem si všiml, že u dokumentů to nemáš otestováno v nasazené verzi, přitom tam již formulář normálně je (zápis dokumentu k akci + následně zobrazení detailu, edit...).

**Comment by svejci** [comment]
@motyc S těmi dokumenty máš pravdu, že jak pro to není samostatný modul tak jsem to opomenul, tabulku jsem si už aktualizoval, jdinou část, kterou u dokumentu k akci nevidím, jsou části k neidentifikované akci, komponetám dokumentu atp.

@jnihnat Mohl bych poprosit u nějaký příklad nejsností, nebo na jaké věci bych se měl zaměřit aby bylo pro Vás vše přehledné? Je to často tak jak zmiňoval David, že některá pole jsou povinná až pro odeslání, ale do té doby může být záznam rozpracován bez nich, případně některá pole jsou povinná až v okamžiku, kdy se člověk snaží přidat k záznamu daný prvek (např. Druh objektů připojovaných ke komponentě musí být zadaný, pokud člověk objekty připojuje, ale ne u všech komponent musí být objekty připojeny).

**Comment by jnihnat** [comment]
@motyc @svejci Zatim postaci to vysvetleni, ze nektere su povinne az pro/po odeslani. Budu teda vychazet z toho, ze co je povinne pro zapsani je povinne pro edit zapsaneho a co je povinne pro odeslani je povinne pro edit odeslaneho. Pokud budu mit nekde dale nejasnosti jak to budu upravovat, tak napisu sem presny pripad.
Zatim dekuji.

**Comment by svejci** [comment]
@jnihnat ano, pokud je nějaké pole povinné pro zapsání, je stejně tak povinné i pokud záznam později edituji. V případě potřeby zodpovíme konkrétní dotazy. Přikládám ještě aktualizovanou tabulku s poli pro dokumenty.
[povinna_pole_kontrola_220317.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/8283045/povinna_pole_kontrola_220317.xlsx)

**Comment by motyc** [comment]
@svejci Máš pravdu, že některé části implementovány ještě nejsou... Jinak abyste si rozuměli, on je opravdu rozdíl v tom, když dám "edit" u pouze zapsaného (pak odpovídá položce "zapsat") a když ho dám u již odeslaného, pak teprve odpovídá Tvému "edit". V tom má @jnihnat pravdu.

V tomhle to je myslím trošku nedotažené/zmatené (např. mrkni na samostatný nález, kde se to vlastně vůbec neřeší.

**Comment by svejci** [comment]
@motyc ano máš pravdu, např. u toho samostatného nálezu to vlastně odpovídá postupu běžného uživatele a chybí tedy např. povinná pole, když admin začne editovat už odeslaný nález. Projdu to ještě ještě jedno a doplním.

**Comment by jnihnat** [comment]
@motyc a @svejci dal som tam zatim zlutou (farba warningu) a rovnako tenku ako u chyby. (da se to pak jednoducho menit samozrejme.
![obrazek](https://user-images.githubusercontent.com/57906106/158976314-142ea9e1-5868-4977-b807-5e63d1ad8690.png)
Dekuji za doplneni tabulek. K tomu jeste 2 veci: 
- chceme uz pri zapise zobrazovat tie fieldy, ktere musi byt vyplnene pro Odeslani/Prihlaseni (pro stav 2)?
- chceme po kliknuti do zluteho pole zmenit barvu na modrou jako u ostatnich pro focusu? Nebo nechat tu tenku linku zlutou ale udelat ten dalsi transparetni okraj? (Prvni moznost dole, druha hore)

![obrazek](https://user-images.githubusercontent.com/57906106/158977002-347de793-71eb-4222-a685-2b09aecc65e1.png)

**Comment by motyc** [comment]
@jnihnat Tenká žlutá vypadá skvěle, u té klidně zůstaňme.
- asi bych to označení udržel konzistentní, ať v tom není úplný zmatek, tj. označil je hned od začátku; kdyby se to po nějakém čase testování neosvědčilo, můžeme to ještě doladit;
- použil bych normálně ten modrý focus

**Comment by svejci** [comment]
@jnihnat Do návrhu formulářů doplněny listy s povinnými poli pro editaci v různých stavech u Akcí, Samostatných nálezů, Knihovny 3D a Dokumentů. Nyní bychom již do formulářů neměli zasahovat a jsou tedy k dispozici.

**Comment by jnihnat** [comment]
upraveno podle dokumentu na google. Prekontrolovane, snad som nikde nespravil chybu, pripadne uz to bude jednoduche opravovat/upravovat.

**Comment by motyc** [comment]
Výsledky testování:
### Projekty
- [ ] P1, P2, P3, P4, P5, P7, P8 (https://wamcr-test.aiscr.cz/projekt/edit/C-201700010)
- vyžaduje vyplnění pole označení stavby - není to povinné pole a ani tak není označené.

- [ ] Px1 (https://wamcr-test.aiscr.cz/projekt/zapsat)
- vyžaduje vyplnění pole Označení stavby - není to povinné pole ani tak není označeno
- nevyžaduje zapsání lokalizace z mapy - po kliknutí na zapsat problikne, ale nikam se to neposune, není upozornění na nutnost zápisu lokalizace z mapy a ani po jejím přidání nelze projekt zapsat

- [ ] https://wamcr-test.aiscr.cz/projekt/oznamovatel/edit/90949
- povinná pole jsou označena hvězdičkou, ale pole k editaci nejsou žlutě zvýrazněna jako v jiných formulářích

### Akce
Není vůbec hotovo, ale asi čeká na #338. Chybí hvězdičky, správné testy i odpovídající podbarvení okraje (viz komentáře výše).

### ADB
- [ ] https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-200913623C
- nedaří se editovat výškové body, abych šlo otestovat vyžadování povinných polí; píše, že se záznam nepodařilo editovat.

**Comment by motyc** [comment]
@jnihnat Doplňuji jednu obecnou chybu - pokud je zobrazen formulář s detailem záznamu, měla by být povinná pole stále označena hvězdičkou. Je to podstatné kvůli posouvání stavů, protože bez toho uživatel nemá šanci zjistit, že mu něco chybí, dokud záznam nezkusí odeslat. Jde o view:
`/arch-z/akce/detail/<str:ident_cely>`
`/dokument/detail/<str:ident_cely>`
`/dokument/model/detail/<str:ident_cely>`
`/projekt/detail/<str:ident_cely>`
`/adb/detail/<str:ident_cely>`
`/dj/detail/<str:ident_cely>`
`/komponenta/detail/<str:ident_cely>`
`/pian/detail/<str:ident_cely>`

**Comment by jnihnat** [comment]
@motyc oznacil som prve opravy ako Done:
- prosim pretestovat jeste jednou projekt zapsat, u mne to funguje spravne, tak mozna jen neco spatne na stare verzi.
- Akce a ADB budou reseny v #338 
Koment zo vcera este opravim samostatne.

**Comment by svejci** [comment]
Zkoušel jsem nyní zápis projektu a pole Označení stavby je stále považováno jako povinné, přestože není a ani tak není označeno. 
Stejně tak pokud nepřidám lokalizaci z mapy, tak přetrvává chyba popsaná výše.

**Comment by jnihnat** [comment]
oznaceni neni jeste nasazeno.
K lokalizaci, mne se to zobrazi vzdy spravne... muzete mozno poslat screenshot co mate jak vyplneno?
![image](https://user-images.githubusercontent.com/57906106/173790498-29188025-4552-4cb2-bef7-a6f0dcffbb33.png)

**Comment by motyc** [comment]
Já jen doplňuji, že testujeme na https://wamcr-test.aiscr.cz/ (resp. http://192.168.254.30:8080/)

**Comment by jnihnat** [comment]
tak oprava prichystana v #502 i kdyz trvalo na to prist preco a kde je... Doplnim jeste hviezdicky a dam do done

**Comment by jnihnat** [comment]
@motyc predsa len mam otazku k tym hviezdickam. Obecne mi nedela problem je tam doplnit, akurat mi nedava zmysel proc to chceme udelat. Priklad:
mam zaznam v stavu 1, ten ma povinne polia: A, B, C.
Bez ich vyplnenia nevytvorim zaznam nikdy, teda i na detailu zobrazim * u A,B,C
stav 2 ale bude chtit navic D, E - to ale nebude zobrazeno jako hviezdicka, protoze to neni Required pro stav 1.

**Comment by motyc** [comment]
@jnihnat Máte pravdu v jedné věci - ono by ve skutečnosti bylo nejlepší, kdyby ty hvězdičky byly u polí, které jsou povinné pro posun do dalšího stavu. Nevím, ale jak by to bylo komplikované udělat. Problém je prostě v tom, že o povinných polích pro další krok se člověk dozví až ve chvíli, kdy jej chce udělat a vyskočí na něj chyba. Snad to vysvětluji srozumitelně...

**Comment by motyc** [comment]
@jnihnat Ok, souhlasím, nechme to jako nový požadavek. Vyrobím ze souvisejících komentářů nové issue. Je třeba, aby to označení ale bylo v pořádku ve všech editačních formulářích.

**Comment by motyc** [comment]
Kromě ADB se zdá ok, ale dokud nebude vyřešeno #287 a související, tak nejde dotestovat.

**Comment by motyc** [comment]
### Výsledky celkové revize
- [ ] U některých polí chybí hvězdička:
/projekt/navrhnout-ke-zruseni/<str:ident_cely>	navrhzruseni.projektId
/projekt/navrhnout-ke-zruseni/<str:ident_cely>	navrhzruseni.vlastniduvod

- [ ] Některá pole jsou označena hvězdičkou i v prostém zobrazení detailu, kdy jinde pole neoznačujeme:
/historie/soubor/<int:soubor_id>		Nazev zkraceny
/historie/soubor/<int:soubor_id>		Nazev puvodni
/historie/soubor/<int:soubor_id>		Nazev
/historie/soubor/<int:soubor_id>		Mimetype
/historie/soubor/<int:soubor_id>		Size bytes
/pas/detail/<str:ident_cely>		Evidenční číslo
/pas/detail/<str:ident_cely>		Přístupnost

- [ ] Některá pole mají správné chování z hlediska testů, nejsou ale žlutě ohraničená, jak by pro ně bylo správné:
/pas/zapsat + /pas/edit/<str:ident_cely>		Šířka (N / X)
/pas/zapsat + /pas/edit/<str:ident_cely>		Délka (E / Y)
/arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/edit/<str:ident_cely>		Hlavní katastr

Celkový přehled zde: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by motyc** [comment]
@sedmar Toto myslím patří do https://github.com/ARUP-CAS/aiscr-webamcr/projects/8#column-19191247

**Comment by motyc** [comment]
@sedmar Souhlasím.

**Comment by jnihnat** [comment]
@motyc Dobry den, mam skoro vse hotove az na:
/arch-z/akce/zapsat/str:projekt_ident_cely + /arch-z/akce/edit/str:ident_cely Hlavní katastr
nechapu proc to chceme zlute, kdyz to je disabled, v cele aplikaci mame ze readonly/disabled neoznacujeme zlute.

**Comment by motyc** [comment]
@jnihnat Ono to zadání vzniklo dřív, než to ještě bylo disabled. V současném pojetí je to ok, takže to můžete nechat. Díky za upozornění.
