### ISSUE TITLE
Filtrace podle historie záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#325]
Výběry záznamu projekt, akce, lokalita, dokument, bibliografie musí obsahovat multiselect sledování změn daného záznamu dle typu změny (nedotaženo - chybná logika fungování).

Jde o tuto část fitračního formuláře (obdobná by měla být u všech podobných tabulek pro výběr; https://wamcr-test.aiscr.cz/projekt/list):
![image](https://user-images.githubusercontent.com/20186892/151408303-f43f6eb8-dbd1-4748-b864-0a725b1def5e.png)

Problém je v tom, že je potřeba dotaz konstruovat tak, aby pole v tomto řádku byla vzájemně závislá, tj. aby platilo mezi jednotlivými poli logické AND, nikoli OR. Např. aby šlo položit dotaz “najdi všechny projekty, kde došlo k posunu P12 nebo P78 od 1.1.2021 do 13.3.2021 uživatelem David Novák nebo Ondřej Švejcar”. To nyní nejde, protože je mezi poli OR.

**Comment by jnihnat** [comment]
@motyc - dobry den, prave koukam na tohle issue a skusim si to a vsude je prave logicke AND jako ma byt. Mozte prosim jeste jednou protestovat, ze to naozaj funguje jako OR?

**Comment by motyc** [comment]
@jnihnat než se vrhnu do testování - a není náhodou to AND implementováno na úrovni tabulky projektu, nikoli na úrovni tabulky historie? V tom totiž byl ten problém. Jde o to, že hledáme specifickou kombinaci na úrovni logu, nikoli projekt, kde se vyskytují dané údaje v tabulce historie v různých záznamech...

**Comment by jnihnat** [comment]
Prave ze mezi kazdym jednim filtracnim polom je AND. pro priklad, mam nasledujuce:
- typ_projektu "zachranny", historie_zmena = P71,P78, historie_uzivatel = Marek,Michal
to vyhlada zaznamy kde:
 typ_projektu "zachranny" AND (historie_zmena = P71 OR historie_zmena=P78) AND historie_uzivatel = Marek OR historie_uzivatel = Michal)

**Comment by motyc** [comment]
Aha, pak by to bylo v pořádku a musel to někdo opravit minulosti, aniž bychom se to dozvěděli. Otestuji to a dám vědět.

**Comment by motyc** [comment]
Tak testovat to nejde, na dostávám error 500

https://wamcr-test.aiscr.cz/projekt/list?ident_cely=&katastr=&oblast=&popisne_udaje=&planovane_zahajeni_after=&planovane_zahajeni_before=&datum_zahajeni_after=&datum_zahajeni_before=&datum_ukonceni_after=&datum_ukonceni_before=&termin_odevzdani_nz_after=&termin_odevzdani_nz_before=&historie_typ_zmeny=P34&historie_datum_zmeny_od_after=2014-12-02&historie_datum_zmeny_od_before=2014-12-02&historie_uzivatel=1847&akce_ident_obsahuje=&akce_katastr=&akce_popisne_udaje=&akce_datum_zahajeni_after=&akce_datum_zahajeni_before=&akce_datum_ukonceni_after=&akce_datum_ukonceni_before=&akce_zjisteni=&akce_je_nz=&dokument_ident_obsahuje=&pian_ident_obsahuje=&zdroj_ident_obsahuje=

**Comment by jnihnat** [comment]
to je nasazenou verzi, u seba som opravoval jednu vec co @pesikj prerabal pred tydnem a zapomnel. Myslel som ze to este nebudete mat nasazene. domluvim se s nim at to pak nasadi a dam vedet.

**Comment by jnihnat** [comment]
jeste som predelal polia kde se vyhledavalo podle osoby nebo uzivatele na asynchronni, kdy se dotahuji zo serveru, zrychluje to tak nacitani stranky. Predchazejici reseni s cache bylo nevyhovujici, protoze po vyhledani se cast formularu kde se zadava vyhledavani nedotahla podle toho co uzivatel vyplnil.

**Comment by motyc** [comment]
https://wamcr-test.aiscr.cz/dokument/model/vybrat
- [ ] vrací `504 Gateway Time-out` pro:
![image](https://user-images.githubusercontent.com/20186892/173690062-b0e3b7b3-85e9-4704-898c-6abf02377bc3.png)
- [ ] kombinace stav = Zápis dokumentu + U-001314 vrací i chybné hodnoty (případy, kdy daný uživatel dokument nezapsal, ale třeba archivoval). Podobný problém vzniká při kombinaci datum + stav, uživatel + datum atd.

https://wamcr-test.aiscr.cz/pas/vyber
- [ ] kombinace stav = Zápis samostatného nálezu + U-000159 vrací i chybné hodnoty (případy, kdy daný uživatel nález nezapsal, ale třeba archivoval). Podobný problém vzniká při kombinaci datum + stav, uživatel + datum atd.

U projektů vše ok.

**Comment by jnihnat** [comment]
upravena filtrace historie vsude. Nemohla fungovat ani u projektu, filtrovani co bylo delano pred tim vzdy filtrovalo oproti zakladnimu zaznamu. Dodelal som teda aby historii filtrovalo spolu.
K prvni chybe 504 to byl klasicky timeout, predpokaldam ze filtrace trvala dlouho. Skuste po uprave, snad to uz bude rychlejsi, jinak by sme museli hledat nejake moznosti vylepseni performance.

**Comment by motyc** [comment]
@pesikj Souhlas.

**Comment by motyc** [comment]
### Výsledky testu
Výsledky jsou v pořádku, problém je možnost zahlcení systému.

https://wamcr-test.aiscr.cz/dokument/model/vyber?historie_typ_zmeny=D01&historie_uzivatel=1023 dává error 504 (přitom první dotaz je již ok (https://wamcr-test.aiscr.cz/dokument/model/vyber?historie_datum_zmeny_od_after=2020-05-27&historie_datum_zmeny_od_before=2020-05-27); problém je ale širší v tom smyslu, že dotazy jde zjevně aplikaci zcela zablokovat (přetížit), a to generálně pro všechny uživatele - udělám k tomu samostatné issue, které bude obdobné situace řešit komplexněji
