### ISSUE TITLE
Řazení v polích s hesláři

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#327]
Řazení musí být vždy podle pole "poradi". Pokud toto pole v hesláři není vyplněno (či neexistuje), pak podle zobrazovaných hesel podle abecedy v češtině se speciálními znaky na začátku seznamu

**Comment by motyc** [comment]
@svejci Ondro, prosím ještě prověř toto, zda je to v pořádku...

**Comment by svejci** [comment]
@motyc 
Ahoj Davide, 
prošel jsem pole s hesláři v aktuální nasazené verzi. Shrnutí opět přikládám v tabulce níže. Většinou je to OK, ale u některých polí jsou přesto chyby. U některých heslářů je pak nasazený heslář trochu jiný, než jaký máme v souboru "helare_aktual", ale to je předpokládám tím, že používají nějakou neaktualizovanou verzi. Pro některá pole také hesláře nemáme, ale v nasazené verzi jsou, předpokládám že se jedná tedy o nějakou pracovní verzi. U některých polí je pak ještě použit chybně např. jednostupňový heslář (řazen ale správně), ale to shrnuje jiné issue. 

Měl bych zase několik dotazů nebo poznámek
1) U přístupnosti by podle mě mělo být řazení podle pořadí, v hesláři ale pole nemáme, odpovídá mu ID a řadí se správně, ale asi by bylo dobré doplnit pole pořadí, aby bylo všude jednotné.
2) U PIAN a Let je "heslář" v podstatě seznam. Jak budeme řadit zde? Podle pořadí/čísla?

Ondra

[razeni_poli_v_heslarich220223.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/8123315/razeni_poli_v_heslarich220223.xlsx)

**Comment by motyc** [comment]
@svejci Díky za kontrolu. Ano, odchylky oproti produkční verzi být mohou, i když by neměly být velké.
Ad "hesláře které nemáme" - ne každé pole s rozbalovacím seznamem je přímo heslář. Pokud tam něco z hlediska těchto polí nevyhovuje, asi to musíme popsat explicitně pro dané pole.
Ad 1 - nesmíš se vztahovat k původním datům, ale k nové DB, kde jsou všechny hesláře integrovány do jedné tabulky a kde ve struktuře pole pořadí je vždy;
Ad 2 - tady nejde o hesláře, ale seznamy ID, řazení bude abecední

K té tabulce:
- v případě výběru uživatelů musíme ještě uvážit, co nám vlastně dovoluje GDPR; struktura by mohla být `Příjmení, Jméno (ident_cely; organizace)`, ale je to třeba ještě uvážit, zda to chceme mít takto jako veřejný heslář.
- stav - není heslář, jde o systémové konstanty, proto to nemůžeš v heslářích najít; řadit by se mělo podle pořadí stavů (uvažoval bych o vypisování ve formátu `P1 - zapsán`, ať je to jasné)
- zjištění, předáno, je NZ (apod.) - to jsou jen pomocné nabídky, opět jde o konstanty
- specifikace data - heslář se redukoval (viz #36)
- souř. systém - myslím, že nejde o heslář, stejně ale jde o dvě hodnoty (první dávat WGS, druhou S-JTSK)

**Comment by jnihnat** [comment]
upravil som podle excelu nasledovne:
- organizace
- kraj
- okres
Podle komentaru som jeste pridal pred stavy cislo "P1 - zapsan"...

**Comment by motyc** [comment]
Výsledky testování:

- [ ] na místech nasazení asynchronních heslářů (https://github.com/ARUP-CAS/aiscr-webamcr/issues/325#issuecomment-1086907559) je seznam řazený podle neznámého klíče, navíc má zvláštní strukturu - upravit na: `prijmeni, jmeno (ident_cely, organizace)`; týká se:
- https://wamcr-test.aiscr.cz/projekt/vyber
- https://wamcr-test.aiscr.cz/dokument/model/vybrat
- https://wamcr-test.aiscr.cz/pas/vyber

- [ ] u Dokumentu při výběru autora je sice správný heslář s abecedním pořadím, při pokusu dojet na konec seznamu však přeskočí na prázdnou “stránku”. Při probliknutí před prázdnou stránkou je však vidět, že za “Žohová, Martina” jsou i další jména (stejné u Dokumentované osoby, Autoři u 3D, Samostatné nálezy - Nálezce), týká se např.:
- https://wamcr-test.aiscr.cz/dokument/edit/X-C-TX-201904031
- https://wamcr-test.aiscr.cz/dokument/model/edit/C-3D-202000004
- https://wamcr-test.aiscr.cz/pas/edit/M-202101534-N00282

- [ ] PIAN u Akce - Dokumentační jednotka - měl by se řadit abecedně, nyní se ale řadí podle pořadí řádků v tabulce pian (http://192.168.254.30:8080/arch-z/akce/detail/C-201911821A)

- [ ] Samostatné nálezy - pořadí v hesláři je na prvním místě S-JTSK a pak WGS84, zde se zobrazuje opačně (http://192.168.254.30:8080/pas/edit/M-202101534-N00282)

**Comment by motyc** [comment]
### Výsledky testů
- [ ] ad 1 (fotmát výpisu uživatelů `prijmeni, jmeno (ident_cely, organizace)`) - chybí čárka za příjmením
- [ ] ad 2 (prázný konec seznamu) - stále platné, ale problém je jen v Mozille

**Comment by motyc** [comment]
@jnihnat první bod v testu doplněn o jeden opomenutý problém

**Comment by jnihnat** [comment]
K tomu vyhledavani, mnelo by to fungovat tak, ze zadam presny retezec: "Novák, Dav" a najde mi to zaznamy, ktere maji vypis zacinajici na zadany retezec?

**Comment by motyc** [comment]
@jnihnat Nejlepší by bylo stejné chování, jako u dalších katastrů (první které začínají, pak ty, které obsahují)

**Comment by jnihnat** [comment]
vyhledavani upraveno, pokud by to vracelo vysledky prilis pomalu, prosim udelat samostatne issue k tomu, budeme to muset pak resit jinak.
