### ISSUE TITLE
Filtrace - asynchronní hesláře

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#328]
Provedena revize. Zde je potřeba doplnit asynchronní seznamy:

- [x] `/adb/zapsat/<str:dj_ident_cely>` + `/dj/detail/<str:ident_cely>`
-- Autor popisu
-- Autor revize
- [x] `/arch-z/akce/zapsat/<str:projekt_ident_cely>` + `/arch-z/akce/edit/<str:ident_cely>`
-- Hlavní vedoucí
-- Vedoucí
- [x] `/dj/zapsat/<str:arch_z_ident_cely>` + `/dj/detail/<str:ident_cely>` - PIAN
- [x] `/pas/vyber` (multivýběr)
-- Katastr
-- Nálezce
- [x] `/pas/zapsat` + `/pas/edit/<str:ident_cely>` - Nálezce
- [x] `/projekt/vyber` (multivýběr)
-- Katastr (projekt)
-- Katastr (akce)
- [x] `/arch-z/akce/vyber` - Katastr (multivýběr)
- [x] `/arch-z/lokalita/vyber` - Katastr (multivýběr)
- [x] `/dokument/vyber` - Katastr (multivýběr)

Celkový přehled zde: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by motyc** [comment]
Řešení nasazeno pro jména (https://github.com/ARUP-CAS/aiscr-webamcr/issues/328), doplnit i pro další podobné situace.

**Comment by motyc** [comment]
Provedena revize. Zde je potřeba doplnit asynchronní seznamy:
/adb/zapsat/<str:dj_ident_cely> + /adb/detail/<str:ident_cely>	Autor popisu
/adb/zapsat/<str:dj_ident_cely> + /adb/detail/<str:ident_cely>	Autor revize
/arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/edit/<str:ident_cely>	Hlavní vedoucí
/arch-z/akce/zapsat/<str:projekt_ident_cely> + /arch-z/akce/edit/<str:ident_cely>	Vedoucí
/dj/zapsat/<str:arch_z_ident_cely> + /dj/detail/<str:ident_cely>	PIAN
/dokument/edit/<str:ident_cely>	Autoři
/dokument/edit/<str:ident_cely>	Dokumentované osoby
/dokument/model/zapsat + /dokument/model/edit/<str:ident_cely>	Autoři
/dokument/zapsat/do-akce/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely>	Autoři
/pas/vyber	Katastr
/pas/zapsat + /pas/edit/<str:ident_cely>	Nálezce
/projekt/vyber	Katastr (projekt)
/projekt/vyber	Katastr (akce)

**Comment by pesikj** [comment]
Především bod s úpravou vzhledu bude poměrně náročný, odhad: 28 hodin.

**Comment by motyc** [comment]
@pesikj Prosím o odhad i bez ní. To je celkem zbytná věc.

**Comment by pesikj** [comment]
Úprava vzhledu: 20 hodin
Doplnění seznam: 8 hodin

**Comment by motyc** [comment]
### Test v0.3.5z49
Vše ok, kromě:
- [ ] http://192.168.254.30:8080/projekt/vyber - rozbité pole Organizace (akce) - pole úplně zmizelo
