### ISSUE TITLE
Vícestupňové hesláře - revize

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#329]
Není implementováno správné chování vícestupňových heslářů (oddělovače v seznamech - funguje dobře např. pro typ akce, ale na mnoha jiných místech nikoli)

**Comment by motyc** [comment]
> Ondřej Švejcar
> Dokončil jsem procházení těch heslářů v aktuální nasazené webové verzi a v návrzích formulářů. Udělal jsem k tomu tabulku (v příloze), kde jsem zohlednil pole, která by měla mít heslář, jestli má být heslář jednostupňový či vícestupňový, jestli je toto pole správně v nasazené verzi (některé části ještě samozřejmě v nasazené verzi nejsou) a jestli je toto pole správně v návrhu formuláře (zde jsem v návrzích do jednotlivých polí doplnil, zda tam má být heslář jedno či vícestupňový). Nejvíc nesouladů jsem našel ve filtrech pro jednotlivé části, kde jsou u některých polí nasazené jednostupňové hesláře místo vícestupňových.
> 
> Také jsem toto porovnal s hesláři, které máme v databázi _heslare_aktual. Tady pro některá pole hesláře nemáme, i když např. v nasazené verzi už nějaký, asi pracovní heslář, je. Některé hesláře, jako např. seznam PIAN, nebo seznam projektů pro samostatné nálezy jsou pochopitelně vlastně jen výčtem všech hodnot a v téhle databázi je nemáme. U Některých polí i když heslář nemáme ani v tabulce ani není v nasazené verzi, jsem pak navrhl že by byl asi dobrý (např. účel letu), ale to se pak asi ještě domluvíme.
> 
> Mimo to se mi při téhle práci nahromadilo několik dílčích dotazů:
> 
> Jak budeme přistupovat k polím kde je na výběr jen ano/ne? Bereme to jako heslář, nebo je tohle také speciální typ pole jako např. v accessu?
> 
> Budeme mít do budoucna heslář pro licence u dokumentů?
>  
> Ještě jsem tabulku poslal Tomovi do Brna, aby to také prošel, jestli jsem se někde nějak výrazně nepřehlédl. Pokud tam ale nenajde nějaký výraznější zásek, jaký bude pak další postup? Máme projít všechny návrhy formulářů a zkontrolovat a dotáhnout je do finální podoby?

[heslare_urovne_kontrola_220126_.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/7952574/heslare_urovne_kontrola_220126_.xlsx)

**Comment by motyc** [comment]
@svejci Odpovídám na dílčí dotazy:
- _Jak budeme přistupovat k polím kde je na výběr jen ano/ne?_ Pokud to není přímo checkbox (což ve filtraci asi být nemůže), tak bych to dělal jako standardní heslář, ať to zbytečně nekomplikujeme více variantami.
- _Budeme mít do budoucna heslář pro licence u dokumentů?_ Osobně to zatím nepovažuji za možné, pouze by se měla vyplňovat defaultní hodnota.
- _Pokud tam ale nenajde nějaký výraznější zásek, jaký bude pak další postup? Máme projít všechny návrhy formulářů a zkontrolovat a dotáhnout je do finální podoby?_ Ano prosím o dotažení

**Comment by ScottVanWagenen** [comment]
this is issue 182 in Jira

**Comment by pesikj** [comment]
@ScottVanWagenen Ok, I was confused by a different title.

**Comment by pesikj** [comment]
@jnihnat Honzo, prosím, podívej se na to. Díky.

**Comment by jnihnat** [comment]
opravene vse krome:
- Letov - bude udelane v issue az sa bude delat modul (filtry taky)
- Dokumenty (Tvary, PIAN, Vedouci) - dodela se az se bude dodelavat modul (filtry taky)

**Comment by motyc** [comment]
@svejci Prosím o test.
