### ISSUE TITLE
Filtrace projektů - nejednotný formát heslářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#332]
Formát rozbalovacích seznamů je nejednotný (minimálně tři 4 typy - Typ, Stav, Územní přísl., Zjištění).

Všude používat jako základní variantu drop down s vyhledáváním (pokud není funkcionalita nějak specifická).

![image](https://user-images.githubusercontent.com/20186892/153274544-c4f3dbcf-eed3-4c30-be62-3955b4dcbff0.png)

![image](https://user-images.githubusercontent.com/20186892/153274598-23af6353-abd6-492d-a3ee-84f9e6387eb9.png)

![image](https://user-images.githubusercontent.com/20186892/153274818-e4cfed4a-573b-4250-bff2-bffdf9199679.png)

![image](https://user-images.githubusercontent.com/20186892/153274859-52353dfd-3ec2-43ac-986c-d700d8c74b5f.png)

**Comment by jnihnat** [comment]
@motyc deslare jsem upravil. Po novu je uz odlizny jen heslar na vedouci. Tam sa totiz pouziva autocomplete heslar, ktery se dotahuje cez url podle toho co uzivatel zadava. Je pouzity pak na vice mistech aby se stranka zbytecne nenacitavala moc dlouho. Pokud by se mnel predelat aby vypadal stejne jako ostatne byla by to vetsci prerabka a uz na samostatne issue.

**Comment by motyc** [comment]
U projektů je to super, ale je to třeba stejně udělat všude:
- https://wamcr-test.aiscr.cz/pas/vyber
- https://wamcr-test.aiscr.cz/dokument/model/vybrat
- https://wamcr-test.aiscr.cz/pas/spoluprace/vyber

(případně i další formuláře, ale tam to můžeme řešit postupně, pokud narazíme na problém)

**Comment by motyc** [comment]
@jnihnat Máte pravdu, iisue bylo jen na projekty (přehlédl jsem to). V každém případě však i u ostatních stránek jde o reklamaci, je to stejná situace. Nehoří to z hlediska termínu.

**Comment by pesikj** [comment]
@motyc Vzhledem k diskusi u tohoto issue nepředpokládám, že je nutné jej vyřešit do 30. června.

**Comment by motyc** [comment]
### Výsledky testování
Provedl jsem celkovou revizi stavu rozbalovacích seznamů s následujícím výsledkem:
- [ ] Seznamy, kde je použitý chybný typ elementu (má být standardní typ jednoduchého výběru s vyhledáváním):
/dj/zapsat/<str:arch_z_ident_cely> + /dj/detail/<str:ident_cely>	Typ
/pian/zapsat/<str:dj_ident_cely> + /pian/detail/<str:ident_cely>	Přesnost
/adb/zapsat/<str:dj_ident_cely> + /adb/detail/<str:ident_cely>	Typ sondy
/adb/zapsat/<str:dj_ident_cely> + /adb/detail/<str:ident_cely>	Podnět
/adb/vyskove-body/zapsat/<str:adb_ident_cely>	vyskovyBod.typ
/dokument/model/zapsat + /dokument/model/edit/<str:ident_cely>	Země
/pas/edit/ulozeni/<str:ident_cely>	Nález předán
/pas/edit/ulozeni/<str:ident_cely> + /pas/potvrdit/<str:ident_cely>	Přístupnost
/projekt/edit/<str:ident_cely>	Památková ochrana
/projekt/prihlasit/<str:ident_cely>	Památková ochrana

- [ ] Seznamy, kde je by měl být vícenásobný výběr, ale není:
/dokument/model/vyber	Typ
/dokument/model/vyber	Formát
/pas/vyber	Pristupnost

- [ ] Seznamy, kde je použitý multiselect, ale zároveň umožňují vybrat i null hodnotu, což nedává smysl:
/dokument/model/vyber	Období
/dokument/model/vyber	Areál
/dokument/model/vyber	Druh předmětu
/dokument/model/vyber	Druh objektu
/dokument/model/vyber	Specifikace objektu
/pas/vyber	Období
/pas/vyber	Druh nálezu
/projekt/vyber	Typ

Žádné další problémy v tomto smyslu jsem neobjevil.

**Comment by motyc** [comment]
### Výsledek testu:
- [ ] V těchto případech byl při opravě omylem použitý asynchronní multiselect, místo obyčejného:
/dokument/model/vyber Typ
/dokument/model/vyber Formát
/pas/vyber Pristupnost
- [ ] Seznamy, kde je použitý multiselect, ale zároveň umožňují vybrat i null hodnotu, což nedává smysl - zde bylo vše výše jmenované opraveno, ale omylem jsem z přehledové tabulky nevypsal některé výskyty chyby; za to se omlouvám:
/arch-z/akce/pripojit/dokument/<str:arch_z_ident_cely> + /projekt/pripojit/dokument/<str:proj_ident_cely>
/dokument/zapsat/do-akce/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely>
/dokument/edit/<str:ident_cely>
/dokument/model/zapsat + /dokument/model/edit/<str:ident_cely>

**Comment by motyc** [comment]
V pořádku, zavírám.
