### ISSUE TITLE
Filtrace projektů - doplnit filtraci podle ADB

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#333]
Viz https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094

**Comment by motyc** [comment]
@pesikj u Typu akce má jít o vícestupňový heslář (chybí tam nadřazená hesla, která dělí seznam na dílčí skupiny, jako např. u hesláře období). Nicméně - toto není něco, čeho by se týkalo toto issue - podobné případy/chyby ještě na naší straně dohledáváme v rámci issue #329 (které budeme řešit, až revizi doděláme). V tomto issue jde pouze o přidání jediného pole, a to pro hledání podle ID ADB (v tabulce Projekt, list Filtrace, M/N 43/44). Myslím, že zde o odhad zahrnuje něco jiného, prosím o úpravu odhadu, pokud to tak je.

**Comment by pesikj** [comment]
My máme u issue tento popis: 

* Formát rozbalovacích seznamů je nejednotný (minimálně tři 4 typy - Typ, Stav, Územní přísl., Zjištění).
* Doplnit filtraci podle ADB (viz  https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094).

Je ten popis tedy k jinému issue?

Odhad je založený na tom, že ne na každý typ filtru je možné použít každý widget a customizace různých widgetů rozhodně nebudou triviální. Abych to dokázal odhadnout, potřebuji právě vědět, v čem je formát rozbalovacích seznamů nejednotný. I kdyby to bylo potřeba řešit v jiném issue, toto je třeba definovat.

**Comment by motyc** [comment]
Prosím, řiďte se tím, co je tady, nikoli tím, co máte původně v Jira. Právě proto, že tyto dvě věci spolu nesouvisí, jsme to i po dohodě na schůzce rozdělili na dvě issue, toto a #332 (tam jsem nyní doplnil i screenshoty těch rozdílných řešení, což považuji za chybu, nikoli za věc pro vývoj - pokud by někde byla odlišnost důvodná funkcionalitou, tak to prosí tam rozeberte, proč to tak má být).

#333 je pak trošku jiné téma, které s tímto přímo nesouvisí, ale zmátlo mne, na co se vlastně ptáte. Nicméně ten typ akce skutečně má být dvoustupňový heslář.
