### ISSUE TITLE
Lépe zvýraznit pole s chybami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#334]
Pokud nevyplním povinné pole, po kliknutí na “Vytvoř akci” se pole zvýrazní. Přidat i hlášku připomínající, které pole je třeba doplnit

Hlášky o chybách jsou navíc nejednotné - dobře viditelné na formuláři https://wamcr-test.aiscr.cz/projekt/create (chování pole Telefon je při chybě jiné, než u ostatních polí - výpis chyby pod polem vs. výpis chyby v tooltipu).

**Comment by pesikj** [comment]
Já vidím u telefonu stejnou chybu jako třeba u Adresy oznamovatele.

![image](https://user-images.githubusercontent.com/15179154/153069721-e708344f-bfa2-48b3-a0e7-dfab8f2f2f98.png)

![image](https://user-images.githubusercontent.com/15179154/153069762-7157f80e-ee28-4e06-b914-567d14dba740.png)

**Comment by motyc** [comment]
@pesikj Zkuste tam vyplnit chybnou hodnotu a pak odeslat. U emailu opět bude tooltip, u telefonu bude červený popisek pod polem.

**Comment by jnihnat** [comment]
@motyc @pesikj 
Pozeral som vcera na to ako to funguje a ake su moznosti:
Momentalne je zapnute nativna kontrola prehliadaca, co znamena, ze povinne polia sa vyznacia ako to je na obrazkoch hore a kontroluje sa aj pole email na to ze ma formu emailu.
Co je mozne upravit:
1. odstranit tuto kontrolu a pridat tam bootstrap validaciu, co by bolo neprakticke z tychto dovodov:
- u oznameni je navic recaptcha a tahle bootstrap validace se tam bude muset ohybat - prace s testovanim mozna na par hodin
- pokud chceme aby tam nebyl jen vykricnik a fajka ale i text, tak je ho potrebne rucne doplnit ku kazdemu poli
- jak by to mohlo vypadat, je to pod Custom styles. Ty texty co se tam objavuji jsou rucne dopsane - https://getbootstrap.com/docs/4.6/components/forms/#validation
2. odstranit kontrolu prohlizece a nechat kontrolu jen na serveru
- ma to jednu nevyhodu a to ze i spatne vyplneny formular se posle na server - hlavne chybejici vyplnene povinne polia
- takze zbytecna zatez na servr
3. nechat to tak jak je
- ten telefon a email je tu specificky jak pisu, Email totiz ma nad sebou validaci na strance a telefon ne, muzu pripadne dodelat tu validaci i na stranku a tak se ta chyba objevi stejna pro telefon i email jako tooltip na pozadovany format.

Dejte prosim vedet jak se rozhodnete.

**Comment by motyc** [comment]
@jnihnat  Šel bych tou cestou, že se to prozatím alespoň sjednotí, tj. že i telefon bude mít validaci na stránce. Ono to navíc celé bude vypadat trošku jinak po tom, co jsme se domluvili na řešení pro #322

**Comment by jnihnat** [comment]
Nasraveny regex pro telefon nech sa zobrazuje uz hlaska o vyplneni spravnehio formatu pred odeslanim.
oznaceni poli bude v oprave #322
