### ISSUE TITLE
Projekt - edit - grafika pole Organizace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#336]
V Mozille se při zahájení editace rozhodí umístění pole Organizace (vyskočí výše než sousední pole)
![image](https://user-images.githubusercontent.com/20186892/151414927-475033ea-6ed8-4e13-96bf-1dd46a9187de.png)

**Comment by jnihnat** [comment]
mnelo by byt vyreseno upravou pridavani vedouciho projektu na modal. Davam do Done a pak prosim o test.
