### ISSUE TITLE
Formuláře - doplnění tooltipů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#337]
Měly by být dostupné jako zástupné klíče pro všechna pole. Jejich naplnění proběhne v souvislosti s obecným laděním a doplněním textů. Pro testovací účely lze používat Lorem ipsum.

Správné řešení tooltipů (graficky) obsahuje např. stránka https://wamcr-test.aiscr.cz/oznameni)

**Comment by jnihnat** [comment]
pridane tooltipy jako hesla.
Taky upraveny treti bod z AMCR-71 (nenasel sem kopii k tomu v githube):
Tlačítko “Poloha” není na první pohled jasné (změnit na “Přidat současnou polohu” nebo podobně?) - pro samostatny nalez
