### ISSUE TITLE
Rozložení formulářů - Knihovna 3D

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#340]
https://docs.google.com/spreadsheets/d/1WVSCrVVFGZduhZ9tbDCeea9c7wyvgCYMWORe8k1AzYg/edit#gid=1525832777

**Comment by jnihnat** [comment]
@motyc 
Chceme prosim nejak inak predelat aj predmety a objekty?
![obrazek](https://user-images.githubusercontent.com/57906106/162177094-4f31d2fb-bfb7-4135-a8f2-40427b981094.png)
Dekuji

**Comment by motyc** [comment]
Napadají mne tři věci:
1) pro počet a poznámku není třeba textarea, stačí normální pole na jeden řádek
2) tooltip vždy stačí pro celý sloupec, nedává smysl am dokola opakovat totéž
3) chování by mělo být jednotné s akcí - tj. jedno ukládací tlačítko (#287), chování volby "odstranit" (#292) atd.

**Comment by motyc** [comment]
Tooltip vždy stačí pro celý sloupec, nedává smysl tam dokola opakovat totéž (platí pro všechny obdobné tabulky - prosím zohlednit obecně), jinak OK.

**Comment by jnihnat** [comment]
tohle by mnelo na nejaktualnejsi verzi fungovat. Opravoval som akurat zavlecenou chybu na odstraneni predmetu (chyba spred dna, mozna neni na test prostredi ani nasazena)
