### ISSUE TITLE
Rozložení formulářů - PAS

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#342]
https://docs.google.com/spreadsheets/d/1EaMlKchCjaVRDwGLYDytvEHgSEPfCqFmkxOAw9PaEQ8/edit

**Comment by jnihnat** [comment]
@motyc oproti google sheetu som upravil tieto zmeny:
- edit ulozeni som predelal na modal form (s tymi 4 poliami mi to pripadalo zbytecne to delat na samostatne obrazovce)
- kvuli tomu som nechal roztahle ulozeni na detailu na celou sirkou.
Pokud by neco z toho vadilo prosim napiste at to predelam podle google sheetu/ nebo jinak.
Dekuji

**Comment by motyc** [comment]
@jnihnat Zkusíme to, až to bude nasazené a případně se dohodneme. Myslím ale, že to bude ok.

**Comment by motyc** [comment]
Tlačítko "Poloha" udělat tak, aby vypadalo jasně jako tlačítko (máme obvykle v barvě dané workflow) a nějak lépe esteticky pojednat (nyní se divně při najetí myši rozsvěcuje ten pin atd.).
