### ISSUE TITLE
Modul Externí zdroje

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#343]
**Přidání funkcionality sestává ze dvou částí:**
- Doplnění správy externích zdrojů (v AMČR původně nazýváno “Bibliografie”)
- Doplnění externích odkazů do view archeologických záznamů (akcí a lokalit)
- Zadání formulářů viz: https://docs.google.com/spreadsheets/d/130YHMD3QNuwzZYZJACbiqp0icYQsrCIQWOL89eKn2rk/edit

### Správa externích zdrojů
- [x] Související URL budou mít schéma http://192.168.254.30:8080/ext-zdroj/*
- [x] Má samostatnou položku “Externí zdroje” na úvodní obrazovce (barva - P. Kudela navrhnout, aby ladilo se zbytkem) a související menu, s volbami:
- Zapsat zdroj
- Vybrat zdroje
- Moje zdroje
- Potvrdit zdroje
- [x] Záznam se skládá z:
- Formuláře pro popis externího zdroje
- Tabulky externích odkazů (tj. vazeb na archeologické záznamy)
- [x] V tabulce externích odkazů musí být možné:
- přidat nový odkaz na archeologický záznam
- editovat paginaci odkazu
- zrušit existující odkaz
- [x] Záznam může nabývat stavů (vracení funguje standardně):
- 1 - zapsaný
- 2 - odeslaný
- 3 - potvrzený
- [x] Správa obsahuje standardní funkcionality (smazání, historie, výpis apod.)
- [x] Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2
- [x] Zdroj vzniká s dočasným ID (“X-” na začátku), trvalé ID je přiděleno při prvním potvrzení (při jakékoli další změně stavu se již nemění). Struktura ident_cely odpovídá schématu:
[BIB]-[pořadové číslo v sedmimístném formátu]
Příklad: BIB-0000001
Má verzi s provizorním ID: X-BIB-0000001
Přidělování lze řešit sekvencí v DB.

### Externí odkazy u archeologických záznamů
- [x] U všech typů archeologických záznamů (akce, lokality) přibude tabulka externích odkazů (rozložení viz https://docs.google.com/spreadsheets/d/1Ms3WEEfARICKbUr25_vGD7ymmwPJEaMw8WbcSB4UdwM/edit#gid=1077257469 a https://docs.google.com/spreadsheets/d/1jwzkkpbFgAiywPsET54y5Spwrr6gv8-FLiOUJoQcQL0/edit#gid=1077257469)
- [x] V tabulce externích odkazů musí být možné:
- přidat nový odkaz na externí zdroj
- editovat paginaci odkazu
- zrušit existující odkaz

**Comment by jnihnat** [comment]
@motyc 
- prosim doplnit heslare pro SYSNO
- prosim popsat sloupce pro tabulku vyhledavani (poradi, primarne zobrazene, dodatocne zobrazene)

**Comment by motyc** [comment]
@jnihnat
- SYSNO - nemá heslář, jde výběr má být fulltext (chyba zadání opravena)
- Sloupce (tučně primárně zobrazené):
-- **Typ záznamu**
-- **Autor**
-- Editor
-- **Rok vydání/vzniku**
-- **Název/označení**
-- Název časopisu/deníku
-- Ročník/číslo
-- Název sborníku
-- SYSNO

**Comment by jnihnat** [comment]
@motyc - co znamena v google tabulce u zapsat "pouze typ zaznamu..."? Jenom v tom pripade se ma zobrazit/byt povinne pole/byt povolene k zapisu(jinak zasedle)?
Predem dekuji

**Comment by motyc** [comment]
@jnihnat Znamená to, že pole je dostupné k vyplnění pouze pro daný typ záznamu a v případě volby jiného je neaktivní. Podobně, jako je to např. se vztahem oznamovatele a typu projektu.

**Comment by motyc** [comment]
### Výsledek testu
(test filtračního formuláře ještě probíhá, výsledky dáme zvlášť)
- [ ] směrem od archeologického záznamu:
-- nejde editovat paginace - doplnit stejně jako je v detailu zdroje
-- nezobrazuje se rok (sloupec je prázdný, i když vyplněno)
- [ ] autory v tabulkách je třeba oddělovat středníkem, protože čárka se používá mezi příjmením a jménem (viz např. http://192.168.254.30:8080/arch-z/akce/detail/C-9111704A)
- [ ] záhlaví je řešeno jinak než v ostatních modulech - popisek má být hned vedle ikony v tmavé části a ve světlejší části má být ident_cely, pokud jsem na konkrétním záznamu
- [ ] http://192.168.254.30:8080/ext-zdroj/zapsat (stejně tak edit) - formulář se vůbec neupravuje podle zvoleného typu zdroje (viz zadání v https://docs.google.com/spreadsheets/d/130YHMD3QNuwzZYZJACbiqp0icYQsrCIQWOL89eKn2rk/edit#gid=474149344 a https://github.com/ARUP-CAS/aiscr-webamcr/issues/343#issuecomment-1307792745)
- [ ] autory a editory je třeba řešit stejně jako je to nově u dokumentu, tj. aby bylo zohledněno pořadí (je k tomu vždy pole v DB)
- [ ] http://192.168.254.30:8080/ext-zdroj/edit/ - chybí tlačítko zpět
- [ ] editace je možná i u záznamu ve stavu 3 - tam znemožnit editaci detailu, ale zachovat možnost přidávat nové odkazy a upravovat paginaci
- [ ] http://192.168.254.30:8080/ext-zdroj/vyber?stav=3 - je třeba zobrazovat záznamy ve stavu 2, nikoli 3 (tj. ty, které je potřeba potvrdit)
- [ ] http://192.168.254.30:8080/historie/ez/BIB-0000013 - v historii je odeslání zaznamenáno jako “import” (tj. posun 1->2) - neřeším teď název, ten upravíme, ale problém je v tom, že se to zjevně zaznamená stejně, jako samotný zápis (tj. x -> 1); projevuje se to i ve stavové liště, kde u “Odeslaný” chybí údaj, i když to všemi stavy prošlo
- [ ] `Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2` - asi opomenuto
- [ ] rok vydání ve formuláři by se měl testovat na RRRR
- [ ] odvozování dočasného ident_cely by mělo fungovat jako např. u projektu, tj. nemělo by docházet k tomu, že se jedno ID používá opakovaně:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/bb482358a3e5f1c46545c4792b7a8dfb2fdab38a/webclient/core/ident_cely.py#L27

**Comment by jnihnat** [comment]
@motyc - k bodu:
- autory a editory je třeba řešit stejně jako je to nově u dokumentu, tj. aby bylo zohledněno pořadí (je k tomu vždy pole v DB)
- mam to pripravene, ale dokonceni pak bude v #670 
- je treba predelat na asynchronni heslar a to pak souvisi s dodelavanim pridavani osoby do async heslare. Tedka to je jen v synchronnim heslari.

**Comment by motyc** [comment]
@jnihnat Ok, není problém.

**Comment by jnihnat** [comment]
@motyc k bodu:
editace je možná i u záznamu ve stavu 3 - tam znemožnit editaci detailu, ale zachovat možnost přidávat nové odkazy a upravovat paginaci
- ma jit i dopojovat v pirpade stavu 3?

**Comment by motyc** [comment]
@jnihnat Ano.

**Comment by jnihnat** [comment]
@motyc 
Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2 - asi opomenuto
- tohle mi funguje jak lokalne tak na serveru. nemohli ste to jen prohlidnout protoze byl spatny zaznam v historii a nezobrazovalo se datum?

**Comment by jnihnat** [comment]
@motyc tohle nemuzu nasimulovat:
při exportu po tom, co jsem záznamy seřadil podle se některé záznamy exportují vícekrát:
[export_externi-zdroje_2022-12-02-14-12-44.xlsx](https://github.com/ARUP-CAS/aiscr-webamcr/files/10141329/export_externi-zdroje_2022-12-02-14-12-44.xlsx)
nepamatujete si jak presne vyzeral filter a razeni? Klidne mi sem muzete dat celou url. Dekuji

**Comment by motyc** [comment]
@jnihnat Jeee, vypadlo slovo - podle autorů :) Teď jsem to testoval a stále to platí (http://192.168.254.30:8080/ext-zdroj/vyber?sort=autor)

**Comment by jnihnat** [comment]
@motyc - ohledne roky vydani a vzniku - jaky tvar ma mit? jenom rok? v DB vidim jeden zaznam ktery ma 2010-2015 (ident - X-BIB-0809031) Dost se potom odvozuje jak se ma zadavat a filtrovat. Dekuji

**Comment by motyc** [comment]
@jnihnat Máte pravdu, nemůže to tak být a nic s tím neuděláme, protože tam mohou být různé hodnoty. Při kontrole ani při tvorbě zadání mi to nedošlo. Tím pádem ale nemůžeme použít ani řešení ve filtračním formuláři. Nechte to bez testu + filtraci lze upravit takto: https://docs.google.com/spreadsheets/d/130YHMD3QNuwzZYZJACbiqp0icYQsrCIQWOL89eKn2rk/edit#gid=826933236

(odebráno vyhledávání podle roku + rok_vydani_vzniku doplněn do popisných údajů)

**Comment by motyc** [comment]
@jnihnat A ten filtrační formulář se s tím popere, i když to bude takto nestandardní?

**Comment by jnihnat** [comment]
myslel jsem jen pro zadavani u zapsani a edite. Filtr bych odstranil, to bychom museli delat vetsi logiku ak bychom to chteli i filtrovat.

**Comment by motyc** [comment]
Rozumím, asi bych to tím pádem nechal být (regex nedoplňoval), protože bych musel prověřit, co vše může nastat a nemá smysl to teď komplikovat. V případě potřeby zadáme úpravu.

**Comment by motyc** [comment]
### Výsledek test
- [ ] - tlačítko pro přidání odkazu se ve stavu 3 zobrazuje, ale nejde použít (nic nedělá) - např. http://192.168.254.30:8080/ext-zdroj/detail/BIB-0000012
- [ ] - [ ] `Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2` - asi opomenuto (platné, testováno pro http://192.168.254.30:8080/ext-zdroj/detail/X-BIB-1276028 + http://192.168.254.30:8080/arch-z/akce/detail/M-9000074A)

**Comment by jnihnat** [comment]
k bodu 2 - ten u mne normalne funguje, skusil som to i na serveru s dotycnym arch zaznamom a tam mi to taky fungovalo, tedka je arch zaznam archivovany a ez odeslany.

**Comment by jnihnat** [comment]
vse ostatne opraveno v #826 (posledni 2 body rovno k testu, script jsem uz pustil)

**Comment by motyc** [comment]
@jnihnat `Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2` - už vidím, kde je problém, je to jen nedorozumění. Nyní se to děje při A2 -> A3, má se to dít při A1 -> A2. Vyčlenil jsem to do nového issue (), toto je jinak ok.
