### ISSUE TITLE
Responsivní chování a optimalizace pro prohlížeče

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#344]
- [ ] Zajistit základní responsivní chování všech obrazovek (správné překrývání prvků, vhodné zalamování, řazení pod sebe, chování modal oken apod.) při šířce >= 360 px. Pod tuto šířku se šířka fixuje a zapne se rolování do stran pro celou stránku.
- [ ] Nutno odladit pro Chrome, Mozilla Firefox, MS Edge and Safari.
- [ ] Zvlášť odladit modul PAS tak, aby zápis a editace nálezů bylo možné pohodlně provádět na mobilním zařízení.
- [ ] Zobrazení obsahu tabulek s rolováním uvnitř tabulky je v aktuální verzi poměrně vyhovující, zde není třeba významně zasahovat (chybí pouze např. zobrazení tooltipů s pokračováním textu) - problém je ale v elementech vně tabulek.

V případě potřeby by myslím mohl s laděním vypomoci Petr Kudela z Inovatiky.

Zahrnuje obecnou revizi v rámci hodinového odhadu (nelze odhadnout přesně a hodiny po dohodě podle potřeby flexibilně navýšíme)

**Comment by pesikj** [comment]
Na setkání bylo domluveno optimalizovat jako první stránku PAS.

**Comment by motyc** [comment]
### Testování v0.3.5z18
Celkově to je myslím nad očekávání dobré a je to třeba spíše doladit, než že by něco fundamentálně nefungovalo. Skvělé je, že použitelné jsou bez větších problémů víceméně všechny části aplikace.

**Obecné**
- [ ] Chování pro karty na úvodních obrazovkách (např. http://192.168.254.30:8080/arch-z/lokalita/) není odladěné. Karty by měly mít nastaveno min-width na 205px (jako je základní šířka) a v případě že se nevejdou vedle sebe, měly by se řadit pod sebe, nebo se případně změnit na jiný typ zobrazení (např. skrytím těch barevných částí. Také není dořešeno zobrazení nápovědného textu na mobilu, protože se dostává zcela mimo obrazovku a na mobilu nebude fungovat h:over.
- [ ] Nepřipouštěl bych stav, kdy máme horní lištu dvouřádkově, nevypadá to dobře a nevejde se do ní volba jazyků. Lepší bude skočit rovnou na variantu s ikonami:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2a054467-dd43-4ecc-9e0c-2ec6012c4342)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/08447c4e-ddac-4d6b-b5af-51e9025a005d)
- [ ] Pokud je v mobilním zobrazení vysunuto levé menu, ikona pro pravé menu divně uskakuje. Buď bych jí nechal v pozadí a neaktivní, nebo menu ve chvíli, kdy dochází k překryvu roztáhl na celou šířku zobrazení (jen pak je třeba vhodně vyřešit jeho zavření). Problém je i s ident_cely, pokud je vypsán v záhlaví:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/52e604c9-2844-40d8-9f81-cf29e072c5a2)
- [ ] U všech užití `app-divider-label` by bylo dobré o zvětšit horní margin/padding celého řádku na 10 px, protože tyto elementy jsou všude hodně blízko předchozímu prvku. To ztěžuje orientaci a hlavně se na se na ně těžko trefuje při klikání (zejména na mobilu) ve filtračních formulářích. Dále bych pro daný element upravil font-size na 100% (nyní 80%).
- [ ] Pokud jsou systémové hlášky delší, celý box se divně posouvá ke straně. V mobilním zobrazení je to rozhozené úplně.
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/22c411e6-44a3-44c7-9abc-e2b99b1f3d20)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/758c0acd-3991-4454-8320-bc739e4d49fc)
- [ ] Nikde nefunguje tooltip u lišty s přehledem stavů (jen problikává)
- [ ] Je třeba vhodně dořešit zalamování patičky (např. zalamovat za "PARTNEŘI":
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5bfbd2d5-aa9b-4686-8a3a-d07d72d9e183)
- [ ] Sjednotit výpis ident_cely v mobilní verzi na způsob řešení jako je u projektu.
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/38e433bc-c9eb-48e8-a64c-bc05dfc5d50f)
- [ ] Při procházení jsem nalezl chyby v používaných ikonách:
-- u modulů lokalit a PAS se nezobrazuje správná ikona z menu, ale všude je ikona akce
-- v externím zdroji neodpovídá ikona v záhlaví ikoně v menu
-- ikony v tabulkách historie by měly vždy odpovídat nadřazenému záznamu, nyní je všude ikona projektu

**Projekty**
- [ ] Mapa je v některých zobrazeních příliš úzká a levé menu se skrývá zbytečně pozdě. Pro mapu bude třeba nastavit vhodnou minimální šířku (např. 400 px), aby nedocházelo k takovýmto situacím:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f66fabfb-1d69-491a-af21-0669f5041e54)

**Arch. záznamy**
- [ ] Modal pro smazání komponenty se nezobrazí (je místo něj jen čára); viz např.: http://192.168.254.30:8080/arch-z/akce/detail/C-9108573A/dj/C-9108573A-D01/komponenta/detail/C-9108573A-K001
- [ ] U akce se pole při zužování okna deformují nad únosnou mez. Menu by se mělo zasunout dříve a stejně tak by mělo dříve dojít k přepnutí na mobilní zobrazení s poli pod sebou.
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/d564fe0f-a33d-4acf-90a1-da1039602c2b)
- [ ] 

**Dokumenty**
- [ ] http://192.168.254.30:8080/dokument/detail/X-M-TX-000000015/komponenta/X-M-TX-000000015-K001 - hesláře pro nálezy se rozbalují pod záhlaví formuláře a nejdou tak použít
- [ ] http://192.168.254.30:8080/dokument/detail/M-DD-202300001/cast/M-DD-202300001-D001 - výpis části dokumentu se špatně zarovnává a chybí u něj horní margin:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/93352e12-925f-49ee-a6a4-b5b01c0336b1)

**Knihovna 3D**
- [ ] Mapa překrývá část polí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/70075e51-326b-4a80-bb20-9a8f45f7fceb)

**PAS**
- [ ] Ve formuláři nálezu je část polí v mobilní verzi zkrácená:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/1e36d678-f965-4490-9725-d00ed176ec93)

**Tabulky**
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a23ede67-dea2-448a-8112-0f5511ea0f04)
- [ ] "Počet nalezených záznamů" bych od určité šířky přesouval na nový řádek, aby nedocházelo k deformaci tlačítka filtrace.
- [ ] Ve spodní části je třeba vyřešit překryv tlačítek (Přejít na list + strákovač + Záznamů na list) a úpravu stránkovače, pokud se sám o sobě nevejde na šířku zobrazení.
- [ ] V mobilní verzi se ani na kliknutí neotevře tooltip s pokračováním zkráceného obsahu buňky.
- [ ] Aktivní stránka se zobrazuje nad levým menu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/16ce1d47-f10d-48dc-917e-dc77cee4e978)
- [ ] V tabulkách historie skrývat popis v záhlaví a ponechat jen ikonu, jako je tomu v ostatních zobrazeních
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/71de7250-998c-425e-9670-5bceb79373ae)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/204e37dc-f5f2-4b9b-bc81-38e8a20644b5)

**Comment by motyc** [comment]
@pesikj Nevím, jestli o tom víte, ale v kontextu úprav zmizely vrstevnice z karet:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/41ff265a-6ad9-4c9d-b1b7-592398ac2ee6)

Bezva je ta úprava rozestupů nadpisů ve filtračních formulářích + zvětšení písma, jen ty odstupy by byly dobré mírně zvětšit i v běžných formulářích, protože tam se to také slévá:

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/507c9b77-c29d-4f14-ae90-c9b0c344ed78)

Samozřejmě to ale beru jako rozpracované, jen reportuji drobnosti, co vidím hned.

**Comment by motyc** [comment]
### Testování v0.3.5z67
Vím, že to nebylo komplet hotové, ale když aplikaci procházím, dám rovnou zpětnou vazbu k hotovému.

**Obecné**
- [ ] _Chování pro karet na úvodních obrazovkách (např. http://192.168.254.30:8080/arch-z/lokalita/) není odladěné._ - zlepšilo se, ale:
-- karty seřazené pod sebe nemají žádný spodní/horní margin, takže se slepí k sobě, což nevypadá hezky
-- zobrazení textu v rámci karty při mobilním zobrazení je zajímavý nápad, ale z hlediska ovládání to není úplně srozumitelné a ergonomické - navrhoval bych v mobilním rozhraní na text ke kartě prostě rezignovat a nedoplňovat ho
-- stránka http://192.168.254.30:8080/projekt/ nyní je nějak rozbitá a popisné texty jsou naopak jen v mobilní verzi
-- v mobilním zobrazení není potřeba prostor pro hover logo, takže bych tam kartu zmenšil i na výšku nějak takto:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/3411cf5b-8bf9-46cf-a2b4-3d0c8c0db881)
-- pokud jsou karty jen v jednom sloupci, bylo by dobré je roztáhnout na celou šířku obrazovky (s rozumným margin), aby nebyly tak divně uskočené do strany
- [ ] Nepřipouštěl bych stav, kdy máme horní lištu dvouřádkově, nevypadá to dobře a nevejde se do ní volba jazyků. Lepší bude skočit rovnou na variantu s ikonami:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2a054467-dd43-4ecc-9e0c-2ec6012c4342)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/08447c4e-ddac-4d6b-b5af-51e9025a005d)
-- zde je to nějaké porouchané, protože ta varianta s ikonami nyní vůbec neexistuje a to menu, co lištu nahrazuje také vůbec nefunguje (po kliknutí nic nezobrazí)
- [ ] Víceřádkovou variantu bych nepřipouštěl ani pro lištu v záhlaví záznamu. Zobrazí se jen ve velmi malém rozsahu šířky a lepší bude zobrazit rovnou tu variantu s ikonami:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/d60f0ae2-771d-43da-9488-199577ae7e28)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/00729e06-31fd-40d6-abfd-96d9d2770eac)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/8958f618-0933-4193-8c80-1a0d697de648)
- [ ] Box s chybovými hláškami se chová o něco lépe, ale čím je zobrazení bližší mobilnímu, tak s tím je stále větší problém a na mobilu je to úplně u strany a malé:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7f645abc-7625-485f-b3d1-616ba0e3f429)
- [ ] Pro levé menu v některých zobrazeních chybí tlačítko pro zavření:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/c8397390-5f20-4a41-81f3-5a0d5acc19de)

**Stavová lišta**
- [ ] Rozpadla se vazba mezi číslem a popiskem, takže u možností s málo kroky je tam divná mezera:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/3f6dd6f7-7212-44fc-b8b5-b26cd6afbee2)
- [ ] Zvláštní mezera je nově i mezi názvem stavu a souvisejícím datumem:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/dab98e86-ef1b-40e0-89f3-6e16700c818c)
- [ ] Problém je také se zobrazením horizontálního rolovátka na PC protože se zobrazí jen na začátku, ale po vertikálním rolování zmizí a už nejde zobrazit. Totéž se děje např. u tabulek souborů (apod.):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/794b3770-cba7-40a6-8f40-8e0d0eee7453)
- [ ] Někde se datum dostává vedle názvu stavu (http://192.168.254.30:8080/pas/detail/C-202009779-N00001):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/9d355657-5cae-4466-8d47-ebad72fb7d48)
- [ ] U projektů se lišta nevejde na obrazovku ani při plném rozlišení, což mi přijde zbytečné, když jsou mezi stavy stále velké mezery; navíc je divná i ta velmi krátká spojovací čára, kdy margin je širší než čára samotná:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5b0ee766-da2a-4ec1-9dfc-05dc029484a4)
- [ ] Chování (problikávání) tooltipu se o něco zlepšílo, ale stále to není ideální (např. http://192.168.254.30:8080/dokument/model/detail/C-3D-202200001). Chtělo by to nějaké stabilnější řešení, které tolik nevisí na délce obsahu tooltipu.

**Projekty**
- [ ] Mapa překrývá vysunuté levé menu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/43adb35b-35dc-4452-9520-0421b710a99e)

**Arch. záznamy**
- [ ] U modulu lokalit se nezobrazuje správná ikona z menu, ale všude je ikona akce

**Knihovna 3D** (nyní nejde testovat)
- [x] Mapa překrývá část polí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/70075e51-326b-4a80-bb20-9a8f45f7fceb)

**Oznámení**
- [ ] špatně zalamují loga v záhlaví:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/8c762b9a-446a-41b7-884f-19023ab4c12a)
- [ ] Výrazně zlepšit font nadpisu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/ba2e5cd5-c55e-4caa-b7be-884c3e22e216)

**Tabulky**
- [ ] _V mobilní verzi se ani na kliknutí neotevře tooltip s pokračováním zkráceného obsahu buňky._
-- problém je nyní v tom, že po otevření záznamu a kroku zpět tooltip s ID zůstává viset a nejde nijak zavřít, kromě refreshe okna
-- problém s chybějícím tooltipem se týká i všech formulářů - na PC se zobrazí při najetí, ale na mobilu není jak zobrazit zbytek textu, pokud se do formulářového pole nevejde
- [ ] V Mozille se špatně zobrazuje sloupec s náhledem - je zbytečně roztažený. Podobný problém je někdy i u dalších sloupců (např. http://192.168.254.30:8080/ext-zdroj/vyber)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/158ee20e-ccd4-4c47-9f73-fec8db4b8263)
- [ ] Nejde přidávat výškové body, protože seznam se zobrazuje takto uvnitř tabulky, kde se přidá vertikální rolovátko. Stejný problém je s přidáváním nálezů ke komponentě (u arch_z i dokumentu), u dalších vedoucích atd:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5ecf7efe-1249-4cb8-b323-f21598650c53)
- [ ] Nedávat číslo u počtu záznamů tučně, vypadá to zvláštně:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/5f62d5b3-62b3-45b9-ba7a-98b6a5888b41)
- [ ] Lister je na mobilu bezva, ale v zobrazení tabletu je chvíle, kdy to zlobí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/2fddbabb-3979-4870-b71f-8393e88cdd31)

**Mapa**
- [ ] _Při editaci PIAN se poslední tlačítko schová za měřítko_ - původní problém již ok, ale je tam ještě trabl se souvisejícím menu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/85004c25-3e67-4b72-93bc-86d03faba60c)

**Comment by pesikj** [comment]
@motyc 

>  Problém je také se zobrazením horizontálního rolovátka na PC protože se zobrazí jen na začátku, ale po vertikálním rolování zmizí a už nejde zobrazit. Totéž se děje např. u tabulek souborů (apod.):

Toto se mi nepodařilo nasimulovat (testoval jsem na Chromiu a Firefoxu).

**Comment by pesikj** [comment]
@motyc 

> -- problém je nyní v tom, že po otevření záznamu a kroku zpět tooltip s ID zůstává viset a nejde nijak zavřít, kromě refreshe okna

Nepodařilo se nasimulovat.

**Comment by motyc** [comment]
Issue rozděleno na dílčí konkrétní položky, toto již zavírám.
