### ISSUE TITLE
Záhlaví formulářů udělat též v barvě patřičné workflow

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#347]
Záhlaví formulářů udělat též v barvě patřičné workflow. Hodně splývají s pozadím a když člověk odroluje hlavní záhlaví, tak barvu už nikde nevidí.

**Comment by jnihnat** [comment]
upravena barva zahlavi a nadpisu (bila jinak by splivala se zelenou napr u arch zaznamu) Pripadne je mozne upravit na jiny odstin viz v title leva a prava cast.
