### ISSUE TITLE
Úprava marginů a řádkování

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#348]
- Stále je to vše graficky hodně roztahané, se spoustou zbytečných mezer atd.; pokusit se o zmenšení polí, marginů atd. tak, aby se toho na obrazovku vešlo co nejvíce.
- Formuláře, tabulky (a celkové rozložení) - zmenšit výšku řádků (line-height: 1.5 -> 1)

**Comment by pesikj** [comment]
![image](https://user-images.githubusercontent.com/15179154/175496230-1785f0df-c55b-44a1-95b3-c21567110b30.png)

Stačí formuláře takto?

**Comment by motyc** [comment]
@pesikj
- ad formuláře:
-- nechal bych o něco málo (kolem 2 px) větší mezeru nad nadpisy polí, aby byly blíže k poli, se kterým souvisí, než k tomu nad sebou
-- pokud to jde, zmenšil bych padding polí (vnitřní odstup od rámečku) tak na polovinu; pole jsou kvůli tomu zbytečně vysoká

- ad tabulky: takto super

**Comment by pesikj** [comment]
@motyc Je možné změnit výšku polí. U formuláře s poli pro čtení je to docela ok, pro formuláře s editací je to problém hlavně kvůli heslářům, které jsou komplexnější a vypadá blbě, když jsou jinak vysoké než běžná políčka pro vstup. Můžeme zatím provést změnu pouze pro formuláře pro čtení?

**Comment by motyc** [comment]
@pesikj Můžeme to udělat tak, že na těch pro čtení otestujeme vhodné nastavení a v návaznosti by se to dodělalo i pro ty na editaci (jestli tam tedy není vyloženě technický problém). O editaci nám ale jde především, protože většinu času uživatelé budou pracovat v režimu zápisu a úpravy dat a jde o to dostat toho na obrazovku více, aby se nemuselo tolik rolovat. Určitě by ale nebylo dobré, aby pole s hesláři byla jinak vysoká. Takže nemám problém s rozložením v čase, ale chtělo by to vyřešit oboje.

**Comment by pesikj** [comment]
![image](https://user-images.githubusercontent.com/15179154/175563813-26d30b80-b244-4217-80cf-9dfe669d79ab.png)

@motyc OK, zatím mám tuto verzi.

**Comment by motyc** [comment]
### Výsledek testu
V principu je to vyhovující a aplikaci to velice prospělo, ale bude třeba provést ladění.

- [ ] Pole v editačních a filtračních formulářích mají různé výšky a zarovnání (známý nedostatek, viz výše).
- [ ] U tabulek se chybně zobrazují ovládací tlačítka (všude):
![image](https://user-images.githubusercontent.com/20186892/175884427-e6799a68-a366-442a-9d5b-1a48638fc3fc.png)
- [ ] Je uskočené tlačítko "Další volby" (všude):
![image](https://user-images.githubusercontent.com/20186892/175884606-5dd97ce1-fab1-48d1-9e53-6579e935e254.png)
- [ ] Záhlaví historie souboru splývá s detaily:
![image](https://user-images.githubusercontent.com/20186892/175885757-5f41014c-a851-4895-8ddb-cd9141dc9bea.png)
- [ ] Nad stavovou lištou je zbytečně velká mezera (stačí jako tak pod ní), navíc pokaždé jiná (sjednotit):
![image](https://user-images.githubusercontent.com/20186892/175886371-2324ac00-3df8-475d-ab6f-a6927e477917.png)
![image](https://user-images.githubusercontent.com/20186892/175886564-96a6883a-511e-4afc-91d4-9f6a376137aa.png)
- [ ] Ve 3D utíká zápatí od spodního okraje:
![image](https://user-images.githubusercontent.com/20186892/175886824-fe4b3a2d-afcb-434f-9f01-d354118f2371.png)
- [ ] Je třeba doladit tlačítka pro přidání osoby do hesláře:
![image](https://user-images.githubusercontent.com/20186892/175887055-d100bfd4-5e9c-42f6-9368-ad8857aa469f.png)
- [ ] Je třeba doladit označení povinných polí a výplně rozbalovacích seznamů: 
![image](https://user-images.githubusercontent.com/20186892/175887286-a72ed1e7-4d2a-48f1-a154-ffb5a28eb034.png)
- [ ] Při editaci je užíváno větší písmo, které se nevejde do pole (při zobrazení to problém není:
![image](https://user-images.githubusercontent.com/20186892/175887952-e347093d-7fd3-4a06-a83e-459473bc834b.png)
- [ ] Patrně s tím souvisí nová chyba, že textová pole ve formulářích není možné roztáhnout pomocí aktivního rohu (nic nedělá, dříve fungovalo):
![image](https://user-images.githubusercontent.com/20186892/175888270-0c4ae445-d711-4824-80c7-ef66ee27aa48.png)

**Comment by motyc** [comment]
@pesikj Ano, rozumím a nebudeme na tom trvat. Nějak se dohodneme.

**Comment by MaxKosta** [comment]
@motyc Zvětšil jsem rozestupy mezi jednotlivými prvky uživatelského rozhraní. Zkontrolujte, prosím, jestli je to tahle v pořádku. Pokud ne, tak mi napište, jak si to přejete upravit
<img width="1918" alt="historie" src="https://user-images.githubusercontent.com/74970764/182614384-0d726384-d1c2-4030-821d-18effb0af7a8.png">
.

**Comment by motyc** [comment]
@MaxKosta Screenshot je za mne ok,

Cílem úpravy v tomto vlákně bylo primárně zmenšit výšku polí a řádků tabulek, případně redukovat zbytné mezery mezi prvky. Zkrátka aby se toho na jednu obrazovku vešlo více bez rolování. V obecné rovině by se prvky na obrazovce opticky ale neměly slévat dohromady.

**Comment by MaxKosta** [comment]
@motyc Můžete prosím vás ověřit úkol na test serveru?

**Comment by motyc** [comment]
@MaxKosta K testování se dostanu zítra.

**Comment by motyc** [comment]
### Výsledky testu
Došlo k velkému posunu k lepšímu. Zde korekce:

- [ ] http://192.168.254.30:8080/projekt/ (a všechny obdobné) + všechny formuláře bez stavové lišty (zapsat a edit; např. http://192.168.254.30:8080/projekt/zapsat) - došlo ke slinutí záhlaví a obsahu. Patrně to souvisí s úpravou stavové lišty podle https://github.com/ARUP-CAS/aiscr-webamcr/issues/348#issuecomment-1167009990
![image](https://user-images.githubusercontent.com/20186892/185102663-4b2c1811-c747-4c52-b80f-d846ab759f0f.png)

- [ ] Tabulky s výběrem:
1) Tlačítko pro filtraci není zarovnáno na střed řádku, resp. není zarovnáno stejně jako ovládací tlačítka tabulky.
2) Ovládací prvky tabulky jsou odsazené daleko od jejího záhlaví a naopak se slévají s pruhem záhlaví stránky.
3) Tlačítka pro ovládání nejsou zarovnána s poli.
![image](https://user-images.githubusercontent.com/20186892/185103672-316da087-9f51-45ac-9a7d-10b1e8ad7682.png)

- [ ] http://192.168.254.30:8080/projekt/detail/C-202007056 (a všechny obdobné) - tlačítka pro posuny stavů nejsou vertikálně na střed a jejich oddělovače nejdou až na kraj lišty. 
![image](https://user-images.githubusercontent.com/20186892/185104613-41ae0f6e-8fba-4416-b4df-6e03efb2aa27.png)

- [ ] Tlačítka pro přidávání osob do hesláře jsou graficky rozhozená (je vidět, že vlevo přesahují rámeček a celkově jej nerespektují).
![image](https://user-images.githubusercontent.com/20186892/185108295-21f71fea-9234-49c5-bb84-9fc1eea4742a.png)

- [ ] http://192.168.254.30:8080/oznameni/ - zůstala zbytečně velká mezera nad stavovou lištou
![image](https://user-images.githubusercontent.com/20186892/185110093-4e2c70cb-56a9-4875-bfdf-a5e5a2ed6f30.png)

- [ ] http://192.168.254.30:8080/dokument/model/detail/C-3D-202000002 - utíká zápatí od spodního okraje:
![image](https://user-images.githubusercontent.com/20186892/185112166-54b46a78-a4bc-49a7-841b-87f258571a4f.png)

- [ ] Je třeba doladit označení povinných polí a výplně rozbalovacích seznamů: 
![image](https://user-images.githubusercontent.com/20186892/175887286-a72ed1e7-4d2a-48f1-a154-ffb5a28eb034.png)

- [ ] Údaj o stavu akce není vertikálně na střed řádku (nejsem si jistý, ale možná je to problém většiny hodnot v dané tabulce, jen je to u toho tagu nejlépe vidět):
![image](https://user-images.githubusercontent.com/20186892/175894272-eeaff7b9-5366-4fa3-8a59-9eea1d5acaca.png)

- [ ] Všechna pole ve formulářích, která mají být víceřádková, tak nejsou (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/338#issuecomment-1173146345)

- [ ] http://192.168.254.30:8080/pas/spoluprace/vyber - výška řádku v tabulce je větší než u ostatních tabulek
![image](https://user-images.githubusercontent.com/20186892/185114057-4c441237-d0ae-473d-841b-591d55438cbf.png)



Neprocházel jsem všechna pole jednotlivě, abych popsal drobné posuny u nich (na několik případů jsem narazil). Otestujeme to systematicky a dáme k tomu zpětnou vazbu najednou. Celkově tam ale velký problém není.

**Comment by pesikj** [comment]
> Tlačítko pro filtraci není zarovnáno na střed řádku, resp. není zarovnáno stejně jako ovládací tlačítka tabulky.

@motyc 
To není úplně přesné, je tam problém s marginy, horní margin byl větší než spodní. Nastavením marginů na stejnou hodnotu je pak tlačítko ve středu řádku.

**Comment by pesikj** [comment]
@motyc Texty na střed zarovnané jsou, je to vidět, pokud si zvětšíte stránku. Badge jsem opravil

![image](https://user-images.githubusercontent.com/15179154/187469371-2ed98f35-5ec3-4b88-a487-affa516c8e1d.png)

**Comment by motyc** [comment]
### Doplněk k testování
Na aktuální verzi aplikace jsem prošel všechny formuláře a výsledky testu zaznamenal do této tabulky: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0 (tabulka zaznamenává i chyby, které přímo nesouvisí s tímto issue a celkově popisuje stav formulářů). Červeně zvýrazněné jsou chyby, žlutě jsou návrhy na úpravy (zatím jen poznámky pro mne).

Kontroloval jsem různé aspekty a lze říci, že 90% problémů je způsobeno následujícími body:
- [ ] všechny pole se seznamy jsou špatně zarovnaná a užší než inputy; celý element má sice 24 px, jako ostatní, ale výplň je menší (uvnitř div, ca 19 px), navíc jsou všechny uskočené o několik px níže na řádku
- [ ] pole s asynchronními hesláři a zároveň s možností multivýběru jsou všechna špatně zarovnaná, ale hlavně při přidání více hodnot pole přeteče a hodnoty se zobrazují úplně mimo pole, skrývají se pod jinými prvky apod.
- [ ] všechna pole typu textarea mají špatně zarovnaný text (posunutý níže v rámci pole) + nemají správnou výšku (mají být obvykle víceřádková); v této souvislosti by ale bylo vhodné první opravit problém s tím, že element textarea je používán zcela náhodně a nikoli jen tam, kde je potřeba (víceřádková pole); to vede k nežádoucím grafickým problémům a nemožnosti používat autocomplete; zde bych doporučoval nejdříve opravit zbytečné textarea na inputy (označeno červeně ve sloupci "Typ") a pak dořešit zbylé případy, kterých bude významně méně než nyní

Pokud budou opraveny tyto tři body výše, udělám novou kontrolu a doladíme případné zbylé chyby. Z tabulky lze vyčíst to, co jsem nyní objevil i mimo tento rámec, ale i kvůli snadnější orientaci bych to bral takto popořadě.

**Comment by pesikj** [comment]
Report oprav (vše ze serveru .30)

> * [ ]  http://192.168.254.30:8080/projekt/ (a všechny obdobné) + všechny formuláře bez stavové lišty (zapsat a edit; např. http://192.168.254.30:8080/projekt/zapsat) - došlo ke slinutí záhlaví a obsahu. Patrně to souvisí s úpravou stavové lišty podle [Úprava marginů a řádkování #348 (comment)](https://github.com/ARUP-CAS/aiscr-webamcr/issues/348#issuecomment-1167009990)

![image](https://user-images.githubusercontent.com/15179154/189308747-30842745-d6e5-42bb-bb37-ed2f7b55af69.png)

> * [ ]  Tabulky s výběrem:
> 
> 1. Tlačítko pro filtraci není zarovnáno na střed řádku, resp. není zarovnáno stejně jako ovládací tlačítka tabulky.
> 2. Ovládací prvky tabulky jsou odsazené daleko od jejího záhlaví a naopak se slévají s pruhem záhlaví stránky.

![image](https://user-images.githubusercontent.com/15179154/189309170-5d529c91-b985-4817-b276-b743fb4fb76e.png)


> 3. Tlačítka pro ovládání nejsou zarovnána s poli.

![image](https://user-images.githubusercontent.com/15179154/189309830-c88af026-8391-40b2-82fa-2bbb652889b6.png)


> 
> * [ ]  http://192.168.254.30:8080/projekt/detail/C-202007056 (a všechny obdobné) - tlačítka pro posuny stavů nejsou vertikálně na střed a jejich oddělovače nejdou až na kraj lišty.

![image](https://user-images.githubusercontent.com/15179154/189309949-b57c1d84-ae77-45ab-82d5-fc0bb5174d64.png)

> * [ ]  Tlačítka pro přidávání osob do hesláře jsou graficky rozhozená (je vidět, že vlevo přesahují rámeček a celkově jej nerespektují).

![image](https://user-images.githubusercontent.com/15179154/189310021-038fb635-1ac4-4f3e-b903-f63ba31bd5df.png)


> * [ ]  http://192.168.254.30:8080/oznameni/ - zůstala zbytečně velká mezera nad stavovou lištou

![image](https://user-images.githubusercontent.com/15179154/189310404-b3caea94-4b7b-450d-a347-a4fecff0f496.png)

Vypadlo připojení k VPN, zbytek screenshotů ještě dodám.

**Comment by pesikj** [comment]
>  Je třeba doladit označení povinných polí a výplně rozbalovacích seznamů:
![image](https://user-images.githubusercontent.com/15179154/190977374-bfbd39e8-e450-4eca-ab2c-a4a7da22d759.png)

>  Údaj o stavu akce není vertikálně na střed řádku (nejsem si jistý, ale možná je to problém většiny hodnot v dané tabulce, jen je to u toho tagu nejlépe vidět):

![image](https://user-images.githubusercontent.com/15179154/190977557-149bf1f3-fb65-470b-bcfc-1d0be8bef5f7.png)

>  http://192.168.254.30:8080/pas/spoluprace/vyber - výška řádku v tabulce je větší než u ostatních tabulek

![image](https://user-images.githubusercontent.com/15179154/190980488-7c4d3a5d-e628-403b-bb9d-3c0f3b59d5bd.png)

**Comment by pesikj** [comment]
@motyc 

>  všechny pole se seznamy jsou špatně zarovnaná a užší než inputy; celý element má sice 24 px, jako ostatní, ale výplň je menší (uvnitř div, ca 19 px), navíc jsou všechny uskočené o několik px níže na řádku

Tady nevím, jestli rozumím. Píšete "užší", ale 24px je výška, takže předpokládám správně, že myslíte "nižší"?

**Comment by motyc** [comment]
@pesikj Ano, máte pravdu, myslel jsem nižší...

**Comment by pesikj** [comment]
@motyc OK a myslel jste tento div? Nyní je 21px vysoký. Není 24 kvůli okrajům nadřazených prvků.

![image](https://user-images.githubusercontent.com/15179154/191097692-54354586-750b-4495-b689-27460f7020a4.png)

**Comment by motyc** [comment]
@pesikj Ano, to by měl být on. Já asi nechci říkat, kolik to má být px a jak to přesně nastavit. Problém je v tom optickém uskočení a menší velikosti oproti inputu. Nevím ale, zda se to nezlepšilo s tou úpravou výplně, co jste sdílel výše... Mám dojem, že na serveru 30 je to nyní lepší a výška už je dobrá, jen to je posunuté na řádku.

**Comment by pesikj** [comment]
@motyc 

>  http://192.168.254.30:8080/dokument/model/detail/C-3D-202000002 - utíká zápatí od spodního okraje:

Toto jsem nebyl schopen vyřešit, protože u mě se to renderuje v pořádku a na .30 špatně. Vůbec netuším, kde může být problém. 

Ostatní popsané věci plus body z komentáře https://github.com/ARUP-CAS/aiscr-webamcr/issues/348#issuecomment-1240492524 jsou připraveny k testování.

**Comment by motyc** [comment]
### Výsledek testování
Obecně - velice dobrá práce a velká změna k lepšímu. Je třeba doladit již jen detaily:
- [ ] http://192.168.254.30:8080/pas/spoluprace/vyber - uskočené tlačítko pro novou spolupráci
![image](https://user-images.githubusercontent.com/20186892/191489096-a706af13-132f-4976-a24e-965dcd2f3f7a.png)
- [ ] Všude přestalo fungovat zasouvání menu + tlačítko není horizontálně na středu řádku
![image](https://user-images.githubusercontent.com/20186892/191489366-0642b789-8fe8-4087-913f-a1260442840a.png)
- [ ] http://192.168.254.30:8080/dokument/model/detail/C-3D-202000002 - utíká zápatí od spodního okraje:
![image](https://user-images.githubusercontent.com/20186892/185112166-54b46a78-a4bc-49a7-841b-87f258571a4f.png)
- [ ] http://192.168.254.30:8080/id/C-201228198A-D01 - rozbité zobrazení pole PIAN
![image](https://user-images.githubusercontent.com/20186892/191492433-566de800-bc49-488b-84fb-969a046bdf32.png)
- [ ] V záhlaví všech formulářů jsou posunutá tlačítka a oddělovač není až do kraje
![image](https://user-images.githubusercontent.com/20186892/191492977-a4be8220-e2fe-4c93-97fa-1f550ef93cd5.png)
- [ ] http://192.168.254.30:8080/dokument/model/detail/C-3D-202000003 (stejně tak: /dokument/model/zapsat + /dokument/model/edit/<str:ident_cely>) - chybná výška polí Popis a Poznámka (změnila se na input, asi v důsledku změny modelu dokument); je nicméně možná i alternativa nechat pole i zde jako input a jen je dát na řádky pod sebe a roztáhnout na celou šířku (možná je to i lepší řešení)
- [ ] http://192.168.254.30:8080/dokument/model/vyber - uskočené pole "Rok vzniku" část "do"
- [ ] Řešení pro asynchronní multivalue pole je sice lepší (např. http://192.168.254.30:8080/dokument/model/vyber Autoři), ale stále ne moc ergonomické - hodnoty nyní přiskakují dovnitř do pole, nicméně ukazatel při zápisu není vertikálně v ose s polem a po přidání více hodnot je trošku problém s listováním. V tomto případě bych asi za nejlepší považoval pole spíše vertikálně roztáhnout, pokud se do něj hodnoty nevejdou, spíše než přidávat rolovátko, pokud v tom tedy není nějaký problém.
- [ ] http://192.168.254.30:8080/pas/detail/M-202102544-N00002 (stejně tak: /pas/zapsat + /pas/edit/<str:ident_cely>)
-- Chyba zarovnání a výšky tlačítka "Poloha".
-- Chybná výška pole "Lokalizace".
- [ ] http://192.168.254.30:8080/oznameni/ - "Souhlasím s podmínkami" vertikálně zarovnat na střed řádku s tlačítky
- [ ] http://192.168.254.30:8080/projekt/detail/C-201902868 - chybná výška pole "Podnět"

Tabulka s přehledem polí byla též odpovídajícím způsobem aktualizována: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by pesikj** [comment]
@motyc @sedmar 

> http://192.168.254.30:8080/dokument/model/detail/C-3D-202000003 (stejně tak: /dokument/model/zapsat + /dokument/model/edit/str:ident_cely) - chybná výška polí Popis a Poznámka (změnila se na input, asi v důsledku změny modelu dokument); je nicméně možná i alternativa nechat pole i zde jako input a jen je dát na řádky pod sebe a roztáhnout na celou šířku (možná je to i lepší řešení)

Změna typu těchto polí byla explicitně požadována. Změním tedy šířku. Nicméně mi přijde nefér, aby bylo něco explicitně požadováno a následně aby splnění tohoto požadavku označeno za chybu.

![image](https://user-images.githubusercontent.com/15179154/193296577-75b6e2a7-08de-4321-8b47-bc4f0eaacf4a.png)

**Comment by pesikj** [comment]
@motyc 
> http://192.168.254.30:8080/dokument/model/vyber - uskočené pole "Rok vzniku" část "do"

Nevím, co je "uskočením" myšleno.

![image](https://user-images.githubusercontent.com/15179154/193303134-16a9e37f-57eb-4b58-8d1f-471fb786c082.png)

**Comment by motyc** [comment]
@pesikj 
> Změna typu těchto polí byla explicitně požadována. Změním tedy šířku. Nicméně mi přijde nefér, aby bylo něco explicitně požadováno a následně aby splnění tohoto požadavku označeno za chybu.
Samozřejmě by bylo nefér tak činit, ale jde myslím o omyl ze strany Huld. Úpravu jsme požadovali pro obrazovky `/dokument/zapsat/do-akce/<str:arch_z_ident_cely>` + `/dokument/zapsat/do-projektu/<str:proj_ident_cely>` + `/dokument/detail/<str:ident_cely>` + `/dokument/edit/<str:ident_cely>`, kde je jiné rozložení (pole jsou zde pod sebou a na celý řádek, což odpovídá zadání), nikoli pro `/dokument/model/*`, kde bylo rozložení původně navrženo jiné. Chápu, že se to asi při opravě nějak omylem propsalo i do view pro model, na což právě reaguje můj návrh řešení, že to prostě sjednotíme do stejné podoby i co do rozložení. Tolik jen k uvedení na pravou míru.

> Nevím, co je "uskočením" myšleno.
Pole "do" (tj. to nepopsané) je o něco málo (1 px?) výše, než pole "od", resp. i než pole Důvěryhodnost. Je to vidět i na tom screenshotu.

>Tady mi není jasné zadání. Pole má být širší, nebo se má dynamicky roztahovat na základě počtu hodnot, nebo to má být jinak?
Jsou tam dva problémy:
- blikající kurzor není v ose řádku
- když je v poli více než jedna hodnota, listování je velmi problematicky použitelné -> pokud by to šlo, tak bych u takových polí (asynchronní multivalue výběr) přidával pole dynamicky roztahoval, aby se hodnoty vešly, nebo aby alespoň bylo lépe vidět rolovátko (např. roztáhnout na tři řádky? - jde o návrh, na konkrétní variantě netrváme, jen je potřeba použít něco funkčního (stejně dobře by posloužilo např. rozbalení obsahu po kliknutí na pole, nebo něco podobného); můžeme to klidně probrat po Zoom společně a domluvit se nad živou aplikací...

**Comment by motyc** [comment]
### Výsledek testu
Zbývají poslední tři drobnosti (testováno v Chrome):

- [ ] tlačítko zasouvání menu již funguje, ale stále není horizontálně na středu řádku (oproti zbytku informací vpravo je posunuté dolů)
![image](https://user-images.githubusercontent.com/20186892/191489366-0642b789-8fe8-4087-913f-a1260442840a.png)
- [ ] http://192.168.254.30:8080/oznameni/ - "Souhlasím s podmínkami" je stále ještě o něco posunuté nahoru
![image](https://user-images.githubusercontent.com/20186892/195121864-6c1ae580-0db9-45a8-9c7e-a7a0b0d6c425.png)
- [ ] asynchronní multivalue pole (např. http://192.168.254.30:8080/dokument/model/vyber Autoři)
-- křížek pro vymazání hodnot není ve středu řádku
![image](https://user-images.githubusercontent.com/20186892/195121075-67228c4a-430c-4982-86ac-2fef7e276b12.png)
-- s křížkem se patrně nepočítá při výpočtu odřádkování, takže může nastat takováto situace:
![image](https://user-images.githubusercontent.com/20186892/195121389-c37ff958-50e3-4aae-9c67-db2a73819543.png)

Tabulka s přehledem polí byla též odpovídajícím způsobem aktualizována: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0
