### ISSUE TITLE
Upozornit uzivatele kdyz se nepovede priradit katastr na servru a neumoznit mu to odeslani na krok 2.

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#35]

**Comment by motyc** [comment]
Nejde kontrolovat podle obsahu pole "Hlavní katastr"? Nyní vrátí error 500

**Comment by motyc** [comment]
Problém je, že po kliknutí mimo ČR sice vyskočí hláška, ale formulář lze přesto odeslat (v hlavním katastru je "none") a pak vyskočí errror 500

**Comment by pesikj** [comment]
Které URL se to týká?

**Comment by motyc** [comment]
http://192.168.254.30:8080/oznameni/

**Comment by pesikj** [comment]
Opraveno. Pro test je potřeba smazat cache prohlížeče (Ctrl+F5), aby se načetla nová verze souboru map.js.

![image](https://user-images.githubusercontent.com/15179154/132420050-ab6f85a1-5e6f-4216-9be1-1d279216e99a.png)
