### ISSUE TITLE
Responsivní chování tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#350]
- [ ] Na mobilu tabulkové zobrazení nebude moc fungovat - řešit jako v původním AMČR-PAS?
- [ ] Každý sloupec má mít stanovenou vhodnou minimální šířku a maximální šířku (viz **zadání tabulek**). Reálná šířka při načtení tabulky má být dána skutečným prostorem na obrazovce a jedině v případě nedostatku prostoru i při minimálním nastavení se zobrazí rolovátko/mobilní zobrazení již od začátku.
- [ ] Při odebírání sloupců se automaticky zvětšuje jen druhý sloupec v pořadí, uvolněné místo by se mělo dynamicky dělit mezi zbývající sloupce (případně jiným vhodnějším způsobem).

**Comment by pesikj** [comment]
@motyc

> řešit jako v původním AMČR-PAS?

Tady není jasné, co je tím myšleno, prosím o popis, jak to je v AMČR PAS řešeno.

**Comment by motyc** [comment]
@pesikj Toto issue máme zařazeno do "ARU - need design", s doplněním zadání počítáme.

**Comment by motyc** [comment]
Aktuální chování tabulek je v základu vyhovující a další ladění provedeme případně až po implementaci #344
