### ISSUE TITLE
Tabulky - ladění funkcí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#351]
- [x] Podporovat řazení podle více sloupců (částečně snad připraveno: https://github.com/ARUP-CAS/aiscr-webamcr/issues/54#issuecomment-851450138).
- [x] Musí být možné přejít na konkrétní list tabulky.
- [x] Musí být možné zvolit počet záznamů na listu (výchozí hodnota 100).
- #499 - vyčleněno zvlášť
- [x] Popisky sloupců centrovat vertikálně na střed buňky.
- [x] Názvy sloupců uvádět jako singuláry.

**Comment by motyc** [comment]
> David Novák 
> 3. ledna 2022 17:27
> - ad 2 - ano, jde o to, že teď nemohu přejít na konkrétní list (musel bych se tam doklikat, což může být někdy neúnosné)
> - ad 3 - ano (umístění zvolte podle citu, ale nejlepší by to bylo spolu s tím přechodem na konkrétní stránku zachovat ve stejném řádku, jako je listování - na tom řádku je místa dost a lze to nějak vhodně rozdělit zarovnáním) a ano, bylo by to dobré
> - ad 5 - ano (prostě to, co je v záhlaví); ale budeme to ještě celkově revidovat (tady jde jen o to upravit nastavení, pokud se to někde dělá automaticky)
> 
> Jan Ihnat 
> 28. prosince 2021 12:37
> - ad 2 - to je uz teraz mozne, alebo si prajete niekde pod cislovanim stranek bunku s moznosti prejit na stranku…?
> - ad 3 - chcete teda pod cislovani stranek, pripadne nekde jinde(kde prosim?) moznost zadat pocet na stranku? Chceme to pak ukladat pro usera jako jeho nastaveni?
> - ad 5 - popisky myslite nazvy?

**Comment by jnihnat** [comment]
ad4 - to odstraneni tooltipu podle toho ci bunka je dlouha nebo ne nedoporucuji. da se to udelat nejakym zlozitym scriptem pri nacitani stranky, ale muze to pak spomalovat samotne nacitani. Kdyz uz tak bych to radeji odstranoval pro nektere sloupce kde vime, ze jsou kratsi (napriklad ident, stav).

**Comment by motyc** [comment]
@jnihnat Ok, rozumím. Navržené druhé řešení mi nepřijde špatné. Dořešíme to ještě při revizi výchozích/minimálních šířek sloupců v tabulkách (#350).

**Comment by jnihnat** [comment]
@motyc muzeme tedda prosim bod 4 vyclenit jako samostatne issue? Pokud ano, tak tohle issue je pak k testu.

**Comment by motyc** [comment]
@jnihnat Ano, založeno nové issue #499

**Comment by motyc** [comment]
@jnihnat Jedna drobnost - do pole s nastavením počtu záznamů na stránku prosím vypsat aktuální nastavený počet. Nikde se to totiž uživatel nedozví.
