### ISSUE TITLE
Tabulky historie převést na standardní formát

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#353]
Použít stejné základní chování jako na https://wamcr-test.aiscr.cz/projekt/list

**Comment by pesikj** [comment]
Odkaz https://wamcr-test.aiscr.cz/projekt/list mi nefunguje ani přes VPN, je server aktivní?

**Comment by jnihnat** [comment]
tabulku historie som predelal podle ostatnich tabulek. barva je podle toho ceho se historie tyka. Nepridaval som tam samozrejme filter, ten je tam podle mne zbytecny. 
jeste navic sem udelal to co bylo v puvodnim issue u nas v JIRA:
http://192.168.254.30:8080/projekt/list
- Jak v zobrazené, tak ve stažené tabulce (CSV, JSON, XLSX) jsou v některých sloupcích jako null hodnoty použity em pomlčky a v některých spojovníky (- vs —), to stěžuje následné parsování atd. Pro null hodnoty nechat políčko zcela prázdné.

- Tabulka vybraných záznamů - sloupce:
    - přidat Plánované zahájení
    - Typy projektů a Památky defaultně skrýt

**Comment by motyc** [comment]
Funkčně ok, ale tlačítko zpět je skryté za patičkou.

**Comment by jnihnat** [comment]
prosim o retest nebo specifikaci kde se chyba vyskytuje. U projektu je to spravne, Tlacitko se zobrazuje a historie je s rolovatkem.
![obrazek](https://user-images.githubusercontent.com/57906106/172138682-9fb473a9-7604-4a98-90bf-15e877640c5f.png)

**Comment by motyc** [comment]
@jnihnat Ve stávající verzi je to ok.
