### ISSUE TITLE
Vyřešit vhodným způsobem překlady

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#354]
Každý textový řetězec v aplikaci by měl mít svůj unikátní klíč, na základě kterého půjde editovat jeho znění v CS a EN. Je třeba najít nejvhodnější cestu, jak dosáhnout udržitelného řešení.

**Comment by jnihnat** [comment]
Pridavam navrh reseni. Pridani rozsireni django-rosetta. vznikne tak polozka na konci admin seznamu:
![obrazek](https://user-images.githubusercontent.com/57906106/156194177-6288bd82-a4bd-4bfa-82d3-964d2fdf88a5.png)
po rozkliknuti to zobrazi tabulky s dostupnymi jazyky a udaji k nim:
![obrazek](https://user-images.githubusercontent.com/57906106/156194360-91e9d25b-e78a-4ac0-8130-5f6d77d18d11.png)
po rozkliknuti jazyku je mozne zahajit preklad. po ulozeni souboru se vygeneruje automaticky soubor pro Django a je uz jen potrebne restartovat server. (Na teste to nebylo potreba, mozna nebude treba ani na produkci, potreba vyskouset, tohle je ale uz spravani Djanga obecne ze to je/neni potreba)
![obrazek](https://user-images.githubusercontent.com/57906106/156194586-b9e224b3-1fe6-4338-bb65-30bd4a4a1ac2.png)

**Comment by jnihnat** [comment]
@motyc  prosim kouknete na navrh reseni hore. 
Potreboval bych potom jeste doplnujici informaci jak si predstavujete pripadny presun prekladu mezi prostredimi. napr z testu do produkce. Postaci ak se to udela jednou, pri pocatecnem spusteni a pak se preklad bude delat jen na produkcni verzi, nebo je potreba na to sofistikovanejsi spusob. Pripadne ci sofistikovany spusob je i kopirovani pomoci ftp. 
Vdaka za odpovedi predem.

**Comment by jnihnat** [comment]
Doplneny wiki navod pro:
- cast administrace: https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Administrace#rosetta-translations
- cast nasazeni aplikace: https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Nasazeni-aplikace

Po nasazeni na test prosim otestujte, ci po ulozeni prekladu se zmeny zobrazi na formularich hned. Pokud ne, budeme asi muset zakomponovat restart servru.

**Comment by jnihnat** [comment]
@pesikj prosim o spusteni na serveru:
pri prvnim nasazeni potrebne spustit makemessages pro vytvoreni souboru prekladu. Ty se ukladaji na volume, takze neni potreba dalsihou spousteni pokud se volume nesmaze. docker exec <container_name> python3 ./manage.py makemessages -l cs (to same pro en)

**Comment by pesikj** [comment]
@jnihnat Dal jsem to do entrypoint.sh a otestuji na .24.

**Comment by motyc** [comment]
### Výsledky testu
Data již jsou viditelná a administrace se chová dobře.

- [ ] Změny se nicméně neprojeví (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/354#issuecomment-1059134566). Testováno na `core.table.pagination.jumpToPage.label` a `core.table.pagination.jumpToPage.button`
- [ ] Část klíčů nemá standardní schéma, ale jako klíč se užívá rovnou překlad. Text je třeba posunout do pole s překladem a klíč nastavit standardně (nehoří, ale je třeba to udělat).

**Comment by pesikj** [comment]
@jnihnat Honzo, k tomu, aby se překlady projevily, stačí spustit compilemessages, nebo je potřeba ještě něco dalšího?

**Comment by jnihnat** [comment]
mnelo by byt potreba jen restartovat server. da se to nastavit i na auto-restart, ale osobne bych to nenastavoval pro produkci.
`This means your project’s labels will be translated right away, unfortunately you’ll still have to restart the web server for the changes to take effect. (NEW: if your web server supports it, you can force auto-reloading of the translated catalog whenever a change was saved. See the note regarding the ROSETTA_WSGI_AUTO_RELOAD variable in conf/settings.py.`

**Comment by jnihnat** [comment]
k bodu 2
- tam sme sa bavili, ze to neni jednoduche, v aplikaci je pres 700 klicu, co neznamena ze to je 700 miest kde dany kluc je..., Neexistuje ziadny jednoduchy sposob, ako tohle upravit, je potrebne prejst kluc po kluci a upravit to v kode. Zaroven potom, ale bude treba spravit preklady. Priklad:
- v aplikacii je teraz "Odeslat" - to je i klic a zobrazuje se to i aplikaci, lebo to nema preklad.
- nahradime to na "common.button.odeslat" to se zacne zobrazovat v prekladech i v aplikaci
- nekdo pak musi zadat preklad do aplikace.
Treba se teda dohodnout, jak to udelat a kdo co udela. zmena v aplikaci je jasna, ale pak zadani noveho prekladu?

**Comment by pesikj** [comment]
@motyc 
> * [ ]  Změny se nicméně neprojeví (viz [Vyřešit vhodným způsobem překlady #354 (comment)](https://github.com/ARUP-CAS/aiscr-webamcr/issues/354#issuecomment-1059134566)). Testováno na `core.table.pagination.jumpToPage.label` a `core.table.pagination.jumpToPage.button`

Podle toho, co píše @jnihnat, nebudou změny k dispozici hned, ale je třeba restartovat server. Počítám, že to nebude v běžném provozu problém, protože tvorba překladu bude jednorázová záležitost a bude dokončena před uvedením do produkce. Nyní jsem provedl deploy nové verze, aby byl restartován server, prosím o kontrolu, zda se překlady v aplikaci projevily.

**Comment by motyc** [comment]
@jnihnat @pesikj 
ad auto-restart - pro test to ale prosím takto alespoň dočasně udělejme, protože jinak by to byl velký problém otestovat nějak souvisleji; navíc postupně budeme muset napsat všechny texty a u toho je třeba to rovnou zkoušet
ad bod 2 - ok, tento bod vydělme jako samostatné issue (#558) a domluvíme se, jak to udělat; rutinní práci se můžeme pokusit udělat my, abyste se tím nezdržovali, jen se musíme dohodnout na pokynech
ad změny v současné verzi - bohužel se neprojevily (kontroluji na http://192.168.254.30:8080/projekt/vyber)

**Comment by jnihnat** [comment]
Zatim som opravil bod 3. Upravim podle toho i navod jak nasazovat zmeny spojene s textami. 
Pri nasazovani bude potreba provest vice ukolu. Mozna to budeme moci dat i do start scriptu:
@pesikj 
- momentalne to funguje tak, ze Django si .po soubor vytvori a musi vytvorit v adresari u sebe. Takze ho neumi vytvorit do docker volume, odkud ho uz ale taha aplikace. Navrh ako to spravit, a neviem ci to teda nedat aj do start scriptu:
- spravit MOVE locale files z LOCALE_VOLUME do containeru aplikace (aby se uz prelozene texty nepremazaly)
- spustit makemessages
- spravit MOVE naspatek z containeru do LOCALE_VOLUME

**Comment by jnihnat** [comment]
autoreload v #567

**Comment by pesikj** [comment]
Na serveru už to nyní funguje, stačí provést úpravu v admin rozhraní a změna se projeví hned.

**Comment by motyc** [comment]
@pesikj @jnihnat Zde se jen chci zeptat - je nějak dořešené to nasazování? Co se vlastně stane, pokud se seznam textů bude v různých verzích aplikace lišit (něco zmizí, něco přibude, něco se přejmenuje)?

**Comment by pesikj** [comment]
@motyc Toto zatím vyřešené není.

**Comment by motyc** [comment]
@pesikj Mám k tomu tedy vyrobit samostatné issue, nebo toto posuneme zpět, ať to nezapadne?

**Comment by pesikj** [comment]
Preferuji založení samostatného issue.

**Comment by motyc** [comment]
Založeno jako #684, toto zavírám.
