### ISSUE TITLE
Oznámení pro uživatele jsou nekonzistentní

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#357]
Oznámení pro uživatele jsou nekonzistentní co do způsobu řešení - http://192.168.254.30:8080/pas/odeslat/ to má jinak než zbytek (možná vlastně lépe). Sjednotit.

**Comment by pesikj** [comment]
Přidán automatický test na toto issue.

**Comment by motyc** [comment]
Budeme testovat průběžně.
