### ISSUE TITLE
Ladění formuláře oznámení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#360]
- [x] Loga - doplnit prokliky na stránky ústavů.
- [x] Emailové adresy - přidat odkazy jako ‘mailto’ (v informacích po rozbalení).

**Comment by jnihnat** [comment]
@motyc - Dobry den, viete mi dat url adresy pro prokliky prosim?
Dam ich stejne do settings, ale at ich uz tedka mame spravne a nemusime menit o pul roku. Dekuji

**Comment by motyc** [comment]
@jnihnat
Zde url:
Praha - https://www.arup.cas.cz/
Brno - https://www.arub.cz/

Děkuji.

**Comment by motyc** [comment]
Prokliky mířit na do nového tabu
