### ISSUE TITLE
Automatické přejmenování souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#362]
Doplnit automatické přejmenování souborů při nahrání
- [x] Dokumenty
- podle ident_cely nadřazeného dokumentu bez pomlček
- první soubor bez suffixu, každý další se suffixem A-Z (Z je maximum, CH nepoužívat)
- příklad: 1. soubor: `[hash]_CTX202112345.pdf`; 2. soubor: `[hash]_CTX202112345A.pdf`
- [x] Samostatné nálezy
- podle ident_cely nadřazeného nálezu bez pomlček
- první soubor bez suffixu, každý další se suffixem F01-99 (99 je maximum)
- příklad: 1. soubor: `[hash]_M202102434N00023F01.jpg`; 2. soubor: `[hash]_M202102434N00023F02.jpg`
- nyní chybně (zůstávají pomlčky, není na dvě číslice po F) při migraci přejmenovat
- [x] Projektová dokumentace
- nahradit diakritiku a další speciální znaky (pouze: a-z, A-Z, 0-9 a podtržítko - nepřevoditelné znaky nahradit podtržítkem)
- příklad `nějaký složitý Název-SOUBORU1.docx` -> `[hash]_nejaky_slozity_Nazev_SOUBORU1.docx`

**Comment by jnihnat** [comment]
Ako se prosim spravat pri Maximu? vratit podobnou chybu jako u maxima pri identu?
co kdyz budu mit nahrane 4 soubory s 01, 02, 03, 04 a zmazu 02. dalsi nahrat jako 02 nebo pokracovat na 05 a 02 nechat vynechanou?

**Comment by motyc** [comment]
@jnihnat
Ad maximum - Teď si nepamatuji přesné řešení u identu, ale systém by v tomto případě měl zahlásit chybu, resp. neumožnit další soubor nahrát.
Ad vyplňování děr - díry nezaplňovat, vždy přidělit první volné na nejvyšší hodnotou (tj. 05). Pokud bych tedy chtěl zaplnit díru, musím soubor nahradit (funkce #260), nebo odmazat soubory s vyšším pořadím.

**Comment by jnihnat** [comment]
@motyc aby sme este predisli chybam ktery nazev se ma prejmenovat:
- nazev
- nazev_zkraceny
- nazev_puvodni
- nazev souboru na disku
Dekuji

**Comment by jnihnat** [comment]
u samostatnych nalezu bych bod pro migraci resil samostatne prosim.

**Comment by jnihnat** [comment]
jeste bude potrebne vyresit duplicity, teraz se vyhodnocovali podle nazve. Pokud chceme kontrolovat duplicity i obsahove, navrhl bych pridat do DB souboru sloupec s checksum, ktery bude teda jedinecny.
@motyc a @pesikj

**Comment by motyc** [comment]
@jnihnat Ale on tam přeci ten checksum je - je součástí názvu souboru ve filesystému ("nazev").

Nicméně - duplicity kontrolovat chceme, nikoli ale jako constraint, ale pouze jako upozornění pro uživatele, že duplicita existuje (a vypsat u čeho). Mělo by být možné nahrát dva totožné soubory (může pro to být i relevantní důvod, zejména v případě projektové dokumentace). Hodně se to řešilo v předchozí fázi vývoje, ale vlastně nevím, k čemu to nakonec dospělo.

**Comment by jnihnat** [comment]
@motyc checksum je soucasti nazvu, ale po novu jen u dokumentu a SN. u projektu je uz nazev bez hashe. Proto je potreba doresit tu kontrolu duplicity po novu.

**Comment by motyc** [comment]
@jnihnat Mea culpa! To je jen chyba v zadání - hash má zůstat, jen je prostě zapomenutý. Omlouvám se za chybu. Upravím v prvním příspěvku.

**Comment by jnihnat** [comment]
opravene a teda kontrola duplicity stale podle hashe v nazvu. Neni treba nijak upravovat.

**Comment by jnihnat** [comment]
opraveno v #486 
@motyc a @pesikj je tam i oprava mazani pdf. to nejspis tedka na test serveru nefunguje.

**Comment by motyc** [comment]
### Výsledek testu
https://wamcr-test.aiscr.cz/dokument/detail/X-C-TX-202200005
- [ ] - první soubor nahrán ok, druhý již vůbec nejde nahrát (je jedno, jaké PDF vkládám). V chrom dostanu podivnou hlášku, i když je soubor zcela unikátní: [test1aaa.pdf](https://github.com/ARUP-CAS/aiscr-webamcr/files/8902118/test1aaa.pdf)
![image](https://user-images.githubusercontent.com/20186892/173640045-b706d29f-57eb-4d21-9430-0f523f94ccc9.png)
