### ISSUE TITLE
U souborů se nedoplňuje počet stran

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#363]
- [x] PDF, TIFF - skutečný počet stran
- [x] TXT, CSV, JPEG, PNG - vždy 1

Jiné formáty nepodporujeme (viz #320).

**Comment by pesikj** [comment]
@motyc Kdy má být počet stran doplněn?

**Comment by motyc** [comment]
Pole soubor.rozsah

**Comment by motyc** [comment]
Nefunguje. Nahráno PDF s dvěma stranami, systém hlásí jednu: https://wamcr-test.aiscr.cz/historie/soubor/339215

**Comment by pesikj** [comment]
@motyc Prosím o poskytnutí PDF, které bylo testováno.

**Comment by motyc** [comment]
Zde: [Pořadač1.pdf](https://github.com/ARUP-CAS/aiscr-webamcr/files/8831917/Poradac1.pdf)

**Comment by pesikj** [comment]
@motyc U mě to funguje OK na stejném souboru. Upravil jsem pouze kontrolu přípony, aby ignorovala velikost písmen (ale to tady problém zřejmě není). Zkontroluji to ještě na serveru.

![image](https://user-images.githubusercontent.com/15179154/174107124-90e96d9b-3bdc-449b-8118-0261c19179d0.png)

**Comment by pesikj** [comment]
![image](https://user-images.githubusercontent.com/15179154/174118097-91e68e93-6f05-4644-96e7-4e6ea85e0f32.png)

Na serveru je to též OK.
