### ISSUE TITLE
Doplnění historie souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#364]
Zaznamenat je třeba pouze nahrání daného souboru (mohou se měnit jeho verze, viz #260):
- historie.datum_zmeny - datum a čas
- historie.typ_zmeny - teoreticky může být prázdné, ale nevím, jak se kódy v daném poli používají; zde je jediná možnost, tj. nahrání dané verze souboru
- historie.uzivatel - uživatel, který soubor nahrál
- historie.poznamka - název souboru při nahrání
- historie.vazba - vazba do tabulky historie_vazby

**Comment by pesikj** [comment]
@motyc Jak má být historie přístupná? V administrátorském rozhraní, jako je to u uživatele, nebo jinak?

**Comment by motyc** [comment]
@pesikj Vzhledem k jednoduchosti záznamů by to možná šlo řešit zobrazením v rámci #265, nicméně variantou je i zobrazení jako samostatné tabulky stejně, jako je to např. u projektů (viz např. https://wamcr-test.aiscr.cz/historie/projekt/C-200810941). Tabulka je všude totožná, tak by to v podstatě mělo být jen o využití téhož s jiným parametrem... (upozorňuji též na související issue #353). Proklik do tabulky by byl z tabulky se seznamem souborů (přes nějakou ikonu).

**Comment by pesikj** [comment]
Toto musí být vyvinuto až po #260.

**Comment by pesikj** [comment]
@motyc Ze zadání mi není jasné, jestli se nějaká historie souboru už zaznamenává, nebo ne. Možná jste to probírali s Honzou, ale řešil jsem obecné zaznamenávání historie a existuje na to modul přímo pro Django, který už používáme na uživatele. Jde tedy o úpravu nějakého stávajícího mechanismu, nebo vytvoření nového?

**Comment by pesikj** [comment]
@motyc Ok, dobře.

**Comment by pesikj** [comment]
@motyc Už asi rozumím rozdílu, je tedy potřeba přidat nový sloupec a provázat soubor a historie_vazby.

**Comment by motyc** [comment]
@pesikj Ano, je to tak. Soubor_vazby propojuje soubor s jejich parenty. Historie_vazby propojuje jakékoli záznamy s tabulkou historie.

**Comment by motyc** [comment]
Toto jsem také otestoval (asi omylem zapomenutý label DONE). Je to ok, ale otevírat by se to mělo ve stejném okně, nikoli v novém (jinde to tak také děláme, jde o interní odkaz).

**Comment by pesikj** [comment]
Opraveno.

**Comment by motyc** [comment]
Test na: https://wamcr-test.aiscr.cz/historie/soubor/329159
- [ ] úplně chybí tlačítko "Zpět"
- [ ] popisek posledního pole v záhlaví ubíhá mimo obrazovku (předpokládám ale, že jde o pole soubor.vytvoreno, které bude patrně v souvislosti s #474 odstraněno)
