### ISSUE TITLE
Pro výškové body chybí migrace geometrie

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#373]
Pro výškové body chybí migrace geometrie.

Pole `vyskovy_bod.northing` a `vyskovy_bod.easting` měla být zrušena a migrována do pole `vyskovy_bod.geom`. Nyní v migrovaných datech původní hodnoty úplně chybí a u nových VB se vyplňuje obojí, ale ve špatném souřadnicovém systému (u výškových bodů pracujeme nativně se souřadným systémem S-JTSK). Vzhledem k tomu, že při vytváření VB dochází k odvození výchozích souřadnic VB z PIAN (tj. převodu WGS84 -> S-JTSK), není třeba řešit ukládání v obou formátech (tento směr převodu je přesný). Data by se však měla ukládat v S-JTSK. Vzhledem k nalezeným chybám myslím, že opravy bude vyžadovat i formulář v aplikaci.

**Comment by pesikj** [comment]
Migrace nebyla implementována, je potřeba ji dodělat.

**Comment by pesikj** [comment]
@motyc Přidal jsem migraci souřadnic z poli `northing` a `easting` do `geom` plus přímé ukládání z formuláře do pole `geom`. Pokud jde o souřadnicové systémy, tak nevím, jestli je to tak správně. Prosím tedy o vysvětlení - hodnoty X a Y, které uživatel zadá do formuláře, je před uložením do pole `geom` nějak konvertovat?

**Comment by motyc** [comment]
@pesikj Popravdě toto je dotaz spíše na @pbartosova nebo @jiri-bartos-huld. Jak to má fungovat, je popsáno v prvním postu, ale praktickou implementaci ma úrovni PostGIS neumím správně definovat.

Mimochodem nevím, jak se nyní přesně aplikace chová, ale popíšu zde ještě raději správné chování toho zápisu souřadnic. Vždy vycházíme z toho, že existuje nějaký nadřazený PIAN, ke kterému je VB vztažen (VB -> ADB -> DJ -> PIAN):
- pokud je PIAN bod, jsou automaticky předvyplněny souřadnice bodu v S-JTSK a nejdou změnit
- pokud je PIAN linie, jsou automaticky předvyplněny souřadnice středu linie v S-JTSK a jdou změnit
- pokud je PIAN polygon, jsou automaticky předvyplněny souřadnice centroidu v S-JTSK a jdou změnit

**Comment by pesikj** [comment]
@pbartosova @jiri-bartos-huld Prosím tedy o radu (nebo si můžete issue převzít, protože vůbec netuším, co s tím.

**Comment by jiri-bartos-huld** [comment]
@motyc  Dobry den, prosim o dosouhlaseni postupu opravy  (at je vse na jednom miste): oprava se tyka tabulky public.vyskovy_bod

1./ Aplikace bude opravena, tak aby necetla+neukladala pole nort+east+niveleta ale pouze pole GEOM
2./Migrace DB: souradnice northing+easting+niveleta budou migrovany do jednotneho pole GEOM jako S-JTSK +Bpv 
a. pokud existuje zaznam GEOM vcetne vysky tak se migrace bude ignorovat (north+east+niveleta se neprenesou do pole GEOM)
b. pokud exituje zaznam GEOM bez vysky, tak se provede doplneni vysky do pole GEOM (pole north+easting se budou ignorovat)
c. pokud je pole GEOM prazdne provede se plna migrace vsech 3 udaju
3./Po migraci DB tabulky pole northing+easting+niveleta budou nastevena na null, aby se zkontrolovalo, ze aplikace jedinnym zdojem je pole GEOM





![image](https://user-images.githubusercontent.com/77389730/166569236-2d17fca0-a314-460c-b4da-63497b0d7e8d.png)

**Comment by motyc** [comment]
@jiri-bartos-huld koriguji:
1) Původně jsme chtěli do geom uložit jen polohopis, ale pokud tam lze dát i výškopis a nenarazíme na nějaký zásadní problém v datech, lze to tak udělat. Pole je tak jako tak povinné k vyplnění.
2a) + 2b) by nikdy nemělo nastat; pole geom se v původní produkční databázi vůbec nevyskytuje; pokud nastane, je něco chybně. Jediné správné řešení (a možnost) by mělo být 2c)
3) pole by měla být při migraci zcela odstraněna

Jen pro ujištění - pokud mluvíme o migraci, myslím tím vždy úkony řešené v rámci, kam by měly být dané kroky zahrnuty: https://github.com/ARUP-CAS/aiscr-webamcr/tree/dev/migrace

**Comment by jiri-bartos-huld** [comment]
Byla provedena migrace na 24
UPDATE public.vyskovy_bod
SET    geom=ST_GeomFromText(CONCAT('POINT(',abs(northing)::text,' ',abs(easting)::text,' ',niveleta::text,')')) 
WHERE geom IS NOT null

**Comment by pesikj** [comment]
@jiri-bartos-huld Ahoj Jirko, jaký je stav tohoto issue?

**Comment by jiri-bartos-huld** [comment]
Nasazeno na 24 i 30.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] dotčená pole `vyskovy_bod.northing`, `vyskovy_bod.easting` a `vyskovy_bod.niveleta` jsou stále v DB (nebyla odstraněna)
- [ ] data z původních polí nebyla migrována

Další problémy spojené s ukládáním změn (#287) a se samovolným odpojením PIAN od DJ (#461) blokují ostatní testy.

**Comment by pesikj** [comment]
@jiri-bartos-huld Jirko, jaký je stav tohoto issue?

**Comment by jiri-bartos-huld** [comment]
@motyc @pesikj 
1./ nalezl jsem chyby, v DB jsou data ve WGS-84,podle me se jedna o testovaci data
nalezene chyby:192.168.254.24

  id  |   adb   |       ident_cely        |                     st_astext                      
------+---------+-------------------------+----------------------------------------------------
 8154 | 1276705 | ADB-PRAH43-000001-V0004 | POINT Z (14.530106661443048 50.06012623313119 100)
 8155 | 1276705 | ADB-PRAH43-000001-V0005 | POINT Z (14.530106661443048 50.06012623313119 100)
 8156 | 1276705 | ADB-PRAH43-000001-V0006 | POINT Z (14.530106661443048 50.06012623313119 100)

nalezene chyby:192.168.254.30
  id  |   adb   |       ident_cely        |                  st_astext                   
------+---------+-------------------------+----------------------------------------------
 8167 | 1276764 | ADB-NAMO04-000001-V0001 | POINT Z (4 3 4)
 8168 | 1276815 | ADB-KRAS07-000001-V0001 | POINT Z (31 443 3)
 8169 |  809740 | ADB-PRAH71-006664-V0001 | POINT Z (-5 99 5)
 8153 | 1276738 | ADB-PRAH61-006770-V0001 | POINT(14.428876385081823 50.08818366584923)
 8154 | 1276738 | ADB-PRAH61-006770-V0002 | POINT(14.428876385081823 50.08818366584923)
 8155 | 1276738 | ADB-PRAH61-006770-V0003 | POINT(14.428876385081823 50.08818366584923)
 8156 | 1276742 | ADB-PRAH61-006771-V0001 | POINT(14.428739637114633 50.088117926450415)
 8157 |  734555 | ADB-HERM87-000001-V0001 | POINT(15.484689701662758 49.88684952652089)
 8158 | 1276750 | ADB-KLAD58-000001-V0001 | POINT(14.118441074474891 50.11771264351254)
 8159 |  980148 | ADB-CHEB50-000001-V0001 | POINT(12.366480568899497 50.081014411671866)
 8161 | 1274469 | ADB-HLUB74-000001-V0001 | POINT(14.25973893861196 49.11489311416916)

2./ Daleko vetsi problem vidim, ze pro 192.168.254.30 neni u zadnych dat vyplnena poloha? Odkud se ma brat poloha techto bodu?
![obrazek](https://user-images.githubusercontent.com/77389730/180262028-035fe6dc-d430-4cd8-b4a9-5f5d1ac8bbc2.png)

**Comment by motyc** [comment]
@jiri-bartos-huld V první řadě nejde o to opravit data na serverech (ta jsou testovací), ale připravit skript pro https://github.com/ARUP-CAS/aiscr-webamcr/tree/dev/migrace - to se stalo, nebo nikoli?

192.168.254.24 není třeba vůbec řešit, resp. je to pouze na potřebách Huld - jde o dev server, kam nechodíme
192.168.254.30 zde bych řešil pouze chyby na v datech, která vznikla migrací a nikoli prací s aplikací. Prosím o úplný seznam problematických VB, na které se přijde při migraci produkční databáze. U těch zjistím, kde je problém a pokusíme se jej vyřešit.

**Comment by jiri-bartos-huld** [comment]
@motyc 
192.168.254.24 je server, kde si to muzeme vyzkouset-proto ho zminuji
192.168.254.30 chyba chybejici polohy se tyka vsech bodu co maji zadanou niveletu a nevznikly praci v aplikaci
migracni skript pripravim do github

**Comment by jiri-bartos-huld** [comment]
poslano na MR

**Comment by motyc** [comment]
> 192.168.254.30 chyba chybejici polohy se tyka vsech bodu co maji zadanou niveletu a nevznikly praci v aplikaci

@jiri-bartos-huld Díval jsem se do zdrojové DB a žádné takové VB neexistují. Všechny mají všechny tři údaje vždy vyplněny (viz 192.168.254.3/prod_zaloha_backup). Problém patrně vznikl při práci s daty na serveru 192.168.254.30. Bude třeba otestovat po nové migraci.

**Comment by pbartosova** [comment]
Přidávám informaci z issue #474, pole northing, easting a niveleta jsou odstraněny.

**Comment by motyc** [comment]
@pbartosova @jiri-bartos-huld Mám k tomu ještě dav dotazy (vztahují se k https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/35_vyskovy_bod_geom.sql):
1. Původní data jsou v S-JTSK (5514), je to nějak zohledněno při převodu na geom, nebo je to jedno? Mělo by se pracovat celkově jen s 5514 (WGS vůbec pro VB nepotřebujeme - v mapě se nikdy nezobrazují).
2. Vzhledem k tomu, že souř. systém nelze z dat snadno poznat, souhlasili byste s přejmenováním pole na geom_sjtsk, jako to máme jinde, ať je to jasné?
