### ISSUE TITLE
Upravit existující souřadnice na odpovídající počet řádů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#377]
- [x] Upravit existující souřadnice na odpovídající počet řádů (viz #307)
- [x] Aplikovat kontrolu geometrií (zda nedošlo nově k chybám; viz #308 a #371)

**Comment by motyc** [comment]
@jiri-bartos-huld Toto asi neumím testovat jinak, než kontrolou kódu. Chybí mi ale odkaz na konkrétní committy.

Navíc by mne trošku překvapilo, kdyby druhý bod skončil bez chyb - proběhla tato kontrola a s jakým výsledkem? Jak bude celé řešení zaintegrováno do procesu migrace?

**Comment by motyc** [comment]
### Výsledek testu
Mám dojem, že committ https://github.com/ARUP-CAS/aiscr-webamcr/commit/d6e9eb451e30d2919421990a8a783f053b0b6c26 řeší ve skutečnosti issue #307. Zde však mělo dojít k úpravě existujících dat (změna počtu řádů souřadnic v datech) + aplikovat kontrolu geometrií při migraci, abychom mohli odstranit existující chyby. Ani jedno se myslím nestalo.

**Comment by jiri-bartos-huld** [comment]
Migrace provedena +wiki
https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Presnost-souradnicovych-systemu

**Comment by motyc** [comment]
@jiri-bartos-huld Nejde o to migraci jen provést, ale zahrnout ji do migrací zde: https://github.com/ARUP-CAS/aiscr-webamcr/tree/dev/migrace - to se stalo, nebo ne? (v commitech nevidím)

Zároveň se mi nějak nezdá, že by došlo ke kontrole geometrií z produkčního serveru bez chyb. Opravdu to tak bylo? Na jakých datech byla kontrola geometrií provedena?

**Comment by jiri-bartos-huld** [comment]
@motyc 
Bude pridano do migraci spolu s #373

**Comment by jiri-bartos-huld** [comment]
poslano na MR

**Comment by jiri-bartos-huld** [comment]
@motyc @ScottVanWagenen @pbartosova  
Dobry den, moc nechapu zadani: Je to tak, ze potrebujete seznam PIAN, ktere nespnuji naroky na validitu(dodatecna pravidla AMCR) geometrie pri rucnim vkladani? To je ale vetsi mnozina nez v tomto issue resena pocet des mist souradnic.

Ukazka statistiky vsech chyb "nevaldity" v ramci PIANu: [wiki](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Validace-Geometrie#validace-pian)

- Jsou tam krizeni na linii: geometry is not simple
- Multiparty: Toto neni chyba pro PIANy z importu ale pro rucne zadane ano (v DB  nedokazeme poznat ktery je ktery)
- prekrroceni min delky mezi body

![obrazek](https://user-images.githubusercontent.com/77389730/183939292-0cc3a9ee-b558-49ab-985d-f0698b7aca9e.png)

Pokud potrebujete jen revidovat, ze pro vsechny ulozene PIAN plati pravidla pro presnost des. mist tak to je popsano vzdy na zacatku migrace (mohu dat i jako sam. kapitolu) [wiki](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Presnost-souradnicovych-systemu#samostatny-nalez)

**Comment by motyc** [comment]
@jiri-bartos-huld Jde o to, že samotným zaokrouhlením může vzniknout kterákoli z chyb, kterou nově testujeme při ukládání do DB (#308). Tento test je třeba zavolat po převodu při migraci a podat výsledek, abychom to případně vyřešili. Je zřejmé, že v DB bude i řada nesouvisejících problémů, které tak jako tak musíme vyřešit. A k tomu bych potřeboval ten seznam PIAN, kterých se to týká a o jaký typ chyby jde...

**Comment by jiri-bartos-huld** [comment]
Podle me pak pri provedeni migrace je potreba jen zavolat: [wiki](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Validace-Geometrie#validace-pian) a ziskam tim seznam chyb.

Tedy pouze toto:


--WGS-84
SELECT id, validateGeom(st_astext(geom)),st_astext(geom) FROM public.pian  
WHERE geom IS NOT NULL AND validateGeom(st_astext(geom))<>'valid'
--S-JTSK
SELECT id, validateGeom(st_astext(geom_sjtsk)),st_astext(geom_sjtsk) FROM public.pian  
WHERE geom_sjtsk IS NOT NULL AND validateGeom(st_astext(geom_sjtsk))<>'valid';

**Comment by motyc** [comment]
@jiri-bartos-huld Děkuji. Zkoušel jsem a funguje to. Ještě se zamyslím, zda to přidat jako automatický krok do migrací, ale issue tímto máme vyřešeno.
