### ISSUE TITLE
Migrace souborů do Fedory

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#38]
Je třeba napsat novou funkci pro migraci do Fedory (obdoba `DocumentGenerator.generate_metadata(*)` (vč. možnosti spustit pro konkrétní id a pro konkrétní počet záznamů), která bude vycházet z tabulky `soubor`. Ta by měla:
- [x] Vyhledat nadřazený záznam (sam. nález, projekt, dokument)
- [x] V rámci kontejneru nadřazeného záznamu vytvořit kontejner pro soubory, pokud ještě neexistuje
- [x] Vybrat soubor z předdefinovaného úložiště na základě jeho názvu (adresa úložiště může být parametrem na vstupu)
- [x] Provést antivirovou kontrolu
- [x] Přenést soubor do Fedory
- [x] Vygenerovat náhledy
- [x] V DB aktualizovat pole `rozsah`, `mimetype`, `path`, `size_mb` a `sha_512` podle skutečných údajů načtených ze souboru
- [x] Aktualizovat metadata nadřazeného záznamu

**Comment by vojtakus** [comment]
ve skriptu 6_migrace_dalsi.sql zjištěn dlouho běžící příkaz: 
update historie h set typ_zmeny = 4
where id in (select his.id as hid from historie his join historie_vazby as hv on hv.id=his.vazba where hv.typ_vazby='archeologicky_zaznam' and his.typ_zmeny=7);

**Comment by vojtakus** [comment]
Cesta k logům (pod uživatelem postgres):
/var/lib/pgsql/aiscr-webamcr/migrace/migrace_all.log
/var/lib/pgsql/aiscr-webamcr/migrace/migrace_all2.log

**Comment by Najiva** [comment]
Migracni skript pro presun souboru je potreba udelat nasledovne.

1. V tabulce soubor, sloupci "vytvoreno" je datum kdy byl soubor vytvoren. Podle toho kdy byl vytvoren, se presune do podslozky /RRRR/MM/DD v rootu media souboru tj. ve /var/lib/docker/volumes/aiscr-amcr-webclient_static_data/_data/media/soubory/. 
2. Pote se do tabulky soubor do sloupce path, kde by melo byt "not specified yet" zapise napr. pro soubor vytvoren 10.01.2021 "soubory/2021/01/10/test.txt"

To se udela pro vsechny soubory a to je vsechno.

**Comment by motyc** [comment]
@Najiva Základní princip potvrzuji, jen by tam ještě mělo být zohledněno to rozdělení typů podle #19, resp. varianty AGPO, OSPD, OSD, FDN. To se bude dělat ex-post, nebo již při této migraci?

**Comment by Najiva** [comment]
Delal bych to rovnou tady. Akorat bude pak potreba jeste udelat upravy do kodu webamcr.

V teto souvislosit bych to videl ze je vhodne to rozdelit nasledovne:
1. AGPO + OSPD spojit do jedne slozky. root bude soubory/OSPD a to pro vsechny soubory, ktere maji relaci na tabulku soubor_vazby kde je ve sloupci typ_vazby "projekt"
2. OSD tj. root bude soubory/OSD pro soubory ktere maji ve vazba.typ_vazby "dokument"
3. FDN tj. root bude soubory/FDN pro soubory ktere maji ve vazba.typ_vazby "samostatny_nalez"

**Comment by motyc** [comment]
Ok, s navrženým souhlasím.

**Comment by Najiva** [comment]
@vojtakus Vojto upravil jsem migracni skript tak aby bylo mozne ho spustit najednou tj. pouze migrace_all.sh Taky jem tam opravil 3 chyby a potreboval bych udelat tu migraci fresh.

**Comment by pesikj** [comment]
@motyc Tady prosím o specifikaci, jak bude vypadat struktura souborů v úložišti a jak soubor v úložišti dohledat na základě údajů v tabulce.

**Comment by pesikj** [comment]
@motyc Odhad pracnosti: 12 hodin

**Comment by motyc** [comment]
@pesikj Díky, klidně s tím začněte.

**Comment by vojtakus** [comment]
Pro ukládání souborů je možno použít složku /opt/data-migrace přístupnou uživateli amcr.

**Comment by motyc** [comment]
@vojtakus Potvrzuji, že složku vidím a jde do ní nahrávat data. Děkuju.

@pesikj Prosím o popis toho postupu. Zítra bych případně migraci rád zkusil.

**Comment by pesikj** [comment]
@motyc Dokumentace je v #1851.

**Comment by motyc** [comment]
### Test v0.4.61
V principu to funguje, narazil jsem jen na následující drobné chyby: 

- [ ] `save_files_from_storage` iteruje v rámci rozsahu, ale nekontroluje, zda nějaké id v DB nechybí. Tím pádem to spadne na prvním souboru v rámci dané řady, kde někdy v historii došlo ke smazání souboru. Je třeba doplnit kontrolu, zda soubor s daným id je v DB a pokud ne, posunout iteraci o číslo výše.
- [ ] Ve Fedoře nesedí `ebucore: hasMimeType` (viz https://fedora-test.aiscr.cz/rest/AMCR/record/M-DP-201500023/file/ccd5524c-b52d-4e9b-872e-3916385fcf1b/orig/fcr:metadata).
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f58cd3f2-a10e-43a3-bca4-3ce1d857b53b)

**Comment by motyc** [comment]
### Test v0.4.70
Snad poslední drobnost:
- [ ] soubory v rámci iterace přes rozsah id jsou seřazeny nikoli podle `soubor.id`, ale podle pole `soubor.nazev` (jestli jsem to dobře vypozoroval); to je nešikovné kvůli případným chybám, kdy sekvence někde zastaví a bude náročné správně nastavit pokračování od zvoleného záznamu - upravit tak, aby iterovalo vzestupně přes id

**Comment by motyc** [comment]
@pesikj @vojtakus Nevím proč, ale najednou systém na .30 nevidí složku "/vol/data-migrace". Nevíte někdo, čím to může být? Nezměnilo se něco?

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/cab676f7-9c3f-4197-9f3e-57b5c4a1b8b8)

**Comment by pesikj** [comment]
Já nevím, ale spustil jsem znovu skript `prod_deploy.sh` a je to zpět.

**Comment by motyc** [comment]
@pesikj Ok, zkusím znovu...

**Comment by motyc** [comment]
V pořádku, zavírám
