### ISSUE TITLE
Vstup do administrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#381]
Přidal volbu is_superadmin do admin. rozhraní.

**Comment by motyc** [comment]
> @pesikj
> Pro přístup do amin rozhraní stačí pole is_staff, viz https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_staff

**Comment by motyc** [comment]
Nyní po přidělení "is_staff" jde vstoupit do administrace, ale nejde v rámci ní nic zobrazit ani upravovat.

**Comment by pesikj** [comment]
Přidal volbu is_superadmin do admin. rozhraní.
