### ISSUE TITLE
Správa novinek a textů na úvodní obrazovce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#383]
Zahrnout správu novinek a textů na úvodní obrazovce do administrace - nelze řešit přes #354?

(navazuje na #119)

"Novinkami" je myšlen statický text, který bude načítaný přes Django translations.

**Comment by jnihnat** [comment]
@motyc - Dotaz k novinkam, mam tu 2 moznosti:
- mit to naozaj cele ako text v translations se vsemi html tagmi a datumami
- dodelat k tomu tabulku s datumom, textcz a texten. Tahat posledne 2 novinky odtial a spravovat to cez admin panel

**Comment by motyc** [comment]
Pokud nic nebrání první variantě, klidně bych se držel této možnosti. Bude to flexibilnější a nemusí se to zanášet do DB. Tak to myslím bylo i naceněné...
