### ISSUE TITLE
Správa uživatelů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#384]
- [x] Uživatele může editovat pouze administrátor (tj. uživatel s přístupem do administrace) s patřičným oprávněním k administraci uživatelů (viz další bod).
- [x] Doplnit správu oprávnění k určitým úkonům:
- správa uživatelů (souvisí s předchozím bodem)
- správa heslářů (zohlednit v #385)
- správa 3D (pouze příprava, dopad bude řešen později)
- správa skupin
- správa překladů

Úkoly související s notifikacemi přesunuty do #736.
Úkol související s identy přesunut do #737.

**Comment by pbartosova** [comment]
Stávající ident_cely je přiřazováno DB, sekvencí user_storage_user_id. Požadované pravidlo je vidět v detailu tabulky user_storage.

**Comment by MaxKosta** [comment]
@motyc Aby uživatel mohl přidávat 
další uživatele, musíte se přihlásit do administrátorského rozhraní a zaškrtnout možnosti podtržené na obrázku.
<img width="1204" alt="Screenshot 2022-09-07 134052" src="https://user-images.githubusercontent.com/74970764/188873096-17d0d0e2-9201-4226-81c8-1ebff40c0b69.png">

**Comment by motyc** [comment]
@MaxKosta Rozumím, podle zadání ale potřebujeme právě oddělit zvlášť oprávnění ke správě uživatelů. Jde o to, že chceme mít možnost tato oprávnění na úrovni adminů definovat přesněji, než "může dělat vše" a "nemůže dělat skoro nic".

**Comment by pesikj** [comment]
@motyc 

> Rozumím, podle zadání ale potřebujeme právě oddělit zvlášť oprávnění ke správě uživatelů. Jde o to, že chceme mít možnost tato oprávnění na úrovni adminů definovat přesněji, než "může dělat vše" a "nemůže dělat skoro nic".

Co tím přesně myslíte? Na základě čeho mají být práva nastavená?

**Comment by pesikj** [comment]
@motyc 
>  Uživatele může editovat pouze administrátor (tj. uživatel s přístupem do administrace) s patřičným oprávněním k administraci uživatelů (viz další bod).

Toto je splněno z principu, uživatel bez přístupu do administrace nemůže editovat ostatní uživatele.

**Comment by motyc** [comment]
@pesikj
Představa o fungování je již v prvním příspěvku, ale zkusím to přehledně rozebrat znovu:

1) Do administrace by měl mít **přístup každý uživatel s rolí administrátor**. Mělo by to tak být automatické a neměla by k tomu být potřeba ještě volba "přístup do admin. rozhraní".

Dále budeme mít takto definovaná **oprávnění**, která půjde přidělit jednotlivým uživatelům (může je nastavit admin s oprávněním podle bodu 2):
2) **správa uživatelů**
3) **správa heslářů**
4) **správa 3D**
5) **příjem oznámení o registraci uživatelů**

Když se teď dívám do administrace, tak mi zároveň dochází, že počet voleb se zde od vzniku zadání rozšířil a zapomněli jsme to reflektovat. Logické by tedy bylo doplnit ještě:
6) **správa skupin**
7) **správa překladů**
(pokud je to velká práce navíc, objednáme to doplňkově - chápu, že to v zadání chybělo)

Na další úkony pak musí mít práva podle 2-5 (resp. 2-7).

Není mi stále úplně jasná funkcionalita volby "globální administrátor" - co konkrétně to dává za pravomoci a potřebujeme tuto volbu vůbec v kontextu výše napsaného?

**Comment by pesikj** [comment]
@motyc Pro překlady to jde takto:
> ROSETTA_LANGUAGE_GROUPS: Set to True to enable language-specific groups, which can be used to give different translators access to different languages. Instead of creating a global translators group, create individual per-language groups, e.g. translators-de, translators-fr, and assign users to these.

**Comment by pesikj** [comment]
@motyc Alternativně takto:
> ROSETTA_ACCESS_CONTROL_FUNCTION: An alternative function (string or a callable) that determines if a given user can access the translation views. This function receives a user as its argument, and returns a boolean specifying whether the passed user is allowed to use Rosetta or not.

**Comment by pesikj** [comment]
@motyc Volba Globální administrátor znamená přidělení všech oprávnění ke všem záznamům, viz.  https://docs.djangoproject.com/en/4.1/ref/contrib/auth/.

> is_superuser
> Boolean. Designates that this user has all permissions without explicitly assigning them.

**Comment by motyc** [comment]
@pesikj To bychom si tedy asi měli nechat oddělené, jako možnost pro opravdu omezený počet adminů, a nastavit by to měl mít možnost jen jiný globální administrátor. V podstatě to asi bude oprávnění pro mě (nebo pro to možná uděláme speciální účet, ať se mi to nemotá dohromady) a pro správcovské účty Huld (podle potřeby).

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Musel jsem se s tím trošku seznámit, abych to pochopil, ale funguje to myslím docela dobře. Jestli tomu dobře rozumím, tak oprávnění ve smyslu zadání (např. správa uživatelů), jsou vlastně kombinací několika položek z menu "Uživatelská oprávnění". Zároveň jde tyto položky shlukovat do "Skupin", kterým můžeme říkat právě např. správa uživatelů apod. Pokud toto platí, přišlo by my o mnoho přehlednější oprávnění přidělovat vždy po skupinách, tj. v editaci uživatelů vůbec část "Uživatelská oprávnění" nezobrazovat a nechat tam pouze část "Skupiny". Mezi skupiny bychom přidali všechny potřebné skupiny a ty pak přidělovali uživatelům. Zjednodušilo by to i přehled v #269 a celkově mi to přijde koncepční i ve vztahu k dalším potřebám.
- [ ] Když jsem ale chtěl nyní toto řešení otestovat a takovou skupinu vytvořit, dostal jsem po pokusu uložit změny (http://192.168.254.30:8080/admin/auth/group/add/) error 500.
- [ ] Pokud tomu zároveň dobře rozumím, tak položky začínající na "dokument | *" v poli "Uživatelská oprávnění" mají být přípravou pro oprávnění ke správě 3D. Pokud to tak je, pak to není úplně dobře, protože s tím to nemá moc společného; dané oprávnění (skupina) by mělo uživateli umožnit archivovat 3D modely (nic více, nic méně), takže to nastavení nebude takto široké. Pokud ale použijeme řešení podle prvního bodu, je to vlastně jedno, protože si zatím jen vytvoříme danou skupinu a její význam budeme řešit až později v příštím roce (při celkovém řešení oprávnění v rámci aplikace z uživatelského pohledu).
- [ ] Pokud to doladíme, jak popisuji výše, bylo by skvělé mít možnost podle skupin filtrovat v tabulce http://192.168.254.30:8080/admin/uzivatel/user/

Je mi jasné, že body výše nejsou z části v pravém smyslu slova chybou, ale cílem i podle zadání je definovat právě ty "Skupiny" uživatelů s určitými oprávněními. Problém v zadání je spíš v nesouladu v terminologii, kdy jsme dříve v AMČR měli zvlášť "role" a "oprávnění" (což bylo každé něco jiného, ale oboje byly vlastně skupiny oprávnění) a dnes máme jen do větší podrobnosti jdoucí dílčí "oprávnění", které dohromady tvoří "skupiny". Nový přístup mi jednoznačně přijde lepší, jen bych proto navrhoval doladění výše.

Samotné chování (přístup do administrace, možnost editace textů atd.) funguje dobře.

**Comment by pesikj** [comment]
@motyc Navrhuji se k tomuto budu spojit přes Zoom a probrat to.

**Comment by motyc** [comment]
@pesikj Souhlas, kdy se Vám to hodí? Klidně můžu hned...

**Comment by pesikj** [comment]
@motyc Ok, tak se potkejme na zoomu hned.

**Comment by pesikj** [comment]
@motyc 
>  Když jsem ale chtěl nyní toto řešení otestovat a takovou skupinu vytvořit, dostal jsem po pokusu uložit změny (http://192.168.254.30:8080/admin/auth/group/add/) error 500.

Vytvoření skupiny nefungovalo, protože z nějakého důvodu byla špatně nastavená sekvence. Opravil jsem to, ale neznám příčinu a po novém nahrání databáze se to teoreticky může objevit znovu.

**Comment by pesikj** [comment]
> Pokud tomu zároveň dobře rozumím, tak položky začínající na "dokument | *" v poli "Uživatelská oprávnění" mají být přípravou pro oprávnění ke správě 3D. Pokud to tak je, pak to není úplně dobře, protože s tím to nemá moc společného; dané oprávnění (skupina) by mělo uživateli umožnit archivovat 3D modely (nic více, nic méně), takže to nastavení nebude takto široké. Pokud ale použijeme řešení podle prvního bodu, je to vlastně jedno, protože si zatím jen vytvoříme danou skupinu a její význam budeme řešit až později v příštím roce (při celkovém řešení oprávnění v rámci aplikace z uživatelského pohledu).

Vyřešeno na Zoom callu.

**Comment by pesikj** [comment]
>  Na Zoomu jsme se shodli, že není třeba skupina "Neaktivní uživatel" - je třeba odstranit buď novým příkazem pro migrace (asi snazší), nebo úpravou původních + revidovat, zda to někde v kódu přecijen není.

Po telefonu domluveno, že výchozí skupina bude nyní Badatel.

**Comment by pesikj** [comment]
@motyc 
>  EDIT: Pole telefon je zbytečně velké (stačí jeden řádek a kratší - jako např. příjmení).

To je stejný problém jako u ostatních textových polí. Navrhuji řešit s novou databází, kde bude použit CharField.

**Comment by pesikj** [comment]
@motyc 
> -- skupiny (zde výčet skupin, ve kterých je kvůli možnosti filtrace)

Django nepodporuje přidávání ManyToMay polí do tabulek. Ale filtr na skupiny jsem přidal, stačí to tak?

**Comment by motyc** [comment]
> Django nepodporuje přidávání ManyToMay polí do tabulek. Ale filtr na skupiny jsem přidal, stačí to tak?

Ano + tedy do tabulky prosím zobrazte alespoň tu hlavní roli, ať se v to jde alespoň částečně zorientovat.

**Comment by motyc** [comment]
#Výsledek testu
- [ ] Uživatele jde nyní ze skupin pouze odebírat, ale nejde je do nich přidávat (když v rozhraní udělám nějaké změny, neuloží se) -> nemohu testovat většinu zbylých funkcí
- [ ] V rozhraní zůstala část "Uživatelská oprávnění", kterou jsme se dohodli, že odstraníme: 
![image](https://user-images.githubusercontent.com/20186892/205698704-799d46a1-01e6-4be3-a652-9f352e42bea8.png)
- [ ] Jestli měl k něčemu být soubor https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/42_user_is_staff.sql, tak je prázdný a dělat nic nebude
- [ ] Nevím, jestli bychom podobně jako u heslářů neměli znemožnit smazání skupiny, ve které jsou nějací uživatelé (raději jsem netestoval, co to teď udělá, ať úplně nerozbiju databázi - je možné, že to ošetřené je)

**Comment by motyc** [comment]
@motyc To muselo vzniknout v Huld. My do DB tímto způsobem nezasahujeme. Možná nějaké testování od @pesikj

**Comment by pesikj** [comment]
@motyc Já určitě ne, podle mě to bylo špatně nastavené od začátku.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] V poli hlavní role nyní jde vybrat jakoukoli skupinu, mělo by být omezeno na odpovídající role (Badatel, Archeolog, Archivář, Admin).
- [ ] Když je nastavena hlavní role, je zároveň potřeba, aby uživatel byl ještě v dané skupině? Pokud ano, nemělo by se to nějak svázat, tj. aby změna jednoho měnila i druhé? Možná to bude složitější a můžeme to odtud vydělit do nového issue, tuším tam ale potenciální problémy a chyby při administraci.
- [ ] Omezení pro odstranění skupiny funguje dobře pro skupiny Badatel-Admin, u ostatních to ale smazat jde, i když v nich uživatelé jsou (správně se to vylistuje, ale není tam omezení, aby to nešlo smazat. Nemá se to řešit pomocí constraint v DB/modelu?

Jinak již vše funguje velice dobře.

**Comment by pesikj** [comment]
@motyc A je nutné pole hlavní role vůbec mít? Pro Django to nemá vůbec význam, pro role (skupiny) se používá vazba M:N, hlavní role je tam navíc.

**Comment by motyc** [comment]
@pesikj No, jak se to vezme. Je to tak, že ty čtyři skupiny (badatel-admin) se navzájem vylučují a každý aktivní uživatel v jedné z nich musí být. Pokud bychom to zvládli nějak ošetřit, pak asi nemusí. Nevím, jestli by to nebylo velké ohýbání, ale posuďte sám.

**Comment by pesikj** [comment]
@motyc
> každý aktivní uživatel v jedné z nich musí být
To jde ošetřit tím, že uživatel bude vložen do skupiny Badatel vždy, když by hrozilo, že v žádné jiné není.
> se navzájem vylučují
Technicky není důvod, aby se vylučovaly, ale pokud byste na tom trval, může být uživatel ponechán ve skupině s nejvyššími právy, pokud by hrozilo, že bych měl být ve více skupinách. Z pohledu nastavení práv je to zbytečné, ale pokud by to mělo význam např. pro nějaký reporting, lze to tak provést.
> Nevím, jestli by to nebylo velké ohýbání, ale posuďte sám.
Ohýbání to není, je to technicky čistší řešení než použití hlavní role.

**Comment by motyc** [comment]
@pesikj Ok, tak můžeme jít touto cestou. Jen poznamenávám:

>To jde ošetřit tím, že uživatel bude vložen do skupiny Badatel vždy, když by hrozilo, že v žádné jiné není.

Musí se případně testovat, že není v žádné z těch čtyř základních, nikoli v jakékoli jiné (nestačí např. "Úprava textů").

> Technicky není důvod, aby se vylučovaly, ale pokud byste na tom trval, může být uživatel ponechán ve skupině s nejvyššími právy, pokud by hrozilo, že bych měl být ve více skupinách. Z pohledu nastavení práv je to zbytečné, ale pokud by to mělo význam např. pro nějaký reporting, lze to tak provést.

Technicky ne, ale prakticky velký, protože by mohl vzniknout chaos. Roli hraje i ten reporting apod. hraje roli. Byl bych skutečně raději, aby systém ohlídal, že tyto základní skupiny nemohu mít dvě zároveň.

Také bude třeba prověřit, že se to opravdu nikde v kódu nepoužívá hlavní role jako podmínka u nějaké funkce.

Potřebovali bychom také zachovat, aby v té tabulce s přehledem uživatelů zůstala ta základní role zobrazena, jinak se v tom nepůjde vyznat.

Jak to tady rozebíráme, tak by možná stálo za to udělat z toho zvlášť issue, ať se to udělá v klidu bez spěchu, co myslíte?

**Comment by pesikj** [comment]
> Také bude třeba prověřit, že se to opravdu nikde v kódu nepoužívá hlavní role jako podmínka u nějaké funkce.

To není třeba, lze to vyřešit pomocí property, která bude poskytovat stejnou informaci.

> Potřebovali bychom také zachovat, aby v té tabulce s přehledem uživatelů zůstala ta základní role zobrazena, jinak se v tom nepůjde vyznat.

To lze také řešit pomocí property

> Jak to tady rozebíráme, tak by možná stálo za to udělat z toho zvlášť issue, ať se to udělá v klidu bez spěchu, co myslíte?

Souhlasím.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] - nyní naopak nejde smazat žádná skupina, bez ohledu na to, zda v ní nějaký uživatel je nebo není - viz http://192.168.254.30:8080/admin/auth/group/11/change/ (je prázdná, smazat nejde)
