### ISSUE TITLE
Správa heslářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#385]
- [x] Může editovat pouze administrátor s patřičným oprávněním (k administraci heslářů; viz #384).
- [x] Obsahuje obdobné funkcionality jako administrace uživatelů (přehledové tabulky, vyhledávání, filtrace, hromadné operace atd.)
- [ ] Při přidání záznamu se automaticky generuje validní ident_cely pro daný typ záznamu (HES-123456), obdobně jako pro uživatele (viz #384).
- [x] Použitá hesla, osoby a organizace nelze smazat, dokud nejsou odpojena od jednotlivých záznamů (mimo vztahy mezi tabulkami heslar_xy).

### Slouží ke správě obsahu tabulek z DB:
- [x] **heslar_nazev**
- Vše pouze k zobrazení.
- Pokud záznam v povolit_zmeny nemá ano, nesmí jít žádným způsobem editovat související záznamy v tabulkách heslar a heslar_hierarchie (ani přidávat nová hesla). Tímto lze oddělit “systémové” hesláře, které jsou užívány jako konstatnty v rámci aplikace a měnit je lze pouze po dohodě s vývojáři.
- [x] **heslar**
- Lze zobrazit: ident_cely, nazev_heslare
- Lze editovat: heslo, popis, zkratka, heslo_en, popis_en, zkratka_en, razeni
- Umožňuje přidávání nových hesel
- Umožňuje mazání existujících hesel
- [x] **heslar_datace**
- Vše lze editovat, přidávat nové záznamy, odstraňovat záznamy
- Váže se na hesla z hesláře období
- [x] **heslar_dokument_typ_material_rada**
- Vše pouze k zobrazení.
- Jednotlivé sloupce vázány na odpovídající hesláře
- [x] **heslar_hierarchie**
- Vše lze editovat, přidávat nové vztahy, odstraňovat vztahy
- Váže se na libovolná hesla
- Typ vztahu může nabývat hodnot:
-- podřízenost - podřazené heslo je hierarchicky podřízeným potomkem nadřazeného hesla
-- uplatnění - podřazené heslo se uplatňuje v souvislosti s nadřazeným heslem
-- výchozí hodnota - podřazené heslo se uplatňuje jako výchozí hodnota při použití nadřazeného hesla
- [x] **heslar_odkaz**
- Vše lze editovat, přidávat nové odkazy, odstraňovat odkazy
- Váže se na libovolná hesla
- [x] **osoba**
- Lze zobrazit: ident_cely
- Lze editovat: vše ostatní
- Lze přidávat nové a odstraňovat existující
- [x] **organizace**
- Lze zobrazit: ident_cely
- Lze editovat: vše ostatní
- Lze přidávat nové a odstraňovat existující
- [x] **ruian_katastr**
- Vše pouze k zobrazení.
- [x] **ruian_okres**
- Vše pouze k zobrazení.
- [x] **ruian_kraj**
- Vše pouze k zobrazení.

**Comment by pesikj** [comment]
> osoba
> Lze zobrazit: ident_cely
> Lze editovat: vše ostatní
> Lze přidávat nové a odstraňovat existujícíosoba

@motyc 
U modelu Osoba není pole ident_cely, to samé platí pro model Organizace.

**Comment by motyc** [comment]
@pesikj Ano, ale oprava se řeší v #474. Preferujete si to vyřešit tady, nebo to takto stačí?

**Comment by pesikj** [comment]
@motyc Dobře, takhle to stačí. Kdybych byl s řešením hotový dříve, tak navrhuji přesunout přidání těchto polí do samostatného issue.

**Comment by pesikj** [comment]
@motyc Je někde přehled prefixů u identů podle typu záznamů? Nebo má být všude HES?

**Comment by motyc** [comment]
@pesikj Pokud se bavíme čistě o heslářích, tak tam nic speciálního není potřeba a všude to bude schéma HES-123456 (průběžná řada). Ident_cely se vč. sekvence přenese z produkce, což jsme nově řešili s @pbartosova v #476. Je na to už připravená migrace i data, ale na testu se to projeví až po nové migraci. Zatím to tedy pro testovací účely můžete naplnit všude nějak zástupně. Obecně máme tvorbu ident_cely popsanou tady, ale ty nove případy tam zatím nebudou zapsané (měli bychom to doplnit): https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely

**Comment by pesikj** [comment]
@motyc Dobře, já tuto část smažu a issue je v tom případě vyřešené.

**Comment by motyc** [comment]
### Výsledky testu
- [ ] http://192.168.254.30:8080/admin/heslar/heslar/ - v tabulce je třeba zobrazit ještě sloupce:
-- heslo_en
-- zkratka_en
-- razeni
- [ ] pole v editaci/přidávání záznamů jsou zbytečně veliká - stačí vždy jeden řádek (platí pro heslar, organizace, osoba, heslar_odkaz)
- [ ] když zavolám se pokusím odstranit heslo s vazbami (resp. záznam z libovolné tabulky), dostanu error 500; je v pořádku, že záznam nejde smazat, protože je použité u dalších záznamů v DB, ale zamezit by tomu měla aplikace a podat smysluplnou hlášku, neměla by se jen vrátit generická chyba DB; mám ale dojem, že tohle bude trošku souviset (přinejmenším v tom přehledu, jaká napojení existují) s nutností nechat vygenerovat DB znovu Djangem, že ano?
- [ ] http://192.168.254.30:8080/admin/uzivatel/osoba/ - v tabulce je třeba zobrazit ještě sloupce:
-- vypis_cely
-- rodne_prijmeni
-- rok_umrti je tam naopak 2x
- [ ] http://192.168.254.30:8080/admin/uzivatel/organizace/add/ (+ edit) - v polích chybí omezení na konkrétní hesláře:
-- Uzivatel.models.Organizace.typ_organizace - organizace_typ
-- Uzivatel.models.Organizace.zverejneni_pristupnost - pristupnost
- [ ] http://192.168.254.30:8080/admin/uzivatel/organizace/add/ - Uzivatel.models.Organizace.zanikla by mělo být not null a výchozí hodnota je "Ne" (v DB chybí - to opravím v migracích)
- [ ] http://192.168.254.30:8080/admin/uzivatel/organizace/?q=test - vrací error 500
- [ ] http://192.168.254.30:8080/admin/uzivatel/organizace/ - v tabulce je třeba zobrazit ještě sloupce:
-- ident_cely
-- nazev
-- nazev_zkraceny_en
-- nazev_en
-- soucast
-- ico
-- adresa
-- email
-- telefon
-- zverejneni_pristupnost
-- mesicu_do_zverejneni
- [ ] nemohu testovat funkcionality spojené s heslar_nazev.povolit_zmeny, protože je všude "true" (to souvisí s migracemi, které doplnim); prosím o nastavení false pro nějaký heslář (např. pristupnost), abych to mohl zkusit - sám to nyní změnit nijak nemůžu
- [ ] http://192.168.254.30:8080/admin/heslar/heslardatace/add/ (+ edit) - chybí omezení na konkrétní heslář v Heslar.models.HeslarDatace.obdobi - obdobi
- [ ] http://192.168.254.30:8080/admin/heslar/heslarhierarchie/ - v poli typ se vůbec nezobrazují data z DB, přestože tam jsou dostupná - asi je to kvůli volbě nových konstant, bez ohledu na stávající data, to ale patrně nejde, protože ty stávající už budou používané v kódu v aplikační logice;
- [ ] http://192.168.254.30:8080/admin/heslar/heslarhierarchie/ - první dva sloupce mají stejný nadpis (data jsou ale jiná) - druhý má být Heslar.models.HeslarHierarchie.heslo_nadrazene
- [ ] http://192.168.254.30:8080/admin/heslar/heslarodkaz/ - doplnit sloupec uri
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankatastr/ - doplnit sloupec pian a odstranit sloupec aktualni
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankraj/ - doplnit sloupec nazev_en (asi chybí v DB, řešíme v migracích) a odstranit sloupec aktualni
- [ ] http://192.168.254.30:8080/admin/heslar/ruianokres/ - odstranit sloupec aktualni
- [ ] http://192.168.254.30:8080/admin/heslar/heslarhierarchie/ - filtace podle heslo_podrazene zde nedává smysl; ponechat jen podle typu

Zatím se také nepřiděluje ident_cely - to ale předpokládám souvisí s potřebou nové migrace.

**Comment by pesikj** [comment]
@motyc 
>  pole v editaci/přidávání záznamů jsou zbytečně veliká - stačí vždy jeden řádek (platí pro heslar, organizace, osoba, heslar_odkaz)

To je dané tím, že v modelu je pole TextField, které slouží k ukládání dlouhých textů. Pokud tam mají být krátké texty obecně, pak je vhodnější pole CharField. Úprava widgetu v admin formuláři by asi šla, ale obecně nedává moc smysl, lepší je vhodně definovat pole na úrovni databáze.

>  když zavolám se pokusím odstranit heslo s vazbami (resp. záznam z libovolné tabulky), dostanu error 500; je v pořádku, že záznam nejde smazat, protože je použité u dalších záznamů v DB, ale zamezit by tomu měla aplikace a podat smysluplnou hlášku, neměla by se jen vrátit generická chyba DB; mám ale dojem, že tohle bude trošku souviset (přinejmenším v tom přehledu, jaká napojení existují) s nutností nechat vygenerovat DB znovu Djangem, že ano?

Zde je asi problém s nastavením cizích klíčů. Při řádně vytvořené databázi Django neumožní smazat záznamy, které nemohou být smazány na základě referenční integrity. Navrhoval bych toto řešit až s novou databází.

**Comment by pesikj** [comment]
@motyc 
> v tabulce je třeba zobrazit ještě sloupce:
> -- ident_cely

Model `Organizace` pole `ident_cely`, je to chyba v textu, nebo je tím myšleno něco jiného?

**Comment by pesikj** [comment]
>  http://192.168.254.30:8080/admin/heslar/ruiankraj/ - doplnit sloupec nazev_en (asi chybí v DB, řešíme v migracích) a odstranit sloupec aktualni

Sloupec `nazev_en` může být přidán, až bude vytvořen sloupec v databázi.

**Comment by pesikj** [comment]
@motyc 
>  http://192.168.254.30:8080/admin/heslar/heslarhierarchie/ - v poli typ se vůbec nezobrazují data z DB, přestože tam jsou dostupná - asi je to kvůli volbě nových konstant, bez ohledu na stávající data, to ale patrně nejde, protože ty stávající už budou používané v kódu v aplikační logice;

Mají tedy být v aplikaci upraveny hodnoty, aby byly v souladu s databází, nebo naopak?

**Comment by pesikj** [comment]
@motyc 
> když zavolám se pokusím odstranit heslo s vazbami (resp. záznam z libovolné tabulky), dostanu error 500; je v pořádku, že záznam nejde smazat, protože je použité u dalších záznamů v DB, ale zamezit by tomu měla aplikace a podat smysluplnou hlášku, neměla by se jen vrátit generická chyba DB; mám ale dojem, že tohle bude trošku souviset (přinejmenším v tom přehledu, jaká napojení existují) s nutností nechat vygenerovat DB znovu Djangem, že ano?

Vyřešeno přidáním třídy `ManyToManyRestrictedClassMixin`. Přidal jsem ji k modelům `Organizace` a `Osoba`, problém se mi nepodařilo nasimulovat na ostatních modelech, takže předpokládám, že tam není potřeba. Ale řešení je obecné a je možné ho použít i jinde.

**Comment by motyc** [comment]
@pesikj 
> Model Organizace pole ident_cely, je to chyba v textu, nebo je tím myšleno něco jiného?

Asi narážíte na to, že pole chybí v DB. To už řešíme v #474, tak si to necháme otevřené jako věc k dořešení po opravě migrací (platí i pro další tyto případy).

Zbytek jsme snad prošli po telefonu.

**Comment by pesikj** [comment]
@motyc Změny zakázány u http://192.168.254.30:8080/admin/heslar/heslarnazev/1/change/?_changelist_filters=povolit_zmeny__exact%3D0

**Comment by motyc** [comment]
### Výsledek testu
- [ ]  http://192.168.254.30:8080/admin/heslar/heslarhierarchie/ - ponechat jen filtraci podle typu (teď se tam doplněním sloupce dostalo ještě heslo_nadrazene)
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankatastr/ - ve sloupci pian prosím uvádět ident_cely, nikoli id
- [ ] tam, kde se vybírá ze všech hesel (http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/; http://192.168.254.30:8080/admin/heslar/heslarodkaz/add/ + totéž pro edit) jsou seznamy dost k nepoužití, protože najít tam správné heslo je skoro nemožné; co by pomohlo:
-- umět v seznamu filtrovat zápisem z klávesnice
-- mít heslář rozdělený nadpisy podle toho, do kterého hesláře hesla patří (a po těchto skupinách řadit k sobě)
-- nevím co z bodu výše jde a jak snadno, případně prosím o jiné možnosti, které Django třeba nativně nabízí
- [ ] http://192.168.254.30:8080/admin/heslar/heslarhierarchie/1/change/?_changelist_filters=p%3D2%26typ__exact%3Dv%25C3%25BDchoz%25C3%25AD%2Bhodnota - dostanu error 500 (může souviset s následujícím bodem)
- [ ] http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/ - testy jsou nastaveny nějak divně, neodpovídají DB, kde je `CONSTRAINT heslar_hierarchie_heslo_podrazene_heslo_nadrazene_typ_key UNIQUE (heslo_podrazene, heslo_nadrazene, typ)`; to zápis níže splňuje, ale zapsat to stejně nejde:
![image](https://user-images.githubusercontent.com/20186892/205980611-e00df1b5-d562-4bfb-a0bd-df28dc46bd76.png)

### Otestovat po nové migraci 
- [ ] http://192.168.254.30:8080/admin/heslar/heslar/585/delete/ - dostanu error 500 - patrně souvisí s nutností vygenerovat DB podle modelů Djanga (@pesikj prosím o potvrzení)
- [ ] Zatím se také nepřiděluje ident_cely
- [ ] http://192.168.254.30:8080/admin/uzivatel/organizace/ - chybí ident cely (test nutný po migraci)
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankraj/ - doplnit sloupec nazev_en (asi chybí v DB, řešíme v migracích) a odstranit sloupec aktualni

**Comment by sedmar** [comment]
@pbartosova šlo by vyřešit úpravou v DB?

**Comment by motyc** [comment]
> > http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/ - testy jsou nastaveny nějak divně, neodpovídají DB, kde je CONSTRAINT heslar_hierarchie_heslo_podrazene_heslo_nadrazene_typ_key UNIQUE (heslo_podrazene, heslo_nadrazene, typ);
> 
> @pbartosova šlo by vyřešit úpravou v DB?

To určitě ne. DB je nastavena správně, problém bude v tom modelu.

**Comment by sedmar** [comment]
> [ ] tam, kde se vybírá ze všech hesel (http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/; http://192.168.254.30:8080/admin/heslar/heslarodkaz/add/ + totéž pro edit) jsou seznamy dost k nepoužití, protože najít tam správné heslo je skoro nemožné; co by pomohlo:
> -- umět v seznamu filtrovat zápisem z klávesnice
> -- mít heslář rozdělený nadpisy podle toho, do kterého hesláře hesla patří (a po těchto skupinách řadit k sobě)
> -- nevím co z bodu výše jde a jak snadno, případně prosím o jiné možnosti, které Django třeba nativně nabízí

@motyc Toto považujeme za nadstavbu objednané funkcionality, která nebyla v původním zadání a proto bychom to vyčlenili do nového issue a řešili jako požadavek na novou funckionalitu.

**Comment by motyc** [comment]
@sedmar Rozumím, vyčlením jako nové issue, až budu testovat zbytek.

**Comment by pesikj** [comment]
@motyc 
> http://192.168.254.30:8080/admin/heslar/heslar/ nepřiděluje se ident_cely
Zde souhlasím, že se stále nepřiděluje, nicméně s tímto issue to nesouvisí.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankatastr/ - error 500
- [ ] http://192.168.254.30:8080/admin/heslar/ruiankraj/ - skrýt pole definicni_bod

Jinak vše v pořádku (to k ident_cely byla jen poznámka pro mne).
