### ISSUE TITLE
Proklik na detail záznamu z mapy a zobrazení popisků

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#39]
V popisu bodu v mape je zobrazen ident_cely (projektu, PIAN...). Vyřešit jako hyperlinky, které povedou buď na konkrétní záznam (tam kde je vazba jednoznačná - projekty, 3D, sam. nálezy), nebo na filtraci podle PIAN (nutno dospecifikovat).

EDIT @motyc: podrobněji viz: https://github.com/ARUP-CAS/aiscr-webamcr/issues/39#issuecomment-1293334885

**Comment by motyc** [comment]
Při zobrazení mapy je třeba po kliknutí zobrazit tooltip a umožnit přechod na související záznam v tooltipu:
- [ ] vrstvy s projekty
-- při najetí zobrazit "`projekt.ident_cely` (`projekt.stav`)"
-- při kliknutí zobrazit `projekt.ident_cely` s proklikem na konkrétní záznam v novém tabu
- [ ] vrstvy se samostatnými nálezy
-- při najetí zobrazit `samostatny_nalez.ident_cely`
-- zobrazit `samostatny_nalez.ident_cely` s proklikem na konkrétní záznam v novém tabu
- [ ] vrstvy s dokumenty 3D
-- při najetí zobrazit `dokument.ident_cely`
-- při kliknutí zobrazit dokument.ident_cely s proklikem na konkrétní záznam v novém tabu
- [ ] vrstvy s PIAN
-- při najetí zobrazit "`pian.ident_cely` (`pian.presnost`)"
-- při kliknutí zobrazit `dokumentacni_jednotka.ident_cely` (všechny napojené) s proklikem na konkrétní záznam v novém tabu

**Comment by motyc** [comment]
Slučuji s #508
