### ISSUE TITLE
Úprava názvů exportovaných tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#396]
Pojmenovat jako export_ + název modulu_ + timestamp ve formátu RRRR_MM_DD_HH_MM_SS + přípona.

Např. "export_projekty_2022-02-15-10-15-48.csv"

**Comment by petrpajdla** [comment]
Ten timestamp by byl lepší s pomlčkami RRRR-MM-DD-HH-MM-SS aby se to kdyžtak dalo hezky rozsekat regexem ten celý název a timestamp zůstal vcelku, co myslíš?
Takže export_projekty_2022-02-15-10-32-00.csv.

**Comment by motyc** [comment]
@petrpajdla Ok, souhlas, upravuji.

**Comment by pesikj** [comment]
@motyc Jde o export pouze tímto menu? Nebo je i jiný způsob exportu?

![image](https://user-images.githubusercontent.com/15179154/181748004-5949e53a-e14e-4854-b8b3-42ebbf6f7547.png)

**Comment by motyc** [comment]
@pesikj Ano, jde o toto menu.

**Comment by motyc** [comment]
### Výsledek testu:
- [ ] - http://192.168.254.30:8080/dokument/model/vyber - chybný název "dokumenty" -> "modely"
- [ ] - http://192.168.254.30:8080/ext-zdroj/vyber - chybný název "lokalita" -> "externi-zdroje"

**Comment by jnihnat** [comment]
opraveno v #746
