### ISSUE TITLE
Akce - chyba migrace dalších katastrů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#397]
Nedošlo k převodu Akce - Další katastry do nové verze (např. C-200912861); prověřit též pro projekty a lokality

Problém je někde v migraci, kdy např. u akce C-200912861A nebyly správně převedeny další katastry, které v původní databázi jsou, ale v nové nikoli. Je třeba se podívat, jak chyba vznikla a zkontrolovat, že k převodu dochází správně všude, kde se s dalšími katastry pracuje, tj. u projektů, akcí a lokalit. Nyní jsem to ještě kontroloval u projektu C-201900257 / akce C-201900257A - zde je dobře vidět, že u projektu se další katastry převedly v pořádku, ale pro akci ne. Přitom způsob uložení a migrace by měl být stejný. Bude tam tedy někde v případě akce chyba. Pro lokality jsem to teď v DB taky kontroloval (např. C-N1000001) a zdá se to být ok.

Vzniklo rozdělením #123

**Comment by pesikj** [comment]
@motyc Co konkrétně znamená, že nedošlo k převodu do nové verze? To se týká souřadnic, nebo něčeho jiného?

**Comment by motyc** [comment]
Znamená to, že je nějaká chyba v migraci. Souřadnic se to netýká, týká se to obsahu pole akce.dalsi_katastry, které není správně převedeno do tabulky akce_katastr v nové DB.

**Comment by pesikj** [comment]
@motyc Podařilo se mi dostat databázi do stavu, která jakž takž odpovídá stavu před migrací dat (nějaké chyby ty migrace vyhazují, ale vše v souvislosti s tímto issue by mělo být funkční) a vytvořil jsem následující testovací dotaz:

```sql
select distinct a.id, a.dalsi_katastry, r.*, false from akce a join ruian_katastr r on r.nazev = SUBSTRING(split_part(dalsi_katastry, ';', 1), 1, POSITION('(' in split_part(a.dalsi_katastry, ';', 1)) - 2) where split_part(a.dalsi_katastry, ';', 2) != ''
and a.ident_cely = 'C-200912861A';
```

Číslo 1 nahrazuje counter v SQL. Výsledek je pak vkládán do tabulky `akce_katastr`. Výsledek je v pořádku. V tomto kroku migrace tedy problém nevidím, data jsou vložena do tabulky v pořádku. Buď tedy proběhla migrace stávající databáze nekorektně, nebo byly další katastry později smazány. Navrhuji toto issue zatím odložit a po nové testovací migraci databáze provést kontrolu, zda je vše přeneseno a zobrazeno korektně a zda třeba nedochází k chybám při ukládání formuláře.

![image](https://user-images.githubusercontent.com/15179154/171212791-d1a7beaa-a3ef-4061-be16-2161a6e43fed.png)

**Comment by motyc** [comment]
@pesikj Souhlasím, zařaďme tedy mezi issue k testování a budeme to sledovat.
