### ISSUE TITLE
Prázdná textová pole v DB (null vs. prázdný řetězec)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#398]
Django do prázdných textových polí nedává null ale ‘’ (viz třeba ADB-PRAH72-006774); dosud v databázi užíváno většinou null - mělo bychom to dělat jednotně a případně ošetřit v migraci.

Nejdříve prosíme @pesikj o popis stávajícího stavu, pak o návrh řešení.

Vzniklo rozdělením #123

**Comment by pesikj** [comment]
Zřejmě se jedná o popsané chování Django u textových polí (`TextField` a `CharField`), požadavek má tag `wontfix`, takže zřejmě nebude vyřízen.

https://code.djangoproject.com/ticket/9590

**Comment by pesikj** [comment]
@motyc 
Toto je v oficiální dokumentaci:

> Avoid using [null](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.Field.null) on string-based fields such as [CharField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.CharField) and [TextField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.TextField). If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” **the Django convention is to use the empty string, not NULL**. One exception is when a [CharField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.CharField) has both unique=True and blank=True set. In this situation, null=True is required to avoid unique constraint violations when saving multiple objects with blank values.

https://docs.djangoproject.com/en/3.2/ref/models/fields/#null

Navrhuji toto chování zdokumentovat a neupravovat. Nerad bych šel proti jasnému doporučení v oficiální dokumentaci, zvláště v tomto případě, kdy změna chování nemá z pohledu aplikace žádný přínos (nebo ho alespoň nevidím).

**Comment by motyc** [comment]
Pak bychom to tedy měli sjednotit obráceně, tj. při migraci převést vše na hodnotu podle Django. Jde o jednotnost, nikoli o konkrétní řešení...

**Comment by pesikj** [comment]
@motyc Ano, to je dobré řešení.

**Comment by pesikj** [comment]
@motyc U tohoto issue předpokládám, že není očekáváno řešení do 30. června. Je potřeba prodiskutovat, jak k tomu přistupovat.

**Comment by motyc** [comment]
@pesikj Ano, stačí to, až se budeme věnovat #474

**Comment by motyc** [comment]
Vyřešeno v https://github.com/ARUP-CAS/aiscr-webamcr/commit/5e4e86295f8f4f3da0ae681d991a31032570b37e
