### ISSUE TITLE
Padají automatické testy

### ISSUE THREAD

**Issue by pesikj** [ARUP-CAS/aiscr-webamcr#423]
Automatické testy by měly být spouštěné pro každou větev, aby byla chyba vidět před propojením MR.
FYI @motyc

**Comment by pesikj** [comment]
@motyc Jeden test upraven, další dva testy je nutné přepsat, aby byly v souladu s novou verzí aplikace. Padání testů tedy není způsobeo bugy v aplikaci.

**Comment by motyc** [comment]
@pesikj Zde máte na mysli logy spojený s automatickými testy, nebo s během aplikace? Případně prosím zapište do dokumentace jak to funguje a kde výstupy najít.

**Comment by motyc** [comment]
@pesikj Díky za vysvětlení. Já právě nevím ani to, kde jsou logy umístěné dosud. Šlo by k tomu tedy prosím přihodit pár vět do: https://github.com/ARUP-CAS/aiscr-webamcr/wiki ?

**Comment by pesikj** [comment]
@motyc Máte nějakou preferovanou formu ukládání?
