### ISSUE TITLE
REQ-D-6 - detail dokumentu

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#44]
url: dokument/detail/ident_cely

- [x] Implementace detailu
- [x] Pridani casti_dokumentu
- [x] Uprava stylu

**Comment by Najiva** [comment]
Stavajici stav. Pro vyvoj muzes pouzit /dokument/detail/C-DT-100004853

![Screenshot from 2021-05-07 12-55-17](https://user-images.githubusercontent.com/26173315/117439754-89801e80-af33-11eb-8d7e-833f77133680.png)
@pkudela  Chce to u dokumentu upravit hlavne Detail a pak formu v editaci.

**Comment by pkudela** [comment]
Hotovo, @Najiva prosim mrkni na to pole "Osoby", tam to hazi chybu, pokud tam zadam - {{ dokument.osoby.all|hesla_to_list }} - je to v kodu vedle zkomentovana, az to opravis, tak to rovnou zmen i v popoveru hned pod tim v atributu "data-content"
