### ISSUE TITLE
Testování - chyby bez zjevné vazby na otevřená issue

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#461]
Rozděleno na issues:
#513
#514
#515
#516
#517
#518
#519
#520
#521
#522
#523
#524
#525
#526
#527
#528
#529

**Comment by motyc** [comment]
@pesikj V důsledku komitů dochází k opakovanému uzavírání tohoto issue. Pokud jde to automatické zavření nějak obejít, bylo by to prosím fajn.

**Comment by pesikj** [comment]
@motyc Vůbec nevím, proč se tak děje, možná vadí text "fix" v komentáři, nebo jde o bug GitHubu.

**Comment by pesikj** [comment]
@jnihnat Honzo, podívej se prosím na:

> Při najetí na tlačítko pro editaci se tooltip zobrazí přes tlačítko, na které pak nejde kliknout. Navíc to vede někdy zacyklení, kdy se při najetí na levou polovinu tlačítka tooltip zběsile začne obnovovat (mizet a zobrazovat se - hlavně v Chrome, v Mozille také, ale není to tak frenetické).

> Kliknu na Archivovat a modal z dotazem má nulovou velikost:

> chybné vertikální zarovnání řádků v tabulce (není na střed - děje se i jinde)

**Comment by pesikj** [comment]
@motyc 
> Akci nejde odeslat, nevím proč
Akci se nedařilo odeslat, protože chyběl popis u dokumentu, uživatel byl o tom informován chybovou zprávou v hlavičce formuláře. Chyba má jen technický text, chybí řetězec v překladovém souboru, ale jinak je za mě uživatel informován a má možnost chybu opravit.

**Comment by pesikj** [comment]
@jiri-bartos-huld 
Jirko, můžeš se prosím podívat na tohle?
> přestala fungovat možnost “Připojit PIAN z mapy” (nic nedělá)
>  vytváření PIAN nefunguje - při pokusu zadat bod vrací “Geometrii se nepodařilo ověřit”

**Comment by pesikj** [comment]
@motyc 
>  ve stavové liště svítí najednou stav odeslaný i archivovaný

Mám trochu podezření, že je zde spíše problém v barvách, funkčnost je podle mě v pořádku. Ale barvy minulých kroků by asi měly být méně výrazné než aktuálního, teď je to spíše obráceně. Máte někde definovanou nějakou barevnou paletu?

![image](https://user-images.githubusercontent.com/15179154/171639171-38e52e69-29c5-49a9-b47e-3486276c4820.png)

**Comment by pesikj** [comment]
@motyc 
> chybné vertikální zarovnání řádků v tabulce (není na střed - děje se i jinde)

To se týká jen sloupců s odkazem?

**Comment by pesikj** [comment]
@motyc 
> filtrace podle vedoucího nefunguje (nemohu najít uživatele, kteří určitě existují a jsou i v tabulce); celé pole je však zvláštní (měl by asi být asynchronní heslář jako u projektů)

Můžete uvést konkrétního uživatele?

**Comment by jnihnat** [comment]
> @motyc
> 
> > chybné vertikální zarovnání řádků v tabulce (není na střed - děje se i jinde)
> 
> To se týká jen sloupců s odkazem?

neni bug v #351 se opravovali jen popisky na stred. prosim na tohle udelat nove zmenovy pozadavek

**Comment by jnihnat** [comment]
@motyc a @pesikj 
- Při najetí na tlačítko pro editaci se tooltip zobrazí přes tlačítko, na které pak nejde kliknout. Navíc to vede někdy zacyklení, kdy se při najetí na levou polovinu tlačítka tooltip zběsile začne obnovovat (mizet a zobrazovat se - hlavně v Chrome, v Mozille také, ale není to tak frenetické).

Kvuli problikavani som pridal offset pro tolltip 1px hore, vidiet to nie je a malo by to pomoct.
Co sa tyka zobrazenia tooltipu cez Tlacitko, tak to sa u mna nedeje (vyskusany chrome aj mozila). Skuste prosim pre istotu premazat cache. Nic sa kolo tooltipov a css ani nemenilo, tak mi to je zvlastne zeby sa nieco take malo zacat diat...

**Comment by motyc** [comment]
> @motyc
> 
> > ve stavové liště svítí najednou stav odeslaný i archivovaný
> 
> Mám trochu podezření, že je zde spíše problém v barvách, funkčnost je podle mě v pořádku. Ale barvy minulých kroků by asi měly být méně výrazné než aktuálního, teď je to spíše obráceně. Máte někde definovanou nějakou barevnou paletu?

Máte pravdu! On je ten dokument ve stavu 1. Paleta byla definovaná jen ve smyslu hlavní barvy pro danou workflow, jinak ne. Tady určitě tu barvu pro zvýraznění budeme muset změnit. Udělám na toto téma samostatné issue.

**Comment by motyc** [comment]
@pesikj 
> > chybné vertikální zarovnání řádků v tabulce (není na střed - děje se i jinde)
> 
> To se týká jen sloupců s odkazem?

Naopak se to týká většiny polí. Mělo by to být vertikálně na střed, což jsou v daném případě jen tři poslední sloupce:
![image](https://user-images.githubusercontent.com/20186892/171834524-a62a6339-bf2b-407a-8f9d-861ffd42121d.png)

**Comment by motyc** [comment]
@pesikj 
> 
> > filtrace podle vedoucího nefunguje (nemohu najít uživatele, kteří určitě existují a jsou i v tabulce); celé pole je však zvláštní (měl by asi být asynchronní heslář jako u projektů)
> 
> Můžete uvést konkrétního uživatele?

Např.: `Mařík, Jan (U-000328)`

**Comment by motyc** [comment]
@pesikj 
> 
> > U všech akcí někam zmizel obsah pole organizace. Jde o chybu migrace spojenou s postupnými úpravami řešení DB. Pole v akce.organizace máme v původní produkční DB a stačí jej zachovat (při migraci původně bylo odstraněno).
> 
> Mazání sloupce jsem z migrace odstranil.

Bude třeba tedy ale odstranit i příkaz, kterým se pole znovu vytvořilo. Jinak ok.

**Comment by motyc** [comment]
@jnihnat 
> 
> * Při najetí na tlačítko pro editaci se tooltip zobrazí přes tlačítko, na které pak nejde kliknout. Navíc to vede někdy zacyklení, kdy se při najetí na levou polovinu tlačítka tooltip zběsile začne obnovovat (mizet a zobrazovat se - hlavně v Chrome, v Mozille také, ale není to tak frenetické).
> 
> Kvuli problikavani som pridal offset pro tolltip 1px hore, vidiet to nie je a malo by to pomoct. Co sa tyka zobrazenia tooltipu cez Tlacitko, tak to sa u mna nedeje (vyskusany chrome aj mozila). Skuste prosim pre istotu premazat cache. Nic sa kolo tooltipov a css ani nemenilo, tak mi to je zvlastne zeby sa nieco take malo zacat diat...

Cache vymazána, děje se stále stejně: https://user-images.githubusercontent.com/20186892/171836677-e97b33cc-0f2b-4478-a90d-a20bd2bddc5d.mp4

**Comment by jnihnat** [comment]
> @jnihnat
> 
> > * Při najetí na tlačítko pro editaci se tooltip zobrazí přes tlačítko, na které pak nejde kliknout. Navíc to vede někdy zacyklení, kdy se při najetí na levou polovinu tlačítka tooltip zběsile začne obnovovat (mizet a zobrazovat se - hlavně v Chrome, v Mozille také, ale není to tak frenetické).
> > 
> > Kvuli problikavani som pridal offset pro tolltip 1px hore, vidiet to nie je a malo by to pomoct. Co sa tyka zobrazenia tooltipu cez Tlacitko, tak to sa u mna nedeje (vyskusany chrome aj mozila). Skuste prosim pre istotu premazat cache. Nic sa kolo tooltipov a css ani nemenilo, tak mi to je zvlastne zeby sa nieco take malo zacat diat...
> 
> Cache vymazána, děje se stále stejně: https://user-images.githubusercontent.com/20186892/171836677-e97b33cc-0f2b-4478-a90d-a20bd2bddc5d.mp4

@motyc navrhuji z toho udelat samostatne issue, mne to porad nasimulovat nejde a to somskusil uz i Edge...
Muzu poprosit jeste verzi prohlizece? Taky kdyby to skusili vasi kolegove nasimulovat u nich, ci se nehonime jen za jednym pripadem u vas.
Problem je v tom, ze z nejakeho duvodu se ten tooltip zakotvi dole a nie hore, pricom cele tohle se dela pres bootstrap co pouzivame, nic nami vyvinuteho.
