### ISSUE TITLE
Srozumitelné chybové hlášky (400, 500 apod.)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#462]
Je třeba zajistit srozumitelnost pro uživatele (co dělat, proč chyba vznikla - pokud to jde atd.) + zobrazovat chybu jako HTML v základním designu (viz např. http://192.168.254.30:8080/accounts/password_reset).

**Comment by pesikj** [comment]
@motyc Má být hláška závislá pouze na kódu chyby, nebo i na něčem jiném?

**Comment by motyc** [comment]
@pesikj Stačilo by na kódu chyby. Nemáme myslím šanci odchytat všechny situace, kdy to může nastat. Ideálně to zase vložme do těch translations.

**Comment by jnihnat** [comment]
Odhad 3h i s dokumentaci. @pesikj
