### ISSUE TITLE
Opravit název souborů v PAS při migraci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#465]
Na žádost @jnihnat vyděleno jako samostatné issue z https://github.com/ARUP-CAS/aiscr-webamcr/issues/362

Pojmenování souborů je nyní chybně (zůstávají pomlčky, není na dvě číslice po F), při migraci je třeba soubory správně přejmenovat.

**Comment by jnihnat** [comment]
podle mne tohle soucasti odhadu nebylo, tam se ratalo jenom s prejmenovanim pri nahravani.
@pesikj @motyc @ScottVanWagenen

**Comment by motyc** [comment]
@jnihnat V dotčeném issue (#362) byl bod `nyní chybně (zůstávají pomlčky, není na dvě číslice po F) při migraci přejmenovat` již při vytvoření (teď jsem koukal do historie). Nedokážu říci, zda to bylo takto již při tvorbě odhadu.

**Comment by pesikj** [comment]
Na základě diskuse s @pbartosova bych toto issue navrhoval prodiskutovat na některém z meetingů.

**Comment by motyc** [comment]
@pesikj Ok.

**Comment by motyc** [comment]
Vyřešíme v rámci #38, toto zavírám.
