### ISSUE TITLE
Migrace - změny v heslářích

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#476]
Juraj bohužel částečně migrace postavil tak, že pracuje s pevnými ID přidělenými jednotlivým heslům v hesláři. Heslář na produkci se však průběžně mění (naposledy v tomto týdnu), což nutně vede k posunům a ve výsledku k chybám při migraci. Zvolené řešení je nepraktické a neudržitelné. Je nutné pracovat na základě údajů, které se měnit nebudou, např. zavedením pole ident_cely již na současný produkční server, a to minimálně pro hesla, která jsou klíčová z hlediska migrací.

Můžeme pomoci dané situace dohledat (nebude jich snad mnoho).

Je proto třeba:
- [x]  zvolit vhodné řešení
- [x]  implementovat jej
- [x]  zpětně opravit/aktualizovat migrace

**Comment by motyc** [comment]
@pbartosova Zde je seznam heslářů, kde je třeba přidat ident_cely (formát: "HES-123456"):
- heslar_podnet
- heslar_typ_sondy
- heslar_typ_akce_druha
- heslar_typ_akce_prvni
- heslar_aktivity
- heslar_areal_druha
- heslar_areal_prvni
- heslar_autorska_role
- heslar_specifikace_data
- heslar_dohlednost
- heslar_typ_dj
- heslar_format_dokumentu
- heslar_material_dokumentu
- heslar_nahrada
- heslar_rada
- heslar_typ_dokumentu
- heslar_ulozeni_originalu
- heslar_zachovalost
- heslar_typ_externiho_zdroje
- heslar_jazyk_dokumentu
- heslar_tvar
- heslar_letiste
- heslar_druh_lokality_druha
- heslar_druh_lokality_prvni
- heslar_typ_lokality
- heslar_typ_nalezu
- heslar_nalezove_okolnosti
- heslar_obdobi_druha
- heslar_obdobi_prvni
- heslar_objekt_druh
- heslar_objekt_kategorie
- heslar_specifikace_objektu_druha
- heslar_specifikace_objektu_prvni
- heslar_typ_organizace
- heslar_kulturni_pamatka
- heslar_presnost
- heslar_typ_pian
- heslar_pocasi
- heslar_posudek
- heslar_predmet_druh
- heslar_predmet_kategorie
- heslar_specifikace_predmetu
- heslar_pristupnost
- heslar_typ_projektu
- heslar_typ_udalosti
- heslar_typ_vyskovy_bod
- heslar_zeme

**Comment by HULD-Lab** [comment]
Shrnuji navržené řešení během schůzky:
1. Vytvořit 1 sekvenci ve staré DB
2. Pro všechny tyto hesláře přidat pole ident_cely a doplnit je hodnotou ze sekvence
3. Opravit migrační skripty tak, aby pole ident_cely se nevytvářelo během migrace ale zapsala se hodnota z DB

**Comment by pbartosova** [comment]
A ještě řešení pro novou DB:
1. Vytvořit sekvenci v nové DB a dát ji počáteční hodnotu +1 než maximum v sekvenci v staré DB.
Nebo raději o něco vyšší ? 
Nevím, jestli nemůže nastat problém při opakované migraci.

**Comment by motyc** [comment]
@pbartosova Tohle by myslím nemělo být potřeba, protože my ve skutečnosti žádnou novou DB nevytváříme. Jen se upravuje migrací tak existující, takže sekvence se prostě přenese, tak jak je (stejně jako v ostatních případech).

**Comment by motyc** [comment]
To je právě to jádro řešení problému. Když se to naplní již v původní databázi, projdu pak migrační skripty a místo mapování id z nové DB, budu používat pro "where" parametry ident_cely, který by měl být unikátní napříč všemi hesláři ve staré i nové verzi. Sloupec puvodni_id bude možné smazat, to si tam dal Juraj asi jako pomocné (jeho smazání bych dal do skriptu s úklidem po migraci).

**Comment by pbartosova** [comment]
V repositáři je připravena větev, která opravuje původní migrace. Samostatně to ale otestovat nejde, aniž by se migrace spouštěly celé znovu, což momentálně nedává smysl.
Zároveň jsou na testu připravené ident_cely v DB + příslušný skript.

**Comment by motyc** [comment]
@pbartosova Provedl jsem testování na test severu desktopové AMČR a vše se zdá být v pořádku funkční. Abych mohl řešit svou část, potřebuji to nejdříve dostat ještě na produkci, protože při aktualizaci skriptů musím pracovat s ident_cely podle produkce. Prosím tedy o nasazení na produkci a následně budu pokračovat úpravou skriptů pro migraci.

**Comment by pbartosova** [comment]
Nasazeno na prodoukci.
Přidání ident_cely v migracích:
https://github.com/ARUP-CAS/aiscr-webamcr/tree/feature/476

**Comment by motyc** [comment]
@pbartosova Je nějaký důvod, proč to nesloučit do dev větve, aby se na to nezapomnělo a nebyl zmatek v tom, co platí? Asi bych to preferoval...
