### ISSUE TITLE
Revize cizich klicu database AMCR

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#48]
Tabulka se vsemi klici nove verze databaze k dnesnimu datu:

https://docs.google.com/spreadsheets/d/198WB6Bgo7ZiSq041RffxSTaq1paATOfpn3RwudTrtM0/edit#gid=1298467805

**Comment by motyc** [comment]
Všechny popsané speciální případy nejsou implementované:

> Existují tři speciální případy:
> 1 - Projekt nejde smazat, dokud neodstraním projektovou dokumentaci (je to speciální jen kvůli tomu, že je tam ta obrácená vazba, jinak by to byl klasický RESTRICT).
> 2 - Pokud mažu dokumentacni_jednotka a ta má vazbu na nepotvrzený PIAN, smazat i tento PIAN.
> 3 - Pokud mažu archeologicky_zaznam, tak:
> 3a - pokud je navázaný dokument nepotvrzený a nemá žádnou další vazbu na archeologicky_zaznam, smazat také dokument (cascade se zde aplikuji standardně v databázi);
> 3b - pokud je navázaný dokument_cast bez vazeb na neident_akce a komponenta_vazby, smazat také dokument_cast (cascade se zde aplikuji standardně v databázi).

**Comment by pesikj** [comment]
Tohle je podle mě možné řešit dvěma způsoby:
- V djangu v navázaných metodách delete.
- Na úrovni databáze s využitím triggerů.
Které řešení je preferované?

**Comment by motyc** [comment]
@pesikj Pokud to jde řešit přímo v DB, preferuji řešení na úrovni DB. Cílem je uchovat konzistenci dat a čím blíže jim to bude, tím lépe.

**Comment by pesikj** [comment]
@motyc Navázaným Dokumentem myslíte dokument navázaný přes model DokumentCast?

**Comment by motyc** [comment]
@pesikj Ano, přesně tak.

**Comment by pbartosova** [comment]
Opět prosím řešit jako reklamaci nebo nový požadavek pro Databázi.

**Comment by pesikj** [comment]
@motyc 
ad 2: Co když je na PIAN navázaná ještě další dokumentační jednotka?

**Comment by pesikj** [comment]
@motyc Body 1 a 2 můžete otestovat.

**Comment by motyc** [comment]
Ve stávající verzi databáze patrně nebyly aplikovány ani revize podle tabulky v úvodním komentáři.

**Comment by pesikj** [comment]
> Ad 2 - aktuální stav (nevím, co je či není nasazeno): -- mažou se i potvrzené PIAN (chyba - mají se jen odpojit) -- když chci smazat akci s potvrzeným PIAN, ke kterému je napojená jiná akce, dostanu error 500 (to ale patrně souvisí s předchozím)
> 
> EDIT: Dívám se na trigger v DB a je to s jistotou špatně (snaží se to mazat vše, bez ohledu na cokoli).

@motyc 
Podmínky v triggeru je - `pian.stav = 1`

```
        BEGIN
            DELETE FROM pian WHERE pian.id = old.pian and pian.stav = 1;
			RETURN NEW;
        END;
```

**Comment by motyc** [comment]
@pesikj Rád bych celé issue otestoval najednou, ale nejsou implementovány některé opravy z tabulky v prvním postu, jak už jsem psal výše. Je potřeba nastavit constrainty podle sloupců "on_update_new" a "on_delete_new". Zdá se, že "on_delete_new" implementuje https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/12_migrace_fk_revision.sql, ale "on_update_new" nikde nastaveno není. Prosím o prověření a případné nasazení.

**Comment by motyc** [comment]
@pbartosova Všechny červené položky v tabulce revidovány a doplněny o popis, nebo odstraněny (něco již bylo vyřešeno, něco souviselo s nepotřebnými/mazanými tabulkami).

**Comment by pbartosova** [comment]
@motyc Prosím o finální potvrzení, že červené položky:
a) tyto constraint nebudeme vytvářet
b) pokud existují, smažeme je.
Děkuji

**Comment by motyc** [comment]
@pbartosova Potvrzuji s poznámkou, že duplicity (viz sloupec "pozn_DN" mazat pouze pokud platí, že jsou opravdu duplicitní a nezměnilo se to.

**Comment by motyc** [comment]
@pbartosova doplněny odpovědi a opraveno

**Comment by pbartosova** [comment]
@motyc  Ještě prosím o potvrzení názvů pro druh nalezu.

**Comment by motyc** [comment]
@pbartosova Vše potvrzuji.

**Comment by pbartosova** [comment]
Děkuji. To jsme měli chyby, které se objevily na DEV.
Teď ještě před sebou máme TEST :)

**Comment by pbartosova** [comment]
Změny provedeny na TESTu.
Migrační skripty jsou v feature/476.

**Comment by pbartosova** [comment]
Pro rekapitulaci: Není jasné, jak bylo zadání vytvořeno. Tabulka mohla vznikat postupně. Není tedy zaručeno, že v tabulce jsou uvedeny všechny constraint, které v DB jsou nebo mají být.

**Comment by motyc** [comment]
@pbartosova Jak na to koukám, tak Juraj to vlastně napsal v tom prvním příspěvku - jde o stav DB k 17.3.2021. Těžko asi stopovat, co vše se od té doby změnilo, ale z hlediska vazeb toho zásadně mnoho nebude. Po další migraci to ale zkusím důsledně prověřit, jestli něco podstatného neuniklo.
