### ISSUE TITLE
Výraznější rozlišení stavu ve stavové liště

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#484]
Ve stavové liště v knihovně 3D je nejasné, který stav je označený, protože se používají jen různé odstíny šedé (http://192.168.254.30:8080/dokument/model/detail/C-3D-202000004): 

![image](https://user-images.githubusercontent.com/20186892/171833781-da82b7fb-f2af-451e-809c-ad81f5ef3158.png)

Jako řešení navrhujeme tučně zvýrazňovat pouze aktivní stav, tedy upravit takto:

![image](https://user-images.githubusercontent.com/20186892/199060743-ff5d4b06-5525-4a52-b991-a406e7c3dc7e.png)

(to by platilo pro všechny stavové lišty, není tedy třeba dělat speciální verzi pro 3D)

**Comment by motyc** [comment]
Nutno kolektivně otestovat a zapsat zjištěné nedostatky na GD - pak to zkonsolidujeme a dáme zpětnou vazbu.

**Comment by motyc** [comment]
Tučně zvýrazňovat pouze aktuální stav

**Comment by motyc** [comment]
Znovu otevírám, bude třeba upravit barvu označující aktivní stav. Stále to není úplně dobře viditelné.

**Comment by jhavrlant** [comment]
@motyc Co takto?
![Image](https://github.com/user-attachments/assets/54aeeab9-f7d6-47ce-8466-889d34e67f30)
![Image](https://github.com/user-attachments/assets/87c57b5c-be3a-4438-b466-3a064f478d56)
![Image](https://github.com/user-attachments/assets/4eb0acd6-2b38-42b7-a14d-e493a07b9b2b)
![Image](https://github.com/user-attachments/assets/2859286d-a58e-4806-a918-62dd952d4ce7)
![Image](https://github.com/user-attachments/assets/f481b445-475a-4caa-b573-77c9d4946613)
![Image](https://github.com/user-attachments/assets/e914b142-1ce2-4ac8-8d74-d010b75273e3)
![Image](https://github.com/user-attachments/assets/8b6dd1d6-f702-4de5-b381-ba8743e71ed1)

**Comment by motyc** [comment]
@jhavrlant To mi přijde v principu dobré, jen bych nechal v takovém případě tu výplň stejnou jako je pozadí (tj. průhlednou, ne bílou) a ohraničení kolečka udělal tak, aby bylo ve výsledku stejně velké jako ta ostatní (při zachování tloušťky ohraničení, jak to máš teď).

**Comment by DanaKriv** [comment]
Vypadá to takhle mnohem lépe, líbí se mi to. Souhlasím s Honzou, že je zapotřebí se zamyslet nad velikostí kolečka a obecně také nad odstupem textu od čísla - když jsi to dal pod sebe, je najednou vidět, jak to na stejných místech odskakuje nejednotně.

**Comment by motyc** [comment]
@DanaKriv To nejednotné "odskočení" je dané výpočtem na dané stránce a souvisí i s názvy stavů. To nemá smysl řešit. Jde teď čistě o to, aby to bylo lépe vidět.

**Comment by motyc** [comment]
@jhavrlant Ano, takto za mne perfekt! Díky.

**Comment by DanaKriv** [comment]
Za mě také OK!
