### ISSUE TITLE
Problém s tlačítkem pro editaci u projektu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#485]
> @jnihnat
> 
> > * Při najetí na tlačítko pro editaci se tooltip zobrazí přes tlačítko, na které pak nejde kliknout. Navíc to vede někdy zacyklení, kdy se při najetí na levou polovinu tlačítka tooltip zběsile začne obnovovat (mizet a zobrazovat se - hlavně v Chrome, v Mozille také, ale není to tak frenetické).
![image](https://user-images.githubusercontent.com/20186892/168613457-5ea1adb7-7945-40c6-8b5c-310cd5f3ddb9.png)
> > 
> > Kvuli problikavani som pridal offset pro tolltip 1px hore, vidiet to nie je a malo by to pomoct. Co sa tyka zobrazenia tooltipu cez Tlacitko, tak to sa u mna nedeje (vyskusany chrome aj mozila). Skuste prosim pre istotu premazat cache. Nic sa kolo tooltipov a css ani nemenilo, tak mi to je zvlastne zeby sa nieco take malo zacat diat...
> 
> Cache vymazána, děje se stále stejně: https://user-images.githubusercontent.com/20186892/171836677-e97b33cc-0f2b-4478-a90d-a20bd2bddc5d.mp4

@motyc navrhuji z toho udelat samostatne issue, mne to porad nasimulovat nejde a to somskusil uz i Edge...
Muzu poprosit jeste verzi prohlizece? Taky kdyby to skusili vasi kolegove nasimulovat u nich, ci se nehonime jen za jednym pripadem u vas.
Problem je v tom, ze z nejakeho duvodu se ten tooltip zakotvi dole a nie hore, pricom cele tohle se dela pres bootstrap co pouzivame, nic nami vyvinuteho.

_Originally posted by @jnihnat in https://github.com/ARUP-CAS/aiscr-webamcr/issues/461#issuecomment-1145863466_

**Comment by motyc** [comment]
@jnihnat Asi jsem na to přišel - musí jít o projekt ve stavu P8, kde je v liště s historií aktivní/vyplněná část "Zrušen". Myslím, že tím vzniká ta kolize. Lze testovat konkrétně na https://wamcr-test.aiscr.cz/projekt/detail/C-200810782

Testováno na dvou různých PC doma a v práci, v obou případech je chování shodné. V obou případech Chrome Verze 102.0.5005.63 (Oficiální sestavení) (64bitový)

**Comment by jnihnat** [comment]
opraveno spolu s #356
