### ISSUE TITLE
Revize mapového prostředí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#49]
### Aktuálně k dodělání:
**PAS**
- [x] #235
- [ ] - zásadní odchylka v transformacích souřadnic S-JTSK -> WGS-84 (až 10 m); při zadání WGS-84 poloha sedí, a to včetně převodu WGS-84 -> S-JTSK; zde srovnání správné polohy v GIS a chybné v aplikaci:
![image](https://user-images.githubusercontent.com/20186892/136557608-51a6fa8c-a4a3-405b-a20d-0d67e9116d64.png)

Dokument se zápisem poznámek dostupný zde: https://docs.google.com/document/d/1ll-i-RZVxzp_LHIArJ74kS035akV7i_dNfI59XFjHIU/edit

**Comment by pbartosova** [comment]
Tasky s označením 🙏 Navrhuji řešit jako rozšíření, protože se jedná o nové funkcionality oproti původní AMČR.

**Comment by motyc** [comment]
Ad problém s výběrem při překryvu - bohužel není úplně pravda, že to funguje dobře; funguje to jen při správném pořadí prvků při vykreslování; nevím, podle jakého klíče se prvky řadí, ale když je menší plocha nahoře, funguje, to; když je dole, tak už nikoli. Problém asi bude i v případě, kdy na sobě bude více než dva prvky. V podstatě myslím, že to nejde řešit úplně automaticky a že bude nutné na kliknutí nabídnout dotaz, co chci vlastně vybrat. 

K tomu by právě mohly sloužit ty zavíratelné popisky v pop-up: ![image](https://user-images.githubusercontent.com/20186892/134670341-38dec65e-27d5-482a-9d60-684c69ab8e11.png), místo automatických tooltipů: ![image](https://user-images.githubusercontent.com/20186892/134670450-2c35d137-a5db-46de-9949-00bce113eeed.png)

Problém je dobře vidět třeba na Pražském hradě:
![image](https://user-images.githubusercontent.com/20186892/134669944-7f35b340-7bca-4e25-895b-d32bb5b35320.png)


Ad odložení dvou označených úkolů - ok, souhlasím a přesouvám zpět do dokumentu na GD

**Comment by pbartosova** [comment]
S tím výběrem jsme asi za hranou technologie a vždycky budou situace, které budou špatně řešitelné. U stávající aplikace taky není chování jednotné. při práci jsme se dostávali do situací, kdy stačí kliknout kamkoliv do mapy a vybere se nejbližší pian, naopak když kliknu přesně na nějakou geometrii dostanu na výběr z pianů z celého výřezu, nebo klikám a mapa se jen znova načte bez jakéhokoliv výběru. Je to situace, která je problematická všude a my děláme maximum.

**Comment by motyc** [comment]
Ve stávajícím řešení se v bere v potaz ještě přesnost PIAN (vyhledává se nad bufferem kolem PIAN, nikoli nad samotnou geometrií PIAN). To jsme naopak nyní už ani nechtěli implementovat a proto může připadat, že se mapa v původní AMČR chová neočekávaně. To, že má jít každý PIAN z mapy vybrat je nutnost a nějaká cesta, jak to udělat být musí, tento požadavek byl známý od první chvíle. Je tedy třeba najít schůdné řešení, které technologická omezení obejde. Můj návrh je, řešit to přes ty pop-up popisky (myšlenku mohu vysvětlit blíže, ale chce si to zavolat nad sdílenou obrazovkou). Jiné alternativy klidně navrhněte z vaší strany. Že to prostě nepůjde, alternativa není.

**Comment by motyc** [comment]
Ad problém zoomu na PIAN - ok, rozumím, že zoom na celé linie/polygony je problém; stačí tedy alespoň změnit to měřítko, ať to není tak moc přiblížené (v tomto duchu upravuji task)

Ad popisky - souvisí s problematikou výběru, takže se to tak souběžně i řešme (tj. domluvíme se).

**Comment by pbartosova** [comment]
V krajní nouzi jde vybrat PIAN vždy přes dropdownlist dole.

**Comment by motyc** [comment]
Taky mě to napadlo, ale když neznám jeho číslo (neumím zobrazit ani popisek), tak ho těžko můžu vybrat... Proto spolu tyhle dva problémy tolik souvisí.

**Comment by motyc** [comment]
Dále řešeno v rámci #305
