### ISSUE TITLE
Umožnit archiváři a adminovi přidat oznamovatele, pokud neexistuje

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#506]
Pokud je automaticky odstraněn oznamovatel, již nejde přidat. To je třeba umožnit archiváři a adminovi ve stavech P1-P5.
- [x] Pokud oznamovatel chybí a jde o projekt typu záchranný, v daných stavech přidat do menu "Další volby" položku "Přidat oznamovatele"
- [x] Pro zápis použít obdobu http://192.168.254.30:8080/projekt/oznamovatel/edit/ (včetně validací atd.)

**Comment by pesikj** [comment]
@motyc 
- Ovlivní to nějak stávající možnost editace oznamovatele?

**Comment by motyc** [comment]
@pesikj Ne.

**Comment by motyc** [comment]
### Výsledek testu
V menu volbu nevidím (http://192.168.254.30:8080/projekt/detail/C-202001174), i když podmínky jsou splněny. Neumím tedy testovat.
![image](https://user-images.githubusercontent.com/20186892/203557587-bc8a30fb-54b3-4088-885a-f8d296b080e5.png)

**Comment by jnihnat** [comment]
@motyc Momentalne mame nastavene podminky:
if projekt.typ_projektu.id == TYP_PROJEKTU_ZACHRANNY_ID:
        if user.hlavni_role == archivar_group or user.hlavni_role == admin_group:
            if not projekt.has_oznamovatel():
                if PROJEKT_STAV_ZAPSANY < projekt.stav < PROJEKT_STAV_UZAVRENY:
                    show_pridat_oznamovatele = True
a co tak koukam jeste do kodu, tak kontrola na stav mnela byt < ARCHIVOVANY a ne uzavreny.
je to tak?

**Comment by motyc** [comment]
@jnihnat Ano, přesně tak, v tom bude ten problém. Ale chyba je i z opačné strany. Mělo by to být `PROJEKT_STAV_ZAPSANY <= projekt.stav <= PROJEKT_STAV_UZAVRENY`
