### ISSUE TITLE
U projektu doplnit možnost filtrace podle historie akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#507]
Řešeno obdobně jako vyhledávání historie projektu (samostatný oddíl za filtrací podle akce).

Týká se http://192.168.254.30:8080/projekt/vyber (zařadit za oddíl "Výběr podle akcí")

**Comment by pesikj** [comment]
@motyc Má jít o obdobu stejného menu u Knihovny 3D? Pole mají být stejná, či má nějaké pole být navíc či naopak chybět? Pro výběr uživatele má být použit stejný našeptávač, nebo jiný?

![image](https://user-images.githubusercontent.com/15179154/181749941-31d6856d-c7fe-4d71-b100-331b5e60ed16.png)

**Comment by motyc** [comment]
@pesikj Ano, jde o ekvivalent. Pole budou stejná, našeptávač "Změna stavu" bude obsahovat pouze hodnoty relevantní pro historii akce. Našeptávač pro uživatele bude stejný.
