### ISSUE TITLE
Nedostupný text v uzamčených polích ve formulářích

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#513]
pokud je pole ve formuláři neaktivní a text se do něj nevejde celý, neexistuje cesta jak si zbylou část textu zobrazit - nutno vyřešit buď možností posunu, nebo tooltipem

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Vím, že toto už jsme řešili někdy loni, tuším, že na tom pracoval @jnihnat, nepamatuješ si to Honzo?

**Comment by jnihnat** [comment]
@motyc muzete prosim uvest priklad kde se to presne deje?
Ja to skusel u projektu na "Uzivatelske oznaceni" a tam pokud to oznacuju tak text se posouva. Souhlasim ze to asi neni nejlepsi reseni, ale tohle aspon funguje.
Muzeme se pak domluvit dodelat na vsechny detaily pro readonly polia tooltip jak je napr. u tabulkach.

**Comment by motyc** [comment]
@pesikj To posouvání v poli stačí, ale někde mi to nefungovalo a myslel jsem, že to nejde nikde. Musíme to otestovat přesněji a dáme zpětnou vazbu konkrétně, zatím lze odložit.

**Comment by motyc** [comment]
@svejci Ondro, až budeš mít chvilku, prosím o test, kde se to děje. Jde o to, že když jsou některá pole zašedlá a text je moc dlouhý, nejde se dostat na zbytek. Je to ale jen někde. Bude to třeba zas systematicky projít a otestovat...

**Comment by motyc** [comment]
@svejci Díky moc. Přísahám bohu, že mi to v nějakém případě nešlo, ale teď jsem také na nic nenarazil. Issue tedy zavírám a vrátíme se k tomu, pokud bychom něco objevili.
