### ISSUE TITLE
Revize oddělovačů v polích s více hodnotami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#514]
oddělovač více položek v jednom poli (aktivity, posudky, autoři…) je většinou mezera + čárka (",")  (musí to být opačně a navíc to není dobré u autorů dokumentu - raději užívat jako oddělovač středník (";")). Např. při zápisu Dokumenty – Autoři nebo Posudky je pořadí čárka a mezera, ale po uložení záznamu se to změní naopak; u Komponenty – Aktivity se to po zápisu nezměnilo, ale v https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201447903A je to chybně

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Bylo v nějakém issue definováno, jaké oddělovače mají být používány? Pokud ne, jde o požadavek na změnu.

**Comment by motyc** [comment]
@pesikj Tady jde trošku o dědictví minulosti, kdy jsme se odvolávali na fungování desktop aplikace. Je to tedy sice na hraně, ale i přes chybějící zadání považuji za problém to, že se to chová pokaždé jinak, a to i v rámci jednoho pole. Jako obvykle také platí, že v případě pochyb může padnout dotaz, jak to řešit správně, k čemuž nedošlo. Navíc mezera + čárka je špatně i gramaticky.

**Comment by motyc** [comment]
@MaxKosta Prošel jsem všechny formuláře a vyplynulo z toho následující. Vyložená chyba nastává ve dvojím smyslu:
- [ ] u pole "autoři" je oddělovač zaměnitelný s vlastním obsahem dat, takže nejde rozlišit, kde končí jedno jméno a začíná druhé:
/dokument/edit/<str:ident_cely> - Autoři
/dokument/edit/<str:ident_cely> - Dokumentované osoby
/dokument/model/zapsat + /dokument/model/edit/<str:ident_cely> - Autoři
/dokument/zapsat/do-akce/<str:arch_z_ident_cely> + /dokument/zapsat/do-projektu/<str:proj_ident_cely> - Autoři

- [ ] v některých zobrazeních se používá oddělovač " ," (mezera + čárka), který je gramaticky nesmyslný (patrně půjde o všechny případy, kdy je pole uzamčené/zobrazuje se jako input a ne select):
/dokument/detail/<str:ident_cely> - Autoři
/dokument/detail/<str:ident_cely> - Dokumentované osoby
/dokument/detail/<str:ident_cely> - Jazyky
/dokument/detail/<str:ident_cely> - Posudky
/dokument/model/detail/<str:ident_cely> - Autoři

V obecné rovině by bylo nejlepší jednotně jako oddělovač hodnot používat "; " (středník + mezera), pokud to tedy jde snadno nastavit obecně, prosím, udělejme to a vyřeší se tím oba předchozí body.

**Comment by pesikj** [comment]
@MaxKosta Jaký je stav tohoto issue? Je pro tebe nyní zadání dostačující?
