### ISSUE TITLE
Chyba tooltipu tlačítek u tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#515]
Tooltip pro Zobrazení sloupců a Export (Další nabídka…) u tabulek – pokud kliknu 2x na rozbalit (rozbalit, sbalit), zůstane na obrazovce a v tomto konkrétním případě se pak nápovědy navzájem překrývají

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Zde souhlasím, že jde o bug.

**Comment by pesikj** [comment]
@motyc Podařilo se mi issue nasimulovat, podle mě to není vyloženě priorita (podle mě se to projeví v minimálním počtu případů), navrhuji opravu během léta.

**Comment by motyc** [comment]
@pesikj Souhlasím

**Comment by motyc** [comment]
### Výsledky testování
Po celkové revizi odhaleno několik míst, kde tooltipy chybí:
/accounts/login/	Email
/accounts/login/	Heslo
/accounts/password_reset/	E-mail
/arch-z/akce/pripojit/dokument/<str:arch_z_ident_cely> + /projekt/pripojit/dokument/<str:proj_ident_cely>	Vyberte dokument k připojení
/dokument/edit/<str:ident_cely>	Řada
/pas/spoluprace/zadost	Text
/projekt/navrhnout-ke-zruseni/<str:ident_cely>	navrhzruseni.projektId
/projekt/navrhnout-ke-zruseni/<str:ident_cely>	navrhzruseni.vlastniduvod
/projekt/zrusit/<str:ident_cely>		zruseni.duvod

Celkový přehled zde: https://docs.google.com/spreadsheets/d/1LPR3hq6ejnYwfWJOECGuROES8ZHaJqasnC2-wGfMBFk/edit#gid=0

**Comment by motyc** [comment]
Chování zůstalo chybné ještě na http://192.168.254.30:8080/pas/spoluprace/vyber (jinde ok)

**Comment by sedmar** [comment]
Opět bude přesunuto do backlogu #4

**Comment by motyc** [comment]
@sedmar Ano, bez problémů.

**Comment by jnihnat** [comment]
@motyc muzete prosim pro jistotu otestovat jeste jednou mne se to nedari nasimulovat. Pripadne @pesikj jak se to podarilo tebe, pamatujes si?

**Comment by motyc** [comment]
@jnihnat Také se mi již nedaří nasimulovat. Buď to někdo opravil, nebo to byl problém cache. Zavírám
