### ISSUE TITLE
Chyba ověření datumů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#516]
I když je v polích s datumy při zadávání zobrazena šablona dd.mm.rrrr, formulář akceptuje i hodnoty dd.mm.rrrrr (tedy více číslic v roce než čtyři)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Znamená to tedy, že rok má být omezen na čtyři číslice?

**Comment by motyc** [comment]
@pesikj ano, jinak to neodpovídá schématu `rrrr`. Zabráníme tím některým překlepům...

**Comment by jnihnat** [comment]
nastaveno max date na 2100

**Comment by motyc** [comment]
### Výsledek testu
- [ ] ověření funguje všude kromě modal oken (např. posun P23 a P34)

**Comment by pesikj** [comment]
@jnihnat Honzo, podívej se na to, prosím.
