### ISSUE TITLE
Chyba grafiky výběru vrstev v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#517]
Výběr vrstev v PAS a Knihovně 3D je tučně (je jiný než v Projektech a Akcích)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Chápu správně, že se to týká mapy?

**Comment by motyc** [comment]
@pesikj Ano
![image](https://user-images.githubusercontent.com/20186892/175425364-480e40d0-6a8f-48c8-9189-d291359ab99d.png)

**Comment by pesikj** [comment]
@jiri-bartos-huld Jirko, prosím o analýzu současného stavu a návrhu řešení.

**Comment by motyc** [comment]
@pesikj @jiri-bartos-huld Za mne to stačí sladit s tímto:
![image](https://user-images.githubusercontent.com/20186892/175532653-70b39d49-a934-4492-8335-59fabf48506d.png)
