### ISSUE TITLE
Chyby při nahrávání souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#518]
https://wamcr-test.aiscr.cz/oznameni/
- [x] (aktualizováno 3.6.) Funguje chybně nahrávání souborů přes oznamovací formulář. Vše proběhne zdánlivě v pořádku, ale soubor se stejně neuloží (zde nahráno, ale soubor chybí: https://wamcr-test.aiscr.cz/projekt/detail/X-C-001276734). Hláška v Chrome se již zobrazuje korektně. EDIT: 14.6. - chování je opět stejné jako před nahráním předchozí verze (divná hláška v Chrome a nic se nenahraje; viz historie tohoto [postu](https://github.com/ARUP-CAS/aiscr-webamcr/issues/461))

https://wamcr-test.aiscr.cz/nahrat-soubor/projekt/C-201337799
- [x] pokud k projektu nahraji soubor a na téže stránce kliknu na odstranit, soubor se k projektu stejně přidá; asi bude stejné i pro další míst s nahráváním souborů (opravit všude)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Navrhuji odebrat odkaz "Odstranit soubor", k mazání souborů slouží samostatná obrazovka. Pokud by měl mít uživatel možnost odstranit soubor i z dropzone, je to požadavek na změnu.

**Comment by motyc** [comment]
@pesikj Vysvětlím situaci a proč navržené řešení není dobré:
- s užitím dropzone vznikl trošku zmatek v tom, kdy se soubor skutečně nahrává na server a do kdy jde jen o výběr souborů k nahrání; osobně jsem to vždy bral tak, že soubory se nahrávají až přes kliknutí na "dokončit", což se ale zjevně neděje  a vidím to jako nezamýšlenou chybu designu, kterou musíme ještě vyřešit (viz #539)
- je obvyklé, že po volbě souboru má uživatel ještě možnost volbu upravit, opravit chybu atd.; to jde nyní trošku kostrbatě udělat u dokumentů, v PAS či v editaci projektu, kde to ale jednoznačně nejde a je to velký problém je oznamování projektů, kde se nepřihlášený uživatel do editace projektu již nikdy nedostane; právě proto jsme možnost odstranit do dropzone zaváděli (viz #122)

Požadavek odstraňovat pře dropzone tak není určitě požadavek na změnu (funkce byla zavedena cíleně), problém je, že nefunguje dobře. Zároveň je ale třeba revidovat i samotnou filozofii nahrávání, což jako změnu beru, ale není to předmětem tohoto issue.

**Comment by jnihnat** [comment]
opraveno v #548

**Comment by pesikj** [comment]
@jnihnat Super, díky

**Comment by motyc** [comment]
@pesikj Diskusi k dropzone bych nechal na #539. Přikláním se k tomu řešení s tmp, ale to se ještě domluvíme.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] chybové hlášky vypadají normálně a soubory se nahrávají všude, s výjimkou http://192.168.254.30:8080/oznameni/
- [ ] s odstraňováním se nic nezměnilo

**Comment by jnihnat** [comment]
@pesikj kdy probehlo prosim posledni nasazeni? Se mi zda ze jeste pred opravou. Vdaka

**Comment by pesikj** [comment]
@jnihnat Cca před 2 hodinami.

**Comment by jnihnat** [comment]
@motyc muzu poprosit jeste o jeden test? Skusil som a mne funguji obe veci, jak nahrani tak smazani. Pripadne prosim o soubor ktery nejde nahrat, mozna je to problem souboru.

**Comment by motyc** [comment]
@jnihnat Otestováno.
Nahráváno přes: http://192.168.254.30:8080/oznameni/
Výsledkem je: http://192.168.254.30:8080/projekt/detail/X-C-001276749

Použité soubory:
- [NÁLEZOVKA DN.pdf](https://github.com/ARUP-CAS/aiscr-webamcr/files/9000145/NALEZOVKA.DN.pdf)
- ![Invenio](https://user-images.githubusercontent.com/20186892/176157655-f32b85cd-d90f-424d-866d-308869078b9c.jpg)

Ani jeden v projektu není.

**Comment by jnihnat** [comment]
na nahravani som nasel chybu, mam pripravenu opravu. To mazani z dropzone vam stale nefunguje taky?

**Comment by motyc** [comment]
@jnihnat Při posledním testu ke dni reportu nefungovalo.

**Comment by jnihnat** [comment]
tak pokud som to dobre nasel, tak to mazani nefungovalo jen pro duplicity. Opravena oba issue, mazani i upload u oznameni.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] funkčně je vše ok, jen když použiji tlačítko "Odstranit" v dorpzone, po přechodu na další obrazovku (jak přes "Dokončit" např. z http://192.168.254.30:8080/nahrat-soubor/projekt/X-C-001276753, tak při dalším kroku na http://192.168.254.30:8080/oznameni/) se zobrazí hláška "Záznam úspěšně smazán". To je extrémně matoucí, zvláště při tom odeslání oznámení - hlášku zobrazit ihned, nebo vůbec.
