### ISSUE TITLE
Chyba přidávání samostatných nálezů k projektu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#519]
https://wamcr-test.aiscr.cz/projekt/detail/C-202004679
- [x] Tlačítko pro přidání sam. nálezu nefunguje
- [x] jeho užití je logické pouze pro P3-P5, jinak nezobrazovat

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Chápu správně, že zadání obsahuje dva různé úkoly - nefunkční tlačítko a požadavek na skrytí tlačítka? První požadavek je bug. U druhého nevím, zda bylo skrytí tlačítka někdy požadováno. Pokud ne, je to požadavek na změnu.

**Comment by motyc** [comment]
@pesikj Problém je v tom, že s tím tlačítkem jsme v designu vůbec nepočítali a objevilo se tam na základě vývoje ze strany Huld. Nepřijde mi to jako špatné, ale musí být v logice aplikace - tj. mělo by fungovat, a to ve stavech, kdy nálezy z principu (viz fungování modulu PAS) lze k projektům připojovat.

**Comment by pesikj** [comment]
@motyc A co konkrétně má tlačítko dělat? Má otevřít stránku http://192.168.254.30:8080/pas/zapsat? Má být něco předvyplněno?

**Comment by motyc** [comment]
@pesikj Ano, s předvyplněným polem "projekt".

**Comment by pesikj** [comment]
@jnihnat Honzo, požadované chování tlačítka je vysvětleno v posledním komentáři od @motyc.
