### ISSUE TITLE
Chyby při řazení tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#520]
- [x] https://wamcr-test.aiscr.cz/projekt/vyber?sort=organizace
- [x] https://wamcr-test.aiscr.cz/pas/spoluprace/vyber?sort=organizace_vedouci
- [x] https://wamcr-test.aiscr.cz/pas/spoluprace/vyber?sort=organizace_spolupracovnik
- [x] https://wamcr-test.aiscr.cz/pas/vyber?sort=predano_organizace

https://wamcr-test.aiscr.cz/pas/spoluprace/vyber
- [x] řazení podle sloupce "historie" nedává smysl, vypnout

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Souhlasím, že jde o bug.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] vše funguje, jen nadpis sloupce Historie na https://wamcr-test.aiscr.cz/pas/spoluprace/vyber je najednou černým písmem
