### ISSUE TITLE
Problémy s PIAN

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#522]
https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-200913623C
- [x] “Připojit PIAN z mapy” - při použití pro D02 se PIAN sice doplní do formuláře, ale po uložení změn se změny neuloží.
- [x] Jakékoli použití tlačítka "Uložit změny" vede k odpojení PIAN od D01.
- [x] již vytvořený PIAN nejde smazat - při kliknutí sice PIAN zmizí, ale tlačítko dokončit je neaktivní. Kliknutí na tvorbu nové geometrie vrátí původní PIAN, u bodového PIAN nezmizí ani značka

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Souhlasím, že jde o bug.

**Comment by jiri-bartos-huld** [comment]
Oprava 1+2

https://user-images.githubusercontent.com/77389730/178471332-a53a2c4c-4cef-480c-9ba6-1029ea37de80.mp4

**Comment by jiri-bartos-huld** [comment]
@motyc 
Dobry den, priznavam se ze nechapu zadani 3 bodu:
"již vytvořený PIAN nejde smazat - při kliknutí sice PIAN zmizí, ale tlačítko dokončit je neaktivní. Kliknutí na tvorbu nové geometrie vrátí původní PIAN, u bodového PIAN nezmizí ani značka"

V nasledujicim videu mam 2 vytvorene piany oba nepotvrzene (jednou polygon a jednou marker) a oba jdou pri editaci smazat+zadat novy marker/polygon.

https://user-images.githubusercontent.com/77389730/178472826-88b30e02-6e19-4813-9625-68b49719ac90.mp4

**Comment by motyc** [comment]
@jiri-bartos-huld Problém je staršího data a teď při testování se mi zdá být vše v pořádku. Asi to byla nějaká dočasná věc. S těmi tlačítky "Dokonči" byl nějaký problém, který jsme opravovali jinde.
