### ISSUE TITLE
Problém s dobou načítání akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#523]
https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201556939A
načítání záznamu trvá extrémně dlouho, selže (prázdná obrazovka), nebo se s obrazovkou nedá pracovat; pravdpodobně je důvodem vyšší množství DJ/komponent/ADB

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Jedná se o optimalizaci databáze. Pokud nebyla v nějaké předchozí objednávce, nejedná se o bug.

**Comment by motyc** [comment]
@pesikj Nesouhlasím s tím, že pokud aplikace nedokáže podat odpověď ve standardní (nikoli chybové) situaci, že nejde o bug. Objem dat je od počátku jasný a je třeba aplikaci psát tak, aby se dokázala s daty vyrovnat, případně na omezení upozornit a navrhnout včas řešení.

**Comment by pesikj** [comment]
@motyc Vyzkoušel jsem tu konkrétní stránku a otevřela se zcela bez problémů. Načítání stránky trvalo o něco déle, ale stránka se načetla. Rozhodně tedy není pravda, že aplikace nedokáže podat odpověď.

Je možné, že důvodem dlouhého načítání není databáze (objem dat zde není nijak velký), ale renderování stránky. Pro každou DJ je potřeba vyrenderovat formulář, který je skrytý a zobrazí se po kliknutí. Optimalizace by v zásadě znamenala, že je potřeba celou stránku přeprogramovat. Další možností je problém s mapou. V každém případě je to záležitost optimalizace aplikace.

Prosím ještě @ScottVanWagenen o reakci.

**Comment by motyc** [comment]
@pesikj Netrvám na tom, že to musíme vyřešit hned. Nechme to na diskusi, jak tento problém řešit a domluvíme se pak i na případných nákladech. Akce se po čase skutečně načte, ale i chování stránky je takové, že s ní v podstatě nejde pracovat. Dám to mezi issue k diskusi.

**Comment by pesikj** [comment]
@motyc Dobře, souhlasím. Rovnou se zeptám: Řešení, aby se formuláře k DJ otevíraly na samostatné stránce, není přijatelné?

**Comment by motyc** [comment]
@pesikj Tomu jsme se snažili vyhnout. Jde o to, že při práci potřebuji průběžně koukat do mapy a překlikávat mezi DJ.

**Comment by pesikj** [comment]
@motyc To v zásadě není problém, ani když bude formulář na samostatné stránce. Překlikávání taky ne, odkazy není problém na stránku dát. Jde především o renderování formulářů, i když je reálně zobrazen vždy jen jeden.

**Comment by motyc** [comment]
@pesikj Asi si to budeme muset na schůzce nějak konkrétněji vysvětlit, jak by se to chovalo. Takto si nejsem jistý a nechci pálit od boku. Jen bychom se měli domluvit před implementací #319 a #318, protože tam se bude daná obrazovka replikovat/opakovaně užívat. Zařadím toto issue do Sprintu 4, aby to nezapadlo.

**Comment by pesikj** [comment]
Je třeba navrhnout varianty řešení.

**Comment by pesikj** [comment]
Návrh řešení:
> Obrazovka s velkým množstvím DJ: namísto renderování a skrývání formulářů renderovat vždy jen aktivní formulář, kliknutí na odkaz vždy načte stránku znovu s vyrenderovaným jiným formulářem.

Musí projít analýzou, zda to pomůže.

**Comment by pesikj** [comment]
@jiri-bartos-huld Jsou informace na mapě nějak navázané na formuláře DJ?

**Comment by pesikj** [comment]
@motyc 
Přidávání komponent funguje, viz http://192.168.254.30:8080/arch-z/akce/detail/C-201556939A/dj/C-201556939A-D06/komponenta/detail/C-201556939A-K023

Chyba 500 byla zřejmě způsobena nějakým problémem s databází, který byl mezitím opraven. Prosím o nový test. Děkuji.

**Comment by motyc** [comment]
@pesikj Jestli jsem ten error 500 měl testovat nyní, tak teď jej dostávám již při snaze přejít na http://192.168.254.30:8080/arch-z/akce/detail/C-201556939A

**Comment by pesikj** [comment]
@motyc To je v důsledku přejmenování podle v databázi ze stav_stary na stav, to bude opraveno při dalším deploymentu.
