### ISSUE TITLE
Obrácená šipka u tlačítka odeslat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#524]
tlačítko “Odeslat” u akce má šipku doleva, což je nesmysl

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Prosím o bližší specifikaci, o jaké tlačítko konkrétně jde.

**Comment by motyc** [comment]
@pesikj https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-201700006A
![image](https://user-images.githubusercontent.com/20186892/175425814-2efc8b33-3b3d-4b51-b210-57a5dacebf75.png)

**Comment by pesikj** [comment]
@motyc A preferujete jinou ikonu, nebo tlačítko zcela bez ikony?

**Comment by motyc** [comment]
@pesikj stačí tu šipku otočit obráceně :)

**Comment by jnihnat** [comment]
@motyc navrhl bych tam tohle "send" Klidne pak bych upravil i u ostatnich tlacitek "Odeslat"
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asend%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by motyc** [comment]
@jnihnat Ano, souhlasím, díky.
