### ISSUE TITLE
Chyby při práci s DJ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#527]
https://wamcr-test.aiscr.cz/arch-z/akce/detail/C-202105596C
- [x] když mám již vytvořenou jednu DJ (negativní) a vytvořím druhou, která má být pozitivní, tak při pokusu o uložení vyskočí chyba 500 (6.6.2022 ve 11:25) - _nedaří se reprodukovat_
- [x] stejně tak, pokud změním např. původně negativní DJ na pozitivní a pokusím se připojit komponentu (6.6.2022, 11:26)
- [x] při pokusu připojit komponentu k D02 error 500 (14.6. 21:58)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Souhlasím, že jde o bug.

**Comment by motyc** [comment]
@pesikj Bod 1 se mi teď reprodukovat nepodařilo, ale bod 2 ano. Postup:
- vytvořena http://192.168.254.30:8080/id/C-202105596C-D02 jako negativní
- změněna na pozitivní a změny uloženy
- přidána komponenta a změny uloženy -> error 500 (12.7. 12:42) - k DJ nejde ani poté komponentu přidat

**Comment by svejci** [comment]
Pokusil jsem se teď ještě jednou reprodukovat bod 1, protože tato chyba se vyskytla při testování u mě, ale žádnou zvolenou kombinací postupu se mi ho nyní také nepodařilo reprodukovat.

**Comment by pesikj** [comment]
@motyc Děkuji, nasimulovat se mi to již podařilo. Problém byl v tom, že zřejmě došlo k chybě při smazání komponenty a ta tedy stále existovala a chyba byla způsobená duplicitou v ident_cely u komponenty. Podle mě to s negativitou DJ nesouvisí. Zkusil jsem teď vytvořit a smazat komponentu a vše proběhlo ok.

**Comment by pesikj** [comment]
@motyc Bod 3 byl zřejmě důsledkem stejné chyby. Mazání komponent jsem testoval opakovaně a funguje ok. Podle mě byla příčina stejná, navrhuji toto issue uzavřít.
