### ISSUE TITLE
PAS - problém s filtrací spolupráce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#528]
https://wamcr-test.aiscr.cz/pas/spoluprace/vyber
filtrace podle vedoucího nefunguje správně (nemohu najít uživatele, kteří určitě existují a jsou i v tabulce); celé pole je však zvláštní (měl by asi být asynchronní heslář jako u projektů)

Např.: Mařík, Jan (U-000328)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Souhlasím, že toto je bug.

**Comment by pesikj** [comment]
@jnihnat Honzo, chyba bude možná někde v API, začal bych pátrat tam.
