### ISSUE TITLE
Chyby zarovnání tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#529]
https://wamcr-test.aiscr.cz/pas/spoluprace/vyber
chybné vertikální zarovnání řádků v tabulce (není na střed - děje se i jinde)

Týká se většiny polí. Mělo by to být vertikálně na střed, což jsou v daném případě jen tři poslední sloupce:
![image](https://user-images.githubusercontent.com/20186892/171834524-a62a6339-bf2b-407a-8f9d-861ffd42121d.png)

u ostatních polí jsme to pouze přehlédli, nyní je to dobře vidět, protože se to chová různě (viz screenshot výše)

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Je někde definováno, jak má zarovnání vypadat? Má být opravdu vše na střed, nebo jsou tam nějaká pravidla?

**Comment by pesikj** [comment]
@motyc Souhlasím, takto je to v pohodě.

**Comment by jnihnat** [comment]
snazil som se to opravit vsude, snad se mi to povedalo, pokud ne napiste prosim kde to bude jeste chybet. Dekuji.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] na http://192.168.254.30:8080/pas/spoluprace/vyber je to stále rozhozené (výška řádku se navíc liší od všech ostatních tabulek, kde to teď vypadá dobře)
![image](https://user-images.githubusercontent.com/20186892/176880345-a53ea2fd-38d8-4945-837a-b1b969bf55a2.png)
