### ISSUE TITLE
Odstraňovat prázdné složky z úložiště

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#531]
Pokud dojde ke smazání souboru, měla by se provést kontrola, zda je složka na FTP prázdná a pokud ano, smazat se rovněž až do úrovně, kde ve složce jsou nějaké soubory či složky.

**Comment by pesikj** [comment]
@motyc Nebylo by lepší provádět mazání prázdných složek v pravidelných intervalech, např. denně? Provádět kontrolu adresáře po každém mazání není úplně efektivní a čistě teoreticky by mohlo dojít ke konfliktu, kdy jeden uživatel ze složky soubor smaže a jiný tam současně bude něco nahrávat.

**Comment by motyc** [comment]
@pesikj Ano, s tím nemám problém. Issue tedy zruším a dám to mezi automatické úlohy do #387
