### ISSUE TITLE
Potvrzení o nahrání souboru

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#539]
Nahrávání souborů proběhne hned, nikoli až po kliknutí na "Dokončit". To může být matoucí, protože pak nemá žádný smysl mít na těchto obrazovkách tlačítko "Zpět" i "Dokončit" zároveň. Řešením je:

- [x] odstranit tlačítka "Zpět" na obrazovkách pro nahrávání souborů a nechat pouze "Dokončit"
-- /nahrat-soubor/dokument/<str:ident_cely>
-- /nahrat-soubor/dokument/nahradit/<int:file_id>
-- /nahrat-soubor/pas/<str:ident_cely>
-- /nahrat-soubor/pas/nahradit/<int:file_id>
-- /nahrat-soubor/projekt/<str:ident_cely>
-- /nahrat-soubor/projekt/nahradit/<int:file_id>
- [x] doplnit k dropzone tooltip, kde vysvětlíme její chování
-- /oznameni/
-- /nahrat-soubor/dokument/<str:ident_cely>
-- /nahrat-soubor/dokument/nahradit/<int:file_id>
-- /nahrat-soubor/pas/<str:ident_cely>
-- /nahrat-soubor/pas/nahradit/<int:file_id>
-- /nahrat-soubor/projekt/<str:ident_cely>
-- /nahrat-soubor/projekt/nahradit/<int:file_id>

**Comment by jnihnat** [comment]
to odesilani by nejspis slo udelat asi i po stisknuti na tlacitko dokoncit: https://stackoverflow.com/questions/46728205/dropzone-submit-button-on-upload
akurat nevim jak by se to chovalo pri chybach vracenych ze serveru.

**Comment by pesikj** [comment]
@motyc Řešení, které navrhuje @jnihnat, vypadá funkčně, ale osobně bych ho nepreferoval. Dropzone je knihovna napsaná pro okamžité nahrávání souborů a její používání jiným způsobem může mít řadu nežádoucích účinků. Jak Honza zmiňuje, může nastat problém při chybném nahrávání (např. uživatel nahraje jeden invalidní soubor a dva validní). Dál třeba může nastat problém při nahrávání většího množství větších souborů (minimálně to aplikaci zpomalí), při práci se špatným internetovým připojením atd.

Možná by bylo nejlepší varianta u každého souboru poznamenat, zda bylo nahrávání potvrzeno (pomocí tlačítka dokončit) a soubory, které nejsou potvrzené, pravidelně (např. jednou za den) mazat.

**Comment by motyc** [comment]
@pesikj Děkuji za vysvětlení. Ještě se nad tím zamyslím. Možná by postačilo lépe informovat uživatele a nějak se vypořádat s přítomnými tlačítky. Když funguje to odstraňování v dropzone, není to takový problém... Dám to design a zamyslíme se interně.

**Comment by pesikj** [comment]
@motyc dropzone nepodporuje informační tooltip, tak navrhuji ho dát do modal okna.

![Image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/aab9ea3a-62ce-4ea4-9da1-ebbde3c9379d)

![Image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/5966e73d-a50f-41f0-b310-76aef59b6e24)

**Comment by motyc** [comment]
@pesikj A nešlo by spíš prosím dát text normálně pod / nad dropbox? Tooltipem jsem myslel něco podobného, jako máme u formulářů:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/591c8470-a599-44d8-894b-8b44aab2de8e)

Myslím, že na tlačítko nikdo moc neklikne...

**Comment by pesikj** [comment]
@motyc Ano, to je také možné.
