### ISSUE TITLE
Podoba a chování tabulek

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#54]
- [x] Tabulka má výchozí sestavu sloupců, uživatel může zobrazení některých vypnout, případně přidat další dostupné.
- [x] Příliš dlouhý text je takový, který se do buňky nevejde při její aktuální velikosti. V takovém případě řetězec zkrátit podle velikosti pole, na konec doplnit „(…)“ a celý obsah zobrazit jako tooltip.
- [x] Umožnit export dat z tabulek (CSV, JSON, XML, XLSX).
- [x] Musí být zřetelný celkový počet záznamů v tabulce.

-------------------------------------------------------
Podzim
- [ ] Každý sloupec má stanovenou vhodnou minimální šířku a maximální šířku. Reálná šířka při načtení tabulky je dána skutečným prostorem na obrazovce a jedině v případě nedostatku prostoru i při minimálním nastavení se zobrazuje rolovátko již od začátku.
- [ ] Vyřešit responsivní chování - na mobilu tabulkové zobrazení nebude moc fungovat.
- [ ] Podporovat řazení podle více sloupců.
- [ ] Musí být možné přejít na konkrétní list.
- [ ] Musí být možné zvolit počet záznamů na listu (výchozí hodnota 100).

**Comment by Najiva** [comment]
Pridal jsem popis kolik je v tabulce zaznamu. @pkudela Zbyva umistit a nastylovat.

**Comment by Najiva** [comment]
Export bude resen v issue #73.

**Comment by Najiva** [comment]
@motyc Ten prechod na stranku je udelany stejnym zpusobem jak filtry. T.j. kdyz chci jit na stranku 123 tak staci jit na url /projekt/list?page=123 Takze to jiz funguje.

**Comment by motyc** [comment]
@Najiva Skvěle. Asi bychom tam jen měli nastavit horní limit na straně serveru, aby se někdo nesnažil udělat stránku s desetisíci záznamů a nějak nám to neshodil.

**Comment by pkudela** [comment]
@motyc jak jsem se zminil naposled, musel jsem dopocitavat velikost table wrapperu, aby byl vzdy na 100% zbyvajiciho contentoveho prostoru s tim, ze paticka bude vzdy videt. Toto reseni nebylo idealni, cili kod jsem prepsal a nyni se uz nic dopocitavat nemusi, jeste jsem zmensil vysku headeru a radku, s tim se jeste bude moct hybat.

**Comment by pkudela** [comment]
@Najiva za me teda zatim hotovo, ted jdu delat neco jineho, kdyby zase neco bylo pro me, tak napis

**Comment by Najiva** [comment]
Razeni podle vice sloupcu - napriklad chci radit podle stavu a pak podle hlavniho_katastru tak:

**&sort=stav&sort=hlavni_katastr**

Kdyz chci aby byl stav sestupne tak:

**&sort=-stav&sort=hlavni_katastr**
