### ISSUE TITLE
Přístupnost záznamu "--------" u akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#560]
Pokud změním přístupnost záznamu na “--------” a uložím, tak dostanu error 500 - volbu bych při zápisu/editaci akce vůbec nenabízel (u dokumentů a v PAS je to dobře).

**Comment by pesikj** [comment]
![image](https://user-images.githubusercontent.com/15179154/181455341-4e75c026-cdf5-49ea-9a29-28f30c32e582.png)
