### ISSUE TITLE
Ve všech tabulkách historie zmizela tlačítka "Zpět"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#561]

**Comment by pesikj** [comment]
@motyc Prosím o jasnou specifikaci.

**Comment by motyc** [comment]
@pesikj Ve všech tabulkách http://192.168.254.30:8080/historie/* se nacházelo tlačítko "Zpět", kterým se bylo možné dostat na původní detail. Nyní tam nikde nejsou. Patrně to bude jen rozbitým GUI a tlačítko je schované někde mimo zobrazení, nebo došlo k odstranění omylem...

**Comment by MaxKosta** [comment]
@motyc Dobry den, 
Otevřel jsem stránku /historie/soubor/13512 a vidím tam tlačítko (breadcrumb) Zpět na detail projektu. Povídejte prosím do přílohy. A to tlačítko funguje. Jestli můžete prosím ukázat stránku nebo stránky kde to není správné. Dekuji.
![image](https://user-images.githubusercontent.com/74970764/181006422-db31d9ca-c68b-4f99-82a1-61e0e1838958.png)

**Comment by motyc** [comment]
@MaxKosta Aha, pak se tedy zdá, že to nyní funguje specificky pro soubory projektové dokumentace, jinde ale ne. Původně to bylo skutečně přímo tlačítko zobrazené pod tabulkou. Nové řešení mi v principu vůbec nevadí, ale možnost vrátit se zpět musí být zachována všude. Možnost nevidím u:
http://192.168.254.30:8080/historie/projekt/X-C-202176665
http://192.168.254.30:8080/historie/arch-z/C-200811808A
http://192.168.254.30:8080/historie/dokument/C-TX-201800107
http://192.168.254.30:8080/historie/soubor/61285
http://192.168.254.30:8080/historie/dokument/C-3D-202000001
http://192.168.254.30:8080/historie/soubor/339290
http://192.168.254.30:8080/historie/pas/C-202010524-N00002
http://192.168.254.30:8080/historie/soubor/329151
http://192.168.254.30:8080/historie/spoluprace/3

**Comment by MaxKosta** [comment]
Prosím vás podívejte na uvedené obrázky. Určíte není tam tlačítko které říká Zpět ale tam je ten breadcrumb který můžete použít abyste se vrátili zpátky. Podtrhnul jsem to na obrazovkách.
<img width="519" alt="C-3D-202000001" src="https://user-images.githubusercontent.com/74970764/181018327-af5f5b18-ea5d-4fcc-840e-8624e23c689c.png">
<img width="586" alt="C-202176" src="https://user-images.githubusercontent.com/74970764/181018331-e8d42f36-5bdf-4ac7-b7ed-576ff5e2c8f2.png">
<img width="521" alt="C-200811808A" src="https://user-images.githubusercontent.com/74970764/181018339-6ae6e92c-b1f4-4bcc-aac5-2df6e86dd447.png">

**Comment by motyc** [comment]
@MaxKosta Tak to jsem si bohužel opravdu nevšiml a jde o (nevyžádanou) změnu, která není úplně vyhovující. Uživatele vůbec nenapadne v tomto smyslu na nadpis "Historie xy" kliknout. Navíc se to chová nekonzistentně, protože na http://192.168.254.30:8080/historie/soubor/61285/historie/soubor/13512 to vypadá takto:
![image](https://user-images.githubusercontent.com/20186892/181043546-f5034131-a154-4a69-8bfa-808964ada7df.png)

A na http://192.168.254.30:8080/historie/soubor/61285 to vypadá takto:
![image](https://user-images.githubusercontent.com/20186892/181043695-36cffb16-c65d-4f29-991b-4c256fd11465.png)

Nevím, z jaké pohnutky k odstranění původního tlačítka "Zpět" došlo, ale buď bych se ve všech případech držel chování, jako je např. zde (tj. do záhlaví dát "Historie xy" + [ident_cely] + "|" + "Zpět na detail XY"):
![image](https://user-images.githubusercontent.com/20186892/181044802-9d11e65a-51e9-400b-b90c-aff6335d2091.png)

nebo vrátil ta tlačítka, jak byla (viz např. zde: https://github.com/ARUP-CAS/aiscr-webamcr/issues/353#issuecomment-1147268839), což je ale asi i z hlediska designu méně vhodné řešení.

**Comment by motyc** [comment]
### Výsledek testování
- [ ] Tlačítko chybí na všech obrazovkách s historií souborů (http://192.168.254.30:8080/historie/soubor/*; v případě projektové dokumentace je tam ten odkaz v liště, který ale jinde chybí - http://192.168.254.30:8080/historie/soubor/338636)

Jinak v pořádku.

**Comment by pesikj** [comment]
@MaxKosta Maksi, ten poslední comment řeší výsledek testování?

**Comment by motyc** [comment]
### Výsledek testu
- [ ] http://192.168.254.30:8080/historie/soubor/339298 - tlačítko je schováno za lištou:
![image](https://user-images.githubusercontent.com/20186892/185480690-076fe9b2-e67f-43eb-9572-ac3c7eac5cf2.png)

**Comment by MaxKosta** [comment]
Podíval jsem na tlačítko zpět, jestli ještě je chováno zkuste prosím zmačknout ctrl + shift + R aby obnovit cache.
<img width="1568" alt="Screenshot 2022-08-30 115141" src="https://user-images.githubusercontent.com/74970764/187407205-17a606c4-2336-4d2e-be59-cd0c036fbfe4.png">

**Comment by motyc** [comment]
@MaxKosta Zkoušel jsem v Chrome na dvou různých PC a v obou případech problém přetrvává pro odkazy:
http://192.168.254.30:8080/historie/soubor/61285
http://192.168.254.30:8080/historie/soubor/329151

**Comment by motyc** [comment]
Znovu otevírám, řešení bohužel nefunguje dobře ve dvou ohledech:
- [ ] tlačítka se zvláštně "vznášejí" na pevné pozici v prostoru a nijak nereflektují ani rozložení okna, ani obsah tabulky; buď by měla být přisazená k tabulce, nebo k zápatí (zvolte, co je snazší
- [ ] při úpravě velikosti okna u http://192.168.254.30:8080/historie/soubor/338636 dochází stále ke skrývání tlačítka za patičku:
![image](https://user-images.githubusercontent.com/20186892/199065790-bc487494-658a-4c0f-8730-697e9d2e4520.png)

**Comment by sedmar** [comment]
Bude řešeno v rámci maintenance.

**Comment by motyc** [comment]
@jnihnat Je to stále řešeno poněkud nešťastně. Místo aby tlačítko bylo fixováno k zápatí tabulky s historií, je fixováno k patičce, což vede ke zvláštnímu chování a ani to nevypadá dobře. Navíc je odstup relativní, takže se mění při úpravě velikosti okna.

**Comment by jnihnat** [comment]
tlacitko opraveno v #1156. je stale na konci stranky, to vychazi z toho jak jsou ted delane tabulky, i ve vyberu pokud nastavite jen 10 zaznamu, tak jsou ty tlacitka dolu. Pokud to je problem treba predelat zobrazeni tabulek a to neni nic jednoducheho a nejsem si jisty jesti bug.

**Comment by motyc** [comment]
@jnihnat Rozumím. Mrknu na to a případně to doladíme společně s responsivitou. Problém je, jak se to různě posouvá a působilo vyloženě divně, že to není k ničemu fixované... Navíc to stále občas mizelo za patičku.
