### ISSUE TITLE
Drobné chyby formulářů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#562]
- [x] http://192.168.254.30:8080//projekt/detail/C-201700010 - po zapnutí editace zmizí obsah pole Označení stavby
- [x] http://192.168.254.30:8080//arch-z/akce/detail/C-202012732B - pole Poznámka zobrazuje totéž, co pole Lokalizace/okolnosti (při editaci ok)
- [x] http://192.168.254.30:8080//arch-z/akce/detail/C-200913623C - vyskovy_bod.ident_cely nemá jít nikdy a nijak editovat

**Comment by pesikj** [comment]
@motyc Pro existující záznamy také

![image](https://user-images.githubusercontent.com/15179154/178974611-176e706e-58d8-4ef0-95b1-309c8dd58681.png)

**Comment by motyc** [comment]
@pesikj Omylem bylo nahlášeno dvakrát, už to opravil @jnihnat v jiném issue.
