### ISSUE TITLE
Ladění odezvy a možného přetížení aplikace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#563]
Aplikaci lze v různých situacích běžnou činností uživatele dostat do stavu, kdy je přetížená, neodpovídá a vrací error 504. Tento stav navíc není platný pouze pro daného uživatele, ale jde skutečně o takové vytížení serveru, že aplikace přestane reagovat všem uživatelům. To je nepřijatelný stav, neboť musíme zvládnout pracovat s odpovídajícím počtem záznamů plynule a zároveň musíme být schopni paralelně a stabilně obsloužit desítky až stovky uživatelů. Je třeba navrhnout optimalizace a implementovat takové řešení, které stabilitu zajistí.

V tomto issue je cílem zejména doplnit do DB potřebné indexy a prověřit situace, kdy k zamrzání může dojít (zejména při filtraci, viz #325).

@sedmar 
> Jako uzivatel aplikace potrebuji responzivni aplikaci, kde je minimalizovana odezva i pri vyvovalani vypocetne narocnych operaci.
> Pozn. Toto lze konfiguraci aplikacniho serveru a ladenim jeho parametru pro optimalni odezvu.

**Comment by pesikj** [comment]
Řešení, která by měla být otestována:
- Problémy se řazením: přidání databázových indexů.
- Problémy s exportem velkého objemu dat: generování souboru na pozadí a odeslání odkazu na soubor mailem.
- Obrazovka s velkým množstvím DJ: namísto renderování a skrývání formulářů renderovat vždy jen aktivní formulář, kliknutí na odkaz vždy načte stránku znovu s vyrenderovaným jiným formulářem.

Postup řešení by měl být:
1) analýza jednotlivých návrhů, zda vůbec problém uspokojivě vyřeší,
2) implementace, kterou bych navrhoval jako samostatné issue.
@motyc

**Comment by motyc** [comment]
@pesikj Ano, může to takto být. K těm obrazovkám akcí máme zvlášť issue #523, k exportům pak #395. Toto issue můžeme nechat na tu analýzu a indexy. Souhlas?

**Comment by pesikj** [comment]
@motyc Za mě ok.

**Comment by motyc** [comment]
Dosavadní testy ukazují následující:
### Projekty
- export projektů při výběru prostým výběrem okresů jsem se úspěšně dostal na 29904 projektů, kdy se připraví .xlsx soubor za cca 59 sekund. Více projektů po minutě zahlásí 504 Gateway Time out
- filtrace na změnu stavu (archivované projekty 2017-2022) - 20268 - výběr trvá cca 43 sekund
- pokud přidám k parametru i vrácené projekty, tak jen pro mě vrátí dotaz v pořádku po cca 17 sekundách, pokud ale přidám např. jen uživatele Jitka Říhová, tak po cca 27 sekundách vrátí 500 interní chybu serveru (Jitka samostatně je také OK a dohromady je to cca 19 tisíc projektů, což při jiném dotazu běžně zvládne vyfiltrovat i vyexportovat, tady neproběhne úspěšně ani filtrace
- stejný dotaz s přidáním parametru akcí podle krajů proběhne OK i když mám zvolené všechny kraje (má na to vliv to, že by tam byla část projektů bez akcí a to neúměrně navýšilo počet výsledků?)

### samostatné nálezy 
- Všechny zapsané nálezy od 2021 do současnosti - po minutě 504 Gateway Time out
- Stejně tak i všechny nálezy za letošní rok (mělo by to vrátit 0 pokud tam nejsou data)
- Stejně i nálezy od 1.7.2022 – to nedává smysl, takže problém bude někde jinde
- Když jsem dal zpět a pokusil se rozkliknout jeden z projektů v tabulce, tak také 504 – jako by několik filtrů za sebou nějak zaseklo aplikaci
- Obecně pro některé filtry na změny stavu v určitém časovém rozsahu to vrací chybu 504 (z počátku jsem si myslel, že se jedná o dotazy, které nemají žádný výsledek, ale někdy to normálně vrátí 0 výsledků
- Problém bude patrně v časovém rozsahu, když jsem např. zadal dotaz od počátku roku do dnešního data tak se vrátilo 0 výsledků, pokud jsem dal dotaz od počátku roku 2021 tak se vrátila chyba 504  (normální výsledek se vrátil až po 4.3.2021)
- Samotný časový rozsah je ale jen část problému, filtr se chová nestandardně, kdy někdy vrátí chybu u menšího časového rozsahu a u většího vrátí 0 výsledků. Zároveň je ale problém ve vrácených výsledcích, protože 0 výsledků se vrací i při parametrech, které by výsledem mít měly (např. odeslání nálezu ze 14.10.2021 by mělo zobrazit minimálně C-201700002-N00002
- Po chybě 504 když kliknu na zpět, tak někdy nevidím navolenou možnost změny stavu, i když po rozkliknutí ji mám pořád nastavenou

### Knihovna 3D
- Zápis dokumentu 27.5.2020 až 9.8.2022 – bez uživatele vrátí výsledek, pokud přidám uživatele Jiří Unger tak vrátí chybu 504, když se vrátím zpět a uživatele odstraním, tak už vrátí jen chybu 504
- Někdy je dost dlouhá odezva na resetování formuláře po novém kliknutí na vybrat, trvá i desítky vteřin a někdy chyba 504. Jako kdyby několik filtrů po sobě opět přetížilo aplikaci a 504 vidím i když se chci vrátit na hlavní stránku (9.8.+- 14:40 a i několikrát potom jsem nemohl přepnout na žádnou jinou stránku, jako by první chyba 504 u 3D zasekla aplikaci a nemůžu se do ní vůbec dostat (testováno ze dvou PC, u jiných částí se mi to zatím nestalo, ale u 3D opakovaně a připojit se mohu až po desítkách minut)

### Externí zdroje
- kombinace více parametrů . např. stav - datum změny a autor změny spustí odstávku - ale jen někdy (např. kombinace stav, datum změny od a Pavel Kacl)

### Akce
- po testování historie - archivace mi to zahlásilo údržbu systému - na stránky se ale můžu opět normálně vrátit🤷‍♂️
stejná situace když jsem se pokusil vyhledat kombinaci plošného PIAN s přesností na katastr (asi to s tím nesouvisí, Dana má také údržbu)
- nyní opět u kombinace bodový PIAN a přesnost na k.ú. (po zadání adresy jsem se opět hned vrátil - ale další pokus opět odstávka a opět po zadání adresy OK
- stejné i v kombinaci liniový PIAN (u plošného proběhne OK) a přesnost na k.ú. - ten dotaz jako takový nedává příliš smysl, ale jde zadat a někteří uživatelé to jistě zkusí takto zadat
- teď mi to vrátilo stejnou chybu i při pokusu o filtraci podle data zahájení (2022-12-01 22:52)

**Comment by jnihnat** [comment]
opravy v #933 
po nasazenich django migracich je potrebne jeste jendou protestovat, ci nahodou se neopomnel nejaky index.

**Comment by motyc** [comment]
@jnihnat Díky, po nasazení otestujeme.

Ještě se zeptám - některé filtrace budou myslím stále náročné. Bude nějak zajištěno, aby i složitá úloha filtrace neměla přímý dopad na chod aplikace pro ostatní uživatele? Problém primárně je v tom, aby jeden uživatel filtrací nemohl druhému uživateli zablokovat. Je třeba myslet na to, že aplikaci souběžně bude používat poměrně hodně uživatelů (minimálně desítky, někdy stovky) a odezva musí být přijatelná i v takovém případě.

**Comment by jnihnat** [comment]
Po nasazeni to chci taky otestovat, skousit udelat i nejaky load test pomoci jmeter. 
Filtrace celkove by mnely byt po novu o dost rychlejsi, ale taky planuju otestovat i sam. Taky to musim pak otestovat na "nove" db delane pomoci django migraci, indexy by tam mnely byt nastaveny sravne, ale je to treba protestovat.

Taky jeste mam jeden bod otevreny - nacteni autoru u dokumentu a externich zdroje, protoze tam je potrebne pouzit razeni z navazane tabulky a to dela zbytecne selecty do DB. celkove to nacteni nespomaluje, ale je tam nadbytok selectov, cemu bych se rad vyhnul, ale zatim moje skousene reseni jsou neuspesne.

**Comment by jnihnat** [comment]
V rámci implementace byli opraveny chyby pri filtraci a skracen cas selectu do DB. Tohle bylo udelano pro vsechny listy a filtry. Nacitani stranek s vyberem by teda nemnelo byt delsi nez 5s a ve vetsine pripadu do 2s. Take bylo upraveno spusteno aplikace, ktera tedka bezi na 5 procesech a teda jeden request neblokuje dalsi request. Pokud nekdo klikne na export ktery trva 30s dalsi nacitani stranky na jine karte je mozne klidne uskutecnit.

**Comment by jnihnat** [comment]
jeste sem pridal par chybejicich indexu v db delane jen migracemi. prosim testujte az @pesikj mergne a nasadi i #990

**Comment by motyc** [comment]
Po testování potvrzujeme odstranění základních potíží a výrazné zrychlení odezvy. Doladění vyřešíme jako #1041
