### ISSUE TITLE
Nefunguje “připojit PIAN z mapy”

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#575]
Nástroj nyní nic nedělá

**Comment by motyc** [comment]
@pesikj Řeší se v rámci #522, toto zavírám jako duplicitu.

**Comment by motyc** [comment]
Znovu otvírám - testováno na http://192.168.254.30:8080/id/C-200912229B-D01 - funkci vyberu v menu, kliknu na PIAN v mapě, mapa se posune, ale PIAN se nepřidá.

**Comment by sedmar** [comment]
Ji6ž opraveno JBa.

**Comment by motyc** [comment]
@sedmar Je to tak, zavírám.

**Comment by motyc** [comment]
Bohužel zase nefunguje. Testováno na: http://192.168.254.30:8080/arch-z/akce/detail/C-9001325A/dj/C-9001325A-D02
