### ISSUE TITLE
Update na Django 4 a aktualizace knihoven

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#577]
Aktualizace nasledujich zavislosti na nejnovejsi stabilni verzi a nasledne otestovani stability:
asgiref==3.5.0
Django==3.2.11
django-dal==1.0.0
psycopg2-binary==2.8.6
pytz==2021.3
sqlparse==0.4.2
simplejson==3.17.2
django-crispy-forms==1.10.0
django-recaptcha==2.0.6
django_registration==3.1.2
django-filter==2.4.0
django-tables2==2.4.0
django-tables2-column-shifter==2.0.3
django-compressor==3.1
django-libsass==0.8
django-autocomplete-light==3.8.2
django-widget-tweaks==1.4.5
tablib[all]
django-simple-history==3.0.0
python-memcached==1.59
distlib==0.3.4
django-rosetta==0.9.8
django-structlog==2.2.0
django-auto-logout==0.5.0
reportlab==3.6.8
PyRTF3==0.47.5
PyPDF2==1.27.12
django-cron==0.6.0
Pillow==9.1.1
beautifulsoup4==4.8.1.
django-extensions==3.1.1
django_select2==8.0.0
celery==5.2.7
redis==4.4.2
flower==1.2.0
django-celery-beat==2.4.0

**Comment by pesikj** [comment]
Je třeba prověřit kompatibilitu používaných plug-inů.

**Comment by jnihnat** [comment]
V rámci implementace byli povyseny vsechny dostupne knihovny na nejnovejsi verze. Byly vyreseny jednotlive zavyslosti. Povyseni knihven nema mit zadny vliv na chod aplikace a bezi stejne jako doted.

**Comment by motyc** [comment]
@jnihnat Toto je nyní spíše na @pesikj, souvisí s tímto:

> Doplnit` monitoring aktuálnosti kódu s využitím funkcionality Dependabot version updates (pan Pešík má z tohoto důvodu dočasně přidělena admin práva k repozitáři).
