### ISSUE TITLE
Prázdný konec seznamů se jmény v Mozille

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#587]
Vyčleněno z #338 a #327

V Mozille při výběru z drop-down listu osob (bez ohledu na umístění v aplikaci) při pokusu dojet na konec seznamu přeskočí seznam na prázdnou “stránku”. Při probliknutí před prázdnou stránkou je však vidět, že za “Žohová, Martina” jsou i další jména.

týká se např.:
http://192.168.254.30:8080/dokument/edit/X-C-TX-201904031
http://192.168.254.30:8080/dokument/model/edit/C-3D-202000004
http://192.168.254.30:8080/pas/edit/M-202101534-N00282
http://192.168.254.30:8080/arch-z/akce/detail/C-202002083A

**Comment by jnihnat** [comment]
mozne otestovat hned. Rucne som upravil css, ktore se z nejakeho duvodu nepregenerovalo po uprave.
Do buducna som nastavil timeout pro rebouild css, tak snad se nebude opakovat, ze se nepregeneruje.

**Comment by svejci** [comment]
@motyc otestoval jsem v Mozille namátkou na různých místech v aplikaci a všude bylo nyní OK.

**Comment by motyc** [comment]
@svejci Díky, dávám do vyřešených.
