### ISSUE TITLE
Error 500 při odpojení dokumentu a refreshi okna

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#588]
Otevřu a nechám otevřené http://192.168.254.30:8080/arch-z/akce/detail/C-200810779A -> přes akci otevřu a nechám otevřené http://192.168.254.30:8080/dokument/detail/C-TX-202200008 -> přes akci odpojím dokument C-TX-202200008 -> refresh okna s C-TX-202200008 -> error 500 -> přechod na http://192.168.254.30:8080/id/X-C-TX-202200004 -> dokument se v pořádku zobrazí

Tuším, že bude souviset s #266

**Comment by pesikj** [comment]
@motyc Zkoušel jsem popsaný postup a žádná chyba se mi nezobrazila, vše proběhlo korektně.

**Comment by motyc** [comment]
@pesikj V nové verzi zkusím znovu reprodukovat. Před tím to šlo vícekrát za sebou.

**Comment by jnihnat** [comment]
@pesikj opraveno v #609 - byl tam proklep
@motyc - nemusite retestovat, respektive az po dalsim nasazeni kde to bude opraveno.
