### ISSUE TITLE
Doplnění číslice do identifikátorů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#59]
- [x] jednotky (části) dokumentu: D01 -> D001
- [x] komponenty: K01 -> K001
- [x] komponenty dok.: K01 -> K001

**Comment by Najiva** [comment]
Ano slo by to udelat i jinak pomoci left, right. Stejne jak v pripade casti dokumentu. Tohle ale bude taky fungovat, protoze nikde jinde nez na konci se v komponentach '-K' nevyskytuje.
