### ISSUE TITLE
formset.is_valid() hazi true i kdyz se specifikace a druh needitoval

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#61]
Potreba zajistit ze django spravne srovnava instance heslare a choices.

**Comment by pesikj** [comment]
@Najiva Můžeš prosím podrobněji specifikovat tento bug?

**Comment by Najiva** [comment]
Uz si to moc nepamatuju. Vim ze validace choices ve formsetu se v nekterem z tech pripadu neprovadi nebo hazi true kdyz by tam melo byt false. Vim ze to nebylo uplne kriticke (kdyz se forma vyplni spravne tak to neni problem) kazdopadne to asi casem vyplave.

**Comment by motyc** [comment]
Nevím, co mám přesně testovat, ale zjevně se to řešilo. Zavírám a narazíme-li na problém, vrátíme se k tomu.
