### ISSUE TITLE
PAS - zápis nálezu - výchozí souřadnice

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#611]
Pokud přejdu na http://192.168.254.30:8080/pas/zapsat a překliknu z WGS-84 na S-JTSK (aniž bych cokoli zadal do mapy), automaticky se vyplní nějaké souřadnice do formuláře, přestože by pole měla zůstat prázdná.

**Comment by jiri-bartos-huld** [comment]
Vyreseno v ramci: issue #305
https://github.com/ARUP-CAS/aiscr-webamcr/commit/4b99a3aed71a78a03e5dd3f0f348f875c2d0b638
