### ISSUE TITLE
Pridat karty v homepage a homepage projektu

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#62]

**Comment by Najiva** [comment]
Pridal jsem url na homepage projektu. Je potreba tam pridat karty ktere budou odpovidat tomu co je v java clientovi.

**Comment by Najiva** [comment]
![application homepate](https://user-images.githubusercontent.com/26173315/116968208-51b77380-acb4-11eb-9e87-f8fea1a0d32e.PNG)

![aplikace projekt](https://user-images.githubusercontent.com/26173315/116968176-43695780-acb4-11eb-8653-587116fb821a.PNG)

**Comment by pkudela** [comment]
Po dohode s Davidem, karta digitalni archiv na home page nebude, odkaz na digiarchiv se umisti jinam, cili pro ted pripravim karty pro entity: projekty, knihovna 3D a samostatne nalezy. Cili shrnuto, karty na home page by mely odpovidat seznamu "entit" v digiarchivu, @motyc prosim potvrd / upresni

**Comment by motyc** [comment]
Ano, souhlasí.

**Comment by pkudela** [comment]
hotovo, design based on @motyc comments, u home je jediny link na projekt, protoze ten existuje, ostatni zatim nevedou nikam. Na strance projekt jsem vzal linky ze sidebaru, jediny link, ktery zatim neni je "Zapsat projekt", prosim pak doplnit do kodu. Je trebe jeste doladit hover event na kartu na home page a az to bude vyladene, tak se udelaji stejnym zpusobem popisky na strance projekt.

**Comment by pkudela** [comment]
Tak tu anomalii s tim collapsovanim @Najiva vyresim, uz vim jak, bootstrap collapse neni mozne pouzit na hover event, pouze na click.

**Comment by pkudela** [comment]
anomalie vyresena, popisky nasazeny i na karty projektu, je to pripravene a pushnute

**Comment by Najiva** [comment]
Vyborne zaviram.
