### ISSUE TITLE
3D - nezobrazují se souřadnice

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#627]
Pole jsou prázdná, přestože v mapě je bod zadaný. Nefunguje ani při editaci.

![image](https://user-images.githubusercontent.com/20186892/181237791-dbba4fc0-f52b-4085-a6f3-1e8b765abc9d.png)

**Comment by jiri-bartos-huld** [comment]
@motyc 
prosim o pretestovani a pokud chyba pretrvava tak o uvedeni URL, protoze pro mnou testovane 3D je vse ok.

![obrazek](https://user-images.githubusercontent.com/77389730/185235204-1a90bcb4-1375-4400-8e0c-48707e125c7f.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Bohužel stále data nevidím (pole se tváří být prázdná). Testuji např. na: http://192.168.254.30:8080/dokument/model/detail/X-C-3D-202200007

**Comment by svejci** [comment]
@jiri-bartos-huld @motyc 
Testoval jsem teď uvedený odkaz a v Mozille a zde souřadnice vidím. V Chrome ale také vidím obě pole prázdná, problém tedy bude patrně v prohlížeči, ze kterého k záznamu přistupujeme.

**Comment by motyc** [comment]
@pesikj Zde platí, co psal kolega Švejcar odpoledne. Zatím se myslím nic nezměnilo.

**Comment by jiri-bartos-huld** [comment]
odlisnost Firefox vs Chrome, opraveno pro Chrome
![obrazek](https://user-images.githubusercontent.com/77389730/185808662-a276a9a3-0e0b-4768-9de3-c8921e221079.png)

**Comment by svejci** [comment]
@motyc @jiri-bartos-huld 
testoval jsem opět na záznamu [http://192.168.254.30:8080/dokument/model/detail/X-C-3D-202200007](url) a v Chrome stále souřadnice nevidím (ani po editaci, ani u jiných záznamů).
![3D_souradnice_Chrome](https://user-images.githubusercontent.com/46997827/185858771-00620614-e410-44fa-90c2-dead10f833f2.PNG)

**Comment by motyc** [comment]
@svejci Ještě to není nasazené :)

**Comment by svejci** [comment]
Omlouvám se byl jsem zbrklý :-)
