### ISSUE TITLE
Detail implementace generovani docasnych a permanentnich identifikatoru

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#63]
Implementovane identifikatory a jejich funkce:

1.  get_permanent_project_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L44
2. get_temporary_project_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L51
3. get_project_event_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L61
4. get_dokument_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L96
5. get_cast_dokumentu_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L129
6. get_dj_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L146
7. get_komponenta_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L163
8. get_adb_ident https://github.com/ARUP-CAS/aiscr-webamcr/blob/63e464fa4e7aa3c0c5812c0f3ce91c0dad015c43/webclient/core/ident_cely.py#L192

@motyc Doporucuju udelat code review jednotlivych casti a podle toho se rozhodnout jak upravit implementace.

**Comment by motyc** [comment]
Obecné problémy, které souvisí se způsobem implementace, pokud se vychází pouze z pořadí:
1) Není zachována persistence v případě posledního přiděleného ID (po smazání se obratem nahradí novým záznamem s jiným obsahem).
2) Systém nepočítá s importy, které nejsou obvykle řazeny přímo v návaznosti na současnou řadu, ale zachovávají odstup od ID přidělovaných systémem (jinak by nebylo možné import rozumně připravit; zároveň je výhodné umět snadno odlišit importovaná data).

Bod 1 je problém pouze někde. Jinde jej naopak není třeba příliš řešit. Bod 2 je však problém všude. Pravděpodobně bude nutné, aby v DB vznikla pomocná datová třída, která by sledovala aktuální stav sekvence pro konkrétní řadu ID. Přinejmenším v některých případech tato již musí být někde v systému obsažena (např. pro samostatné akce - možná uloženo v atree?).

Jaká implementace by v dílčích případech měla být:
- get_permanent_project_ident - nutno řešit bod 1 i 2 (pro každý region zvlášť; reset s novým rokem)
- get_temporary_project_ident - dočasný, nemusí být zaručena persistence (pouze unikátnost v daném čase)
- get_project_event_ident - může zůstat (persistence je zde podstatná na úrovni projektu a u akce až po archivaci)
- get_dokument_ident - nutno řešit bod 1 i 2 (pro každou řadu/region zvlášť; reset s novým rokem)
- get_cast_dokumentu_ident - může zůstat
- get_dj_ident - může zůstat
- get_komponenta_ident - může zůstat
- get_adb_ident - nutno řešit bod 1 i 2 (pro každý mapový list zvlášť - již implementováno v DB)

**Comment by Najiva** [comment]
Pokousim se naimplementovat nove prirazovani ident_cely na zaklade sekvence pro ruzne rady projektu. Vytvoril jsem tabulu projekt_sekvence. Nove chovani bude nasledujici:

1. Poradove cislo pro danou radu se bude brat ze sloupce sekvence. Pro kazdou radu a rok zvlast. Tady je potreba aby tam nikdo nesahal a aby tam bylo dost let dopredu. Sekvence nema kto resetovat takze tam budou natvrdo roky dopredu.
2. V pripade ze django pri precteni sekvence zjisti, ze pro danou radu jiz takove poradove cislo existuje ve sloupci ident_cely (protoze ho tam nekdo importoval, nebo z jineho duvodu napr. ze se po zmene identu neinkrementovala sekvence), pokusi se django inkremetnovat poradove cislo (sekvenci) tak dlouho, az najde prvni volny ident.

To znamena ze ted, kdyz nekdo vytvori projekt a tomuto projektu se prideli permanentni ident C-202012345 django metodou (ta ktera inkrementuje taky sekvenci) a pak se smaze, tak se pri vytvoreni noveho projektu, ktery se dostane do stavu kdy se zmeni jeho ident na permanentni jiz vygeneruje ident dalsi (dle sekvence tj. C-202012346), ne porad prvni volny jak tomu bylo doted.

**Comment by Najiva** [comment]
![Screenshot from 2021-05-11 17-00-46](https://user-images.githubusercontent.com/26173315/117838284-7d20fc00-b27a-11eb-924e-48d94dac9ddd.png)

**Comment by Najiva** [comment]
Jeste se zapomelo na jednu vec a to je ze kdyz se projekt vrati do predchoziho stavu tj. ze zapsan do oznamen (co udelat lze), projektu se priradi opet novy permanentni ident. Tohle asi nechceme ze?

**Comment by motyc** [comment]
Ze zapsán do oznámen by neměl jít projekt vůbec vrátit.

**Comment by Najiva** [comment]
Aha tak tenhle pozadavek jsem nezaznamenal. V poradku.

**Comment by motyc** [comment]
Pro dokončení issue je třeba:
- [ ] @pesikj @DanaKriv prověřit přidělování provizorních ID, zda nemůže dojít k přetečení, případně popsat, jak je ošetřeno
- [ ] @pesikj @DanaKriv provést revizi stavu implementace pro všechny typy ID
- [ ] @pesikj opravit přidělování ID PIAN - nyní se v databázi odvozuje z PK ZM50, místo aby se odvozovalo z označení mapy (kladyzm.cislo); pořadové číslo je o řád kratší, než má být; vůbec nenavazuje na stávající sekvence v tabulce pian_sekvence
- [ ] @pesikj opravit přidělování ID ADB - tabulka adb_sekvence nekoresponduje s generováním ident_cely (vytvořen ADB-PRAH72-006774; v tabulce přitom uvedeno pro tento list 6755 - to je ale již dávno obsazené); jak se stanovuje číslo v adb_sekvence?
- [ ] vše odpovídajícím způsobem zadokumentovat (#115)

**Comment by DanaKriv** [comment]
Prošla jsem přidělování všech ID a narazila na následující problémy

PROJEKT ident_cely trvaly (set_permanent_ident_cely) - není ošetřeno přetečení nad 99 9999 (je velmi málo pravděpodobné, můžeme řešit později)

PIAN ident_cely 1) není formálně správně 2) přiděluje se na základě maximální hodnoty, nikoliv sekvenční tabulky 3) nepotvrzený i potvrzený PIAN sdílejí tu samou řadu čísel
- nepotvrzený PIAN má mít ident_cely ve tvaru N-1224-654123 a měl by být odvozován na základě maxima
- potvrzený PIAN má mít ident_cely ve tvaru P-1224-654123 a měl by být odvozen ze sekvenční tabulky
- druhá část ID (1224) má být odvozena z kladyzm.cislo a to bez pomlčky
- pian_sekvence obsahuje pro každou mapu ZM50 dva řádky, jeden se sekvencí pro PIAN=4, což je neurčená poloha v rámci katastru (řada nad 900000) a druhý pro ostatní PIAN (řada nad 100000) - je nutné to při přidělování čísla rozlišit

ADB ident_cely je formálně správně, ale opět se odvozuje na základě maxima a nikoliv sekvenční tabulky (v proceduře označeno jako TODO rewrite)

DOKUMENT ident_cely dočasný (get_temp_dokument_ident) - chybí ošetření přetečení nad 99 9999

**Comment by jnihnat** [comment]
@motyc , @DanaKriv Dobry den, mam prosim dotazy:
ad 1 - ako by ste si predstavovali osetrit pretecenie? Dvihnutie zo 6 cisel na 7? Pripadne navrhujem na tento bof zalozit nove issue
ad 2 - PIAN ident upraveny na max pro nepotvrzeny a sekvenci pro potvrzeny.  co sa tyka PIAN=4 je tym mysleno typ? pokud ano, pian ma zatim zavedeno len 3 typy v DB v heslari. 
ad 3 - predelano na sekvenci
ad 4 - tp same co pro projekt, ako by to malo byt reseno?

Dekuji za odpovedi.

**Comment by motyc** [comment]
@jnihnat
ad 1 - Chybovou hláškou a nutností reakce admina (záznam se již nevytvoří). Ošetřením je myšleno "aby to nezbořilo aplikaci/databázi". V praxi by k tomu docházet nemělo a pokud by se taková situace blížila, budeme to řešit v předstihu.
ad 2 - je tím myšlena přesnost PIAN (PIAN.presnost); "4" znamená "na katastr"
ad 4 - odpoví @DanaKriv

**Comment by DanaKriv** [comment]
@jnihnat @motyc 
ad 4 mělo by se to řešit stejně, jako v jiných procedurách stanovením max a reakcí na překročení
např. def get_cast_dokumentu_ident(dokument: Dokument) -> str:
         MAXIMUM: int = 999 ....
else:
        logger.error("Maximal number of dokument parts is" + str(MAXIMUM))

Ještě jsme přemýšleli, jak je to s přetečením u permanentního ID dokumentu (def set_permanent_ident_cely(self, rada)). Myslela jsem si, že instrukce
"{0}".format(sequence.sekvence).zfill(5) 
zajišťuje, že vždy dojde k ořezu na 5 míst a v případě dokumentů se vyhledává první neobsazená pozice. Co se ale stane, když  všech 99 999 pozic bude obsazeno, došlo by k zacyklení? Vedle toho jsem si znovu přečetla definici zfill, kde se praví 

str.zfill(width)
Return a copy of the string left filled with ASCII '0' digits to make a string of length width. A leading sign prefix ('+'/'-') is handled by inserting the padding after the sign character rather than before. The original string is returned if width is less than or equal to len(s).

a není mi jasné, co se stane, když original string překročí 99 999, bude tím pádem šestimístný a překročí width. Nebo se to nemůže stát, protože je to ošetřeno v sekvenční tabulce?

**Comment by jnihnat** [comment]
@motyc  a @DanaKriv 
zalogovani chyby je jasne. ja osobne bych k tomu jeste dodelal i zobrazeni chyby na FE pomoci cervenych alertova ako je jinde v aplikaci. Pokud souhlasite, tak kdyz mi napisete hlasku to tam pridam. (momentalne tam je: "Maximalni cislo identifikatoru bylo prekroceno")
Pokud ne, tak aplikace by mnelo zobrazit nejakou generickou web error. 

co a tyka str.zfill() tak ten len doplna nuly pred retazec do daneho poctu, pokud uz je pocet rovny alebo prekroceny ignoruje sa.
Pokud se to teda stane osetrim to jako je u Maxima aby se zalogovala error a pripadne vypsal alert userovi. (podle bodu hore)

co sa tyka maxim, tak tie funguju tak, ze sa najde vzdy posledny zaznam v tabulke, zoberie sa to cast z iden_cely a pripocita sa +1.
Takze nie je to tak, zeby sa pripadne plnili aj medzery po odmazanych. Po odmazanych pripadne ostavaju "diery".

**Comment by motyc** [comment]
@jnihnat
Ano, ten alert jsem měl na mysli, takže souhlas. Text může být: "Byl překročen limit při přidělování identifikátoru. Pro vyřešení problému kontaktujte administrátora AMČR."

Z popisu fungování tedy vyplývá, že tam, kde to není ošetřeno, by se ještě měla doplnit ochrana proti přetečení nad nastavený počet číslic (víme, že chybí u dokumentů - dočasná i trvala ID).

**Comment by DanaKriv** [comment]
@jnihnat 
Ještě prosím o kontrolu procedury pro přidělení dočasného ID projektu (get_temporary_project_ident). Nemůže nastat situace, že nově přidělené ID už bude v databázi existovat?

**Comment by jnihnat** [comment]
@motyc a @DanaKriv 
- doplneni preteceni dodelam pro dokumenty
- preteceni taky chybi pro docasny ident pre projekt. Plus ten se bere jen jako "X-" + region + "-" + str(year) + id_number
kde id_number je doplnene id z databaze na 5 cisel.
je to takto spravne? Tu sa trocha obavam, ze se muzeme dostat rychlo na 99999 (i kdyz nevim kolik projektu v ramci AMCR vznika rocne, tak mozna se mylim)

**Comment by motyc** [comment]
@jnihnat Jestli ale dobře chápu způsob přidělování, tak pro dočasný ident projektu se na tvrdo doplňuje 5 znaků podle DB, takže přetečení na 6 číslic nehrozí. Může ale (teoreticky) nastat ta situace zmíněná @DanaKriv, že se DB pokusí přidělit podruhé tentýž ident_cely, a to ve chvíli, kdy by projektů v jednom roce bylo více než 99999 a zároveň stále existoval dočasný ident_cely u projektu s ID o 100000 nižším. Projektů bývá max. 20 tis. ročně, takže by se to stát v praxi nemělo, ale ošetřit bychom to asi měli (chybovou hláškou). Hranice 99999 jako taková tady ale myslím nehraje roli.

**Comment by jnihnat** [comment]
@motyc 
Prepacte, ja to trocha spatne napsal, upresnim.
docasny ident pracuse s projekt.id. ID je automaticke pole vzdy vyssi o 1. Takze nehrozi, zeby se udelil 2x stejne ID. Spis co hrozi tedka je preteceni (to doplneni je pokud je min jak 5 cisel, vic to povoli). Taky je potrebne osetrit to pridelovani. 20 tis rocne by znamenalo preteceni po 5 letech (a to nepocitam kolik projektu je v DB ted). 
Otazka je, ci chcete ten docasny ident stejne jako perm = podle regionu a podle roku - vytvorit teda sekvencni tabulku respektive ji doplnit o sekvence pro docasne identy.
Nebo jenom podle roku, pripadne ci tam je jina pozadavka pro docasny ident.

**Comment by motyc** [comment]
@pesikj Aha, rozumím. Když nad tím přemýšlím, možná by bylo nejsnazší vypustit z dočasného ID údaj o roku, a brát z ID 9 čísel, což zajistí, že to v podstatě nemůže přetéct nikdy... Bylo by to tedy: "X-" + region + 9 číslic

Co myslíte?

**Comment by jnihnat** [comment]
dokumentace vytvorena na Wiki:
https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely

**Comment by jnihnat** [comment]
> 
> 
> Pro dokončení issue je třeba:
> 
>     * [x]  @pesikj @DanaKriv prověřit přidělování provizorních ID, zda nemůže dojít k přetečení, případně popsat, jak je ošetřeno
> 
>     * [x]  @pesikj @DanaKriv provést revizi stavu implementace pro všechny typy ID
> 
>     * [ ]  @pesikj opravit přidělování ID PIAN - nyní se v databázi odvozuje z PK ZM50, místo aby se odvozovalo z označení mapy (kladyzm.cislo); pořadové číslo je o řád kratší, než má být; vůbec nenavazuje na stávající sekvence v tabulce pian_sekvence
> 
>     * [ ]  @pesikj opravit přidělování ID ADB - tabulka adb_sekvence nekoresponduje s generováním ident_cely (vytvořen ADB-PRAH72-006774; v tabulce přitom uvedeno pro tento list 6755 - to je ale již dávno obsazené); jak se stanovuje číslo v adb_sekvence?
> 
>     * [ ]  @pesikj vše odpovídajícím způsobem zadokumentovat ([Dokumentace kritickych bodu (REQ-NF-7) #115](https://github.com/ARUP-CAS/aiscr-webamcr/issues/115))

Vsetky body hore by mali byt splnene. Kvoli zasahom do vacsiny pridelovania identov, prosim pretestovat vsetky.

**Comment by motyc** [comment]
@jnihnat v dokumentaci vidím tyto nepřesnosti; je třeba je opravit, zvláště pokud platí i v kódu:
1) Permanentní ID projektu se přiděluje při přechodu do P1, nikoli při archivaci.
2) Mezi rokem a číslem v ID projektu nemá být pomlčka (správně je "M-202100034" (je třeba promítnout i do podřízených tříd (akce, DJ atd.)
3) Dokument - zde opět nemá být pomlčka mezi rokem a číslem (správně je "X-M-TX-20210034").
4) V permanentním ID dokumentu chybí region (C/M; správně např.: "M-TX-20210034").
5) Nezapomenout na to, že při archivaci se změní nejen ID dokumentu, ale též děděných tříd (Části dokumentu).
6) ID dokumentační jednotky a komponenty - opět pomlčky navíc - má být: "M-202100034A-D001, resp. "M-202100034A-K001"
7) Nevím, co je "Komponenta dokumentacni casti"; pokud je tím myšlena komponenta dokumentu (připojovaná k části dokumentu), tak tam je schéma ID např.: M-TX-20210034-K001. Aplikace jej ale nyní nepřiděluje, tato část se teprve bude implementovat.
8) Samostatný nález - opět pomlčky navíc, správně je: "M-202100034A-N00001"
9) Chybí popis pro výškové body

**Comment by jnihnat** [comment]
@motyc vacsina chyb byla naozaj jenom v dokumentaci, pro jistotu som kontroloval v kodu, po bodoch:

1. chyba jen v dokumentaci
2. chyba jen v dokumentaci
3. chyba jen v dokumentaci
4. chyba jen v dokumentaci + oprava v kodu
5. chyba jen v dokumentaci + oprava v kodu
6. chyba jen v dokumentaci
7. Aplikaci tu komponentu vytvari na pozadi a prideluje i ident, proto som napsal jak to tedka funguje.
8. chyba jen v dokumentaci
9. dopsany popis

**Comment by motyc** [comment]
@jnihnat
ad 7 - jste si jistý, že se skutečně ta komponenta někde sama na pozadí vytváří? Pokud ano, bylo by to chybně a nově vytvářet se sama nemá. Díval jsem se do kódu na https://github.com/ARUP-CAS/aiscr-webamcr/blob/94318064878810211213fb274d0c040a4607348b/webclient/core/ident_cely.py#L170 a je u toho komentář `# nikde nepouzite`...

**Comment by jnihnat** [comment]
Jo ta komponenta se vytvari pro 3D model:
create/model
samotny ident se pak nevytvari z methody ale je hardcoded:
`komponenta = form_komponenta.save(commit=False)`
`komponenta.komponenta_vazby = dc.komponenty`
`komponenta.ident_cely = dokument.ident_cely + "-K001"`
`komponenta.save()`

**Comment by motyc** [comment]
@jnihnat Ano, máte pravdu, tam je to úplně dobře. Na tuto část aplikace jsem zapomněl (myslel jsem jen na dokumenty u projektových akcí). Díky za upřesnění.

**Comment by motyc** [comment]
@DanaKriv Měla bys prosím čas to otestovat?

**Comment by DanaKriv** [comment]
@jnihnat @motyc  Otestovala jsem, děkuji za vytvoření dokumentace, jde to s ní mnohem lépe. 

Poznámky:

1. webclient/core/exceptions.py/MaximalIdentNumberError: hlášení "Maximalni cislo identifikatoru bylo prekroceno“ nahraďte za "Byl překročen limit při přidělování identifikátoru. Pro vyřešení problému kontaktujte administrátora AMČR."

 2. trvalý ident Projektu (webclient/projekt/models.py/set_permanent_ident_cely) a Dokumentu (webclient/dokumenty/models.py/set_permanent_ident_cely) - ošetření přetečení předchází cyklu pro přeskakování existující řady čísel, tam ale k němu může dojít také

 3. webclient/core/ident_cely.py/get_temporary_pian_ident - nechybí tam test if PIAN.exists() (dočasný PIAN nemusí existovat)?

**Comment by jnihnat** [comment]
ad1 - v souboru `exceptions.py` jsou texty ktere se ukladaji jen do logu. to co se zobrazi uzivateli je v `core/message_constance.py` a tam to je verim ze spravne.
ad2 - mate pravdu opravil som to a kontrolu pridal po cyklu kvuli importu
ad3 - mate pravdu, pridal som kontrolu.
zmeny jsou v #215

**Comment by pbartosova** [comment]
Hotové, prosím zavřít.

**Comment by jnihnat** [comment]
VB pridelovani opraveno do #243

**Comment by motyc** [comment]
Testovat lze až po opravě #373
