### ISSUE TITLE
Chyba při potvrzování nálezu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#639]
Při pokusu potvrdit nález (např.: http://192.168.254.30:8080/pas/detail/C-202105366-N00001; posun stavu N2->N3) je prázdné pole "Předáno organizaci" - má v něm však být automaticky doplněna organizace, která odpovídá příslušné organizaci projektu připojeného k nálezu (projekt.organizace):
![image](https://user-images.githubusercontent.com/20186892/182812786-b6e333ad-c28f-4292-bc1c-4fa9c9b18328.png)

Nyní se tak nejde posunout dále v dané workflow.

**Comment by MaxKosta** [comment]
@motyc 
Dobrý den,
Mám několik otázek, abych to správně opravil.
V jakému stavu samostatného nálezu pole «Předáno organizaci» musí byt dezaktivované(disabled)?
Může mít samostatný nález jinou organizaci než projekt?

**Comment by motyc** [comment]
@MaxKosta Pole je disabled vždy a vždy se odvozuje z organizace projektu, takže rozejít se to může pouze v případě nějaké pozdější editace projektu samotného.

**Comment by MaxKosta** [comment]
@motyc Jak a z čím je spojena hodnota pole "přístupnost"?
A jaké hodnoty v poli "přístupnost" jsou povolené pro různé stavy modelu "samostatný nalez"?
<img width="848" alt="Screenshot 2022-08-16 160308" src="https://user-images.githubusercontent.com/74970764/184902787-cd88c9f8-7a35-4a18-b200-b0616fb9b9d7.png">

**Comment by motyc** [comment]
@MaxKosta Jde o hodnoty A - D (anonym - archivář) z hesláře přístupnost. Stav rozsah hodnot v daném poli neovlivňuje.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Nyní se to chová tak, že nález sice potvrdit lze, ale pole organizace zůstává úplně prázdné (testováno na http://192.168.254.30:8080/pas/detail/C-202105366-N00001). Nicméně když zapíšu nový nález, tak se pole rovnou předvyplní. Mám to chápat tak, že to nově bude fungovat takto? Pokud ano, bude ale třeba ošetřit stará data při migraci, protože tam bude spousta nálezů, u kterých je dané pole prázdné (organizace se zapsala až při posunu stavu N2->N3).

**Comment by MaxKosta** [comment]
@motyc Dobry den. Vysvětlím cely proces, jak to funguje, abychom měli stejný pohled.
<img width="1693" alt="1" src="https://user-images.githubusercontent.com/74970764/185612196-8e62cfc9-c4a1-42e3-adc1-821a7d62806e.png">
1 obrázek: Všechna pole jsou neaktivní a prázdná.
<img width="1685" alt="2" src="https://user-images.githubusercontent.com/74970764/185612167-59daafbf-686d-4450-ac0b-b90d1b422075.png">
2 obrázek: Editovaní „Uloženi“. Všechna pole kromě „Předáno organizaci“ jsou prázdná a je možné je editovat. Po uložení se stránka znovu načte. A vidíme 3 obrázek
<img width="1910" alt="3" src="https://user-images.githubusercontent.com/74970764/185612181-093bb050-cb16-414d-9d6c-8c139297a9b7.png">
3 obrázek: pole „Předáno organizaci“ bylo automaticky nahráno.
Pokud potřebujeme aktualizovat stávající modely, musíme použít migraci nebo najít jiné řešení

**Comment by motyc** [comment]
@MaxKosta Otestoval jsem chování a už asi rozumím tomu, kde je problém - organizace se skutečně doplní při použití editace, ale nedoplní se, pokud použiji funkci "Potvrdit":
![image](https://user-images.githubusercontent.com/20186892/185613274-bf53dbae-d615-4140-9af6-ec4d4d961c8c.png)

Pokud toto opravíte, bude to ok a neměl by být problém ani s původními daty.

Zároveň je trošku matoucí, že při zapnutí editace/potvrzení je pole organizace prázdné a doplní se až po odeslání. Buď by mělo být viditelně předvyplněno již při otevření editace/potvrzení, nebo v těchto dialozích pole prostě skryjme a zobrazujme jej jen v detailu.

**Comment by MaxKosta** [comment]
@motyc Opravil jsem to. Až budete mít čas podívejte se prosím.

**Comment by motyc** [comment]
@MaxKosta Otestuji, až bude nasazená nová verze.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Pole organizace mělo být skryto jen v modálním okně při kliknutí na editovat/potvrdit. V detailu nálezu jsme ho skrývat nechtěli (`v těchto dialozích pole prostě skryjme a zobrazujme jej jen v detailu.`).

Jinak v pořádku.

**Comment by MaxKosta** [comment]
@motyc Chtěl bych zeptat (_v těchto dialozích pole prostě skryjme a zobrazujme jej jen v detailu._) jestli tam už je informace to taky skrýváme to?

**Comment by motyc** [comment]
@MaxKosta Ano, pole lze skrýt vždy. Měnit obsah stejně nejde a stačí, když bude viditelné v zobrazení detailu záznamu. Je to myslím nejjednodušší řešení.

**Comment by pesikj** [comment]
@MaxKosta Maksi, podle mě je to vyřešeno, je to tak?

**Comment by MaxKosta** [comment]
@pesikj Podle mě je to vyřešeno.
