### ISSUE TITLE
U souborů potvrzení o oznámení chybí hash

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#642]
Do názvu automaticky generovaných souborů oznámení se při ukládání do úložiště nevkládá hash.

**Comment by pesikj** [comment]
V zadání (#273) nic o vkládání hashe není, nejde o bug.

**Comment by motyc** [comment]
@pesikj Máte pravdu, v zadání je to opomenuté (resp. zadané bez něj). Opravdu o chybu nejde, ale půjde o úpravu.

**Comment by pbartosova** [comment]
Abychom předešli nedorozumění, prosím o potvrzení, že se jedná o tyto situace:
1. Při přechodu projektu z P0 (oznámený) na P1 (zapsaný) 
2.  Generování nového oznámení

**Comment by motyc** [comment]
@pbartosova Ano.
