### ISSUE TITLE
Doladit nastavení heatmapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#660]
Je třeba revidovat nastavení tak, aby bylo blíže chování https://digiarchiv.aiscr.cz/results?mapa=true

Problém není primárně v dynamice změny heatmapy (zohlednění polohy okna), ale v nalezení takového nastavení barevné škály, které lépe vyhovuje dané implementaci. V současném stavu jsou místa s malou hustotou snadno zaměnitelná s oblastmi zcela bez dat, což není vyhovující pro orientaci uživatele.

https://github.com/ARUP-CAS/aiscr-digiarchiv-2/blob/main/web/src/main/ng/src/assets/config.json

**Comment by jiri-bartos-huld** [comment]
Tento pozadavek vyzaduje dalsi analyzu a proto bych ho zaradil samostatne-treba do samostatne objednavky. Protoze nejsme schopni tento pozadavek v soucasnosti nacenit, protoze nevime v cem je rozdilene chovani.

**Comment by jiri-bartos-huld** [comment]
Toto je velmi tezke nacenit: navrhuji pouze revidovat konfiguraci  a pokusit se dosahnout stejneho vzhledu. Nacenuji tedy na 4hodiny. Vetsi zasahy do vzhledu nejsou naceneny.
V soucasnosti pouzivame knihovnu: https://github.com/Leaflet/Leaflet.heat/tree/gh-pages/src
ale digiarchiv pouziva HeatmapOverlay coz je angular nadstavba


provedl jsem pokus o sladeni heatmapy:
https://github.com/ARUP-CAS/aiscr-webamcr/pull/1140

**Comment by jiri-bartos-huld** [comment]
Doporucuji nejprve vyzkouset #1140, pokud bude zmena dostatecna, tak issue uzavrit, jinak pokracovat v naceneni.

**Comment by motyc** [comment]
@jiri-bartos-huld Po nasazení potvrdím, zda to pomohlo, jinak souhlasím.

**Comment by motyc** [comment]
@jiri-bartos-huld @pesikj Nyní se mi vůbec nedaří heatmapu načíst. U projektů se při oddálení nekonečně točí kolečko nad mapou, u arch_z se sice kolečko zatočí a zmizí, ale vidět nic není. Nechám to tedy v objednávce, ale je to kombinace bugu a ladění.

**Comment by pesikj** [comment]
@motyc Pokusil jsem se bug opravit, prosím o test, zda je to takto v pořádku.

**Comment by motyc** [comment]
@pesikj Bohužel to nezabralo. Resp. jediná změna je, že u projektů už se nekonečně netočí načítání, ale vidět heatmapa není vůbec.

**Comment by motyc** [comment]
Díval jsem se na tu heatmapu - je to o něco lepší, ale problémy zůstávají dva:
- [ ] Nefunguje pro PIAN (http://192.168.254.30:8080/arch-z/akce/detail/C-9723781A)
- [ ] Ten radius by stále chtěl o něco zvětšit aby i při větším přiblížení pokrytí více odpovídalo tomuto:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/462db109-3c61-4437-a74a-dd69849f0429)

spíše než tomuto:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/42b0f80e-0d2a-49c4-a451-71e795b755fb)

- [ ] Zároveň je však třeba si ještě trošku pohrát s nastavením barevné škály, aby byla více logaritmická (normalizovaná), protože nyní se fialová (nízké hodnoty nepoužívá skoro vůbec) a naopak to velmi brzo přechází do maxim (červená). Optimální cílový stav je něco jako toto:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/007dedc0-30d1-4475-b058-2d77a429b23d)

Odpovídá to následujícímu nastavení, ale jde o jinou knihovnu:
```javascript
"heatmapOptions":
{
	"radius": 0.5,
	"maxOpacity": 0.8,
	"minOpacity": 0.15,
	"scaleRadius": true,
	"useLocalExtrema": true,
	"latField": "lat",
	"lngField": "lng",
	"valueField": "count",
	"gradient":
	{
		"0.0": "rgb(255,0,255)",
		"0.15": "rgb(0,0,255)",
		"0.25": "rgb(0,255,0)",
		"0.45": "rgb(255,255,0)",
		"0.65": "rgb(255,170,0)",
		"0.95": "rgb(255,0,0)",
		"1.0": "rgb(255,0,0)"
	}
},
```

**Comment by pesikj** [comment]
@motyc Podle mě by bylo jednodušší umožnist nastavení těchto konstant v administrátorském rozhraní. Pak můžete sám najít optimální kombinaci. Pokud bychom to měli ladit společně a kvůli každé změně dělat deployment, tak to bude trvat násobně déle.

**Comment by motyc** [comment]
Telefonicky dohodnuto, že se vytvoří model system_settings, kde bude celý konfigurační kod v jednom poli. Model pak půjde případně využít i pro další obdobné případy.

**Comment by motyc** [comment]
### Testování v0.3.5z18
- [ ] Místo požadované knihovny https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html užívané v Digitálním archivu se používá https://github.com/Leaflet/Leaflet.heat - to je důvod proč se nedaří najít vyhovující nastavení, protože užívaná knihovna nabízí velmi omezené možnosti nastavení. Prosím o výměnu, pokud to něco vyloženě neblokuje, protože i přes veškerou snahu nejde nastavení se současnou knihovnou vyladit do vyhovujícího stavu.
- [ ] http://192.168.254.30:8080/admin/core/customadminsettings/ - bylo by dobré vypisovat i sloupce `Item group` a `Item id`, ať se v tabulce dá nějak vyznat.
- [ ] `arch_z_heatmap_options` se nikde v kódu nevyskytuje, všude je jen `projekty_heatmap_options`; u akce se mi nyní nedaří heatmapu vůbec zobrazit
- [ ] Heatmapa se nikdy nenačte hned po vstupu na obrazovku, ale až po prvním pohybu mapou.

**Comment by pesikj** [comment]
>  Místo požadované knihovny https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html užívané v Digitálním archivu se používá https://github.com/Leaflet/Leaflet.heat - to je důvod proč se nedaří najít vyhovující nastavení, protože užívaná knihovna nabízí velmi omezené možnosti nastavení. Prosím o výměnu, pokud to něco vyloženě neblokuje, protože i přes veškerou snahu nejde nastavení se současnou knihovnou vyladit do vyhovujícího stavu.

@jiri-bartos-huld Jirko, je možné ty knihovny vyměnit?

**Comment by jiri-bartos-huld** [comment]
predelano na https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html u
@motyc  @pesikj 
Dobry den, muzete mi prosim poslat nejaky rozumny  options pro heatmapu, pokud se pokusim pouzit tento pro projekty, ale neni to ono:
"heatmapOptions":
{
	"radius": 0.5,
	"maxOpacity": 0.8,
	"minOpacity": 0.15,
	"scaleRadius": true,
	"useLocalExtrema": true,
	"latField": "lat",
	"lngField": "lng",
	"valueField": "count",
	"gradient":
	{
		"0.0": "rgb(255,0,255)",
		"0.15": "rgb(0,0,255)",
		"0.25": "rgb(0,255,0)",
		"0.45": "rgb(255,255,0)",
		"0.65": "rgb(255,170,0)",
		"0.95": "rgb(255,0,0)",
		"1.0": "rgb(255,0,0)"
	}
},

projekty:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/7e1e4b4a-4a77-4503-a2cb-8809cfdc6cd4)

**Comment by pesikj** [comment]
@jiri-bartos-huld @motyc 

Dle naší dohody může fine-tunning parametrů heat-mapy provádět @motyc, z toho důvodu jsme to přenášeli do admin rozhraní. Jde jen o to vyměnit knihovnu.

**Comment by motyc** [comment]
@jiri-bartos-huld S tím nastavováním si hlavu nelamte, stačí to navázat na nastavení zde: http://192.168.254.30:8080/admin/core/customadminsettings/2/change/

Já už si s tím pak pohraju a doladím to, aby to vypadalo pěkně. Vy tím nemusíte ztrácet čas. Když teď budu mít všechny možnosti nové knihovny, určitě se mi to nějak povede.

**Comment by motyc** [comment]
@jiri-bartos-huld Ještě doplním jednu drobnost: http://192.168.254.30:8080/arch-z/akce/detail/X-M-9000000023A - pokud jsem na zobrazení heatmapy a vypnu související vrstvu, heatmapa nezmizí a zůstane jakoby zaseklá v zobrazení; pokud vrstvu vypnu při jiném zobrazení, heatmapa se nenačte (což je správně)

**Comment by motyc** [comment]
### Test v0.3.5z47
Knihovna je vyměněná, ale mám pocit, že nikdo nečte moje komentáře k testování. Byla tak opraven jen jeden bod z několika referovaných.
- [ ] http://192.168.254.30:8080/admin/core/customadminsettings/ - bylo by dobré vypisovat i sloupce `Item group` a `Item id`, ať se v tabulce dá nějak vyznat.
- [ ] `arch_z_heatmap_options` se nikde v kódu nevyskytuje, všude je jen `projekty_heatmap_options`; pro heatmapy s PIAN by se mělo používat `arch_z_heatmap_options`
- [ ] Heatmapa se nikdy nenačte hned po vstupu na obrazovku, ale až po prvním pohybu mapou.
- [ ] http://192.168.254.30:8080/projekt/zapsat - Nastavování již jde ok a vše se chová smysluplně. Problém je nyní v tom, že se zdají být nějaká nesprávná data, se kterými heatmapa pracuje. Zde je dobře vidět, že to vypadá, že v Plzni nejsou žádné projekty:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f75597c3-b6a0-4d84-bba7-684ebd5f6c65)

Když ale zazoomuji blíže, je naopak vidět, že projektů je tam oproti okolí velmi mnoho:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7ac7e615-3efe-4c98-b44d-0eea7d6db8cc)

Je proto zřejmé, že data pro heatmapu se negenerují správně.

**Comment by motyc** [comment]
### Test v0.3.5z61
- [ ] Heatmapa se nikdy nenačte hned po vstupu na obrazovku, ale až po prvním pohybu mapou.

Jinak již vše v tomto issue ok.

**Comment by jiri-bartos-huld** [comment]
Pripraveno na MR

**Comment by motyc** [comment]
v0.3.5z67 - aktuálně je to zase tak, že mapa naskočí bez ohledu na počet záznamů a po prvním pohybu mapy se teprve vypne. Např.: http://192.168.254.30:8080/arch-z/akce/detail/C-202011498A

**Comment by jiri-bartos-huld** [comment]
Melo by byt opraveno
