### ISSUE TITLE
Tlačítka pro přidání osoby do hesláře

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#670]
Tlačítko "+" u pole chybí v těchto případech:
/dokument/zapsat/do-akce/<str:arch_z_ident_cely>		Autoři
/dokument/zapsat/do-projektu/<str:proj_ident_cely>		Autoři
/dokument/edit/<str:ident_cely>		Autoři
/dokument/edit/<str:ident_cely>		Dokumentované osoby
/dokument/detail/<str:ident_cely>		Autoři
/pas/zapsat		Nálezce
/pas/edit/<str:ident_cely>		Nálezce

Tlačítko "+" u pole je nadbytečné v těchto případech (v detailu nedává smysl):
/dokument/model/detail/<str:ident_cely>		Autoři

**Comment by sedmar** [comment]
Bude vyřešeno v rámci maintenance.

**Comment by motyc** [comment]
Neopomenout: https://github.com/ARUP-CAS/aiscr-webamcr/issues/343#issuecomment-1346707178
![image](https://user-images.githubusercontent.com/20186892/208233460-7236245c-7c18-4537-bd6c-e9dc0ebfae3e.png)

**Comment by pesikj** [comment]
@jnihnat Honzo, podívej se prosím na komentář https://github.com/ARUP-CAS/aiscr-webamcr/issues/670#issuecomment-1356121431.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Tlačítka jsou všude správně, nicméně po pokusu zapsat jakékoli jméno systém hlásí, že již existuje a do hesláře se nezapíše. Podotýkám, že nejde o kontrolu duplicit v modal okně, tam to funguje dobře. Ale pokud tato kontrola projde (tj. o duplicitu nejde), vyskočí žlutá hláška po zavření modalu.

**Comment by jnihnat** [comment]
@motyc 
Prosim tohle bych potreboval lepe popsat, protoze se mi to nedari nasimulovat.
Jak by to mnelo fungovat:
- do modalu zadate jmeno a prijmeni
- pokud je stejne, jako v DB uz je, tak se nic nezapise a ostavate na modalu s hlaskou
- pokud v DB neni, zapise se, modal se automaticky zavre a jmeno se doplni do pole.

Skousel sem na vice mistech a fungovalo mi to spravne. 
Dekuji

**Comment by motyc** [comment]
@jnihnat Zkusil jsem to teď znovu na http://192.168.254.30:8080/. Nevím, kde to testujete Vy, ale tam to v bodu 3 podle Vašeho příspěvku místo zápisu do DB vypíše žlutou hlášku "Jméno již existuje", i když to stoprocentně není pravda. Platí to bez ohledu na místo užití (snadno k otestování např. na http://192.168.254.30:8080/pas/zapsat).

**Comment by jnihnat** [comment]
skousel sem na lokaly, kde mam nejnovejsi dev verzi, tam to uz nejspis opravil @pesikj pres: #898 byla tam chyba pri uladani osoby. Prosim pockejte az se nasadi nova verze a potom retestujte znova.
Dekuji
