### ISSUE TITLE
PAS - hloubka - chyba v testu při odeslání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#671]
http://192.168.254.30:8080/pas/detail/M-202101534-N00281

Pokud je v poli hloubka údaj "0", systém jej při pokusu o odeslání nálezu (N1->N2) chápe jako null hodnotu a nález nejde odeslat.

**Comment by sedmar** [comment]
Bude řešeno v rámci Maintenance.
