### ISSUE TITLE
Chyba funkce "připojit PIAN podle ID"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#672]
Pokud vyrobím N (nepotvrzený) PIAN a použiji funkci připojit PIAN podle ID, v mapě zůstane N PIAN bez vazby. Správným řešením je funkci zpřístupnit pouze tehdy, nemá-li DJ PIAN (v takovém případě musí nejdříve vždy dojít k odpojení PIAN, kde to ošetřené máme).

**Comment by sedmar** [comment]
@motyc Lze parafrázovat problematiku z pohledu uživatele, abychom správně pochopili co je chybou a věděli jaký je požadovaný stav?

**Comment by motyc** [comment]
@sedmar V principu jde o to, že PIAN ve stavu N by neměly v systému vystupovat nikdy samostatně bez vazeb. Zůstala nám tam ale skulina, kdy k tomu omylem dojít může.

V praxi nastává to, že pokud na dokumentační jednotku s již připojeným PIAN použiji funkci "Odpojit PIAN", dojde (správně) ke smazání N PIAN, pokud nemá jiné vazby. Pokud ale místo toho použiji funkci "Připojit PIAN podle ID", tak se nic netestuje, PIAN se připojí nový místo existujícího a z původního PIAN se stane sirotek. Abychom to nemuseli ošetřovat složitěji, stačí přidat podmínku, že funkce "Připojit PIAN podle ID" půjde použít jen v případě, že dokumentační jednotka nemá žádný PIAN. To uživatele vždy donutí použít před tím funkci "Odpojit PIAN", kde je to správně ošetřeno. Obě funkce jsou dostupné v menu u dokumentační jednotky.

Takto je to pochopitelné, nebo to mám ještě zkusit jinak, třeba i se screenshoty?

**Comment by sedmar** [comment]
@motyc Takto to stačí a bude to tedy vyřešeno v rámci maintenance.
