### ISSUE TITLE
Tlačítka zpět změnit na pevné odkazy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#676]
Většina tlačítek "Zpět" je v rámci aplikace nastavena na funkci `goBack()`. To je nevyhovující z více důvodů - není to vhodné při otevírání nových oken, může to vést k nezáměrnému opětovnému odeslání formuláře apod. Proto bude lepší vést vše jako odkazy s pevným cílem, který se bude odvozovat ze vztahu v DB (parent/child).

Přesné zadání obsahuje tato tabulka: https://docs.google.com/spreadsheets/d/1hJVJLa7W7I2RYRAATgmb-sAqAa1c2Unc/edit#gid=1416271806

**Comment by pesikj** [comment]
Odhad: 5 hodin.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z16)

- [ ] http://192.168.254.30:8080/dokument/model/edit/C-3D-202300001 - chybně vrací na http://192.168.254.30:8080/dokument/model/ místo správného http://192.168.254.30:8080/dokument/model/detail/C-3D-202300001
- [ ] http://192.168.254.30:8080/historie/lokalita/M-N1000004 - tlačítko zpět úplně chybí
- [ ] http://192.168.254.30:8080/pas/zapsat - tlačítko zpět úplně chybí
- [ ] http://192.168.254.30:8080/projekt/zapsat - tlačítko je posunuté oproti vedlejšímu

**Comment by motyc** [comment]
### Test v0.3.5z40
- [ ] http://192.168.254.30:8080/historie/soubor/529773 - tlačítko vrací na http://192.168.254.30:8080/dokument/detail/C-3D-202300002, místo na http://192.168.254.30:8080/dokument/model/detail/C-3D-202300002
- [ ] http://192.168.254.30:8080/historie/soubor/338636 - odstranit "Zpět na detail projektu" - je to duplicitní vůči tlačítku "Zpět"
- [ ] http://192.168.254.30:8080/pas/zapsat - zpět má vracet na http://192.168.254.30:8080/pas/

Jinak ok.

**Comment by motyc** [comment]
### Test v0.3.5z41
- [ ] Teď vůbec nefunguje historie souborů ve 3D: http://192.168.254.30:8080/historie/soubor/529841 `'str' object has no attribute 'contains'`
