### ISSUE TITLE
Nastavit základní rozložení sloupců tabulek a výchozí řazení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#678]
Vyjmenovány jsou vždy dostupné sloupce.
**Tučně** jsou sloupce, které mají být viditelné (zapnuté) jako výchozí.
V (závorce) jsou sloupce s ovládacími prvky.
Samostatně je uvedeno výchozí řazení pro jednotlivé položky z menu (varianty zobrazení výběru).

### Výběrové tabulky
- [x] http://192.168.254.30:8080/projekt/vyber
-- **ident_cely**, **stav**, **typ_projektu**, uzivatelske_oznaceni, **hlavni_katastr**, katastry, **planovane_zahajeni**, **datum_zahajeni**, **datum_ukonceni**, termin_odevzdani_nz, **podnet**, **oznaceni_stavby**, lokalizace, parcelni_cislo, **organizace**, vedouci_projektu, kulturni_pamatka
-- Schválit oznámení: `sort=planovane_zahajeni&sort=hlavni_katastr&sort=ident_cely`
-- Přihlásit projekt: `sort=planovane_zahajeni&sort=hlavni_katastr&sort=ident_cely`
-- Zahájit výzkum: `sort=hlavni_katastr&sort=ident_cely`
-- Ukončit terén: `sort=hlavni_katastr&sort=ident_cely`
-- Spravovat akce: `sort=hlavni_katastr&sort=ident_cely`
-- Uzavřít projekt: `sort=hlavni_katastr&sort=ident_cely`
-- Vybrat projekty: `sort=hlavni_katastr&sort=ident_cely`
-- Naše projekty: `sort=stav&sort=ident_cely`
-- Archivovat projekty: `sort=datum_ukonceni&sort=ident_cely`

- [x] http://192.168.254.30:8080/arch-z/akce/vyber
-- **ident_cely**, **stav**, pristupnost, uzivatelske_oznaceni, **hlavni_katastr**, katastry, specifikace_data, **datum_zahajeni**, **datum_ukonceni**, **organizace**, AkceVedouci.organizace, **hlavni_vedouci**, AkceVedouci.vedouci, **hlavni_typ**, **vedlejsi_typ**, **lokalizace_okolnosti**, ulozeni_nalezu, ulozeni_dokumentace, je_nz, odlozena_nz
-- Vybrat: `sort=katastr&sort=ident_cely`
-- Moje akce: `sort=stav&sort=ident_cely`
-- Naše akce: `sort=stav&sort=ident_cely`
-- Archivovat: `sort=datum_ukonceni&sort=ident_cely`

- [x] http://192.168.254.30:8080/arch-z/lokalita/vyber
-- **ident_cely**, **stav**, pristupnost, uzivatelske_oznaceni, **hlavni_katastr**, katastry, **nazev**, **typ_lokality**, **druh**, **zachovalost**, **jistota**
-- Vybrat: `sort=nazev`
-- Moje lokality: `sort=stav&sort=ident_cely`
-- Naše lokality: `sort=stav&sort=ident_cely`
-- Archivovat: `sort=nazev`

- [x] http://192.168.254.30:8080/pas/vyber
-- **(nahled)**, **ident_cely**, **stav**, predano, pristupnost, evidencni_cislo, **katastr**, **lokalizace**, **datum_nalezu**, **nalezce**, **predano_organizace**, **obdobi**, presna_datace, **druh_nalezu**, **specifikace**, pocet, poznamka, okolnosti, hloubka
-- Vybrat: `sort=katastr&sort=ident_cely`
-- Moje nálezy: `sort=stav&sort=ident_cely`
-- Naše nálezy: `sort=stav&sort=ident_cely`
-- Potvrdit: `sort=nalezce&sort=datum_nalezu&sort=ident_cely`
-- Archivovat: `sort=datum_nalezu&sort=ident_cely`

- [x] http://192.168.254.30:8080/pas/spoluprace/vyber
-- **stav**, **vedouci**, **vedouci.organizace**, **spolupracovnik**, **spolupracovnik.organizace** **(historie)**, **(aktivace)**, **(smazani)**
-- Spolupráce: `sort=organizace_vedouci&sort=spolupracovnik`

- [x] http://192.168.254.30:8080/dokument/model/vyber
-- **(nahled)**, **ident_cely**, **stav**, **typ_dokumentu**, **autori**, **organizace**, **rok_vzniku**, **popis**, **extra_data.format**, **extra_data.odkaz**, **extra_data.duveryhodnost**, extra_data.zeme, extra_data.region
-- Vybrat: `sort=organizace__nazev_zkraceny&sort=autori&sort=ident_cely`
-- Moje modely: `sort=stav&sort=ident_cely`
-- Naše modely: `sort=stav&sort=ident_cely`
-- Archivovat: `sort=ident_cely`

- [x] http://192.168.254.30:8080/dokument/vyber
-- (nahled), **ident_cely**, **stav**, pristupnost, datum_zverejneni, oznaceni_originalu, **autori**, **organizace**, **rok_vzniku**, extra_data.datum_vzniku, **popis**, poznamka, extra_data.cislo_objektu, rada, **typ_dokumentu**, material_originalu, extra_data.format, ulozeni_originalu, licence, let, extra_data.zachovalost, extra_data.nahrada, extra_data.pocet_variant_originalu, extra_data.meritko, extra_data.vyska, extra_data.sirka, extra_data.zeme, extra_data.region, extra_data.udalost_typ, extra_data.udalost, extra_data.rok_od, extra_data.rok_do, osoby, extra_data.odkaz, extra_data.duveryhodnost
-- Vybrat: `sort=typ_dokumentu&sort=ident_cely`
-- Moje dokumenty: `sort=stav&sort=ident_cely`
-- Naše dokumenty: `sort=stav&sort=ident_cely`
-- Archivovat: `sort=ident_cely`

- [ ] http://192.168.254.30:8080/ext-zdroj/vyber
-- **ident_cely**, sysno, **stav**, **typ**, **autori**, **rok_vydani_vzniku**, datum_rd, **nazev**, **editori**, **casopis_denik_nazev**, **casopis_rocnik**, **sbornik_nazev**, edice_rada, misto, vydavatel, typ_dokumentu, organizace, paginace_titulu, isbn, issn, link, poznamka
-- Vybrat: `sort=autor&sort=rok_vydani_vzniku&sort=nazev`
-- Moje zdroje: `sort=autor&sort=rok_vydani_vzniku&sort=nazev`
-- Naše zdroje: `sort=autor&sort=rok_vydani_vzniku&sort=nazev`
-- Potvrdit: `sort=autor&sort=rok_vydani_vzniku&sort=nazev`

### Tabulky s odkazy
(vždy řadit podle `ident_cely`; neuvádím sloupce s ovládacími prvky, pokud jsou v konkrétních případech, např. paginace u ext, odkazu)
- [ ] arch-z/radek-tabulky-odkaz (použito v /ext-zdroj/detail/, /dokument/detail/ a /projekt/detail/)
-- akce: **ident_cely**, **hlavni_katastr**, **datum_zahajeni**, **datum_ukonceni**, **hlavni_typ**
-- lokalita: **ident_cely**, **hlavni_katastr**, **druh**, **nazev**
- [x] dokument/radek-tabulky-odkaz (použito v /projekt/detail/, /arch-z/akce/detail/ a /arch-z/lokalita/detail/)
-- **ident_cely**, **typ_dokumentu**, **organizace**, **rok_vzniku**, **popis**
- [x] ext-zdroj/radek-tabulky-odkaz (použito v /arch-z/akce/detail/ a /arch-z/lokalita/detail/)
-- **ident_cely**, **autori**, **rok_vydani_vzniku**, **nazev**
- [x] projekt/radek-tabulky-odkaz (použito v /arch-z/akce/detail/ a /dokument/detail/)
-- **ident_cely**, **stav**, **hlavni_katastr**, **podnet**, **organizace**
- [x] pas/radek-tabulky-odkaz (použito v /projekt/detail/) - toto jen odhaduji, ale definici URL nevidím
-- **(nahled)**, **ident_cely**, **stav**, **katastr**, **datum_nalezu**, **nalezce**, **obdobi**, **druh_nalezu**

### Ostatní tabulky
- [x] Historie (stejné pro všechny verze)
-- **datum_zmeny**, **typ_zmeny**, **uzivatel**, **poznamka**
-- `sort=datum_zmeny`

- [x] Soubory (stejné pro všechny verze kromě "nahradit", které je jen u dokumentů a pas)
-- **nahled**, **nazev**, **mimetype**, **size_mb**, **rozsah**, **(historie)**, **(stáhnout)**, **(nahradit)**, **(smazat)**
-- vždy řadit podle `nazev`

- [x] Nálezy
-- **druh**, **specifikace**, **pocet**, **poznamka**, **(odstranit)**
-- vždy řadit podle `druh` + `specifikace` (na základě `heslar.razeni`)

- [x] Další vedoucí
-- **vedouci**, **organizace**, **(odstranit)**
-- vždy řadit podle `vedouci`

- [x] Výškové body
-- **ident_cely**, **typ**, **X**, **Y**, **Z**, **(odstranit)**
-- vždy řadit podle `ident_cely`

- [x] Tvary
-- **tvar**, **poznamka**, **(odstranit)**
-- vždy řadit podle `tvar`

**Comment by pesikj** [comment]
Odhad: 9 hodin

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z17)
- [ ] Po úpravě filtru se odebere nastavené řazení. Mělo by se uchovat z předchozího dotazu.
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber- poslední čtyři položky jsou v tabulce navíc (duplicitně):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/dd788e7d-0ae6-44f4-ad23-97c84387e523)
- [ ] http://192.168.254.30:8080/dokument/vyber - oznaceni_originalu - nemá být výchozí
- [ ] http://192.168.254.30:8080/dokument/vyber - seznam polí mizím mimo obrazovku a nejde v něm rolovat (nejde tak ani kompletně zkontrolovat)
- [ ] [Dokument vybrat](http://192.168.254.30:8080/dokument/vyber)
-- zdvojený otazník v URL (asi jde o chybu): http://192.168.254.30:8080/dokument/vyber??sort=organizace__nazev_zkraceny&sort=autori&sort=ident_cely
-- špatné výchozí řazení ve všech variantách kromě Archivovat
- [ ] http://192.168.254.30:8080/ext-zdroj/vyber - pro řazení se volá chybné pole (`autor`), místo správného (`autori`)
- [ ] `arch-z/radek-tabulky-odkaz` - `hlavni_typ` - pole je vždy prázdné
- [ ] `dokument/radek-tabulky-odkaz` - prosím ještě doplni náhled (jako první sloupec) - bude to velmi užitečné a zapomněl jsem na to
- [ ] `projekt/radek-tabulky-odkaz` - nesedí nastavení zobrazených polí
- [ ] Historie - řazení má být datum změny vzestupně
- [ ] Soubory - špatné pořadí sloupců s ovládacími prvky

**Comment by pesikj** [comment]
@motyc 

>  http://192.168.254.30:8080/dokument/vyber - oznaceni_originalu - nemá být výchozí

Výchozí nastavení je skrytí tohoto sloupce.

**Comment by pesikj** [comment]
@motyc 
>  arch-z/radek-tabulky-odkaz - hlavni_typ - pole je vždy prázdné

Tady nevím, jak je to myšleno. Ve sloupci hlavni_typ data jsou.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/02a8c112-4386-4fda-b50b-4fd53a8d6585)

**Comment by motyc** [comment]
### Test v0.3.5z40
- [ ] _Po úpravě filtru se odebere nastavené řazení. Mělo by se uchovat z předchozího dotazu._ - opraveno částečně. Nyní když mám http://192.168.254.30:8080/projekt/vyber?sort=hlavni_katastr&sort=ident_cely, tak po přidání filtru na záchranné projekty zmizí jedna podmínka, druhá se zachová: http://192.168.254.30:8080/projekt/vyber?typ_projektu=1137&sort=ident_cely
- [ ] http://192.168.254.30:8080/arch-z/akce/vyber - `AkceVedouci.organizace` a `AkceVedouci.vedouci` nemá být default zapnuto
- [ ] http://192.168.254.30:8080/dokument/vyber - je třeba opravdu řadit podle zadání (nyní opraveno pro Vybrat a Archivovat, ale jinde chybně):
-- Moje záznamy: `sort=stav&sort=ident_cely`
-- Naše záznamy: `sort=stav&sort=ident_cely`
- [ ] `projekt/radek-tabulky-odkaz` - do pole podnět se vypisuje nějaké číslo, místo obsahu pole `projekt.podnet`

Jinak ok.
