### ISSUE TITLE
U dokumentačních jednotek vydělit zvlášť možnosti přidávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#679]
U DJ pod nové tlačítko "+" samostatně vydělit tyto existující volby:
- Přidat nový PIAN
- Připojit PIAN z mapy
- Připojit PIAN podle ID
- Přidat komponentu
- Přidat ADB

V současném menu (tři tečky) zůstanou ostatní zbylé možnosti.

**Comment by pesikj** [comment]
@motyc Kde má být to tlačítko plus? Vedle tří teček?

**Comment by motyc** [comment]
@pesikj Ano, přesně tak.
