### ISSUE TITLE
Uprava stylu filtru projektu

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#68]
Je potreba upravit rozlozeni filtru v projekt/list. Domluvit s Davidem.

Aktualni podoba:
![Screenshot from 2021-05-10 11-05-59](https://user-images.githubusercontent.com/26173315/117635012-c3456500-b17f-11eb-8d70-876e838cc688.png)

**Comment by pkudela** [comment]
@Najiva abych mohl upravit layout fomulare, potrebuji pripravit do filters.py alespon zaklad html, stejne jako je to u ostatnich formularu, cili obal div class "row" a pod tim pro kazdy field div s class "col-sm-12", jakmile toto bude pripravene a David doda navrh layoutu pro jednotlive fieldy, pak to podle toho upravim. NIze posilam priklad co potrebuji z jineho formulare:
![image](https://user-images.githubusercontent.com/16591052/119107321-69665a00-ba1f-11eb-93e2-27a1831ee16f.png)

**Comment by pkudela** [comment]
@Najiva dale je potreba vytahnout button pro smazani filtru z formulare a umistit vedle buttonu pro rozbaleni filtru - to jsem jiz udelal, ale je potreba aby byl viditelny jen pokud je nektery z filtru vybran, pokud zadny filtr neni vybran/aktivovan, tak se button pro odstraneni filtru nezobrazi
![image](https://user-images.githubusercontent.com/16591052/119108159-31134b80-ba20-11eb-94f9-97e0b27d87cc.png)

**Comment by pkudela** [comment]
jakmile to budes @Najiva mit hotove, prehod issue zase na me, prosim

**Comment by Najiva** [comment]
Mas to tam.

**Comment by pkudela** [comment]
Layout je implementovan, nyni je grid na 2 sloupce, ceka se na predlohu formularu od Davida.

**Comment by motyc** [comment]
@pkudela Předpokládám, že počet sloupců gridu ještě můžeme upravit na základě podrobného zadání, viď?

**Comment by pkudela** [comment]
@motyc samozrejme, dyk jsem to psal o jedno vlakno vys :) "ceka se na predlohu formularu od Davida."

**Comment by motyc** [comment]
Řeší se již jinde, zavírám.
