### ISSUE TITLE
Zrušit pole soubor.nazev_puvodni

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#680]
- [x] Zrušit pole soubor.nazev_puvodní (vše je v historii).
- [x] U migrovaných dat (souborů) doplnit do historie první záznam podle stávajících údajů.
- [x] Pole skrýt v aplikaci.

**Comment by jnihnat** [comment]
@pesikj a @motyc co tak koukam, tak nikde to pole uz nevidim. Mnelo by teda byt ok.

**Comment by pesikj** [comment]
@motyc @jnihnat Souhlasím.

**Comment by motyc** [comment]
Prověřím to pak společně se zbytkem, ale může to tak být, protože se to částečně řešilo společně s migrací.
