### ISSUE TITLE
Chyba zobrazení počtu záznamů v tabulce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#681]
Přejdu na http://192.168.254.30:8080/projekt/vyber a počet záznamů se zobrazuje 135749 (vypadá správně), seřadím podle nějakého pole a počet se změní na 617128 (jednoznačně chyba).

Obdobně platí pro:
http://192.168.254.30:8080/dokument/model/vyber
http://192.168.254.30:8080/pas/vyber

**Comment by motyc** [comment]
Zdá se, že nemusí jít o špatný counter, ale že se možná opravdu záznamy zobrazují vícekrát. Při zadání http://192.168.254.30:8080/pas/vyber?ident_cely__icontains=C-202009779-N00021 dostanu jako výsledek duplicitně tentýž nález dvakrát:
![image](https://user-images.githubusercontent.com/20186892/195149499-dba79392-6315-486c-a450-46ce867a6a15.png)

**Comment by sedmar** [comment]
Bude řešeno v rámci maintenance.

**Comment by pesikj** [comment]
@motyc Ani jeden z případů se mi nepodařilo nasimulovat. Můžete prosím provést test znovu?

![image](https://user-images.githubusercontent.com/15179154/214675152-b216ad2f-0331-4fe2-8aca-bae67db1f710.png)

![image](https://user-images.githubusercontent.com/15179154/214675577-be7a7d49-562d-4ca3-85ea-c6793c71f48d.png)

**Comment by motyc** [comment]
@pesikj Už to vypadá v pořádku. Mohl pomoci ten refakor, co dělal @jnihnat. Zavírám
