### ISSUE TITLE
Překlady při nasazování nových verzí aplikace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#684]
Navazuje na #354 

Je třeba vhodným způsobem zajistit proces nasazování nových verzí aplikace tak, aby se mohly do překladů promítat změny v kódu, ale zároveň nedošlo ke smazání existujících překladů. Problém je hlavně s možnými konflikty (změna názvů klíčů apod.).

**Comment by motyc** [comment]
@sedmar Toto myslím patří do https://github.com/ARUP-CAS/aiscr-webamcr/projects/8#column-19191247

**Comment by motyc** [comment]
@sedmar Děkuji za vysvětlení. Asi bychom se tedy jen měli dohodnout, že pokud by k tomu mělo dojít znovu (bude nutno smazat soubory s překlady), měli bychom si to předem dát vědět a řešit to. Pokud začneme na překladech pracovat systematicky, byl by velký problém o práci najednou přijít. Jinak issue vrátím mezi testované a po pár dalších nasazeních to zavřu.

**Comment by motyc** [comment]
@sedmar Opět došlo k vymazání. Přijde mi, že to tedy moc nefunguje, nebo s tím nakládáte nějak nestandardně, což mi moc nevyhovuje.

**Comment by sedmar** [comment]
@motyc byla chyba v kódu který spouštěl aplikaci, tímto způsobem při každém novém nasazení došlo k vymazaní dat. Spouštění již opraveno a bude nasazeno v následující verzi. Verze 0.2.9h neobsahuje tuto změnu! Navíc bylo přidáno pravidelné zálohování překladů na lokální disk, což zabrání ztrátě dat i v případě výmazu perzistentního volume.
