### ISSUE TITLE
Uprava stylu resetu hesla

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#70]
HTML templaty ktere je potreba nastylovat:

![Screenshot from 2021-05-17 14-11-36](https://user-images.githubusercontent.com/26173315/118486411-df19af80-b719-11eb-9f99-48dbaeca7c01.png)

Link na URLs je z login screenu. Email s vygenerovanym URL pro reset se ulozi do souboru na 192.168.254.17:/home/amc/sink

**Comment by pkudela** [comment]
hotovo, @Najiva prosim o otestovani a pak zavrit, dik
