### ISSUE TITLE
Slinutí tlačítek se záhlavím v historii záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#711]
![image](https://user-images.githubusercontent.com/20186892/198276838-d0665ae8-7a95-43f2-8d04-a6bcfe39be82.png)

Platí všude, s výjimkou historie souboru.

**Comment by sedmar** [comment]
@motyc stačí přidat jednoduchý margin mezi tlačítka a horní lištu nebo vyžadováno složitější pozicování?

**Comment by sedmar** [comment]
@motyc dobře. Přesunuto tedy do maintenance
