### ISSUE TITLE
Při zasunutém menu se nedonačte mapa

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#712]
Pokud zasunu levé menu, u akce se nedonačte celá mapa (testováno v Chrome):

![image](https://user-images.githubusercontent.com/20186892/198277925-762969fa-0ad2-4cb8-9b9a-a63b18a2ae8c.png)

**Comment by jiri-bartos-huld** [comment]
Pripraveno k nasazeni

**Comment by jiri-bartos-huld** [comment]
vyreseno v ramci https://github.com/ARUP-CAS/aiscr-webamcr/issues/712
je soucasti dev

**Comment by motyc** [comment]
Bohužel mi to nefunguje, chování je stále stejné.

**Comment by jiri-bartos-huld** [comment]
Zde je videt oprava v chrome:
1./Zobrazim detail akce
2./zoomuji
3./nez dozoomuji tak dam zkryt leve menu
4./vse se nacte spravne
5./...

![deepin-screen-recorder_Select area_20230514234519](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/9bfd279f-c11b-4e27-8b45-dbf63a8c5f9f)
