### ISSUE TITLE
Hash pro soubory se ukládají s různým počtem znaků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#714]
Sjednotit tak, aby odpovídalo stávajícímu nastavení v AMČR (13 znaků).

![image](https://user-images.githubusercontent.com/20186892/198278984-0f90f404-3a7e-439f-8bd0-5056bf7128fa.png)

**Comment by jnihnat** [comment]
@motyc - muzeme to doplnit na 13 znaku pomoci "0" na zacatku?
Staci to tedka udelat jen pro nove vytvorene soubory? Stare by ostali s mene znaky? Na testu to predpokladam tedka nevadi a az se bude resit migrace souboru tak prepdokladam ze tam se bude koukat ci neni potreba neco menit.

**Comment by motyc** [comment]
@jnihnat Ano a ano. Aktuální data jsou jen testovací, takže ty netřeba zpětně opravovat.
