### ISSUE TITLE
Správa emailových notifikací pro vlastní uživatelský účet

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#720]
Uživatel by si měl mít možnost zvolit, které emaily a upozornění chce dostávat (pokud není zmíněno, emaily chodí vždy). Dostupné volby:
AMČR: archivace záznamů (E-A-xx)
AMČR-PAS: nové nálezy k potvrzení (E-N-01)
AMČR-PAS: archivace záznamů (E-N-02)
AMČR-PAS: nová žádost o spolupráci (E-N-05)
AMČR - Knihovna 3D: archivace záznamů (E-K-01)
Hlídací pes - Každý uživatel od archeologa výše (C, D, E) si může nastavit hlídacího psa na nově zapsané projekty na úrovni kraje, okresu či katastru (E-P-02). Email odchází ihned po potvrzení (schválení - P01) projektu.

Odpovídá #389 a navazuje na #269

**Comment by motyc** [comment]
@sedmar Toto issue mi přijde zbytečné a navrhuji ho zrušit. Vše se stejně řeší v #389

**Comment by sedmar** [comment]
@motyc Ano zrusime, bude reseno v ramci #389
