### ISSUE TITLE
Chyba ověření pole nálezce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#721]
Při posunu stavu (např. N1->N2; http://192.168.254.30:8080/pas/detail/C-202104256-N00007) se nekontroluje, zda je vyplněný nálezce, přestože pole je správně označeno žlutě v http://192.168.254.30:8080/pas/edit/C-202104256-N00007.

**Comment by sedmar** [comment]
Bude řešeno v rámci maintenance.
