### ISSUE TITLE
Export tabulky projektu

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#73]
Pridal jsem export do formatu json, xlsx a csv. 
1. XML zatim export toolem neni podporovane. 
2. Dalsi vec je ze export podle toho jak velka datova sada se exportuje muze trvat hodne dlouho (je to skousnutelne cca do 10 - 20 000 zaznamu) Projektu je > 160 000. Takze bude potreba to nejak omezit pro bezneho uzivatele.

**Comment by motyc** [comment]
1. XML lze zatím vynechat, není klíčové, pokud ostatní formáty máme. Může se to řešit i případnou vazbou na API.
2. OK. Zde musíme vymyslet, jak to z pohledu uživatele udělat a jaká je to zátěž na server. Proberme to prosím na schůzce.

**Comment by Najiva** [comment]
@motyc Xls export jsem opravil a pridal jsem do tooltipu:

Export výběru (při výběru většího množství záznamů může trvat delší dobu)
