### ISSUE TITLE
Úprava sekvencí pro ident_cely

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#732]
Některé tabulky se sekvencemi pro ident_cely jsou nedořešené, případně jsou řešené nevhodně. Spolu s tím revidovat principy přidělování ident_cely i v dalších případech. Cílem je zajistit persistenci ident_cely u všech hlavních typů záznamů. Zároveň je však třeba myslet na možnost importu dat (záznamy s dočasnými ident_cely nikdy nemohou být importovány, tam tedy takové opatření není třeba).

### Dočasné ident_cely
- [x] Řešit v DB přes samostatné sekvence (nevázat na id, kde nově nejsou sekvence pojmenované a celkově by mohlo spojení ident_cely s id činit problémy).
- [x] Sekvence nastavit s počátkem na 1 a maximem na 999999999
- [x] Při změně dočasného ident_cely na trvalý vždy uložit původní dočasný ident_cely do pole `historie.poznamka` (k vytvářenému záznamu o změně stavu).
- [x] [projekty](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely#docasny-ident)
-- `"X-" + region + "-" + projekt_xident_seq (na 9 číslic doplnit nulami)`
-- např.: X-M-000001234
- [x] [dokumenty](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely#docasny-ident-1)
-- `"X-" + region + "-" + rada + "-" + dokument_xident_seq (na 9 číslic doplnit nulami)`
-- např.: X-M-TX-123456789
- [x] lokality
-- `"X-" + region + "-" + typ + lokalita_xident_seq (na 9 číslic doplnit nulami)`
-- např.: X-C-L123456789
- [x] PIAN
-- `"N-" + cislo zm50 (bez "-") + "-" + pian_xident_seq (na 9 číslic doplnit nulami)`
-- např.: N-1224-123456789
- [x] samostatné akce
-- `"X-" + region + "-9" + akce_xident_seq (na 9 číslic doplnit nulami) + "A"`
-- např.: X-C-9123456789A
- [x] externí zdroje
-- `"X-BIB-" + externi_zdroj_xident_seq (na 9 číslic doplnit nulami)`
-- např.: X-BIB-123456789

### dokument_sekvence
- [x] sloupec `rada` změnit na typ integer + not null + FK na `heslar.id`
- [x] doplnit sloupec `region` varchar(1) not null + check (omeznení) na hodnoty C/M
- [x] unique kombinace `rada` + `region` + `rok`
- [x] opravit v aplikaci přidělování ident_cely podle aktualizované struktury tabulky
- [x] výchozí sekvence nastavit na 1 (při prvním zápisu přes aplikaci se správně aktualizuje)
- [x] nastavit sekvence dostatečně dopředu (nebo to dělat aplikačně)

### projekt_sekvence
- [x] přejmenovat `rada` na `region`
- [x] unique kombinace `region` + `rok`
- [x] sekvence nastavit na maximum podle dat pro daný region a rok
- [x] nastavit sekvence dostatečně dopředu (nebo to dělat aplikačně)

### lokalita_sekvence
- [x] doplnit, sloupce budou:
-- `id` integer not null (PK)
-- `region` varchar(1) not null + check (omeznení) na hodnoty C/M
-- `typ` integer FK (heslar.id) - jedná se o odkaz na heslář lokalita_typ
-- `sekvence` integer not null
- [x] unique kombinace `region` + `typ`
- [x] zohlednit tabulku v aplikaci při přidělování trvalých ident_cely pro lokality (princip přidělování stejný jako u [projektu](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely#permanentny-ident))
- [x] výchozí sekvence nastavit na 1 (při prvním zápisu přes aplikaci se správně aktualizuje)

### pian_sekvence
- [x] unique kombinace `kladyzm_id` + `katastr`

### akce_sekvence
- [x] doplnit, sloupce budou:
-- `id` integer not null (PK)
-- `region` varchar(1) not null + check (omeznení) na hodnoty C/M + unique
-- `sekvence` integer not null
- [x] výchozí sekvence nastavit na 1 (při prvním zápisu přes aplikaci se správně aktualizuje)
- [x] zohlednit tabulku v aplikaci při přidělování trvalých ident_cely pro samostatné akce (princip přidělování stejný jako u [projektu](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely#permanentny-ident))

### externi_zdroj_sekvence
- [x] doplnit, sloupce budou:
-- `id` integer not null (PK)
-- `sekvence` integer not null
- [x] výchozí sekvence nastavit na 1 (při prvním zápisu přes aplikaci se správně aktualizuje)
- [x] zohlednit tabulku v aplikaci při přidělování trvalých ident_cely pro externí zdroje (princip přidělování stejný jako u [projektu](https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely#permanentny-ident))

**Comment by sedmar** [comment]
@motyc  navrhujeme úpravu titulku na "Úprava tabulek se sekvencemi pro iden_cely" a budeme to řešit jako nový požadavek, protože to chápeme jako nové zadání v rámci kterého se opraví z toho plynoucí nedostatky.  Z podstaty nelze opravovat věci co jsou nedořešené.

**Comment by motyc** [comment]
@sedmar Souhlasím, kloudné zadání k tomu nebylo.

**Comment by jnihnat** [comment]
@motyc ohledne docasnych identu, mame tedka na produkci zaznamy s docasnymi identami? Jde mi o nasledovne:
- pokud jo budeme mit 2 zapisy, nebo udelat script pro jejich "precislovani"
- pokud mame a nechceme precislovat budeme mit dvoji implementaci pro url /id/<str:ident_cely> pro redirect podle identu
- pokud na produkci nic takove nemame, tak bych stare zaznamy neresil ak souhlasite

**Comment by motyc** [comment]
@jnihnat To je dobrá poznámka, ale zásadní problém by to snad být neměl. Záznamy s dočasnými identy na produkci jsou, ale časem stará verze přirozeně vymizí a ničemu by to nemělo vadit. Obě verze identů by mělo jít poznat stejným regulárním výrazem, pokud bude vhodně napsaný. Když to vezmu postupně, tak:
- **projekty** - původní je: `"X-" + region + "-" + RRRR + 00000` (např. X-C-202252277), nový je: `"X-" + region + "-" 000000000` (např. X-C-123452277) - je tedy obecnější, ale z pohledu výrazu stejný
- **dokumenty** -  původní je: `"X-" + region + "-" + rada + "-" + RRRR + 00000` (např. X-M-TX-202106594), nový je: `"X-" + region + "-" + rada + "-" + 000000000` (např. X-M-TX-123406594) -  opět jen obecnější
- **lokality** - původní je: `"X-" + region + "-" + typ + 0000000` (např. X-M-L106594), nová je: `"X-" + region + "-" + typ + 0000000000` (např. X-M-L000106594) - zde jsem udělal v zadání drobnou chybu a odchýlil se omylem od původního principu z hlediska užívání spojovníku za typem - to jsem nyní v úvodním příspěvku opravil a spojovník dal pryč; liší se tedy jen délka čísla, což nevím, jestli regulárnímu výrazu vadí
- **PIAN** -  původní je: `"N-" + ZM50 + "-" + 000000` (např. N-1234-456789), nový je: `"N-" + ZM50 + "-" + 000000` (např. N-1234-000456789) - opět se liší jen délka čísla
- **samostatné akce** -  původní je: `"X-" + region + "-9" + 000000 + "A"` (např. X-C-9969458A), nový je: `"X-" + region + "-9" + 000000000 + "A"` (např. X-C-9000969458A) - opět jen různá délka čísla
- **externí zdroje** -  původní je: `"X-BIB-" + 0000000` (např. X-BIB-0926116), nový je: `"X-BIB-" + 000000000` (např. X-BIB-000926116) - opět jen různá délka čísla

Když to shrnu, tak pokud bychom dělali přečíslování, museli bychom podle toho rovnou i nastavovat sekvence, aby nemohla vzniknou duplicita. To mi přijde vlastně úplně zbytečné, zvláště když stará dočasná ID postupně zmizí a věc se sama vyřeší. Regulární výrazy to může ovlivnit u lokalit, PIAN, samostatných akcí a externích zdrojů, ale jejich úprava by snad měla být poměrně snadná, protože vždy jde jen o prodloužení číselné části. Takže bych asi raději šel touto cestou.

**Comment by jnihnat** [comment]
jeste jeden maly dotaz, permanentni sekvence chceme ponechat na starem poctu znaku? napr akce mame docasne 9 a permanentne 7.

**Comment by motyc** [comment]
Ano, je to záměr a ten důvod je, že stálé sekvence nikdy nepřesáhneme. U těch dočasných mohou čísla rychle růst, protože stačí párkrát kliknout a sekvence snadno naroste, byť stálý ident nikdy nebude přidělen.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5o)
Chování je víceméně dobré až na drobnosti. V prvním příspěvku je označeno vše, co je ok, ostatní nezaškrtané buď nešlo testovat, nebo je v tom nějaký problém.

- [ ] Abych mohl testování dokončit, potřebuji SELECT přístup pro uživatele cz_archeologickamapa_api_view k (zařídit jako výchozí stav):
-- tabulce dokument_sekvence
-- tabulce lokalita_sekvence
-- tabulce akce_sekvence
-- tabulce externi_zdroj_sekvence
-- všem sekvencím
- [ ] projekt_sekvence - nejsou nastaveny výchozí hodnoty pro roky 2026+ - jak budeme řešit? Vygeneruje to aplikace s prvním projektem daného roku sama (ideální řešení)? Pokud ano, měli bychom naopak záznamy pro 2024 a 2025 odmazat.
- [ ] U trvalých ident je špatně řešeno vyhledání prvního čísla k přidělení (testování u sam. akcí). Musí to být tak, že se začne od 1 a hledá se první volná pozice. Ta se využije a aktualizuje se tabulka sekvence. S každým dalším číslem se postupuje stejně. Je to takto třeba řešit kvůli importovaným datům, které mají ident nastavený výše v řadě a pod nimi je velká mezera. Nesmí se tedy nikdy zohledňovat existující maximum. Případné budoucí kolize, které mohou vzniknou smazáním importovaného záznamu, nám pomůže řešit plné verzování, které budeme mít ve Fedoře.

**Comment by jnihnat** [comment]
@motyc prominte ale tohle:
U trvalých ident je špatně řešeno vyhledání prvního čísla k přidělení (testování u sam. akcí). Musí to být tak, že se začne od 1 a hledá se první volná pozice. Ta se využije a aktualizuje se tabulka sekvence. S každým dalším číslem se postupuje stejně. Je to takto třeba řešit kvůli importovaným datům, které mají ident nastavený výše v řadě a pod nimi je velká mezera. Nesmí se tedy nikdy zohledňovat existující maximum. Případné budoucí kolize, které mohou vzniknou smazáním importovaného záznamu, nám pomůže řešit plné verzování, které budeme mít ve Fedoře.
je v kolizi s 
sekvence nastavit na maximum podle dat pro daný region a rok

tak bud chci maximum nebo ho nechci, pred tim to bylo tak ze se bralo z mezer, predelal jsem na maxima a tedka mam predelavat naspatek? To mi pak pripada mit zbytecnou tu sekvenci kdyz mam porad kontrolovat stejne jestli nekde neni mezera... Bud teda berme maximum nebo ne, nexhapu biznisove proc nam vadi nejaka mezera, pokud mame stale dostatek mista do maxima, tak bych to osobne neresil. Klidne si k tomu muzeme i zavolat.

**Comment by motyc** [comment]
@jnihnat Máte pravdu, nepřesně jsem to napsal. Samozřejmě by to v kolizi bylo, pokud bychom ale nemluvili o různých sekvencích.

Toto platí pouze pro projekty:
> sekvence nastavit na maximum podle dat pro daný region a rok

Druhá varianta platí tam, kde je napsáno (všechny trvalé kromě projektů):
> výchozí sekvence nastavit na 1 (při prvním zápisu přes aplikaci se správně aktualizuje)

Proto se také popis v obou případech lišil. U projektů importy neprobíhají, proto to tam není třeba řešit. U ostatních typů záznamů však ano a byl by to problém. Koukal jsem se do produkční DB a třeba u samostatných akcí by to problém byl. Podstata těch pevných sekvencí je, že se mezery zkontrolují pouze jednou a sekvence už se nikdy nevrací, tj. teoreticky vyplníme starší mezery v automaticky generovaných ident_cely ale nikdy nedosáhneme na importovaná data, která jsou vložená s velkým odstupem (v sekvenci je záměrně velká mezera). Úplně nejsprávnější by bylo přenést i aktuální pozici sekvence z produkční verze, to má ale případně smysl až při ostré migraci, kdy můžeme ad hoc upravit sekvenční tabulky na správné počáteční hodnoty. Celé řešení se tím však nijak nezmění.

Klidně si ale zavolejme a zkusím vše lépe vysvětlit. Chápu, že něco může působit divně a je mi líto, že jsme si to nevysvětlili pořádně hned. Jsem na mobilu na příjmu.

**Comment by motyc** [comment]
Narazili jsme na chybu, kdy nejde schválit http://192.168.254.30:8080/projekt/detail/X-M-202374757. V logu je `psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "projekt_ident_cely_key"
DETAIL:  Key (ident_cely)=(M-202300002) already exists.`

Bude to asi souviset s diskusí výše.

**Comment by jnihnat** [comment]
@motyc upraveno teda podle dohody v #1151 
jak to teda bude fungovat:
- nejprve se skusi dohledat sekvence. Pokud sekvence existuje bere dalsi cislo a kontroluje pro jistotu ci uz neexistuje dany ident. Pokud jo hleda se dalsi mezera
- pokud sekvence neni vytvori se bud s 1 nebo s nejblizsi mezerou
- Bude teda potrebne nastavit prve sekvence rucne, pripadne upravit az se nasetujou s prvym zaznamem, protoze je mozne ze se najde prvni mezera po smazanym zazname.
- Co se tyce sekvenci kde se berou roky, tak pro 2024+ nebude potreba nastavovat pokud chceme aby se zacalo od 1
