### ISSUE TITLE
Správa uživatelů - notifikace

### ISSUE THREAD

**Issue by pesikj** [ARUP-CAS/aiscr-webamcr#736]
- [ ] Doplnit správu oprávnění k příjmu oznámení o registraci uživatelů (zohlednit při zasílání mailů podle https://github.com/ARUP-CAS/aiscr-webamcr/issues/389)
- [ ] Doplnit správu emailových notifikací, tj. možnost nastavení pro jednotlivé uživatele (volby viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/389)

**Comment by motyc** [comment]
@pesikj Pokud se budeme řídit podle https://github.com/ARUP-CAS/aiscr-webamcr/issues/384#issuecomment-1325290406, měl by být první bod řešený jako skupina (podobně jako "Úprava textů").

**Comment by motyc** [comment]
@pesikj Myšleno to bylo jako druhá varianta.

**Comment by pesikj** [comment]
@motyc Může to být takto? Je to stránka z editací uživatele dole (jsou tam i check-boxy navázané na uživatele).

![image](https://user-images.githubusercontent.com/15179154/208311731-4cd494a4-d6b8-43f3-87b5-e739a818aa2f.png)

**Comment by motyc** [comment]
@pesikj Ano, to je myslím pro administraci bez problémů... Jen prosím nezapomeňte select omezit pouze na emaily, kde je vůbec volba přípustná (E-A-01, E-A-02, E-N-01, E-N-02, E-N-05, E-K-01, E-U-04).

E-P-02 se pak bude týkat hlídacího psa, ale to řešíme jinde.

**Comment by motyc** [comment]
@pesikj @sedmar Toto asi není nasazené, přestože označeno k testu.

**Comment by pesikj** [comment]
@motyc Nasazené to je, viz screenshot.

![image](https://user-images.githubusercontent.com/15179154/208425503-ac233aec-44a2-4d4b-bf82-49945d46bb1a.png)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Ve formuláři zůstalo nepotřebné toto:
![image](https://user-images.githubusercontent.com/20186892/208667673-571714e6-dc5f-4eeb-8ca2-0de24ff4fd52.png)
- [ ] Účtu přiřadím nějaké notifikace (např. E-U-04) a uložím -> znovu jakkoli edituji tentýž účet (stačí jen otevřít a kliknout na "Uložit" -> nastavení notifikací zmizí; jde asi o to, že se nastavení přepíše posledními třemi řádky a původní nastavení se nezachová

Funkčnost nastavení lze testovat až s #389

**Comment by pesikj** [comment]
@motyc Má být možné skutečně deaktivovat E-U-04? Tato notifikace je mezi seznamem `always_active`, takže to nastavení aktuálně nemá vliv. Je tedy nutné ji buď ze seznamu always_active vymazat nebo ji nedovolit změnit v admin rozhraní. Potenciálně taky hrozí, že když si notifikaci všichni administrátoři vypnou, nebude nikdo o nových uživatelích informován.
CC @MaxKosta

**Comment by motyc** [comment]
@pesikj Ano, má to být možné. V praxi to máme většinou nastaveno tak, že upozornění chodí např. jen na amcr@arup.cas.cz, což je hromadná schránka, kde se to pak vyřizuje podle potřeby a nespamuje to všechny administrátory.

Z 'always_active' to tedy bude třeba vyřadit (chápu, proč se to tam dostalo - jde o to, že původně se to celé řešilo jinak přes oprávnění, tak se to rozpadlo do dvou issue).

**Comment by motyc** [comment]
@pesikj Toto bohužel myslím nefunguje vůbec. U uživatelů se zapnutými notifikacemi ve správě účtu (http://192.168.254.30:8080/upravit-uzivatele/) se v administraci nic nezobrazuje (http://192.168.254.30:8080/admin/uzivatel/user/1898/change/). Naopak pro http://192.168.254.30:8080/admin/uzivatel/user/1847/change/ notifikace E-U-04 nechodí.
