### ISSUE TITLE
Generování ident_cely uživatele

### ISSUE THREAD

**Issue by pesikj** [ARUP-CAS/aiscr-webamcr#737]
- [x] Algoritmus generování ident_cely zachovat, jen zavést do dokumentace (https://github.com/ARUP-CAS/aiscr-webamcr/wiki/Pridelovani-ident_cely) a prověřit, že funguje i v nové DB (zdá se, že sekvence nyní u pole auth_user.ident_cely není nastavená).

**Comment by motyc** [comment]
@pesikj Máte pravdu, není tam. Byla nastavená pro tabulku uzivatel, asi se na přenos zapomnělo při migraci:
`ident_cely text COLLATE pg_catalog."default" DEFAULT ('U-'::text || "right"(concat('000000', (nextval('user_storage_user_id'::regclass))::text), 6))`

**Comment by pbartosova** [comment]
Dokumentace doplněna. V DB je nastaveno správně.

**Comment by motyc** [comment]
@pbartosova Podle mě to nemůže platit. Když se dívám do DB, tak vidím následující:
- Správné řešení je aplikováno tabulce uzivatel, ta se ale nepoužívá a má být smazána v rámci #474: `ident_cely text COLLATE pg_catalog."default" DEFAULT ('U-'::text || "right"(concat('000000', (nextval('user_storage_user_id'::regclass))::text), 6))`
- V tabulce, se kterou se nyní reálně pracuje, je: `ident_cely character varying(150) COLLATE pg_catalog."default" NOT NULL,`

To znamená, že se to aplikaci přiděluje nějak jinak a nenavazuje to na původní řadu, čemuž odpovídají i nově přidělené ident_cely. Viz:
![image](https://user-images.githubusercontent.com/20186892/207381213-c19f4022-a1b1-4a75-80c1-26aa3d713816.png)

Myslím, že se sekvence skutečně nepřenesla do nové tabulky a používá se něco jiného.

**Comment by pbartosova** [comment]
Omlouvám se, až v souvislosti s #474 mi došla podstata tohoto issue. 
a) v tabulce auth_user je nyní default nastaven správně
Je ale nutné mít sekvenci pro ident_cely zvlášť.
b) @pesikj prosím o revizi záznamů s id>900000, ty musely vzniknout při vývoji a jsou úplně mimo sekvenci auth_user_id
c) @motyc prosím o revizi migračních skriptů, jestli už jsi k této tabulce došel.

**Comment by motyc** [comment]
@pbartosova Ok, v migraci to zkusím pořešit.
