### ISSUE TITLE
Úprava patičky

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#74]
Po dohodě s Petrem upravíme patičku tak, aby nekomplikovala rozložení dílčích views. V patičce zůstane jen toto (ideově, graficky to samozřejmě upravit dle potřeby):

![image](https://user-images.githubusercontent.com/20186892/119526000-46210f00-bd7f-11eb-9535-24db94a66806.png)

Přičemž nadpisy otevřou modal okna s patřičným obsahem.

**Comment by pkudela** [comment]
hotovo viz. screenshots

![image](https://user-images.githubusercontent.com/16591052/119642409-f8f27b00-be1a-11eb-96fa-b19fa20bb7e1.png)

![image](https://user-images.githubusercontent.com/16591052/119642469-0c054b00-be1b-11eb-9e57-a323654f6972.png)

**Comment by pkudela** [comment]
@motyc je to v poradku?
