### ISSUE TITLE
Překrytí ovládacích prvků v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#744]
http://192.168.254.30:8080/dokument/model/detail/C-3D-202000007
Mapě bude třeba nastavit nějakou minimální výšku, jinak může dojít k překryvu prvků:
![image](https://user-images.githubusercontent.com/20186892/203526382-74ed2811-455d-4e92-b0a9-20d99ad635f0.png)

Nevím, zda je to třeba ošetřit obecně, nebo jen v daném případě.

**Comment by jiri-bartos-huld** [comment]
Vyreseni v ramci https://github.com/ARUP-CAS/aiscr-webamcr/commit/311d5016d2f3b1b7875be8b00bbbfdef99e57b81
je soucasti dev
