### ISSUE TITLE
Dohledat přímé použití ID z DB v kódu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#749]
S novými migracemi určitě dojde k posunu ID v DB a konstanty je třeba aktualizovat (vyřešeno v rámci #476). Pokud by byly někde jinde přímo v kódu (kromě SQL souborů migrací), bude to velký problém, protože se rozbije aplikační logika.

- [x] Je třeba ověřit, že všechny odkazy na hesláře, které pak mají vystupovat jako konstanty v kódu, jsou podle dřívější domluvy řešeny přes soubor: https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/heslar/hesla.py
- [x] V rámci migrací ARÚ doplní do komentářů do souboru výše správné reference pomocí ident_cely (hotovo). Konstanty je třeba upravit tak, aby se nastavovaly podle ident_cely, nikoli podle ID, jinak se bude muset opakovaně aktualizovat.
- [x] Některé definice jsou i zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/core/constants.py (např. `PIAN_PRESNOST_KATASTR`) - mělo by se asi jednotně dávat do https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/heslar/hesla.py
- [x] Podobně se nesmí vyskytovat přímé odkazy na jiné záznamy, jako např. zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/30af0a8c9a795e08935ed0f7e9fe91525e0bb4a5/webclient/pian/views.py#L248
- [x] V kódu se někdy nepoužívají jen ID, ale dokonce přímo jiné hodnoty z DB, viz např.: https://github.com/ARUP-CAS/aiscr-webamcr/blob/c1be3294140416773fdb877d31ea804e4b13977f/webclient/watchdog/views.py#L17

**Comment by sedmar** [comment]
@motyc Bude řešeno v rámci maintenance s tím, že význam ID bude muset být doplněn ARUP. Souhlas?

**Comment by motyc** [comment]
Upraven první post po dokončení revize migrací.

**Comment by pesikj** [comment]
@motyc Při dopisování identů jako komentářů prosím vkládání aspoň dvou mezer před začátek komentáře, jak doporučuje PEPL 8 (https://peps.python.org/pep-0008/#inline-comments).

**Comment by pesikj** [comment]
@motyc Zbylo v constants něco, co jsem přehlédl?
https://github.com/ARUP-CAS/aiscr-webamcr/pull/856/files#diff-0c7d0e3ca0e4fb970ae4ee0bcb84068edae94db606f5e0fe0f5c7314fa6232b0

**Comment by pesikj** [comment]
@motyc K poslednímu bodu (tj. ke skupině). Skupina má pole pouze název a ID. Za mě je v případě skupiny použití názvu v pořádku, v rámci Django se s názvy skupin běžně pracuje. Je též možné použít ID, ale název skupiny mi přijde lepší. Máte případně jiný návrh?

**Comment by motyc** [comment]
@pesikj Problém je v tom, že hodnoty se nyní všude zobrazují tak, jak jsou, proto je už nyní bylo třeba upravit, viz aktuální verze migrací: https://github.com/ARUP-CAS/aiscr-webamcr/blob/789f02127fa64a9a0e34ed6a65569018bf764914/migrace/1_migrace_django_users.sql#L18

I zde navíc budeme muset řešit češtinu/angličtinu. Nepřijde mi šťastné používat tedy hodnoty z DB kdekoli v kódu, ale postupoval bych jako jinde, tj. definoval si konstanty v https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/heslar/hesla.py na základě údajů z DB a pak pracoval pouze s nimi.

Nebo něco přehlížím?

**Comment by pesikj** [comment]
@motyc Překlady lze řešit standardně, názvy skupin můžou být upraveny v části Rosetta. Co se týká editace, možná by bylo lepší ji tedy zakázat, tj. názvy skupin by nebylo možné upravovat. Použití konstant je možné, konstanty přidám.

**Comment by motyc** [comment]
@pesikj 
> Co se týká editace, možná by bylo lepší ji tedy zakázat, tj. názvy skupin by nebylo možné upravovat. Použití konstant je možné, konstanty přidám.

Tady jen pozor, že editaci bych zakázal jen pro ty základní pevně dané skupiny (role, texty, skupiny). Jiné by mělo být možné přidávat a editovat. Jinak souhlas.

**Comment by motyc** [comment]
@pesikj

Při kontrolách jsem náhodou našel tyto definice konstant na nevhodných místech:
1) https://github.com/ARUP-CAS/aiscr-webamcr/blob/140a7e4becdb44913b65a314554f1a6f8992eab6/webclient/projekt/templates/projekt/projekt_list.html#L5
2) https://github.com/ARUP-CAS/aiscr-webamcr/blob/babd80bf45a0b18e6fbcfea350069f54a64c5ba7/webclient/templates/search_list.html#L215
3) https://github.com/ARUP-CAS/aiscr-webamcr/blob/5d25fd27e8073753d41922a11c59ee901521d240/webclient/services/mailer.py#L523

Často se také místo užívá definice oblastí natvrdo řetězcem (zde toho bude asi více, typově např.: `if projekt.ident_cely[0] == "C"`), když na to máme opět konstanty: https://github.com/ARUP-CAS/aiscr-webamcr/blob/140a7e4becdb44913b65a314554f1a6f8992eab6/webclient/core/constants.py#L106
