### ISSUE TITLE
Ladění související s DJ, PIAN a komponentami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#760]
Issue navazuje na testování #318 a #319. Týká se to obojího, tak vyčleňuji takto zvlášť. Mohu rozdělit i na dílčí issue, ale jde komplet o problémy spojené s jednou částí aplikace a má smysl je řešit najednou (často spolu i souvisí).

DJ typu “Katastrální území”:
- [ ] #780
- [ ] #781

PIAN s přesností 4 (katastr)

- [ ] #779 

Chování mapy
- [ ] #779 

Chování DJ
- [ ] #782

Komponenty
- [ ] #783

**Comment by sedmar** [comment]
> Issue navazuje na testování #318 a #319. Týká se to obojího, tak vyčleňuji takto zvlášť. Mohu rozdělit i na dílčí issue, ale jde komplet o problémy spojené s jednou částí aplikace a má smysl je řešit najednou (často spolu i souvisí).
> 
> DJ typu “Katastrální území”:
> 
> * [ ]  nemůže mít povolenou volbu “Odpojit PIAN”; pokud změním typ DJ na jiný, musí dojít k automatickému odpojení PIAN
@motyc  bude řešeno v rámci maintenance.

> * [ ]  potřebuji mít možnost nějak změnit katastrální území záznamu, což nyní nejde -> do menu k DJ přidat funkci “Změnit 
katastr”, která otevře modal pro výběr jiného KÚ -> po výběru se automaticky přepojí PIAN a upraví hlavní katastr záznamu
@motyc Výběr přes modální okno nepovažujeme za konzistetní se zbytkem aplikace. Navrhujeme řešit jako požadavek na nový vývoj s tím, že design této funkcionality bude upřesněn.

> * [ ]  PIAN katastru se automaticky připojí k nové DJ bez ohledu na její typ - to se má dít pouze pro typ “Katastrální území” (je třeba ošetřit i pro změnu typu z čehokoli na “Katastrální území”)
@motyc vyřešit v rámci maintenance.

> 
> PIAN s přesností 4 (katastr)
> 
> * [ ]  jeho hranice by nikdy neměly být vidět v mapě (nyní se je vidět např. P-1121-900086 (Abertamy);
> * [ ]  pokud je někde třeba zobrazit definiční bod, měl by mít standardní symbologii, tedy malý pin (nyní má velký) - např. http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000002A/dj/X-C-9000002A-D01
> * [ ]  nikdy by neměl jít vybrat přes "Připojit PIAN z mapy" nebo "Připojit PIAN podle ID"
@motyc asi je to chyba, ale potrebovali bych odkazat na zadani jak se to ma chovat pro mapu az v tomto issue, nejblize tomu je [https://github.com/ARUP-CAS/aiscr-webamcr/issues/17](https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FARUP-CAS%2Faiscr-webamcr%2Fissues%2F17&data=05%7C01%7C%7Cbd984b05a2b84661239808dad711f698%7C2a82d2e0be594e30a9834919d6a291b2%7C0%7C0%7C638058769387287319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fo7bUj56BHOtymsa8inKmpyYIeRbdvV0O5%2FCVxQe9t4%3D&reserved=0) ale to neni zadani pro mapu.

> Chování mapy
> 
> * [ ]  přestala správně fungovat symbologie podle [Nastavení symbologie bodů #303](https://github.com/ARUP-CAS/aiscr-webamcr/issues/303) a [Symbologie linií a polygonů + principy clusteringu/heatmapy #302](https://github.com/ARUP-CAS/aiscr-webamcr/issues/302) - nyní jsou vpodstatě všechny PIAN v mapě zelené, jako by patřily ke stejnému záznamu
> * [ ]  výchozí zobrazení mapy u arch. záznamů je nyní na celou ČR a nejsou vidět žádná data, místo aby mapa zohledňovala zvolený katastr (příp. na polohu PIAN); totéž platí když kliknu na “Přidat nový PIAN” u DJ
> * [ ]  při kliknutí na “Upravit PIAN” se obrazovka posune až nahoru, místo na záhlaví mapy
@motyc prvni dva body, jsou hlasene chyby-overime/opravime-nejspise to je dano problemem s refaktorizaci.  Bude opraveno v ramci maintenance.


> Chování DJ
> 
> * [ ]  když má DJ ADB, nesmí jít změnit typ na jiný než sonda (odporuje to pravidlům zápisu)
@motyc bude řešeno v rámci maintenance => bug.

> 
> Komponenty
> 
> * [ ]  u komponenty musí být výchozí jistota nastavena na “ano”
> * [ ]  přestala se vyplňovat výchozí specifikace u předmětů (podle vazby v hesláři)
@motyc potřebovali bychom znát výchozí specifikaci předmětů, poté řešeno v rámci maintenance.

**Comment by sedmar** [comment]
Chovani mapy a PIAN s přesností 4 vyjmuty do samostatného issue #779

**Comment by sedmar** [comment]
@motyc Rozdeleno viz vyse.

**Comment by motyc** [comment]
@sedmar Děkuji, toto issue zavírám.
