### ISSUE TITLE
Popisek v záhlaví modulů se chová různě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#762]
Správné chování je u projektů, kde slovo "Projekt" směřuje na domovskou stránku modulu. Jinde většinou proklik nic nedělá. Je třeba udělat pro všechny části.

![image](https://user-images.githubusercontent.com/20186892/205154981-093b7e5c-a9f2-438b-ac80-8578ebc2b22d.png)

**Comment by sedmar** [comment]
@motyc bude řešeno v rámci maintenance.

**Comment by motyc** [comment]
### Test v0.4.66

- [ ] Vše ok, jen v rámci app lokalita (http://192.168.254.30:8080/arch-z/lokalita/) volba vrací na akci (http://192.168.254.30:8080/arch-z/akce/).
