### ISSUE TITLE
Chování po smazání otevřeného záznamu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#763]
Směrování po smazání záznamu, jehož detail mám otevřený, by bylo vhodné dělat jednotně, a to vždy na homepage nadřazeného modulu - nyní se to chová různě, někdy vyloženě chybně (např. akce vede na lokalitu).

**Comment by sedmar** [comment]
@motyc navržená funkcionalita, tj. návrat na homepage nadřazeného modulu, nám nepřijde optimální z pohledu uživatele. Zadání diskutovat s @pesikj. Po upřesnění zadání bude řešeno kam zařadit.

**Comment by motyc** [comment]
@sedmar Není problém se domluvit jinak, rád si poslechnu návrh. Problém hlavně aktuální zmatečnost.
