### ISSUE TITLE
Výška menu pro výběr DJ

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#765]
Výška menu pro výběr DJ a komponent nekoresponduje s výškou mapy, takže se v něm při více záznamech úplně zbytečně roluje, přitom pod ním je prázdný prostor. Výšku obou částí svázat tak, aby byly vždy stejné (a nastavit vhodné minimum).

**Comment by sedmar** [comment]
@motyc Lze upřesnit, kterou konkrétní obrazovku, pokud totiž myslíme to samé, tak ta výška nebyla nikdy stejná. Pokud se jedná jen o úpravu výšky, tak bude řešeno v rámci Maintenance.

**Comment by motyc** [comment]
@sedmar Jde o:
http://192.168.254.30:8080/arch-z/akce/detail/
http://192.168.254.30:8080/arch-z/lokalita/detail/

Ona se měnila ta výška mapy, tak je možné, že se to rozběhlo v tu chvíli, nebo to dříve nebylo tak zřetelné. A jinak ano, jde jen o úpravu výšky, aby byla ve shodě s mapou (tj. aby box pro výběr DJ byl delší).

**Comment by pesikj** [comment]
@motyc Upraveno, ale popravdě mi to zvlášť u lokalit nepřipadá moc estetické. Možná bych upravil max-height, aby nebylo potřeba scrollovat, a u lokalit a akcí s málo DJ nechat původní výšku.

![image](https://user-images.githubusercontent.com/15179154/214702115-39c89f88-40b8-46c0-ad50-37c35e3bf80a.png)

**Comment by motyc** [comment]
@pesikj Zatím to nechte takto, než uvidím, jak to bude vypadat v reálu. Přijde mi celkem jedno, jestli je tam prázdné místo v boxu, nebo mimo něj.
