### ISSUE TITLE
Záznamy v menu "Moje"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#766]
Fungování rubriky “Moje” ve všech modulech (kromě projektů, kde není) - měly by být jen záznamy, které přihlášený uživatel zapsal (nikoli ty, kde je uživatel jakkoli zmíněn v historii).

- [x] http://192.168.254.30:8080/arch-z/akce/vyber?vlastnik=1898 -> http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_typ_zmeny=AZ01&historie_uzivatel=1898
- [x] http://192.168.254.30:8080/dokument/vyber?vlastnik=1898 -> http://192.168.254.30:8080/dokument/vyber?historie_typ_zmeny=D01&historie_uzivatel=1898
- [x] http://192.168.254.30:8080/dokument/model/vyber?vlastnik=1898 -> http://192.168.254.30:8080/dokument/model/vyber?historie_typ_zmeny=D01&historie_uzivatel=1898
- [x] http://192.168.254.30:8080/pas/vyber?vlastnik=1898 -> http://192.168.254.30:8080/pas/vyber?historie_typ_zmeny=SN01&historie_uzivatel=1898
- [x] http://192.168.254.30:8080/arch-z/lokalita/vyber?vlastnik=1898 -> http://192.168.254.30:8080/arch-z/lokalita/vyber?historie_typ_zmeny=AZ01&historie_uzivatel=1898
- [x] http://192.168.254.30:8080/ext-zdroj/vyber?vlastnik=1898 -> (nyní nejde simulovat URL, ale obdobně jako výše)

(projektů se to netýká, tam je vše ok)

**Comment by sedmar** [comment]
Bude řešeno v rámci maintenance. @motyc Chápeme správně, že úprava fungování se týká i modulů, které nebyly řešeny v rámci aktuální objednávky, tzn. tato chybná funkcionalita existuje již delší dobu a nevznikla jako důsledek současného vývoje?

**Comment by motyc** [comment]
@sedmar Přiznám se, že jsem to netestoval důsledně. Mohu se k tomu vrátit a prověřit to. Aktuálně se mi to dělo u nových modulů. Nejlepší by bylo vypsat aktuální nastavení (nebo dát odkaz na kód, ze kterého je to jasné) a já bych to případně potvrdil.

**Comment by pesikj** [comment]
@motyc Prosím o kontrolu filtru pro externí zdroje, jestli je to takto v pořádku:

http://localhost:8000/ext-zdroj/vyber?historie_typ_zmeny=EZ01&historie_uzivatel=901661

**Comment by motyc** [comment]
@pesikj Na test se aktuálně nedá připojit, takže nemohu potvrdit přímo, ale v principu to vypadá ok.

**Comment by motyc** [comment]
Zjistil jsem drobnou chybu implementaci tohoto issue - odkazy sice byly změněny v menu, ale nedošlo k jejich úpravě na kartách (např. http://192.168.254.30:8080/pas/). Tam zůstaly všude původní odkazy.

**Comment by motyc** [comment]
Vyřešeno v: https://github.com/ARUP-CAS/aiscr-webamcr/pull/1348
