### ISSUE TITLE
Problémy chování levého menu a zobrazení karet

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#767]
- [x] upravit pořadí v menu (viz níže) + ikony (aby korespondovaly s Digitálním archivem)
-- Projekty (ikona ok)
-- Samostatné akce (ikonu upravit na: [https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Abrush%3AFILL%401%3Bwght%40400%3BGRAD%400%3 Boss%4048](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Abrush%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4048))
-- Lokality (ikonu upravit na: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Atour%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048
-- Samostatné nálezy (ikona ok)
-- Knihovna 3D (ikona ok)
-- Dokumenty (ikona ok)
-- Externí zdroje (ikonu upravit na: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amenu_book%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4048)
-- Administrace (ikona ok) - zrušit volby v podmenu a rovnou proklikávat do admin. rozhraní (nemá smysl zde komplikovat)
- [x] Pokud jsem ve workflow Akce, Lokality, Dokumenty a Externí zdroje, nejsou rozevřené odpovídající levé menu (naopak to např. po aplikaci výběru rozevírá projekty) - pokud jsem v daném modulu, měla by být vždy rozbalená odpovídající nabídka (jako je to u projektů)
- [x] chybí karty na úvodní obrazovce (http://192.168.254.30:8080/), které vedou do jednotlivých modulů (pořadí karet jako v menu)
- [x] karty na úvodních obrazovkách modulů (např. http://192.168.254.30:8080/arch-z/akce) by měly být ve stejném pořadí, jako položky v levém menu

**Comment by sedmar** [comment]
Bude řešeno v rámci Maintenance.

**Comment by motyc** [comment]
### Výseledek testu
- [ ] Pro Externí zdroje opomenuta změna ikony na: https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amenu_book%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4048
- [ ] Proklik do admin rozhraní vede na http://192.168.254.30:8080/admin/uzivatel/user/, směřovat raději na http://192.168.254.30:8080/admin/
- [ ] http://192.168.254.30:8080/ - u karet Samostatné akce, Lokality, Dokumenty, Externí zdroje chybí vysvětlující text (stačí placeholder a překlad bude klasicky v Rosetta).
