### ISSUE TITLE
Problémy s tabulkami výběru a filtrací (průřezové)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#771]
- [x] Všude kromě tabulky projektů dochází při práci s tabulkami (např. po seřazení, filtraci přechodu na stránku) k resetování výběru sloupců, někdy jen částečnému.
- [x] v poli přechod na číslo stránky by mělo být uvedeno nějaké výchozí číslo (např. aktuální stránku), nebo musí být ošetřena prázdná hodnota - nyní pokud zůstane prázdné a uživatel klikne na tlačítko -> chyba 404
- [x] pokud snížím počet záznamů na stránku a kliknu na číslo poslední stránky -> chyba 404
- [x] ve většině nových modulů chybí mezera a dvojtečka mezi popiskem a počtem vyhledaných záznamů

**EDIT 13/12/2022**
- [x] často není pořádně vidět ikona u tlačítka pro potvrzení filtrace - změnit na bílou
- [x] do URL se zbytečně vypisují všechny prázdné parametry, což je nepraktické a nepřehledé; vše přitom funguje správně i bez nich

**Comment by sedmar** [comment]
Bug => bude řešeno v rámci Maintenance.

**Comment by motyc** [comment]
@sedmar Doplněny dva body (viz výše) - pokud nesouhlasíte, vydělíme zvlášť.

**Comment by jnihnat** [comment]
@motyc mnel bych tu 2 dotazy:
-  pokud snížím počet záznamů na stránku a kliknu na číslo poslední stránky -> chyba 404 - tohle se mi prosim nedari nasimulovat, potreboval bych presnejsi popis co ste jak kliknul po sobe. Mozna i stranku
- tedka mame logiku na zobrazovani hlavicky v toolbare podle toho na ktery filter user kliknul, napr u projektu "Naše projekty". U projektoch to funguje spravne. U ostatnych filtru, hlavne novych to neni spravne naimplementovano. Chceme to dodelat, je to takto potrebne? Ptam se protoze premyslim rovno nad sloucenim tech stranek, tak at to rovno udelat spravne.
![image](https://user-images.githubusercontent.com/57906106/211348391-c8b9414b-7ae7-496a-9744-805993fc2358.png)
