### ISSUE TITLE
Úprava zadávání typu a druhu lokality

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#775]
Navazuje na https://github.com/ARUP-CAS/aiscr-webamcr/issues/319#issuecomment-1335830130

- [x] typ se musí vyplňovat automaticky podle druhu (na základě vazby heslářů lokalita_druh -> lokalita_druh_kat -> lokalita_typ)
- [x] druh je dvoustupňový heslář (lokalita_druh + lokalita_druh_kat)
- [x] v editaci nesmí jít změnit typ
- [x] v editaci může jít změnit druh pouze v rámci daného typu (na základě vazby heslářů)

Jde o to, že by se nám jinak mohl rozpadnout vztah mezi ident_cely a typem a druhem lokality. Výše popsané bylo promítnuto i do zadání formulářů.

Co se týče vazby typ a druh_kat, tak ta je následovná:

letecká archeologie
-- polygon archeologického průzkumu
nemovitá památka
-- přírodní útvar s lidskou aktivitou
-- zaniklý areál
-- historická část živého areálu
krajinný prvek
-- přírodní krajinný útvar
-- živé sídlo
-- extravilán živých sídel
-- místo historické paměti
-- zvláštní prvek krajiny
(při psaní SQL prosím neodkazujte jen na znění hesel, ale vždy i na kombinaci s konkrétním heslářem, protože jinak nemusí být hesla unikátní)

**Comment by motyc** [comment]
@sedmar Moc děkuji.

**Comment by jnihnat** [comment]
prvni reseni udelano v #830 . Prosim dejte vedet pak, ci vyhovuje i to jak se zobrazuji pole a moznosti, nebo chceme trocha "skomplikovat" to jak se dane polia ukazuji. Dekuji
