### ISSUE TITLE
Ladění mapa PIANy

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#779]
Vyjmuto z #760 

PIAN s přesností 4 (katastr)
- [x] jeho hranice by nikdy neměly být vidět v mapě (nyní se je vidět např. P-1121-900086 (Abertamy);
- [x] pokud je někde třeba zobrazit definiční bod, měl by mít standardní symbologii, tedy malý pin (nyní má velký) - např. http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000002A/dj/X-C-9000002A-D01
- [ ] nikdy by neměl jít vybrat přes "Připojit PIAN z mapy" nebo "Připojit PIAN podle ID"

Chování mapy
- [x] přestala správně fungovat symbologie podle https://github.com/ARUP-CAS/aiscr-webamcr/issues/303 a https://github.com/ARUP-CAS/aiscr-webamcr/issues/302 - nyní jsou vpodstatě všechny PIAN v mapě zelené, jako by patřily ke stejnému záznamu
- [x] výchozí zobrazení mapy u arch. záznamů je nyní na celou ČR a nejsou vidět žádná data, místo aby mapa zohledňovala zvolený katastr (příp. na polohu PIAN); totéž platí když kliknu na “Přidat nový PIAN” u DJ
- [x] při kliknutí na “Upravit PIAN” se obrazovka posune až nahoru, místo na záhlaví mapy

**Comment by motyc** [comment]
ad @sedmar 
> asi je to chyba, ale potrebovali bych odkazat na zadani jak se to ma chovat pro mapu az v tomto issue, nejblize tomu je https://github.com/ARUP-CAS/aiscr-webamcr/issues/17 ale to neni zadani pro mapu.

Prosím případně o konkretizaci dotazů. Celkem chápu, že s těmi katastry mohou vyvstávat různé otázky, ale vlastně nevím, na co přesně reagovat a co vše je třeba popas - asi by bylo nejlepší jmenovat, co může nastat (resp. jak jet to nastaveno nyní) a já k tomu dám reakce.

**Comment by jiri-bartos-huld** [comment]
bod 4. prosim o ukazku mapy, kde se to chova spatne, me se nyni na serveru 30, vse chova spravne

**Comment by jiri-bartos-huld** [comment]
pripraveno na MR, vse mimo  bodu 4

**Comment by motyc** [comment]
@jiri-bartos-huld Děje se to zjevně ve chvíli, kdy akce ještě nemá připojený žádný PIAN. Např. zde (většina zelená + nefunguje clustering): http://192.168.254.30:8080/arch-z/akce/detail/X-C-91276777A
![image](https://user-images.githubusercontent.com/20186892/207110461-4381685b-6f1d-48f0-9196-9a4cb27c8115.png)

**Comment by jiri-bartos-huld** [comment]
dekuji! Kouknu na to!

**Comment by motyc** [comment]
Ještě jsem si teď všiml, že při zadávání/editaci PIAN se ostatní PIAN nezobrazují vůbec.

**Comment by jiri-bartos-huld** [comment]
@motyc opraveno a poslano na MR

**Comment by motyc** [comment]
### Výsledek testu
- [ ] Výchozí zoom stále zlobí, resp. nyní se to vždy vrací na katastr, i když vyberu konkrétní DJ, která má PIAN (dobře zřetelné např. zde: http://192.168.254.30:8080/arch-z/akce/detail/X-C-91276780A/dj/X-C-91276780A-D02)- vždy to přizoomuje na PIAN, ale následně to hned skočí na celý katastr.
- [ ] Definiční bod PIAN s přesností 4 se někdy v mapě zobrazuje (http://192.168.254.30:8080/arch-z/akce/detail/C-9163608A) a jindy ne (http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000005A/dj/X-C-9000005A-D01). Není mi jasné, podle jakého klíče to funguje, definiční bod by měl být vidět v obou případech.
- [ ] Funkce "Připojit PIAN z mapy" nyní nefunguje vůbec (testováno u http://192.168.254.30:8080/arch-z/akce/detail/C-9163635A/dj/C-9163635A-D01).

**Comment by pesikj** [comment]
@jiri-bartos-huld Jirko, podívej se prosím na body z komentáře https://github.com/ARUP-CAS/aiscr-webamcr/issues/779#issuecomment-1357631688.

**Comment by jiri-bartos-huld** [comment]
Opraveno poslano na MR:
1./Chyba byla dana tim, ze se zdvojoval dotaz na pian a ku, ku pak vzdy trval dele a "vyhral posledni zmenu"
2./Chyba byla dana tim, ze ku Abertamy je v DB jako multipolygon -kolekce jsme drive pro Ruian neuvazovali
3./Chyba byla dana negaci podminky presnosti==4

**Comment by jiri-bartos-huld** [comment]
https://github.com/ARUP-CAS/aiscr-webamcr/pull/896

**Comment by jiri-bartos-huld** [comment]
@motyc @pesikj  prosim, zkontrolovar podle me se chova jiz spravne 
viz http://192.168.254.30:8080/arch-z/akce/detail/X-C-91276777A/dj/X-C-91276777A-D01

**Comment by motyc** [comment]
@jiri-bartos-huld Potvrzuji, že vše je již ok a zavírám.
