### ISSUE TITLE
Kladyzm zaznam listu s SRID=4326

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#78]
gid = 1094

select ST_AsText('0106000020E6100000010000000103000000010000000500000082E35FBF6EFC2B40942180C249AE48406DBAEE795DA72C401E4F14245DAE48402ADCF7B7F4A72C4066D964D17E9848402C254B4317FD2B40B063EC986B98484082E35FBF6EFC2B40942180C249AE4840');

vrati:

MULTIPOLYGON(((13.9930324368049 49.361625969471,14.326885042564 49.3622174357572,14.3280389299453 49.1913701765468,13.9943181065779 49.1907836107488,13.9930324368049 49.361625969471)))

**Comment by Najiva** [comment]
jiny list s srid 102067

MULTIPOLYGON(((-868869.058895666 -1060270.89900142,-868291.779062647 -1056515.0099199,-863537.200012058 -1057249.62890229,-864111.518937778 -1061005.97898849,-868869.058895666 -1060270.89900142)))

**Comment by motyc** [comment]
Ok, díky. Chyba je jasná. Vzhledem k času bych to ale nyní neřešil (pokud to tedy nehoří na Tvé straně), nechal zaevidované a vrátíme se k tomu, až nebudou důležitější věci na stole.

**Comment by motyc** [comment]
Pozor - je to dokonce ošetřováno v kódu aplikace: https://github.com/ARUP-CAS/aiscr-webamcr/search?q=1094 (bude nutno odstranit)

**Comment by motyc** [comment]
Juraj musel někde udělat chybu. V geometrii žádný problém není - ani v produkční DB, ani v DB na testu. Patrně si omylem někde souřadnice sám převedl a pak s tím pracoval.
