### ISSUE TITLE
Přidat funkci Změnit katastr

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#780]
Potřebuji mít možnost nějak změnit katastrální území záznamu, což nyní nejde -> do menu k DJ přidat funkci “Změnit katastr”, která otevře modal pro výběr jiného KÚ -> po výběru se automaticky přepojí PIAN a upraví hlavní katastr záznamu

**Comment by sedmar** [comment]
Potřebuji mít možnost nějak změnit katastrální území záznamu, což nyní nejde -> do menu k DJ přidat funkci “Změnit katastr”, která otevře modal pro výběr jiného KÚ -> po výběru se automaticky přepojí PIAN a upraví hlavní katastr záznamu

**Comment by motyc** [comment]
@sedmar S tímto bych ne zcela souhlasil. Asi jde jen o nepochopení daného bodu ze zadání, ale v https://github.com/ARUP-CAS/aiscr-webamcr/issues/318#issue-1116477707 je u této funkce uvedeno:
> k DJ je automaticky připojen PIAN katastru podle uživatelské volby (**nutno dohodnout, jak přesně uživatel vybere katastr, když pro akce s PIAN jej budeme stanovovat automaticky a pole ve formuláři je neaktivní**)

Na to přesně reaguje tento výsledek testu, že to není vyřešeno, resp. máme řešení jen při zápisu nového záznamu, ale nikoli u existujícího. Na tom, že to má být přes modální okno netrvám, přišlo mi to jako nejsnazší ale může to být i jinak (např. editací detailu, pokud není problém nastavit správně podmínky pro dané pole a následně správné přepojení PIAN u DJ).

**Comment by sedmar** [comment]
@motyc Ano, upravime to tedy v ramci #318.

**Comment by motyc** [comment]
### Výsledek testu
(testováno na http://192.168.254.30:8080/arch-z/akce/detail/X-C-91276769A)
- [ ] - vše funguje skvěle, pokud změním katastr na nějaký, kde pro který existuje PIAN; pokud ještě PIAN není vytvořen, nenastaví se správně - patrně souvisí s tím, že se nezohledňuje funkce #17
- [ ] - pokud je DJ typu Katastrální území, v menu u DJ se objevila nová funkce `Nastav Katastrální území z mapy` - nevím co má dělat a jak funguje; může to být dobře myšleno, ale momentálně si s tím vůbec nevím rady a nezdá se, že by to dobře fungovalo

**Comment by jnihnat** [comment]
@motyc prvni a treti bod opraven v #827 
Druhy bod jsem nedelal ja a v kodu je uz podle vseho dele. funkce vytvorena pred rokem a pul @jiri-bartos-huld . Posledne zmeny jsou od @pesikj jak prerabal nacitani stranky. Videlil bych proto jak samostatne issue a mozna oba Jiriove budou vedet o tom vic.

**Comment by motyc** [comment]
@jnihnat Druhý bod vyčleněn do #828
