### ISSUE TITLE
DJ typu “Katastrální území” - připojení / odpojení PIAN

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#781]
DJ typu “Katastrální území” 

- [x] nemůže mít povolenou volbu “Odpojit PIAN”; pokud změním typ DJ na jiný, musí dojít k automatickému odpojení PIAN

- [x] PIAN katastru se automaticky připojí k nové DJ bez ohledu na její typ - to se má dít pouze pro typ “Katastrální území” (je třeba ošetřit i pro změnu typu z čehokoli na “Katastrální území”)

**Comment by motyc** [comment]
Mám takové tušení, že chování podle druhého bodu je způsobeno mylným výkladem textu:

> při vytvoření nelokalizované dokumentační jednotky (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/319 a https://github.com/ARUP-CAS/aiscr-webamcr/issues/318) automaticky připojit existující PIAN 4 katastru, pokud již existuje (tj. když ruian_katastr.pian is not null tak dokumentacni_jednotka.pian = ruian_katastr.pian)

(viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/17#issue-802686836)
"vytvoření nelokalizované dokumentační jednotky" zde bylo myšleno jako vytvoření DJ typu "Katastrální území" - dříve to byl typ "Nelokalizovaná akce" a tím jsme se asi zmátli. Omlouvám se, pokud to tak je a interpretovali jste to jinak, je to opravdu nešťastně napsané.

**Comment by jnihnat** [comment]
Opraveno. 
Mam ale tuseni ze mame spatne zobrazovani typu dj pri vytvareni a detailu DJ. minimalne pokud mam vic typu dj Sond. Nejsem si ale uplne jisty jak to ma byt spravne. Bylo by nejlepe pokud by se to cele pretestovalo, nebo pokud udelate bug s presnym popisem/tabulkou co ma byt kdy zobrazeno pro typ, ja skontroluji/opravim kod a pak by se to pretestovalo. Dekuji.

**Comment by motyc** [comment]
@jnihnat Zde to zkusím shrnout:

**Projektové akce**
- První DJ: Celek akce / Sonda
- Další DJ: Část akce (pokud první Celek) / Sonda (pokud první Sonda)

**Samostatné akce**
- První DJ: Celek akce / Sonda / Katastrální území
- Další DJ: Část akce (pokud první Celek) / Sonda (pokud první Sonda) / nic (pokud první KÚ)

**Lokality**
- Jediná DJ: Lokalita / Katastrální území

Stačí takto? Otestuji to případně s nějakou další nasazenou verzí.

**Comment by jnihnat** [comment]
@motyc presel sem to a opravil v #855 az bude nasazeno muzete pretestovat i ty typy DJ. Dekuji
