### ISSUE TITLE
Ladění Komponenty

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#783]
- [x] u komponenty musí být výchozí jistota nastavena na “ano”
- [x] přestala se vyplňovat výchozí specifikace u předmětů (podle vazby v hesláři)

**Comment by motyc** [comment]
ad @sedmar 
> potřebovali bychom znát výchozí specifikaci předmětů, poté řešeno v rámci maintenance.

Ta je dána vztahem typu "výchozí hodnota" přes heslar_hierarchie. Už to fungovalo dříve, jen se to nějak rozbilo.

**Comment by jnihnat** [comment]
Kdyby to nahodou nekde jeste nefungovalo prosim napiste presne misto. Snazil jsem se projit vsechna mista ale clovek nikdy nevi ci neco nemine. Dekuji
