### ISSUE TITLE
Úprava vyhledávání v mapě

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#797]
Navazuje na #293 

- [x] Vyhledávání nesmí být case sensitive
- [x] Vyhledávání ve vrstvě "Obce" nahradit vyhledáváním ve vrstvě "Geonames"
- [ ] Zvážit přidání možnosti vyhledávání podle vrstev (pro každou zvlášť):
-- ulice
-- adresy
-- parcely
- [ ] Zvážit přidání rozbalovacího menu pro volbu vrstvy:
![image](https://user-images.githubusercontent.com/20186892/207282973-b9125a7e-dd10-4f16-a4a8-cf71eb930c51.png)
- [x] Zajistit lepší chování pole pro zápis - teď se divně prodlužuje, zkracuje atd.

**Comment by motyc** [comment]
### Text v0.4.75
Je to ok až na dvě drobnosti:
- [ ] když provedu vyhledání, tak texty jsou poměrně dlouhé a momentálně není jak se podívat na zbytek. Navrhoval bych řešit zobrazením celého textu v tooltipu po najetí myší (pokud to jde):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/771670b4-984d-4b69-9a75-c7237a03b1a1)
- [ ] nevím, podle jakého klíče se řadí výsledky; asi by to ale bylo dobré abecedně, aby se jednotlivé typy výskytů dostaly k sobě (všechny obce, místní části atd...)

**Comment by jhavrlant** [comment]
@motyc  Mě se zobrazí takto
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/155644357/921838b6-9070-4b80-af32-d1f8d953bb31)

**Comment by motyc** [comment]
@jhavrlant Zjevně se to nechová všude stejně. Na http://192.168.254.30:8080/arch-z/akce/detail/M-9112179A je to ok. Ale zlobí to na:
- http://192.168.254.30:8080/pas/zapsat (a související)
- http://192.168.254.30:8080/oznameni/
- http://192.168.254.30:8080/dokument/model/zapsat - tady je to úplně špatné, protože to zmizí za jinými prvky a okrajem mapy; asi zde bude řešením dát mapovému oknu nějakou minimální výšku?

**Comment by jhavrlant** [comment]
@motyc Je potřeba aktualizovat překlad mapa.SearchText (vyhledávací políčko)

**Comment by motyc** [comment]
@jhavrlant Díky, upraveno.

**Comment by motyc** [comment]
@jhavrlant Implementovaná část je v pořádku, zbytek odkládáme na neurčito.

**Comment by motyc** [comment]
> Potřeba přidat překlady
> KatastralniUzemi: '{% trans "leaflet_search.KatastralniUzemi" %}',
> Okres: '{% trans "leaflet_search.Okres" %}',
> Obec: '{% trans "leaflet_search.Obec" %}',
> Adresa: '{% trans "leaflet_search.Adresa" %}',
> Ulice: '{% trans "leaflet_search.Ulice" %}',
> Geonames: '{% trans "leaflet_search.Geonames" %}',
> Parcela: '{% trans "leaflet_search.Parcela" %}',
> Stavebni: '{% trans "leaflet_search.Stavebni" %}',
> Pozemkova: '{% trans "leaflet_search.Pozemkova" %}',
> upravit
> SearchTextCancel: '{% trans "leaflet_search.SearchTextCancel" %}',
> SearchTextError: '{% trans "leaflet_search.SearchTextError" %}'
> a smazat překlad
> mapa.SearchText
