### ISSUE TITLE
Nesprávně ošetřený přístup do aplikace v nových modulech

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#798]
Pokud nejsem přihlášený a zadám:
- http://192.168.254.30:8080/arch-z/lokalita/detail/C-N0000002
- http://192.168.254.30:8080/ext-zdroj/detail/X-BIB-0926117

nedostanu se na login page, ale zobrazí se tato podivná stránka:
![image](https://user-images.githubusercontent.com/20186892/207283843-27db3ffc-3925-4c1c-8349-bbc7fc54517e.png)

**Comment by jnihnat** [comment]
tohle bylo uz opraveno davneji, prosim o test

**Comment by motyc** [comment]
@jnihnat Potvrzuji a zavírám.
