### ISSUE TITLE
Vyjmout navigaci listovani ven z tabulky

### ISSUE THREAD

**Issue by Najiva** [ARUP-CAS/aiscr-webamcr#80]
@pkudela Pokousel jsem si vyjmout to listovani do souboru wrapnutim tabulky krome navigacni listy `(<div class="app-table-list-wrapper"> a <div class="app-table-list-inner">)` v bootstrap4_base.html ale nejak mi to nefunguje. Prosim podivej se zda by to slo udelat.

**Comment by Najiva** [comment]
![Screenshot from 2021-06-03 16-10-14](https://user-images.githubusercontent.com/26173315/120659083-4d829f80-c486-11eb-8eab-4c86ce2ce5ed.png)

**Comment by pkudela** [comment]
@Najiva - dival jsem se na to a aby to fungovalo a paginace se nezobrazovala v ramci sroll elementu, musi byt umistena pod elementem class "app-table-list-wrapper", nikoliv uvnitr, pak to nemuze fungovat. V konzoli jsem to zkusil nasimulovat a funguje to viz. screenshot nize.

![image](https://user-images.githubusercontent.com/16591052/122417017-7d06d100-cf89-11eb-9fca-f4ae0525676a.png)

Cili otazka je, jestli umime paginaci vytahnout ven ze souboru bootstrap4.html do souboru pojekt_list.html

**Comment by pkudela** [comment]
Pro jistotu posilam screenshot kodu, v jakem miste by se mela navigace volat.

![image](https://user-images.githubusercontent.com/16591052/122418476-85abd700-cf8a-11eb-9864-24b83d3d6369.png)

Prosim, @Najiva dej vedet, jestli je to mozne, zkratka stejne jako se vola tabulka ze souboru "projekt_list.html", tak stejnym zpusobem by se mela volat navigace ze souboru "projekt_list.html", jak je na screenshotu kodu.

**Comment by pkudela** [comment]
pripadne pokud musi byt tabulka a navigace v jednom souboru, ktery se pak vola z "projekt_list.html", tak bychom museli wrappery presunout ze souboru "projekt_list.html" do souboru ze ktereho se vola tabulka a paginace a tam je spraven umistit, kdyz tak @Najiva vysvetlim, az spolu budeme mluvit.

**Comment by pesikj** [comment]
@jnihnat Bug, o kterém jsme se dnes bavili, by měl být odstraněn.
