### ISSUE TITLE
Omezení typu dokumentu při zápisu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#800]
pri zadavani je tedka omezeni na nektere typy (DATA_GPS, EXPERTNI_POSUDEK, HLASENI_ZAA, TYP_DOKUMENTU_NALEZOVA_ZPRAVA, DATA_ANALYZY_EKOFAKTORU, INVESTORSKA_ZPRAVA, RESTAURATORSKA_ZPRAVA, DATA_VEKTOROVEHO_PLANU, TEXT_JINY, DATA_TERENNIHO_VYZKUMU, PRILOHA_NZ_ZAA, DATA_GEOFYZIKALNI, DATA_GEODETICKA)

Toto omezení lze vypustit.

**Comment by pesikj** [comment]
Technicky to asi nebude problém, ale je třeba to dořešit na Vaší straně.

**Comment by motyc** [comment]
Ano, vím o tom, proto mám ve "Working"
