### ISSUE TITLE
Hesláře - optimalizace výběru ze seznamu všech hesel

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#804]
Tam, kde se vybírá ze všech hesel (http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/; http://192.168.254.30:8080/admin/heslar/heslarodkaz/add/ + totéž pro edit) jsou seznamy dost k nepoužití, protože najít tam správné heslo je skoro nemožné; co by pomohlo:
-- umět v seznamu filtrovat zápisem z klávesnice
-- mít heslář rozdělený nadpisy podle toho, do kterého hesláře hesla patří (a po těchto skupinách řadit k sobě)
-- nevím co z bodu výše jde a jak snadno, případně prosím o jiné možnosti, které Django třeba nativně nabízí

**Comment by pesikj** [comment]
@jnihnat Dokážeš to prosím odhadnout?

**Comment by jnihnat** [comment]
Muzeme asi udelat i autocomplete - tohle by mohlo byt jednoduche. nebo to rozdelit do dvou inputu, jedno nazev heslare a az ten je vybraty tak sa prefiltruje druhy heslar. Podle toho k cemu se odhodlame bych to videl na 8-16H.

**Comment by motyc** [comment]
@jnihnat Ta varianta s výběrem ve dvou stupních mi přijde schůdná. Ono někdy se mohou hesla i napříč hesláři opakovat, takže je potřeba celkem jasně vědět, s čím pracuji. Na obojím by pak byl dobrý autocomplete, ať se s tím rychleji pracuje.

**Comment by jnihnat** [comment]
@motyc - Filtrace cez nazev heslare, ma byt samostatna pro podrazene a nadrazene, nebo jen jeden select platny pro oba?

**Comment by motyc** [comment]
@jnihnat Vyzkoušel jsem, chování je fajn, ale po přidání hierarchie (http://192.168.254.30:8080/admin/heslar/heslarhierarchie/add/) hlásí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7edb3b33-31aa-4ca5-93d4-58647d26ab03)

Totéž platí pro http://192.168.254.30:8080/admin/heslar/heslarodkaz/add/

Nevím, zda s tím souvisí i chyba http://192.168.254.30:8080/admin/heslar/heslardatace/add/, kde to hlásí:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/0b50dd25-ba2b-4be3-bc54-a7d7291fac94)

**Comment by jnihnat** [comment]
Oboje jde za Jirkom: https://github.com/ARUP-CAS/aiscr-webamcr/pull/1475
@pesikj mrknes na to nebo ty? ja nejak netusim proc to tam vubec mas :(

**Comment by pesikj** [comment]
@motyc @jnihnat Ano, to jde za mnou, podívám se na to.
