### ISSUE TITLE
Generování centroidu ploch

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#805]
Jak se počítá centroid pro polygony? Není tam nějaká chyba transformace či výpočtu? Působí dost posunutý oproti skutečnému středu plochy. U čtyřúhelníku bych jej čekal na průsečíků úhlopříček.

Např. zde: http://192.168.254.30:8080/arch-z/lokalita/detail/C-N0000002/dj/X-C-N0000003-D01

![image](https://user-images.githubusercontent.com/20186892/207407558-d1425fcc-936c-45c7-ab69-5f3c597a861e.png)

**Comment by motyc** [comment]
@jiri-bartos-huld Stále je to nějaké podivné. Např. zde: http://192.168.254.30:8080/arch-z/akce/detail/C-9113408A/dj/C-9113408A-D10

Místo aby se centroid zobrazoval na správném místě:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a06748dd-4693-43d8-a7e5-68f0100ea8b1)

Zobrazuje se na místě, které určitě není těžištěm geometrie:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/8f2f1330-51f1-4803-a4b7-e745582b67c6)

Je ale zajímavé, že u geometrií bez konkávních částí to asi funguje dobře.

**Comment by jiri-bartos-huld** [comment]
Podle me to co pozadujete neni centroid: https://stackoverflow.com/questions/50588009/better-centerpoint-than-centroid

**Comment by jiri-bartos-huld** [comment]
Vylepseno pro polygony:
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/1dcbe88d-4b86-495b-9801-f593209e6ddb)

Linie zustavaji stejne:
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/1a147f68-2ded-490a-92f9-5edb9e8c0cdd)

**Comment by jiri-bartos-huld** [comment]
Pripraveno na mR

**Comment by pesikj** [comment]
@jiri-bartos-huld Pokud je některý PR připravený na merge, tak ho přehoď ze stavu Draft na Ready.
