### ISSUE TITLE
Odstranění hlavní role uživatele a náhrada skupinami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#806]
Navazuje na #384 

Když je nastavena hlavní role, je zároveň potřeba, aby uživatel byl ještě v dané skupině? Pokud ano, nemělo by se to nějak svázat, tj. aby změna jednoho měnila i druhé? Možná to bude složitější a můžeme to odtud vydělit do nového issue, tuším tam ale potenciální problémy a chyby při administraci.

![image](https://user-images.githubusercontent.com/20186892/207450938-1e8d00da-22b0-4eec-adf2-5c3f142be12f.png)
![image](https://user-images.githubusercontent.com/20186892/207450727-dccb041c-d436-45f7-b9c0-490762155693.png)
![image](https://user-images.githubusercontent.com/20186892/207450813-ab02eda5-8944-4d36-b935-5b7635286764.png)

**Comment by motyc** [comment]
### Výsledek testu
- [ ] - zkusil jsem uživatele úplně vyřadit ze všech skupin (http://192.168.254.30:8080/admin/uzivatel/user/2207/change/) -> error 500

Jinak jsem nenarazil na problém.

**Comment by motyc** [comment]
@pesikj Myslím, že omylem došlo k záměně - nyní se administrátorovi automaticky nastaví i to, že je superadmin. To nebylo požadováno. Šlo jen o to, aby měl automaticky oprávění is_staff, tj. aby měl vůbec přístup do admin rozhraní. Řešení pro superadmina mělo zůstat původní, tj. že jej může uživateli zapnout jen jiný superadmin.

Jinak je to v pořádku.

**Comment by pesikj** [comment]
@motyc A aby tedy bylo ovládání konzistentní, nebylo by lepší vytvořit ještě jednu skupinu Superadministrátor?

**Comment by motyc** [comment]
Domluveno tak, že přibude skupina "Superadministrátor", která se však nebude vylučovat s ostatními základními skupinami (Badatel-Administrátor).

**Comment by motyc** [comment]
Nebudeme to dále komplikovat, dořeší se to v rámci #379 jednodušší cestou.
