### ISSUE TITLE
Ladění hlídacího psa

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#810]
Implementace proběhla bez konzultací, obsahuje řadu chyb a je uživatelsky nešikovně řešená. Bude proto udělat úpravy podle návrhů níže (nebo případně se dohodnout jinak).

**Návrh řešení**
- [x] - Huld upraví názvy aplikace + modelu tak, abychom se drželi češtiny (aplikace "notifikace_projekty", model "pes" -> tabulka "notifikace_projekty_pes")
- [x] Upravit řešení v DB:
-- zrušit řešení přes `object_id` + `content_type_id` (sloupce smazat) a nahradit je třemi sloupci `ruain_katastr`, `ruian_okres`, `ruian_kraj` (s patřičnými FK ON UPDATE CASCADE ON DELETE CASCADE) + check, že když je vyplněn jeden, zbylé dva jsou prázdné + unique constraint na kombinaci `(user_id, ruain_katastr, ruian_okres, ruian_kraj)`; tím bude zajištěna konzistence DB a není třeba to víc komplikovat
-- `watchdog_watchdog_user_id_c1145180_fk_auth_user_id` - má být ON UPDATE CASCADE ON DELETE CASCADE
- [x] - až budou zpřístupněny nové tabulky pro "cz_archeologickamapa_api_view" a vysvětleno nové řešení v DB, tak připravíme za ARÚ migraci uživatelských nastavení z původních tabulek podle potřeby
- [x] stávající řešení zadávání a zobrazení psů není moc vyhovující; jako nejlepší řešení v souladu se zbytkem aplikace bych viděl:
-- http://192.168.254.30:8080/watchdog/create/ - tuto stránku úplně zrušit
-- na http://192.168.254.30:8080/watchdog/ (nově http://192.168.254.30:8080/notifikace_projekty/) dát tři tabulky ve stylu přidávání nálezů/ostatních vedoucích/VB, tj. každou pro dílčí úroveň (kraj, okres, katastr - ten nyní úplně chybí), která se bude chovat zcela běžně jako jinde v aplikaci (ikona pro odebírání, poslední řádek umožňuje zadání nové položky)
-- žádná tabulka neumožní přidání dvou stejných hodnot
-- každá tabulka bude mít vždy jeden sloupec s položkami, který bude řazen abecedně + sloupec s ikonou pro odstraňování záznamů
-- tlačítko "Uložit" bude každou tabulku zvlášť (EDIT - původně uváděno společné, ale spíše by to asi mátlo a bude to snazší)
(tímto by se měly vyřešit i všechny ostatní dříve referované problémy v ovládání hlídacího psa z pohledu uživatele)
- [x] bude doplněno tlačítko Zpět pro návrat na správu účtu
- [x] zůstal divný cyklus, přitom email má přijít vždy hned po zápisu projektu.
https://github.com/ARUP-CAS/aiscr-webamcr/blob/ca7efb1ab357cfd27fb8b7afb186de10d08cb17c/webclient/templates/projects/emails/E-P-02.html#L5

**Správa hlídacího psa v administraci**
- [x] nejde o nový požadavek; požadavek na správu všech notifikací i přes administraci byl od počátku popsán v  https://github.com/ARUP-CAS/aiscr-webamcr/issues/384#issue-1119461023, pouze později došlo na žádost Huld k vyčlenění do: #736. Jak to v administraci řešit, se lze domluvit (nemusí to být totožné jako u správy vlastního účtu, pokud to tam stejně dělat nejde - napadá mne řešení obdobné jako u správy skupin (dva sloupce, vlevo možnosti, vpravo vybrané položky) - zde jsem otevřený nějaké rozumné dohodě.

**Comment by MaxKosta** [comment]
@motyc Prosím pěkné ne obnovovat stáři komentáři k úkolů. Nedostavám o tom notifikace. Přidejte prosím novy komentář jestli mate něco nove.

**Comment by motyc** [comment]
Přenesen související nevyřešený bod z #389, dotýkající se chyb v DB.

**Comment by motyc** [comment]
Doplněn návrh lepšího řešení v DB.

**Comment by pesikj** [comment]
@motyc 

> -- zrušit řešení přes object_id + content_type_id (sloupce smazat) a nahradit je třemi sloupci ruain_katastr, ruian_okres, ruian_kraj (s patřičnými FK ON UPDATE CASCADE ON DELETE CASCADE) + check, že když je vyplněn jeden, zbylé dva jsou prázdné + unique constraint na kombinaci (user_id, ruain_katastr, ruian_okres, ruian_kraj); tím bude zajištěna konzistence DB a není třeba to víc komplikovat

S tímto bodem nesouhlasím, navrhuji ponechat stávající řešení. Můžeme to probrat telefonicky, pokud byste měl zájem.

**Comment by motyc** [comment]
@pesikj Teď jsem to probírali po Zoomu s @jnihnat. Nevím, jestli jste spolu už teď mluvili. Asi to prodiskutujte spolu a pak mi případně podle potřeby zavolejte, k čemu jste došli.

**Comment by jnihnat** [comment]
@motyc nechal jsem reseni s object_id + content_type_id. Podme se pobavit jak by mohli vznikat dany sirotci, teda jak je mozne odebrat katastr/okres/kraj. Jenom pres DB? nebo jen pres Django admin? 
Nasledne bych to osetril ci uz cez DB trigger nebo Django si to taky umi osetrit.
Pokud by nevadilo klidne bych to videlil jako samostatne issue, to uz asi nebude neco co treba dosetrit ASAP. 
Dekuji

**Comment by pesikj** [comment]
@motyc Já jen doplním @jnihnat, že konzistenci databáze lze jednoduše hlídat pomocí signálů či pomocí úlohy naplánovaných s využitím cronu.

**Comment by motyc** [comment]
@jnihnat Souhlasím s vydělením do samostatného issue. Asi není problém se v daném případě spokojit s řešením, které navrhuje @pesikj.

**Comment by motyc** [comment]
@pesikj Pokud by to nevadilo, chtěl jsem to testovat najednou s #389, protože to úzce souvisí.

**Comment by pesikj** [comment]
@motyc Ok dobře.
