### ISSUE TITLE
Integrace Knihovny 3D

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#83]

**Comment by Najiva** [comment]
@motyc Tady je potreba rozhodnout zda budou modely soucasti aplikace dokument nebo budou mit svoji vlastni aplikaci. Vzhledem k tomu, ze je to ale ta sama tabulka tak bych doporucoval pridat modely3d pod dokumenty tak aby vsechny URL zacinali na /dokument

**Comment by motyc** [comment]
@Najiva Nejsem proti, jen musíme udržet oddělenou workflow a odpovídající view. Pokud je to z hlediska implementace výhodnější, určitě to tak udělej.

**Comment by Najiva** [comment]
- [ ] Dodelat filtr

**Comment by motyc** [comment]
@Najiva Zde doplněno zadání k filtraci: https://docs.google.com/spreadsheets/d/1LzGctLXR5-9MJl1rG75l6rKrJ7BvzXDGdSQ_uloyuSg/edit#gid=1624149656

**Comment by Najiva** [comment]
Pro dodelavku spoluprace jsem udelal nove issue. #114
