### ISSUE TITLE
Automatický posun stavu ext. zdroje

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#831]
Při odeslání archeologického záznamu k archivaci dojde k automatickému posunu připojených zdrojů ve stavu 1 do stavu 2` - nyní se to děje při A2 -> A3, má se to dít při A1 -> A2.

**Comment by jnihnat** [comment]
mne zmatlo teda to "odeslani k archivaci" Upravim teda na posun A1->A2

**Comment by motyc** [comment]
@jnihnat Ano, úplně chápu. Pardon.
