### ISSUE TITLE
Error 500 v aplikaci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#846]
- [x] http://192.168.254.30:8080/admin/uzivatel/user/add/ - když se pokusím vytvořit nového uživatele (https://github.com/ARUP-CAS/aiscr-webamcr/issues/737)
- [x] http://192.168.254.30:8080/arch-z/lokalita/detail/X-C-L0000001/dj/X-C-L0000001-D01 - když se pokusím uložit změny DJ
- [x] http://192.168.254.30:8080/projekt/detail/C-201227322
- [x] http://192.168.254.30:8080/dokument/model/detail/X-C-3D-202300001
- [x] http://192.168.254.30:8080/pas/detail/C-202104256-N00009

**Comment by pesikj** [comment]
@motyc

>  http://192.168.254.30:8080/arch-z/lokalita/detail/X-C-L0000001/dj/X-C-L0000001-D01 - když se pokusím uložit změny DJ

Bod se mi nepodařil nasimulovat, můžete prosím specifikovat vstup, který vám nešel uložit?

**Comment by motyc** [comment]
@pesikj Bylo to obecné, prostě nefungovala editace DJ. Nyní to ale už jde, takže pateně to souviselo s jinou chybou.
