### ISSUE TITLE
Problémy s nahráváním souborů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#849]
- [x] chybové hlášky souborů neobsahují název souboru, takže při nahrávání více souborů není jasné, kterého se hláška týká
- [x] pokud nahraji více souborů, než je k dispozici písmen v abecedě (tj. pokud vyčerpám dostupné suffixy pro názvy), soubor se patrně nenahraje, nicméně uživatel o tom nedostane žádnou informaci - viz např. http://192.168.254.30:8080/dokument/detail/C-TX-202200015

**Comment by sedmar** [comment]
@motyc Bylo někde definováno jak mají vypadat chybové stavy a jak mají být ošetřeny? Patrně, někde byl definován způsob označování nahraných souborů suffixy a možná u toho?

**Comment by motyc** [comment]
@sedmar Přesně to definováno nebylo. Ono to celé souvisí s tím, že nyní (na rozdíl od původní aplikace) jde vkládat více souborů najednou v jedné dávce. Nikoho tak nenapadlo tyto problémy postihnout v zadání. Je to na hraně, ale dám to jako enhancement.
