### ISSUE TITLE
Na obrazovkách s transakcemi doplnit tlačítka "zpět"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#86]
(doplnit seznam URL)

Někde tlačítka jsou, ale jmenují se "Zrušit" (opravit):
- [x] /projekt/navrhnout-ke-zruseni/
- [x] - http://192.168.254.24:8080/projekt/vratit/
- [x] - http://192.168.254.24:8080/historie/
- [x] - http://192.168.254.24:8080/projekt/edit/
- [x] - http://192.168.254.24:8080/oznameni/edit/
- [x] - http://192.168.254.24:8080/arch_z/zapsat/
- [x] - http://192.168.254.24:8080/upload_file/projekt/
- [x] - http://192.168.254.24:8080/arch_z/edit/
- [x] - http://192.168.254.24:8080/dokument/zapsat/
- [x] - http://192.168.254.24:8080/arch_z/pripojit/dokument/
- [x] - http://192.168.254.24:8080/dokument/edit/
- [x] - http://192.168.254.24:8080/upload_file/dokument/

**Comment by Najiva** [comment]
Doplnil jsem tlacitko zpet u projektovych transakci kde jsou formy tj.

1. zahajeni v terenu
2. ukonceni v terenu
3. navrhnout ke zruseni
4. prihlasit projekt

Dalsi transakce tlacitko zpet maji.

**Comment by motyc** [comment]
Seznam doplněn
