### ISSUE TITLE
Uživatel se registruje jako rovnou aktivní

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#874]
http://192.168.254.30:8080/admin/uzivatel/user/2218/change/ - uživatel byl rovnou zaregistrován jako aktivní; přidělená role "Badatel" nevadí, ale is_active by mělo být ve výchozím režimu false

**Comment by jnihnat** [comment]
odebrana aktivace, tedka je potrebna rucna cez admin, nebo databazy.

**Comment by motyc** [comment]
Nelze testovat. Při pokusu o registraci uživatele přišel email s chybným odkazem:
![image](https://user-images.githubusercontent.com/20186892/235217354-49e0dd04-02dd-4985-a21a-c864706c6e0d.png)

Po použití odkazu aplikace hlásí výjimku: http://192.168.254.30:8080/accounts/activate/Im1haWxAdGVzdHguY3oi:1psS75:INN365nN4wq3t7xdBYXp5tf5SR9n4PilwD-MEgH78cs/
