### ISSUE TITLE
Změna trvalého ident_cely akce

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#875]
http://192.168.254.30:8080/arch-z/akce/detail/M-9000074A akci se pouhými posuny stavů změnilo id z původního M-9000015A na M-9000074A. Jakmile je trvalý ident_cely (bez "X-") jednou přidělen, neměl by se už nikdy změnit (výjimka je převod akce na projektovou a naopak).

Toto platí pro všechny typy záznamů - prověřit, že se to nemůže stát i jinde (lokality, ext. zdroje, dokumenty, knihovna 3D).

**Comment by jnihnat** [comment]
Oprava udelana v #903 Presel jsem i ostatni moduly a tam jsem chybu nenasel pri opetovne archivaci.
