### ISSUE TITLE
Akce - ADB - chyba filtrace podle roku popisu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#877]
Dotazy:
http://192.168.254.30:8080/arch-z/akce/vyber?adb_roky_after=2015-01-01&adb_roky_before=2015-12-31 (podle rok popisu)
http://192.168.254.30:8080/arch-z/akce/vyber?adb_roky_after=2017-01-01&adb_roky_before=2017-12-31 (podle rok revize)
by oba měly vrátit akci:
http://192.168.254.30:8080/arch-z/akce/detail/C-9001325A/dj/C-9001325A-D01

U žádného z nich se to nestane.

**Comment by jnihnat** [comment]
@motyc do adb roku je ale mozne zadat jen rok a ne cely datum. Proto to u vas nefunguje. Ve formulari to je osetrene aby neslo zadat cely datum. Url jsem uz neosetroval. Chcete aby se teda v tomto pripade vratila na formualr chyba?

**Comment by motyc** [comment]
@jnihnat Já jsem to ale zkoušel zadáním přes formulář a jen vymazal prázdná pole z get requestu. Je ale pravda, že teď už to tam jinak zadat nejde a chová se to dobře. Měli jsme to někde zapsané bokem a asi jste to opravil v mezičase. Issue je v pořádku a zavírám jej. URL není třeba ošetřovat.
