### ISSUE TITLE
Povolená volba přístupnosti záznamu je vždy pouze A-D

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#88]
Tj. nelze zadat administrátor (rozsah anonym-archivář).

**Comment by Najiva** [comment]
@motyc V tom pripade dava smysl ho odebrat z hesare pristupnosti.

**Comment by motyc** [comment]
@Najiva Ano, to máš pravdu. Klidně to pro webAMČR udělej.

**Comment by Najiva** [comment]
Done
