### ISSUE TITLE
Doplnit přepnutí do EN pro oznámení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#883]
Doplnit přepnutí do EN pro http://192.168.254.30:8080/oznameni/ (nyní jde přepnout jen přes http://192.168.254.30:8080/accounts/login/)

**Comment by jnihnat** [comment]
Odhad je 2H.

@motyc - vyhovuje prosim poloha?: Pokd jo tak to upravim aby to jeste vypadalo hezky.
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/57906106/1f8db147-cb6b-4098-96ea-eb3a6136e162)

**Comment by motyc** [comment]
@jnihnat Ano, za mne v pohodě. Díky.
