### ISSUE TITLE
Umožnit vybraným organizacím přistupovat k archivovaným dokumentům

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#884]
Cílem je umožnit archeologům NPÚ přistupovat k archivovaným dokumentům bez omezení.

Řešit doplněním parametru `organizace.cteni_dokumentu`, který archeologům (C) dané organizace umožní neomezené stahování souborů archivovaných dokumentů (tj. obejde související oprávnění).

Odpovídající element doplnit též do https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/xml_generator/definitions/amcr.xsd

**Comment by jnihnat** [comment]
@motyc tohle potrebuji lepe popsat, nejlepe o ktere pravo ide co mame v tabulce.

**Comment by motyc** [comment]
@jnihnat Budu u pocitace az vecer, tak to lovim na mobilu, ale mely by to byt:
- soubor_nahled_dokument
- soubor_stahnout_dokument
