### ISSUE TITLE
Next v URL po automatickém odhlášení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#885]
Po automatickém odhlášení nechat v URL v “next” původní adresu.

**Comment by pesikj** [comment]
Odhad od @jnihnat: 4 hodiny

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z17)
Funguje to velmi dobře až na jednu drobnost - když mám otevřených více oken a aplikace mne v nich odhlásí, tak po přihlášení v jednom okně vše funguje ok. Jakmile ale ve druhém udělám to samé, dostanu toto hlášení: 
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/b6685720-59c7-4902-9ca1-5dea22ac6445)

Lepší by bylo, aby situaci aplikace odchytila a standardně mne přesměrovala na cílovou stránku, protože přihlášený normálně již jsem.

**Comment by motyc** [comment]
@pesikj Rozumím. necháme to tedy na nové issue.
