### ISSUE TITLE
Rozlišení negativní/pozitivní zjitění

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#892]
Při filtrování pouze negativních akcí/projektů (pole Terénní zjištění na http://192.168.254.30:8080/projekt/vyber a http://192.168.254.30:8080/arch-z/akce/vyber) jsou ve výsledku např. i zapsané akce, které ještě ani nemají DJ. Aby to dávalo smysluplné výsledky, je třeba kombinovat se stavem akce. Výsledky by měly zobrazovat jen akce s alespoň jednou DJ.

**Comment by sedmar** [comment]
@motyc Toto vypadá na dopřesnění funkcionality a proto navrhuji řešit v rámci dalších objednávek.

**Comment by pesikj** [comment]
Odhad: 3 hodiny

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z16)
- [ ] Nefunguje správně. Hledání http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&has_positive_find=False vrátilo také akci http://192.168.254.30:8080/arch-z/akce/detail/X-C-9000000016A, která žádnou DJ nemá.

**Comment by motyc** [comment]
### Testování v0.3.5z18
Stále to vrací nesprávné výsledky pro jednu variantu, raději zrekapituluji celé správné chování:
- [ ] pokud hledám [pozitivní](http://192.168.254.30:8080/arch-z/akce/vyber?has_positive_find=True), mělo by to vrátit všechny akce, kde je alespoň jedna DJ pozitivní. Nyní jsem pro první případ dostal i negativní akci (např. http://192.168.254.30:8080/arch-z/akce/detail/X-C-91470542A/dj/X-C-91470542A-D01).
- [x] Pokud hledám [negativní](http://192.168.254.30:8080/arch-z/akce/vyber?has_positive_find=False), mělo by to vrátit všechny akce, kde je alespoň jedna DJ a všechny DJ jsou negativní - toto se zdá být v pořádku.

**Comment by motyc** [comment]
### Test v0.3.5z28
Nemůže být dobře, protože v DB máme 175799 akcí. Z nich 168064 má nějakou DJ. [Dotaz na pozitivní zjištění](http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=True&has_positive_find=True) vrátí 68719 výsledků, [dotaz na negativní](http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=True&has_positive_find=False) pak 101609. To v součtu dá 170328, tj. o 2264 záznamů více, než by se dalo očekávat. Obě skupiny se v principu navzájem vylučují. Počet pozitivních sedí správně, chybně je ale počet negativních, který má být 99345. Problém je v tom, že mezi negativní se v aplikaci počítají i ty záznamy, které mají negativní i pozitivní DJ. Správné a otestované dotazy dávám níže.

Dotaz na pozitivní akce:
```plpgsql
WITH pozitivni AS (
SELECT archeologicky_zaznam AS az FROM dokumentacni_jednotka WHERE negativni_jednotka = False
)
SELECT DISTINCT archeologicky_zaznam.ident_cely FROM archeologicky_zaznam
INNER JOIN pozitivni ON pozitivni.az = archeologicky_zaznam.id
WHERE archeologicky_zaznam.typ_zaznamu = 'A'
``` 

Dotaz na negativní akce:
```plpgsql
WITH pozitivni AS (
SELECT archeologicky_zaznam AS az FROM dokumentacni_jednotka WHERE negativni_jednotka = False
)
SELECT DISTINCT archeologicky_zaznam.ident_cely FROM archeologicky_zaznam
INNER JOIN dokumentacni_jednotka ON dokumentacni_jednotka.archeologicky_zaznam = archeologicky_zaznam.id
WHERE archeologicky_zaznam.typ_zaznamu = 'A'
AND not exists(SELECT pozitivni.az FROM pozitivni WHERE archeologicky_zaznam.id = pozitivni.az)
```
