### ISSUE TITLE
Nefunguje migrace pro nastavení přesnosti prostorových dat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#894]
https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/34_presnost_bodu.sql

Hlásí chyby (patrně problém dat) a migraci tak nelze aplikovat, není ale jasné co znamenají. Prosím o přípravu srozumitelného výpisu chyb nad DB `192.168.254.30/amcr_produkce_20230113`, resp. skriptu, kterým lze chyby vypsat, abychom je mohli případně v datech odstranit.

**Comment by pesikj** [comment]
@motyc Problém minimálně u části záznamů bude v nevalidní geometrii. Např. níže u pianu N-1432-231804. To samé  N-1242-312392.

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/2936aaab-1032-448b-aed1-3d4c9436c4b6)

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/1b2d73f4-7947-4634-a10d-317f567fa1e0)

Zde je trigger, který zjistí identy chybných záznamů a jejich chyby.

```sql
CREATE OR REPLACE FUNCTION process_geometry_update()
RETURNS TRIGGER AS $$
BEGIN
    -- Attempt to reduce precision and make valid
    BEGIN
        NEW.geom := ST_MakeValid(ST_ReducePrecision(NEW.geom, 0.0000001));
    EXCEPTION
        WHEN OTHERS THEN
            -- In case of any exception, log the ID, ident_cely, and error message, then keep the original geom
            RAISE NOTICE 'Failed to process geometry for ID: %, ident_cely: %, Error: %', NEW.id, NEW.ident_cely, SQLERRM;
    END;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE TRIGGER trig_process_geometry_update
BEFORE UPDATE ON public.pian
FOR EACH ROW EXECUTE FUNCTION process_geometry_update();
```

Pro výpis stačí spustit

```
UPDATE public.pian
SET geom = geom

```
