### ISSUE TITLE
Přechod z menu administrace do backendu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#90]
V menu administrace (viditelné pro admina) by měl být snadný přechod na správu uživatelů, i když bude v backendu. Správu uživatelů je třeba také rámcově zprovoznit.

Nevím, zda je možné přechod řešit i bez další nutnosti přihlášení, ale bylo by to fajn.

**Comment by Najiva** [comment]
Prihlaseni na url /admin je stejne jako na dalsi URL. 

Do skriptu na import testovacich uzivatelu jsem pridal josef_admin@example.com co je SUPERUSER tj. ma pristup do /admin sekce. Heslo ma stejne jako dalsi testovaci uzivatele. Kdyz chces pridam link na administraci uzivatelu (/admin/uzivatel/user/)  primo do menu v aplikaci.

**Comment by Najiva** [comment]
![admin](https://user-images.githubusercontent.com/26173315/121040111-efb9c480-c7b1-11eb-9c2a-7461d542580d.PNG)

**Comment by motyc** [comment]
@Najiva A šlo by prosím správu uživatelů aktivovat pro novak@arup.cas.cz? Do administrace se dostanu, ale mám to úplně prázdné.

Ad menu - ano, takto jsem to myslel; jen k existující volbě napojit tu adresu.
Jinak potvrzuji, že sdílené přihlášení funguje. Díky.
