### ISSUE TITLE
V záhlaví stránky zobrazovat také organizaci uživatele

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#91]

**Comment by Najiva** [comment]
![organizace](https://user-images.githubusercontent.com/26173315/121040907-930ad980-c7b2-11eb-9158-60611b6ac406.PNG)

**Comment by Najiva** [comment]
@pkudela Je to tam. Staci to nastylovat.

**Comment by motyc** [comment]
Stylovat není co, za mne ok.
