### ISSUE TITLE
Dokumentace readthedocs.io

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#911]
Zalozit automaticky system generovani dokumentace s vyuzitim readthedocs.io

- zalozeni adresare docs v repozitari
- vytvoreni uctu na readthedocs.io
- konfigurace build systemu dokumentace
- vlozeni dokumentace do casti kodu, ktere ilustruje jak v budoucnu dokumentaci rozvijet, dokumentace modulu projekt
- zalozit dokumentaci pro nezdrojovou cast projektu (vytvoreni dedikovanych souboru dokumentace v adresari docs/ (popis nasazovani aplikace)

**Comment by jnihnat** [comment]
@motyc dotaz k dokumentaci, chceme ji mit v cestine nebo anglictine?

**Comment by motyc** [comment]
@jnihnat Držme se češtiny, protože jinak bychom si vnesli hrozný zmatek do pojmů. Časem můžeme uvažovat o překladu, ale zatím to nekomplikujme. Všechny ostatní materiály jsou stejně v češtině.

**Comment by jnihnat** [comment]
dokumentace vytvorena na strance: https://aiscr-webamcr.readthedocs.io/cs/latest/
postupne dokumentovan kod, z ktereho se zbuldi automaticka dokumentace podle komentaru.
cast dokumentace je taky popis nasazovani a dalsi.

ps. momentalne nefunguje build, protoze je tam chyba v kodu, zalozena oprava #942 
ps2. build zatim poustim rucne, protoze da se delat automaticky po merge do dev, ale to tedka dela Jirka spis najednou par mergu a to by spustilo vice buildu najednou co neni chtene. Musime jeste doresit interne jak ten build dokumentace spoustet.

**Comment by sedmar** [comment]
@motyc, můžete uvést, kterou licenci, jste chtěl zmínit v copyright části?

**Comment by motyc** [comment]
@sedmar Zrovna jsem poslal mail... Je to: https://creativecommons.org/licenses/by/4.0/deed.cs

**Comment by jnihnat** [comment]
@motyc pridal jsem vas pak do maintaineru readthedocs. Prosim kouknete pak na tenhle navod:
https://docs.readthedocs.io/en/stable/guides/git-integrations.html
pro pridani integrace s githubem abychom mohli nastavit automaticke generovani po vytvoreni noveho tagu. Ja na to nemam prava v githubu.

**Comment by motyc** [comment]
@jnihnat Nastaveno podle návodu. Vrátilo 200, zdá se, že funguje.
