### ISSUE TITLE
Vytvoreni testovaci metodiky pro regresni testovani

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#914]
- Vytvorit ramec pro automatické testovaní aplikace.
- Zaclenit tyto automaticke testy do CI
- Vytvorit pocatecni sady testovacich scenaru (ilustrujicich pristup k vytvareni testu)

**Comment by motyc** [comment]
@sedmar Zde jsou rozpracované příklady scénářů. Zatím je to velmi pracovní verze, ale kolegové na tom mohou pokračovat, jakmile se domluvíme na vhodné formě: https://drive.google.com/drive/folders/1C2JZYHp9kkEH6Iv2qkptizjansyOttCG

**Comment by pesikj** [comment]
Implementované scénáře jsou popsané zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/TESTOVACI_SCENARE.md

Testování je možné spustit pomocí terminálu a příkazu
`docker exec HASH_KONTEJNERU python3 manage.py test --settings=webclient.settings.dev`
