### ISSUE TITLE
Ladeni vykonu aplikace

### ISSUE THREAD

**Issue by sedmar** [ARUP-CAS/aiscr-webamcr#915]
Jako uzivatel aplikace potrebuji responzivni aplikaci, kde je minimalizovana odezva i pri vyvovalani vypocetne narocnych operaci. 
Pozn. Toto lze konfiguraci aplikacniho serveru a ladenim jeho parametru pro optimalni odezvu.

**Comment by motyc** [comment]
Sloučeno s existujícím #563, kde již jsou i některé konkrétní výsledky testů.
