### ISSUE TITLE
Opravit nestandardní způsoby nakládání se souřadnicemi

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#920]
Souřadnice SJTSK jsou často pojímány v aplikaci chybně; je třeba pracovat v rámci definovaných standardů jak v aplikaci, tak v DB:
- u samostatných nálezů se používá EPSG 5513 místo 5514 (musí se to nějak překládat mezi aplikací a DB, protože na formuláři se zobrazují souřadnice v mínusových hodnotách a ve správném pořadí)
- u výškových bodů a PIAN jde o nějaký hybrid mezi tím, kdy se pouze souřadnice vynásobí "-1", ale do DB se neuloží opačně, takže to neodpovídá ani jednomu EPSG
- správné nastavení je vidět v https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/44c_DN_ruzne_opravy.sql

**Comment by jiri-bartos-huld** [comment]
@motyc Jedna vec je oprava na urovni aplikace, ale bude potreba vytvorit migracni task. Prosim vytvorte ho.

**Comment by motyc** [comment]
@jiri-bartos-huld Nevím, co myslíte "migračním taskem". Při migracích ze staré DB jsem data kontroloval a ve skutečnosti je to tak, že původní data všechna potřebná pravidla splňují. Problém vzniká až na úrovni dat, která nově generuje Django.

**Comment by motyc** [comment]
@jiri-bartos-huld Prosím jen o kontrolu i u `pian.geom_sjtsk`. Mám tušení, že mohou být problémy všude tam, kde by mělo být 5514

**Comment by motyc** [comment]
@jiri-bartos-huld Nevím, zda jste ve druhém budě nepřehlédl, že problem je i u `pian.geom_sjtsk`
