### ISSUE TITLE
Označování verzí

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#93]
Jak bude fungovat označení verzí? Měli bychom do budoucna (od release 1.0.0 dále) mít skutečné changelogy ke každé verzi... Verze ve vývoji by měla být asi 0.x.x

Nebo jak se s tím nyní pracuje?

**Comment by Najiva** [comment]
Tohle bych nechal az bude SW na produkci. Do te doby je verze dana commitem.

**Comment by motyc** [comment]
Ok, zatím tedy neřešme.
