### ISSUE TITLE
Autentizační služba

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#934]
Zejména z důvodu využití v Digitálním archivu a v API potřebujeme umožnit autentizaci uživatelů na základě zadání uživatelského jména a hesla. V praxi může asi fungovat jako HTTPS GET request (případně navrhnout jiné vhodné řešení), který v odpovědi vrátí údaje o uživateli ve formátu jako se ukládá do Fedory (#365), tj. tohoto issue se odpověď negeneruje, pouze se předá odpovídající soubor metadata.xml z Fedory:

XSD definice:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/73b8d9383317bf37aa6b04857f594d047aeb7acc/webclient/xml_generator/definitions/amcr.xsd#L213

Příklad odpovědi:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/26d0d1780b42c22f6b5dc554b4d9f1a39f1f5cf1/webclient/xml_generator/definitions/metadata.xml#L447

Výsledná implementace viz: https://github.com/ARUP-CAS/aiscr-webamcr/issues/934#issuecomment-1563887690

**Comment by jnihnat** [comment]
Pridavam postman kolekciu na otestovani (https://www.postman.com/)
[Web-AMCR.postman_collection.json.zip](https://github.com/ARUP-CAS/aiscr-webamcr/files/11572295/Web-AMCR.postman_collection.json.zip)
potreba pridat amcr_url do global variables. 
upravit pak email a heslo v Ziskej token
poslat request - vrati se token s kterym je mozne volat API
poslat request Uzivatel info. (token se automaticky doplnuje v ramci scriptu v postmanovi)

**Comment by motyc** [comment]
@jnihnat Předpokládám, že je třeba počkat na novou verzi aplikace... Nyní vrací 404.

**Comment by jnihnat** [comment]
ano presne tak, az se #987 mergne a nasadi.

**Comment by motyc** [comment]
@jnihnat Potvrzuji funkčnost. Stačí tak doplnit podání správné odpovědi podle #365 a bude to ok.

**Comment by pesikj** [comment]
@motyc Nyní je používána definice z Fedory, prosím o test.

**Comment by motyc** [comment]
@pesikj Aktuálně mi postman vrací na POST dotaz token (to je ok), ale na následující GET vrací jen slovo "detail"

**Comment by pesikj** [comment]
@motyc Pošlete mi prosím request, který používáte k testování.

**Comment by motyc** [comment]
```
curl --location 'http://192.168.254.30:8080/api/uzivatel-info/' \
--header 'Authorization: Bearer [tokent]'
```

Ještě mne napadá - jaká je platnost tokenu? Asi by měla být nějak omezena v čase (např. 1 hod s možností obnovení po zavolání), protože nyní tam jsou stejné tokeny od prvního vygenerování, což není úplně bezpečné... (http://192.168.254.30:8080/admin/authtoken/tokenproxy/)

**Comment by jnihnat** [comment]
@motyc  a @pesikj pridana validace na stary tokenu v #1091 (tedka tyden nastavitelne v settings)

**Comment by motyc** [comment]
V pořádku, zavírám.
