### ISSUE TITLE
Ladění ../oznameni

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#94]
- [x] pokud zadám další katastry, při přechodu na krok 2 hodí error 500
- [x] v mapě chybí některé funkcionality (volba podkladových vrstev, fullscreen, vyhledání místního jména)
- [x] v kroku 2 se zobrazuje toto pokud není další katastr:
![image](https://user-images.githubusercontent.com/20186892/120848881-a846f480-c575-11eb-83a6-b41600154c71.png)

- [x] opravit formát plánovaného zahájení podle obecné konvence pro formuláře: DD.MM.RRRR-DD.MM.RRRR (bez závorek)
- [x] v plánovaném zahájení zakázat našeptávání prohlížeče
- [x] telefon ponechat bez složitých regulárních výrazů (povolit číslice a znak +)
- [x] povolené typy souborů pro upload projektové dokumentace rozšířit na (nikoli case-sensitive): RTF, JPG, JPEG, TIF, TIFF, XLS, XLSX, CSV, DOC, DOCX, TXT, PDF, PDFA, PNG, ZIP, RAR, ODT, ODS, 7z, SVG
- [x] pokud soubor přesáhne maximální povolenou velikost, objeví se neparsovaná chybová hláška:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.7</center>
</body>
</html>
```

**Comment by Najiva** [comment]
@motyc pro funkcionalitu vyhledavani a fullscreen prosim nove issue

**Comment by motyc** [comment]
@motyc Navrhuji počkat na nasazení nové verze od @jiri-bartos-huld. Pak otestuji mapu všude a udělám k tomu dílčí issue.

**Comment by pesikj** [comment]
@jnihnat Podívej se prosím na úkoly 6-8.

**Comment by jnihnat** [comment]
ad6 - upravene v #121 
ad7 - upravene v #98 
ad8 - upravene v #98
