### ISSUE TITLE
PAS - zarovnání mapy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#945]
Mapa nově nesahá až marginu boxu, ale je z nějakého důvodu menší:
![image](https://user-images.githubusercontent.com/20186892/235207050-7f064110-70a7-4be5-944f-50e53b00824b.png)

**Comment by jiri-bartos-huld** [comment]
Opraveno, pripraveno na MR
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/7ce43e1e-9f20-453b-a477-78bc46d1fb2e)

**Comment by motyc** [comment]
@jiri-bartos-huld Nyní mapa naopak přesahuje až přes okraj formuláře (test v Chrome):
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a5abd527-8e15-4955-857f-bf98ab50c4fe)

**Comment by jnihnat** [comment]
oprava v #1155
