### ISSUE TITLE
Nefunguje správa uživatele v administraci

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#947]
http://192.168.254.30:8080/admin/uzivatel/user/1898/change/?_changelist_filters=q%3Dnov%25C3%25A1k - vrátí výjimku

**Comment by jnihnat** [comment]
nebyl pusten script na prejmenovani tabulek. Pustil jsem a mnelo by fungovat. Dodelal jsem akurat jeste preklady.
