### ISSUE TITLE
U katastrů ve formulářích vždy zobrazovat v závorce i okres

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#95]
Např.: MALÁ STRANA (HLAVNÍ MĚSTO PRAHA)

**Comment by motyc** [comment]
Opomenuto v poli "Další katastry" při zobrazení (při zápisu je to ok):
- [ ] http://192.168.254.30:8080/projekt/detail/
- [ ] http://192.168.254.30:8080/oznameni/ - krok 2
- [ ] http://192.168.254.30:8080/arch_z/detail/

**Comment by jnihnat** [comment]
upravene na miestach z komentara.
