### ISSUE TITLE
Vyřešit proces průběžné aktualizace statických knihoven a kontejnerů s knihovnami

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#973]
Souvisí s bodem 4.3 a 4.4 bezpečnostní zprávy (#918).

Je třeba dohodnout postup, jak budou knihovny udržovány aktuální - nastavit monitoring a způsob reakce při vydání nových verzí.

Viz také: https://scout.docker.com/reports/org/aiscr/overview

**Comment by motyc** [comment]
Aktualizace bude probíhat ručně při vydávání nových verzí.

**Comment by motyc** [comment]
@pesikj @vojtakus @jhavrlant Nově jsem doplnil workflow https://github.com/ARUP-CAS/aiscr-webamcr/actions/workflows/docker_scout.yml, která se volá na každý PR a pomocí Docker Scout porovná zranitelnosti posledních zveřejněných kontejnerů z Docker Hub s výsledky na základě PR. Výstupy se pak vloží do PR jako komentáře - příklad viz zde: https://github.com/ARUP-CAS/aiscr-webamcr/pull/2033

Pokud uděláte merge hned po vytvoření PR, workflow selže (což v principu nevadí - asi to není třeba nechat proběhnout pro každý PR). Každopádně díky tomu jednou za čas snadno uvidíme, jak to vypadá se zranitelnostmi knihoven, aniž by někdo musel cíleně sledovat Docker Hub.

**Comment by motyc** [comment]
K dořešení:
- [ ] @jhavrlant - aktualizace podle výsledků Docker Scout (zejména Ubuntu, Debian, Alpine, postgis)
- [ ] Domluvit se na vhodné nastavení pro součásti monitoringu - něco je fixně, něco naopak bez specifikace verze:
-- grafana/grafana-enterprise:8.2.0
-- prom/prometheus
-- docker.elastic.co/logstash/logstash:8.7.0
-- docker.elastic.co/elasticsearch/elasticsearch:8.7.0
-- docker.elastic.co/kibana/kibana:8.7.0
-- selenium/standalone-firefox
-- gcr.io/cadvisor/cadvisor:v0.47.2
-- quay.io/prometheuscommunity/postgres-exporter
-- eeacms/rsync:latest

**Comment by jhavrlant** [comment]
Leaflet používáme aktuální 1.9.4.

**Comment by motyc** [comment]
@jhavrlant Jestli to tak je už déle, je to chybně v dokumentaci a je třeba ji opravit: https://aiscr-webamcr.readthedocs.io/cs/latest/knihovny_read_only.html#knihovny-vkladane-jako-staticke-soubory

**Comment by motyc** [comment]
@jhavrlant Musí tam být nějaká chyba, protože se to nezobrazuje v https://aiscr-webamcr.readthedocs.io/cs/latest/knihovny_read_only.html (build přitom prošel po PR dobře).

**Comment by jhavrlant** [comment]
@motyc Opraví se to po spuštění New version.
