### ISSUE TITLE
Kontrola typu souboru podle obsahu

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#974]
Souvisí s bodem 4.9 bezpečnostní zprávy (#918).

Je třeba zajistit kontrolu mime-type uploadovaných soborů na základě skutečného obsahu souboru, nikoli jen na základě přípony.

Viz např.:
https://stackoverflow.com/questions/43580/how-to-find-the-mime-type-of-a-file-in-python
https://www.tutorialspoint.com/How-to-find-the-mime-type-of-a-file-in-Python

**Comment by pesikj** [comment]
@motyc Jak má být řešení případ, kdy mime neodpovídá?

- U podporovaných typů bych navrhoval upravit příponu souboru a informovat o tom uživatele.
- U ostatních (např. exe) navrhuji soubor ihned smazat a vypsat chybu.

**Comment by motyc** [comment]
@pesikj Plný souhlas, děkuji.

**Comment by motyc** [comment]
Test blokován #1207

**Comment by motyc** [comment]
### Test v0.4.33
- [ ] Nejde nahrát soubory CSV (bez specifikace chyby) - test pro http://192.168.254.30:8080/soubor/nahrat/projekt/M-202204674 a soubor [tabulka.csv](https://github.com/ARUP-CAS/aiscr-webamcr/files/14935417/tabulka.csv)
- [ ] Dal jsem nahrát soubor `pdf_jpg.jpg`, který měl chybnou příponu (správně `pdf_jpg.pdf`). Souboru se automaticky nezměnila jen přípona, ale i součást názvu, tj. výsledek byl chybně `pdf_pdf.pdf`. Je třeba upravit způsob přejmenování, aby ovlivňoval jen příponu.

Jinak vše v pořádku.
