### ISSUE TITLE
Ladění ../projekt/list

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#99]
- [x] ve filtraci, pole Stavy - "Nevržen ke zrušení" -> "Navržen ke zrušení" (asi bude obecně v aplikaci špatně konstanta)
- [x] ve filtraci Stavy záznamů akcí - Zapsán, Odeslán, Archivován -> Zapsána, Odeslána, Archivována (asi bude obecně v aplikaci špatně konstanta)
- [x] ve filtraci - výběr podle historie - zcela chybně řešeno (alespoň vložit správná pole podle https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094 (je s tím spojena i komplikovanější funkcionalita, kterou vyřešíme později)
- [x] ve filtraci neúplně implementována některá pole - Hlavní typy akce - výběr je skutečně pouze podle pole Hlavní typ, ale měl by zahrnout i Vedlejší typ (totéž platí i pro vyhledávání podle Katastr projektu, Katastr akce a Vedoucí akce, Organizace akce - musí zahrnovat vyhledávání v polích Další katastr a Další vedoucí a jejich organizace; stejně tak pro související hledání v okrese a krajích) - pro lepší pochopitelnost by bylo vhodné i popisky sladit s https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094
- [x] volba "Archivovat projekty" nemá mít nativně filtr podle organizace (pouze podle stavu)
- [x] část polí stále chybí (viz červeně v https://docs.google.com/spreadsheets/d/12vYM2HgqefWvgQe8AQoDTun4nWfkATqgLMKfyVJxCIM/edit#gid=722556094)

-------------------------------------------------------
Podzim
- [ ] názvy sloupců v jednotném čísle (ještě upřesní ARÚ)
- [ ] JSON podávat formátovaný, nikoli jako spojitý řádek textu

**Comment by jnihnat** [comment]
@motyc - Pro reseni issue som si zazadal pristup do google docs, prosim o schvaleni.

**Comment by motyc** [comment]
@jnihnat Pošlete mi prosím svůj Google účet, přidám Vás tam. Vlastníkem dokumentu je kolega, takže mail došel jemu, ale je bohužel na dovolené.

**Comment by jnihnat** [comment]
@motyc email: jnihnat@gmail.com

**Comment by motyc** [comment]
@jnihnat K dokumentům byste již měl mít přístup.

**Comment by jnihnat** [comment]
@motyc - Dokoncujem upravu vo filtroch a vsimol som si, ze u 2 datumovych: planovane_zahajeni a termin_odevzdani se nastavuje pokud neni vyplneno tak horni hranice na dnes. Je to takto spravne obmedzene, alebo pokial to user nevyplnil spravat sa k tomu ze tam vrchni hranice neni?

**Comment by jnihnat** [comment]
@motyc  - jeste k bodu 4. akce nema Dalsiho Vedoucího akce. Teda proto se filtruje jen na hlavniho. Je to takto spravne, alebo i akce ma mit vedlejsiho vedouciho?

**Comment by motyc** [comment]
ad horní hranice pro datumy - neměla by tam být; naopak v obou případech může jít o datum v budoucnosti

ad bod 4 - zde mám obojakou odpověď - v datech ve skutečnosti další vedoucí/organizace být mohou (tabulka akce_vedouci); zatím to jen nemáme vyřešené ve formuláři a nechtěli jsme tím teď na poslední chvíli komplikovat vývoj; v principu by tam tak filtr hledat měl, jen data zatím neumíme zobrazit a spravovat ve formuláři

**Comment by jnihnat** [comment]
ad 2 - horni hranice upravena
ad 4 - pridane filtrovani i v tabulce akce_vedouci
