### ISSUE TITLE
Monitoring potřeby updatů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#992]
Navazuje na #577 

Doplnit monitoring aktuálnosti kódu s využitím funkcionality Dependabot version updates a nastavit vhodný model správy a implementace aktualizací.

**Comment by pesikj** [comment]
Dependabot nastaven.

**Comment by motyc** [comment]
@pesikj Ok, děkuji. Necháme to chvilku běžet a uvidíme, jak se to bude chovat. Vrátil jsem Vám práva na maintain, v případě potřeby je zase dočasně přidělím. Issue jsem posunul k akceptaci.

**Comment by pesikj** [comment]
Vypadá to, že to nefunguje. Z dokumentace mi to nebylo jasné, je to tam popsáno docela stručně. Nicméně po sjednocení definice závislostí je možné je přesunout výše, což nastavení zjenoduší.

**Comment by pesikj** [comment]
@motyc Hotovo, smazal jsem původní `crontests.txt`. Zítra zkontroluji, zda to takto stačí nebo zda bude potřeba změna konfigurace.

**Comment by motyc** [comment]
@pesikj Tuším, že to bude muset být definováno jako `directory: "/webclient/"`, ale spíše odhaduji.

**Comment by motyc** [comment]
@pesikj Tak to funguje. Diky a zaviram.
