### ISSUE TITLE
Snazší cesta ke správě vlastních záznamů organizací

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#994]
- [x] Jako základ do všech nabídek "Vybrat ..." přidat do části s filtrací podle historie možnost filtrace podle organizace uživatele.

Do menu dílčích modulů pro uživatele C+ (archeolog a výše) doplnit položky, které umožní snadno filtrovat záznamy podle organizace uživatele. Jde o obdobu menu "Naše projekty":
- [x] http://192.168.254.30:8080/arch-z/akce - "Naše akce": `AZ01.uzivatel.organizace = uzivatel.organizace` AND `zahrnout_projektove=False`
- [x] http://192.168.254.30:8080/arch-z/lokalita/ - "Naše lokality": `AZ01.uzivatel.organizace = uzivatel.organizace`
- [x] http://192.168.254.30:8080/pas/ - "Naše nálezy": `SN.projekt.organizace = uzivatel.organizace`
- [x] http://192.168.254.30:8080/dokument/model - "Naše modely": `D01.uzivatel.organizace = uzivatel.organizace`
- [x] http://192.168.254.30:8080/dokument/ - "Naše dokumenty": `D01.uzivatel.organizace = uzivatel.organizace`
- [x] http://192.168.254.30:8080/ext-zdroj/ - "Naše zdroje": `EZ01.uzivatel.organizace = uzivatel.organizace`

Řazeny budou vždy hned za položku "Moje" v témže modulu.

**Comment by pesikj** [comment]
Odhad: 6 hodin.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z16)

- [ ] Není implementováno: Jako základ do všech nabídek "Vybrat ..." přidat do části s filtrací podle historie možnost filtrace podle organizace uživatele.
- [ ] Do menu dílčích modulů pro uživatele C+ (archeolog a výše) - toto není nastaveno (zobrazuje se i badateli (B)
- [ ] [Naše akce](http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_zapsal_uzivatel_organizace=315755&sort=stav&sort=ident_cely) a [Naše lokality](http://192.168.254.30:8080/arch-z/lokalita/vyber?historie_typ_zmeny=AZ01&historie_zapsal_uzivatel_organizace=315755&sort=stav&sort=ident_cely) skončí na time-out (504)
- [ ] http://192.168.254.30:8080/dokument/model/ - chybí popisky při najetí na kartu Naše modely

Důsledně to však nejde testovat kvůli chybě v #1145

**Comment by pesikj** [comment]
Kontrolní dotaz pro arch_z

```sql
SELECT distinct a.ident_cely, org.nazev
	FROM public.organizace as org
	INNER join auth_user as u on u.organizace = org.id
	INNER join historie as h on h.uzivatel = u.id
	INNER join historie_vazby as hv on hv.id = h.vazba
	INNER join archeologicky_zaznam as a on a.historie = hv.id
	WHERE org.id in (315810, 315785, 943015) AND h.typ_zmeny = 'AZ01';
```

**Comment by motyc** [comment]
### Testování v0.3.5z18
Už je to lepší, ale jsou tam nedorozumění či chyby v implementaci:
- [ ] Pole organizace ve filtraci podle historie by nemělo být explicitně spojeno se stavem 1, ale mělo by jít kombinovat stejně, jako jakékoli jiné pole v této části filtračního formuláře. Např. filtraci "Naše akce" by tak měla odpovídat URL: http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_typ_zmeny=AZ01&historie_zapsal_uzivatel_organizace=315755 a URL http://192.168.254.30:8080/arch-z/akce/vyber?zahrnout_projektove=False&historie_zapsal_uzivatel_organizace=315755 by měla vracet výsledky pro všechny případy, kdy se v rámci historie záznamu vyskytuje uživatel dané organizace bez ohledu na stav.
- [ ] V kontextu předchozího bodu by se pole mělo objevit i ve formuláři u projektu (nicméně nastavení volby "Naše projekty" to v daném případě neovlivní).
- [ ] V PAS je nastavení nabídky "Naše nálezy" chybné, má se odvíjet od `SN.projekt.organizace = uzivatel.organizace`, nikoli od historie nálezu.

Pokud by to bylo takto nejasné, klidně se ještě prosím doptejte či mi zavolejte.

**Comment by motyc** [comment]
@pesikj Zde je to původní issue k historii: https://github.com/ARUP-CAS/aiscr-webamcr/issues/325

**Comment by motyc** [comment]
### Test v0.3.5z28
- [ ] Stále se buď nechápeme, nebo implementaci nikdo před nasazením netestuje. Pokud zadám [tento dotaz](http://192.168.254.30:8080/ext-zdroj/vyber?ident_cely=BIB-0000030&historie_typ_zmeny=EZ01&historie_uzivatel_organizace=315755), nemělo by se najít nic a přesto mi to záznam vrátí (záznam bych měl dostat např. při [této kombinaci](http://192.168.254.30:8080/ext-zdroj/vyber?ident_cely=BIB-0000030&historie_typ_zmeny=EZ23&historie_uzivatel_organizace=315755) stejných polí). Přitom pokud to kombinuji přímo přes uživatele [tímto dotazem](http://192.168.254.30:8080/ext-zdroj/vyber?ident_cely=BIB-0000030&historie_typ_zmeny=EZ01&historie_uzivatel=3422), vše funguje dobře, takže řešení to mít musí (to je ta původní část správně nasazená v rámci #325). Platí to pro všechny typy záznamů.
- [ ] Po kliknutí na [Naše záznamy](http://192.168.254.30:8080/pas/vyber?projekt_organizace=315755&sort=stav&sort=ident_cely) v PAS se v levém menu rozbalují Projekty místo PAS
- [ ] V PAS je chybně propojeno pole Organizace uživatele ve filtraci podle historie na `projekt_organizace`, místo na `historie_uzivatel_organizace`. Údaj `projekt_organizace` se má používat jen pro Naše záznamy, kde je to teď dobře.
