### ISSUE TITLE
Upravit datové vrstvy - PAS

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#995]
Upravit datové vrstvy pro mapu v PAS (**tučně** - defaultně zapnuté; čísla uvádí pořadí vrstev)
- Při souběžném zapnutí vrstev 2 a 3 tvořit heatmapu jako sloučenou verzi, která se bude vytvářet z obou vrstev.
- V případě heatmapy NENÍ třeba zohledňovat přístupnost a vlastnictví u žádné z vrstev, protože informace je natolik generalizovaná, že stejně nikomu nic neřekne. Clustering přístupnost a vlastnictví zohledňovat MUSÍ.
- [ ] 1- AMČR Zájmové body - přejmenovat -> **Lokalizace nálezu** (aktivní vrstva)
- [ ] 2 - Samostatné nálezy - definice a chování viz #300 (lze sdílet)
- [ ] 3 - PIAN - definice a chování viz #300 (lze sdílet)

**Comment by jiri-bartos-huld** [comment]
Naceneno je jen rozdil od #300, tj. naceneni plati, kdyz budou oba tasky delany dohromady

**Comment by jiri-bartos-huld** [comment]
@motyc Neni to zde primo receno, ale clustering rozumim, ze take bude spolecny pro vrstvy 2+3, stejne tak u #300

**Comment by motyc** [comment]
@jiri-bartos-huld Ano, je to tak.

**Comment by jiri-bartos-huld** [comment]
@jnihnat prosim pristupnost a vlastnictvi

**Comment by jiri-bartos-huld** [comment]
@pesikj  @jnihnat  Toto je pripraveno k nasazeni 31.10.2023

**Comment by motyc** [comment]
### Testování v0.3.5z18
Vůbec nefunguje. Nejde přidávat a upravovat lokalizace (bod v mapě se vůbec nezobrazí). Vrstvy PIAN a Samostatné nálezy nic nezobrazují.

**Comment by jiri-bartos-huld** [comment]
1./Melo by dojit k prekmenovani popisku souradnic: spravne poradi je sirka, delka
spravne by melo byt:   "Sirka (N/X)" a "Delka (E/Y)"
dnes je "Delka (E/X)" a "Sirka (N/Y)"

**Comment by motyc** [comment]
### Test v0.3.5z29
- [ ] Body ve vrstvě Samostatné nálezy mají chybnou ikonu (3D místo PAS)
- [ ] Když zapnu vrstvu PIAN, tak naskočí až po pohybu mapou, ne hned po zapnutí vrstvy.
- [ ] Stejný problém s popiskem bodu nálezu jako je v https://github.com/ARUP-CAS/aiscr-webamcr/issues/299#issuecomment-1815531966
